### ISSUE TITLE
Oracle and Other RDBMS Status?

### ISSUE THREAD

**Issue by dicgf8** [magento/magento2#100]
What is the status on multiple RDBMS' to be included in version 2?

**Comment by VDuda** [comment]
Was hoping this issue could be re-addressed. I'd love to help in progressing the abstraction for Multiple RDBMS'.

**Comment by alankent** [comment]
High confidence prediction: wont be done for Magento 2.0. We are looking at the right strategic direction for the database layer, with a low probability of significant change here in the 2.0 time frame. That is, we would like to share the direction we plan to head but it *probably* wont be implemented until after 2.0.

On top of that, we use MySQL specific features which would have to be ported to other database systems. Right now Oracle is not on the Magento roadmap. If we pick up an ORM tool such as Doctrine, that *might* provide a way forward for greater database abstraction.

There investigation going on internally about what is the long term strategy, but low probability any significant change will come in the Magento 2.0 timeframe.

**Comment by theroch** [comment]
Here is an comment from another thread:
"We investigated moving to Doctrine, but it was too much work for the Magento 2.0.0 release. We may however do it in 2.1, 2.2, 3.0, or... (no commitment yet). When we do get to it, we may also change our mind whether to use ZF1, ZF2, Doctrine etc based on new information available."

[source]( http://magento.stackexchange.com/questions/37024/why-arent-magento-developers-using-zend-framework-2-for-magento-2)

**Comment by magento-engcom-team** [comment]
Hi @dicgf8. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#102 by @dmytro-ch in 2.3-develop branch
Related commit(s):
 - [9116d8259244ac3b03dec76f39aa56e2d478998f](https://github.com/magento/magento2/commit/9116d8259244ac3b03dec76f39aa56e2d478998f)

The fix will be available with the upcoming 2.3.0 release.

**Comment by VladimirZaets** [comment]
Hi @dicgf8. Thank you for your report. 
The issue has been fixed in magento/magento2#25940 by @sedonik in 2.4-develop branch
Related commit(s):
 - [dc8821dc2e297c1b73064ea49c1c4e7253b7e84f](https://github.com/magento/magento2/commit/dc8821dc2e297c1b73064ea49c1c4e7253b7e84f)
 - [f305a84472fc0222147844ffa83542c01cd1c023](https://github.com/magento/magento2/commit/f305a84472fc0222147844ffa83542c01cd1c023)
 - [345ece3f5277c1add6a1fd31cf8c830b3615c96f](https://github.com/magento/magento2/commit/345ece3f5277c1add6a1fd31cf8c830b3615c96f)
 - [b1e518ca649a862abca2856db0c99d385ba964a3](https://github.com/magento/magento2/commit/b1e518ca649a862abca2856db0c99d385ba964a3)

The fix will be available with the upcoming 2.4.0 release.

**Comment by theroch** [comment]
> The issue has been fixed in #25940 by @sedonik in 2.4-develop branch
> 
> The fix will be available with the upcoming 2.4.0 release.

I think @dicgf8 meant the support of different RDBMS like Oracle, PostgreSQL, MS-SQL etc. and not asynchronous operations. So #25940 doesn't solve his question.
