### ISSUE TITLE
Save on tax rule showing error, "priority is a required field. customer_tax_class_ids is a required field. product_tax_class_ids is a required field."

### ISSUE THREAD

**Issue by frshjb373** [magento/magento2#10012]
When saving a tax rule, the following error is displayed when trying to add additional tax rates

### Preconditions

1. Magento ver. 2.1.2

### Steps to reproduce

1. Imported many rates for each zip code.
2. Adding more tax rates to rule and saving

### Expected result

1. rates should save

### Actual result

1.
![fireshot-capture-7---ca- -ut-non-taxable-shipping-_-tax-rul_---https___dev ollydog com_admin_tax_r](https://user-images.githubusercontent.com/7178139/27393469-3b89643e-565e-11e7-8b74-6d81fe7844a9.jpg)

**Comment by AlexWorking** [comment]
Hi @frshjb373. We couldn't reproduce Your issue on the develop version which for Your case is 2.1.7. Probably it was fixed. Please let us now if You are still able to reproduce this issue on an appropriate latest version (2.1.7). Thank's for applying

**Comment by frshjb373** [comment]
I've updated to 2.1.7 and still getting same error. Additionally, we updated PHP versions to 7.0 and still experiencing.

**Comment by frshjb373** [comment]
We've determined that saving tax zone with more than 995 tax rates it will not save. Anything less than that is saving fine.

**Comment by AlexWorking** [comment]
Using concrete data (995 or more) the issue is really reproducible on the develop versions. So based on Your issue an internal ticket - MAGETWO-70147 has been created. You, @frshjb373, will be informed when the bug is fixed.

**Comment by oabreu** [comment]
Hi, did you fix this? @AlexWorking Im having the same issue adding a lot of tax rates to a tax rule , please let me know what can i do, thanks

**Comment by frshjb373** [comment]
As a temporary fix, we reduced number of tax rates by combining individual rates into ranges that contained same rates.

**Comment by oabreu** [comment]
that will be to much work, because I import them and I have around 15000, imagine if I have to reduce that to 995 manually, do you know any plugin or something that can do that for me?

**Comment by oabreu** [comment]
fixed, i just add the tax rates to the table gbtax_calculation in the database for that same rule with those same classes and thats it

**Comment by frshjb373** [comment]
@oabreu, we have an expert in excel on staff and he was able to do it pretty quickly with a few formulas.

**Comment by oabreu** [comment]
ok,but in the future u just have to add the id of the tax rate in the "gbtax_calculation" and thats it, just for u to know

**Comment by AlexWorking** [comment]
Hi. @oabreu. No fix for now yet. After the fix is made You shall be informed.

**Comment by paras0092** [comment]
you guys any solution for this  ????????

**Comment by magento-engcom-team** [comment]
@frshjb373, thank you for your report.
We've created internal ticket(s) MAGETWO-70147 to track progress on the issue.

**Comment by serhii-balko** [comment]
Hi @frshjb373 
I want to create pull request to fix the issue.
Could you share rates csv file with more that 955 rows.
Thanks

**Comment by serhii-balko** [comment]
Hi @paras0092 and @frshjb373
This issue can be temporary solved by set `max_input_vars = 2000` param in `php.ini` or `.htaccess` files.

**Comment by treii28** [comment]
Also running into this with an auto-imported tax-jar ruleset.  Any status on a fix?

**Comment by magento-engcom-team** [comment]
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Comment by magento-engcom-team** [comment]
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc
