### ISSUE TITLE
WEBAPI: create of video link by SOAP API is failing catalogProductAttributeMediaGalleryManagementV1CreateRequest

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#10019]
### Preconditions
1. Magento 2.1.7 standard

### Steps to reproduce
1.  Send attached XML to a std. magento environment , webservice is catalogProductAttributeMediaGalleryManagementV1CreateRequest
![image](https://user-images.githubusercontent.com/15381778/27427378-0ea0c390-573f-11e7-8fab-1e48d833d421.png)

### Expected result
1. The video should be assigned to the product

### Actual result
We are receiving this error: Argument 1 passed to Magento\Framework\Api\ImageContentValidator::isValid() must be an instance of Magento\Framework\Api\Data\ImageContentInterface, null given, called in C:\inetpub\STAGE\dev_magento6\vendor\magento\module-catalog\Model\Product\Gallery\GalleryManagement.php on line 53
![image](https://user-images.githubusercontent.com/15381778/27427413-298a9e60-573f-11e7-9545-2b0312036361.png)

**Comment by TomashKhamlai** [comment]
Thanks for reporting this issue. We've created internal ticket MAGETWO-70572 to address this issue. There is also a good news for you. The same problem with REST API will be fixed in Magento v2.2.0 release.

**Comment by magento-engcom-team** [comment]
@tinxit, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by ericahoekerd** [comment]
we have tested on a 2.2. enviroment and still the same error message occurs as reported in June 2017
