### ISSUE TITLE
Stock is not updating after changing the product quantity?

### ISSUE THREAD

**Issue by MoschenBayern** [magento/magento2#10313]
### Preconditions

1.  Magento 2.1.7 with PHP 7.0.21

### Steps to reproduce

1.  A product has quantity 1 and status is "in stock"
2.  Change the quantity to 0 and save

### Expected result

1. Quantity should be 0
2. Stock status should be 0

### Actual result

1. Quantity is 0
2. Stock status not change to "out of stock"

Also if we manually change the stock status to "out of stock" and click the save button, this change will not be saved. products are always on stock.

But this problem is not on each product. some products you can change the stock status without problems but at most of the products the stock status is not changed

**Comment by orlangur** [comment]
Exactly the same title as https://github.com/magento/magento2/issues/10270 but does not seem to be a duplicate :) Thanks for detailed steps here.

**Comment by magento-engcom-team** [comment]
@MoschenBayern, thank you for your report.
The issue is already fixed in 2.1.9

**Comment by JayashreeDCKAP** [comment]
@magento-engcom-team ,I am using 2.2.4, But now I am facing the same issue, it is not fixed
