### ISSUE TITLE
Category edit screen does not show "Use default value" checkboxes.

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#10351]
### Preconditions
1. Install the latest version of Magento 2.1.X

### Steps to reproduce
1.  Create multiple store views
2.  Create a new category
3.  Go to a specific storeview and edit the category

### Expected result
1. The ability to check and uncheck the "Use default value" checkbox for store view specific settings. 

### Actual result
1. No checkboxes "Use default value" are shown. These checkboxes are missing for every field with a storeview specific scope on the category screen. When you need to change a category you will have to do this for every storeview, because there is no way to let it know you want to use one value for a specific setting. 

![image](https://user-images.githubusercontent.com/1058480/28665182-1ff8b0fe-72c3-11e7-8d21-33299837603c.png)

**Comment by magento-engcom-team** [comment]
@dverkade, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by mihaifaget** [comment]
@magento-engcom-team the bug still exists in 2.2.2, at least for custom created category attributes with scope store

**Comment by real34** [comment]
I confirm, the issue can be reproduced on a 2.2.1 too.

**Comment by praveen-chelumalla** [comment]
I am also facing same issue 
![screenshot-sample-magento local-2018 05 02-12-24-38](https://user-images.githubusercontent.com/32830727/39509427-e55aff3e-4e03-11e8-917f-d7e235861d28.png)

**Comment by chedaroo** [comment]
https://github.com/magento/magento2/issues/10351#issuecomment-356560861

This issue is being tracked elsewhere https://github.com/magento/magento2/issues/13440
