### ISSUE TITLE
Magento 2.1 downloadable product upload popup error

### ISSUE THREAD

**Issue by saeohioalpha** [magento/magento2#10479]
Uploading a 9,100KB PowerPoint file for a downloadable product fails, and A popup appears that has the title "Attention" and the content is simply "true".

This was caused by the upload_max_filesize setting in PHP being 2M and attempted to upload a file larger than that limit. However, a better error message than "Attention:True" should be displayed. 

### Preconditions
1. Magento v2.1.7
2. PHP v7.0.22-2+ubuntu16.04.1+deb.sury.org+4
3. Apache/2.4.27 (Ubuntu)
4. 10.1.25-MariaDB

### Steps to reproduce
1. Upload file for downloadable product that is larger than the PHP Max Upload size

### Expected result
1. A descriptive error, or as descriptive as can be regarding the error. 

### Actual result
1. See Screenshot
![screen shot 2017-08-09 at 9 52 07 am](https://user-images.githubusercontent.com/969559/29124986-774622ae-7ce8-11e7-9fb9-3fdbffcd790e.png)

**Comment by magento-engcom-team** [comment]
@saeohioalpha thank you for your bug report.
We've created internal ticket MAGETWO-75465 to track progress on the issue.

**Comment by eswolters** [comment]
Can I pick up this ticket.

**Comment by okorshenko** [comment]
@eswolters sure. Thank you

**Comment by eswolters** [comment]
@okorshenko  issue still exists 2.2 behavior has changed, now there is no error message, and the form field is reset.

**Comment by manuelson** [comment]
Hello, can i contribute in this issue?

Thanks

**Comment by okorshenko** [comment]
Hi @eswolters thank you for research. 
Closing this issue since it is already fixed in 2.2.0

**Comment by sonal-infobeans** [comment]
Still facing the same issue(popup with title "Attention" and the content is simply "true") on Magento ver. 2.2.2 when uploading the large file which is not allowed.

**Comment by Banhawy** [comment]
This issue also exists on Magento version 2.3 every time I do a clean installation using composer.

**Comment by lewis-dan** [comment]
The issue is still there on Magento v2.3.3, getting the same error.

**Comment by romeof1980** [comment]
same problem with 2.3.4 vanilla installation. `main.DEBUG: Request validation failed for action "Magento\Downloadable\Controller\Adminhtml\Downloadable\File\Upload\Interceptor"`
