### ISSUE TITLE
form_key cookie expires immediately if cookie lifetime is set to 0

### ISSUE THREAD

**Issue by ekuusela** [magento/magento2#10527]
form_key cookie expires immediately if cookie lifetime is set to 0. This causes for example the minicart remove button to not function.

### Preconditions
Magento 2.1.8 with cookie lifetime set to 0, i.e. expire when the session ends.

### Steps to reproduce
1. Set cookie lifetime to 0 in Stores -> Configuration -> General -> Web
2. Navigate to a product page and add a product to cart
3. Wait until the page has been fully loaded. Observe with browser dev tools that form_key cookie is not present.
4. Try to remove the product using the minicart.
5. Note that product is not removed.

### Expected result
1. form_key cookie should be valid until session is closed.
2. minicart remove button should work.

### Actual result
1. form_key cookie expires upon ajax request to /banner/ajax/load/?sections
2. minicart remove button does not work.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71544

**Comment by magento-engcom-team** [comment]
@ekuusela, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
@ekuusela, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
Hi @ekuusela the issue is already fixed in 2.2.1 and will be available soon

**Comment by staradzinau** [comment]
Please, note: the issue is still reproduced on the 2.3.0, because of incorrect merge of modifications!

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nopenopenope** [comment]
I still reproduce this issue in Magento ^2.4.x
