### ISSUE TITLE
Get stock from different scope id

### ISSUE THREAD

**Issue by amcastror** [magento/magento2#10702]
This is not really a bug so close it if you want.

[Here](https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogInventory/Model/StockRegistry.php#L73), the StockRegistry ignores the $scopeId completely, so, how can I get a stock (or stockItem, stockStatus...) in a scope different from default?

``` php
    /**
     * @param int $scopeId
     * @return \Magento\CatalogInventory\Api\Data\StockInterface
     */
    public function getStock($scopeId = null)
    {
        $scopeId = $this->stockConfiguration->getDefaultScopeId();
        return $this->stockRegistryProvider->getStock($scopeId);
    }
```

Even more, [here](https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogInventory/Model/Configuration.php#L158), the Configuration class will always return 0 for getDefaultScopeId.

``` php
    /**
     * {@inheritdoc}
     */
    public function getDefaultScopeId()
    {
        // TODO: should be fixed in MAGETWO-46043
        // "0" is id of admin website, which is used in backend during save entity
        return 0;
    }
```

I am working injecting the stockRegistryInterface as it's recommended (I'm creating a Cron):

``` php
class UpdateStocks {

    /**
     * @var StockRegistryInterface
     */
    protected $stockRegistry;
    protected $objectManager;

    public function __construct(
        \Magento\Framework\ObjectManager\ObjectManager $objectManager,
        \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry,
        \dsy\Bsale\Logger\BsaleLogger $logger
    ) {
        $this->objectManager = $objectManager;
        $this->stockRegistry = $stockRegistry;
        $this->bSaleClient = new BSaleClient('c7896090d959b448c20f83e3fcd95536bde0588e');
        $this->_logger = $logger;

    }

    public function execute() {
          // Rest of the code
     }
}

```
I think I might be doing something wrong here and my code will break in the future. Thanks a lot!

**Comment by magento-engcom-team** [comment]
Hi @amcastror 
the issue should be fixed in scope of MAGETWO-46043
thank you for report

**Comment by chris-pook** [comment]
This issue of the StockRegistry immediately replacing its $scopeId parameter and the TODO in the Configuration class are still present in 2.3.3. Can this be looked in to please, seems like a fairly major issue to me?

**Comment by engcom-Charlie** [comment]
Hello @chris-pook   
Your issue for Magento inventory modules.

Please refer to the [Magento Inventory repository](https://github.com/magento/inventory/issues) with your issue, for advice or general discussion.
