### ISSUE TITLE
Duplicate customer addresses added on checkout if payment fails

### ISSUE THREAD

**Issue by dankocherga** [magento/magento2#10709]
If you add new address on checkout and then payment process fails for some reason, customer address is still saved.

### Preconditions
1. Magento 2.1.7

### Steps to reproduce
1. Go to checkout as logged in customer
2. Choose to add new address and choose "save in address book"
3. Proceed to the last step
4. Force payment method to fail somehow (throw an exception).

### Expected result
1. Order not created
2. Customer address not created (since there was an error in order processing)

### Actual result
1. Customer address is created anyway.
2. If you continue trying to submit order from the last checkout step, multiple customer addresses will be saved with the same data.

The problem appears because customer address is saved to the database before payment processing, and in case of error is not rolled back.

In [Magento\Quote\Model\QuoteManagement::submitQuote](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Quote/Model/QuoteManagement.php#L430) it calls for `_prepareCustomerQuote`, and then `$quote->addCustomerAddress`. This method [does actual save](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Quote/Model/Quote.php#L1027) in customer repository.
Later quote management class [calls](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Quote/Model/QuoteManagement.php#L488) for `$order = $this->orderManagement->place($order);` which could fail with payment error. But customer address is already in the database.

**Comment by magento-engcom-team** [comment]
@dankocherga thank you for your bug report.
We've created internal ticket MAGETWO - 75372 to track progress on the issue.

**Comment by p-bystritsky** [comment]
Issue already fixed in 2.2.X ([pull request](https://github.com/magento/magento2ce/pull/1287))

**Comment by jcconde** [comment]
Guys, it's still happening on Magento 2.2.4 and @p-bystritsky, the pull request link is broke
