### ISSUE TITLE
Webapi - Object-Array parameter does not work when using PUT

### ISSUE THREAD

**Issue by philippsander** [magento/magento2#10726]
### Preconditions
We're using Magento 2.1.7

### Steps to reproduce

We have a REST Enpoint:

    <route method="PUT" url="/V1/our-module/:sku/blacklist/:blacklist_id">
        <service class="OurVendor\OurModule\Api\BlacklistManagementInterface" method="save"/>
        <resources>
            <resource ref="Magento_Catalog::products"/>
        </resources>
    </route>

The method signature looks like this:

    /**
     * @param string $sku
     * @param \OurVendor\OurModule\Api\Data\OptionBlacklistInterface[] $blacklist
     *
     * @return \OurVendor\OurModule\Api\Data\OptionBlacklistInterface[]
     *
     * @throws \Magento\Framework\Exception\CouldNotSaveException
     * @throws \Magento\Framework\Exception\InputException
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function save($sku, array $blacklist);

### Expected result
The code is then implementation of the save function is executed. We calling the API via swagger/postman/....

### Actual result
Response contains:

    "message": "Class \\OurVendor\\OurModule\\Api\\Data\\OptionBlacklistInterface[] does not exist",

### Notes

The crucial code segments seems to bee:

1. https://github.com/magento/magento2/blob/develop/app/code/Magento/Webapi/Controller/Rest/InputParamsResolver.php#L88
1. \Magento\Framework\Reflection\MethodsMap::getMethodMapViaReflection
1. \Magento\Framework\Reflection\MethodsMap::getMethodParams

### Workaround

We currently use a plugin to fix this issue

    public function beforeGetMethodsMap(MethodsMap $subject, $interfaceName)
    {
        if (substr($interfaceName, -2) === '[]') {
            $interfaceName = substr($interfaceName, 0, -2);
        }

        return [$interfaceName];
    }

**Comment by orlangur** [comment]
There is such logic already: https://github.com/magento/magento2/blame/2.1.7/lib/internal/Magento/Framework/Reflection/TypeProcessor.php#L558

Is there a mistake in regular expression or this code is not used in case of PUT?

**Comment by philippsander** [comment]
@orlangur I can check if this code gets called, but I haven't seen it before.

I asume it's not called when using PUT

**Comment by philippsander** [comment]
They Method gets indeed called!

It will return "\OurVendor\OurModule\Api\Data\OptionBlacklistInterface[]" in line 561!

**Comment by orlangur** [comment]
Hmm, have no idea how it works for many core data interfaces then which use `\ClassName[]` notation a lot.

From 563 you can see that this method always returns such format
```
return "{$type}[]";
```

We need to try any core API consuming such parameter type in action to see the execution flow and why it works.

**Comment by magento-engcom-team** [comment]
@philippsander thank you for your bug report.
We've created internal ticket MAGETWO-75356 to track progress on the issue.

**Comment by koenner01** [comment]
I'm having the same problem when trying to use the \Magento\Framework\Webapi\ServiceOutputProcessor to process an invoice to fetch it's dataModel.

Calling:

```
$invoiceOutputData = $this->serviceOutputProcessor->process(
    $invoice,
    'Magento\Sales\Api\InvoiceRepositoryInterface',
    'get'
);
```

Will produce an exception:

`Class \Magento\Sales\Api\Data\InvoiceItemInterface[] does not exist`

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @philippsander thank you for you report, this issue has already fixed in 2.3-develop branch and available on 2.3.0 release.

**Comment by ulftietze** [comment]
Still reproducable in Magento 2.3.3 :(
``` php
/**
     * @param string $someString
     * @param ClassItems[] $items
     *
     * @return void
     * @throws NoSuchEntityException
     */
    public function execute(string $someString, array $items): void;
```

``` xml
<route url="/V1/params/:someString/items" method="POST">
        <service class="Neusta\Vendor\Api\AddItems" method="execute"/>
        <resources>
            <resource ref="anonymous" />
        </resources>
    </route>
```

If i declare as `PUT` i got an error like this: `Class ClassItems[] not found...`; if i declare as `POST` everything is fine.

**Comment by engcom-Charlie** [comment]
Hello @ulftietze 
We are not able to reproduce this issue on the latest Magento 2.3-develop(merged code from 2.3.3).

**Manual testing scenario:**
1. Create a module with api interface
(i used your code):
```
/**
     * @param string $someString
     * @param ClassItems[] $items
     *
     * @return void
     * @throws NoSuchEntityException
     */
    public function execute(string $someString, array $items): void;
```

but i change method from "POST" to "PUT"
```
<route url="/V1/params/:someString/items" method="PUT">
        <service class="Neusta\Vendor\Api\AddItems" method="execute"/>
        <resources>
            <resource ref="anonymous" />
        </resources>
    </route>
```
2. Send a request

**Actual result:**
response = void 
![image](https://user-images.githubusercontent.com/51680850/67467270-21b7fa80-f651-11e9-9b0f-f97a3340d8a6.png)

So this issue should be closed.

**Comment by sky-hub** [comment]
@engcom-Charlie , I have managed to reproduce this issue by adding a GET parameter to the API request url.
For example: `/V1/params/test/items?XDEBUG_SESSION=PHPSTORM`

**Comment by engcom-November** [comment]
Hello @sky-hub,

Thanks for the reply!

We are reopening this issue for further analysis.

Thanks

**Comment by engcom-November** [comment]
Hello @philippsander,
Thank you for report and collaboration!
Thank you @sky-hub for input!

We are able to reproduce the issue on 2.4-develop.
Please refer the screenshots below:
**The API Interface is same for both `PUT` and `POST`, and it returns void.**
<img width="1120" alt="image" src="https://github.com/magento/magento2/assets/60198231/bf304cd5-9df5-4ae2-8d4b-21e21a92b15f">

**Using `POST`.**
<img width="1132" alt="image" src="https://github.com/magento/magento2/assets/60198231/5d5cbf6d-7a4a-47d5-8dcb-6f5995195ac4">
<img width="1119" alt="image" src="https://github.com/magento/magento2/assets/60198231/7e9fe3a3-8243-4408-a678-bd35e17af05a">

**Using `PUT`.**
<img width="1130" alt="image" src="https://github.com/magento/magento2/assets/60198231/4d5ef086-b22a-49d9-a625-d5d6f154622d">
<img width="1087" alt="image" src="https://github.com/magento/magento2/assets/60198231/05b5f67c-ff73-40c4-8d28-8648e3ca9e87">

But we are unsure that this is the correct way to reproduce the issue.
Please find the attached custom module and let us know if this is the correct way to reproduce the issue.
[ApiVendor.zip](https://github.com/magento/magento2/files/12273427/ApiVendor.zip)

Thank you.

**Comment by engcom-November** [comment]
Hello @philippsander,

We have noticed that this issue has not been updated since a long time, hence closing this issue.
Feel free to reopen this issue if you need more assistance.

Thank you.
