### ISSUE TITLE
Magento 2.1.8 : Cart Rules + New Customer (Please enter a valid date) Locale AU

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#10754]
### Preconditions

1. Magento CE 2.1.8
2. PHP version: 7.0
3. Locale AU

### Steps to reproduce

Set Locale AU
1. Stores > Configuration >General > General > Locale Options
Set Default Country to Australia and Locale to AU
Step 1 Screenshot
https://prnt.sc/ggek4e

2. Admin > Account Settings > My Account > Account Information
Set Interface Locale to English Australia
Step 2 Screenshot
https://prnt.sc/ggelkj

3. Stores > Configuration >Catalog > Catalog >Date & Time Custom Options
Use JavaScript Calendar to Yes and Date Fields Order to dd/mm/yyyy
Step 3 Screenshot
https://prnt.sc/ggemrx

3. Date format working fine on frontend (dd/mm/yyyy)
Step 4 Screensho
https://prnt.sc/ggen57

DATE FORMAT NOT WORKING ON BACKEND

**Cart Price Rules**
1. Navigate to Marketing > Cart Price Rules > Add New Rule
2. Select start date 20/09/2017 with date picker
3. Select end date 28/09/2017 with date picker

Screenshot 1
If the date format is dd/mm/yyyy (29/09/2017)
https://prnt.sc/ggejfg

Screenshot 2
If the date format is mm/dd/yyyy (11/09/2017)
https://prnt.sc/ggep2u

**New Customer**
1. Add New Customer on Front-end date format is 
(dd/mm/yyyy) 20/08/1981
Step1 Screenshot
https://prnt.sc/ggeqor

2. Go to Customers > All Customers > Edit
Step2 Screenshot
https://prnt.sc/ggero2

3. Go to Customers > All Customers > Edit > Customer Information > Account Information
Date of birth field showing Account Created date
Step3 Screenshot
https://prnt.sc/ggesad

Account Created date
Step4 Screenshot
https://prnt.sc/gget53

If you tried to change
Step5 Screenshot
https://prnt.sc/ggetiw

### Expected result

**Cart Price Rules**
1. Select start date 20/09/2017 with date picker
2. Select end date 28/09/2017 with date picker

**New Customer**
1. Date of birth in list should be dd/mm/yyyy format
Step1 Screenshot
https://prnt.sc/ggero2

2. Date of birth should be original date of birth which capture from fronted (20/08/1981)
Step2 Screenshot
https://prnt.sc/gget53

### Actual result

**Cart Price Rules**
1. Navigate to Marketing > Cart Price Rules > Add New Rule
2. Select start date 20/09/2017 with date picker
3. Select end date 28/09/2017 with date picker

Screenshot 1
If the date format is dd/mm/yyyy (29/09/2017)
https://prnt.sc/ggejfg

Screenshot 2
If the date format is mm/dd/yyyy (11/09/2017)
https://prnt.sc/ggep2u

**New Customer**
1. Add New Customer on Front-end date format is 
(dd/mm/yyyy) 20/08/1981
Step1 Screenshot
https://prnt.sc/ggeqor

2. Go to Customers > All Customers > Edit
Step2 Screenshot
https://prnt.sc/ggero2

3. Go to Customers > All Customers > Edit > Customer Information > Account Information
Date of birth field showing Account Created date
Step3 Screenshot
https://prnt.sc/ggesad

Account Created date
Step4 Screenshot
https://prnt.sc/gget53

If you tried to change
Step5 Screenshot
https://prnt.sc/ggetiw

**Comment by gilbertsohal** [comment]
@TomashKhamlai 

Could you please guide me what to do?

**Comment by deckside** [comment]
I have the same problem this started after upgrading from CE2.17 to CE2.18

**Comment by gilbertsohal** [comment]
@  magento-engcom-team

How long will take to fix this bug?

**Comment by orlangur** [comment]
Seems to be a duplicate of https://github.com/magento/magento2/issues/10580 (not closing as they both are `G3 Passed`).

**Comment by magento-engcom-team** [comment]
@gilbertsohal, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by gilbertsohal** [comment]
@magento-engcom-team ohh great, Could you please confirm when you have plan to release patch.

**Comment by patrick-bigbridge** [comment]
@magento-engcom-team Please provide commit id of fix so that we can apply the change.

**Comment by adie1980** [comment]
@magento-engcom-team are you able to provide details of the fix? I have the same problem with Magento 2.1.9 and since upgrading, it won't let me save or amend any cart price rules, nor other extensions where a date has to be entered. "Please Enter A Valid Date". (although I am UK Locale)

**Comment by damjess** [comment]
@magento-engcom-team Same problem in 2.1.9, similar problem in add/edit product for "Set as New," researching if it's connected... 

Edit: Solution to add/edit "Set Product as New From" error found here -https://github.com/magento/magento2/issues/10485

**Comment by gilbertsohal** [comment]
@magento-engcom-team Have you fixed this issue in ver 2.2.0?

**Comment by nelero** [comment]
Is this bug is fixed ? real problem with start/end date for catalog rules, set as new from/to dates, dob customer when locale is not en_US. (ie fr_FR)
really painfull for production websites....

**Comment by gilbertsohal** [comment]
@okorshenko Have you fixed this issue?

**Comment by gilbertsohal** [comment]
@okobchenko 

Have you fixed this issue? I tried with fresh installation (2.1.9 AU) this issue still present in 2.1.9. Please help

**Comment by adie1980** [comment]
As a temporary fix for my store, I changed in admin “account settings” (found in top-right dropdown - where you set your admin username and password) the interface locale to English (United States).. this only changes the admin interface local (you can still have the front end store set as your local country interface (ie. Locale AU, or in my case UK locale)..

After I did this - now the date inputs work fine when setting cart rules / new product dates / sale price dates etc.. it’s not ideal but it worked for me..

**Comment by gilbertsohal** [comment]
@magento-engcom-team @orlangur 

Have you fixed this issue? I still facing same issue in 2.1.10 Please help?

**Comment by sergiomendonca** [comment]
Is this issue fixed or we'll still have to edit the validator file?

**Comment by sergiomendonca** [comment]
Magento 2.2 updated in December still have this bug. And have another many bugs associated by dates, like filters, entire marketing modulo, from to in catalog module...

**Comment by magento-engcom-team** [comment]
Hi @gilbertsohal. Thank you for your report. 
The issue has been fixed in magento/magento2#11306 by @raumatbel in 2.3-develop branch
Related commit(s):
 - b237558168488b77309d69872bf2d517aa942d49

The fix will be available with the upcoming 2.3.0 release.

**Comment by patrick-bigbridge** [comment]
I tried this commit. It doesn't work for me for the case described in this issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @gilbertsohal The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
