### ISSUE TITLE
Export data from grid not adding custom rendered data magento2

### ISSUE THREAD

**Issue by bulbulagarwal896** [magento/magento2#10765]
### Preconditions:
1. Magento 2.1.8
2. With needed prerequisites.

### Steps to reproduce
1. login to admin panel.
2. Go to customer panel, and click on export button to export details in CSV format.

### Expected result
1. in CSV, columns **Confirmed email** and **Account Lock**, values should be displayed as in customer grid.

### Actual result
1. Not displaying and value in **Confirmed email** and **Account Lock** columns of CSV. it just gives a blank value.
exporting not adding the values which are rendered by prepareDataSource function(ui/component/listing classes).

**Comment by Zefiryn** [comment]
I am gonna do it.

**Comment by magento-engcom-team** [comment]
@bulbulagarwal896, thank you for your report.
We've created internal ticket(s) MAGETWO-76254 to track progress on the issue.

**Comment by okorshenko** [comment]
We need a backport of the solution to 2.2-develop

**Comment by convenient** [comment]
@okorshenko I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
Hi @bulbulagarwal896 the issue has been fixed and delivered to 2.2-develop branch. Will be available with release 2.2.2

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81959

**Comment by vinaysikarwar** [comment]
Its still not working. Custom Rendered data not exporting from custom class.
