### ISSUE TITLE
Responsive Design Issue on Mobile with Magento 2.1.9

### ISSUE THREAD

**Issue by rishabhchd19** [magento/magento2#10941]
### Preconditions
Magento 2.1.7, 2.1.8, 2.1.9, php 5.6
### Steps to reproduce
Open frontend on mobile device (Android)
### Expected result
Expected that the `Shop By` is positioned correctly and nothing positioned incorrectly as shown in the screenshots. 

### Actual result
The `Shop By` and other contents positioned incorrectly and it happens only at the landing page i.e. the Main Page. It shows correctly and `Shop By` tab comes to correct position when any category or subcategory is selected as shown in the last image.
Everything showing OK on iPad, Laptop and Desktop website...having an issue on mobile layout.

![Magento 2.1.7, 2.1.8 Mobile responsive layout](https://user-images.githubusercontent.com/30948461/30526716-35e9eaf6-9c3d-11e7-9b58-4a4253b2057d.png)
![Magento 2.1.8, 2.1.9](https://user-images.githubusercontent.com/30948461/30526721-42e47320-9c3d-11e7-9295-ee8686974541.jpg)
![Correctly showing only when a category is selected from Menu or Navigation Layer](https://user-images.githubusercontent.com/30948461/30526818-a38088bc-9c3e-11e7-98ce-49cb5245c68f.png)

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details in steps to reproduce, or try to reproduce this issue on a clean installation, another Android device or another browser.

**Comment by jordanbrauer** [comment]
I have this as well @magento-engcom-team. Did you test it on an _Android Device_ like he specified?

Version **2.1.5**

**Comment by rishabhchd19** [comment]
You can please visit the website at [catalogue.yogdiagnostics.com](url) and can check yourself. I am getting the problem on each n every mobile device except iPad, iPhone(i didn't check), Laptop and Desktop.

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your answer.
We have reproduced this issue on the site you provided on a desktop browser by narrowing the browser window. But we cannot reproduce this issue on clean Magento installation even with a logo from your site. 
It seems like you Magento theme is improperly configurated. Please provide more details in steps to reproduce, or try to reproduce this issue on a clean installation.

**Comment by rishabhchd19** [comment]
It happens on Landing Page only, not on selecting any Category or Category Product. On Landing page under Content> Pages>>Landing Page I have edited shown in picture 1

and edited Custom XML under Design as Layout: 2 columns with left bar and Layout Update XML as shown in picture 2. 

If keep Landing page clear and no Layout update, the NEW PRODUCTS "Items 1 to 4 of 16 total"  shows at the top left corner and if we keep Layout update as shown in picture 2, Shop By and Items 1 to 4 of 16 total moved to corner. It happens only on the first page, not by selecting any category. I have already installed fresh magento copy 2.1.9 and now updated to 2.2.0.
![picture 1](https://user-images.githubusercontent.com/30948461/31017176-515befd0-a545-11e7-9d48-3ec0d42449d4.jpg)
![picture 2](https://user-images.githubusercontent.com/30948461/31017184-5c0f2f28-a545-11e7-929c-710289253de7.jpg)

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your response.
Can you please provide code from Content and Layout Update XML in text format?
If you provide some information about your custom widgets, it may be helpful too.

**Comment by rishabhchd19** [comment]
Content>Widget 

> <p>{{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="all_products" show_pager="1" products_per_page="4" products_count="16" template="product/widget/new/content/new_grid.phtml" page_var_name="pipexq"}}</p>

> <p>{{widget type="Magento\Catalog\Block\Widget\RecentlyViewed" uiComponent="widget_recently_viewed" page_size="4" show_attributes="name,image,price" show_buttons="add_to_cart,add_to_compare,add_to_wishlist" template="product/widget/viewed/grid.phtml"}}</p>

**Comment by rishabhchd19** [comment]
[layout update xml.txt](https://github.com/magento/magento2/files/1349145/layout.update.xml.txt)
Layout Update Xml config is attached here. Please note that I have upgraded Magento 2.19. to 2.2.0 and other issues have now come to see under this version. 
![layout_responsive](https://user-images.githubusercontent.com/30948461/31081819-b4da7bbe-a7aa-11e7-98b9-873cd28ac6a1.jpg)

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your report.
We've created internal ticket(s) MAGETWO-80668 to track progress on the issue.

**Comment by slackerzz** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by slackerzz** [comment]
@rishabhchd19 I'm trying to reproduce the issue on a clean installation with sample data.
I created a cms page with this content:

```
{{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="all_products" show_pager="1" products_per_page="4" products_count="16" template="product/widget/new/content/new_grid.phtml" page_var_name="pipexq"}}
{{widget type="Magento\Catalog\Block\Widget\RecentlyViewed" uiComponent="widget_recently_viewed" page_size="4" show_attributes="name,image,price" show_buttons="add_to_cart,add_to_compare,add_to_wishlist" template="product/widget/viewed/grid.phtml"}}
```

The page layout is "2 Columns with left sidebar", is it right?
In the `Layout Update XML` box i've pasted:
```
<referenceContainer name="sidebar.main">
    <block class="Magento\LayeredNavigation\Block\Navigation\Category" name="catalog.leftnav" before="-" template="layer/view.phtml">
        <block class="Magento\LayeredNavigation\Block\Navigation\State" name="catalog.navigation.state" as="state" />
        <block class="Magento\LayeredNavigation\Block\Navigation\FilterRenderer" name="catalog.navigation.renderer" as="renderer" template="layer/filter.phtml"/>
    </block>
</referenceContainer>
<referenceContainer name="content">
    <block class="Magento\Catalog\Block\Product\ListProduct" name="category.products.list" as="product_list" template="Magento_Catalog::product/list.phtml">
        <container name="category.product.list.additional" as="additional" />
        <block class="Magento\Framework\View\Element\RendererList" name="category.product.type.details.renderers" as="details.renderers">
            <block class="Magento\Framework\View\Element\Template" as="default"/>
        </block>
        <block class="Magento\Catalog\Block\Product\ProductList\Item\Container" name="category.product.addto" as="addto">
            <block class="Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare"
                   name="category.product.addto.compare" as="compare"
                   template="Magento_Catalog::product/list/addto/compare.phtml"/>
        </block>
        <block class="Magento\Catalog\Block\Product\ProductList\Toolbar" name="product_list_toolbar" template="Magento_Catalog::product/list/toolbar.phtml">
            <block class="Magento\Theme\Block\Html\Pager" name="product_list_toolbar_pager"/>
        </block>
        <action method="setToolbarBlockName">
            <argument name="name" xsi:type="string">product_list_toolbar</argument>
        </action>
    </block>
</referenceContainer>
```

but the result is:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\StateException): Bucket does not exist
```

Are you sure that the layout update is the same you are using?

**Comment by slackerzz** [comment]
I've removed this block

```
<referenceContainer name="sidebar.main">
    <block class="Magento\LayeredNavigation\Block\Navigation\Category" name="catalog.leftnav" before="-" template="layer/view.phtml">
        <block class="Magento\LayeredNavigation\Block\Navigation\State" name="catalog.navigation.state" as="state" />
        <block class="Magento\LayeredNavigation\Block\Navigation\FilterRenderer" name="catalog.navigation.renderer" as="renderer" template="layer/filter.phtml"/>
    </block>
</referenceContainer>
```

from the layout update and now i can render the page and the result is:

![m2dev local-test-catalog nexus 5](https://user-images.githubusercontent.com/3061752/31547352-4e649344-b027-11e7-9451-3656dfbb7304.png)

This can be easily fixed

**Comment by rishabhchd19** [comment]
@slackerzz  Yes, it is 100% sure that I am using the same layout update reason being it is showing Navigation layer on adding that container. And removing that block is actually removing the Navigation layer. Also, you can notice that by removing the Navigation Layer as Shop By option not resolving the other issues. It would be good if users would able to use Navigation Layer by this block...Is it there any other Layout update that getting back the Navigation Layer properly?

**Comment by rishabhchd19** [comment]
Also, it has started showing Show X per page at top and bottom of the main block...twice on the page after updating to 2.2.0

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81986

**Comment by okorshenko** [comment]
Hi @rishabhchd19 the issue has been fixed and delivered to 2.2-develop branch and will be available with 2.2.2 release soon

**Comment by rishabhchd19** [comment]
yaaaaaaay!!!! will be waiting for it to be released

**Comment by rishabhchd19** [comment]
![quicksquare_20171221104044471](https://user-images.githubusercontent.com/30948461/34457551-04ff0ed2-edda-11e7-8f05-05d4cb0ae3bf.jpg)
There's still a problem. Layered navigation SHOP BY not at correct position.

**Comment by magento-engcom-team** [comment]
Hi @rishabhchd19. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1283 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 074285735cd6d33fd530302390ab8101e73d7e34
 - fde512eacfce36508bcec2b1c08ef381d0af3f92
 - e7d90de918be70731e2021dee757d1e7af374ab8
 - 6d4f36db79a9bee553b4acfe8c0820b5c046e6af
 - 2e83a36fbf3201bdaf6612dcfce08125687f0e28
 - 23b4aa11f5a4a0b6bfe76cd1e812d36d88ed4d83
 - b50bfa811876af007426b734019fd149def63bba
 - 04cd60da14a87727768165942c23fc1403016e41
 - 75d5a0522e8a18c2f403ea284d62e445e3d6ddc2
 - 5e02b15fcbe310cd13e385d0ae7a3e6017b56497
 - aad5ba6236ca8557072f62db524b23d68eae5de3
 - 3e321401374a7f2292bd3b2c4540db2c0af34216
 - 7898946b7ec40999b2007ee377d6b6312a3778b3
 - a173e1cd160b1d7cd24a855420317fdd7bfd9624
 - 41d0075104cb628ec1806130b6449929e8585997
 - dda19b2f6eff23e0904673fe7719c3fd935aed02
 - cba48cdfedc500b652deee50e3a3dc95e366eca3
 - 0c62caaf80c9659530d0c3dd0741108d1b0dadb0
 - 736f783b1b2fd361fb8328fd7c5cf9e7c3c172e2
 - 7569b7002878019a115aa2ea587d476a282fcd17

The fix will be available with the upcoming patch release.

**Comment by rishabhchd19** [comment]
Problem is still there.

**Comment by rishabhchd19** [comment]
Problem is still there as you can see in the attachment.

**Comment by rishabhchd19** [comment]
![quicksquare_20171221104044471](https://user-images.githubusercontent.com/30948461/36628413-c86d7c78-1972-11e8-963e-25e9b01e0ca1.jpg)
 This issue is still there.

**Comment by samanaveen** [comment]
I have added below code on above "Bucket does not exist" condition. Because we are showing subcategories on main category pages. So we don't need filters. 

        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
        
        if($category && $category->getIsAnchor() == '0'){
            return '';
        }

        if (!$bucket) {
            throw new StateException(new Phrase('Bucket does not exist'));
        }

**Comment by PawanKumarN** [comment]
hi @samanaveen .I have added above code \vendor\magento\module-catalog-search\Model\ResourceModel\Fulltext\Collection.php  above below line

> throw new StateException(__('Bucket does not exist'));
but i got error : Uncaught Error: Class 'Magento\CatalogSearch\Model\ResourceModel\Fulltext\Phrase' not found
