### ISSUE TITLE
i18n:collect-phrases -m can't find many important magento phrases 

### ISSUE THREAD

**Issue by scholtz** [magento/magento2#11175]
**Summary**
This is continuation of thread https://github.com/magento/magento2/issues/2630
Magento 2.2 clear installation using script http://apps.scholtz.sk/magento.install.script.txt
### Preconditions

1. Magento 2.4-develop
2. PHP 7.1, Nginx, Mysql 5.7

### Steps to reproduce
1. Install Magento and download SK language pack
2. do collect phrases php bin/magento i18n:collect-phrases -o "$VER.csv" -m
3. translate phrases
4. Check translations in admin

(I have full translation of magento to slovak language, so i skip step 2 i install it through the script listed above)

### Expected result
I expect all texts to be localised

### Actual result
Some phrases are not translated.. Btw, i can see some progress in the 2 years work now, but still some are missing..

![obrazok](https://user-images.githubusercontent.com/1223439/31060813-1394adf0-a71a-11e7-8afa-e21480af8404.png)
![obrazok](https://user-images.githubusercontent.com/1223439/31060821-346e5d78-a71a-11e7-8a97-56e892897a54.png)
![obrazok](https://user-images.githubusercontent.com/1223439/31060831-5f04d594-a71a-11e7-9246-f22cf27d57c6.png)
![obrazok](https://user-images.githubusercontent.com/1223439/31060838-78ca954a-a71a-11e7-8d9a-74f25aff1763.png)
![obrazok](https://user-images.githubusercontent.com/1223439/31060852-a44da3ce-a71a-11e7-8e09-54bed1bdd600.png)
![obrazok](https://user-images.githubusercontent.com/1223439/31060880-23de71b8-a71b-11e7-9510-2a0763f4c791.png)

**Comment by magento-engcom-team** [comment]
@scholtz, thank you for your report.
We've created internal ticket(s) MAGETWO-80604 to track progress on the issue.

**Comment by PascalBrouwers** [comment]
Added a PR for 2.2-develop.

**Comment by PascalBrouwers** [comment]
Added a PR for 2.3-develop while we're at it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29541` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bartlomiejsz** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @scholtz. Thank you for your report. 
The issue has been fixed in magento/magento2#30320 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [48216f3e13d04b8755b70f8b9b1399d87a33ab91](https://github.com/magento/magento2/commit/48216f3e13d04b8755b70f8b9b1399d87a33ab91)

The fix will be available with the upcoming 2.4.2 release.

**Comment by maksymz** [comment]
Hi, @magento-engcom-team and @scholtz !

Seems this still lacks some functionality. This will still not collect phrases translated with `$t()` function in cases like this:

```html
                <input
                       name="email"
                       data-bind="
                            value: email,
                            attr: {
                                title: $t('Email'),
                                placeholder: $t('Your Email'),
                            }
                       "
                />
```

Regards,
Max

**Comment by maksymz** [comment]
Hi, @scholtz and @magento-engcom-team !

According to the official Magento 2 documentations, there is a way to translate HTML attributes, but this is not covered as well. Here is a text from the documentation:
> When a string is added as an attribute of an HTML element:
```html
<input type="text" data-bind="attr: {placeholder: $t('First Name')}" />
```

This was of translating attributes does not seem to be used in the Magento 2 itself (if my search is correct). Though, it is officially documented, is used by some vendors and it can be found in some Q&A on the Internet ( like here - https://magento.stackexchange.com/questions/181070/magento-2-translate-input-placeholder-attribute-string-in-knockout-html-templat )

As a result, this is still a potential issue I think...

Regards,
Max

**Comment by maksymz** [comment]
Possible additional regular expression for the class `\Magento\Setup\Module\I18n\Parser\Adapter\Html` is:
```php
'/\\$t\(\s*([\'"])(?<value>.*?[^\\\])\1.*?[),]/i'
```

**Comment by hostep** [comment]
Hi @maksymz, feel free to open a pull request with your suggest fix. If that's not possible somehow, I'd recommend you to open a new issue instead of commenting on an old closed one which is considered fixed. Thanks! 🙂

**Comment by gabrieldagama** [comment]
Hi @scholtz. Thank you for your report. 
The issue has been fixed in magento/magento2#31804 by @maksymz in 2.4-develop branch
Related commit(s):
 - [754ea5fcb1ed51281019235b7095d8152a6ffdc6](https://github.com/magento/magento2/commit/754ea5fcb1ed51281019235b7095d8152a6ffdc6)
 - [77daafd4571efbaf93b302076017ea3efd757e91](https://github.com/magento/magento2/commit/77daafd4571efbaf93b302076017ea3efd757e91)
 - [f847294d47d95ee171a2b6ea860be68ebeb7aff5](https://github.com/magento/magento2/commit/f847294d47d95ee171a2b6ea860be68ebeb7aff5)

The fix will be available with the upcoming 2.4.3 release.
