### ISSUE TITLE
Use secure urls in front end breaks admin customer section

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1117]
I have enabled https in front end. it's working ok in front end. But when I try to load admin/customer/index it loses all css and render just text page. I can fix this by enabling secure urls in admin.
![image](https://cloud.githubusercontent.com/assets/3830093/6769337/65024728-d0bd-11e4-91a0-12988a8ea4a4.png)

**Comment by mazhalai** [comment]
@bgkavinga Thank you for reporting this issue. We have created MAGETWO-35409 our internal tracking.

**Comment by JesusTinoco** [comment]
I had the same problem.

**Comment by JesusTinoco** [comment]
Are you working on that? Thanks!

**Comment by vpelipenko** [comment]
@bgkavinga, @JesusTinoco, this issue is already fixed and available from version 0.74.0-beta3. Could you check it again?

**Comment by JesusTinoco** [comment]
I'm checking it now, thanks a lot!

**Comment by JesusTinoco** [comment]
I'm still have the same problem. It serves the js and css by the 80 port when it should serve it by the 443 port.
![screen shot 2015-04-06 at 17 04 34](https://cloud.githubusercontent.com/assets/2388836/7006186/7694cae2-dc7f-11e4-8171-de348a12311c.png)

**Comment by vpelipenko** [comment]
@JesusTinoco, hm... did you check it on the latest 0.74.0-beta3?

**Comment by JesusTinoco** [comment]
I've just done a clean installation of that version.

**Comment by vpelipenko** [comment]
Ok. Thank you. We'll check it again.

**Comment by vpelipenko** [comment]
It works on our side. Probably it is something with Apache configuration on your side. More information about server configuration you can find here http://devdocs.magento.com/guides/v1.0/install-gde/prereq/apache.html. Is it reproduced only on customer related pages in backed? What happens when you click directly on css/js source link? Is it available? Please, provide more information for us, if you can. It will be very valuable and help us to find a problem.

**Comment by JesusTinoco** [comment]
It is reproduced in all /admin/ pages. 

![screen shot 2015-04-08 at 11 27 24](https://cloud.githubusercontent.com/assets/2388836/7042837/fdcd9168-dde4-11e4-82dc-cfc64032e3f4.png)

This is my configuration:

![screen shot 2015-04-08 at 11 29 45](https://cloud.githubusercontent.com/assets/2388836/7042846/155b90be-dde5-11e4-912c-8a50f5b25bc3.png)

And the css/js are available:

![screen shot 2015-04-08 at 11 28 31](https://cloud.githubusercontent.com/assets/2388836/7042868/58c9cb2c-dde5-11e4-89af-7322e38a2025.png)

But I don't know why they serve the static files by 80 port when with the 443 port the files are available too.

![screen shot 2015-04-08 at 11 28 22](https://cloud.githubusercontent.com/assets/2388836/7042893/91112246-dde5-11e4-8dfe-f26c62a6824c.png)

**Comment by bgkavinga** [comment]
Hi, I am getting circular dependency error after new updates. 
"name": "magento/project-community-edition",
    "description": "Magento project (Community Edition)",
    "type": "project",
    "version": "0.74.0-beta4",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
I am running,
PHP 5.6.7
![image](https://cloud.githubusercontent.com/assets/3830093/7105680/67cdb0d8-e142-11e4-8331-755d4787bdae.png)

Any hints ?

**Comment by mazhalai** [comment]
@bgkavinga @JesusTinoco 
- Can you please tell us what server are you using?
- If you are using apache, has mod rewrite been enabled?

**Comment by bgkavinga** [comment]
Hi @mazhalai ,
This is working ok after a fresh installation. Previously I switched to develop branch from master in order to get latest update. It breaks the entire web site.
Thanks

**Comment by vpelipenko** [comment]
@bgkavinga, can we close the issue?

**Comment by bgkavinga** [comment]
This issue is no longer valid. Closing the bug.
