### ISSUE TITLE
Attribute category_ids issue

### ISSUE THREAD

**Issue by AmastyLtd-zz** [magento/magento2#11341]
Preconditions

1. Magento 2.2.0 EE.
2. PHP 7.0

Steps to reproduce

1. Enable developer mode.
2. Go to Admin->Stores->Attributes->Product (https://screen.amasty.com/1507615065816.png)
3. Find attribute category_ids
4. Go to Storefront Properties in this attribute
5. Enable Visible on Catalog Pages on Storefront https://screen.amasty.com/1507615274284.png
6. Go to product page on front and take this https://screen.amasty.com/1507615245856.png

Expected result

Category ids not visible on the front because users are not interested in knowing id categories.

Actual result:

```
1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in /var/www/sources/shagoiko/ee220/app/code/Magento/Catalog/Block/Product/View/Attributes.php on line 88

Exception #0 (Exception): Notice: Array to string conversion in /var/www/sources/shagoiko/ee220/app/code/Magento/Catalog/Block/Product/View/Attributes.php on line 88
#0 /var/www/sources/shagoiko/ee220/app/code/Magento/Catalog/Block/Product/View/Attributes.php(88): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/var/www/source...', 88, Array)
#1 /var/www/sources/shagoiko/ee220/app/code/Magento/Catalog/view/frontend/templates/product/view/attributes.phtml(19): Magento\Catalog\Block\Product\View\Attributes->getAdditionalData()
#2 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/var/www/source...')
#3 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Attributes), '/var/www/source...', Array)
#4 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/source...')
#5 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#6 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('product.attribu...')
#8 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.attribu...')
#9 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.attribu...')
#10 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.attribu...', true)
#11 /var/www/sources/shagoiko/ee220/app/code/Magento/Catalog/view/frontend/templates/product/view/details.phtml(16): Magento\Framework\View\Layout\Interceptor->renderElement('product.attribu...')
#12 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/var/www/source...')
#13 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Description), '/var/www/source...', Array)
#14 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/source...')
#15 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#16 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#17 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('product.info.de...')
#18 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.de...')
#19 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.de...')
#20 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.de...', true)
#21 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.de...')
#22 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#23 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#24 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#25 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#26 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#27 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main')
#28 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#29 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#30 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#31 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#32 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns')
#33 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#34 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#35 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#36 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#37 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content')
#38 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#39 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#40 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#41 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#42 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#43 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#44 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#45 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#46 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#47 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#48 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#49 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#50 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#51 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#52 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#53 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#54 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#55 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#56 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#57 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#58 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#60 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#61 /var/www/sources/shagoiko/ee220/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#62 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#63 /var/www/sources/shagoiko/ee220/lib/internal/Magento/Framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#64 /var/www/sources/shagoiko/ee220/index.php(41): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#65 {main}
```

Reason:

We are debbuging and find that in \Magento\Catalog\Block\Product\View\Attributes::getAdditionalData not provided array value of the attribute (https://screen.amasty.com/1507556183855.png).

**Comment by orlangur** [comment]
> Enable Visible on Catalog Pages on Storefront

> Expected result
> Category ids not visible on the front

This is clearly store misconfiguration and not a bug. `E_NOTICE` will not be displayed to end user.

**Comment by orlangur** [comment]
@magento-engcom-team please provide some reasoning when reopening issue.

This case can be covered in https://github.com/magento/magento2/pull/10619/files, just that expected behavior is not so clear in described store setup. Should any `is_array($value)` be treated as `$value = ''`?

**Comment by ishakhsuvarov** [comment]
@orlangur While `E_NOTICE` is not displayed to the end user it still should be eliminated

**Comment by magento-engcom-team** [comment]
@AmastyLtd, thank you for your report.
We've created internal ticket(s) MAGETWO-81575 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by tushhan** [comment]
The problem persist on magento 2.2.3

1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in /home/..../public_html/..../vendor/magento/module-catalog/Block/Product/View/Attributes.php on line 88

Exception #0 (Exception): Notice: Array to string conversion in /home/..../public_html/..../vendor/magento/module-catalog/Block/Product/View/Attributes.php on line 88
