### ISSUE TITLE
Multiple stores allowed countries not working in magento2 ?

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/magento2#11511]
### Preconditions

1. Magento 2.1.9
2. PHP 7.0.23
3. MySQL 5.6.36-2.el6

### Steps to reproduce

1. Set multistore
2. Set different allowed countries for each store in Stores > Configuration > General > General > Country Options
3. Add product to cart
4. Go to checkout

### Expected result

1. Client should be able to select destinations based on the store he's in. So only the countries selected for the active store should be available.

### Actual result

1. All the allowed countries in default configuration are available.

It seems like somebody managed to fix this issue : 
[https://magento.stackexchange.com/questions/166121/allowed-country-not-working-in-magento2](https://magento.stackexchange.com/questions/166121/allowed-country-not-working-in-magento2)
But it should be handled by core as the option is available in administration.

**Comment by magento-engcom-team** [comment]
@ShapesGraphicStudio, thank you for your report.
We've created internal ticket(s) MAGETWO-82124 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@ShapesGraphicStudio, thank you for your report.
The issue is already fixed in 2.2.2

**Comment by ShapesGraphicStudio** [comment]
Hello,
I made the update to 2.2.2, but the issue still remains.

**Comment by jbalca** [comment]
Hi,

We're also using 2.2.2 and have the same issue.
In our case it's showing a "merge" of all the allowed countries from all websites. It should show only the allowed countries for the current website.

**Comment by wescey** [comment]
Hello,
I',m on 2.2. Same problem here as above.

**Comment by Lakshyami** [comment]
Issue is still there on 2.2.3. Any updates?

**Comment by Lakshyami** [comment]
Seems its working with changing Store->Configuration->Customers->Customer Configuration->Account Sharing Options in to 'Per Website'. (version 2.2.3)

**Comment by webcreative24** [comment]
working on Magento 2.2
