### ISSUE TITLE
Invoice for products that use qty decimal rounds down to whole number

### ISSUE THREAD

**Issue by ralbin** [magento/magento2#11941]
This is a new issue in Magento 2.2.0.  This feature works as expected in all previous versions. Use check/money order for payment. When trying to invoice an order that has products with quantity decimals, the invoice rounds down to the nearest whole number.  Example, ordered 6.5 of a product but the invoice uses 6.  The ultimate reason this is not working is in the table sales_order_item column is_qty_decimal is not being set to 1.

### Preconditions

1. Magento ver. 2.2.0
2. PHP 7.0.24
3. MySQL 5.7

### Steps to reproduce

1. Create a virtual product
2. In Advanced Inventory Qty Uses Decimals = Yes
3. In Advanced Inventory Manage Stock = No
4. In the admin create an order using the new product and pay with check/money order
5. Purchase a quantity of 6.5 of the product and complete the order
6. Start to create the invoice look at the QTY invoiced it will be rounded down to 6
7. If you set the flag $_canCapturePartial you are able to edit the field, however it resets back to 6
8. Look at the database table sales_order_item and notice that the column is_qty_decimal is set to 0.

### Expected result

1. Invoice should automatically use the QTY ordered such as 6.5
2. Ability to edit of a quantity similar to 5.5 
3. Button to update the invoice to show the changes if modified from the original
4. Review the database table sales_order_item and column is_qty_decimal = 1
### Actual result

1. Quantity is rounded down to the nearest whole number and unable to edit the qty to be invoiced
2. Inspecting the database sales_order_item I noticed that is_qty_decimal was set to 0, changing that to 1 made the invoice show 6.5 for the quantity. 
3. Ability to edit a check/money order quantity should be available by default, rather than having to do a new module that sets the flag $_canCapturePartial = true;

**Comment by magento-engcom-team** [comment]
@ralbin, thank you for your report.
We've created internal ticket(s) MAGETWO-83167 to track progress on the issue.

**Comment by okorshenko** [comment]
Fixed in 2.2-develop

**Comment by magento-engcom-team** [comment]
Hi @ralbin. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1289 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - b41594122f532f6a89165a70906a5b257562c0df
 - 7369261d82e0e5ad926eaf4ccb2a8def79c4fcbb
 - dce1c66301cdddfee2dc2887f584c333d0b438b2
 - 95ed67ee4adbbd7f3f0107a52da4b9238cf44803
 - 05fcdd1a52c674ea09a34960cea71e73488fbc99
 - 8b1a2972b3f0ddd4713d00055b8d60f737a72ce4
 - 90addb731c3b253d3da4dc564ddf94ac3525bd0f
 - d5c9eef075cd5f4d9781ec7f3151a14e087d061d
 - 6ec62717c16ed96d45e670d7f867b724f0449aaa
 - f0af87edad79b295b4be87f6f92502bacfbc2764
 - 2497062749bf41c80aaebb9b6cd21eb48656f58c
 - 1f7347f47cca48238f9deabd48a0a280bc0c309f
 - 0d151c41539ba7c4d20ede20d614bb4be257903c
 - 07982fdea19074788654c6e825874cb8188ab627
 - 617da6ca08607890779ce71530a2871438c88351
 - 39ed21f83071ebffd71963e9097ecb59fd906702
 - 9aa036dec42211867f68f714a746b71395c43bb2
 - fda37ef0af75e6b28d4a0da1781b19c7a7894a97
 - 47b109180b6b5e499ba8d82e6c67888fca21ffe8
 - ef6badace5c6b046047a6e5f617020f9d4410a82
 - 809ec050986fa3ddfeec4a715ce5ace1e41a4427

The fix will be available with the upcoming patch release.

**Comment by Jilco** [comment]
Problem is back in 2.3.3! Never had the problem, but after upgrade from 2.3.2 to 2.3.3 it was there...

**Comment by niekappartmedia** [comment]
Problem still exists in 2.4.3-p1
