### ISSUE TITLE
Tier Price for Customer Group

### ISSUE THREAD

**Issue by afavata** [magento/magento2#12486]
Tier price is related to customer group. Product price in the cart should be updated as soon as customer log into an account which group is set in tier price.

### Preconditions
Magento 2.2.0

### Steps to reproduce
1. Create product XX with standard price $ 10 and  Tier price $5 for quantity 3 and for **Wholesale Customer Group** 
2. Shop the product on frontend as account "not logged in" 
3. Add 3 pcs of product XX to the cart. Price used by Magento is the standard one $10.
4. Log in to an account which belong to  **Wholesale Customer Group**

### Expected result
1. Price for product XX should be updated with the tier price (from $10 to $5).

### Actual result
1.  Price for product XX is not updated to reflect tier price (it stays $10)

**Comment by magento-engcom-team** [comment]
@afavata, thank you for your report.
The issue is already fixed in 2.2.1

**Comment by afavata** [comment]
Sorry ... my Magento is at 2.2.1 but issue is still present.
Please reopen this.
thanks

**Comment by rakeshept** [comment]
Hello,
I am facing this issue in magento version 2.2.2.
Can you please reopen this ticket?

**Comment by thanhdble** [comment]
Same issue in version 2.2.3

**Comment by aledevil** [comment]
some news for this issue?

**Comment by andyjoneski** [comment]
I'm experiencing the exact same issue in 2.3.2 - thought i was going mad. But the base price of the product always shows.

e.g. base price of the product is £10. Customer group A price is £8, upon logging into the site in customer group A the price remains £10 and not 8.

**Comment by amon81** [comment]
I've created one customer's group rule with a discount of 30% for one group.
When the customer log into the magento frontend the price rule is not vibile with the discount price. When if i clear the cache of the browser and the MAGENTO now became visible the price rule applied to the customer's group. 
It's clearly an issue. 
Magento CE version 2.2.8

**Comment by sayanthkoroth** [comment]
I have the issue in 2.3.4 The unit price and total is not getting updated as given in the tier price. It always show the default unit price.

**Comment by carlzata** [comment]
Same issue in 2.3.4. Price still uses regular price after setting up tier prices
