### ISSUE TITLE
when saving a page in magento 2.2.1, 'Modified' date field is not getting updated

### ISSUE THREAD

**Issue by mahmood537** [magento/magento2#12625]
### Preconditions

1. Magento version 2.2.1
2. 

### Steps to reproduce

1. Login to magento admin
2. Go to Content > Pages
3. In Action column, click select > edit
4. Make changes to that page and click 'Save Page'

### Expected result

1. The 'Modified' value for the edited page should be current timestamp

### Actual result

1. 'Modified' value for the edit page did not change. It's still the same as 'Created' value

This happens in Magento version  2.2.1
![pages1](https://user-images.githubusercontent.com/12780399/33831391-c6013c76-de2c-11e7-91f9-926e986f628a.jpg)
![pages2](https://user-images.githubusercontent.com/12780399/33831393-c9f96880-de2c-11e7-81f3-1a3698ec7d57.jpg)

**Comment by magento-engcom-team** [comment]
@mahmood537, thank you for your report.
We've created internal ticket(s) MAGETWO-85309 to track progress on the issue.

**Comment by osrecio** [comment]
Working on it!
The same thing happens for static blocks. I will fix for both

**Comment by okorshenko** [comment]
Hi @mahmood537. Thank you for your report. 
The issue has been fixed in magento/magento2#12636 by @osrecio in 2.2-develop branch
Related commit(s):
 - 22f454dd020719686c558a36d67df6dc13506c3f

The fix will be available with the upcoming patch release.

**Comment by stephansteiner** [comment]
Still is still an issue in Magento 2.2.3. This error can be reproduced on a blank installation of magento 2. Error occurs when saving cms pages and blocks, other entities 
Steps to reproduce:
- create new cms block
- reopen newly created cms block, modify text/and or title and save again
- modification date remains unchanged.
