### ISSUE TITLE
Sort by Product Name doesn't work with Ancor and available filters

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#12860]
On the category page when we have filters (as example - we need to define color for products) +  "Ancor" is enabled for category - sorting by product name doesn't work correct.

### Preconditions
1. Install Magento 2.2.2
2. Create "test" category
3. Create 3 products and add them to "test" category
- Product A (**color attribute set to "red"**)
- Product B (**color attribute set to "blue"**)
- Cool Product C (**color attribute set to "red"**)
4. For "test" category in "Design" section change "Layout" to "1 column", save category
5. For "test" category in "Design" section change "Layout Update XML" to "```<referenceContainer name="main.content" htmlClass="page-main products-grid--max-4-col"/>```", save category

### Steps to reproduce
1. Go to frontend >> Test category
2. Change "Sort" to "Product Name"

### Expected result
1. Products should be sorder by name (when ancor disabled - it works good)
![image](https://user-images.githubusercontent.com/1873745/34300282-f9e76f86-e72f-11e7-9d3e-38771ef2ac22.png)
![image](https://user-images.githubusercontent.com/1873745/34300301-0f540870-e730-11e7-93ce-432cb02adba9.png)

### Actual result

1. Products are not sorted by name (product B should be 3rd, but it is second) ![image](https://user-images.githubusercontent.com/1873745/34300024-ecbc6448-e72e-11e7-8da3-ff976c755a17.png)
2. Sorting by desc also doesn't work: 
![image](https://user-images.githubusercontent.com/1873745/34300091-315767f6-e72f-11e7-8811-eac756c0425c.png)

We hadn't this issue in Magento 2.1.x, it appeared during upgrade to 2.2, so probably it's regression.

Video where I was able to reproduce it: https://photos.app.goo.gl/tfRvSIcYYNN90jUB2

**Comment by magento-engcom-team** [comment]
Hello @ihor-sviziev. Thanks for reporting. Currently we are not able to reproduce Your issue. We tried to do that on a clear instance of Magento and recorded a video about that. In fact there are three separate videos : Video1, Video2 and Video3. Please watch them in that order and tell us what we have missed or done not as You have.
[Video1.zip](https://github.com/magento/magento2/files/1590616/Video1.zip)
[Video2.zip](https://github.com/magento/magento2/files/1590617/Video2.zip)
[Video3.zip](https://github.com/magento/magento2/files/1590618/Video3.zip)

**Comment by ihor-sviziev** [comment]
Hi @magento-engcom-team, 

I was able to reproduce on fresh magento installation, will try to check steps to reproduce, probably there is mistake. Will update you later

**Comment by ihor-sviziev** [comment]
Looks like this issue reproducing not every time, will try to record video or define more clear steps to reproduce.

**Comment by ihor-sviziev** [comment]
@magento-engcom-team I've updated steps to reproduce, also I prepared video where I reproduced this issue. Link to video: https://photos.app.goo.gl/tfRvSIcYYNN90jUB2

**Comment by magento-engcom-team** [comment]
@ihor-sviziev, thank you for your report.
We've created internal ticket(s) MAGETWO-86296 to track progress on the issue.

**Comment by ihor-sviziev** [comment]
@magento-engcom-team I had this issue on 2.1.9. Weren't you able to reproduce it on 2.1.x?

**Comment by okorshenko** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1192 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - e5b030afbfa1714763f640b36509230230ec0c1f
 - d80c790567dca73561e67d53c43c0900a7137d0f


The fix will be available with the upcoming 2.2.4 release.

**Comment by ihor-sviziev** [comment]
@p-bystritsky thank you so much for fixing it!

**Comment by SatishDubariya** [comment]
**Product Sorting Not works for 1column layout.**
I have installed fresh magento 2.2.2 with sample data and change Category Page Layout to 1 Column for Jackets Category in Women > Tops.
But after that when i tried to sort products by Name and Position, i found that it is not sorting.

![position-desc](https://user-images.githubusercontent.com/21054477/35790342-dd545e46-0a67-11e8-9cd7-fbce843606ef.jpg)
![position-asc](https://user-images.githubusercontent.com/21054477/35790343-dd9461bc-0a67-11e8-8899-d39af969a16c.jpg)
![name-asc](https://user-images.githubusercontent.com/21054477/35790344-ddd20e7c-0a67-11e8-916c-93b5151000af.jpg)
![name-desc](https://user-images.githubusercontent.com/21054477/35790345-de0ff30e-0a67-11e8-8e62-36cbd557a55a.jpg)

**Comment by ihor-sviziev** [comment]
@SatishDubariya fix for this issue is here: https://github.com/magento/magento2/commit/e5b030afbfa1714763f640b36509230230ec0c1f
You can apply this patch for your project.
Here is example how to apply it: https://gist.github.com/amenk/908e80748662d896718685c778cd4db4

**Comment by vberthet** [comment]
Same problem with magento 2.1.14.

Fix in https://github.com/magento/magento2/pull/13468/ works. Please merge in 2.1.x

**Comment by ihor-sviziev** [comment]
@vberthet I created PR for fixing it in 2.1.x

**Comment by sidolov** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#16945 by @ihor-sviziev in 2.1-develop branch
Related commit(s):
 - [045b95c50bce57f67264337865b63af4dfb8782d](https://github.com/magento/magento2/commit/045b95c50bce57f67264337865b63af4dfb8782d)

The fix will be available with the upcoming 2.1.15 release.

**Comment by solomon-tech-critic** [comment]
I am on Magento 2.2.3 is this issue persists.

**Comment by magejunkie** [comment]
@ihor-sviziev I am on Magento 2.2.3 and this issue persists.

**Comment by ihor-sviziev** [comment]
@magejunkie, just update to latest version and this issue should go away

**Comment by magento2dev** [comment]
> Hi @ihor-sviziev. Thank you for your report.
> The issue has been fixed in #16945 by @ihor-sviziev in 2.1-develop branch
> Related commit(s):
> 
> * [045b95c50bce57f67264337865b63af4dfb8782d](https://github.com/magento/magento2/commit/045b95c50bce57f67264337865b63af4dfb8782d)
> 
> The fix will be available with the upcoming 2.1.15 release.

I'm on Magento 2.2 and I tried to apply this fix but I still get the issue (not filtering by product name and showing more products than toolbar defined) is there anything else to do ?

Thanks !
