### ISSUE TITLE
Wrong shipping fee in backend with multiple store views

### ISSUE THREAD

**Issue by tig-dennisvanderhammen** [magento/magento2#12889]
### Preconditions

1. Magento version 2.2.2 with sample data installed
2. PHP version 7.0.25
3. Two different websites with storeviews (explained in steps to reproduce)
4. Each website a different flat fee (explained in steps to reproduce)

### Steps to reproduce

1. Install a clean version of Magento 2.2.2.
2. Set up a Second website, second store and second storeview in Stores->All Stores.
3. Add a product to your Second website at Catalog->Products (in my case the Joust Duffle Bag from the sampledata)
4. Set up different flat fee shipping fees for both websites in Stores->Configuration->Sales->Shipping Methods (in my case 10$ for flat fee in Main Website, 20$ for flat fee in Second website).
5. Clear the Magento cache.
6. Create a new order at Sales->Orders->Create new order.
7. Click on the button Create New Customer.
8. Select the Second store view in the Second website.
9. Add a product and fill in the order details
10. Click on the button Get shipping methods and rates

### Expected result

1. Expected shipping fee of 20$ is applied, because I selected the second store view when creating the order.

### Actual result

1. The shipping fee of the default website is selected as shown on the screenshot below.
![screen shot 2017-12-27 at 11 07 41](https://user-images.githubusercontent.com/23072926/34378461-31687dc8-eaf6-11e7-81ef-f4f92a5a879c.png)

It seems that whenever I change the default website (Stores->All Stores, click on Second Website, select Set as Default and save) I get the shipping fee of the newly selected default store. 

Extra screenshots:

Configured websites:
![screen shot 2017-12-27 at 11 10 49](https://user-images.githubusercontent.com/23072926/34378557-a2ccf070-eaf6-11e7-9022-e3796d053f22.png)

Configured flat fee price for Main Website:
![screen shot 2017-12-27 at 11 11 45](https://user-images.githubusercontent.com/23072926/34378577-cf23ee08-eaf6-11e7-8004-21e187e80b37.png)

Configured flat fee price for Second Website:
![screen shot 2017-12-27 at 11 12 44](https://user-images.githubusercontent.com/23072926/34378588-e3dcc252-eaf6-11e7-8bf2-e044fa6ae759.png)

**Comment by magento-engcom-team** [comment]
@tig-dennisvanderhammen, thank you for your report.
We've created internal ticket(s) MAGETWO-86049 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @tig-dennisvanderhammen 
the issue has been fixed in 2.2-develop branch

**Comment by InternetMedicineMan** [comment]
I'm in version 2.2.3 and having this issue. It doesn't appear to be fixed. - edit - Oh I see it's on develop branch so probably next release

**Comment by Rickertje** [comment]
I am on 2.2.5 and this is still not solved (be it tablerates in my case)
We are now 6 months after this was labeled 'Fixed in 2.2.x'
Can someone tell me what the status is? Thx.

**Comment by Rickertje** [comment]
@magento-engcom-team cab you please answer this question? Thank you.

**Comment by callumstar** [comment]
Hi @magento-engcom-team and @okorshenko,

This is still an issue, is there any updates on this please?

**Comment by callumstar** [comment]
Hi @tig-dennisvanderhammen,

Did you ever manage to fix this?

**Comment by Rickertje** [comment]
My developer tells me that there was an attempt to fix (part of) this in 2.2.5. Anyway it was not fixed for tablerates, I'm not sure about other shipping methods. So there is still work to do on this issue.

**Comment by tig-dennisvanderhammen** [comment]
@callumstar, I didn't get any complaints from our clients about this and encountered this during development of an extension. I didn't look into fixing this issue and simply wanted Magento to know about this issue. Sorry!

**Comment by Rickertje** [comment]
Ok so where is the big red button to reopen this issue

**Comment by jhruehl** [comment]
Thanks. The fix for this issue now causes the standard shipping rate label to be shown in the language of the store view where the last product was added. (cart and checkout).

I'm going to create a pull request, which sets the QuoteStoreId not as given by the order object, but as given by the store manager. This doesn't mess things up and probably still works for @tig-dennisvanderhammen problem.

**Comment by jhruehl** [comment]
It seems I cannot create any pull requests for the 2.2-develop branch even with an updated fork. Only for 2.2 and 2.3-develop. So I leave it there, because the "fix" to this issue still isn't present in the 2.3 branches.

My fix for the "fix" of this issue can be found in the pull requests above, which have been rejected, because they weren't given via a fork.

**Comment by Rickertje** [comment]
I'm not sure I understand (but I'm not a developer). While editing an order in admin the store(view) to be used for selecting shipping methods and/or tablerates should be set as the store(view) for which the order was initially created. Also it would be nessecary to have fix become part of 2-2-dev and 2.3.

**Comment by jhruehl** [comment]
@Rickertje Yes. An order should be, but this is about quotes. So the problem isn't that easy to solve I guess. Because the fix was placed somewhere, which has an effect on the frontend, too. We use store views only for different languages. So switching the store view (language) in the frontend can/will cause problems with the current fix.

**Comment by Rickertje** [comment]
Hi @jhruehl can you give an update for this issue. Along with maybe the possible duplicates #16604 and #18059 . Thank you.

**Comment by jhruehl** [comment]
@Rickertje I see both cases are valid. The case from this issue and my case. I don't know, if my solution/adjustment given in  https://github.com/jhruehl/magento2/commit/fed80e247dfbb5e504de366db4e3a18a114d2a23 still solves the issue given here. And I don't have the time to spare to recreate and test the scenario given by the author of the issue with my adjustment.

So we will handle it as we handle most of the bugs, "unconveniant" fixes and changes given by Magento. Creating a core patch, which serves our needs, document it for the next update (with references to exisiting issues) and see if the core patch is still needed or has to be adjusted during the implementation of the next Magento update.

I'd advise your developers to do so in a similar fassion. Saves a lot of time.

Here is a howto for creating patches:
https://docs.gitlab.com/omnibus/development/creating-patches.html
(you should create and apply them in the source folder of the project; we apply them with a different command though)

(Or we throw the problem at the Magento Commerce Support as soon as 2.3 is released officially and let them handle it.)

**Comment by deadlyw1re** [comment]
Why is the shipping price on the website level instead of storeview level?

**Comment by krzysztofjasniok** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
@krzysztofjasniok thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by krzysztofjasniok** [comment]
Unable to reproduce on Magento 2.3 with given steps. Tested with flat rate as well as tablerates
