### ISSUE TITLE
Can't add grouped product, with out of stock sub product, to cart

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#12970]
When "Stores -> Configuration -> Catalog -> Inventory -> Options -> Display Out of Stock Products" config enabled.
Can't add grouped product, which haves out of stock sub product, to cart.

### Preconditions

1. Magento 2.1.8 CE/EE
2. nginx/1.10.3
3. Ver 15.1 Distrib 10.0.31-MariaDB
4. PHP 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce

1. Create grouped product with one out of stock sub product 
2. Set default sub products quantities biggest then "0"
http://pix.toile-libre.org/upload/original/1514981790.png
2. Set "Stores -> Configuration -> Catalog -> Inventory -> Options -> Display Out of Stock Products" to "Yes"
3. Go to grouped product PDP
4. Add product to cart

### Expected result

1. Sub products which are "In stock" is added to cart

### Actual result

1. No one product added to cart:
http://pix.toile-libre.org/upload/original/1514981851.png

**Comment by magento-engcom-team** [comment]
@breg-13, thank you for your report.
We've created internal ticket(s) MAGETWO-86389 to track progress on the issue.

**Comment by ashvinim0003** [comment]
Facing the same issue.
Let me know what is the quick fix for this issue.

**Comment by adamlavery** [comment]
This issue can be resolved by setting the grouped product Manage Stock = No. 

@magento-engcom-team, should grouped products be fixed to manage_stock=no? The grouped product is just a display container. There should never be any stock of the container to manage.

**Comment by CompactCodeEU** [comment]
I am having the same issue. When there is 1 assoc product with no stock then it just returns 'please specify quantities of product(s)"

**Comment by magento-engcom-team** [comment]
Hi @breg-13. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1169 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - [7d4465670326ad09d15985091d40834f6ec040f9](https://github.com/magento/magento2/commit/7d4465670326ad09d15985091d40834f6ec040f9)
 - [42b4f3c7180fa1a56354c4e8466c32fa5882ada0](https://github.com/magento/magento2/commit/42b4f3c7180fa1a56354c4e8466c32fa5882ada0)
 - [da05e921b80ac0766b3965d1e693e7da742abb72](https://github.com/magento/magento2/commit/da05e921b80ac0766b3965d1e693e7da742abb72)
 - [40600b9aea44981db11b8094fd9b78ba5a91c904](https://github.com/magento/magento2/commit/40600b9aea44981db11b8094fd9b78ba5a91c904)
 - [63c7fc9b795d9ad284f546b80f8ae6a0c64b46f6](https://github.com/magento/magento2/commit/63c7fc9b795d9ad284f546b80f8ae6a0c64b46f6)
 - [26b6a27ca619468f33165b4481bcc4bce9a56f95](https://github.com/magento/magento2/commit/26b6a27ca619468f33165b4481bcc4bce9a56f95)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @kirillvidyuk. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#2315 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [f631c90376dd2d217686e781147cc707bd816c8f](https://github.com/magento/magento2/commit/f631c90376dd2d217686e781147cc707bd816c8f)

The fix will be available with the upcoming 2.3.1 release.

**Comment by bart42functions** [comment]
Hi,

It is still not working in version 2.3.1.
Line 347 of app/code/Magento/GroupedProduct/Model/Product/Type/Grouped.php
`if ($isStrictProcessMode && !$subProduct->getQty()) {
                    return __('Please specify the quantity of product(s).')->render();
                }`
will still throw an error. Removing it seems to work tho

**Comment by stephan-cream** [comment]
This issue has not been resolved yet.

**Preconditions**
Magento 2.1.* , 2.2.*, 2.3.* CE/EE
DB: Any
PHP: Any

**Steps to reproduce:**

1. Create a grouped product
2. Create two simple products
3. Add two simple sub-products to the grouped product
4. Set default quantity to 0 for each simple product association.
5. Give sub-product 1 a stock quantity of 0 and the status 'Out of stock'.
6. Give sub-product 2 a stock quantity of 10 and the status 'In stock'.
7. Configure "Stores -> Configuration -> Catalog -> Inventory -> Options -> Display Out of Stock Products" to 'Yes'.
8. (Optionally) Reindex inventory and flat tables.
9. Go to the grouped product's detail page.
10. Attempt to add sub-product 2 (which has stock).

**Expected result:**
- Grouped product with sub-product 2 is added to the cart.
- No errors occur.

**Actual result:**
- Error is thrown "Please specify the quantity of product(s)." through the message manager
- Grouped product with sub-product 2 is not added to the cart.

What i don't understand is why `if ($isStrictProcessMode && !$subProduct->getQty())` is there.
If you don't have a default quantity, which is used to determine how many of the sub-product should be added or if it is set to 0, it should just ignore the sub-product in the first place.
The code beyond this if statement is NEVER reached as the `Magento\Quote\Model\Quote function addProduct` function always uses `\Magento\Catalog\Model\Product\Type\AbstractType::PROCESS_MODE_FULL` which results in `$isStrictProcessMode === true`.
Seeing as we set the default quantity to 0, it results in `!$subProduct->getQty() === true`.

**There are two possible solutions:**

1. Remove the if statement altogether, however this would break backwards compatibility as `$isStrictProcessMode` would no longer be used and would need to be removed from the function parameters and the calls made to the function.
2. Instead of `!$subProduct->getQty()` use `(!is_numeric($subProduct->getQty()) || $subProduct->getQty() < 0)`, since 0 is still a valid default quantity.
So you would get `if ($isStrictProcessMode && (!is_numeric($subProduct->getQty()) || $subProduct->getQty() < 0)) {`.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17572`, `MC-17573` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by stephan-cream** [comment]
I forgot to mention this by the way, but the error is thrown because of the 'Out of stock' product.
Since it is out of stock, the input field for this out of stock product is not submitted (or even shown).
As such the following if statement returns true `(!isset($productsInfo[$subProduct->getId()])`.
This does not occur when there are only 'In stock' products and the default quantity is set to 0 on the sub-product associations.

**Comment by magento-engcom-team** [comment]
Hi @kirillvidyuk. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-17573` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by romeof1980** [comment]
We can confirm this issue has not been resolved yet.

Preconditions
Magento 2.4.3-p1 CE
PHP: 7.4.27

**Steps to reproduce:**
Create a grouped product
Create a few simple products
Add two or more simple sub-products to the grouped product
(In the grouped) Set "default quantity to 0 for each simple product association.
Give sub-product 1 a stock quantity of 0 and the status 'Out of stock'.
Give sub-product 2 a stock quantity of 10 and the status 'In stock'.
Configure "Stores -> Configuration -> Catalog -> Inventory -> Stock Options -> Display Out of Stock Products" to 'Yes'.
(Optionally) Reindex inventory and flat tables.
Go to the grouped product's detail page.
Attempt to add sub-product 2 (which has stock).

**Expected result:**
Grouped product with sub-product 2 is added to the cart.
No errors occur.

**Actual result:**
Error is thrown "Please specify the quantity of product(s)." through the message manager
Grouped product with sub-product 2 is not added to the cart.

Citing again https://github.com/magento/magento2/issues/12970#issuecomment-503081269 thanks @stephan-cream 
same for me after debuggign: 
What i don't understand is why if ($isStrictProcessMode && !$subProduct->getQty()) is there.
If you don't have a default quantity, which is used to determine how many of the sub-product should be added or if it is set to 0, it should just ignore the sub-product in the first place.
The code beyond this if statement is NEVER reached as the Magento\Quote\Model\Quote function addProduct function always uses \Magento\Catalog\Model\Product\Type\AbstractType::PROCESS_MODE_FULL which results in $isStrictProcessMode === true.
Seeing as we set the default quantity to 0, it results in !$subProduct->getQty() === true.

There are two possible solutions:

Remove the if statement altogether, however this would break backwards compatibility as $isStrictProcessMode would no longer be used and would need to be removed from the function parameters and the calls made to the function.
Instead of `!$subProduct->getQty()` use `(!is_numeric($subProduct->getQty()) || $subProduct->getQty() < 0)`, **since 0 is still a valid default quantity.**
So you would get if ($isStrictProcessMode && (!is_numeric($subProduct->getQty()) || $subProduct->getQty() < 0)) {.

**Comment by romeof1980** [comment]
@magento give me 2.4-develop instance

**Comment by romeof1980** [comment]
@magento give me 2.4-develop instance

**Comment by romeof1980** [comment]
@magento give me 2.4.3 instance

**Comment by romeof1980** [comment]
how weird I can't reproduce this. I really can't understand how it can add due to the following:

**Comment by romeof1980** [comment]
@magento give me 2.4.3-p1 instance

**Comment by romeof1980** [comment]
ok not able to reproduce on vanilla 2.4.3. **Not a bug**.
Just for reference: reproduced on custom installations where an AFTER plugin returns true/false listening on Magento\Catalog\Model\Product->isSalable
this is why it enters the return error warning message in the following snippet:
```
 if (!isset($productsInfo[$subProduct->getId()])) {
                if ($isStrictProcessMode && !$subProduct->getQty() && $subProduct->isSalable()) {
                    return __('Please specify the quantity of product(s).')->render();
                }
```
this is how it works:
`$productsInfo[$subProduct->getId()] `
this excludes from the check all the grouped (associated) products that are in the addtocart POST request i.e. in $productsInfo (even the products with qty==0 are present in the array. They will be considered correctly with qty-to-be-added==0)

`&& $subProduct->isSalable()`
this will NEVER be checked against products that have the quantity field in the list: only against products that are not available in the list (in vanilla they appear in the frontend grouped list as "out of stock" products.

**Comment by sdouma** [comment]
@romeof1980 thanks for going that deep. It is appreciated
