### ISSUE TITLE
2.2.2 - Duplicating Bundle Product Removes Bundle Options From Original Product

### ISSUE THREAD

**Issue by MattUnity** [magento/magento2#13126]
I can't seem to duplicate bundle products and retain their bundle options on a Vanilla 2.2.2 installation - It moves the bundle options over but doesn't appear to retain them for the original product, leaving it blank and stripping its options.

### Preconditions
1. Magento 2.2.2 
2. PHP 7.0.27

### Steps to reproduce
1. Create a simple product
2. Create a bundle product, adding the aforementioned simple product as a bundle option
3. Click Save he bundle product
3. Click Save and Duplicate the bundle product

### Expected result
1. Both the original and duplicated bundle products should contain the simple product as a bundle option.

### Actual result
1. The duplicated bundle product contains the bundle options, but the original product has bundle options removed.

**Comment by magento-engcom-team** [comment]
@MattUnity, thank you for your report.
We've created internal ticket(s) MAGETWO-86647 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @MattUnity. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1217 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - b57eb03b2f6491d271221d08b185e2ff37bfcd4c
 - d8bd657c94175392eca5ad462932bc2e86c51257

The fix will be available with the upcoming patch release.

**Comment by densen45** [comment]
Unfortunately, the fix is not included in the 2.2.3 release. However, it is currently included in the 2.2.4-preview branch.

**Comment by macrodesignuk** [comment]
This problem still exists in v2.3.0, has this fix been made live?

**Comment by getsolved** [comment]
Problem still exists in 2.3.0
When will it be fixed? Mass creation of products very annoying.
No solution in over a year??

**Comment by macrodesignuk** [comment]
> Problem still exists in 2.3.0
> When will it be fixed? Mass creation of products very annoying.
> No solution in over a year??

They have fixed it, they just haven't released the patch. Its annoying as a lot of the Magento 2 faults I've experienced were fixed 1 year ago, but they haven't officially released them yet. 

You can replace the related problem files from here 
https://github.com/magento/magento2/commit/b57eb03b2f6491d271221d08b185e2ff37bfcd4c
https://github.com/magento/magento2/commit/d8bd657c94175392eca5ad462932bc2e86c51257

**Comment by Goeny** [comment]
Problem still not fixed ?

**Comment by hostep** [comment]
Re-opening, since it looks like the fix never was forward ported to the `2.3-develop` branch.
If someone wants to take a stab at it, please do so :)

**Comment by AlexWorking** [comment]
Issue is really reproduced only on 2.3-develop (fixed on 2.2-develop). Steps to Reproduce here have been slightly modified: there has been added an additional step number 3. Without it the issue won't reproduce - if You start to create a new bundle product and instead of Save You click Save and Duplicate everything will work as expected, e.g. two bundle products with the same bundle option will be created.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99840` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Goeny** [comment]
Why is this issue still not resolved?

How can i implement a manual fix in either 2.3.1 or 2.3.2 ?

**Comment by macrodesignuk** [comment]
@magento-engcom-team @magento-team 
Why has this fix not been applied to the official Magento release yet? The fix works.

I recently updated to 2.3.2 which caused Magento to revert back to the old broken version and overridden my manual file fix.

**Comment by hostep** [comment]
@macrodesignuk, or somebody else: can you create a pull request with the suggested fixes, it will be much quicker integrated in Magento that way than endlessly waiting for Magento core devs to finally take a look at this. Thanks! 🙂

**Comment by macrodesignuk** [comment]
> @macrodesignuk, or somebody else: can you create a pull request with the suggested fixes, it will be much quicker integrated in Magento that way than endlessly waiting for Magento core devs to finally take a look at this. Thanks!

Thanks Pieter, I just tried to fork it and the related file is completely different in the fork copy to that of the official release. It looks like somebody has rewritten the fix, but it is significantly different. Not sure what to do in this case.

**Comment by hostep** [comment]
Hi @macrodesignuk, I just created a PR for this at https://github.com/magento/magento2/pull/24703

It wasn't very difficult, just cherry-picked the two commits mentioned above on the 2.3-develop branch, which applied cleanly, had no conflicts to solve.

**Comment by macrodesignuk** [comment]
@hostep Thanks,

The reason I didn't do it was because the version that they give on the released version of Magento is not the same as in that development branch. Therefore its not patching the same file and could cause a problem. Hopefully it all works out though, thank you for your help

**Comment by magento-engcom-team** [comment]
Hi @MattUnity. Thank you for your report. 
The issue has been fixed in magento/magento2#24703 by @hostep in 2.3-develop branch
Related commit(s):
 - [f1a187eba85b2eaeca4c619c1482ca8916fdb284](https://github.com/magento/magento2/commit/f1a187eba85b2eaeca4c619c1482ca8916fdb284)
 - [bf36defe362496ecb6f6b7693600a9054fbd801b](https://github.com/magento/magento2/commit/bf36defe362496ecb6f6b7693600a9054fbd801b)
 - [629fcdfc22c35ce0cc2f3732b54b9885e8b2b362](https://github.com/magento/magento2/commit/629fcdfc22c35ce0cc2f3732b54b9885e8b2b362)

The fix will be available with the upcoming 2.3.4 release.

**Comment by YiffyToys** [comment]
We just experienced this in Magento 2.4.7-p1

**Comment by codingkoaladev** [comment]
It is also in 2.4.7-p3

**Comment by Goeny** [comment]
We experience this in 2.4.7-p4
