### ISSUE TITLE
Clicking the close button of the full screen gallery causes elements underneath to be clicked

### ISSUE THREAD

**Issue by chefbuitenhuis** [magento/magento2#13382]
There are multiple issues opened on this, each without an actual resolution. This is something which should be fixed as it is undesired behavior.

### Preconditions
1. Any version of 2.1
2. For example this demo shop: magento2-demo.nexcess.net

### Steps to reproduce
1. Use Chrome and go into the mobile inspector to any mobile device.
2. Visit a PDP
2. Open the fullscreen gallery
3. Click on the "X" 

### Expected result
1. Gallery should close, mini-cart should stay closed and it shouldn't redirect.

### Actual result
1. Notice how the click is passed through the elements underneath and opens the mini-cart/goes to the account page.

**Comment by magento-engcom-team** [comment]
@chefbuitenhuis, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sweethurricane7** [comment]
The same here, tested on 2.1.11

**Comment by magento-engcom-team** [comment]
@chefbuitenhuis The issue is already fixed in 2.2.2 onward.
Closing ticket for now. Please reopen if you need any further assistance with this.

**Comment by Ctucker9233** [comment]
@magento-engcom-team What are the commits for this issue?

**Comment by lcastro-art** [comment]
Hello, this error is still occurring in the Magento 2.4.5-p1 version, could this ticket be reopened? Thank you.
