### ISSUE TITLE
Why doesn't shipping total segment respect tax settings like e.g. subtotal does?

### ISSUE THREAD

**Issue by vaaralav** [magento/magento2#13392]
### Preconditions

1. 2.1.9

### Steps to reproduce

1. Choose "Including Tax" setting for Display Shipping Prices and Display Shipping Amount.
2. Create a (guest) cart
3. Call `/rest/V1/guest-carts/<the_id_here>/totals-information` for the cart
 

### Expected result

1. The `value` property for shipping segment in `responseData.total_segments` includes the tax.

### Actual result

1. The `value` property of shipping segment in `responseData.total_segments` excludes the tax.
2. Below is a screenshot of `/checkout/cart` page and the `totals-information` response.

<img width="643" alt="screen shot 2018-01-26 at 16 52 31" src="https://user-images.githubusercontent.com/8571541/35445274-cf0a941e-02b9-11e8-92c6-3719942f966a.png">

**Comment by magento-engcom-team** [comment]
@vaaralav  thank you for your report,
Please try to reproduce this issue on the clean installation use one of the standard shipping methods Magento and tell us the result.

**Comment by vaaralav** [comment]
@magento-engcom-team 
Same thing happens with fresh Magento-CE-2.1.9_sample_data-2017-09-13-03-57-21.tar.gz installation.
<img width="910" alt="screen shot 2018-01-30 at 14 35 05" src="https://user-images.githubusercontent.com/8571541/35566680-e85309b0-05ca-11e8-8e8d-b29b7e545322.png">

## Tax Settings
![tax-settings](https://user-images.githubusercontent.com/8571541/35566861-976345c8-05cb-11e8-89a2-8545136ff0ed.png)

**Comment by magento-engcom-team** [comment]
@vaaralav thank you for your report
In your cases, you used third-party extensions for shipping. Please try to reproduce this issue by standard shipping methods and tell us your result.

**Comment by vaaralav** [comment]
@magento-engcom-team what are the standard shipping methods here? There's nothing but Magento 2 with sample data in the second example.

To clarify the screenshots were from `/checkout/cart` page. Here's the same thing in `/checkout/#payment` view if it helps you
<img width="922" alt="screen shot 2018-02-01 at 10 09 26" src="https://user-images.githubusercontent.com/8571541/35667947-2ad5e1e0-0738-11e8-8c05-7ec60e6328f5.png">

**Comment by magento-engcom-team** [comment]
@vaaralav, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dennisderoo** [comment]
Is this fixed in 2.3.2 ?

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

1. Choose "Including Tax" setting for Display Shipping Prices and Display Shipping Amount.
2. Create a (guest) cart
3. Call `/rest/V1/guest-carts/<the_id_here>/totals-information` for the cart

**Result**
The `value` property for shipping segment in `responseData.total_segments` includes the tax.
![Screenshot_9](https://user-images.githubusercontent.com/51681435/70541866-76b3bf80-1b70-11ea-8de8-0249c44b127d.png)
So I have to close this issue.
Thanks for your report!

**Comment by mrkhoa99** [comment]
Our commits for this issue? still having this issue on Magento 2.3.5-p1 @sdzhepa

**Comment by simonmaass** [comment]
I am able to reproduct this issue on a clean m2.4.0 installation!

![image](https://user-images.githubusercontent.com/32599710/96113957-35551480-0ee5-11eb-9672-8accfd48b8ce.png)

![image](https://user-images.githubusercontent.com/32599710/96114013-4dc52f00-0ee5-11eb-926c-5bff5b12f972.png)

This doesnt seem to be fixed!

**Comment by simonmaass** [comment]
@engcom-Echo  @vaaralav just reproduced this issue in 2.4.1!

**Comment by eerohakio** [comment]
Can also confirm that this is reproducable in 2.4.1

**Comment by eerohakio** [comment]
For subtotal there seems to be own logic inside: module-tax/Model/Sales/Total/Quote/Tax.php
`   /**
         * Modify subtotal
         */
        if ($this->_config->displayCartSubtotalBoth($store) || $this->_config->displayCartSubtotalInclTax($store)) {
            if ($total->getSubtotalInclTax() > 0) {
                $subtotalInclTax = $total->getSubtotalInclTax();
            } else {
                $subtotalInclTax = $total->getSubtotal() + $taxAmount - $total->getShippingTaxAmount();
            }

            $totals[] = [
                'code' => 'subtotal',
                'title' => __('Subtotal'),
                'value' => $subtotalInclTax,
                'value_incl_tax' => $subtotalInclTax,
                'value_excl_tax' => $total->getSubtotal(),
            ];
        }
`
This logic however is missing for shipping reader

**Comment by eerohakio** [comment]
Created this patch, use with precaution however as this is only tested with Including tax config settings..

```
--- a/vendor/magento/module-tax/Model/Sales/Total/Quote/Shipping.php	2020-10-28 10:15:59.000000000 +0200
+++ b/vendor/magento/module-tax/Model/Sales/Total/Quote/Shipping.php	2020-10-28 10:16:44.000000000 +0200
@@ -72,12 +72,22 @@
      */
     public function fetch(\Magento\Quote\Model\Quote $quote, \Magento\Quote\Model\Quote\Address\Total $total)
     {
-        if ($total->getShippingInclTax()) {
+        if (!$total->getShippingInclTax()) {
+            return null;
+        }
+
+        if ($this->_config->displayCartShippingBoth() || $this->_config->displayCartShippingInclTax()) {
             return [
                 'code' => 'shipping',
-                'shipping_incl_tax' => $total->getShippingInclTax()
+                'shipping_incl_tax' => $total->getShippingInclTax(),
+                'value' => $total->getShippingInclTax(),
+                'value_incl_tax' => $total->getShippingInclTax()
             ];
         }
-        return null;
+
+        return [
+            'code' => 'shipping',
+            'shipping_incl_tax' => $total->getShippingInclTax()
+        ];
     }
 }
```

**Comment by dio5** [comment]
I am not quite getting @engcom-Echo's reply. In his comment he's saying it includes tax but if you look closely it seems without tax to me - 4.9 + 0.1 = 5.

See my screenshot. Maybe it's supposed to be without tax?

![shipping_tax](https://user-images.githubusercontent.com/628642/111798578-7e612880-88ca-11eb-8e83-426f740ae17e.png)

**Comment by harihhs** [comment]
@magento-engcom-team 
This is issue is still reproducible in M 2.4.4. Should be re-opened
