### ISSUE TITLE
Invoice Sales Email not send

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#13466]
### Preconditions

1. Magento 2.2.2
2. OS: Ubuntu 16.04
3. Mysql version 5.7.21
4. PHP version 7.0.22

### Steps to reproduce

1. Set up "Stores -> Settings -> Configuration -> Sales -> Sales Emails -> Invoice -> Enabled -> Yes"
2. Configure PayPal "Stores -> Settings -> Configuration -> Sales -> Payment Methods -> PayPal -> Payment Action -> Sale"
3. Make order and pay with PayPal.

### Expected result

1. Order Created
2. Email with order information send.
3. Invoice Created
4. Email with invoice information send

### Actual result

1. Order Created <- ok
2. Email with order information send. <- ok
3. Invoice Created <- ok
4. Email with invoice information is not send <- wrong

Overview docs http://docs.magento.com/m2/ce/user_guide/configuration/sales/sales-emails.html
Since sales emails for invoice is enabled Magento should sends a transactional email for each invoice generated.

**Comment by sivajik34** [comment]
@LordHansolo Asynchronous sending enabled? then it should run through cron.
You can refer https://magento.stackexchange.com/questions/198779/how-does-asynchronous-email-sending-works-in-magento-2

**Comment by LordHansolo** [comment]
@sivajik34 Thank you for response.
Now I understand that config is only for "Asynchronous sending".
I expected that email with invoice is send always after invoice is generated regardless "Asynchronous sending" configuration.
I expected that especially when you pay via PayPal with "Payment Action" set on "Sale". Invoice is generated automatically with status Paid if everything is correct but email is not send.

**Comment by sivajik34** [comment]
if Asynchronous sending disabled:
then flow
step1:
magento/module-sales/etc/events.xml:      
  `<observer name="sales_send_order_invoice_emails" instance="SalesOrderInvoiceSendEmailsObserver" />`
step2:
magento/module-sales/etc/di.xml:   
```
 <virtualType name="SalesOrderInvoiceSendEmailsObserver" type="Magento\Sales\Observer\Virtual\SendEmails">
        <arguments>
            <argument name="emailSenderHandler" xsi:type="object">SalesOrderInvoiceSendEmails</argument>
        </arguments>
    </virtualType>
```

```
 <virtualType name="SalesOrderInvoiceSendEmails" type="Magento\Sales\Model\EmailSenderHandler">
        <arguments>
            <argument name="emailSender" xsi:type="object">Magento\Sales\Model\Order\Email\Sender\InvoiceSender</argument>
            <argument name="entityResource" xsi:type="object">Magento\Sales\Model\ResourceModel\Order\Invoice</argument>
            <argument name="entityCollection" xsi:type="object" shared="false">Magento\Sales\Model\ResourceModel\Order\Invoice\Collection</argument>
        </arguments>
    </virtualType>
```


step 3:
Magento\Sales\Observer\Virtual\SendEmails:
```
 /**
     * Handles asynchronous email sending during corresponding
     * cron job.
     *
     * Also method is used in the next events:
     *
     * - config_data_sales_email_general_async_sending_disabled
     *
     * Works only if asynchronous email sending is enabled
     * in global settings.
     *
     * @param \Magento\Framework\Event\Observer $observer
     * @return void
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $this->emailSenderHandler->sendEmails();
    }
```

here emailSenderHandler -> Magento\Sales\Model\EmailSenderHandler

 ```
/**
     * Handles asynchronous email sending
     * @return void
     */
    public function sendEmails()
    {
        if ($this->globalConfig->getValue('sales_email/general/async_sending')) {
            $this->entityCollection->addFieldToFilter('send_email', ['eq' => 1]);
            $this->entityCollection->addFieldToFilter('email_sent', ['null' => true]);

            /** @var \Magento\Sales\Model\AbstractModel $item */
            foreach ($this->entityCollection->getItems() as $item) {
                if ($this->emailSender->send($item, true)) {
                    $this->entityResource->save(
                        $item->setEmailSent(true)
                    );
                }
            }
        }
    }

```

**even if you disable async finally its calling async code**. still, i have some confusion implementation of this.

**Comment by LordHansolo** [comment]
@sivajik34 One more time thank you.
I updated my previous comment.
Now it is clear, that invoice email is not send if "Asynchronous sending" is disabled.
During read configuration files, especially magento/module-sales/etc/events.xml with fragment below:
`<event name="config_data_sales_email_general_async_sending_disabled">
    ...
</event>`
I had hape that emails should be send but after fully code read my hope has gone out ;)

**Comment by lucscu** [comment]
some progress on this issue?

**Comment by ghost** [comment]
Hi @LordHansolo thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by nntoan** [comment]
@engcom-backlog-nazar Any progress so far?

**Comment by avaldi** [comment]
Guys, any update on this?

**Comment by Darkbelg** [comment]
We are experiencing this issue. Is there any timeframe when this is going to be fixed ?

**Comment by deloenzien** [comment]
will this be solved in 2.3.1?

**Comment by fabrice-dresscodes** [comment]
Hello. Any progress or fix ?

**Comment by deloenzien** [comment]
Enable Asynchronous sending. Then cron takes care of sending e-mails.
This works for me.

**Comment by fabrice-dresscodes** [comment]
In which version of Magento. On 2.2.3 with asynchronous sending it doest not work for me.

When I invoice manually and check Send Mail it works.

**Comment by nadeefit6** [comment]
The issue can be reproduced in 2.2.7 as well.
Other than "Asynchronous sending" Invoice email sending is not developed in Paypal module.

**Comment by magento-engcom-team** [comment]
Hi @nadeefit6. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by rav-redchamps** [comment]
Hey Guys,

This extension should solve the problem.

https://redchamps.com/invoice-email-magento-2-extension.html

**Comment by neddy236** [comment]
I have a Magento 2.3.1 installation and this issue seems like its still present

**Comment by Julen10** [comment]
Hi guys,
I know this still in progress but, did you solved it by doing something?
I have tried to enable the Async sending but still not receiving the Invoice mail.
Thanks a lot

**Comment by yekyo** [comment]
Hi guys,
I fixed this bug.
https://github.com/py4762013/Magento_AutoInvoiceEmail

**Comment by sjgdk** [comment]
> Hi guys,
> I fixed this bug.
> https://github.com/py4762013/Magento_AutoInvoiceEmail

I have tried your code, but it is not working. However, I do not know how to debug your code either.

Edit: Just to remind everyone, both enabling or disabling async are not working, the invoice won't be sent even if you enable it.

**Comment by deckside** [comment]
I don't know what is causing the actual problem but I have a workaround.

Invoices seem to be sent OK if the customer has an account. It looks like the New Invoice Guest Template is faulty.

Go to Marketing> Email Templates>Add New Template
Load default template from New Invoice. 
Make any changes and save as New Invoice Guest Custom.

Go to Stores>Configuration>Sales>Sales Emails>
Under Invoice > Invoice Email Template for Guest. change this to the new template you saved.

Flush cache

**Comment by Julen10** [comment]
@deckside I have done it since the creation of the web. I have my own template with css. I can't solve it like that :S

I have made a workaround using API and creating my own script.

**Comment by LiamKarlMitchell** [comment]
Tried the work around suggested above by @py4762013 also tried new templates but no luck :(
Does not work for guest or logged in customer.
This might be impacting other Payment Methods I know it does for PoliPay and Payment Express..

**Comment by magento-engcom-team** [comment]
Hi @LordHansolo. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [5ccd367ebc628b588a77cb2032faeabd6005b039](https://github.com/magento/magento2/commit/5ccd367ebc628b588a77cb2032faeabd6005b039)
 - [953e034762cb79c5a187426f979cceeec2617b11](https://github.com/magento/magento2/commit/953e034762cb79c5a187426f979cceeec2617b11)

The fix will be available with the upcoming `2.3.4` release.

**Comment by LiamKarlMitchell** [comment]
@magento-engcom-team 
Will the above commits work to patch this on Magento <2.3.4 such as 2.3.0?

What about shipment tracking emails?

Edit:

Okay the paid module from rav-redchamps resolves this for invoice emails, but not for shipment tracking emails. It's quite a simple work-around well done.

**Comment by ovidiucaramida** [comment]
This module will make your invoice emails work
https://webpanda-solutions.com/auto-invoice-shipment.html
It works with offline payment methods, online payment methods with action Authorize also with Authorize and Capture.

**Comment by ilnytskyi** [comment]
@magento-engcom-team @StasKozar @viktym 
the code from, supposed to be released in 2.3.4  
https://github.com/magento/magento2/commit/5ccd367ebc628b588a77cb2032faeabd6005b039

and actual 2.3.4 and 2.4-develop is a bit different
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Observer/SubmitObserver.php

so as we understand now the customer will always have 2 emails after order placing ?

**Comment by engcom-Charlie** [comment]
Hello, @LordHansolo looks like the issue already fixed on the latest 2.4-develop please see https://github.com/magento/magento2/pull/27739#issuecomment-750865450.
Please feel free to comment, reopen, or create a new ticket if you are still facing this issue on the latest `2.4-develop` branch. Thank you for your collaboration.

Thanks for your report!

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by drinkingsouls** [comment]
I also have an issue with Magento Invoice emails not being sent automatically. Manual sends fine. Asynchronous is enabled but stll doesn't send. Other emails send fine.
