### ISSUE TITLE
Sorting in Product Listing via Quantity not work

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#13556]
### Preconditions

1. Magento 2.2.2
2. OS Ubuntu 16.04
3. Server Apache version 2.4.18
4. MySQL version 5.7.21
5. PHP version 7.0.22
### Steps to reproduce

1. Set quantity_and_stock_status product attribute to be "Used for Sorting in Product Listing".
![sorting_via_quantity_admin](https://user-images.githubusercontent.com/22025597/35969544-7cf481fe-0cc7-11e8-8cee-0520510e94a4.png)
2. Set different quantities for products.
3. Go to Category Page on storefront and try sort via Quantity.

### Expected result

1. Product are sorted from the lowest to the highest quantity or from the highest to the lowest quantity.

### Actual result

1. Products are sorted via Position.

**Comment by magento-engcom-team** [comment]
@LordHansolo, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @LordHansolo. Thank you for your report. 
The issue has been fixed in magento/magento2#13691 by @nuzil in 2.2-develop branch
Related commit(s):
 - [24d1e790015557c0a7723b14f1f9b4b559d0f3a0](https://github.com/magento/magento2/commit/24d1e790015557c0a7723b14f1f9b4b559d0f3a0)
 - [aee70865e1a6c795d25335770daed3d399ad13b6](https://github.com/magento/magento2/commit/aee70865e1a6c795d25335770daed3d399ad13b6)
 - [c7132d14ae3fcc064d94f4d92e4f9d138a3a60a9](https://github.com/magento/magento2/commit/c7132d14ae3fcc064d94f4d92e4f9d138a3a60a9)
 - [a7b08069b8362945e6393d181235ff361978df59](https://github.com/magento/magento2/commit/a7b08069b8362945e6393d181235ff361978df59)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @LordHansolo. Thank you for your report. 
The issue has been fixed in magento/magento2#14179 by @dimonovp in 2.3-develop branch
Related commit(s):
 - [ce6dd8572efc5802b5b9d9f2257b2dce30e8ff9d](https://github.com/magento/magento2/commit/ce6dd8572efc5802b5b9d9f2257b2dce30e8ff9d)
 - [a6dc79ac003855cda3df4f17d4645f0dd29373dd](https://github.com/magento/magento2/commit/a6dc79ac003855cda3df4f17d4645f0dd29373dd)
 - [bcb553c40e0becae8a164f3902cd61c5e2d3447e](https://github.com/magento/magento2/commit/bcb553c40e0becae8a164f3902cd61c5e2d3447e)
 - [551fa251b53b92743eb4fd830e2d029c30788449](https://github.com/magento/magento2/commit/551fa251b53b92743eb4fd830e2d029c30788449)

The fix will be available with the upcoming 2.3.0 release.

**Comment by umgeric** [comment]
I have same problem on Magento 2.2.2, I added 2 files changed in this commit to /vendor directory. But it did not fix my problem. 
\vendor\magento\module-catalog-inventory\Model\Source\Stock.php
\vendor\magento\module-catalog-inventory\Test\Unit\Model\Source\StockTest.php

What I missing now?
