### ISSUE TITLE
Magento 2 - Update qty & Addresses Button Not updating  first item on  Ship to Multiple Addresses page in Multi-shipping

### ISSUE THREAD

**Issue by pradeeprcs** [magento/magento2#13646]
### Preconditions

1. M 2.1.7
2. 

### Steps to reproduce

1.  add two item to cart
2. checkout as multi shipping 
3.  In first page that is Ship to Multiple Addresses you can see  drop down for each item
4. change the address from default to some other address 
5. click on  Update qty & Addresses Button

### Expected result

1.  Should update a address as selected address of each items

### Actual result

1.  First item address was reset to default address (may be its setting null address or default shipping address)
2. but its sets correct address for rest of item except first item

**Comment by magento-engcom-team** [comment]
@pradeeprcs, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@pradeeprcs The issue is already fixed in 2.2.2 onward.
Closing ticket for now. Please reopen if you need any further assistance with this.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Was this fixed in 2.1? What are the commits for this issue?

**Comment by pradeeprcs** [comment]
@magento-engcom-team :-  Can i get commit id ? or modified files ? so i can push to m 2.1.7

**Comment by mertgokceimam** [comment]
@magento-engcom-team this is not fixed on 2.2.9 and the issue is still reproducible. We've found out this issue when we were also debugging a flow that was not correctly working.

Another ticket where Magento failed to patch in 3 years and claim they patch where patch fails to work and causing tons of hour - money waste to EE customers.
