### ISSUE TITLE
Add to Cart Form wrong Form Key in FPC

### ISSUE THREAD

**Issue by alexgoodey** [magento/magento2#13746]
When the page initially loads the form*key that is placed on the page is cached between independent requests. This is not an issue if the entire page loads before the "Add to Cart" button is pressed, however if the Add to Cart is clicked before the Javascript has fully initialized (and therefore the form is actually posted via a standard POST HTTP request) then the form*key that is sent in the form data does not match the users session and the product is not added to the cart.

### Preconditions
1. Magento CE 2.2.2 with sample data installed
1. Full Page Cache enabled 
1. Redirect to cart on "Add to Cart" set to yes in configuration (Sales>Checkout>Shopping Cart)

### Steps to reproduce
1. Open a browser window and navigate to a product page.
1. View the page source and search for the form*key that is part of product_addtocart*form form (form id)
1. Note the form_key down
1. Open an incognito window and navigate to the same product page
1. View the page source again and search for the form_key field

### Expected result
1. The two form_key values should be different

### Actual result
1. The two form_key values are the same (meaning the second one is wrong as it will not match the cookie)

### Additional information
- detailed explanation https://github.com/magento/magento2/issues/13746#issuecomment-368062429
- confirmed for `2.4-develop` https://github.com/magento/magento2/issues/13746#issuecomment-570216197

**Comment by joshdavenport** [comment]
We have literally been looking into this today and are experiencing the same issue. Locally where we don't have a full FPC setup we have no issues. However on our dev/staging/live servers with varnish fully set up we see failed add to carts before JS is initialised. 

We initially saw it sporadically but having come to the conclusion it was a form key issue not 10 minutes before finding this issue report, we identified FPC as the issue so the sporadic nature must come from seeing uncached pages sometimes (works, form key is right) and cached pages other times (doesn't, form key isn't right)

**Comment by magento-engcom-team** [comment]
@alexgoodey , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by alexgoodey** [comment]
Not sure how else I can explain it. Herer are some screenshots.
1. Viewing a product page that is not yet in the FPC. Showing the form_key cookie value (in Chrome)
![uncached_product_page_with_form_key_cookie](https://user-images.githubusercontent.com/2563109/36604963-2e7b2dc4-18b7-11e8-93da-5a67a8cf98fa.png)

2. The page source of the above page view shows the correct form key value in the source
![uncached_product_page_source_showing_same_form_key_value](https://user-images.githubusercontent.com/2563109/36604991-46936c5a-18b7-11e8-8582-96d81ea73f39.png)

3. A second view (now that is in the FPC) of the same product page in an incognito window, showing the form_key cookie value (which, as expected, is different to the above as this is a completely different session)
![cached_product_page_with_form_key_cookie](https://user-images.githubusercontent.com/2563109/36605035-6a5f00c2-18b7-11e8-878d-55ad6211fe7f.png)

4. The page source of the same product page in an incognito window shows the original form_key value not the one belonging to the current (incognito) session
![cache_product_page_source_showing_incorrect_form_key_value](https://user-images.githubusercontent.com/2563109/36605078-8577cbd2-18b7-11e8-9851-41f6b1a8012d.png)

**Comment by magento-engcom-team** [comment]
@alexgoodey , thanks for you update. 
We not reproduced this issue on fresh installiation Magento 2.2.2 CE with sample data. See attachments

Defaul browser window
![screenshot_5](https://user-images.githubusercontent.com/31669971/36671288-be11d9b2-1b03-11e8-9347-d777344d244f.png)


![screenshot_2](https://user-images.githubusercontent.com/31669971/36670958-ae7728e6-1b02-11e8-9090-5940442dc46d.png)


Incognito browser window

![screenshot_3](https://user-images.githubusercontent.com/31669971/36670980-bc683242-1b02-11e8-90ef-6153584e0f99.png)

![screenshot_4](https://user-images.githubusercontent.com/31669971/36670988-c1a9b898-1b02-11e8-8680-67b54709e6fe.png)

The two form_key values should be different

**Comment by alexgoodey** [comment]
Using developer tools won't demonstrate the problem as the Javascript updates the developer tools and this problem is only apparent before Javascript has fully executed. You need to view the page source (i.e. in chrome using "view-source:", which does not execute Javascript) to see the initial form_key that is loaded with the page (and is therefore used if the Add to Cart button is clicked before the Javascript has executed).

**Comment by magento-engcom-team** [comment]
@alexgoodey, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by robmacecs** [comment]
Any update?

**Comment by sodobean** [comment]
Experiencing the same problem in 2.2.4 and now in 2.2.5. Server we are using has and internal dns, server resolves with url http://magentotest, server centos 7 with apache. 

Just to be able to test the cart, I had to comment out this code in Validator.php
`   public function validate(\Magento\Framework\App\RequestInterface $request)

    {

        $formKey = $request->getParam('form_key', null);
//        if (!$formKey || $formKey !== $this->_formKey->getFormKey()) {
 //           return false;

  //      }

        return true;

    }`

**Comment by sangthieu** [comment]
I have same issue. Any update? it is big problem

**Comment by DrewML** [comment]
To make sure I understand the issue correctly, going to try and summarize:

1. `form_key` is a CSRF token
2. The content in the full page cache persists the `form_key` that was generated for the first request with a cold cache
3. The issue is not present once the JS initializes because it takes over form submission and it uses a different value than the `form_key` found in the initial DOM

Is that accurate?

**Comment by sanderjongsma** [comment]
It looks like the form_key in the add to cart form is changed by JS. But when you submit the form to fast it is not yet changed, so submitted with a cached form_key. I recorded it and can show you what is happening in  the dom:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2726055/54607065-b8826000-4a4d-11e9-8cc0-f4edd2436954.gif)

**Comment by cscd98** [comment]
https://github.com/magento/magento2/pull/21007

2.3.2

**Comment by onlinebizsoft** [comment]
I dont think there is any good way to resolve this issue.
- Disable post button until JS executed
- Turn form key into ESI (performance issue)

**Comment by setrada** [comment]
Have the same problem. Did anyone solved it or has a workaround?

**Comment by ananth-iyer** [comment]
I have solved the same issue and during tracing it I've found that the **pageCache** JS component was not added to page HTML. This component is responsible to create form_key.
![1OSX2ckqrF](https://user-images.githubusercontent.com/24892273/66268198-b2709700-e858-11e9-9fb5-355690f3c1e4.png)

After fixing the issue I have found that add to cart is working properly.

**Comment by ReggieTe** [comment]
@ananth-iyer  the patch you suggested is not working and it seems to be already there

**Comment by ReggieTe** [comment]
We're experiencing a very similar issue too but the steps are a bit different to the ones raised by @alexgoodey .The site is a multi-store site and almost every time a user switches stores the issue is highly likely to appear when adding a cross sell item to cart ,the item is not added to bag  and at time even without switching stores the issue appears.  

We checked the form_key in normal mode and incognito mode and they all checks out to be different as expected

**Preconditions**
    Magento EE 2.2.9 with products data
    Full Page Cache enabled  Fastly
    Site is a multiple store

**Steps to reproduce**
   version 1

-  Open a browser window and navigate to a product page.    
-     Switch Store 
-     Add a cross sell item to cart

version 2

-    Open a browser window and navigate to a product page.   
-     Add a cross sell item to cart

**Expected result**
    Product must be added to cart

**Actual result**
    Product page hangs ,product is not added to cart

Has anyone experience a similiar issue on a multi-store

**Comment by engcom-Bravo** [comment]
Hello @alexgoodey 
The issue is not reproducible on Magento 2.4-develop with Sample Data
The form_key values are different in two different browsers. Please see the screenshot
![form_keys](https://user-images.githubusercontent.com/51680745/71660111-b5453000-2d52-11ea-8cb2-e095a3cdad66.png)

So, we have to close this issue.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.

**Comment by alexgoodey** [comment]
@engcom-Bravo 

I refer you to my earlier comment (using developer tools doesn't demonstrate the issue) - from almost 2 years ago!

https://github.com/magento/magento2/issues/13746#issuecomment-368498965

**Comment by onlinebizsoft** [comment]
I can't believe this is the team who have made the Magento product!!!

**Comment by engcom-Bravo** [comment]
@alexgoodey @onlinebizsoft 
Thank you for your comments. 
Sorry, I've acknowledged my mistake. The issue is still present in Magento 2.4-develop
![form_value](https://user-images.githubusercontent.com/51680745/71670678-53e48780-2d79-11ea-8f98-d067d588aed4.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30171` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saroopqs** [comment]
@magento-engcom-team any update on this issue. I am facing issue on Magento 2.3.3 . While adding product into cart with fpc+varnish enabled. Getting formkey invalid issue.

**Comment by iszabo-gcgi** [comment]
Same issue here, running 2.3.3, FPC is on - almost 2 years later... any solution guys?

**Comment by chavesfop** [comment]
Same issue here, running 2.2.10, FPC is on, anything I can do to help to solve?

**Comment by ihor-sviziev** [comment]
Seems like following JS is updating form_key in the all forms. I believe we just need to make it load one of the first and issue will be solved.

https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L100-L126

https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L300-L303

**Comment by gh-darvishani** [comment]
I am using 2.4.1 and the issue still is here

**Comment by ihor-sviziev** [comment]
> I am using 2.4.1 and the issue still is here
> for more information, I upgrade form 2.3.5 to 2.4.1and use Debian as os server
The issue was fixed in https://github.com/magento/magento2/pull/30961. You can apply it as a patch

**Comment by jonathanribas** [comment]
Unfortunately we still have this issue using https://github.com/magento/magento2/pull/30961 as a patch.
Any idea?

**Comment by ihor-sviziev** [comment]
@joshdavenport, are there any steps to reproduce that we can check on the 2.4-develop branch? If so - could you create a new issue for verifying it?

**Comment by joshdavenport** [comment]
To be honest, I'd forgotten this issue was a thing. I remember it being a real pain back when I commented in 2018 but since that period, i.e. over the last couple of years I don't recall seeing this issue manifest in any meaningful way. 

My instinct is that the issue has been resolved and we're seeing the benefit of that but it could also be due to Magento just being much faster. I certainly don't have anywhere I'm managing to easily reproduce. 

Clearly people are still experiencing this issue, but I suspect seeing the issue is more related to faster/slower environments - something that isn't going to be easily reproducible. That's guesswork though, sorry.

**Comment by sodobean** [comment]
Install Linux, (Centos7 ), install apache and all dependencies, install
Magento, try to add an item to the cart, you will be unable to.

**Comment by jonathanribas** [comment]
Just added disabled attribute on Add to Cart button on our theme, a native JS will remove it automatically when all JS files are loaded. That gives the time for `form_key` to be updated correctly. We don't have the issue anymore.

**Comment by ihor-sviziev** [comment]
@jonathanribas, we do have a `disabled` attribute on the add to cart button, but still an issue there.

**Comment by jonathanribas** [comment]
@ihor-sviziev have you applied https://github.com/magento/magento2/pull/30961? Because on our project we have.

**Comment by ihor-sviziev** [comment]
@jonathanribas ah, sorry, I just looked at the wrong issue. This issue was fixed in https://github.com/magento/magento2/pull/30961
