### ISSUE TITLE
Uploading image with REST API works on localhost but not server

### ISSUE THREAD

**Issue by oe-bayram** [magento/magento2#13835]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1.  API call to /rest/V1/products with POST and authentication token
2.  Following body request:
```
{
  "product": {
    "sku": "KT911",
    "name": "PrintaMent2",
    "price": 2.5,
    "status": 1,
    "type_id": "simple",
    "attribute_set_id": 4,
    "weight": 0.5,
    "extension_attributes": {
      "website_ids": [
        1
      ],
      "category_links": [
        {
          "position": 2,
          "category_id": "3"
        }
      ],
      "stock_item": {
        "qty": 99
      }
    },
    "media_gallery_entries": [
      {
        "position": 0,
        "media_type": "image",
        "label": "test",
        "disabled": false,
        "types": [
          "image"
        ],
        "content": {
          "base64_encoded_data": "iVBORw0KGgoAAAANSUhEUgAAAEwAAAA...<cutted_here>",
          "type": "image/png",
          "name": "giropay.png"
        }
      }
    ]
  }
}
```

3. Send requset

### Expected result

1. Created product with the image file

### Actual result

```php
{
  "message": "Unable to save product.",
  "trace": "
  #0 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Catalog\\Model\\ProductRepository->save(Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n
  #1 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->___callParent('save', Array)\n
  #2 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n
  #3 /generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(52): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->___callPlugins('save', Array, Array)\n
  #4 [internal function]: Magento\\Catalog\\Model\\ProductRepository\\Interceptor->save(Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n
  #5 /vendor/magento/module-webapi/Controller/Rest.php(330): call_user_func_array(Array, Array)\n
  #6 /vendor/magento/module-webapi/Controller/Rest.php(239): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n
  #7 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
  #8 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n
  #9 /app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
  #10 /vendor/magento/framework/Interception/Interceptor.php(135): Infortis\\Cgen\\Plugin\\Magento\\Framework\\App\\FrontController->aroundDispatch(Object(Magento\\Webapi\\Controller\\Rest\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n
  #11 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
  #12 /generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(39): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n
  #13 /vendor/magento/framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
  #14 /generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n
  #15 /vendor/magento/framework/App/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n
  #16 /index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n
  #17 {main}"
}
```

**Comment by magento-engcom-team** [comment]
@oe-bayram, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by humbertogonzalez** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@humbertogonzalez thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
@oe-bayram The issue is already fixed in `2.2.2` and `2.3-dev`.
Closing ticket for now. Please reopen if you need any further assistance with this.

**Comment by oe-bayram** [comment]
@magento-engcom-team I have upgraded Magento to 2.2.3 but I still get the same error messsage. Could you please tell me the commit where this is being fixed.

**Comment by Ctucker9233** [comment]
@magento-engcom-team What are the commits for this issue?
