### ISSUE TITLE
installation sample data

### ISSUE THREAD

**Issue by pierrefay** [magento/magento2#1399]
I have an error when trying to install the sample data :

root@magento2-cloud:/var/www/magento2# /var/www/magento2/bin/magento sampledata:install admin
                                                                                                                 
  [Magento\Framework\Exception\LocalizedException]                                                                
  Source class "\Magento\Setup\Model\Console" for "Magento\Setup\Model\ConsoleLogger" generation does not exist.  

maybe i missed something ?

Pierre.

**Comment by Vinai** [comment]
Duplicate, please see: https://github.com/magento/magento2/issues/1398#issuecomment-114016718

**Comment by safwkhan** [comment]
We are working on it. Internal issue number: MAGETWO-39001

**Comment by pierrefay** [comment]
thanks.

**Comment by pierrefay** [comment]
@Vinai it's not exactly the same :)

**Comment by Vinai** [comment]
Oh - sorry!

**Comment by pierrefay** [comment]
if you read this post and you have a quick fix, don't hesitate to let a message....don't understand where is the problem with this error.

**Comment by vpelipenko** [comment]
@pierrefay, do you still have this issue? It seems this issue was already fixed. Could you check it?

**Comment by pierrefay** [comment]
yes it has been solved  :) thanks a LOT :)

**Comment by novuswebbw** [comment]
What was the fix on this? I made the change noted in #1398 but still get the same error noted in this issue when trying to install the sample data. Using latest installed version of Magento 2.

**Comment by pierrefay** [comment]
i did nothing, just delete the folder, git clone and composer install, etc...again and it was ok for me. Pierre.
