### ISSUE TITLE
Retrieve session information from another customer under /customer/section/load/sections=&update_section_id=true

### ISSUE THREAD

**Issue by intercase** [magento/magento2#14049]
### Preconditions

- It happens on a fresh Magento 2.2.2 installation via composer.
- PHP 7.1
- MySQL 5.6

### Steps to reproduce

1) Installed Magento 2.2.2 via composer
2) Go to frontend and register a new customer. Logoff and login with this customer.
3) Open a new browser or use another device to repeat the step (2).
4) Under device 1, open a new tab and go to http://localhost/customer/section/load/?sections=&update_section_id=true
5) Using device 2, go to the same URL, http://localhost/customer/section/load/?sections=&update_section_id=true
6) Logoff from device 1 and 2. Execute the URL under both devices.

It is important to create more than 1 user browsing the store in order to get the problem.

During some tests, we confirmed this issue under live stores, that affects the store header that contains the customer name.

### Actual result

It is possible to get another customer session information from sections controller, without timestamp.
Sometimes, this url is trigged from knockout without timestamp, and shows another customer name in the store header.

### Expected result

Always return the user data for the current logged user. 
In case of no session, return no data from cache.

### Suggestion

Enforce session id check in order to avoid send cached data to another session.
It works with timestamp url hint, but for sensitive data, it is easy to decrement the timestamp and start to get customers who logged and visited the store.

**Comment by magento-engcom-team** [comment]
@intercase, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by intercase** [comment]
The solution was found by reading the Magento documentation, we noticed that the full page cache was caching the section controller:
http://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching/public-content.html

We have solved the problem by doing a rewrite of the file:
vendor/magento/module-customer/Controller/Section/Load.php

In the execute function

Before:

```
...
    $resultJson->setStatusHeader(
        \Zend\Http\Response::STATUS_CODE_400,
        \Zend\Http\AbstractMessage::VERSION_11,
        'Bad Request'
    );
    $response = ['message' => $this->getEscaper()->escapeHtml($e->getMessage())];
}


return $resultJson->setData($response);
```

After:

```
...
    $resultJson->setStatusHeader(
        \Zend\Http\Response::STATUS_CODE_400,
        \Zend\Http\AbstractMessage::VERSION_11,
        'Bad Request'
    );
    $response = ['message' => $this->getEscaper()->escapeHtml($e->getMessage())];
}

$resultJson->setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0', true);

return $resultJson->setData($response);

```

Thanks!

**Comment by pemann** [comment]
I think this is fixed in 2.2.2. See the commit: https://github.com/magento/magento2/commit/86c7816de42c9fa5e3d630dad1b1b1941b0d00ff

**Comment by joost-florijn-kega** [comment]
@pemann,

That commit doesn't fix it, because the header isn't replaced but just added to the headers of the response. Only the first header with the same name is return:
https://github.com/zendframework/zend-http/blob/master/src/Headers.php#L257

I have created a pull request to fix this issue:
https://github.com/magento/magento2/pull/14176

**Comment by magento-engcom-team** [comment]
Hi @intercase. Thank you for your report. 
The issue has been fixed in magento/magento2#14176 by @joost-florijn-kega in 2.2-develop branch
Related commit(s):
 - [f3bd0c2f16e038f687ba40ed2a575b04698ccd76](https://github.com/magento/magento2/commit/f3bd0c2f16e038f687ba40ed2a575b04698ccd76)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @intercase. Thank you for your report. 
The issue has been fixed in magento/magento2#14661 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [9359b43681a2cef1b1df1f8071d49505775fefc6](https://github.com/magento/magento2/commit/9359b43681a2cef1b1df1f8071d49505775fefc6)

The fix will be available with the upcoming 2.3.0 release.
