### ISSUE TITLE
Print order just printing a empty pdf on magento 2.1.8

### ISSUE THREAD

**Issue by tousif12** [magento/magento2#14113]
## Preconditions
Magento 2.1.8

## Steps to Reproduce
Login as customer
Place order
Go to "My account" page on frontend
Click on your order
Click "Print Order"
## Actual Result
https://image.ibb.co/eP3N7x/pdf.png
Pdf just with  date order #  on top

## Expected result
Order printed on pdf 

**P.S**   I was getting this error first   https://github.com/magento/magento2/issues/10530   which I fixed by using given fix now encounter this issue.

**Comment by magento-engcom-team** [comment]
@tousif12 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![print_order](https://user-images.githubusercontent.com/31669971/37460777-f5de6dac-2854-11e8-9a35-1c42ba682249.png)

![print_orde_2](https://user-images.githubusercontent.com/31669971/37460793-ff30dbf6-2854-11e8-9a13-4151d26c39cd.png)

**Comment by tousif12** [comment]
@magento-engcom-team   Yes I tested on other versions it is working . But I noticed 1 thing that on other versions on print order a new page open a on onload a  window.print()  apply  .In my version its like 

   ```
 jQuery(function() {
        window.print();
    });


```

But In  other versions its like


```

    require(
        [
            'jquery'
        ],
        function($) {
            $(function() {
                window.print();
            });
        }
    );
```

As onload function.    Where I can find that function written ? Is it causing issue  ?    

And 2nd thing on my whole website ctrl+p even giving a empty pdf just url on top.  which probably print whole page.

**Comment by magento-engcom-team** [comment]
@tousif12 , thanks for you update. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by magento-engcom-team** [comment]
@tousif12, thank you for your report.
The issue is already fixed in 2.2.3, 2.3.0, 2.1.12

**Comment by nicolallias** [comment]
In the end, what is the official fix? Only the requirejs call by @tousif12 ?

Which are the relevant commits? (I have third party constraints to stay beyond 2.1.12)

**Comment by nallias** [comment]
Hi all,
After upgrade (done with web wizard, dobl-check with CLI) magento from 2.1.7 to 2.2.3, the bug is still there.

**Comment by chakravarthykalyan90** [comment]
We are running 2.3.1 the bug is still there. Looks like the print is called before the complete page load. If we try to print for the second time then it is working.

**Comment by asshumski** [comment]
Magento ver. 2.2.8 bug presents 
Updated 07/29/2019
Issue was related to Google optimize antiflicker code. Not related to Magento.

**Comment by sezio** [comment]
2.2.5, we also have the problem here, only in chrome. It seems the problem comes from Chrome... I'm not sure it's directly related to magento. 
There's a lot of issue opened on the internet on the subject and chrome. Some solution are proposed but none of them worked for me... You can google search "window.print empty chrome" for more information

**Comment by Den4ik** [comment]
@magento give me test instance

**Comment by JMC-PK** [comment]
Did this ever get fixed? I can confirm that this is still happening on 2.3.2 & is not fixed in 2.3.0 as @magento-engcom-team  claimed. Was about to begin the process of updating to 2.4.x and was looking into if this was fixed yet or not.
