### ISSUE TITLE
window.checkout is undefined if minicart is removed

### ISSUE THREAD

**Issue by Zaylril** [magento/magento2#1458]
Hey,

When building the cart/checkout page on my current theme, i've removed the minicart from the cart page in the header. However this results in me now getting an error when clicking proceed to checkout as the checkoutUrl is undefined in the window.checkout object. 

You should be able to proceed to the checkout without having the minicart available on the page (I've just had to hide it for now with css rather than remove).

Thanks

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-39865

**Comment by vpelipenko** [comment]
@Zaylril, internal ticket is fixed and already available in develop branch. Please, check the fix, if something doesn't work for you, feel free to reopen this issue.

**Comment by weilunallen** [comment]
In 2.0.6, this problem still persist,  I can't use search's autocomplete, if mini-cart is not on the page, due to window.checkout.autocomplete is undefined.

**Comment by Galch24** [comment]
In 2.1.0, this problem still persist. If I hided minicart in header (in default.xml layout) the similar errors are showed in console:

```
TypeError: window[this.configSource] is undefined
captchaConfig = window[this.configSource]['captcha'];
```

in defaultCaptcha.js (line 29, col 17)

**Comment by TClilMouse** [comment]
In 2.1.1, this problem still persist.

**Comment by markdavies** [comment]
window.checkout.autocomplete is undefined if you remove the minicart... still

**Comment by designbyadrian** [comment]
Does anyone know what the minimum amount of blocks you need to add to make this work?

**Comment by simonrl** [comment]
I worked around this by not removing the minicart block in the layout, but overriding the template file Magento_Checkout/templates/cart/minicart.phtml; the contents of the new file:

```
<script>
    window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
</script>
```

**Comment by rodchencko** [comment]
2.1.1 here and the problem still persists. Has anybody discovered a workaround for this?

**Comment by pravalitera** [comment]
I had to solve it quickly yesterday. Put it in the layout you need :

```
<referenceContainer name="after.body.start">
            <block class="Magento\Framework\View\Element\Text" name="fixminicarterror">
                <arguments>
                    <argument name="text" xsi:type="string"><![CDATA[<script>window.checkout = {};</script>]]></argument>
                </arguments>
            </block>
        </referenceContainer>
```
