### ISSUE TITLE
Export Products bug. I can't exclude attributes from CSV file. 

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#14642]
I can't exclude some attributes from CSV file with with all products. Checkboxes don't work properly.

### Preconditions

1. Magento 2.2.2 & 2.3.x
2. mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22

### Steps to reproduce

1. Make sure you have products in your Magento 2. 
2. Create a couple of custom attributes (color, size for example). Not sure this field is __required__. I think this bug will reproduced without custom attributes.
2. Go to BO-> System -> Data Transfer (Export).
3. [Choose](http://joxi.ru/KAgZWGJI4wkY92): 
__Entity Type__ select = Products
__Export File Format__ =  CSV
 __Fields Enclosure__ = unchecked
4. I tried to set checkbox on [*SKU*](http://joxi.ru/DmBlxDRSweB5ZA) field for example.

### Expected result

1. I should get CSV file wihout *SKU* column (see the screenshot attached below). 

### Actual result

1. Here is what I get. The same screenshot attached below. 

![screenshot from 2018-04-11 15-15-50](https://user-images.githubusercontent.com/10618641/38616063-623c5bc0-3d9b-11e8-8175-3c1413406132.png)

**Comment by oefterdal** [comment]
I think SKU is requiered since its also used for matching on import. So think the real bug is that you can set exclude on SKU.

**Comment by AleksLi** [comment]
@oefterdal I tried with other attributes but it failed either. Try to exclude other attributes from CSV. It will be the same result

**Comment by ghost** [comment]
@AleksLi, this is not a bug. By setting this fields you can exclude some products from export, not columns.

**Comment by simonmaass** [comment]
i agree that it is confusing - i also thought that it will exclude the column!

**Comment by arnoudhgz** [comment]
@engcom-backlog-pb @AleksLi @simonmaass according to [the documentation](https://docs.magento.com/m2/ce/user_guide/system/data-export.html) the column should actually be excluded from the export. 

I could reproduce his on 2.3.2

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19661` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by arnoudhgz** [comment]
I found out that the `skip_attr` (which is posted through the `Exclude` column) is not saved in the `queue_message` table.

**Comment by magento-engcom-team** [comment]
Hi @AleksLi. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [c1b7ba0b1fa7e1737a94d9307a9a40d115f42e09](https://github.com/magento/magento2/commit/c1b7ba0b1fa7e1737a94d9307a9a40d115f42e09)
 - [e01d260bb49313b3cc2ecbc993c4a16dd29e3856](https://github.com/magento/magento2/commit/e01d260bb49313b3cc2ecbc993c4a16dd29e3856)
 - [a16f08be22a8b1b0376ef9ddee66c7b43c0895a3](https://github.com/magento/magento2/commit/a16f08be22a8b1b0376ef9ddee66c7b43c0895a3)
 - [cd05c5a96b7e397f7f18d08bb431e902747227c4](https://github.com/magento/magento2/commit/cd05c5a96b7e397f7f18d08bb431e902747227c4)
 - [a467c03e5642501718770688070d4d98d324b09f](https://github.com/magento/magento2/commit/a467c03e5642501718770688070d4d98d324b09f)
 - [bf72e2374f84076641623215381aeb78569d83ea](https://github.com/magento/magento2/commit/bf72e2374f84076641623215381aeb78569d83ea)
 - [be2c55edf1c650a0cbcb02e248fd21d2754aa51a](https://github.com/magento/magento2/commit/be2c55edf1c650a0cbcb02e248fd21d2754aa51a)
 - [bc26eb16471d7d44525a8471b9e8847bd4f5d98a](https://github.com/magento/magento2/commit/bc26eb16471d7d44525a8471b9e8847bd4f5d98a)
 - [5c6666895920f92ebeaf8cf078e9ce6c2a38b3be](https://github.com/magento/magento2/commit/5c6666895920f92ebeaf8cf078e9ce6c2a38b3be)
 - [d178a55fdf4e95d02b085d0d2d7f05535321cdab](https://github.com/magento/magento2/commit/d178a55fdf4e95d02b085d0d2d7f05535321cdab)
 - [56bf57ecbd0caed993e20c9d389b900eebbf746b](https://github.com/magento/magento2/commit/56bf57ecbd0caed993e20c9d389b900eebbf746b)
 - [eb5f20130e50ba3ad235e1bd371ae1ff4025b5f3](https://github.com/magento/magento2/commit/eb5f20130e50ba3ad235e1bd371ae1ff4025b5f3)
 - [900a707c9980c760137d573fa10b45eaf1414ee1](https://github.com/magento/magento2/commit/900a707c9980c760137d573fa10b45eaf1414ee1)
 - [8632e6df4f4146e230bbb5b13432d8af797eeb9a](https://github.com/magento/magento2/commit/8632e6df4f4146e230bbb5b13432d8af797eeb9a)

The fix will be available with the upcoming `2.3.4` release.

**Comment by onepack** [comment]
And so.. I'm on 2.3.3 now and this issue still persists. When will this be solved?

**Comment by simonmaass** [comment]
what a shame that this was not included in 2.3.3....

**Comment by ABARAUJOMGA** [comment]
While there isn't a 2.3.4 release, they could say something to us about how to make this work.

**Comment by rickyhub** [comment]
> While there isn't a 2.3.4 release, they could say something to us about how to make this work.

I need a fix too please.
Regards

**Comment by magedev218** [comment]
I have tried to resolve this issue by applying given patch but it does not work for me. Can any one help me?
Getting Error after applying above patch is as below:
`[2020-02-13 17:17:38] main.CRITICAL: Message has been rejected: Property "SkipAttr" does not have accessor method "getSkipAttr" in class "Magento\ImportExport\Api\Data\ExportInfoInterface". [] []`

**Comment by lenlorijn** [comment]
This is still broken on 2.4.2

**Comment by affirmative-pl** [comment]
also an issue in Magento ver. 2.3.5-p2

**Comment by rfortes-scrubsandbeyond** [comment]
Still broken on 2.4.5-p1
