### ISSUE TITLE
M 2.2.3 price per website - wrong price at backend by a create order after update

### ISSUE THREAD

**Issue by Webroju** [magento/magento2#14869]
At a shop with 2 websites (and 2 storeviews) and use different prices (price scope: website), if  you create an order at the backend for the second website and update this order, e.g. change the quantity then the default price is calculated and not the price of the special website.
 

### Preconditions

1. Magento 2.2.3. 
2. NGINX, 
2. PHP 7.1.3

### Steps to reproduce

1. Create a second website, create a store and a storeview at this second website
2. Change the config at Stores > Configuration > Catalog > Catalog> Price >Catalog Price Scope > change from global to website
3. Create a Product with a price 
4. Change the storeview to the second storeview and and change the price only for this storeview, not the global
5. At the Backend, create a new order in the second storeview and add the product to the "Items Ordered" (now the price is correct) 
6. change the quantity of the product and click "update items and quantities"

### Expected result

1. the price of the appropriate storeview 

### Actual result

1. the default price

![screenshot_1](https://user-images.githubusercontent.com/13220558/39305472-85c240c8-495d-11e8-88c6-691dafc20126.png)
![screenshot_2](https://user-images.githubusercontent.com/13220558/39305471-859fb10c-495d-11e8-9fab-6b7d261bb3c5.png)

**Comment by VladimirZaets** [comment]
Hi @Webroju. Thank you for your report. 
The issue has been fixed in magento/magento2#14904 by @phoenix128 in 2.2-develop branch
Related commit(s):
 - [dd74f6bd4f70be344f751a3a6896008ab267bf04](https://github.com/magento/magento2/commit/dd74f6bd4f70be344f751a3a6896008ab267bf04)

The fix will be available with the upcoming 2.2.5 release.

**Comment by julienvb** [comment]
I created the folder and file but the issue still persists, did I implement the fix wrongly?
![image](https://user-images.githubusercontent.com/12121188/42228095-6336252c-7ee3-11e8-9095-905e57ca502a.png)

**Comment by sidolov** [comment]
Hi @Webroju. Thank you for your report. 
The issue has been fixed in magento/magento2#16893 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [49926d73e6e26961f9b3f529dac1856957c4688d](https://github.com/magento/magento2/commit/49926d73e6e26961f9b3f529dac1856957c4688d)
 - [35b968e0dc897fb28fa95255131861d04950745f](https://github.com/magento/magento2/commit/35b968e0dc897fb28fa95255131861d04950745f)

The fix will be available with the upcoming 2.3.0 release.

**Comment by digikeijs** [comment]
@sidolov issue is not solved yet, See new incident 15846

**Comment by ihor-sviziev** [comment]
Hi @digikeijs,
I re-checked, this issue was fixed in 2.2.6 release.
