### ISSUE TITLE
Module Manager module grid is not working Magento 2.2.4

### ISSUE THREAD

**Issue by jignesh-baldha** [magento/magento2#15192]
### Preconditions
1. Magento Version 2.2.4
2. PHP Version 7.0.30
3. MySQL version 5.7.22
4. Apache/2.4.18 (Ubuntu)

### Steps to reproduce
1. I've installed latest Magento ver 2.2.4
2. Module Manager doesn't show module grid when going through below step:
- System > Tools > Web Setup Wizard > Module Manager

### Expected result
1. It should show manage module grid.

### Actual result
![2018_05_14_manage_module](https://user-images.githubusercontent.com/24771248/39988119-2b5b5c20-5784-11e8-9e7f-0388f99606f8.png)
**Console shows following error**
`GET http://127.0.0.1/magento224/setup/index.php/moduleGrid/modules 500 (Internal Server Error)`

**Comment by DigitalStartupUK** [comment]
I too am able to reproduce this.

**Comment by hostep** [comment]
Hi guys, can you please take a look in the log files of your webserver (apache/nginx/...), because "Internal Server Errors" are getting logged over there. Those log files will probably give you more info about what's wrong.

**Comment by DigitalStartupUK** [comment]
Nothing in Apache logs is being generated. I can't do a deep dive in this instance as I'm looking at a Shared Hosting Account that I use for Sandboxing. I don't particularly want to try and reproduce this on my Production/Dev Dedicated servers. Perhaps @jignesh-baldha can produce logs.

**Comment by ghost** [comment]
I am having same issue on Fresh Install of Magento CE 2.2.4 with PHP 7.1.6

JS is No Where (500) for `....../setup/index.php/moduleGrid/modules`

**Comment by evagabond** [comment]
Facing the same issues using Magento CE 2.2.4 & PHP 7.0.28

**Comment by ghost** [comment]
@hostep , No logs in apache.

**Comment by jignesh-baldha** [comment]
@hostep Not found any error in apache logs.

**Comment by hostep** [comment]
Ok, and how about the log locations of your Magento installation, for example in:
- `var/log/`
- `var/report/`

Also: if you take a look in your inspector to the network tab and you see that request which throws a 500 error, can you take a look at the response if something interesting is in there?

**Comment by donos0** [comment]
Fresh Magento CE 2.2.4 install with PHP 7.0.25 + Apache 2.4.29.
Same error as all above.
No logs in apache or in Magento. No report in Magento.

The console error message goes a bit further, though:
![console](https://user-images.githubusercontent.com/39330386/40105186-8ce52cc2-58f2-11e8-91f8-1ccbf4861844.jpg)
![angular](https://user-images.githubusercontent.com/39330386/40105192-9082a38c-58f2-11e8-9791-633c1c724866.jpg)

**Comment by AndyJAllen** [comment]
You guys can get further than I can. I get HTTP ERROR 500 when trying to just access the Web Setup Wizard on 2.2.4. I updated via composer.

**Comment by donos0** [comment]
Could this be anyhow related to issues [#4546](https://github.com/magento/magento2/issues/4546) and [#4575](https://github.com/magento/magento2/issues/4575) ?

**Comment by rishabhchd19** [comment]
same problem here.

**Comment by hostep** [comment]
Hi guys, I just saw this PR which seems to fix this problem: https://github.com/magento/magento2/pull/15211
Can someone confirm that changing that one line fixes the problem? Thanks!

**Comment by DigitalStartupUK** [comment]
@hostep I can confirm that this does "fix" the issue. Looks like it's down to the new Amazon Pay component (amzn/amazon-pay-and-login-magento-2-module). But this shouldn't be considered an actual fix for anyone thinking about changing the core code.

Thank you by-the-way, @hostep

**Comment by hostep** [comment]
Thanks for confirming @DigitalStartupUK, great! So if the PR gets approved it should get released in an upcoming new version. I agree this isn't the correct fix to edit the core files, this was only for verifying if it fixes the issue. People should consider for themselves how to workaround the issue, or just wait for a new version to be released in which the fix is included.

**Comment by sidolov** [comment]
Hi @jignesh-baldha. Thank you for your report. 
The issue has been fixed in magento/magento2#15211 by @flancer64 in 2.2-develop branch
Related commit(s):
 - [a95034a140326ede1f4fbd18236a1db9ed3e20f8](https://github.com/magento/magento2/commit/a95034a140326ede1f4fbd18236a1db9ed3e20f8)
 - [131a45818c88a0f57a8459f96fc24860946a0729](https://github.com/magento/magento2/commit/131a45818c88a0f57a8459f96fc24860946a0729)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @jignesh-baldha. Thank you for your report. 
The issue has been fixed in magento/magento2#15756 by @vijay-wagento in 2.1-develop branch
Related commit(s):
 - [8f4f052c449d0a80dfae665c991b358d0c183af0](https://github.com/magento/magento2/commit/8f4f052c449d0a80dfae665c991b358d0c183af0)
 - [13dc0174bced63fc506af8e36a41651c70e202de](https://github.com/magento/magento2/commit/13dc0174bced63fc506af8e36a41651c70e202de)

The fix will be available with the upcoming 2.1.15 release.

**Comment by sidolov** [comment]
Hi @jignesh-baldha. Thank you for your report. 
The issue has been fixed in magento/magento2#15755 by @vijay-wagento in 2.3-develop branch
Related commit(s):
 - [486f7a72c37ea04a5eeb1978bf2a8af0be9f0943](https://github.com/magento/magento2/commit/486f7a72c37ea04a5eeb1978bf2a8af0be9f0943)
 - [1b5d1d1da3c9a4c01351f5c5ac34da9691c355a5](https://github.com/magento/magento2/commit/1b5d1d1da3c9a4c01351f5c5ac34da9691c355a5)

The fix will be available with the upcoming 2.3.0 release.

**Comment by jissereitsma** [comment]
I've bumped into the same issue with Magento 2.2.5 which was just released today. The issue is not fixed. However, the fix mentioned above does work for me.

**Comment by Jacob-Wilsons** [comment]
I can confirm, the issue with blank page on "Module Manager" is still in magento 2.2.5

**Comment by ghost** [comment]
Hi there, I can confirm same issue still with 2.2.5 here.

**Comment by rishabhchd19** [comment]
> Hi there, I can confirm same issue still with 2.2.5 here.

@Shellanza and @Jacob-Wilsons The changes have been made and tested successfully. Please go to setup/src/Magento/Setup/Model/Grid/Module.php

Change from:
$item['moduleName'] = $item['moduleName'] **?:**$this->packageInfo->getModuleName($item['name']);

Change to:
$item['moduleName'] = $item['moduleName'] **??** $this->packageInfo->getModuleName($item['name']);

at line 181

**Comment by key-dev** [comment]
It worked.
Thank you

**Comment by key-dev** [comment]
> > Hi there, I can confirm same issue still with 2.2.5 here.
> 
> @Shellanza and @Jacob-Wilsons The changes have been made and tested successfully. Please go to setup/src/Magento/Setup/Model/Grid/Module.php
> 
> Change from:
> $item['moduleName'] = $item['moduleName'] **?:**$this->packageInfo->getModuleName($item['name']);
> 
> Change to:
> $item['moduleName'] = $item['moduleName'] **??** $this->packageInfo->getModuleName($item['name']);
> 
> at line 181

It worked.
Thank you

**Comment by tarunatbasics** [comment]
As key-dev said, I have changed 181 line of Module.php but the problem is still there, can anyone have a solution to this problem?
