### ISSUE TITLE
theme can not be changed in magento 2.2.4

### ISSUE THREAD

**Issue by staywithabhi** [magento/magento2#15359]
We have installed a fresh copy of magento 2.2.4 however it is not allowing us to change the theme and throwing the exception "**Something went wrong while saving this configuration: Area is already set**" 

### Preconditions

1. ubuntu 16.04
2. php 7.0

### Steps to reproduce

1. content->design configuration
2. edit and change the theme
3. save the new select theme

### Expected result

1. Theme must be changed and new theme must be applied without errors

### Actual result

Theme can not be changed.Please have a glance over the attached screenshot.
1. [Screenshot]
![screenshot from 2018-05-19 15-22-01](https://user-images.githubusercontent.com/12792172/40267381-d61b0e9c-5b78-11e8-8299-112db6325c2f.png)

**Comment by hostep** [comment]
Thanks for creating this issue. But I'm going to close it as the same issue has been reported a couple of times before. Next time you want to create an issue, it might be a good idea to search if there aren't already issues reported around the same problem :)

Closing this ticket in favor of https://github.com/magento/magento2/issues/14968 which was already fixed by https://github.com/magento/magento2/pull/15137 and the fix should get released in Magento 2.2.5

**Comment by rezaulsarker** [comment]
I am also face this and I am found my solution here >> https://magento.stackexchange.com/questions/225628/something-went-wrong-while-saving-this-configuration-area-is-already-set

**Comment by staywithabhi** [comment]
yeah i also found that solution but making changes directly in core file is not a good practise.Well as explained by @hostep ,issue will be fixed in upcoming release i.e. 2.2.5

**Comment by legweilo** [comment]
Hi guys,

a small module to fix it without touching the core:

https://github.com/pfortin-expertime/MageFix-Misc

Enjoy :)

**Comment by DanielRuf** [comment]
It is already fixed in 2.2-develop.

**Comment by rajputlalita** [comment]
i am still getting this issue in  Magento ver. 2.2.5

![magentoerror](https://user-images.githubusercontent.com/16317684/43321998-1b4e045a-91cb-11e8-8b62-906669c0c604.png)
Any suggestion or do  i need  to  do  the changes suggested by @rezaulsarker

**Comment by DanielRuf** [comment]
It will be fixed in 2.2.6.

**Comment by DanielRuf** [comment]
Magento provides a patch for this bug for those who need it now.

**Comment by rajputlalita** [comment]
Okay Thanks @DanielRuf
