### ISSUE TITLE
Double click on "Proceed to Checkout" causes errors

### ISSUE THREAD

**Issue by TobiasLufinity** [magento/magento2#15434]
Double clicking (multiple clicks) on "Proceed to Checkout" seems to cause the session to malfunction. 
You are redirected to checkout/cart/ with an empty cart but the mini-cart still seem to show a product.

### Preconditions

1.  Magento version 2.2.2
2. PHP version 7.0.15

### Steps to reproduce

1. Add a product to the cart
2.  Go to checkout/cart/ 
3.  Click "Proceed to checkout" twice with half a second or so between clicks. Or just click it a couple of times

### Expected result

1. You will be directed to checkout/ procedure

### Actual result

1. You are redirected to checkout/cart/ with an empty cart but mini-cart still shows a product

After this happens the product in the cart remains until you add another product.
This also causes logged in users to be logged out.
I would say that a double click is not that uncommon and if the site is slow the time between clicks increases

**Comment by hobaugh** [comment]
This happens on 2.2.3 as well

**Comment by dankhrapiyush** [comment]
Hi @TobiasCodeNull @hobaugh 
This issue is resolved in 2.2-develop branch by @odubovyk.

Related commit(s):
 - [9a799f130a0a8b64028de6258e7cf1378bc9bc8f](https://github.com/magento/magento2/commit/9a799f130a0a8b64028de6258e7cf1378bc9bc8f)

**Comment by jignesh-baldha** [comment]
@dankhrapiyush Same issue still exists when click "Proceed to checkout" couple of times from mini-cart.

**Comment by dankhrapiyush** [comment]
Getting the same issue on refresh checkout page couple of times.

**Comment by xpoback** [comment]
@dankhrapiyush I can confirm that the bug is reproduceable. I've created another issue for that: #16188
The fix you referenced only makes it impossible to click the button multiple times but it doesn't fix the main problem

**Comment by sanganinamrata** [comment]
@dankhrapiyush @jignesh-baldha @hobaugh  Hello,

 I confirm the [Fix](https://github.com/magento/magento2/commit/a6f146cd9302fbbb6305df9613c7ce3eea7a05ae) provided by @xpoback is working for **Secure domain** fir all the cases mentioned by you. (Issue still exists for an **Unsecured domain**.)

Thanks

**Comment by engcom-backlog-nickolas** [comment]
Hello @TobiasCodeNull, thank you for your report. As being said in comment above, this issue already has been fixed on 2.2-develop and 2.3-develop branches.
