### ISSUE TITLE
WYSIWYG not working after upgrading from 2.2.3 -> 2.2.4

### ISSUE THREAD

**Issue by danharper83** [magento/magento2#15638]
### Preconditions
1. Sart with Magento version 2.2.3
2. Run composer update to version 2.2.4
3. Follow update steps using command line.

### Steps to reproduce
1. Go to catalog
3. Click on any product
2. Click show hide editor

### Expected result

1. Should see WYSIWYG

### Actual result

1. Do not see WYSIWYG
2. Get errors in console
[Screenshot was included. Redacted due to sensitive info]

**Comment by magento-engcom-team** [comment]
Hi @danharper83
Please try clearing static content in your store. This issue looks like it relates to it.

**Comment by hostep** [comment]
@danharper83: do you have minifying JS enabled?
If yes: then you are running into a new bug introduced in 2.2.4, because the now-included-by-default Klarna modules have a bug in them which causes the tinymce editor to not work properly when minifying JS is enabled.
It has already been reported at the end of [an old issue](https://github.com/magento/magento2/issues/11577#issuecomment-391313584), so it's good to keep this issue open, until Klarna prepares an update for their modules and Magento releases them on their repo, so we can update them using composer.

For now, easy fix: disable the Klarna modules if you aren't using them :)

**Comment by danharper83** [comment]
I disabled Klarna and then cleared the static content but still have the problem. Where do I find the JS minification setting?

**Comment by seo99ita** [comment]
I solved the problem by [following these](https://github.com/magento/magento2/issues/11577#issuecomment-341890277) and then [following these too](https://www.yireo.com/blog/1880-disabling-annoying-3rd-party-magento-modules), which I fully endorse.
Now everything works correctly.

**Comment by hostep** [comment]
@danharper83: this works for me (started from a clean 2.2.4 project running in production mode):
```
bin/magento module:disable Klarna_Kp Klarna_Ordermanagement Klarna_Core
bin/magento deploy:mode:set production
```

I wouldn't recommend following the first link by @seo99ita though, that's not the right way to go.
I agree with the second link though, good article by Jisse!

**Comment by danharper83** [comment]
I didn't spot the other Klarna modules, once disabled and re-deployed all works fine 👍

Can be marked as resolved I guess, is this logged with Klarna somewhere so we can link the issues?

**Comment by hostep** [comment]
I'd leave it open until fixed.

No idea if someone reported it to Klarna (I didn't) or even how to report it, I've opened an issue for the doc team requesting for contact information for those new Core Bundled Extensions: https://github.com/magento/devdocs/issues/1961

**Comment by matin73** [comment]
bin/magento module:disable Klarna_Kp Klarna_Ordermanagement Klarna_Core worked for me

**Comment by hostep** [comment]
Updating the Klarna modules to the latest version using composer seems to fix the issue, at least I don't see any `<minify_exclude>` entries anymore in those modules, so I assume it should be fixed.

Can someone confirm, so we can close this issue?

**Comment by danharper83** [comment]
Tested and it seems to be fixed in 2.2.5

**Comment by hostep** [comment]
Thanks @danharper83. @LSERRE also confirmed in https://github.com/magento/magento2/issues/11577#issuecomment-401840977, so let's close this issue as it is fixed in the latest version of the Klarna module.

**Comment by oviliz** [comment]
Why do we need these modules anyway?

**Comment by drinkingsouls** [comment]
I also have this problem in fresh install. Disabled Klarna but the issue persists.

**Comment by hostep** [comment]
@drinkingsouls: it might help if you read the entire thread of https://github.com/magento/magento2/issues/11577, there are some useful comments there which might steer you in the right direction. Good luck! :)
