### ISSUE TITLE
Duplicated product is out of stock when index set to UPDATE BY SCHEDULE

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#15939]
### Preconditions
1. Install Magento Open Source 2.2.4 with sample data
2. Setup CRON
3. Change all indexes to "UPDATE BY SCHEDULE"

### Steps to reproduce
1. Locate a simple product in the backend
2. Click "Save & Duplicate"
3. Set the following attribute values on the newly created product and then click "Save":
    * Enabled: True
    * Quantity: 1
    * Stock Status: In Stock
4. Load the product on the frontend (either by loading the url key or by accessing the product directly via /catalog/product/view/<ID>)

### Expected result
1. The product should show with an "Add to Cart" button:
![11-08-27 tp - meta title-onn3t](https://user-images.githubusercontent.com/129031/41111943-1951432e-6a43-11e8-858f-b393efb25721.jpg)

### Actual result
1. The product shows as "Out of Stock":
![11-06-49 tp - meta title-pk0l0](https://user-images.githubusercontent.com/129031/41111862-dfb64786-6a42-11e8-9153-a4f7857588d7.jpg)
2. If I run these commands, then the product shows as in stock:
```
bin/magento indexer:reindex cataloginventory_stock
bin/magento cache:flush
```

**Comment by ghost** [comment]
Hi @erikhansen Which versions your tested ?

**Comment by erikhansen** [comment]
@engcom-backlog-nazar I tested it on Magento 2.2.4. I edited the task description just now to clarify that.

**Comment by amanuni** [comment]
I am also facing same issue.

**Comment by matthew-muscat** [comment]
This looks to have been fixed in release v2.2.5 - the change can be found in https://github.com/magento/magento2/issues/12205

@engcom-backlog-nazar - this appears to be a duplicate of https://github.com/magento/magento2/issues/15984 —  is it assumed merchants need to update to v2.2.5 to get the fix?

**Comment by ghost** [comment]
@erikhansen This commit, doesn't fix the issue.

**Comment by matthew-muscat** [comment]
@engcom-backlog-nazar yep, looks like #12205 does not actually fix this particular issue... apologies.

Upon investigating this one further - this looks to be due to an omission in the way the stock indexer changelog is triggered on INSERT / UPDATES / DELETES...

For example...
1) Updating a product's details relating to inventory (ie: qty or stock status), will result in the item being scheduled for update in the stock index - as such, the product becomes available for sale after the schedule update is completed.

2) Updating a product's attribute details (ie: enabling / disabling a product's status), will NOT result in the item being scheduled for an update in the stock index — this can result in the item becoming available in Magento's frontend, but in a state where it will appear as "Out Of Stock"

The problem would also appear to be related to "disabled" products not containing an entry in the `cataloginventory_stock_status` table. As such, once it's enabled, it never gets this entry.


For example — updates to the `catalog_product_entity` and `catalog_product_entity_int` tables does not trigger updates to the stock indexer changelog.

*catalog_product_entity triggers*
```
BEGIN
INSERT IGNORE INTO `catalogsearch_fulltext_cl` (`entity_id`) VALUES (OLD.`entity_id`);
INSERT IGNORE INTO `catalog_product_price_cl` (`entity_id`) VALUES (OLD.`entity_id`);
INSERT IGNORE INTO `catalogrule_product_cl` (`entity_id`) VALUES (OLD.`entity_id`);
END
```

*catalog_product_entity_int triggers*
```
BEGIN
IF (NEW.`value_id` != OLD.`value_id` OR NEW.`attribute_id` != OLD.`attribute_id` OR NEW.`store_id` != OLD.`store_id` OR NEW.`entity_id` != OLD.`entity_id` OR NEW.`value` != OLD.`value`) THEN INSERT IGNORE INTO `catalogsearch_fulltext_cl` (`entity_id`) VALUES (NEW.`entity_id`); END IF;
IF (NEW.`value_id` != OLD.`value_id` OR NEW.`attribute_id` != OLD.`attribute_id` OR NEW.`store_id` != OLD.`store_id` OR NEW.`entity_id` != OLD.`entity_id` OR NEW.`value` != OLD.`value`) THEN INSERT IGNORE INTO `catalog_product_category_cl` (`entity_id`) VALUES (NEW.`entity_id`); END IF;
IF (NEW.`value_id` != OLD.`value_id` OR NEW.`attribute_id` != OLD.`attribute_id` OR NEW.`store_id` != OLD.`store_id` OR NEW.`entity_id` != OLD.`entity_id` OR NEW.`value` != OLD.`value`) THEN INSERT IGNORE INTO `catalog_product_price_cl` (`entity_id`) VALUES (NEW.`entity_id`); END IF;
IF (NEW.`value_id` != OLD.`value_id` OR NEW.`attribute_id` != OLD.`attribute_id` OR NEW.`store_id` != OLD.`store_id` OR NEW.`entity_id` != OLD.`entity_id` OR NEW.`value` != OLD.`value`) THEN INSERT IGNORE INTO `catalog_product_attribute_cl` (`entity_id`) VALUES (NEW.`entity_id`); END IF;
IF (NEW.`value_id` != OLD.`value_id` OR NEW.`attribute_id` != OLD.`attribute_id` OR NEW.`store_id` != OLD.`store_id` OR NEW.`entity_id` != OLD.`entity_id` OR NEW.`value` != OLD.`value`) THEN INSERT IGNORE INTO `catalogrule_product_cl` (`entity_id`) VALUES (NEW.`entity_id`); END IF;
END
```

**Comment by matthew-muscat** [comment]
Locating the triggers in place for the Stock Index changelog can be found using the following query...

```
SHOW TRIGGERS WHERE `Statement` LIKE '%cataloginventory_stock_cl%';
```

For me, this results in only the following triggers being present...

Trigger | Table | Action
------- | ----- | ------
trg_cataloginventory_stock_item_after_insert | cataloginventory_stock_item | INSERT
trg_cataloginventory_stock_item_after_update | cataloginventory_stock_item | UPDATE
trg_cataloginventory_stock_item_after_delete | cataloginventory_stock_item | DELETE

**Comment by sjb9774** [comment]
@matthew-muscat do you have a suggested fix for this issue? I'm currently running into this on 2.2.6

**Comment by matthew-muscat** [comment]
@sjb9774 — we changed the index mode for stock to "update on save" — which works around the issue, since it's only the "update on schedule" mode that is affected here.

**Comment by sheshagiriAnvekar** [comment]
Is there any fix available for this issue?  we are finding the same issue on 2.2.5

**Comment by sjb9774** [comment]
@engcom-backlog-nazar Do you know if there's any solution in a future version or patch that addresses this problem? I'm currently dealing with it for a client who cannot reasonably change the index mode to "update on save".

**Comment by hostep** [comment]
I have the feeling this issue might have been solved by [MC-19407: Number of the rows increase very fast in changelog table](https://github.com/magento/magento2/commit/eec9c26a44f3a62ef426f9ac326ff36269a77d7b), but I'm not sure.

Could somebody try to test this?

**Comment by Pavel-Fekete** [comment]
Still facing this issue on latest 2.4-develop

**Preconditions**

1. Magento 2.4-develop
2. Setup CRON
3. Change all indexes to "UPDATE BY SCHEDULE"
![Indexer](https://user-images.githubusercontent.com/67371013/98109150-c8121f00-1ea5-11eb-93a4-3c895c92d000.png)


**Steps to Rerpoduce:**

1. Select existing product in backend or create new 
2. Click "Save & Duplicate"
3. Set the following attribute values on the newly created product and then click "Save":
Enabled: True
Quantity: 1
Stock Status: In Stock
![Save and duplicate](https://user-images.githubusercontent.com/67371013/98109382-22ab7b00-1ea6-11eb-96ac-fbfab66f4251.png)
4. Load the product on the frontend

**Actual Result:** The product shows as "Out of Stock":
![Out](https://user-images.githubusercontent.com/67371013/98109542-6e5e2480-1ea6-11eb-868c-1536a7235a5a.png)

**Comment by Vasudev-22** [comment]
@magento I am working on this

**Comment by Vasudev-22** [comment]
@erikhansen , @Pavel-Fekete , 

Hi , This issue is not reproducible in latest version (Open Source)

Attached here the video for reference, please let me know, if i missed any steps to reproduce.


https://github.com/magento/magento2/assets/104893739/3d00e206-927c-4b22-90d6-8f4743f02c60

**Comment by engcom-Bravo** [comment]
Hi @erikhansen,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

Please feel free to reopen the issue if you are still facing any issue.

Thanks.
