### ISSUE TITLE
Convert a custom data from quote to order?

### ISSUE THREAD

**Issue by Edward-Nguyen** [magento/magento2#1616]
Hi all,

I'm creating a new module on Magento 2 and I found a problem when I try to convert a custom data value from quote to order. I need to get it in event sales_order_place_after.
In my "collect" fuction, I set a custom value for quote $quote->setDemo('a');
Then in file "fieldset.xml", I write a code block
<fieldset id="sales_convert_quote">
   <field name="gift_codes">
      <aspect name="to_order" />
   </field>
 </fieldset>
In file Magento\Quote\Model\Quote\Address\ToOrder.php
function convert, the variable $order I can get "demo" value.
Then in file Magento\Framework\Reflection\DataObjectProcessor function buildOutputDataArray, it uses interface \Magento\Sales\Api\Data\OrderInterface to get method maps and it doesn't have function setDemo or getDemo so output doesn't have "demo" value.
Because \Magento\Sales\Api\Data\OrderInterface is a core file so I can't edit it.
Anyone know how I can convert a custom value from quote to order?
 Please help me.

Thank you very much.

**Comment by Edward-Nguyen** [comment]
I tried add 2 function get and set demo in \Magento\Sales\Api\Data\OrderInterface and \Magento\Sales\Model\Order and I can get demo value.
I aslo tried to rewrite 2 this file but it doesn't work. 
Anyone can help me?

**Comment by vpelipenko** [comment]
To convert some data from quote to order you just need to define this in your fieldset.xml, for example use

**Comment by FireKirin** [comment]
@vpelipenko I did the same as you said but it does not work.

**Comment by Edward-Nguyen** [comment]
@vpelipenko Yes, I did it but it didn't work. I need to use an event to get "demo" from quote and set it to order.
Could you help me?

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-41474

**Comment by Edward-Nguyen** [comment]
How can I see your internal ticket MAGETWO-41474?

**Comment by vpelipenko** [comment]
It is for our needs to track the progress.

**Comment by choukalos** [comment]
@Edward-Nguyen when we close our internal ticket we'll close this github issue.  Internally we're treating this as a major bug and are targeting this to be addressed in the near term.

**Comment by Edward-Nguyen** [comment]
@vpelipenko @choukalos Thank you very much.

**Comment by piotrekkaminski** [comment]
It was fixed and should be published soon.

**Comment by bulbulagarwal896** [comment]
Hello, i am still having same issue.

**Comment by TheFrankman** [comment]
I can only assume that this still hasn't been fixed. I'm on version 2.0.7 and still no luck. 

Additionally I don't see anything in the codebase to handle sales_convert_quote only payments, addresses, etc. 

I'd prefer to do this the proper way, I also don't see how it would work without the appropriate getters and setters in the order / invoice interface.

**Comment by hemant2586** [comment]
I am also struggling to convert quote additional options to order Item. In Magento2, the event sales_convert_quote_item_to_order_item is removed, so have to check for different way. I am looking for alternative but no luck yet. Please help me if anyone have idea about this.

Thanks in advance!
Himmat

**Comment by yohanespradono** [comment]
i am also struggling on convertin quote address custom field to order address
