### ISSUE TITLE
Page title not showing on product page.

### ISSUE THREAD

**Issue by drew7721** [magento/magento2#16249]
### Preconditions
1. Magento 2.2.4 
2. PHP 7.1.17
3. Mysql 5.6.39-83.1
4. Nginx

### Steps to reproduce
1.  Fresh install 2.2.4 (tag)
2. Install sample data
3. Edit any product, delete meta title.
4. Go to a product page and note that there is not page title. In the header, the `<title>` element is empty.

### Expected result
1. The product name should be set as the page title and be displayed.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/9411699/41605693-f2900150-73af-11e8-8882-d28b99f71e96.png">

### Actual result
1. <img width="581" alt="image" src="https://user-images.githubusercontent.com/9411699/41605627-d20ae8be-73af-11e8-82eb-da29c500abc8.png">

There is no title, if you look at the browser tab and in the source, no page title is set on the product page.

**Comment by kkrieger85** [comment]
@drew7721 Please add **PHP Version, MySQL version, Web Server** to your **preconditions**

Does this issue also occur on vanilla magento without sample data?

**Comment by drew7721** [comment]
yes. It's not the sample data. It has to do with the latest commits in the https://github.com/magento/magento2/commits/2.2.4/app/code/Magento/Catalog/Block/Product/View.php class. I think the product initialization is not done as it should.

**Comment by drew7721** [comment]
I guess moving the contents of the `_prepareLayout()` method into a helper as an optimization was the intention but stuff seems to have been broken doing so.. 😞

**Comment by pemann** [comment]
This is pretty critical.

**Comment by chirag-wagento** [comment]
I am working on this PR.

**Comment by novakivskiy** [comment]
solution like hotfix
In the [/app/code/Magento/Catalog/Helper/Product/View.php](https://github.com/magento/magento2/blob/2.2.4/app/code/Magento/Catalog/Helper/Product/View.php#L119)

replace 
```
  if ($title) {
            $pageConfig->getTitle()->set($title);
        }
```

```
  if ($title) {
            $pageConfig->getTitle()->set($title);
        }else{
            $pageConfig->getTitle()->set($product->getName());
        }
```

**Comment by ghost** [comment]
I want to work on this issue. please assign me

**Comment by emiprotech** [comment]
I want to work on this issue. please assign me

**Comment by ghost** [comment]
@drew7721, thank you for your report.
This issue is already fixed. Please update your instance to the latest version.
![image](https://user-images.githubusercontent.com/40756187/42277476-2a35dd90-7fa0-11e8-982f-84d47d9e24d6.png)

**Comment by michelve** [comment]
i updated to magento 2.2.5 and this fix is not there.

thank you for the hotfix @novakivskiy

**Comment by chris-pook** [comment]
This is indeed still happening in 2.2.5. Re-opening until resolved.

**Comment by ghost** [comment]
@chris-pook, please provide obvious steps to reproduce.

**Comment by josephmcdermott** [comment]
This is when the product has no meta title I believe. On creating a product via the admin panel the meta title is auto-populated, but when creating a product through other means such as the API, they meta title can remain empty.

@engcom-backlog-pb create a new product in a vanilla 2.2.5, then edit the product and delete the meta title, and then you will see that the product has no title on the frontend.

I suppose the product title should never be empty on the frontend so the core code should have the suggested fix from @novakivskiy ?

**Comment by josephmcdermott** [comment]
Apologies, looks like you have already fixed this in 2.3-develop:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Helper/Product/View.php#L115

**Comment by ghost** [comment]
@josephmcdermott , thank you for clarification.
We've acknowledged the issue and added to our backlog.

**Comment by peterjaap** [comment]
Fixed in 2.2.6; https://github.com/magento/magento2/blob/2.2.6/app/code/Magento/Catalog/Helper/Product/View.php#L118

**Comment by adrian-martinez-interactiv4** [comment]
As @peterjaap said, this has been already fixed for 2.2 branch in https://github.com/magento/magento2/commit/0a38b845508577e38d79280288a4fc716f2d1108. We are closing this issue as fixed.
