### ISSUE TITLE
How to copy custom data from quote to order and order item?

### ISSUE THREAD

**Issue by FireKirin** [magento/magento2#1632]
I am building a custom module in magento 2 that have a custom discount. I am trying to copy the discount from quote, quote item to order and order item.
In magento 1, I declare in config.xml like this:
 

    <fieldsets>
            <sales_convert_quote_address>
                <custom_discount_amount><to_order>*</to_order></custome_discount_amount>
                <base_custom_discount_amount><to_order>*</to_order></base_custome_discount_amount>
            </sales_convert_quote_address>
            <sales_convert_quote_item>
                <custome_discount_amount><to_order_item>*</to_order_item></custome_discount_amount>
                <base_custom_discount_amount><to_order_item>*</to_order_item></base_custom_discount_amount>
            </sales_convert_quote_item>
        </fieldsets> 

and my custom discount amount was copied to tables: sales_flat_order and sales_flat_order_item as expected.

In Magento 2, I created a file name: fieldset.xml with this code:

    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Object/etc/fieldset.xsd">
    <scope id="global">
        <fieldset id="sales_convert_quote_item">
            <field name="custom_discount_amount">
                <aspect name="to_order_item" />
            </field>
            <field name="base_custom_discount_amount">
                <aspect name="to_order_item" />
            </field>
        </fieldset>         
          <fieldset id="sales_convert_quote_address">
            <field name="custom_discount_amount">
                <aspect name="to_order" />
            </field>
            <field name="base_custom_discount_amount">
                <aspect name="to_order" />
            </field>
        </fieldset>   
    </scope>
</config>
but there is no success.
What else I need to do in magento 2 to make it works? Can you guys please help me?

**Comment by vpelipenko** [comment]
Related issue https://github.com/magento/magento2/issues/1616.

**Comment by vpelipenko** [comment]
@FireKirin, did you flush cache after adding new fieldset.xml? Did you add new columns for sales_flat_order and sales_flat_order_item tables?

**Comment by FireKirin** [comment]
@vpelipenko yes, I added new columns and flushed cache many times (even it always disabled). nothing change :(

**Comment by vpelipenko** [comment]
Try this code:

```
<fieldset id="quote_convert_item">
    <field name="custom_discount_amount">
        <aspect name="to_order_item" />
    </field>
    <field name="base_custom_discount_amount">
        <aspect name="to_order_item" />
    </field>
</fieldset>         
<fieldset id="quote_convert_address">
    <field name="custom_discount_amount">
        <aspect name="to_order" />
    </field>
    <field name="base_custom_discount_amount">
        <aspect name="to_order" />
    </field>
</fieldset>   
```

**Comment by FireKirin** [comment]
Hi @vpelipenko it still does not work. Is it a bug of magento2?

**Comment by vpelipenko** [comment]
Probably, yes. We'll investigate this issue.

**Comment by Edward-Nguyen** [comment]
As I said, I need to add 2 get and set "demo" methods in files \Magento\Sales\Api\Data\OrderInterface and file \Magento\Sales\Model\Order then I can get demo value, but I can't override core file in my module.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-41474

**Comment by okorshenko** [comment]
@FireKirin , Are you still able to reproduce this issue? Seems like this issue was fixed in https://github.com/magento/magento2/commit/499b7733bd6aa41933ee7e2bfada6d7528194df4

**Comment by okorshenko** [comment]
@FireKirin , Please, let us know if you still have an issue

**Comment by Nehace40** [comment]
@vpelipenko  I have same issue and use your solution which is given above but its not converting,
@okorshenko "Seems like this issue was fixed in 499b773" made changes like this but it still not working

**Comment by webspeaks** [comment]
Doesn't work for me as well. I am on v 2.0.7

**Comment by MagePsycho** [comment]
Doesn't work for me in 2.1.0

**Comment by mauromm** [comment]
I tried in magento 2.1.0. It doesn't work.

```
<scope id="global">
    <fieldset id="sales_convert_quote">
        <field name="my_field">
            <aspect name="to_order" />
        </field>
    </fieldset>
</scope>
```

**Comment by ccasciotti** [comment]
Doesn't work for me on 2.1.1, i have to use events to convert a custom attribute from quote to order
