### ISSUE TITLE
Error with translation of confirmation modal buttons

### ISSUE THREAD

**Issue by delyriand** [magento/magento2#17193]
### Preconditions
1. Magento 2.2.5 with samples data
2. French language packe (like Imaginaerum/magento2-language-fr-fr)
3. Change locale configuration to fr_FR - General > Locale Options > Locale = French (France)
4. Enable:
     - js and css merge (dev/css/merge_css_files and dev/js/merge_files)
     - js bundling (dev/js/enable_js_bundling)
     - production mode

### Steps to reproduce
1. Add a product to cart
2. Open mincart and click on trash pictogram

### Expected result
1. Confirmation modal with two butttons in french: "Annuler" and "OK" 

### Actual result
1. Confirmation modal with two butttons in english: "Cancel" and "OK" 
![confirmation_modal](https://user-images.githubusercontent.com/465524/43322948-7d68ce6a-91b0-11e8-9c62-e0322cffcd20.png)

**Comment by magento-engcom-team** [comment]
Hi @delyriand. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@delyriand do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @delyriand, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @delyriand. Thank you for your report. 
The issue has been fixed in magento/magento2#17275 by @Karlasa in 2.2-develop branch
Related commit(s):
 - [5cfde8a4231203033d78452e3df64a26f0b8af19](https://github.com/magento/magento2/commit/5cfde8a4231203033d78452e3df64a26f0b8af19)

The fix will be available with the upcoming 2.2.7 release.

**Comment by sidolov** [comment]
Hi @delyriand. Thank you for your report. 
The issue has been fixed in magento/magento2#17359 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [76b1481c375a53fcfbb111e3fa3c6eb3deb74d74](https://github.com/magento/magento2/commit/76b1481c375a53fcfbb111e3fa3c6eb3deb74d74)

The fix will be available with the upcoming 2.3.0 release.

**Comment by Nastradoomus** [comment]
2.3.3 Still not working like it should.

![ok-cancel](https://user-images.githubusercontent.com/35959304/69614407-be4c2e80-103b-11ea-84a2-478ef1fcdbaf.png)

fi_FI.csv:
"Cancel","Peruuta"

js_translation.json:
"Cancel":"Peruuta"

For now i just run it over with require-js.
Copy: vendor/magento/module-ui/view/base/web/js/modal/confirm.js
To: app/design/frontend/YOUR/THEME/web/js/magento-ui-modal/confirm.js

Edit require-js:
    map: {
        '*': {
                 ...
                 "Magento_Ui/js/modal/confirm": "js/magento-ui-modal/confirm"
                 ...

**Comment by torhoehn** [comment]
@Nastradoomus So you think there's another problem e.g. the loading order?

**Comment by Nastradoomus** [comment]
> @Nastradoomus So you think there's another problem e.g. the loading order?

First i'm sorry i don't have the time right now to test things with vanilla Magento installation but there are two things that comes to my mind.

As you said:
Loading order or some process that isn't finished before paint.
or
Litespeed Litemage cache (which obviously complicates things)

It is always the JavaScript translations that fails. It's actually quite irritating to update Magento and find out several days later that a translation which worked on previous release does not work anymore and trying to fix that error with caching and all is a pain in the...

I was wondering that would it be beneficial to hard translate JavaScript on deploy or does it break definitions of i18n?

**Comment by torhoehn** [comment]
@Nastradoomus I'll test it tomorrow on a vanilla Magento instance.

**Comment by torhoehn** [comment]
@Nastradoomus On a vanilla Magento instance I installed the official German language pack. I removed an article via minicart and the cancel button was translated.

<img width="1552" alt="Screenshot 2019-11-28 at 14 16 43" src="https://user-images.githubusercontent.com/1945725/69809336-d8c40a80-11e9-11ea-9c3e-b2c7ed083cfc.png">

**Comment by Nastradoomus** [comment]
I'll get back on this next week. I'll see if i can get an instance running for you to test.
