### ISSUE TITLE
No children data for \Magento\Catalog\Model\CategoryManagement::getTree($categoryId) after first call.

### ISSUE THREAD

**Issue by j0um** [magento/magento2#17297]
The Magento implementation of the CategoryManagementInterface::getTree($rootCategoryId) does not provide a tree with children data after the first function usage.

### Preconditions
1. Magento 2.2.5
2. Php 7.1.15,  Percona Mysql 5.7.22-22

### Steps to reproduce
In a console script making use of \Magento\Catalog\Model\CategoryManagement, do the following :
$categoryId = 1;   // Any valid category id.
$hasChildren = $categoryManagement->getTree($categoryId)->getChildrenData();
$noChildren = $categoryManagement->getTree($categoryId)->getChildrenData();

if (count($hasChildren) != count($noChildren)) {
   // Well this is unexpected.
}

### Expected result
I expect $noChildren to be populated with children.

### Actual result
$noChildren's children_data is an empty array.

**Comment by magento-engcom-team** [comment]
Hi @j0um. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@j0um do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by j0um** [comment]
@magento-engcom-team give me {2.2.5} instance

**Comment by ghost** [comment]
Hi @j0um, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @pmclain. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @j0um. Thank you for your report. 
The issue has been fixed in magento/magento2#18705 by @pmclain in 2.3-develop branch
Related commit(s):
 - [0db0e84dee2a3c1ef66ab83ed7950a9db9b5af17](https://github.com/magento/magento2/commit/0db0e84dee2a3c1ef66ab83ed7950a9db9b5af17)

The fix will be available with the upcoming 2.3.2 release.

**Comment by themystery404** [comment]
Hello @pmclain , this issue still reproduced for me, if I need to get several trees of different Root Categories. 
Example
```
        foreach ($rootCategoryIds as $rootCategoryId) {
            $categoryManagement = $this->categoryManagementFactory->create();
            $tree = $categoryManagement->getTree($rootCategoryId, 5);
        }
```
Only first tree has children

It caused shared $categoryCollection property in Magento/Catalog/Model/Category/Tree.php 
I fixed this issue by adding to my di.xml next code

```
    <type name="Magento\Catalog\Model\Category\Tree">
        <arguments>
            <argument name="categoryCollection" shared="false" xsi:type="object">Magento\Catalog\Model\ResourceModel\Category\Collection</argument>
        </arguments>
    </type>
    <type name="Magento\Catalog\Model\CategoryManagement">
        <arguments>
            <argument name="categoryTree" shared="false" xsi:type="object">Magento\Catalog\Model\Category\Tree</argument>
        </arguments>
    </type>
```

But, would be better to fix this using by using factory for collection in __construct in Magento core code

What do you think?
