### ISSUE TITLE
session_start(): Failed to read session data: user (path: /var/lib/php/sessions)

### ISSUE THREAD

**Issue by AykutCevik** [magento/magento2#17310]
While viewing the orders page in the admin area and opening several orders I'm facing an error message.

### Preconditions
1. PHP 7.1.17-1
2. Redis server v=3.0.6
3. set redis as the session handler in env.php
3.1 see session config:
```
`'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => '<IP>',
            'port' => '<PORT>',
            'password' => '',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '0',
            'compression_threshold' => '2048',
            'compression_library' => 'gzip',
            'log_level' => '1',
            'max_concurrency' => '6',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '0',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000'
        ]
    ],`
```
2. have orders in your system

### Steps to reproduce
1. Browse the order pages in the admin area
2. click on an order
3. go back to the order list
4. click on an other order again
5. retry several times
6. see error message in the admin area:
![image](https://user-images.githubusercontent.com/1965251/43528674-ce79e602-95a9-11e8-8039-ef980e45f29e.png)

### Expected result
1. Browsing pages in the admin area shouldn't throw an error

### Actual result
Message in step 6 of reproduction appears, in the log I can find the following:
```
{"0":"Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /vendor/magento/framework/Session/SessionManager.php on line 193","1":"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'session_start()...', '/home/cloudpane...', 193, Array)\n#1 /vendor/magento/framework/Session/SessionManager.php(193): session_start()\n#2 /generated/code/Magento/Backend/Model/Session/Interceptor.php(63): Magento\Framework\Session\SessionManager->start()\n#3 /vendor/magento/framework/Session/SessionManager.php(130): Magento\Backend\Model\Session\Interceptor->start()\n#4 /generated/code/Magento/Backend/Model/Session/Interceptor.php(14): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Backend\Model\Session\AdminConfig), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))\n#5 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Backend\Model\Session\Interceptor->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Backend\Model\Session\AdminConfig), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))\n#6 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Backend...', Array)\n#7 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')\n#8 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Backend...')\n#9 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'session', 'Magento\\Store\\A...')\n#10 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Store\\A...', Array, Array)\n#11 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Store\\A...', Array, Array)\n#12 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\A...')\n#13 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Store\\A...')\n#14 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'redirect', 'Magento\\Backend...')\n#15 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Backend...', Array, Array)\n#16 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Backend...', Array, Array)\n#17 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')\n#18 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Backend...')\n#19 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Backend...', NULL, 'context', 'Magento\\Ui\\Cont...')\n#20 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Ui\\Cont...', Array, Array)\n#21 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Ui\\Cont...', Array, Array)\n#22 /vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Ui\\Cont...', Array)\n#23 /vendor/magento/framework/App/ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Ui\\Cont...')\n#24 /vendor/magento/framework/App/Router/Base.php(297): Magento\Framework\App\ActionFactory->create('Magento\\Ui\\Cont...')\n#25 /vendor/magento/framework/App/Router/Base.php(158): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)\n#26 /vendor/magento/framework/App/FrontController.php(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))\n#27 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))\n#28 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)\n#29 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))\n#30 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)\n#31 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))\n#32 /generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()\n#33 /vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()\n#34 /pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))\n#35 {main}","url":"/admin/mui/index/render/key/[MASKED]/order_id/[MASKED]]?namespace=payone_sales_order_view_transactionstatus_grid&sorting%5Bfield%5D=sequencenumber&sorting%5Bdirection%5D=asc&isAjax=true","script_name":"/index.php"}
```

The path `/var/lib/php/sessions` was never set anywhere. I actually can't understand why Magento is trying to use the path when redis is configured. It may be related to `SessionManager->registerSaveHandler()`?

**Comment by magento-engcom-team** [comment]
Hi @AykutCevik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@AykutCevik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @AykutCevik, thank you for your report. I'm not able to reproduce this issue on 2.2-develop branch. Could you please specify magento version you use?

**Comment by ananth-iyer** [comment]
@AykutCevik  Can you tell us which link you followed to install Redis?

**Comment by AykutCevik** [comment]
@engcom-backlog-nickolas I'm using Magento CE 2.2.5.
@ananth-iyer what do you mean by link and following it to install Redis?

**Comment by ananth-iyer** [comment]
Yes, the website you followed to install Redis.

**Comment by josephmcdermott** [comment]
Agree with @AykutCevik we have this appearing in `var/report` every now and then, its very difficult to track down and/or replicate but is happening. We are also using Redis for session saves.

I was able to replicate using the view order > view order grid as @AykutCevik suggested, for a split second I saw the error on the Order view page, before being taken to the order grid.

Here is the stack trace generated:
```
{"0":"Warning: session_start(): Failed to read session data: user (path: /var/session/) in /vendor/magento/framework/Session/SessionManager.php on line 189","1":"
0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'session_start()...', '/var/www/vhosts...', 189, Array)\n
1 /vendor/magento/framework/Session/SessionManager.php(189): session_start()\n
2 /generated/code/Magento/Backend/Model/Session/Interceptor.php(24): Magento\\Framework\\Session\\SessionManager->start()\n
3 /vendor/magento/framework/Session/SessionManager.php(130): Magento\\Backend\\Model\\Session\\Interceptor->start()\n
4 /generated/code/Magento/Backend/Model/Session/Interceptor.php(14): Magento\\Framework\\Session\\SessionManager->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Backend\\Model\\Session\\AdminConfig), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n
5 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\\Backend\\Model\\Session\\Interceptor->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Backend\\Model\\Session\\AdminConfig), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n
6 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Backend...', Array)\n
7 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Backend...')\n
8 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Backend...')\n
9 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Store\\\\A...')\n
10 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Store\\\\A...')\n
11 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Backend...')\n
12 /vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Backend...')\n
13 /vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Ui\\\\Cont...', Array)\n
14 /vendor/magento/framework/App/ActionFactory.php(40): Magento\\Framework\\ObjectManager\\ObjectManager->create('Magento\\\\Ui\\\\Cont...')\n
15 /vendor/magento/framework/App/Router/Base.php(297): Magento\\Framework\\App\\ActionFactory->create('Magento\\\\Ui\\\\Cont...')\n
16 /vendor/magento/framework/App/Router/Base.php(158): Magento\\Framework\\App\\Router\\Base->matchAction(Object(Magento\\Framework\\App\\Request\\Http), Array)\n
17 /vendor/magento/framework/App/FrontController.php(50): Magento\\Framework\\App\\Router\\Base->match(Object(Magento\\Framework\\App\\Request\\Http))\n
18 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
19 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n
20 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
21 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n
22 /vendor/magento/framework/App/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
23 /vendor/magento/framework/App/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n
24 /pub/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n
25 {main}","url":"/admin/mui/bookmark/save/key/0194bbb75ffe47f654ca4e5343628982d1264a99d6a680a341326e9111d89296/?isAjax=true","script_name":"/index.php"}
```

From searching online, it appears to be either
a) a red herring message and some session `read` data is being returned as NULL or FALSE instead of '',
b) or Magento is falling back to the native session handler in `\Magento\Framework\Session\SaveHandlerFactory::create`
c) or something else :)

**Comment by AykutCevik** [comment]
May this be related to `max_concurrency` where the fallback is the default PHP session handling? 🤔
(https://devdocs.magento.com/guides/v2.2/config-guide/redis/redis-session.html)

**Comment by engcom-backlog-nickolas** [comment]
@AykutCevik, thanks for feedback, and @josephmcdermott for details. I've tested on 2.2.5 with order view and order grid. Also I've been trying other different manipulation and still couldn't get described error on screen nor in logs. 
Looks like we still missing some important steps or details, to replicate and therefore to fix this issue.
I'm leaving this issue open and if you guys have any details, feel free to share in order to write specific steps to reproduce.

**Comment by chris-pook** [comment]
@AykutCevik I believe this is indeed due to the `max_concurrency` value in env.php under the session => redis section. Magento is failing to save/retrieve sessions from the redis back-end based on the value of this config. However the error that's being reported here is stating that having failed to access Redis, the session also couldn't be accessed from the native PHP session directory (it may not exist on the server in the php.ini specified location, have a check on your server).

@engcom-backlog-nickolas, to consistently replicate the issue please try the following steps:

**Preconditions**
- Redis enabled for sessions
- Sessions Redis env.php config as per defaults in M2 devdocs (Max_concurency => 6)

**Steps to reproduce**
- Using Google Chrome, login to the admin area
- Open 10 or more browser tabs with the orders grid page
- Click the left most tab
- Hold shift and click the right most tab (this selects all tabs)
- Right click the right most tab and select "reload"
- Check the tabs after they have all reloaded, only ~6 will successfully load, the rest will exhibit this error *
- Check the var/report folder for the start_session error report relating to the tabs that failed.
- Now modify the `max_concurrency` to a value greater than the number of tabs, reload them all again and none will fail.

\* if you aren't seeing this error, check in your PHP sessions directory. It should be empty (as Redis is the session back-end of course), however if there are session files building up in the directory, you are seeing a symptom of the same problem here, although it hides the error because PHP handles the session as a fallback. @AykutCevik try a `php -i | grep session` and check your session save path is available and has the correct permissions. Once corrected you'll likely see PHP handling the sessions rather than your error.

This is all happening because of contention for accessing session data from single threaded Redis. The `max_concurency` config value defines the size of the queue that can form to access Redis and retrieve the session. In the event of lots of traffic hitting the server at once, some users will receive this behavior because the queue is full, so the request to access the Redis session back-end is denied. PHP session handling kicks in here and if configured correctly will start creating sessions (this is still an issue as Redis is meant to be doing this for a reason, PHP will be saving to local disk so sessions wont be available across multiple web servers etc).

This same error will happen also on the front-end of Magento2. Try it by opening 10 or more tabs of different pages; clear the FPC (or just disable full page cache to emulate hitting un-cached pages); reload all the tabs at once as above and again some will fail. This is particularly bad when you have items in your cart as the local storage is not synched, resulting in the "I have no items in my cart, but there are items in my mini-cart" scenario I'm sure you've come across.

I would suggest that "6" as a default for `max_concurrency` is no good for most sites and that a better explanation of how to derive the correct value for the config should be made available. The Devdocs state "at least 10% of the number of PHP processes" but not why. I would assume that with 10% covered, in the unlikely(ish) event all your users hit pages at the same time (think Flash sale, Black Friday etc), 90% would receive this behavior still. I'm guessing the 10% suggestion is a stab in the dark at the likely percentage of requests that might all hit at the same time. This value should probably be derived from the `max_children` / `max_requests` values of the server's PHP-FPM pools, looking to accommodate as many requests as might come in concurrently.

Would be great to get a view from Magento on this!

Thanks

**Comment by chris-pook** [comment]
**Update on the above comment**

Having looked further in to this, I think potentially my above comment may not be completely accurate. The key being the code implementation of the function below:

`\Cm\RedisSession\Handler::read()`

This function implements the locking mechanism and appears to hold the lock per $sessionId. So this issue is not a problem globally across multiple sessions after all. I.e on a flash sale day, it would not be the case that the first 6 concurrent requests globally would get through and the rest bounce. Instead you would see all requests served but for each individual user's session only 6 concurrent requests allowed through.

To test this, I have repeated the front-end mass concurrent reload steps from before (with `max_concurrency` set to 6 still) only this time using `ab`:

```
ab -c 100 -n 100 <M2-instance-domain>

Concurrency Level:      100
Time taken for tests:   6.037 seconds
Complete requests:      100
Failed requests:        0
```

Here 100 concurrent requests are served no problem with no failures despite sessions being started.

Having discovered this I am happy that the 10% of PHP processes (php-fpm `max_children`) suggestion is probably quite sound. You don't want a single user session hogging the Redis instance making everyone else wait, so better to serve them 503 errors beyond their first X concurrent requests.

The likelihood is that this limit will only ever be exceeded by admin users trying to do too much at once, or abuse of the front-end.

It would still be great to get a line from Magento here to confirm. Apologies if this is going back over old ground that may have been covered elsewhere.

Thanks

**Comment by engcom-backlog-nickolas** [comment]
@AykutCevik, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by AykutCevik** [comment]
A Magento core dev may have a look since we can't provide any updates.

**Comment by maximecarey** [comment]
I can confirm this is currently happening on our site (Magento 2.2.5). We're getting non-responsive checkout process randomly happening. The max_concurrency value was still at the default value of 6. I'm increasing it to 30. The permission for /var/lib/php/sessions are set to drwx-wx-wt  root:root, which explains why the FPM pool cannot read in it, but it obviously shouldn't be trying as redis should be acting as session backend.

`
Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/vhosts/www.com/subdomains/shop/vendor/magento/framework/Session/SessionManager.php on line 189 {"exception":"[object] (Exception(code: 0): Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/vhosts/www.com/subdomains/shop/vendor/magento/framework/Session/SessionManager.php on line 189 at /var/www/vhosts/www.com/subdomains/shop/vendor/magento/framework/App/ErrorHandler.php:61)"} []
`

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
HI @AykutCevik Thank you for you report, the fix for this issue has already available in 2.2-develop and 2.3-develop branch, fixed by this pr -> https://github.com/magento/magento2/pull/17608

**Comment by cscd98** [comment]
@engcom-backlog-nazar I am still seeing this issue in 2.3.0. I am using it for sessions and cache, both on different ports.

This is a major issue, as it causing payments to fail in dev environment - which makes it look like a coding issue with the plugin but I believe in fact it is due to Magento not being able to read session data.

Is Magento falling back to /var/lib/php/sessions? Would that cause a different session and therefore no quote? Is there a permission issue?

Is Magento 2 compatible with redis 5.0.x?

report:
```
{"0":"Warning: session_start(): Failed to read session data: user (path: \/var\/lib\/php\/sessions) in \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/Session\/SessionManager.php on line 191","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'session_start()...', '\/var\/www\/vhosts...', 191, Array)\n#1 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/Session\/SessionManager.php(191): session_start()\n#2 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\Session\\SessionManager->start()\n#3 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Session\\Generic\\Interceptor->___callParent('start', Array)\n#4 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\Session\\Generic\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#5 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(52): Magento\\Framework\\Session\\Generic\\Interceptor->___callPlugins('start', Array, Array)\n#6 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/Session\/SessionManager.php(127): Magento\\Framework\\Session\\Generic\\Interceptor->start()\n#7 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(14): Magento\\Framework\\Session\\SessionManager->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State\\Interceptor))\n#8 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(116): Magento\\Framework\\Session\\Generic\\Interceptor->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State\\Interceptor))\n#9 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#10 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#11 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(160): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#12 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'session', 'Magento\\\\Framewo...')\n#13 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#14 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#15 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#16 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(160): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#17 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'formKey', 'Magento\\\\Framewo...')\n#18 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#19 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#20 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#21 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(160): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#22 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'formKeyValidato...', 'CsrfRequestVali...')\n#23 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('CsrfRequestVali...', Array, Array)\n#24 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('CsrfRequestVali...', Array, Array)\n#25 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('CsrfRequestVali...')\n#26 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(196): Magento\\Framework\\ObjectManager\\ObjectManager->get('CsrfRequestVali...')\n#27 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(172): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->parseArray(Array)\n#28 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, NULL, NULL, 'validators', 'RequestValidato...')\n#29 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('RequestValidato...', Array, Array)\n#30 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('RequestValidato...', Array, Array)\n#31 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('RequestValidato...')\n#32 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/App\/FrontController.php(71): Magento\\Framework\\ObjectManager\\ObjectManager->get('RequestValidato...')\n#33 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(14): Magento\\Framework\\App\\FrontController->__construct(Object(Magento\\Framework\\App\\RouterList), Object(Magento\\Framework\\App\\Response\\Http\\Interceptor), NULL, NULL, NULL)\n#34 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(116): Magento\\Framework\\App\\FrontController\\Interceptor->__construct(Object(Magento\\Framework\\App\\RouterList), Object(Magento\\Framework\\App\\Response\\Http\\Interceptor), NULL, NULL, NULL)\n#35 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#36 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#37 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/App\/Http.php(134): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#38 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#39 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#40 \/var\/www\/vhosts\/vax-uk2-dev\/releases\/20190208104332\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#41 {main}","url":"\/newsletter\/subscriber\/checkEmail","script_name":"\/index.php"}
```

redis-cli -v
```
redis-cli 4.0.11
```

ls -la /var/lib/php/
```
drwxrwxrwx  2 root root 98304 Feb 11 09:41 sessions
```

There are session files in the folder.

php-fpm7.2 -i | grep session
```
igbinary session support => yes
redis.session.lock_expire => 0 => 0
redis.session.lock_retries => 10 => 10
redis.session.lock_wait_time => 2000 => 2000
redis.session.locking_enabled => 0 => 0
session
session.auto_start => Off => Off
session.cache_expire => 180 => 180
session.cache_limiter => nocache => nocache
session.cookie_domain => no value => no value
session.cookie_httponly => no value => no value
session.cookie_lifetime => 0 => 0
session.cookie_path => / => /
session.cookie_secure => 0 => 0
session.gc_divisor => 1000 => 1000
session.gc_maxlifetime => 1440 => 1440
session.gc_probability => 1 => 1
session.lazy_write => On => On
session.name => PHPSESSID => PHPSESSID
session.referer_check => no value => no value
session.save_handler => files => files
session.save_path => /var/lib/php/sessions => /var/lib/php/sessions
session.serialize_handler => php => php
session.sid_bits_per_character => 4 => 4
session.sid_length => 32 => 32
session.upload_progress.cleanup => On => On
session.upload_progress.enabled => On => On
session.upload_progress.freq => 1% => 1%
session.upload_progress.min_freq => 1 => 1
session.upload_progress.name => PHP_SESSION_UPLOAD_PROGRESS => PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix => upload_progress_ => upload_progress_
session.use_cookies => 1 => 1
session.use_only_cookies => 1 => 1
session.use_strict_mode => 0 => 0
session.use_trans_sid => 0 => 0
session.trans_sid_hosts => no value => no value
session.trans_sid_tags => a=href,area=href,frame=src,form= => a=href,area=href,frame=src,form=
```

max_concurrency is 6 in app/etc/env.php, max_children in php7.2-fpm is 15.

**Comment by chris-pook** [comment]
@craigcarnell @werfu do you get these same symptoms in a vanilla install of the relevant versions of M2? If it is the introduction of custom code that is causing it then as per [my comment](https://github.com/magento/magento2/issues/17310#issuecomment-410672582) I think this is certainly due to the limitation on max concurrency (usually only seen in the admin with multi tabs open). You should be able to trace the concurrent requests stemming from your code to work out what the max value needs to be to allow for it (or ideally reduce the number of requests).

**Comment by DigitalStartupUK** [comment]
This appears to be something that I've been suffering with lately. I have changed my `max_concurrency` from '6' to '20' _(technically I should be able to go to '25')_. However, I still get the Apache error emails through.

After changing `max_concurrency` in `env.php`, does anything need restarting for the changes to take affect? I'm currently in `Production Mode`.

**Comment by cscd98** [comment]
@chris-pook This seems to have gone away after increasing max_concurrency but it is very worrying

**Comment by wjpbill** [comment]
I've been directed to post on here by Yireo as they think my problem is the same.

Firstly, I'm not brilliantly technical so apologies if this isn't clear.

On a live M2.2.5 site, running in production mode with docroot set to pub, I've started seeing errors in exception.log

`[2019-03-03 10:50:36] main.CRITICAL: Report ID: webapi-5c7bb17c499c1; Message: Warning: session_start(): Failed to read session data: user (path: /dev/shm) in /chroot/home/myserver/mydomain.com/vendor/magento/framework/Session/SessionManager.php on line 189 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5c7bb17c499c1; Message: Warning: session_start(): Failed to read session data: user (path: /dev/shm) in /chroot/home/myserver/mydomain.com/vendor/magento/framework/Session/SessionManager.php on line 189 at /chroot/home/myserver/mydomain.com/vendor/magento/framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Warning: session_start(): Failed to read session data: user (path: /dev/shm) in /chroot/home/myserver/mydomain.com/vendor/magento/framework/Session/SessionManager.php on line 189 at /chroot/home/myserver/mydomain.com/vendor/magento/framework/App/ErrorHandler.php:61)"} []
`

In addition, I'm seeing a report generated that reads

`{"0":"Warning: session_start(): Failed to read session data: user (path: \/dev\/shm) in \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Session\/SessionManager.php on line 189","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'session_start()...', '\/chroot\/home\/a8...', 189, Array)\n#1 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Session\/SessionManager.php(189): session_start()\n#2 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\Session\\SessionManager->start()\n#3 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Session\\Generic\\Interceptor->___callParent('start', Array)\n#4 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\Session\\Generic\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#5 \/chroot\/home\/myserver\/mydomain.com\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(26): Magento\\Framework\\Session\\Generic\\Interceptor->___callPlugins('start', Array, Array)\n#6 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Session\/SessionManager.php(130): Magento\\Framework\\Session\\Generic\\Interceptor->start()\n#7 \/chroot\/home\/myserver\/mydomain.com\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(14): Magento\\Framework\\Session\\SessionManager->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n#8 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Magento\\Framework\\Session\\Generic\\Interceptor->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n#9 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#10 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Framewo...')\n#11 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Framewo...')\n#12 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Store\\\\A...')\n#13 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Store\\\\A...')\n#14 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Framewo...')\n#15 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Framewo...')\n#16 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Custome...', Array)\n#17 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/App\/ActionFactory.php(40): Magento\\Framework\\ObjectManager\\ObjectManager->create('Magento\\\\Custome...')\n#18 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/App\/Router\/Base.php(297): Magento\\Framework\\App\\ActionFactory->create('Magento\\\\Custome...')\n#19 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/App\/Router\/Base.php(158): Magento\\Framework\\App\\Router\\Base->matchAction(Object(Magento\\Framework\\App\\Request\\Http), Array)\n#20 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/App\/FrontController.php(50): Magento\\Framework\\App\\Router\\Base->match(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#23 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#24 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#26 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#27 \/chroot\/home\/myserver\/mydomain.com\/app\/code\/Infortis\/Cgen\/Plugin\/Magento\/Framework\/App\/FrontController.php(32): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#28 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Infortis\\Cgen\\Plugin\\Magento\\Framework\\App\\FrontController->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#29 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#30 \/chroot\/home\/myserver\/mydomain.com\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#31 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#32 \/chroot\/home\/myserver\/mydomain.com\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#33 \/chroot\/home\/myserver\/mydomain.com\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#34 {main}","url":"\/customer\/section\/load\/?sections=yireo-gtm-quote%2Cyireo-gtm-order&_=1551874746963","script_name":"\/index.php"}`

I don't know what the cause is but the tech support guys @ Yireo asked me to add it to this post in case someone could help me or that it helps someone else.

**Comment by DigitalStartupUK** [comment]
@wjpbill This appears to be related to your session handler such as Redis or Varnish. Perhaps they aren't configured to take on your increase in site traffic? I'd focus my investigation into that.

I had a similar issue, which has been discussed above. Where my Redis `max_concurrency` was left as default. I had to do some calculations to work out what I could increase it to, then set it to that. Since then I don't recall seeing this issue popup _(touch wood)_.

**Comment by wjpbill** [comment]
> @wjpbill This appears to be related to your session handler such as Redis or Varnish. Perhaps they aren't configured to take on your increase in site traffic? I'd focus my investigation into that.
> I had a similar issue, which has been discussed above. Where my Redis max_concurrency was left as default. I had to do some calculations to work out what I could increase it to, then set it to that. Since then I don't recall seeing this issue popup (touch wood).

Thanks for replying DigitalStatupUK, very much appreciated.

My hosting company got someone to work on it and they've increase max_concurrency to 20.

Fingers crossed it handles it all. It does seem a bit short sighted by Magento though not to flag it anywhere.

**Comment by DigitalStartupUK** [comment]
@wjpbill Awesome. Please, give us an update in the future to confirm the fix. Others would find that very useful to know.

**Comment by ghost** [comment]
Hi @DigitalStartupUK  Hi @wjpbill  so this issue related to `max_concurrency` ?

**Comment by wjpbill** [comment]
Hello everyone and @engcom-backlog-nazar

I got some help from senior engineers at the company I host with.

They agreed and changed max_concurrency from 6 to 20.

Since then, I haven't seen the problem again - fingers crossed!

Apologies for not replying sooner.

**Comment by ghost** [comment]
Hi folks, thanks @wjpbill for explanation, i'm will close this one, as problem related to php-configs, but if someone found another reason, feel free to reopen this one. thanks for collaboration :+1:

**Comment by fritzmg** [comment]
We are still getting this issue even after increasing the `max_concurrency` to `18`. We have set it now to `54` and are observing if this issue still occurs.

However - I still do not quite get why the native session fallback does not work. If I disable Redis for sessions, sessions with the native session storage work fine. But why does the fallback not work, when using Redis as the session storage?

**Comment by nickpiro** [comment]
I am having a similar issue on 2.2.8. On our Redis setup in the env.php from our hosting provider, there was no max_concurrency...So I've added it and made it 50. We're a fairly high traffic site, so I will be able to get a good idea and report back how it works! :)

**Comment by qrider** [comment]
> HI @AykutCevik Thank you for you report, the fix for this issue has already available in 2.2-develop and 2.3-develop branch, fixed by this pr -> #17608

Did this not fix the issue? What 2.3 release was this in?

**Comment by qrider** [comment]
Answered my own question. Looks like it is in at least 2.3.1. We are getting the error with the above patch. Bumped max_concurrency to 20 from 6 to see what happens.

**Comment by marcusirgens** [comment]
@qrider Did this solve your issue?

**Comment by marvinhinz** [comment]
I am also experiencing this error in magento 2.3.2 while in developer mode. Why doesnt the fallback from redis to files work?

**Comment by theozzz** [comment]
Hi everyone, increased from 6 to 20 seems to resolve the issue for us! Let's monitor things now.

**Comment by fritzmg** [comment]
This issue is, in principle, still happening in Magento 2.3.2. If you set `max_concurrency` to a low value, the fallback still does not work any subsequent concurrent request for the same sessions ends in a 503.

**Comment by nghelo** [comment]
This issue still happening in Magento 2.3.4 @magento-engcom-team  please give us your opinion.

**Comment by marvinhinz** [comment]
Why was this closed?

**Comment by marvinhinz** [comment]
> Hi folks, thanks @wjpbill for explanation, i'm will close this one, as problem related to php-configs, but if someone found another reason, feel free to reopen this one. thanks for collaboration 👍

This is not due to php config, its a wrong default configuration that is shipped with magento. It would be enough to just increase the value.

**Comment by nix0x00** [comment]
I confirm, this issue exists in **Magento 2.3.5-p1**.

**Comment by ihor-sviziev** [comment]
Re-opening this issue due to report and possible solution in https://github.com/magento/magento2/pull/29140

**Comment by fritzmg** [comment]
> Re-opening this issue due to reports [#17310 (comment)](https://github.com/magento/magento2/issues/17310#issuecomment-502406645) [#17310 (comment)](https://github.com/magento/magento2/issues/17310#issuecomment-595753077) [#17310 (comment)](https://github.com/magento/magento2/issues/17310#issuecomment-658299391) and possible solution in #29140

That's not really a solution to the original problem. The problem is, that the _fallback_ is not working, in case the max concurrency limit is reached. Magento should not rely upon this limit being high enough, should it?

**Comment by ihor-sviziev** [comment]
> > Re-opening this issue due to reports [#17310 (comment)](https://github.com/magento/magento2/issues/17310#issuecomment-502406645) [#17310 (comment)](https://github.com/magento/magento2/issues/17310#issuecomment-595753077) [#17310 (comment)](https://github.com/magento/magento2/issues/17310#issuecomment-658299391) and possible solution in #29140
> 
> That's not really a solution to the original problem. The problem is, that the _fallback_ is not working, in case the max concurrency limit is reached. Magento should not rely upon this limit being high enough, should it?

 Could you please explain which fallback doesn’t work? If you mean fallback to files - seems like it’s wrong direction, as sessions should have only one shared storage, otherwise it will not work correctly when you have multiple web nodes

**Comment by fritzmg** [comment]
> Could you please explain which fallback doesn’t work? If you mean fallback to files

Yes, the automatic fallback to the native session storage.

> seems like it’s wrong direction, as sessions should have only one shared storage, otherwise it will not work correctly when you have multiple web nodes

Sure, seems like a valid point, but if that is the case, then Magento should not try to fall back to the native session storage in the first place, should it?

**Comment by ihor-sviziev** [comment]
@fritzmg i think it’s good idea. Please create pull request with your suggestion, will definitely review it! Anyway - even increasing max concurrency should fix the issue and it’s just simpler solution.

**Comment by fritzmg** [comment]
> Please create pull request with your suggestion, will definitely review it!

Unfortunately I still know very little about Magento's session handling implementation at this point, so it might take some time ;).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36187` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rudstone** [comment]
h

**Comment by rajankouzina** [comment]
I also face the same issue every time I clone my Magento Directory.

This is a temporary fix that works for me.

add this line in app/etc/env.php file.

    'session' => [
        'save' => 'files',
        'save_path' => '/var/html/www/[magento site]/var/session'      //important

save path should be the absolute path for Magento directory.

**Comment by Nazar65** [comment]
Why this is P4 ?  this issue is easy reproduce in any page just pressing multiple times F5 button and then we got 
![Screenshot_2020-10-12 Screenshot](https://user-images.githubusercontent.com/2481206/96140908-22543b80-0f09-11eb-8c19-3ed515e6f2d7.png)

**Comment by ihor-sviziev** [comment]
Hi,

Due to this issue, we faced a few issues in the custom extensions that were resulting in the partially broken product page (**custom options and add to cart blocks**) were missing AND then cached in Varnish.

The investigation shown that basically when you're just creating any session object - it tries to start the session and as result tries to connect to Redis.

In the constructor, it just executes the `start` method:
https://github.com/magento/magento2/blob/caefb4e63f0c726c996118c2707afaf63ed3c665/lib/internal/Magento/Framework/Session/SessionManager.php#L117-L142

This method runs `session_start`.
https://github.com/magento/magento2/blob/caefb4e63f0c726c996118c2707afaf63ed3c665/lib/internal/Magento/Framework/Session/SessionManager.php#L179-L222

**Comment by sidolov** [comment]
@ihor-sviziev thanks for investigation and detailed report! I changed priority to P2

**Comment by Morgy93** [comment]
Just came here to see that the issue is not resolved for over 3 years. 😔 

This happens for me sometimes on the frontend product page.
Magento 2.4.3 with redis-server 6.2.5

```
'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => '127.0.0.1',
            'port' => '6379',
            'password' => '',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '2',
            'compression_threshold' => '2048',
            'compression_library' => 'gzip',
            'log_level' => '4',
            'max_concurrency' => '6',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '0',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000',
            'sentinel_master' => '',
            'sentinel_servers' => '',
            'sentinel_connect_retries' => '5',
            'sentinel_verify_master' => '0'
        ]
    ],
```

```
Error:
Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in vendor/magento/framework/Session/SessionManager.php on line 204

Trace:
#1 session_start() called at [vendor/magento/framework/Session/SessionManager.php:204]
#2 Magento\Framework\Session\SessionManager->start() called at [generated/code/Magento/Customer/Model/Session/Interceptor.php:23]
#3 Magento\Customer\Model\Session\Interceptor->start() called at [vendor/magento/framework/Session/SessionManager.php:141]
#4 Magento\Framework\Session\SessionManager->__construct() called at [vendor/magento/module-customer/Model/Session.php:180]
#5 Magento\Customer\Model\Session->__construct() called at [generated/code/Magento/Customer/Model/Session/Interceptor.php:14]
#6 Magento\Customer\Model\Session\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#7 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#8 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#9 Magento\Framework\ObjectManager\ObjectManager->create() called at [generated/code/Magento/Customer/Model/SessionFactory.php:43]
#10 Magento\Customer\Model\SessionFactory->create() called at [vendor/amasty/mostviewed/Model/Customer/GroupValidator.php:36]
#11 Amasty\Mostviewed\Model\Customer\GroupValidator->validate() called at [vendor/amasty/mostviewed/Model/Repository/GroupRepository.php:192]
#12 Amasty\Mostviewed\Model\Repository\GroupRepository->validateGroup() called at [vendor/amasty/mostviewed/Model/Repository/GroupRepository.php:136]
#13 Amasty\Mostviewed\Model\Repository\GroupRepository->getGroupByIdAndPosition() called at [vendor/amasty/mostviewed/Model/ProductProvider.php:167]
#14 Amasty\Mostviewed\Model\ProductProvider->modifyCollection() called at [vendor/amasty/mostviewed/Plugin/Community/AbstractProduct.php:74]
#15 Amasty\Mostviewed\Plugin\Community\AbstractProduct->prepareCollection() called at [vendor/amasty/mostviewed/Plugin/Community/Related.php:24]
#16 Amasty\Mostviewed\Plugin\Community\Related->afterGetItems() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#17 Magento\Catalog\Block\Product\ProductList\Related\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#18 Magento\Catalog\Block\Product\ProductList\Related\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Block/Product/ProductList/Related/Interceptor.php:23]
#19 Magento\Catalog\Block\Product\ProductList\Related\Interceptor->getItems() called at [vendor/magento/module-catalog/Block/Product/ProductList/Related.php:147]
#20 Magento\Catalog\Block\Product\ProductList\Related->getIdentities() called at [vendor/magento/module-page-cache/Model/Layout/LayoutPlugin.php:96]
#21 Magento\PageCache\Model\Layout\LayoutPlugin->afterGetOutput() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#22 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#23 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:41]
#24 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#25 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#26 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magezon/module-core/Plugin/View/Result/Layout.php:24]
#29 Magezon\Core\Plugin\View\Result\Layout->aroundRenderResult() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#30 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#31 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:23]
#32 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#33 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#34 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
```

Any help?

**Comment by oneserv-heuser** [comment]
Having the same issue after adding several user roles (acl). Now the adminhtml is insane slow and sometimes this error occurs and a error page is shown. We're using 2.4.3-p1.
If I delete the user roles, everything is fine again. We're also using redis.

**Comment by oneserv-heuser** [comment]
Related to [#3374](https://github.com/magento/magento2/issues/33748)

**Comment by pkarsai** [comment]
After reading through this thread multiple times and looking into the relevant Magento code, I think that the following is going on:
- Magento can fall back to file based session handling, when Redis is not available at all (see `\Magento\Framework\Session\SaveHandler::callSafely`), but cannot handle the situation when the session is already created in Redis, but it can't be read from, due to a concurrency issue. Looking at `\Magento\Framework\Session\SaveHandler\Redis::read`, we can see that on `ConcurrentConnectionsExceededException` Magento immediately redirects to a 503 page. It doesn't even try to fall back to the file based session handling.
- The error that we get (`Warning: session_start(): Failed to read session data: user`) is not related to permission issues. When configuring Magento save the sessions to `files`, instead of `redis`, it can perfectly read and write from/to the same location.

Considering all this, I ended up subclassing `\Magento\Framework\Session\SaveHandler\Redis`, and I added some logic to retry the read on `ConcurrentConnectionsExceededException`, with exponential backoff. This is what I came up with: https://gist.github.com/pkarsai/0dcc35294870c057b9be9803cba891b6. The tests look promising so far, but it's not yet in production. BTW, `max_concurrency` was set to 30 and were still having this problem, that's why I ended up implementing this custom solution.

**Comment by tuyennn** [comment]
@engcom-November Could we have update status of this ticket

**Comment by schmengler** [comment]
FWIW, it still happened here in a 2.4.3 installation which was not even live yet, so there was not much concurrent traffic. But at least increasing max_concurrency seemed to help

**Comment by Djohn12** [comment]
Still reproducing this on a 2.4.3-p3 instance using the default session redis config with a `'max_concurrency' => '6'`.

Is there anyone from magento team working on this ?

**Comment by plamenh** [comment]
2.4.2 here, can't fix it.

**Comment by adarshkhatri** [comment]
Happening in 2.4.6-p2 as well.
