### ISSUE TITLE
"- undefined" displayed in checkout summary when shipping method name is not set

### ISSUE THREAD

**Issue by krzksz** [magento/magento2#17492]
Sometimes it is the case that setting both `Carrier title` and `Method name` for a shipping method is redundant and having only the first one set it totally enough. Sadly, in the case of leaving `Method name` field blank there is a small visual bug displayed in checkout summary box.
### Preconditions

1. Magento 2.2.x, but any version may be affected
2. Shipping method with empty `Method Name` set.

### Steps to reproduce

1. Add new or edit any existing shipping methods with `Method name` field left as a blank field.
2. Add any product to the cart and go through the checkout to the last step.

### Expected result

1. Shipping method is displayed nicely.

### Actual result

1. There is a `- undefined` string displayed.
<img width="422" alt="obraz" src="https://user-images.githubusercontent.com/829189/43958973-6f77d4e2-9cad-11e8-9052-02a196898c52.png">

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@krzksz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by krzksz** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [Magento instance](https://i-17492-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17492-2-2-develop.engcom.dev.magento.com/admin](https://i-17492-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@krzksz , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your report. 
The issue has been fixed in magento/magento2#17526 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [c789fb2813a74d5333fbcddca7f92b0a0c245162](https://github.com/magento/magento2/commit/c789fb2813a74d5333fbcddca7f92b0a0c245162)
 - [7aecb1f3c73e9af00375deabdfdc2bc78186e735](https://github.com/magento/magento2/commit/7aecb1f3c73e9af00375deabdfdc2bc78186e735)

The fix will be available with the upcoming 2.2.7 release.

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your report. 
The issue has been fixed in magento/magento2#17697 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [667e276ffcb41927bb07648f5e0e01ad8a733e5e](https://github.com/magento/magento2/commit/667e276ffcb41927bb07648f5e0e01ad8a733e5e)
 - [d85dd69d40acdcc4934a9f0f2fc3ebbbb9f8eb40](https://github.com/magento/magento2/commit/d85dd69d40acdcc4934a9f0f2fc3ebbbb9f8eb40)
 - [cd7c2b197cfb9db5e7aa1de10dfa95528bd57ad3](https://github.com/magento/magento2/commit/cd7c2b197cfb9db5e7aa1de10dfa95528bd57ad3)

The fix will be available with the upcoming 2.3.0 release.

**Comment by orlangur** [comment]
This seems to be not fixed completely according to new linked PR.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17845`, `MC-17846` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @krzksz. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.2.10` release.

**Comment by magento-engcom-team** [comment]
Hi @krzksz. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.
