### ISSUE TITLE
Cart Total is NaN in some circumstances

### ISSUE THREAD

**Issue by rauberdaniel** [magento/magento2#18027]
### Preconditions

1.  Magento 2.2.5
2. PHP 7.1
3. MySQL 5.6.27

### Steps to reproduce

1. Put two items in the cart, in our case this is one product at 59,80€ incl. Tax and one product at 9,49€ incl. Tax, Shipping is free
2. Apply a coupon code (cart price rule) with 100% discount

Or in comment -> https://github.com/magento/magento2/issues/18027#issuecomment-439338846

### Expected result

1. Cart Total should be `0,00 €`

### Actual result

1. Cart Total is `NaN,N €`

This issue might be a parsing issue in the frontend or a rounding issue in the backend, as the `/rest/default/V1/guests-cart/…/totals-information` returns a JSON response including `"grand_total":1.4210854715202e-14` (which is basically 0). Either the Frontend has an issue parsing this value or the backend shouldn’t even return a value that hasn’t been rounded. In some cases this value can even be negative and would result in `-NaN,N €`.

**Comment by magento-engcom-team** [comment]
Hi @rauberdaniel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rauberdaniel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rauberdaniel** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @rauberdaniel. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @rauberdaniel, here is your [Magento instance](https://i-18027-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18027-2-2-5.engcom.dev.magento.com/admin](https://i-18027-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @rauberdaniel I'm not able to reproduce following steps your described.
![selection_077](https://user-images.githubusercontent.com/40756439/45423622-9540b780-b69c-11e8-83b6-6babbabbb6a4.png)

**Comment by rauberdaniel** [comment]
This only appears in conditions where floating point calculations are not accurate. I assume it has to do with taxes (7% in my case).

I tried reproducing in the magento instance you offered me, but that instance does not update its index automatically (I assume no cronjob running) and therefore does not allow to create any products (refresh index on save doesn’t seem to work either and manual reindex is only possible using command line).

**Comment by ghost** [comment]
@rauberdaniel  I try several times but same result, tax 7% and do reindex, cron run cache clean, but not have an NaN
![selection_078](https://user-images.githubusercontent.com/40756439/45425804-169b4880-b6a3-11e8-9fea-7521f6295e05.png)

**Comment by ghost** [comment]
@rauberdaniel And rest api result Any update ?
![selection_079](https://user-images.githubusercontent.com/40756439/45427675-13ef2200-b6a8-11e8-87b2-7b6621ec46bf.png)

**Comment by rauberdaniel** [comment]
Guess I need to set up a vanilla Magento 2.2.5 instance to reproduce this, as the one offered above is not working correctly. However, I don’t currently have time for that. Might also have to do something with tax and discount calculation (post or pre tax). Will let you know as soon as I had time for it. Thank you!

**Comment by ghost** [comment]
@rauberdaniel ok somehow i'm get this result but not in grand total
![selection_080](https://user-images.githubusercontent.com/40756439/45428610-41d56600-b6aa-11e8-8a13-6768e31e9941.png)

**Comment by ghost** [comment]
@rauberdaniel yes finally i'm reproduce this :)
![selection_081](https://user-images.githubusercontent.com/40756439/45429052-2dde3400-b6ab-11e8-8df3-d32c8d714b94.png)

**Comment by rauberdaniel** [comment]
Great to hear, thank you very much for the help! This is a critical issue for us, as it prevents going past the payment method step in checkout, as no payment methods are available for a `NaN` price.

**Comment by ghost** [comment]
@rauberdaniel, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jayankaghosh** [comment]
What can I do to reproduce this issue? I have tried as the OP mentioned and got 0.00 as the total

**Comment by jayankaghosh** [comment]
Ok nevermind. I reproduced it. Seems to be a floating point precision error. We could round the floating point number to 2 digits, since that's the max precision Magento uses to display prices

**Comment by jayankaghosh** [comment]
I am working on this

**Comment by ghost** [comment]
**Steps to reproduce:**

- **Create two simple products:**
--  Name="simple1", Price=55.89 
--  Name="simple2", Price=8.87
- **Configure Shipping Methods:**
-- Flat Rate -> Enabled=No
-- Free Shipping - > Enabled=Yes
- **Configure Tax:**
-- Calculation Settings:
-- Catalog Prices=Including Tax
-- Apply Discount On Prices=Including Tax
-- Shopping Cart Display Settings:
-- Display Prices=Including Tax
-- Create Tax Rate:
-- Tax Identifier=test
-- Zip/Post Code=*
-- State=*
-- Country=United States
-- Rate Percent=7
-- Create Tax Rule:
-- Name=test rule
-- Tax Rate=test
- **Create Cart Price Rules:**
-- Rule Name=test
-- Websites=Main Website
-- Customer Groups=NOT LOGGED IN,General,Wholesale,Retailer
-- Coupon=Specific Coupon
-- Coupon Code=test
-- Apply=Percent of product price discount
-- Discount Amount=100
- **Go to Stores->Configuration->General->Currency Setup**
-- Add Euro to Allowed Currencies
- **Go to Stores->Currency Rates**
-- Choose Import Service=Currency Converter API and click Import button
- **Go to storefront and choose EUR-Euro currency**
-- Add two simple products to cart
- **Go to View and Edit Cart**
-- Apply discount code "test"

 **Expected result:**
Order Total = €0.00

 **Actual result:**
Order Total = €NaN.N

**Comment by magento-engcom-team** [comment]
Hi @rauberdaniel. Thank you for your report. 
The issue has been fixed in magento/magento2#20638 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [3ecdb4f7855d9b08fa1b616d76de6b047869bed9](https://github.com/magento/magento2/commit/3ecdb4f7855d9b08fa1b616d76de6b047869bed9)
 - [c26719dba5acd817ddb667e46fd422b8845eeaf0](https://github.com/magento/magento2/commit/c26719dba5acd817ddb667e46fd422b8845eeaf0)
 - [63cc54b542e5c17cb5519c399e6ce972c55540f6](https://github.com/magento/magento2/commit/63cc54b542e5c17cb5519c399e6ce972c55540f6)
 - [785a38a936acd94618e3d49f951be3f6b2b1d682](https://github.com/magento/magento2/commit/785a38a936acd94618e3d49f951be3f6b2b1d682)
 - [b6f9b6e92a9958e235aa239057b2b6b51fb2f14a](https://github.com/magento/magento2/commit/b6f9b6e92a9958e235aa239057b2b6b51fb2f14a)
 - [6c9a97c67ea89bb3585135d206321618cbc99586](https://github.com/magento/magento2/commit/6c9a97c67ea89bb3585135d206321618cbc99586)
 - [422ab6774ddd50f9bc9d424f8ba218866c162b64](https://github.com/magento/magento2/commit/422ab6774ddd50f9bc9d424f8ba218866c162b64)
 - [8aa89dd3e3814eb086d271e026cd84994b57549d](https://github.com/magento/magento2/commit/8aa89dd3e3814eb086d271e026cd84994b57549d)

The fix will be available with the upcoming 2.2.8 release.

**Comment by AndyJAllen** [comment]
Still experiencing this on 2.3.3; despite the existence of this line in Total.php:
`$amount = is_float($amount) ? round($amount, 4) : $amount;`

**Comment by krzysztofkuzniar** [comment]
@AndyJAllen I confirm, in 2.3.3 still display **NaN** value

**Comment by engcom-Delta** [comment]
HI @krzysztofkuzniar . I am not able to reproduce issue by steps from [comment](
https://github.com/magento/magento2/issues/18027#issuecomment-439338846) on 2.4-develop.
![#18027issue](https://user-images.githubusercontent.com/51681379/80582105-d83cd380-8a16-11ea-916e-86105b8a5f5f.png)

Are you facing with this issue on branch 2.4-develop?

**Comment by engcom-Delta** [comment]
@krzysztofkuzniar,  we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
