### ISSUE TITLE
Rounding problem on prices when adding tax to display prices

### ISSUE THREAD

**Issue by mlindholm** [magento/magento2#18025]
### Preconditions

1. Magento 2.2.x, 2.3.x & 2.4-develop
2. PHP 7.1.9 & 7.2
3. MySql 5.6.37

### Steps to reproduce
1.  Set _Configuration > Tax > Calculation Settings_ to following:
![tax_calculation_settings](https://user-images.githubusercontent.com/5977769/45406384-682dde00-b677-11e8-85ec-e1400d2bc6ec.png)
2. Set  _Configuration > Tax > Price Display Settings_ to _Including Tax_

### Expected result

1. Tax should be added to price set in product data when getting amount from classes extending Magento\Framework\Pricing\Price\AbstractPrice. Example Affirm Water Bottle with price of 7.00 with tax of 25 percent should result final value of 8.75

### Actual result

1. Magento\Framework\Pricing\Price\AbstractPrice returns value of 8.750001. This is visible example data-price-amount se to price wrapper element. See screenshot.
![image](https://user-images.githubusercontent.com/5977769/45406745-80522d00-b678-11e8-842b-123a9c1e1484.png)

### Own findings

Problem seems to stem from Magento\Tax\Model\Calculation\AbstractCalculator. Calculator is adding delta of 0.000001 in deltaRound to prices, even if the $round is set to false and no rounding is happening. 

```php
    /**
     * Round price based on previous rounding operation delta
     *
     * @param float $price
     * @param string $rate
     * @param bool $direction
     * @param string $type
     * @param bool $round
     * @return float
     */
    protected function deltaRound($price, $rate, $direction, $type = self::KEY_REGULAR_DELTA_ROUNDING, $round = true)
    {
        if ($price) {
            $rate = (string)$rate;
            $type = $type . $direction;
            // initialize the delta to a small number to avoid non-deterministic behavior with rounding of 0.5
            $delta = isset($this->roundingDeltas[$type][$rate]) ?
                $this->roundingDeltas[$type][$rate] :
                0.000001;
            $price += $delta;
            $roundPrice = $price;
            if ($round) {
                $roundPrice = $this->calculationTool->round($roundPrice);
            }
            $this->roundingDeltas[$type][$rate] = $price - $roundPrice;
            $price = $roundPrice;
        }
        return $price;
    }
```

**Comment by magento-engcom-team** [comment]
Hi @Tuuhea. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Tuuhea do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Tuuhea, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30105` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by oneserv-heuser** [comment]
Hold up, just because no one works on it it'll get closed? It's an bug which needs to be fixed!

**Comment by DJB95** [comment]
Does anyone have an update on this? Is this maybe fixed in M2.4.x?

**Comment by oneserv-heuser** [comment]
I can confirm that the error still exists in 2.4.1, so not yet fixed.

**Comment by DJB95** [comment]
@oneserv-heuser alright, thanks Timon! hopefully this will be fixed soon

**Comment by rupertbyers-ec** [comment]
Any update on this yet? Please, Magento devs, please provide us with a hack until thsi is resolved properly!

**Comment by oneserv-heuser** [comment]
Still an issue which needs to be fixed.

**Comment by rb-ec** [comment]
definitely still an issue that needs fixing. @engcom-Charlie  magento-engcom-team

**Comment by oneserv-heuser** [comment]
And again, still an issue which needs to be fixed.

**Comment by rb-ec** [comment]
Yes, still an issue.

**Comment by vivekp-dev** [comment]
I am facing the same issue in Magento

**Comment by mcspronko** [comment]
Any chance to fix the issue that was reported back in 2018?

**Comment by holzkern** [comment]
Still an issue in 2023

**Comment by othuress** [comment]
Still an issue especially when TAX reported for OSS https://vat-one-stop-shop.ec.europa.eu/one-stop-shop_en creates deviations in reporting and what needs to actually needs to be paid. This issue needs attention and solution ASAP. reported in 2018 embarrassing this has not yet been fixed.

**Comment by Seppo-Konttinen-Solteq** [comment]
Yeap still an issue.

**Comment by othuress** [comment]
Hi @magento-engcom-team can you please pick up in this issue, it has been neglected for too long.

**Comment by s0ko7likaj** [comment]
🤣

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Tuuhea,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


<img width="1440" alt="Screenshot 2024-04-02 at 15 22 48" src="https://github.com/magento/magento2/assets/51680745/ae26c15b-eeb4-4a39-bd1b-60d4756dddcb">

Magento\Framework\Pricing\Price\AbstractPrice returns value of 8.750001.

Hence Confirming the issue.

Thanks.
