### ISSUE TITLE
Magento 2.2.6 coupon codes don't work anymore

### ISSUE THREAD

**Issue by Cristiano81** [magento/magento2#18183]
### Preconditions

1. Magento 2.2.6
2. Cart price rule based on coupon code

### Steps to reproduce

1. Create a cart price rule with specific coupon with date from 2018 to 2088
2. Try add the coupon to the cart

### Expected result

1. The coupon has been successfull applied to the cart

### Actual result

1. Every coupon code result invalid

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Cristiano81 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Cristiano81** [comment]
In 2.2.5 the coupon code work

**Comment by Cristiano81** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81, here is your [Magento instance](https://i-18183-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18183-2-2-6.engcom.dev.magento.com/admin](https://i-18183-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Cristiano81** [comment]
yes i can reproduce the issue on vanilla magento

**Comment by Cristiano81** [comment]
This maybe be usefull, when i try to apply the coupon code, i received this error on chrome console:
jquery.js:10254 PUT https://i-18183-2-2-6.engcom.dev.magento.com/rest/default/V1/guest-carts/BWM5XQCXhnzdxK9njKSP2cL611NFTmcG/coupons/TEST2018 404 (Not Found)
send @ jquery.js:10254
ajax @ jquery.js:9738
put @ storage.js:62
(anonymous) @ set-coupon-code.js:33
apply @ discount.js:41
(anonymous) @ knockout.js:3863
dispatch @ jquery.js:5226
elemData.handle @ jquery.js:4878

**Comment by kunj1988** [comment]
@Cristiano81, I have tried with vanilla Magento 2.2.6 and it is working for me, Please provide more details.

**Comment by Cristiano81** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81, here is your [Magento instance](https://i-18183-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18183-2-2-6.engcom.dev.magento.com/admin](https://i-18183-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Cristiano81** [comment]
@kunj1988 thank you,
i just created a test product with price 100$
![image](https://user-images.githubusercontent.com/31507804/45917555-1278e300-be7a-11e8-9588-e82938073453.png)

after that i created a new coupon with this attribute:

![image](https://user-images.githubusercontent.com/31507804/45917585-9c28b080-be7a-11e8-9c97-5c5bce1e9c28.png)
![image](https://user-images.githubusercontent.com/31507804/45917592-a8147280-be7a-11e8-936c-24adc1a6e5b1.png)
![image](https://user-images.githubusercontent.com/31507804/45917598-b82c5200-be7a-11e8-8d06-67a38af6a716.png)

after i add the test product in cart and try to apply the coupon discount, this is the result:
![image](https://user-images.githubusercontent.com/31507804/45917622-ff1a4780-be7a-11e8-9e12-9c1e361a7565.png)

maybe you can tell me your coupon configuration if it works

**Comment by hostep** [comment]
@Cristiano81 : the coupon codes in your screenshot don't match: `TEST20118` vs `TEST2018`, please make sure they are the same ;)

**Comment by Cristiano81** [comment]
ops you are right :P but even if they are the same it doesn't work,
please try on the active vanilla magento

**Comment by hostep** [comment]
Ok, I was able to reproduce, and also found out why.

It has to do with the "to date". In your example, you put it in the year 2088.
When I first tested, I just used 2018 and it worked perfectly fine.

After some playing around, it looks like the limit is 20 years, the year 2037 works, but the year 2038 no longer works.

So this is pretty strange.
You say it worked before on Magento 2.2.5? Also with the year 2088?
If yes: then you've found a new bug, but the fix is pretty easy. But I still consider it a bug if it worked in Magento 2.2.5, because this is kind of unexpected.

**Comment by hostep** [comment]
Hmm, just tested on Magento 2.2.5, it has the exact same problem, so it's not a new bug in 2.2.6. But it's certainly a problem.

**Comment by Cristiano81** [comment]
Thank you for your support!
I can tell y the same, in 2.2.5 it didn't work with 2088, BUT it worked with blank "to date" , it does not in 2.2.6 .
I'm going to set an early "to date" thank y again

**Comment by hostep** [comment]
Hmm, I can not confirm the problem with the blank "to date".
See the test instance, I've added a new coupon with code `TEST2020` with a blank "to date". And it works, maybe double check if I've missed something?


<img width="768" alt="coupon-settings" src="https://user-images.githubusercontent.com/85479/45918419-09dad980-be87-11e8-9aa2-58a601923dcd.png">

<img width="602" alt="coupon-results" src="https://user-images.githubusercontent.com/85479/45918426-165f3200-be87-11e8-9813-d4b72ffe5eef.png">

**Comment by kunj1988** [comment]
@Cristiano81, yes, I got the same error while adding Date with **09/30/2088** in `To` field otherwise working fine. It works with max 20 years difference between `From` and `To` field.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @hostep so this is bug ? or we can just leave field empty?

**Comment by kunj1988** [comment]
In my case, While we add `To` date more than 20 years Magento adding `0000-00-00 00:00:00` value in `expiration_date` field. 
![select salesrule_coupon adminer](https://user-images.githubusercontent.com/13017040/45939746-86d69200-bff2-11e8-8695-e347908e3d51.png)

**Comment by hostep** [comment]
@engcom-backlog-nazar: the fact that the 20 year problem exist is a bug, but it seems to have already existed since Magento 2.2.0 at least (haven't tested further back).

I'm still curious about the exact problem of @Cristiano81 where it worked on 2.2.5 but no longer on 2.2.6, that part hasn't been discovered yet I believe.

**Comment by Cristiano81** [comment]
@hostep the fact is very curious.
I opened this issue because we had a Magento 2.2.2 with a coupon with these settings:
![image](https://user-images.githubusercontent.com/31507804/45940576-2e939600-bfda-11e8-9311-63716f171516.png)
![image](https://user-images.githubusercontent.com/31507804/45940589-394e2b00-bfda-11e8-9428-a8870d8c2e02.png)
![image](https://user-images.githubusercontent.com/31507804/45940596-45d28380-bfda-11e8-8abc-76fbdc09ce8c.png)

After upgrade from 2.2.2 to 2.2.5 and after to 2.2.6 this coupon stopped work.
But on our test enviroment where there is the 2.2.5 version of Magento the same coupon works perfectly.
On saturday after some try with the date it starts work also on 2.2.6 ...

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95197`, `MAGETWO-95198` were created

**Comment by ghost** [comment]
@Cristiano81 maybe edit steps to reproduce, add the step of specific date

**Comment by kunj1988** [comment]
@hostep, I got the same issue with Magento 2.2.5, I think the issue with MySQL database. It doesn't allow to add date more than 20 years.

**Comment by BezV8** [comment]
20 years from now is the end of Unix time for 32-bit fields, so that is likely the cause of the problem. Magento would have to move to using 64-bit date fields?

**Comment by ghost** [comment]
Hi @hostep Hi  @BezV8 It looks like this is Mysql bug. -> https://bugs.mysql.com/bug.php?id=12654

**Comment by hostep** [comment]
@BezV8 & @engcom-backlog-nazar: nice find!

Since that bug was reported in 2005 and hasn't been fixed in 2018, I don't think we should wait on that, maybe Magento (or somebody else) can find a workaround for this?

**Comment by kaalar** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @kaalar. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @kaalar, here is your [Magento instance](https://i-18183-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18183-2-2-6.engcom.dev.magento.com/admin](https://i-18183-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by saphaljha** [comment]
Hello @kaalar , Are you working on this issue? Else I'll review and take this issue, Please advise.

**Comment by kaalar** [comment]
Hello Saphal i working, but i dont to replicate in my local.

**Comment by ravi-chandra3197** [comment]
Hello @Cristiano81 
I have a re-produce issue in my local
- Create a cart price rule with the specific coupon with a date from 2018 to 2088

After I have checked in database "salesrule_coupon" table and I have found expiration_date is 0000-00-00 00:00:00 because MySQL does not allow date greater or equal then 2038, if we have entered 2037 it's valid but 2038 invalidate, so it's actually a MySQL error. Magento passes correct data (to date) to backend but when data insert into MySQL table it's changing to 0000-00-00 00:00:00 if the year is greater or equal then 2038.

Mysql issue:: WL#1872: Add support for dates from 2038 till 2116 as values of TIMESTAMP type
[https://dev.mysql.com/worklog/task/?id=1872](https://dev.mysql.com/worklog/task/?id=1872)

salesrule_coupon table in database
![mysql_date_bug](https://user-images.githubusercontent.com/43946827/47080686-4ac7d300-d226-11e8-95db-5756e43cdc20.png)


mysql allow if date lessthen 2038. like I have enter 2037 it's valid

![valida_date_if_lessthen_2038](https://user-images.githubusercontent.com/43946827/47080543-e3118800-d225-11e8-8cbb-3376bfeab3e2.png)

mysql not allow if date greater then 2038. like I have use 2038 it's invalid

![mysql_give_error_if_daet_greate_then_2038](https://user-images.githubusercontent.com/43946827/47080629-2966e700-d226-11e8-981e-f5052d4e4660.png)

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18183-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18183-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18183-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Shubham0492** [comment]
I am able to reproduce this error in vanila magento.
![screencapture-ec2-34-228-235-121-compute-1-amazonaws-i-18183-2-2-develop-admin-sales_rule-promo_quote-edit-id-1-2018-10-31-00_56_31](https://user-images.githubusercontent.com/35595582/47744754-20efc100-dca8-11e8-9bf7-09c68d9e0029.png)
![screencapture-ec2-34-228-235-121-compute-1-amazonaws-i-18183-2-2-develop-checkout-cart-2018-10-31-00_57_01](https://user-images.githubusercontent.com/35595582/47744810-42e94380-dca8-11e8-83db-6f65f3ae3292.png)

**Comment by konarshankar07** [comment]
As expiration_date is a TIMESTAMP so it will have range from '1970-01-01 00:00:01.000000' to '2038-01-19 03:14:07.999999'. So it won't save for the 2088 year but if you still want to save so we need to change the column from TIMESTAMP to DATETIME. Hope this will help you.

**Comment by giacmir** [comment]
Today I encountered this same issue in a 2.1.9 instance.

**Comment by vdBrandtMedia** [comment]
I have encountered the same issue on 2.2.5, checked the date_to value in the salesrule table but it gives a correct value of 2019-11-26

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by scottsb** [comment]
I agree with @konarshankar07 that the best/correct solution here is to change the expiration column type to a DATETIME instead of TIMESTAMP.

**Comment by magento-engcom-team** [comment]
Hi @henryktews. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by thomas-avada** [comment]
My client encountered this issue for one time. As far as I can tell, it is because the server configuration does not allow PUT, PATCH and DELETE request. You should contact your server guy on this and try my approach to enable all of the above request verbs.

**Comment by this-adarsh** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@this-adarsh thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by this-adarsh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @this-adarsh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @this-adarsh, here is your [Magento instance](https://i-18183-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-18183-2-3-develop.instances.magento-community.engineering/admin](https://i-18183-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81. Thank you for your report. 
The issue has been fixed in magento/magento2#22718 by @this-adarsh in 2.3-develop branch
Related commit(s):
 - [e965f0ca8676b6e71e155843da8ebef1c65ae7da](https://github.com/magento/magento2/commit/e965f0ca8676b6e71e155843da8ebef1c65ae7da)

The fix will be available with the upcoming 2.3.3 release.

**Comment by ashvinim0003** [comment]
The issue still exists in Magento 2.3.2.tried to fix it using by change timestamp to datetime in db_schema.xml file 

```
<column xsi:type="timestamp" name="expiration_date" on_update="false" nullable="true"
                comment="Expiration Date"/>
        <column xsi:type="smallint" name="is_primary" padding="5" unsigned="true" nullable="true" identity="false"
                comment="Is Primary"/>
        <column xsi:type="timestamp" name="created_at" on_update="false" nullable="true"
                comment="Coupon Code Creation Date"/>
```

But still not fixed.

**Comment by SrinivasChukka** [comment]
Really appreciate and thanks for sharing i use shopwale. shopwale has some of the best deals and coupons there’s no wait you get the code right away unlike many other sites. shopwale codes have always worked for you so far and you have been using it for a while now. You can find more offers of <a href="https://www.shopwale.com/freecharge-coupons/">Freecharge Coupons</a> here.
[https://www.shopwale.com](url)
