### ISSUE TITLE
Reset password throws error since 2.2.6

### ISSUE THREAD

**Issue by edwinbos** [magento/magento2#18256]
### Preconditions
Magento 2.2.6 (clean installation)

### Steps to reproduce
1. Clicked on "Reset password" on the login page
2. Entered e-mailadres and submitted form
3. Clicked on link in the password reset mail
4. Entered password two times and submit form by clicking "reset password"

### Expected result
1. Password is changed and the user can login with the new password

### Actual result
1. Error occurred "something went wrong while saving the new password".

![schermafbeelding 2018-09-26 om 11 53 58](https://user-images.githubusercontent.com/1267356/46072939-ed3eea00-c183-11e8-9939-c48617ff6725.png)

**Comment by magento-engcom-team** [comment]
Hi @edwinbos. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@edwinbos do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @edwinbos I'm not able to reproduce following steps you described. see attachments
![46073905-d5209800-c18e-11e8-88d1-25869a3e2bde](https://user-images.githubusercontent.com/40756439/46275595-31f0c980-c566-11e8-847a-826003c3d5dd.png)

**Comment by edwinbos** [comment]
You have forgotten step 3 and step 4:
3. Clicked on link in the password reset mail
4. Entered password two times and submit form by clicking "reset password"

**Comment by ghost** [comment]
@edwinbos Can you confirm it on vanilla instance ?
![selection_140](https://user-images.githubusercontent.com/40756439/46075783-3eef7080-c194-11e8-9610-99a5a5d1d32d.png)

**Comment by edwinbos** [comment]
I can confirm it's a vanilla Magento 2.2.6 instance.
Also with two real shops (on a test environment) the same problem.

@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @edwinbos. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @edwinbos, here is your [Magento instance](https://i-18256-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18256-2-2-6.engcom.dev.magento.com/admin](https://i-18256-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@edwinbos So can  you reproduce this on vanilla instance ?

**Comment by julian-van-drielen** [comment]
@engcom-backlog-nazar I was able to reproduce this issue on a clean Magento 2.2.6 instance.
![image](https://user-images.githubusercontent.com/35022803/46080200-2e89c680-c191-11e8-888c-9978ed09e853.png)

**Comment by ghost** [comment]
@edwinbos But why i'm able to reset password on this instance ?
![selection_142](https://user-images.githubusercontent.com/40756439/46080565-f25f6180-c1a2-11e8-991b-cd5eefaac8b2.png)

**Comment by edwinbos** [comment]
Found it. It doesn't work on PHP7.0.30 on my local instance, but it's working on PHP7.1.
Which version of PHP is this instance using?

**Comment by ghost** [comment]
@edwinbos Supported version 7.1 7.0 only for 2.1-*

**Comment by edwinbos** [comment]
Does that mean the DevDocs is not up-to-date?

![schermafbeelding 2018-09-26 om 14 52 03](https://user-images.githubusercontent.com/1267356/46081082-e3c17c00-c19b-11e8-8ad2-ca2d6b7b0f65.png)

https://devdocs.magento.com/guides/v2.2/install-gde/prereq/prereq-overview.html

![schermafbeelding 2018-09-26 om 14 54 40](https://user-images.githubusercontent.com/1267356/46081184-2d11cb80-c19c-11e8-8c0b-b88b2b93dd84.png)

https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

**Comment by ghost** [comment]
@edwinbos I'm tested with php 7.0 and have no issue passwords reset correctly, maybe some problem in you environment ?

**Comment by hostep** [comment]
Can reproduce on a clean Magento 2.2.6 installed using composer.
Error happens both in PHP 7.0.32 as 7.1.22, I don't think the PHP version matters here.

The exception message which happens is: `Warning: SessionHandler::destroy(): Session is not active in vendor/magento/framework/Session/SaveHandler.php on line 116`

Stacktrace:
```
Magento\Customer\Controller\Account\ResetPasswordPost\Interceptor->execute (vendor/magento/module-customer/Controller/Account/ResetPasswordPost.php:103)
Magento\Customer\Controller\Account\ResetPasswordPost\Interceptor->execute (generated/code/Magento/Customer/Controller/Account/ResetPasswordPost/Interceptor.php:24)
Magento\Customer\Controller\Account\ResetPasswordPost\Interceptor->dispatch (vendor/magento/framework/App/Action/Action.php:107)
Magento\Customer\Controller\Account\ResetPasswordPost\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Customer\Controller\Account\ResetPasswordPost\Interceptor->Magento\Framework\Interception\{closure} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Customer\Controller\Account\ResetPasswordPost\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Customer\Controller\Account\ResetPasswordPost\Interceptor->dispatch (generated/code/Magento/Customer/Controller/Account/ResetPasswordPost/Interceptor.php:39)
Magento\Framework\App\FrontController\Interceptor->dispatch (vendor/magento/framework/App/FrontController.php:55)
Magento\Framework\App\FrontController\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch (vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure} (vendor/magento/framework/Interception/Interceptor.php:135)
Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch (vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure} (vendor/magento/framework/Interception/Interceptor.php:135)
Magento\Framework\App\FrontController\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Framework\App\FrontController\Interceptor->dispatch (generated/code/Magento/Framework/App/FrontController/Interceptor.php:26)
Magento\Framework\App\Http\Interceptor->launch (vendor/magento/framework/App/Http.php:135)
Magento\Framework\App\Http\Interceptor->launch (generated/code/Magento/Framework/App/Http/Interceptor.php:24)
Magento\Framework\App\Bootstrap->run (vendor/magento/framework/App/Bootstrap.php:257)
{main} (pub/index.php:37)
```

Exact steps to reproduce:
1. Setup clean Magento 2.2.6 installation
2. Create a new account in the frontend
3. Logout
4. Go to the password reset page
5. Enter your email address and the captcha
6. Click on the link you've received
7. Enter a new password in the two fields
8. Getting error `Something went wrong while saving the new password.`

**Comment by ghost** [comment]
Hi @hostep Thank you for your explanation now i'm able to reproduce on composer version, but on 2.2-dev this works perfectly.

**Comment by hostep** [comment]
@engcom-backlog-nazar: ok, great!
Please in the future, always try to test with composer based installs, it's how the real world uses Magento, we don't clone from a git repo (well most of us, some actually do it like that).

I really hope this won't turn out to be caused by one of the CBE's again, because otherwise this is getting quite ridiculous...

**Comment by ghost** [comment]
@hostep, Ok thanks that be my mistake to not use composer version.

**Comment by salikahmed** [comment]
@engcom-backlog-nazar I have the same issue found on composer version cloud instance 2.2.6, I have submitted the internal ticket with the issue I found the issue missing customer id lines of code in the Controller "ResetPasswordPost.php" which may cause the issue, I fixed the temp solution override the core .

**Comment by ghost** [comment]
@hostep I'm disabled Amazon module, and have success result.

**Comment by hostep** [comment]
@engcom-backlog-nazar: I cannot confirm this, disabling all Amazon modules still triggers the problem over here.
As a next test, I've disabled all CBE's: Amazon_Core, Klarna_Core, Amazon_Login, Amazon_Payment, Klarna_Ordermanagement, Klarna_Kp, Dotdigitalgroup_Email, Temando_Shipping, Vertex_Tax.
But still the error can be reproduced, so it looks like the CBE's have nothing to do with this for once.

@salikahmed: can you share your solution? Or maybe even better, create a pull request with the fix if you believe it is correct? Thanks!

**Comment by hostep** [comment]
Some extra useful information from @webspeaks from https://github.com/magento/magento2/issues/18297:
> This issue seems to occur only for new users who register after upgrading to 2.2.6.

(not verified if this is true)

**Comment by webspeaks** [comment]
A temporary fix is to modify the `vendor\magento\module-customer\Model\AccountManagement.php`.
Go to function `resetPassword()` and 
 Replace following lines (around line # 673):
```
        $this->sessionManager->destroy();
        $this->destroyCustomerSessions($customer->getId());
```
with following lines

```
        try {
            $this->sessionManager->destroy();
            $this->destroyCustomerSessions($customer->getId());
        } catch (\Exception $e) {}

```
### Note: We have modified core file which is not recommended. But its a temporary fix and not a permanent solution.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95341`, `MAGETWO-95342` were created

**Comment by timbaker1991** [comment]
We are having the same issue, is there an ETA to when a fix may be ready?

On a side note, is this not something that is unit-tested on release? Feels like fairly basic testing has been missed to not notice a password can not be reset.

**Comment by paco44** [comment]
#Mm18mx

**Comment by magento-engcom-team** [comment]
@paco44 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @paco44. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by paco44** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @paco44. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @paco44, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18256-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18256-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18256-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nahidacm** [comment]
Updating PHP version from 7.0 to 7.1 fixed the issue for me.

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sidolov** [comment]
Hi @edwinbos. Thank you for your report. 
The issue has been fixed in magento/magento2#19026 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [bc8d3d5d0ead9779cb22d19201cd731719a79b0c](https://github.com/magento/magento2/commit/bc8d3d5d0ead9779cb22d19201cd731719a79b0c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by nuwaus** [comment]
How can we override this class without modifying the core class?
I tried to override with di.xml but then I get an error while sending the reset email.

**Comment by tonycr7** [comment]
Hi @nuwaus,

I tried overriding the 'AccountManagement' Class and its working fine. Please make sure the private functions which are using 'resetPassword' function are also included in the extended class. In addtion to this if you are overriding the whole file then please make sure all class has namespace because in core  'AccountManagement' class excluded some class namespace which are in the same directory.

**Comment by nuwaus** [comment]
@tonycr7 

So far I managed to fix it by removing the **module-customer** module from composer and adding a clone of it with changes again via composer, eg: **module-customer-temp**

That way I managed to get it working, but I'll try as you mentioned and write the outcome here, soon..

**Comment by peterjaap** [comment]
@nuwaus @tonycr7 the recommended way is to make a composer patch file to use with for example https://github.com/cweagans/composer-patches

**Comment by josefbehr** [comment]
Seems to also be fixed in 2.2-develop already, but not in 2.2.7

**Comment by joris-ati4** [comment]
> Seems to also be fixed in 2.2-develop already, but not in 2.2.7

Yes I can see this has been fixed in the 2.2-develop branch on 05/11/2018 ( https://github.com/magento/magento2/commit/7443dc3194040e9ce2f7baf902470deb975b97c6 )but it wasn't included in 2.2.7. @magento-engcom-team will this fix be included in 2.2.8 ? 

Thank you !

**Comment by DanielRuf** [comment]
> included in 2.2.7. @magento-engcom-team will this fix be included in 2.2.8 ?

Yes as not all commits made it into the planned release (the bot who gives the info about the version is still not very accurate / correct).

**Comment by maartenwolfsen** [comment]
@peterjaap @nuwaus @tonycr7 I created a patch for the fix: https://gist.githubusercontent.com/maartenatmarissen/b8e41e15f8a0597cf510a84be56b65c5/raw/cdf2be8cfcdf6b08c884d7b751b1c21e5a7078d7/AccountManagement.php.patch

Can be applied using https://github.com/cweagans/composer-patches :
` "magento/module-customer": {`
     `"18256": "https://gist.githubusercontent.com/maartenwolfsen/b8e41e15f8a0597cf510a84be56b65c5/raw/cdf2be8cfcdf6b08c884d7b751b1c21e5a7078d7/AccountManagement.php.patch"`
`}`

**Comment by lewisje** [comment]
Apparently you changed your username, so the gist is now at https://gist.githubusercontent.com/maartenwolfsen/b8e41e15f8a0597cf510a84be56b65c5/raw/cdf2be8cfcdf6b08c884d7b751b1c21e5a7078d7/AccountManagement.php.patch with more information at https://gist.github.com/maartenwolfsen/b8e41e15f8a0597cf510a84be56b65c5/ and composer-patch code

    "magento/module-customer": {
        "18256": "https://gist.githubusercontent.com/maartenwolfsen/b8e41e15f8a0597cf510a84be56b65c5/raw/cdf2be8cfcdf6b08c884d7b751b1c21e5a7078d7/AccountManagement.php.patch"
    }

**Comment by peterjaap** [comment]
@lewisje might be better to use https://github.com/magento/magento2/commit/bc8d3d5d0ead9779cb22d19201cd731719a79b0c.patch (use patch level 5 when using https://github.com/vaimo/composer-patches);

```
{
  "patches": {
    "magento/module-customer": {
      "Reset password throws error since 2.2.6.": {
        "link": "https://github.com/magento/magento2/issues/18256",
        "source": "https://github.com/magento/magento2/commit/bc8d3d5d0ead9779cb22d19201cd731719a79b0c.patch",
        "level": 5,
        "depends": {
          "magento/product-community-edition": ">=2.2.6 <2.3.1"
        }
      }
    }
  }
}
```

**Comment by maartenwolfsen** [comment]
> Apparently you changed your username, so the gist is now at https://gist.githubusercontent.com/maartenwolfsen/b8e41e15f8a0597cf510a84be56b65c5/raw/cdf2be8cfcdf6b08c884d7b751b1c21e5a7078d7/AccountManagement.php.patch with more information at https://gist.github.com/maartenwolfsen/b8e41e15f8a0597cf510a84be56b65c5/ and composer-patch code
> 
> ```
> "magento/module-customer": {
>     "18256": "https://gist.githubusercontent.com/maartenwolfsen/b8e41e15f8a0597cf510a84be56b65c5/raw/cdf2be8cfcdf6b08c884d7b751b1c21e5a7078d7/AccountManagement.php.patch"
> }
> ```

Thank you for noticing, I´ve also changes the link
