### ISSUE TITLE
Unable to get product  attribute value for store-view scope type in product collection loaded for a specific store.

### ISSUE THREAD

**Issue by milindsingh** [magento/magento2#18374]
### Preconditions

1. Product has a user defined attribute with scope : store-view. Created via:
```
`/** @var \Magento\Eav\Setup\EavSetup $eavSetup */`
`
$eavSetup->addAttribute(
                    'catalog_product',
                   'ced_profile_id',
                    [
                        'group' => $groupName,
                        'note' => 'Profile Id',
                        'input' => 'text',
                        'type' => 'varchar',
                        'label' => 'Profile Id ',
                        'backend' => '',
                        'visible' => 1,
                        'required' => 0,
                        'sort_order' => 1,
                        'user_defined' => 1,
                        'comparable' => 0,
                        'visible_on_front' => 0,
                        'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_STORE,
                    ]
                );
`
 
```
2. Magento is setup with 2 store configuration. [Default Store & My Store] 
3. Attribute `ced_profile_id` has value **'blank'** in **All Store Views** ( i.e. for Admin store ID - 0), and value **'2'** for **Default Store** ( i.e. ID - 1).
4. On loading product collection with following code: 
`$storeId = 1; 
\** @var Magento\Catalog\Model\ResourceModel\Product\Collection $collection **\
$collection->setStoreId($storeId);
$collection->addAttributeToSelect(['ced_profile_id']);
$products = $collection->getData();
`
5. Environment:
 + Magento CE 2.2.5
 + PHP 7.09
 + MYSQL 5.7

### Steps to reproduce

1. Create a store-wise user-defined attribute.
2. Have blank value for admin store (i.e. all store views, ID - 0). and Have 'some value' for Default Store i.e. ID - 1.
3. Load Product collection by setting store id - 1, will get no values for default store - 1 for store -wise user defined attributes.

### Expected result

1.$products have **2**  attribute for 'ced_profile_id'.

### Actual result

1. $products have **null**  attribute for 'ced_profile_id'.
2. The Product collection final get SQL query search for *Null* value in admin store, while there is no row in admin store entity table for blank values. Add a row with null value for admin store and I  am able to get the default store values.
![2018-10-04-132110_1366x768_scrot](https://user-images.githubusercontent.com/13949703/46460084-7edbd680-c7d8-11e8-9310-fb6963f0cc7a.png)
In above image, entity_id 2,3,4 have **null** values for admin store - 0 and collection can get the default store values.
While entity_id 1 don't have a row in `catalog_product_entity_varchar`, hence I am not able to get values in product collection for store id 1 i.e. **Default Store** .

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@milindsingh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by milindsingh** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @milindsingh, here is your [Magento instance](https://i-18374-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18374-2-2-5.engcom.dev.magento.com/admin](https://i-18374-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by milindsingh** [comment]
In above Magento Instance (https://i-18374-2-2-5.engcom.dev.magento.com/),
I have created a custom attribute **`ced_profile_id`** with **Store-View** Scope and created a product with SKU: **Test Product**.
+ The Product SKU: **Test Product** has **`blank`** value in `All Store Views` and **`2`**. Screen Shot attached below.
![test product products inventory catalog magento admin](https://user-images.githubusercontent.com/13949703/46472784-ec4d2e80-c7fb-11e8-9502-981acf88b798.png)
+ The Catalog Product grid is added with 2 filters, store filter with value "Default Store View" and "Profile Id" (my created attribute) with value "2", but grid has no results which conflicts the first image. 
![products inventory catalog magento admin 1](https://user-images.githubusercontent.com/13949703/46473006-81e8be00-c7fc-11e8-9740-b98aa1368795.png)

**Comment by milindsingh** [comment]
@magento-engcom-team
> Hi @milindsingh. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @milindsingh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96206`, `MAGETWO-96207` were created

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your report. 
The issue has been fixed in magento/magento2#19911 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [3fad6a7006f6d995b45913b891854b838f590fc2](https://github.com/magento/magento2/commit/3fad6a7006f6d995b45913b891854b838f590fc2)
 - [e9e1db668d9bea210de4c5892aaec7539f35bd9e](https://github.com/magento/magento2/commit/e9e1db668d9bea210de4c5892aaec7539f35bd9e)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your report. 
The issue has been fixed in magento/magento2#20071 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [825fa30f043cdee014dcb6602eed50616a2f601c](https://github.com/magento/magento2/commit/825fa30f043cdee014dcb6602eed50616a2f601c)
 - [fd52e94b69f2ec44552fb1ff21a3897d114f620a](https://github.com/magento/magento2/commit/fd52e94b69f2ec44552fb1ff21a3897d114f620a)
 - [bc35cdce662c0364d6bbe819007c2de0ec032997](https://github.com/magento/magento2/commit/bc35cdce662c0364d6bbe819007c2de0ec032997)

The fix will be available with the upcoming 2.3.2 release.

**Comment by Cros1404** [comment]
Website scoped attributes still have the same issue in 2.2.8
