### ISSUE TITLE
Tierprice discount not calculated correctly if has specialprice.

### ISSUE THREAD

**Issue by Hoszi** [magento/magento2#18652]
### Preconditions (*)
1. Install the newest version 2.2.6

### Steps to reproduce (*)
1. Add new product with price $18.42
2. Add special price $14
3. Add tier price with qty=2, type = "Discount" and value = "%12"
4. Add tier price with qty=300, type = "Discount" and value = "%25"
4. Add tier price with qty=1000, type = "Discount" and value = "%50"
6. Save the product

### Expected result (*)
1. The tierprice discount calculated by specialprice and show all the tierprice

### Actual result (*)
1. The price and the "Discount" value on frontend for qty=2 is not visible
2. The tierprice percent for qty=300 is 1% instead of 25% on frontend

### Possible Solution
In:
\Magento\Catalog\Model\Product\Attribute\Backend\Tierprice.php
change modifyPriceData function like this:

    protected function modifyPriceData($object, $data)
    {
        /** @var \Magento\Catalog\Model\Product $object */
        $data = parent::modifyPriceData($object, $data);
        $price = $object->getPrice();

        // ADD FROM HERE
        $specialprice = $object->getSpecialPrice();
        $specialPriceFromDate = $object->getSpecialFromDate();
        $specialPriceToDate = $object->getSpecialToDate();
        $today = time();

        if ($specialprice && ($object->getPrice() > $object->getFinalPrice())){
            if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) ||
                $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {
                $price = $specialprice;
            }
        }
        // TO HERE

        foreach ($data as $key => $tierPrice) {
            $percentageValue = $this->getPercentage($tierPrice);
            if ($percentageValue) {
                $data[$key]['price'] = $price * (1 - $percentageValue / 100);
                $data[$key]['website_price'] = $data[$key]['price'];
            }
        }
        return $data;
    }

**Comment by magento-engcom-team** [comment]
Hi @Hoszi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Hoszi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by oleksii-lunkov** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18652-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18652-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18652-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@Alex-Lunkov Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96099` were created

**Comment by magento-engcom-team** [comment]
Hi @Hoszi. Thank you for your report. 
The issue has been fixed in magento/magento2#18743 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [e40b9c7396d98dd136883cda2112ef98f8fcfe7e](https://github.com/magento/magento2/commit/e40b9c7396d98dd136883cda2112ef98f8fcfe7e)
 - [451b6baf59a14eb7284e8263905853215d6448cd](https://github.com/magento/magento2/commit/451b6baf59a14eb7284e8263905853215d6448cd)
 - [edf09b3c171685ad9ea6419275838ee3a4f1a870](https://github.com/magento/magento2/commit/edf09b3c171685ad9ea6419275838ee3a4f1a870)
 - [09bd229cad810e57de4c31fcce1184a1c953e47a](https://github.com/magento/magento2/commit/09bd229cad810e57de4c31fcce1184a1c953e47a)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @Hoszi. Thank you for your report. 
The issue has been fixed in magento/magento2#19179 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [8f463db4808afc9f8f4908a4dee65f3abe981eba](https://github.com/magento/magento2/commit/8f463db4808afc9f8f4908a4dee65f3abe981eba)
 - [63c9ea46673e58f2712da5a768d0840ece184152](https://github.com/magento/magento2/commit/63c9ea46673e58f2712da5a768d0840ece184152)
 - [77492c1c08695753b3a274b02552fab7be9c64c0](https://github.com/magento/magento2/commit/77492c1c08695753b3a274b02552fab7be9c64c0)
 - [d0ba9973dffac27560364906b22786d70410d69d](https://github.com/magento/magento2/commit/d0ba9973dffac27560364906b22786d70410d69d)

The fix will be available with the upcoming 2.3.1 release.

**Comment by cproach** [comment]
This issue is still happening since the patch referenced above was reverted.

**Comment by t-eichmann** [comment]
Still happening in 2.4.2-p2. When will this be fixed?
