### ISSUE TITLE
Negative order amount in dashboard latest order when order is cancelled where coupon has been used

### ISSUE THREAD

**Issue by albsa** [magento/magento2#18754]
### Preconditions (*)

1. Magento v2.2.6
2. PHP 7.1.31

### Steps to reproduce (*)

1. Place an order with a coupon code, for example 4.95 EUR off
2. Cancel the order

### Expected result (*)

1. Expected to see an order with result of 0 in the dashboard latest orders.

### Actual result (*)

1. Getting these results
<img width="401" alt="schermafbeelding 2018-10-22 om 23 03 12" src="https://user-images.githubusercontent.com/8933779/47319744-c2936480-d64f-11e8-9c02-b54b0f0976cb.png">

**Comment by magento-engcom-team** [comment]
Hi @albsa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@albsa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95861`, `MAGETWO-95862` were created

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @albsa. Thank you for your report. 
The issue has been fixed in magento/magento2#19372 by @niravkrish in 2.3-develop branch
Related commit(s):
 - [c4f9a02b53bdc0aed4f0374731e6f785d30b02da](https://github.com/magento/magento2/commit/c4f9a02b53bdc0aed4f0374731e6f785d30b02da)
 - [6ad2344e4929d9e46db8dd2bc8fbc28d5887c6d3](https://github.com/magento/magento2/commit/6ad2344e4929d9e46db8dd2bc8fbc28d5887c6d3)

The fix will be available with the upcoming 2.3.1 release.

**Comment by rav-redchamps** [comment]
This issue is still repeatable on 2.3-develop branch when you view data of particular store/website in the admin dashboard. 

Just fixed it in pull request https://github.com/magento/magento2/pull/21283

**Comment by magento-engcom-team** [comment]
Hi @albsa. Thank you for your report. 
The issue has been fixed in magento/magento2#21283 by @rav-redchamps in 2.3-develop branch
Related commit(s):
 - [d79eb085cabfb16ed8f4432f5cd25b00cf3ba686](https://github.com/magento/magento2/commit/d79eb085cabfb16ed8f4432f5cd25b00cf3ba686)
 - [d1e71b96056f2b83d182c92120008837cd665b9f](https://github.com/magento/magento2/commit/d1e71b96056f2b83d182c92120008837cd665b9f)
 - [f893a925bbf5a92967a79509beefa4314b897f23](https://github.com/magento/magento2/commit/f893a925bbf5a92967a79509beefa4314b897f23)
 - [57c4db41be4281541fc0745bcfd4f6cbca64ef86](https://github.com/magento/magento2/commit/57c4db41be4281541fc0745bcfd4f6cbca64ef86)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @albsa. Thank you for your report. 
The issue has been fixed in magento/magento2#21944 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [7d81b55eb5fd9b170dc6c6c0f60fd9bf4d12274e](https://github.com/magento/magento2/commit/7d81b55eb5fd9b170dc6c6c0f60fd9bf4d12274e)
 - [0cea56222c7c1ba0c361de223a1daf42c2e63fc6](https://github.com/magento/magento2/commit/0cea56222c7c1ba0c361de223a1daf42c2e63fc6)
 - [891e2e1e3afefae742e6c106c1252b881930242a](https://github.com/magento/magento2/commit/891e2e1e3afefae742e6c106c1252b881930242a)
 - [a54bba35bbc7716455bd72cfb72fd1939e9a3885](https://github.com/magento/magento2/commit/a54bba35bbc7716455bd72cfb72fd1939e9a3885)

The fix will be available with the upcoming 2.2.9 release.
