### ISSUE TITLE
ProductRepository->get($sku) fails on incorrect case

### ISSUE THREAD

**Issue by karl-micesoft** [magento/magento2#18803]
### Preconditions (*)

1. Magento 2.2.5
2. (Tested on Magento Cloud platform)

### Steps to reproduce (*)

1. Create (or choose) a product with alphanumeric SKU (e.g. 12345A)
2. Make a call to ProductRepository->get('12345a') (i.e. the SKU but with the wrong case)

### Expected result (*)

1. Depending on required behaviour, either the product returned (case-insensitive) or a NoSuchEntityException (case-sensitive).

### Actual result (*)

1. "Notice: Undefined index: '12345a'"

There are a few simple ways I can see to fix this. For case sensitive matching, just add before the return (module-catalog/Model/ProductRepository.php line 254):

`if(!isset($this->instances[$sku]) {
  throw new NoSuchEntityException(...);
}`

For case insensitive (I think this is probably the most intuitive behaviour), I'd add a lookup array which is populated after the ->getIdBySku, and replace the sku with the loaded one or the one from the lookup array.

**Comment by magento-engcom-team** [comment]
Hi @karl-micesoft. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@karl-micesoft do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by karl-micesoft** [comment]
Apologies, this appears to have already been raised in https://github.com/magento/magento2/issues/12073

I do find it a little odd that it's not been fixed in 2.2.5 when it was raised nearly a year ago and that issue indicates an even simpler fix than mine is in place (cast $sku through strtolower)

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
@Shubham-Webkul thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18803-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18803-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18803-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @karl-micesoft, thank you for you report, I'm not able to reproduce your scenarion on 2.3-develop branch.
![selection_174](https://user-images.githubusercontent.com/40756439/47496497-9c441380-d85f-11e8-9a79-f9237fdb975f.png)

**Comment by karl-micesoft** [comment]
@engcom-backlog-nazar I am not using the 2.3-develop (or 2.2-develop) branch, but 2.2.5 (on a client site on the Magento Cloud platform) as specified above.

**Comment by ghost** [comment]
@karl-micesoft seems like this fixed in 2.2 and 2.3 branches https://github.com/magento/magento2/commit/45da02260c989f088b4645307e4af42d9b944b00 , In my case sku -> '1234a' and '1234A' returns  the same product id

**Comment by ghost** [comment]
@karl-micesoft  I'm closing this issue, as this is already fixed and will be available on next 2.2.7 release.

**Comment by PascalBrouwers** [comment]
still not fixed if you are using a migrated database that contains SKUs that are in uppercase
