### ISSUE TITLE
Duplicate order confirmation emails when checking out with PayPal Express

### ISSUE THREAD

**Issue by squeegy06** [magento/magento2#18838]
### Preconditions (*)
Magento 2.2.5

### Steps to reproduce (*)
1. Configure Paypal Express as a payment option.
2. Add items to cart and proceed to checkout as guest or logged in.
3. Use paypal express as the payment method and complete order.
4. Observe email.

### Expected result (*)
I expected to receive a single order confirmation email.

### Actual result (*)
I receive 2 order confirmation emails.

**Comment by magento-engcom-team** [comment]
Hi @squeegy06. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@squeegy06 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by webkul-ratnesh** [comment]
I would be willing to take on this issue! #SQUASHTOBERFEST

**Comment by webkul-ratnesh** [comment]
I am unable to reproduce the issue on vanilla magento 2.2.5 and 2.2.6

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @squeegy06 thank you for you report, this issue has already fixed by this commit -> https://github.com/magento/magento2/pull/15094

**Comment by squeegy06** [comment]
Sorry if I bothered anyone.  I did finally narrow down the module causing the issue and for the sake of anyone else struggling with this and searching around...

We previously had issues (still present in 2.2.5) with confirmation emails missing the FROM, see bug #14952, and as a result we applied this little module https://github.com/pfortin-expertime/MageFix-Misc which had worked nicely until this issue with PayPal.

Thanks again, I do hope this helps someone.

**Comment by squeegy06** [comment]
Hello again,

I've had some time to work on this issue, and I'm fairly confident there is an issue here.  @engcom-backlog-nazar mentioned this was fixed, but it does not appear that the fix made it into 2.2.5.

So, testing from a fresh install of 2.2.5, when checking out with PayPal, a customer does indeed only get one confirmation email, but it's not because everything functioned correctly, instead a warning is thrown and caught during execution that the "FROM" in the email cannot be set twice, causing the second confirmation that would be sent to fail.

So, this might work, but it's not proper.  And this issue is compounded by the fact that a bug is still present in 2.2.5 where the FROM in the email doesn't actually get set in the end.  So when we apply a fix found in https://github.com/pfortin-expertime/MageFix-Misc to solve the problem with the FROM not being set, it also stops the warning from being thrown so now when you checkout with PayPal, it sends 2 confirmation emails.

Writing a quick module that replaces the paypal checkout with the fix found in #15094 does ultimately fix all of my issues.  But I just want to make someone aware that this issue does not appear to be fixed in 2.2.5

**Comment by fwolfst** [comment]
I believe the issue ist found in 2.2.7; we observe similar behavior, but cannot confirm the fixes yet (will try).

**Comment by rossparachute** [comment]
Hey folks,

**Issue Still Persists**
For what it's worth, we've encountered this issue today:
- Magento v2.3.6
- Magento Paypal v100.3.6.

**Possible Causes**
The why isn't really 100% clear but it could be related to the order's "email_sent" attribute not being set properly. Which other modules should check for before sending the e-mail via the order sender classes.

Possibly the other code sending the e-mail didn't exist before, necessitating an explicit call in the Magento Paypal code (details below). This may no longer be required.

**Quick Fix**
An around plugin on [this method](https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Paypal/Model/Express/Checkout.php#L830) is clearly the most effective, best-practice solution until the underlying issue is fixed.

If you're in a pinch, commenting out those lines seems is an option too. 

----

**Call Details**
Call is here:
https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Paypal/Model/Express/Checkout.php#L830

`if (!$order->getEmailSent()) {
    $this->orderSender->send($order);
}`

Inside this method call here you can see the e-mail is sent with:
https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Sales/Model/Order/Email/Sender/OrderSender.php#L99

Which then calls checkAndSend():
https://github.com/magento/magento2/blob/2.3.6/app/code/Magento/Sales/Model/Order/Email/Sender.php#L74
