### ISSUE TITLE
Transfer Cart Line Items and Transfer Shipping Options do not work for PayPal

### ISSUE THREAD

**Issue by martasiewierskastanczak** [magento/magento2#19064]
### Preconditions

1. Magento 2.2.6
2. In Stores > Configuration > Sales > Payment Methods > PayPal > Advance Settings > PayPal Express Checkout Enabled with Sandbox Mode
2. In Stores > Configuration > Sales > Payment Methods > PayPal > Advance Settings > Transfer Cart Line Items set to _Yes_ and Transfer Shipping Options set to _Yes_  and Skip Order Review Step set to _Yes_

### Steps to reproduce 

1. Add a product to the cart
2. Go to the checkout and fill the Shipping step, fill the form, then go to the Payment step and choose PayPal
3. Alternatively, use PayPal button in the cart step or in the minicart

### Expected result

1. Cart items and shipping methods are visible on PayPal page
2. If you Use Express ( from the cart page or from the minicart) checkout review step is NOT visible 

### Actual result 

1. Cart items and shipping methods are not transferred into PayPal page
2. If you Use Express ( from the cart page or from the minicart) checkout review step is visible although _Skip review_ setting is set to _Yes_

![zrzut ekranu 2018-11-05 o 08 01 44](https://user-images.githubusercontent.com/44764610/47982948-f18aeb00-e0d1-11e8-97cc-86a619844c2d.png)

**Comment by magento-engcom-team** [comment]
Hi @martasiewierskastanczak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@martasiewierskastanczak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by martasiewierskastanczak** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @martasiewierskastanczak. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @martasiewierskastanczak, here is your [Magento instance](http://34.228.235.121/i-19064-2-2-6/).
Admin access: [http://34.228.235.121/i-19064-2-2-6//admin](http://34.228.235.121/i-19064-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96137`, `MAGETWO-96138` were created

**Comment by vseager** [comment]
I can confirm this is still an issue on 2.3.1

**Comment by sdzhepa** [comment]
Hello @martasiewierskastanczak @vseager 

Thank you for contribution and collaboration!

The corresponding internal ticket `MAGETWO-96137`, `MAGETWO-96138` were fixed and closed by Magento team

Delivered to `2.3-develop` branch and should be available with 2.3.2 release
Please see details in the next commits:
- cfcb773

Delivered to `2.2-develop` branch and should be available with 2.2.9 release
Please see details in the next commits:
- e0e5c40

**Comment by rishabhchd19** [comment]
This issue didn't resolve in 2.3.2 as well. We are using Indian Rupee, and 1 extension that ADD Extra Service Charge(Collection Charge) during Checkout. Now if Order is above Rs.500, the discount applies on Cart Rule. The Checkout shows correct data but it doesn't load to paypal gateway, giving same issue as posted here. 
![2019-10-08_1-05-04](https://user-images.githubusercontent.com/30948461/66342884-0b7b2080-e968-11e9-83b8-3c7f8dc459f6.jpg)
