### ISSUE TITLE
Fatal error: Uncaught Error: Cannot call abstract method Magento\Framework\App\ActionInterface::execute()

### ISSUE THREAD

**Issue by kanhaiya5590** [magento/magento2#19082]
### Preconditions (*)

1. Tested on Magento > 2.2.1 

### Steps to reproduce (*)

1. Try accessing http://www.domain.com/catalog/product/compare in any browser.

### Expected result (*)

1. Should be handling the exception and ideally showing 404 page.

### Actual result (*)

1. It is  throwing `Fatal error: Uncaught Error: Cannot call abstract method Magento\Framework\App\ActionInterface::execute() in .../Magento/Catalog/Controller/Product/Compare/Interceptor.php`.

**Comment by magento-engcom-team** [comment]
Hi @kanhaiya5590. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kanhaiya5590 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://34.228.235.121/i-19082-2-2-develop/).
Admin access: [http://34.228.235.121/i-19082-2-2-develop//admin](http://34.228.235.121/i-19082-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://34.228.235.121/i-19082-2-3-develop/).
Admin access: [http://34.228.235.121/i-19082-2-3-develop//admin](http://34.228.235.121/i-19082-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@rogyar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96148`, `MAGETWO-96149` were created

**Comment by rogyar** [comment]
For reference, by using this URL the router tries to load the following abstract class `\Magento\Catalog\Controller\Product\Compare` which does not have an `execute` method within its scope.

**Comment by VladimirZaets** [comment]
Hi @kanhaiya5590. Thank you for your report. 
The issue has been fixed in magento/magento2#19337 by @agorbulin in 2.2-develop branch
Related commit(s):
 - [20922a02cd1ed9a70bae9dee530b5ef0b712b436](https://github.com/magento/magento2/commit/20922a02cd1ed9a70bae9dee530b5ef0b712b436)

The fix will be available with the upcoming 2.2.8 release.

**Comment by kanhaiya5590** [comment]
@VladimirZaets  Thanks for update,

Any update for magento 2.3 because issue still there in 2.3

**Comment by agorbulin** [comment]
Hello @kanhaiya5590 
Fix merged to 2.3.1, so it's not available in 2.3.0.
You can apply fix manually for 2.3 and remove it, after upgrade to 2.3.1

**Comment by kanhaiya5590** [comment]
@agorbulin thanks for update
