### ISSUE TITLE
Can't Cancel Order

### ISSUE THREAD

**Issue by friendscottn** [magento/magento2#19230]
### Preconditions (*)

1. 2.2.6
2. Allow guest checkout
3. Have a coupon you can use

### Steps to reproduce (*)

1. Checkout as a guest using a valid coupon
2. After placing the order, register an account using the create account button on the order confirmation page.
3. Login to the admin
4. Make sure to get the order to a processing state.
5. Try to cancel the order

### Expected result (*)

1. The order is canceled

### Actual result (*)

1. You receive the generic errror "You have not canceled the item"
2. The underlying error is: 
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mage`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES () {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mage`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES () at /www/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mage`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE) at /www/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"} []
```

### Related Issues
https://github.com/magento/magento2/issues/16779

**Comment by magento-engcom-team** [comment]
Hi @friendscottn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@friendscottn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](http://34.228.235.121/i-19230-2-2-develop/).
Admin access: [http://34.228.235.121/i-19230-2-2-develop//admin](http://34.228.235.121/i-19230-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96384` were created

**Comment by machaka** [comment]
Hi there, I'm able to reproduce it, I'm facing the same issue on magento 2.2.6

**Comment by dudzio12** [comment]
Same for me

**Comment by Winfle** [comment]
Reproducible on `2.2.7-dev`

**Comment by magento-engcom-team** [comment]
Hi @KravetsAndriy. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by SamB-GB** [comment]
Does anyone know if this is an issue in 2.2.3?

**Comment by Winfle** [comment]
@SamB-GB Hello. It doesn't throw exception, however expected behaviour is not valid, because after making an account, it doesn't increase coupon usage for newly created customer. 
So, I think, that make reverse bugs, however, if you you're interested only in canceling order, you won't have a bug, described here.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash, here is your [Magento instance](https://i-19230-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19230-2-3-0.instances.magento-community.engineering/admin](https://i-19230-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@friendscottn, thank you for reporting this isuue. The latest released version of Magento (2.3.0) is not affected by this issue. After the order is invoiced you cannot cancel the order. By if the merchant ships the order without invoicing than order gets status processing and also he is able to cancel it until invoice is not created. In such conditions order has no problems with cancelation

**Comment by Winfle** [comment]
@engcom-backlog-tomash I think, when user makes guest order with coupon code and then registers an account, coupon code usage should be increased and coupon usage per customer should be increased , the same way as customer made account BEFORE checkout with given coupon.
In fact, coupon has been used, but amount of usages will be the same as before. This behaviour exists in 2.3.
If its not relevant to current scope ( Canceling an order), I can make separated issue.

**Comment by ghost** [comment]
@Winfle, yes please create new one if it's not already created.

**Comment by sidolov** [comment]
Hi @friendscottn. Thank you for your report. 
The issue has been fixed in magento/magento2#19423 by @Winfle in 2.2-develop branch
Related commit(s):
 - [cede04f014733bffc5104f2e26579e8ce242f462](https://github.com/magento/magento2/commit/cede04f014733bffc5104f2e26579e8ce242f462)
 - [11480e8b44d26ecf8e692c1a3406423b1532031f](https://github.com/magento/magento2/commit/11480e8b44d26ecf8e692c1a3406423b1532031f)
 - [10fbf4041c98b12ee4bb19f09f04efc7856dfa60](https://github.com/magento/magento2/commit/10fbf4041c98b12ee4bb19f09f04efc7856dfa60)
 - [1e2f3fbd5481b3eee6d7c049703c0d51b849c439](https://github.com/magento/magento2/commit/1e2f3fbd5481b3eee6d7c049703c0d51b849c439)
 - [5ea6e7208099123c5e7f8df34607fca9ef03c650](https://github.com/magento/magento2/commit/5ea6e7208099123c5e7f8df34607fca9ef03c650)
 - [9a63dad6a2958d07aa631bb0e971f17e3f6eda3b](https://github.com/magento/magento2/commit/9a63dad6a2958d07aa631bb0e971f17e3f6eda3b)
 - [36c2329505ca63c821fc8d7a553e6f35a4f3ae40](https://github.com/magento/magento2/commit/36c2329505ca63c821fc8d7a553e6f35a4f3ae40)
 - [fdf7da48088ffae823021e5a8be4429afa941404](https://github.com/magento/magento2/commit/fdf7da48088ffae823021e5a8be4429afa941404)

The fix will be available with the upcoming 2.2.8 release.

**Comment by MageCloudTeam** [comment]
@sidolov the same issue in Magento 2.2.9

**Comment by magento-engcom-team** [comment]
Hi @friendscottn. Thank you for your report. 
The issue has been fixed in magento/magento2#20577 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [5a24c411060934c8496830762704e5d07131a80a](https://github.com/magento/magento2/commit/5a24c411060934c8496830762704e5d07131a80a)
 - [44760ff282f67091c8eb325ce81c41655bdabc7a](https://github.com/magento/magento2/commit/44760ff282f67091c8eb325ce81c41655bdabc7a)
 - [ae76c57fcbef3f0cc58c2599816dfec916567a85](https://github.com/magento/magento2/commit/ae76c57fcbef3f0cc58c2599816dfec916567a85)
 - [d8add8a90b22ce58f6688e3d6677c7623080fbe7](https://github.com/magento/magento2/commit/d8add8a90b22ce58f6688e3d6677c7623080fbe7)
 - [2fd017a4afe6f90e98f09fa154799dd8ab2a9d46](https://github.com/magento/magento2/commit/2fd017a4afe6f90e98f09fa154799dd8ab2a9d46)
 - [565d0b10ec4719a3e9d5befa05898a71329e86ea](https://github.com/magento/magento2/commit/565d0b10ec4719a3e9d5befa05898a71329e86ea)

The fix will be available with the upcoming 2.3.4 release.

**Comment by parekhreena** [comment]
The issue still happens with Guest Users. The issue originates from \Magento\SalesRule\Model\Coupon\UpdateCouponUsages::updateCustomerRuleUsages and this line $ruleCustomer->save(); was causing the issue. I am on enterprise version.

**Comment by mertgokceimam** [comment]
@magento-engcom-team Can you please release a patch for this on 2.2.x for EE customers. Orders can't be cancelled have big effect on stock values within the system

**Comment by simonmaass** [comment]
i am still having this issue in magento 2.3.3 CE:

[2020-01-03 10:42:12] main.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`xxxx`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES () {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`xxxx`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE), query was: INSERT INTO `salesrule_customer` () VALUES () at /var/www/html/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dbzn3lqcchilq`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SALESRULE_RULE_ID` FOREIGN KEY (`rule_id`) REFERENCES `salesrule` (`rule_id`) ON DELETE CASCADE) at /var/www/html/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []

**Comment by khoimm92** [comment]
This issue still exists on Magento 2.4.2

**Comment by simonmaass** [comment]
can still confirm this issue in 2.4.3-p1

**Comment by igi8819** [comment]
This issue still exist on Magento 2.4.3-p1

````
Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_value`) ON DELETE C), query was: INSERT INTO `salesrule_customer` () VALUES () {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_value`) ON DELETE C), query was: INSERT INTO `salesrule_customer` () VALUES () at /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_value`) ON DELETE C) at /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
````

**Comment by johnorourke** [comment]
@simonmaass @igi8819 on 2.4.3-p1 you might have the same issue I did - trying to cancel an order via the REST API immediately after it's placed caused this error.  I added a short pause (1 second) between the order place event and the API call to cancel it, and the problem went away.  I think it's because the call to place an order is done from javascript, so perhaps the call to cancel the order can happen before the place order code has completed and the database is fully up to date.
