### ISSUE TITLE
Wrong price amount in opengraph

### ISSUE THREAD

**Issue by jcourtei** [magento/magento2#20010]
### Preconditions (*)
Version 2.2.6 (Community Edition).

### Steps to reproduce (*)
1. Several store views with several currency rates.
2. View source code of a simple product in a store view with a currency (USD) different  from the base currency (EUR).

### Expected result (*)
Meta tag "product:price:amount" should contain the price converted in USD.

### Actual result (*)
Meta tag "product:price:amount" contains the price in EUR.
Meta tag "product:price:currency" on the other hand is correct (USD).

In module-catalog/view/frontend/templates/product/view/opengraph/general.phtml the following line is wrong :
`<?php if ($priceAmount = $block->getProduct()->getFinalPrice()):?>`
It should be :
`<?php if ($priceAmount = $block->getProduct()->getPriceInfo()->getPrice('final_price')->getValue()):?>`

**Comment by magento-engcom-team** [comment]
Hi @jcourtei. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jcourtei do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @milindsingh, here is your [Magento instance](https://i-20010-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20010-2-3-develop.instances.magento-community.engineering/admin](https://i-20010-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by milindsingh** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @milindsingh, here is your [Magento instance](https://i-20010-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20010-2-2-develop.instances.magento-community.engineering/admin](https://i-20010-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@milindsingh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97381`, `MAGETWO-97382` were created

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20010-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20010-2-3-develop.instances.magento-community.engineering/admin](https://i-20010-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @jcourtei. Thank you for your report. 
The issue has been fixed in magento/magento2#20011 by @milindsingh in 2.3-develop branch
Related commit(s):
 - [5ee1d4281c1b6c3456aeec5a069ac0338c8b3898](https://github.com/magento/magento2/commit/5ee1d4281c1b6c3456aeec5a069ac0338c8b3898)

The fix will be available with the upcoming  release.

**Comment by magento-engcom-team** [comment]
Hi @jcourtei. Thank you for your report. 
The issue has been fixed in magento/magento2#21202 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [85cdc9d41bb027aca3ce5b4412f67e8af634c141](https://github.com/magento/magento2/commit/85cdc9d41bb027aca3ce5b4412f67e8af634c141)

The fix will be available with the upcoming 2.2.9 release.

**Comment by wssweb** [comment]
The open graph price tag is still incorrect in 2.3.2 when Minimum Advertised Price is enabled. The price used will be Price, and not Manufacturer's Suggested Retail Price. Search engines like Google will use the open graph tag to override the price displayed on the page in their search results, which will cause you to violate any normal IMAP agreement.

**Comment by tprocter1984** [comment]
This is still an issue with grouped products.
