### ISSUE TITLE
[2.2.7] Wrong image order when changing swatches in Configurable product 

### ISSUE THREAD

**Issue by rakeshvarma90** [magento/magento2#20312]
In configurable product associated product's gallery images not sorting as set in Admin 
### Preconditions (*)

1. Magento CE 2.2.7 
2. PHP 7.0.6

### Steps to reproduce (*)

1. Create Configurable product and upload images for the associated product.
2. Save Configurable product.
3. Edit one of Associated product and change its image sort order and save that product.

### Expected result (*)

1. Gallery sort order should be same as set in admin after selecting associate product.

### Actual result (*)

1. Sort order is not same as set in Admin.

**Comment by magento-engcom-team** [comment]
Hi @rakeshvarma90. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rakeshvarma90 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-20312-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20312-2-2-develop.instances.magento-community.engineering/admin](https://i-20312-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @rakeshvarma90 thank you for you report, i'm not able to reproduce following steps you described, please check test instance.

**Comment by rakeshvarma90** [comment]
@magento-engcom-team pleasee provide me 2.2.7 instance I will reproduce this error

**Comment by rakeshvarma90** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rakeshvarma90. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by karangar** [comment]
@magento-engcom-team  give me 2.2-develop instance

**Comment by ghost** [comment]
@karangar why you reopen this issue ?

**Comment by karangar** [comment]
@magento-engcom-team I checked this issue in my local instance. So this issue is generated.
So please give me 2.2-develop instance. So I can generate issue.

**Comment by ghost** [comment]
@rakeshvarma90 please provide a screenshot of your actual result, because i was recheck, and this issue is not reproducible

**Comment by rakeshvarma90** [comment]
@magento-engcom-team Please check attached screenshot 

Backend setting for image sort order.
![backend](https://user-images.githubusercontent.com/40866016/51238987-310d6780-199e-11e9-8442-abd37c2ef6b0.png)

Frontend output.

![frontend](https://user-images.githubusercontent.com/40866016/51239044-500bf980-199e-11e9-835e-2b6ae95e6bf8.png)

**Comment by ghost** [comment]
@rakeshvarma90 on which instance you tested ?

**Comment by rakeshvarma90** [comment]
I have tested in 2.2.7

**Comment by ghost** [comment]
@rakeshvarma90 so please recheck on 2.2-dev because this issue is not present there.

**Comment by rakeshvarma90** [comment]
@magento-engcom-team provide me 2.2-dev instance so I will check there

**Comment by ghost** [comment]
@rakeshvarma90 i was recheck on both 2.2-develop and 2.3-develop there is no this issue.

**Comment by rakeshvarma90** [comment]
@magento-engcom-team I have give you screenshot in 2.2.7. can you please give me instance so I will check from my end too. 
and also check this closed issue of #5918  recently one use has confirmed there is a bug in 2.2.7

**Comment by ghost** [comment]
@rakeshvarma90 we now talking about that this already fixed on 2.2-dev branch so will be available on 2.2.8 release.

**Comment by rakeshvarma90** [comment]
@magento-engcom-team can you please provide me changes to fix this issue in 2.2.7?

**Comment by ghost** [comment]
@rakeshvarma90 i'm will try to find

**Comment by joshdavenport** [comment]
@engcom-backlog-nazar Any progress in finding the change that fixes this? Very much need this fix ASAP but am not in a position to upgrade to any currently released version that would fix this.

**Comment by joshdavenport** [comment]
After looking at the [history of module-swatches](https://github.com/magento/magento2/commits/2.2-develop/app/code/Magento/Swatches), I suppose the fix comes from  https://github.com/magento/magento2/commit/ff692d0402084eab3788a2ca4f129e953c9fa0dd and https://github.com/magento/magento2/commit/6f5b681c7f5cb3b76825896b0d03031ea36bae4a? @rakeshvarma90 you are presumably interested in these fixes too, hopefully they work!

**Comment by ghost** [comment]
@rakeshvarma90 i'm not able to find, seems like this was fixed by core team on private repository.

**Comment by rakeshvarma90** [comment]
@joshdavenport Good Finding Thanks. I will try this fix

**Comment by ywsw** [comment]
this issue is still present on 2.3
(summary of issue: when on a configurable product page, clicking a swatch to load the simple product images, the images are sometimes loaded out of order)

The issue seems to be caused by Magento remembering the original order that the images were uploaded to this particular simple product. Even though I had rearranged them in the backend on the product page, they will still be loaded on the configurable product page (when the simple product is loaded) on the original and incorrect image order. 
This only affects simple products loaded on configurable product pages. If that simple product was made visible and you go directly to that page, the images are shown in the correct and updated order. Only when this simple product is loaded through a configurable product page are the original and incorrect image order shown.

Temporary solution: delete the images and re-upload them in the correct order...

**Comment by joshdavenport** [comment]
Yes @ywsw, the issue is definitely present in 2.3.0 because the fix made it to 2.2-develop and 2.3-develop post release of 2.3.0. Therefore, I'd imagine the fix will make it into 2.3.1 (and 2.2.8 for 2.2.x releases)

You can see the fix in 2.3-develop anyway so for now you'll have to manually patch with these changes https://github.com/magento/magento2/commit/94391bdeb98bbd100313d33d1257f16c982e2a1 and https://github.com/magento/magento2/commit/e21aae365e4b17dbadc825adeb4cf063be887662
