### ISSUE TITLE
File type option value shows html content in order, invoice and credit memo emails

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#20352]
Updated issue description 

### Preconditions (*)

1. Magento 2.4-develop
2.

### Steps to reproduce (*)

1. Create a product with file type option.
2. Place an order with this product by uploading file.
3. Created invoice and credit memo for order
4. Send emails for order, invoice and credit memo to customer from backend
5. Check emails

### Expected result (*)

1. Option value must be display as link.(e.g., as for shipment email)
![image](https://user-images.githubusercontent.com/51681379/92085607-bd69d980-edd1-11ea-8066-952f906738ef.png)

### Actual result (*)

1. Option value shows html content
- Order email:
![image](https://user-images.githubusercontent.com/51681379/92085711-e12d1f80-edd1-11ea-9f9e-eec6ae9035b1.png)

- Invoice email:
![image](https://user-images.githubusercontent.com/51681379/92085774-f6a24980-edd1-11ea-876e-e9fcc0161ce3.png)

- Credir memo email:
![image](https://user-images.githubusercontent.com/51681379/92085835-07eb5600-edd2-11ea-9427-27e347751545.png)

### Additional information:
Original issue description:
 Preconditions (*)

1. Magento 2.2.X
2.

 Steps to reproduce (*)

1. Create a product with file type option.
2. Place an order with this product by uploading file.
3. Go to Sales->Order view.
4. Option value is displaying html content instead on link

 Expected result (*)

1. Option value must be display as link.
![screenshot](https://user-images.githubusercontent.com/32479280/51271085-a2740700-19ec-11e9-8f34-e4ce882993e7.png)

 Actual result (*)

1. ![screenshot](https://user-images.githubusercontent.com/32479280/51271034-807a8480-19ec-11e9-814f-3d553c8eaeb4.png)
2.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@maheshWebkul721 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97663` were created

**Comment by cedarvinda** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your report. 
The issue has been fixed in magento/magento2#20353 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [c0730dc827a417f09c42f96dacd6d1349dd7a565](https://github.com/magento/magento2/commit/c0730dc827a417f09c42f96dacd6d1349dd7a565)

The fix will be available with the upcoming 2.2.8 release.

**Comment by WilliejanB** [comment]
Hi, I use Magento ver. 2.3.5-p1 and this issue still excists. Please let me know how I can solve this!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37335` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by WilliejanB** [comment]
Has this issue been solved? In Magento 2.4.0 it still exists. Please let me know in which version it is solved?

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by WilliejanB** [comment]
This issue still occurs in Magento ver 2.4.3
In Magento backend admin, in order confirmation emails and PDF documents.

![Sales _ Magento Admin](https://user-images.githubusercontent.com/67437750/134638102-bed16417-d679-47a8-b3e1-0326b059eac2.png)
