### ISSUE TITLE
Inconsistency: an attribute code maximum length validation does not conform to the database field maximum length

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2073]
A detailed analysis here: https://mage2.pro/t/129
See also another bug with attribute code length validation: https://github.com/magento/magento2/issues/1978

**Comment by tanya-soroka** [comment]
Internal ticket has been created MAGETWO-44070.

**Comment by tanya-soroka** [comment]
@dfediuk issue has been fixed.

**Comment by rain2o** [comment]
As of version 2.1.2 I am still seeing this discrepancy between the 30 character limit and the 255 character limit. I don't see where this was resolved.

**Comment by steros** [comment]
@tanya-soroka this is still an issue in 2.1.5 and possibly newer, can you please reopen the ticket

**Comment by davidvarney** [comment]
@tanya-soroka adding to @steros comment, this is still an issue in 2.1.6 and 2.1.7, can you please reopen the ticket.

@tanya-soroka This is a pretty annoying issue here. I changed the constant value from 30 to 255 and everything was fine when I programmatically added a bunch of attributes via my custom module.

**Comment by korostii** [comment]
Hi @magento-team, can this issue be looked at?
All the code referenced in the [issue report](https://mage2.pro/t/129) remains unchanged on both `develop` and `2.1-develop` up until now:
https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/Eav/Model/Entity/Attribute.php

It's not clear, what was reportedly "fixed" instead, exactly?

**Comment by vaguemind** [comment]
Hello , I still have this issue when importing csv file for products in version 2.3 ?! 
can you advise the solution ?

Thanks

**Comment by oviliz** [comment]
@magento-admin could anyone please review this "closed" issue?
