### ISSUE TITLE
Magento backend catalog "Cost" without currency symbol

### ISSUE THREAD

**Issue by mage2pratik** [magento/magento2#20906]
### Preconditions (*)

1. Magento 2.3.X
2. Magento 2.2.X

### Steps to reproduce (*)

1. Navigate to admin catalog product grid
2. Using "Columns" selection add 'Cost' column in the grid

### Expected result (*)

1. "Cost" will be shown with currency code

### Actual result (*)

![screenshot](https://user-images.githubusercontent.com/33807558/52173581-21b75800-27ad-11e9-97fa-7816665fd953.png)

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mage2pratik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by mage2pratik** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by mage2pratik** [comment]
#MM19IN

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @mage2pratik
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by mage2pratik** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik, here is your [Magento instance](https://i-20906-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20906-2-3-develop.instances.magento-community.engineering/admin](https://i-20906-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98037`, `MAGETWO-98038` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by swnsma** [comment]
#20472

**Comment by jtomka** [comment]
#mlau

**Comment by jtomka** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jtomka. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jtomka, here is your [Magento instance](https://i-20906-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20906-2-3-develop.instances.magento-community.engineering/admin](https://i-20906-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @jtomka. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your report. 
The issue has been fixed in magento/magento2#20907 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [85beeec61b061f9494df14cad448753bd9e75c8b](https://github.com/magento/magento2/commit/85beeec61b061f9494df14cad448753bd9e75c8b)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your report. 
The issue has been fixed in magento/magento2#21157 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [ee8868922bd027510c707a092d2c0f0d04019b71](https://github.com/magento/magento2/commit/ee8868922bd027510c707a092d2c0f0d04019b71)

The fix will be available with the upcoming 2.2.9 release.

**Comment by orlangur** [comment]
Still not fixed properly. Currently merged PRs must be reverted.

Proper fix does require changing columns displayed in grid by default and will also cover https://github.com/magento/magento2/issues/20472 and https://github.com/magento/magento2/issues/21910.

**Comment by imrandotftr** [comment]
"I am working on this at #dmcdindia19”

**Comment by magento-engcom-team** [comment]
@imrandotftr thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik, @orlangur, @imrandotftr. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.

**Comment by slavvka** [comment]
Hi @mage2pratik. Thank you for your report. 
The issue has been fixed in magento/magento2#27261 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [d81d1d451bb7f10492d249e2c0c70e9d8d1df905](https://github.com/magento/magento2/commit/d81d1d451bb7f10492d249e2c0c70e9d8d1df905)

The fix will be available with the upcoming 2.4.0 release.
