### ISSUE TITLE
Can't change customer group when placing an admin order

### ISSUE THREAD

**Issue by gaurav-473** [magento/magento2#21144]
When ordering in the admin, we can't change the customer group when creating a new customer while creating an order.
### Preconditions
1.  Magento 2.3
3.  Several Customer Groups created
### Steps to reproduce
1.  In admin select Sales->Orders.
2.  Select Create New Order
3.  Select Create New Customer
4.  Under Account Information, change the group.
### Expected result
1.  Selected customer group stays selected in select box.
2.  Product prices are updated for the group.
### Actual result
1.  Wait overlay comes up, twice.
2.  Customer group goes back to the default.
3.  Email input box to the right is cleared.
4.  Product prices stay the same.

Note: this issue is similiar to #7974 and #6162

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gauravagarwal1001 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-21144-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21144-2-3-develop.instances.magento-community.engineering/admin](https://i-21144-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98214`, `MAGETWO-98215` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your report. 
The issue has been fixed in magento/magento2#21145 by @gauravagarwal1001 in 2.3-develop branch
Related commit(s):
 - [76468502c720ae637c3c61382dfd57a40c071ad1](https://github.com/magento/magento2/commit/76468502c720ae637c3c61382dfd57a40c071ad1)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your report. 
The issue has been fixed in magento/magento2#21239 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [d77bc6acaccaecddc4bda3415d268ed21ef94981](https://github.com/magento/magento2/commit/d77bc6acaccaecddc4bda3415d268ed21ef94981)

The fix will be available with the upcoming 2.2.9 release.

**Comment by kunzi** [comment]
I'm still having this issue in Magento 2.3.3. Is there a way to fix this?

**Comment by herman-aka-wouter** [comment]
I'm having the same issue still on 2.3.3. can't find a patch

**Comment by herman-aka-wouter** [comment]
@kunzi  i found this topic: https://stackoverflow.com/questions/23255545/magento-ce-customer-groups-changing-not-saving

specialy the comment: 
> I know it is old thread but the issue was in Settings > Customers > Customer Configuration(in your admin panel) . Please set Enable Automatic Assignment to Customer Group to no.

after setting this to 0 the problem is solved ;-)

**Comment by web4exposure-org** [comment]
@wouter-toppy 
This is not a fix for me, it does make it possible to change the customer group from the backend, but it will also disallow a guest customer to order with a certain (VAT-determined) customer group from the frontend.

I assume an override of the Mage classes will be required to fix both these cases.

**Comment by magedev218** [comment]
I am still facing the same issue on Magento version 2.3.3. I have selected YES for Enable Automatic Assignment to Customer Group for Guest Customer with valid VAT ID. Also patch doesnot works for me.

Does any one have solution?

**Comment by DominicWatts** [comment]
@magedev218 the solution is to set to NO. With the option set to YES Magento is trying to validate the VAT ID - it's failing and reverting the customer group to default. This also affected customer group specific price rules on frontend for me.
