### ISSUE TITLE
Duplicate Sign Out Buttons on Mobile

### ISSUE THREAD

**Issue by dervishm96** [magento/magento2#21195]
### Preconditions (*)

1. 2.3.0
2. Frontend

### Steps to reproduce (*)

1. Customer signs in to their account on mobile.
2. Goes to Menu > Account > 
3. There are 3 Sign Out buttons and 2 My Account butttons present

### Expected result (*)

1. Customer signs in to their account on mobile.
2. Goes to Menu > Account > 
3. There should be one sign out button and one My Account button.

### Actual result (*)

1. Customer signs in to their account on mobile.
2. Goes to Menu > Account > 
3. There are 3 Sign Out buttons and 2 My Account butttons present
![inkedscreenshot_20190213-145007_chrome_li](https://user-images.githubusercontent.com/47602218/52720275-319a1d80-2f9f-11e9-9f56-d51fdeae4dac.jpg)

**Comment by magento-engcom-team** [comment]
Hi @dervishm96. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dervishm96 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-21195-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21195-2-3-develop.instances.magento-community.engineering/admin](https://i-21195-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @dervishm96 thank you for your report . It seems this issue is already fixed in current magento 2.3 - develop instance

**Comment by dervishm96** [comment]
Hi,

I am still experiencing this issue and I am currently using the latest version 2.3.0.

Please see temporary frontend:
www.new.image-work.co.uk/magento2/

**Comment by shikhamis11** [comment]
hello @dervishm96 I checked on current magento 2.3-develop instance this is not present It seems it is fixed in earlier commits . You can check on the above instance
