### ISSUE TITLE
Category Layered Filter Issue

### ISSUE THREAD

**Issue by kost08** [magento/magento2#2121]
When you search for something, using sample data for example, a '**bag**' no category filters are displayed. That happens because category filters are only rendered if Category in `$categories` has no children categories. In [`Magento\CatalogSearch\Model\Layer\Filter\Category`](https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogSearch/Model/Layer/Filter/Category.php) in `::_getItemsData()` `$category` is *Default Category* and `$categories` is a collection of it's direct children categories. 
![1](https://cloud.githubusercontent.com/assets/3988557/10520519/8279a772-737b-11e5-860b-5857581f2fda.PNG)
But `$optionsFacetedData` is an array of Categories which are children of the `$categories`
![2](https://cloud.githubusercontent.com/assets/3988557/10520523/87efc222-737b-11e5-9eb0-1d0dcd6fbf48.PNG)
When you check 
````
...
foreach ($categories as $category) {
    if ($category->getIsActive()
        -> && isset($optionsFacetedData[$category->getId()]) <-
        && $this->isOptionReducesResults($optionsFacetedData[$category->getId()]['count'], $collectionSize)
) {
...
```
There is no match and filters aren't rendered.

**Comment by magebay99** [comment]
why not using isotope filtering?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by psol7** [comment]
I think it is a technical issue (bug) with M2.
Categories in layered are only rendered if Category in  has no children.
Layered category filter only shows non-anchored sub-categories, all is_anchor ones are not displayed.
Same with search results layered category.
This happen with the demo sample data as well as our migrated store from 1.9.01 (2000 categories in 4 levels). in our 1.9.0.1 all categories and sub-categories are displayed fine in layered left nav.

**Comment by RakeshJesadiya** [comment]
I have same kind of issue available for category with subcategory have product then its not display inside layered navigation.

I have checked category with subcategory all have is_anchor equal yes.

Any update for this issue?

**Comment by ktruehl** [comment]
Here's a patch that fixes the issue:

```
diff --git a/www/vendor/magento/module-catalog-search/Model/Adapter/Mysql/Plugin/Aggregation/Category/DataProvider.php b/www/vendor/magento/module-catalog-search/Model/Adapter/Mysql/Plugin/Aggregation/Category/DataProvider.php
index f54a60f..678226b 100644
--- a/www/vendor/magento/module-catalog-search/Model/Adapter/Mysql/Plugin/Aggregation/Category/DataProvider.php
+++ b/www/vendor/magento/module-catalog-search/Model/Adapter/Mysql/Plugin/Aggregation/Category/DataProvider.php
@@ -74,8 +74,8 @@ class DataProvider
             $derivedTable->from(
                 ['main_table' => $this->resource->getTableName('catalog_category_product_index')],
                 [
-                    'entity_id' => 'product_id',
                     'value' => 'category_id',
+                    'entity_id' => 'product_id',
                 ]
             )->where('main_table.store_id = ?', $currentScopeId);
             $derivedTable->joinInner(
```

The problem is the following. In `Magento\CatalogSearch\Model\Adapter\Mysql\Aggregation\DataProvider` in the `execute`-method the `fetchAssoc` method is used to convert the query result into an associative array. The `fetchAssoc` method however uses the first column for the keys of the associated array. For all attribute aggregations the first column is always the `value` column, as it should be. However for the category aggregation the first column for some reason is the `entity_id` column, which is not unique. The fix consists thus in making the `value` column the first column to be returned by the select.

**Comment by psol7** [comment]
Right on ktruehl. Problem fixed. Thks.

**Comment by choukalos** [comment]
Hi @ktruehl Thanks for the patch!  I've created a bug for internal tracking purposes - MAGETWO-52436 .
Closing the other github issue as a dup.

**Comment by Krapulat** [comment]
Thanks @ktruehl, your fix works perfectly.

**Comment by maghamed** [comment]
Current issue has been fixed and delivered in the scope of 2.0.3 patch release.
So, it's now available on github 
The fix is the same as @ktruehl provided above
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogSearch/Model/Adapter/Mysql/Plugin/Aggregation/Category/DataProvider.php

**Comment by mwsanders0** [comment]
This fix isn't in the 2.0.3 patch, it's not even in 2.0.5, but I can still see the fix in the dev branch - any reason it's not been included yet?

**Comment by maghamed** [comment]
It didn't get to 2.0.3. Now it's going to be delivered in the scope of 2.0.7 Patch release

**Comment by ghost** [comment]
I am having a similar issue. Not all the categories that appear in the navigation menu dropdown are appearing in the category section in the layered navigation. There doesn't seem to be anything related with what shows up and what doesn't show up. All categories are set as anchors. Some categories have sub categories and some don't. It doesn't seem to make a difference as to them showing up or not. There are enabled products in all categories/sub categories.

I have tried deleting and re-adding one of the categories that wasn't showing up in the layered navigation and it did show up but then went away again after adding some sub categories to it.

This is with Magento 2.0.7 CE.

Here is a screenshot showing what I mean.

![mage2categorybug](https://cloud.githubusercontent.com/assets/19348887/15867747/080493ae-2cbb-11e6-85c2-c5ac28ee41ba.png)

**Comment by w3prodigy** [comment]
Thanks for the fix @ktruehl

**Comment by blizam** [comment]
I'm experiencing crtsl's issue as well... getting Categories to show in the Category Layered Navigation seems very buggy... deleting-readding categories seems to fix it temporarily... but then as I work in a category adding sub cats or products it seems to get removed... sometimes... I'm trying to narrow down the behavior exactly...

Mage 2.0.7

**Comment by blizam** [comment]
Yeah, when I create a New Category and add products to it via the Category Products tab then the layered navigation renders on the front end for that Category.

If I then add 1 Subcategory, assign it some products in the same manner... everything is fine.

As soon as I add a second subcategory, assign it some products, and save then the parent Category disappears from Layered Navigation all together.

I feel like this is perhaps offtopic here though as the OP was posting about Search... I'll open a new Issue

**Comment by blizam** [comment]
https://github.com/magento/magento2/issues/5009

**Comment by maghamed** [comment]
Internal issue created - MAGETWO-54383

**Comment by KrystynaKabannyk** [comment]
Hello @kost08, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by vivek-ted** [comment]
Thank you all, its helped me lot.

@kost08 thanks for the post.

**Comment by pitangaweb** [comment]
I'm experiencing the exact same issue on Magento 2.1.2 on blank theme. Category filter disappear as soon as I add products on subcategory.

**Comment by jpcsguru** [comment]
this is still present in 2.1.6

**Comment by jamiejackson1183** [comment]
Also having same issue in 2.1.3 Enterprise

**Comment by btwq** [comment]
Having similar issues in 2.1.7

Valid subcategories are not appearing in layered navigation "Category" section of a parent category page

**Comment by ci2014** [comment]
Still present in 2.2.0

**Comment by allyreflections** [comment]
I have the same issue in Magento 2.1.7. Any fix on this issue..?

**Comment by rnkings** [comment]
I'm having the same issue in Magento 2.1.5 :/

**Comment by SilvanLaroo** [comment]
Same issue on Magento 2.1.10.

**Comment by alexvais** [comment]
i think that this issue is related to "isOptionReducesResults" method. 

I had the same issue when you have a parent category, for example "furniture" and inside "chairs" and "tables"

If all searched items are inside "furniture", this option is not showed because for Magento 2 have no sense show an option to filter where all the products are inside. 

BUT this also do not allow the customer to filter on the subcategories.

If you want show it anyways you have to delete "isOptionReducesResults" check from here "vendor/magento/module-catalog-search/Model/Layer/Filter/Category.php"

`   /**
     * Get data array for building category filter items
     *
     * @return array
     */
    protected function _getItemsData()
    {
        /** @var \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection $productCollection */
        $productCollection = $this->getLayer()->getProductCollection();
        $optionsFacetedData = $productCollection->getFacetedData('category');
        $category = $this->dataProvider->getCategory();
        $categories = $category->getChildrenCategories();

        $collectionSize = $productCollection->getSize();

        if ($category->getIsActive()) {
            foreach ($categories as $category) {
                if ($category->getIsActive()
                    && isset($optionsFacetedData[$category->getId()])
                    && $this->isOptionReducesResults($optionsFacetedData[$category->getId()]['count'], $collectionSize)
                ) {
                    $this->itemDataBuilder->addItemData(
                        $this->escaper->escapeHtml($category->getName()),
                        $category->getId(),
                        $optionsFacetedData[$category->getId()]['count']
                    );
                }
            }
        }
        return $this->itemDataBuilder->build();
    }`
