### ISSUE TITLE
Catalog rule with is oneof/ not one of not working with multiple SKU condition

### ISSUE THREAD

**Issue by Jitheesh** [magento/magento2#21618]
Catalogue rule is only applied to first SKU if we include multiple SKUs from product chooser grid while configuring **is one of** or **is not one of** conditions. 
### Preconditions (*)

1. Magento 2.2 or 2.3

### Steps to reproduce (*)

1.  Include SKU attribute in promo rule conditions Store >  Attributes > Product > Edit SKU  > Use for Promo Rule Conditions > Yes
2. Create Catalogue rule, fill required values
3. While configuring conditions, choose Product attribute  SKU and condition as is one of or is not one of
3.1. _If ALL  of these conditions are TRUE  SKU  is one of_ 
![nhmqugs](https://user-images.githubusercontent.com/1536507/54019053-3920a100-41b0-11e9-8721-433bfb69433b.png)

### Expected result (*)

1.  Catalogue rule applied to selected SKUs

### Actual result (*)

1. Catalogue rule only applied to first product from the selection

### Reason

While we choosing SKUs from product chooser grid, condition input field is populated with selected SKUs and they are separated with comma and a single space. Magento is not stripping this space while creating product search filter. 
Example query:
`SELECT `e`.* FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id = e.entity_id AND product_website.website_id IN(1) WHERE ((e.sku IN('tp1', ' tp2', ' tp3')))`

As per above query tp2 & tp3 won't be included in the result because of space in-front of SKU.

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Jitheesh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by rogyar** [comment]
Hi @Jitheesh.
I cannot reproduce this issue on 2.3-develop. If you select products from the list (upon SKUs selection), the values are being added with ", " as a separator. But once the rule is saved, the separator is trimmed to "," automatically. 
If you try to open and edit the rule by adding the spaces manually - the spaces are trimmed once again after rule saving.

**Condition**
![image](https://user-images.githubusercontent.com/2148959/54021261-023a9300-4190-11e9-8df3-79fd27fa8f3a.png)

**Result**
![image](https://user-images.githubusercontent.com/2148959/54021275-0c5c9180-4190-11e9-98b0-a187531cf9bd.png)

**Comment by Jitheesh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh, here is your [Magento instance](https://i-21618-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21618-2-3-develop.instances.magento-community.engineering/admin](https://i-21618-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jitheesh** [comment]
Hi @rogyar 

I'm not able to replicate this issue on Magento 2.3 develop [instance](https://i-21618-2-3-develop.instances.magento-community.engineering/)  but still I can see this issue on my local 2.3 branch. Maybe this issue is resolved by recent pull requests.

**Comment by rogyar** [comment]
Hi @Jitheesh. Probably it's already fixed. Thank you for your approach, anyway. I'm closing this PR for now

**Comment by VeronikaKurochkina** [comment]
Hello, this issue is still reproduced on 2.4-develop. I faced this issue with condition 'is **NOT** one of' condition.  Space is added
![image](https://user-images.githubusercontent.com/93131106/199699893-b41e89ed-3a68-41e4-ae08-d9c16e62b95a.png)
Condition 'is one of' works fine as expected. 
Could you please have a look at this issue?

**Comment by arjun-tm** [comment]
> Hello, this issue is still reproduced on 2.4-develop. I faced this issue with condition 'is **NOT** one of' condition. Space is added ![image](https://user-images.githubusercontent.com/93131106/199699893-b41e89ed-3a68-41e4-ae08-d9c16e62b95a.png) Condition 'is one of' works fine as expected. Could you please have a look at this issue?

As stated here this issue is still seen when the condition used is 'is **NOT** one of' in a Magento 2.4.5-p7 instance. We had to remove the spaces in between the multiple SKUs entered for the rule to properly work, or else only the first SKU was exempted from the rule.
