### ISSUE TITLE
Payment Method only work for all allowed countries . Its not showing in frontend when its set to specific country configuration from Admin

### ISSUE THREAD

**Issue by paragpadsumbiya** [magento/magento2#21972]
### Preconditions (*)

1. Magento Version 2.2.6
2. PHP Version 7.1.

### Steps to reproduce (*)

1.Login to admin panel
2. Go to Stores >> Configuration >> Sales >> Payment method
3. Edit "Cash On Delivery" method.
4 Set "Payment from Applicable Countries" to Specific Countries and select only NL or any other countries.
5. On Frontend - open checkout and select any allowed country and click NEXT. It will not show Cash On Delivery Payment Method
6. Now Set "Payment from Applicable Countries" to all allowed countries.
7. Now Go to Checkout and select any country then it will show payment methods 

### Expected result (*)

1. Payment Method Show as per the selection of country as per the specific country setting in Backend.

### Actual result (*)

1. Payment Method only show if it select to all allowed countries . Its not showing when its set to specific countries.

**Comment by paragpadsumbiya** [comment]
@orlangur can you please check as well

**Comment by magento-engcom-team** [comment]
Hi @paragpadsumbiya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@paragpadsumbiya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by paragpadsumbiya** [comment]
@magento-engcom-team this is very issue and this issue is on all magento versions even if latest 2.3.0 version. And this is from begginning and not resolved yet.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-21972-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21972-2-3-develop.instances.magento-community.engineering/admin](https://i-21972-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-21972-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21972-2-2-develop.instances.magento-community.engineering/admin](https://i-21972-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@paragpadsumbiya this issue is not reproduceable at magento 2.2-develop and 2.3-develop instance .It seems it is already fixed in earlier versions. Check this on latest magento versions and message here if you are able to reproduce it

**Comment by paragpadsumbiya** [comment]
Hello @shikhamis11 

This issues is still exists in 2.2.6. And here same issue for reference . https://github.com/magento/magento2/issues/10234

Please dont close issue if you are not able to solve it . Until it fixed.

**Comment by paragpadsumbiya** [comment]
@magento-engcom-team @shikhamis11 
please reopen issue.

**Comment by orlangur** [comment]
@paragpadsumbiya please reproduce an issue on provided instance first: https://github.com/magento/magento2/issues/21972#issuecomment-477217502

**Comment by orlangur** [comment]
@paragpadsumbiya,

>  And here same issue for reference ...

We don't need more than one open issue for each bug. I've removed some labels fora an earlier one so that it will be rechecked.

**Comment by paragpadsumbiya** [comment]
@orlangur 
Yes but instance in expired . I have reproduce this issue in our many websites . I have also reported that to Mollie extension developers so they found that this is actually Magento 2 core issues and I have checked same too.
