### ISSUE TITLE
Media Storage does not have separate storages for different stores

### ISSUE THREAD

**Issue by Lealopez95PSF** [magento/magento2#21981]
### Preconditions (*)

1.Magento 2.2.6

### Steps to reproduce (*)

1. Have multiple websites and stores configured.
2. Have an admin user per storeview 
3. Log in as an Store admin (Only access to one storeView)
4. Go to Content --> Blocks.
5. Edit or Create a block.
6. Add an image to the block using WYSIWYG editor.
7. Save Block.
8. Log in as a different admin of another storeview.
9. Go to content --> blocks.
10. Create or Edit a block.
11. Add an image with WYSIWYG editor.

### Expected result (*)

1. See only the images and folders that i've created with the current admin.

### Actual result (*)

1. I can see, use and delete All the images of the different Stores and Websites.
![image](https://user-images.githubusercontent.com/49006402/55116863-89ac5f80-50c7-11e9-89a8-424189a56858.png)

It's supposed that the roles separate perms to admin users. Why does an admin of the store "first store" can use or delete images that the admin of "second store" has uploaded?

**Comment by magento-engcom-team** [comment]
Hi @Lealopez95PSF. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Lealopez95PSF do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Lealopez95PSF** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Lealopez95PSF. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Lealopez95PSF, here is your [Magento instance](https://i-21981-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21981-2-3-develop.instances.magento-community.engineering/admin](https://i-21981-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Lealopez95PSF thank you for you report, this issue has already fixed in 2.3-develop branch, and 2.2-develop branch and available on 2.3.1 and 2.2.8 release.

**Comment by Lealopez95PSF** [comment]
> Hi @Lealopez95PSF thank you for you report, this issue has already fixed in 2.3-develop branch, and 2.2-develop branch and available on 2.3.1 and 2.2.8 release.

I've upgraded from Magento 2.2.6 to 2.2.8 and the issue still there. The files created with one admin, can be seen by other admin from different store views.
