### ISSUE TITLE
Payment methods source model is broken again

### ISSUE THREAD

**Issue by mam08ixo** [magento/magento2#22043]
### Preconditions
1. Magento 2.3.1

### Steps to reproduce
1. Go to _Marketing → Cart Price Rules_.
2. Edit/Open a rule.
3. Under _Conditions_, add the _Cart Attribute_ condition _Payment Method_.
4. Wait for the possible options to load.

### Expected result
1. I see a list of either all or at least the activated payment methods.

### Actual result
1. I see a list with only the payment methods active per *config defaults* (i.e. `checkmo`, `free` and `paypal_billing_agreement`, plus some payment group names).

![payment_method_cart_attribute_options](https://user-images.githubusercontent.com/1771622/55245359-4119b100-5243-11e9-973e-085febfc9616.png)

### Additional Information
The bug was introduced in 28c86be by testing the `active` flag of payment methods in [`\Magento\Payment\Helper\Data::getPaymentMethodList`](https://github.com/magento/magento2/blame/2.3.1/app/code/Magento/Payment/Helper/Data.php#L264) (where `\Magento\Payment\Model\Config\Source\Allmethods::toOptionArray` forwards to).

https://github.com/magento/magento2/blob/28c86bed310311247604caa6c5c3b6c165fbd4f3/app/code/Magento/Payment/Helper/Data.php#L264-L271

Because the source of the data is the default payment method configuration of a plain vanilla installation, no config setting changes (=activating additional methods) are taken into account.

This issue does not only affect the cart price rules. Every extension developer building upon this source model is affected:

#### Source model in Magento 2.3.1
![payment_methods_231](https://user-images.githubusercontent.com/1771622/55246441-80e19800-5245-11e9-8413-1f74939c19d8.png)

#### Source model in Magento 2.3.0
![payment_methods_230](https://user-images.githubusercontent.com/1771622/55246453-850db580-5245-11e9-881f-879cb11c66a7.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98998`, `MAGETWO-98999` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
Hi,

Looks like this issue was fixed in `2.3-develop` branch using following commits:
- https://github.com/magento/magento2/commit/da0c7374e5dcae81735552bdd685ee5e646b8486
- https://github.com/magento/magento2/commit/4344cc9bc34fbda80dc798ebafcf80c516788442

Related comments:
https://github.com/magento/magento2/issues/22231#issuecomment-503750491
https://github.com/magento/magento2/issues/22231#issuecomment-504000986

@engcom-backlog-nazar could you re-check if this issue is reproducing?

Also we're not accepting PRs to 2.2 release line, so we don't need to wait till this issue will be fixed there.

Thank you!

**Comment by engcom-Alfa** [comment]
Hi @ihor-sviziev. Thank you for clarification. The issue was tested and we can confirm that this issue not present in 2.3-develop. I closing as not actual anymore.

**Comment by gewaechshaus** [comment]
Hi,
the same issue is present in 2.2.9. You can temporary fix it be setting the payment method config.xml active flag to 1. 

F.E. for banktransfer

```
<banktransfer>
  <active>1</active>
   ...
```

**Comment by dbartelmus** [comment]
> Hi,
> the same issue is present in 2.2.9. You can temporary fix it be setting the payment method config.xml active flag to 1.
> 
> F.E. for banktransfer
> 
> ```
> <banktransfer>
>   <active>1</active>
>    ...
> ```

1. Path to folder is (composer installation):
`vendor/magento/module-offline-payments/etc/config.xml
`
2. Make changes 0 to 1 to activate payment method ex.
`<banktransfer>
  <active>1</active>
   ...`

Then launch command to apply changes:
```
bin/magento setup:di:compile
bin/magento setup:upgrade
```

Done.

**Comment by uabassguy** [comment]
Why is changing in xml a valid fix but in core_config_data the active flag is set? This is still reproducible on vanilla 2.3.2 with any payment method that does not have active = 1 in xml. If the config is enabled in the database then source does not consider it.

**Comment by uabassguy** [comment]
Seems the real reason this does not work correctly is the payment method instance is coming from a factory create object, which considers xml, but does not check the database to see if the method is enabled. Something needs to be added during the factory object creation which gets config from the database core_config_data payment/<method_code>/active, or other config values as well if those affect anything.
