### ISSUE TITLE
Shipping address information is lost in billing step

### ISSUE THREAD

**Issue by delyriand** [magento/magento2#22112]
### Preconditions (*)

1. Magento 2.3.1 (or Magento 2.2.8)
2. PHP 7.2 (or PHP 7.0)
3. Samples data

### Steps to reproduce (*)

1. Connected with the sample account (roni_cost@example.com / roni_cost3@example.com)
2. Add a product to cart
3. Go to checkout
4. Validate shipping address
5. Uncheck "My billing and shipping address are the same" and choose "New address"
6. Fill the address form (especially postal code) and clic on "Update"

### Expected result (*)

1. "Ship to" information is not modified
2. If back to shipping step, my previously shipping address is selected

### Actual result (*)
1. "Ship to" information is updated with empty values
![image](https://user-images.githubusercontent.com/465524/55392161-0b264680-553b-11e9-8b5d-78424a53bbe6.png)
2. If I return to the shipping step, my shipping address is no longer selected
![image](https://user-images.githubusercontent.com/465524/55392262-3c067b80-553b-11e9-9c70-2b436e8516f2.png)
3. With magento 2.2.8, it is possible to validate shipping step without address

**Comment by delyriand** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @delyriand. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @delyriand, here is your [Magento instance](https://i-22112-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22112-2-3-develop.instances.magento-community.engineering/admin](https://i-22112-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by delyriand** [comment]
I confirm that I reproduce the problem on 2.3-develop branch

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99015`, `MAGETWO-99016` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rikwillems** [comment]
I traced my appearance of this issue, on 2.2.8, to the file vendor/magento/module-checkout/view/frontend/web/js/model/shipping-rates-validator.js line 200.
Commenting this line fixes the issue and doesn't seem to have any other negative effect.

I notice that when being logged in and having an empty local storage the issue appears. After reloading the checkout the selected address remains selected. Also when not being clicked/selected at the first load. Clearing the local storage and reloading the checkout makes the issue appear again. The selected address becomes unselected after a second or so. 

In the network tab two calls are visible when the issue occurs:
rest/default/V1/carts/mine/estimate-shipping-methods-by-address-id
rest/default/V1/carts/mine/estimate-shipping-methods

**Comment by asprada** [comment]
I can confirm that that the same issue appears on 2.3.1 Commerce. It can be reproduced with steps delyriand described.

In my case there's also a popup with an error:
`Carrier with such method not found: %1, %2`

and 404 error from /V1/carts/mine/shipping-information where the billing_address is filled up correctly and the shipping_address has empty values.

**Comment by sjb9774** [comment]
I'm facing this same issue and am trying to find an elegant solution. Tracing the code altered in this PR up to where it is initiated I find `vendor/magento/module-checkout/view/frontend/web/js/model/shipping-rates-validator.js` lines 150-152 being of interest.
```
self.validateAddressTimeout = setTimeout(function () {
    self.validateFields();
}, delay);
```
It seems strange to me that the fields are validated on a timeout rather than on billing address change. Is that strictly necessary? Additionally, `validateFields()` calls `selectShippingAddress(address)` (`vendor/magento/module-checkout/view/frontend/web/js/model/shipping-rates-validator.js` line 198) without checking if the billing and shipping addresses are set to match; why should the shipping address change when the billing address is validated if they aren't even supposed to match? My thought would be to change the code such that `validateFields` is only called when the billing address is updated and only call `selectShippingAddress` if the billing address and shipping address are supposed to match. Is there someone more knowledgeable in this section of the code who can tell me if such a solution makes sense? 

Tagging @sidolov as he was involved in [a closed PR](https://github.com/magento/magento2/pull/23207) to address this issue and may have valuable input.

**Comment by sidolov** [comment]
Hi @sjb9774 , we found an issue with the solution and PR was closed due to inactivity. You may create your own PR with proper solution and we will process it. Thank you!

**Comment by xuanbinh** [comment]
Hi @rikwillems, 
This is function to refresh shipping method.
When you comment it, the website will can't get shipping method when change Postcode. 
Thank you!

**Comment by magento-engcom-team** [comment]
Hi @delyriand, @rsimmons07. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.

**Comment by beamingbaby** [comment]
Hi @magento, @delyriand, @rsimmons07.

We have installed the new release: Magento 2.3.3
but we are still getting the same error:
 "The shipping address is missing. Set the address and try again."

Can you confirm this is fixed?

![image](https://user-images.githubusercontent.com/43178422/66820610-ecb4f500-ef38-11e9-9df9-1881320a164d.png)

**Comment by UKRogue** [comment]
I have this issue on my 2.2.6 installation. Can you confirm the fix is available for 2.2?

**Comment by ron-sooryen** [comment]
Related tickets:
#11958
#6817
#16149
#5959
#13690

**Comment by sureshkantharaj** [comment]
I faced the same issue.

1.rest/default/V1/carts/mine/estimate-shipping-methods 500 Internal Server Error
2.rest/default/V1/carts/guest/estimate-shipping-methods 500 Internal Server Error

<i>At checkout page shipping methods were not displaying. This is issue with Magento_Amqp ,Magento_MysqlMq and Temando_Shipping modules.</i>

<i>I solved this issue by updating composer. First run composer update command.<i>

Run the command below and re-deploy magento.

    composer update
    
    php bin/magento setup:upgrade
    php bin/magento setup:di:compile
    php bin/magento setup:static-content:deploy -f
    php bin/magento cache:flush

**Comment by duckchip** [comment]
I tested the merged PR on 2.2.3 but it did not work unfortunately.
