### ISSUE TITLE
"Estimate Shipping and Tax" data is cleared after click button "Update Shopping Cart"

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#22129]
### Preconditions
1. Magento 2.2.7

### Steps to reproduce
1. Add any product to cart as not logged in customer.
2. Go to "checkout/cart/".
3. Click button "Update Shopping Cart".
![update_shopping_cart](https://user-images.githubusercontent.com/22025597/55472351-2d3bc980-560c-11e9-9520-d5f3bbd056c2.png)

### Expected result
1. Address data in "Estimate Shipping and Tax" persist same like after refresh page.

### Actual result
1. Address data is cleared in "Estimate Shipping and Tax".

### Additional information
1. I can see any changes made to cart automatically reset "Estimate Shipping and Tax" data.

**Comment by ghost** [comment]
Hi @LordHansolo thank you for you report, this issue has already fixed in 2.2.-develop branch and available on 2.2.8 release

**Comment by asprada** [comment]
> Hi @LordHansolo thank you for you report, this issue has already fixed in 2.2.-develop branch and available on 2.2.8 release

Hi @engcom-backlog-nazar, can you provide the pull request to the fix you mentioned? I'm using version 2.3.1 EE and the issue still exist.

**Comment by engcom-Charlie** [comment]
Hello @asprada ! Thank you for your report !
This issue is not present in 2.3.x release line and i was not able to reproduce it .

![Peek 2019-07-18 14-43](https://user-images.githubusercontent.com/51680850/61454968-fc896100-a96a-11e9-8d71-191b483a29d5.gif)
