### ISSUE TITLE
2.3.1 REST-API: order: custom product price not accepted

### ISSUE THREAD

**Issue by Darkwolf81** [magento/magento2#22215]
### Preconditions (*)

1. Magento 2.3.0 / 2.3.1
2. At least 1 product / customer

### Steps to reproduce (*)

1. Create an order with rest api
2. Set custom price in cart_item

### Expected result (*)

1. The given price is used for this product

### Actual result (*)

1. price is ignored / overridden with the original price

I used the same logic in Magento 1, there the custom price is used in the order. In Magento 2 i tried to debug the problem. I saw in a price setter function when the price is set, first the custom price is used, then the function called again with the store price.

I used following code to set the custom price
API: /rest/V1/carts/mine/items

```
$productData = [
    'cart_item' => [
        'quote_id' => $quote_id,
        'sku' => 'J-Park',
        'qty' => 1,
        'price' => '9.0',
        "productOption" => [
            "extensionAttributes" => [
                "customOptions" => [
                    [
                        "optionId" => $option_id,
                        "optionValue" => "My Text"
                    ]
                ]
            ]
        ]
    ]
];
```

**Comment by Darkwolf81** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Darkwolf81. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Darkwolf81, here is your [Magento instance](https://i-22215-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22215-2-3-develop.instances.magento-community.engineering/admin](https://i-22215-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Darkwolf81** [comment]
I could reproduct the issue in vanilla magento. Product price is 17 $, API custom price was 9 $, order is still 17 $.

**Comment by ghost** [comment]
Hi @Darkwolf81, thank you for you report, you can use many ways to set custom price, one of this is observer and plugin.
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="checkout_cart_product_add_after">
        <observer name="customprice" instance="Test\Hello\Observer\CustomPrice" />
    </event>
</config>
```

```
namespaceTest\Hello\Observer;
 
    use Magento\Framework\Event\ObserverInterface;
    use Magento\Framework\App\RequestInterface;
 
    class CustomPrice implements ObserverInterface
    {
        public function execute(\Magento\Framework\Event\Observer $observer) {
            $item = $observer->getEvent()->getData('quote_item');         
            $item = ( $item->getParentItem() ? $item->getParentItem() : $item );
            $price = 100; //set your price here
            $item->setCustomPrice($price);
            $item->setOriginalCustomPrice($price);
            $item->getProduct()->setIsSuperMode(true);
        }
 
    }
```
Thanks for collaboration.

**Comment by Darkwolf81** [comment]
Thanks for this. I tried the code, but it dont work in the rest api, event is not fired.
And i dont understand why this is not a bug. It is possible to tell a price value in the rest order product call. But it is ignored / overridden by the original price.
That worked in Magento 1, and we use this for long time, then it should work in Magento 2, too.

**Comment by teqt** [comment]
I am running into the exact same issue.

How is this not a bug? API's are designed to utilize internal functionality **without** having to create plugins. Second, if that parameter is not supposed to do anything, then why does the parameter exist in the first place? Please, reopen this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99855`, `MAGETWO-99856` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
hi @Darkwolf81 & @teqt , 
while working on this issue I found that there is event available that is called during rest api and with this you can change the price of the product while add to cart in REST API
`<event name="sales_quote_item_set_product"> </event>`

**Comment by jimmy-lion** [comment]
@magento-engcom-team I'm testing this on the 2.3-develop and this is not currently working.  Where can I check tickets MAGETWO-99855 and MAGETWO-99856.  Are they not public? Can you update me on the state of these?  Thanks

@shikhamis11 did you manage to make this work without adding an observer? Thanks

**Comment by fritzmg** [comment]
Has the original issue been fixed at all? Is it possible to set a cart item's price when adding the item via the REST API?

**Comment by danielrona** [comment]
@shikhamis11 
@magento-engcom-team 

Is there any information on when this issue will be fixed?
As  this is still not working with [2.3.3](https://github.com/magento/magento2/tree/2.3.3)

**Comment by skast96** [comment]
This is still an issue in 2.3.5, which is really annoying...

**Comment by 0xMatt** [comment]
bump

**Comment by LeanderFS** [comment]
This issue is also present when creating a negotiable quote (EE module) using the API. 
To circumvent the issue, I've tried a custom API endpoint which explicitly sets the custom_price value when adding items to a quote, but the custom price gets overridden later in the chain. Making it impossible to create an order using custom prices using the API. 

What's the status of internal tickets  `MAGETWO-99856` and `MAGETWO-99855`?

**Comment by 4thePeace2** [comment]
Magento ver. 2.4.2 issue is still present. Can we have V2 with fix in it? 4 years pass...
