### ISSUE TITLE
Enable PayPal Credit option not avaible

### ISSUE THREAD

**Issue by Julen10** [magento/magento2#22243]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Stores > Config > Sales > Payment Methods
2. PayPal Express Checkout > Configure

### Expected result (*)

As in version 2.3.0, it should appear Enable PayPal Credit [YES/NO]

### Actual result (*)

After Merchant Account ID, it doesn´t appear the option.

I have tried this without any results: https://github.com/magento/magento2/issues/10450

**Comment by ghost** [comment]
HI @Julen10 thank you for you report, this is expected behavior,` MC-11034: Enable Paypal Credit option should be disabled/greyed out when a non-US merchant is chosen - Fixed review comments` fixed in this commit.

**Comment by Julen10** [comment]
I´ve download and used that code and still not being able to set Enable Paypal Credit to NO. I have the banner on the website.

**Comment by staywithabhi** [comment]
worst thing about the issue is there is no option in admin to enable or disable but it is showing on frontend product page.Can not disable it permanantly

**Comment by Julen10** [comment]
@staywithabhi that's the key, how to disable something that isn't there? Even if changing the merchant to US I'm not able to view it

**Comment by staywithabhi** [comment]
@Julen10 yes..and paypal credit option is there on product page which is also not working properly and needed to be disabled but there is no option in admin to disable it

**Comment by luctuosa** [comment]
@Julen10 @staywithabhi I can confirm the ability to enable/disable Paypal Credit is no longer an option in my 2.3.1 instance either. However, when I enable In-Context Checkout Experience, Paypal Credit no longer appears on my frontend. Maybe that will help you guys?

**Comment by Julen10** [comment]
@luctuosa Finally, I decided to hide it using css because it was a nonsense configuration...

**Comment by chrischerrett** [comment]
it appears that the Credit option is enabled by default (and shows on the frontend) but you can only disable it by switching your Merchant Country to USA, in order to switch it off. It should be disabled by default.

**Comment by chequille** [comment]
I give my comment as well here, even if the issue is closed, which it should not.

Give us the ability to decide by ourselves whether PayPal credit should be offered or not. This is my decision and not Paypals or Magentos.

Hope more people will see this as I see it.

BR
Jürgen

**Comment by Julen10** [comment]
@chrischerrett Even if I change the Merchant Country to USA, im not able to switch off or see the option.

@chequille You are right, hope we can get this change done. Thanks.

**Comment by chequille** [comment]
I am happy, that somebody is seeing it as I do !!!!!!
BR
Jürgen

**Comment by beachbum12** [comment]
Just found how to switch PayPal Credit option off!!  You need to set your Merchant Country to United States and clear cache. Then go to: 

Basic Settings - Paypal Express Checkout > Advanced Settings > Frontend Experience Settings > Features > Disable Funding Options: Paypal Credit

If you set your Merchant Country to United Kingdom this option disappears and you can't turn it off.

**Comment by Julen10** [comment]
Thanks a lot @beachbum12

**Comment by Detzler** [comment]
Just another workaround to disable paypal credit:

Find row in _core_config_data_ table by _path_ "paypal/style/disable_funding_options". Set/add _value_ to **CREDIT**

Note that resaving config data in the backend payment area will delete the value. Paypal Credit will be active again.

My current magento version: 2.3.2

**Comment by shyam100379** [comment]
@engcom-backlog-nazar regarding "HI @Julen10 thank you for you report, this is expected behavior, MC-11034: Enable Paypal Credit option should be disabled/greyed out when a non-US merchant is chosen - Fixed review comments fixed in this commit."
--- I have tried and its not working like that. If we select merchant as US we do have option to disable credit funding option. Since i am from UK, merchant need to set with UK. Then i have disabled the credit funding in US, then UK is chosen under merchants and checked in frontend= > it is again visible. I think this is a bug, checked in core_config_data like what mentioned in previous comment and i can see its not there. After adding CREDIT in that field, it went invisible. But if we again save anything in payment method, its visible again. This is a bug with 2.3.2.
Kindly address this issue asap. Thanks.

**Comment by edward-simpson** [comment]
Is this still not supported outside of the USA?  I have a UK client looking to use it, and it's very widely used in the UK
