### ISSUE TITLE
Digit in Vendor name throws error in developer mode 

### ISSUE THREAD

**Issue by orionpt** [magento/magento2#22313]
### Preconditions (*)

1. Magento 2.3.1
2. Php 7.1.20
3. Developer mode

### Steps to reproduce (*)

1. Install module with a digit in vendor name
2. do magento setup:upgrade

### Expected result (*)

1. No errors

### Actual result (*)

1. Error

Running schema recurring...Invalid Document 
Element 'indexer', attribute 'class': [facet 'pattern'] The value 'Best4Mage\CPSD\Model\Indexer\SimpleProductUrlRewrites' is not accepted by the pattern '[a-zA-Z\\]+'.
Line: 3

Element 'indexer', attribute 'class': 'Best4Mage\CPSD\Model\Indexer\SimpleProductUrlRewrites' is not a valid value of the atomic type 'classType'.
Line: 3

The error will not be thrown in default mode.

Changing the following files clears the error:
/vendor/magento/framework/Indexer/etc/indexer.xsd
Line 74:
            <xs:pattern value="[a-zA-Z\\]+" />
to
            <xs:pattern value="[a-zA-Z0-9\\]+" />

/vendor/magento/framework/Indexer/etc/indexer_merged.xsd
Line 64:
            <xs:pattern value="[a-zA-Z\\]+" />
to
            <xs:pattern value="[a-zA-Z0-9\\]+" />

/vendor/magento/framework/Indexer/etc/indexer_merged.xsd
Line 58:
            <xs:pattern value="[a-zA-Z\\]+" />
to
            <xs:pattern value="[a-zA-Z0-9\\]+" />

**Comment by jitendra-cedcoss** [comment]
I am working on this at #dmcdindia1

**Comment by KooTjoo** [comment]
Any updates on this? Issue is still there in Magento 2.3.2

**Comment by orlangur** [comment]
Hi @KooTjoo, there are a bunch of places where this regexp needs to be adjusted, will prepare a PR next week so that the fix will become a part of 2.3.3

**Comment by niksjethva** [comment]
Hi orionpt,

You have given the wrong path of last file name as well your pattern also wrong.
Please follow below changes with exact path and changes of Pattern in Magento 2.3.1 :

Changing the following files clears the error:
/vendor/magento/framework/Indexer/etc/indexer.xsd
Line 74:
`<xs:pattern value="[a-zA-Z\\]+" />
to
<xs:pattern value="[a-zA-Z0-9\\]+" />`

/vendor/magento/framework/Indexer/etc/indexer_merged.xsd
Line 64:
`<xs:pattern value="[a-zA-Z\\]+" />
to
<xs:pattern value="[a-zA-Z0-9\\]+" />`

vendor/magento/framework/Mview/etc/mview.xsd
Line 58:
`<xs:pattern value="[a-zA-Z\\]+" />
to
<xs:pattern value="[a-zA-Z0-9\\]+" />`

The last file is mview.xsd. The changed pattern should end with a double slash (`\\`).

Thanks.

**Comment by KooTjoo** [comment]
Hi,

I saw 2.3.3 came out today is this fix implemented?

**Comment by engcom-Delta** [comment]
Hi @orionpt thank you for your report. I am not able to reproduce issue by steps you described on  2.3-develop.
![#22313issue](https://user-images.githubusercontent.com/51681379/66909185-fb70da00-f014-11e9-9d93-805044c1a4b8.png)

If you'd like to update issue, please reopen it.

**Comment by KooTjoo** [comment]
This issue is still present in Magento 2.3.4 CE. I tried to install extension and got this:

Element 'indexer', attribute 'class': [facet 'pattern'] The value 'Best4Mage\UCPS\Model\Indexer\SimpleProductUrlRewrites' is not accepted by the pattern '[a-zA-Z\\]+'.
Line: 3

Element 'indexer', attribute 'class': 'Best4Mage\UCPS\Model\Indexer\SimpleProductUrlRewrites' is not a valid value of the atomic type 'classType'.
Line: 3

**Comment by prabhacse09** [comment]
Hi @KooTjoo 

Magento 2.3.4 CE still has the issue on the below file.

/vendor/magento/framework/Indexer/etc/indexer_merged.xsd

Open the file and edit Line 64:
from
`<xs:pattern value="[a-zA-Z\\]+" /> `
to 
`<xs:pattern value="[a-zA-Z|\\]+[a-zA-Z0-9\\]+" />`

**Comment by KooTjoo** [comment]
Hi,

Thank you I know how to fix it, but I thought this bug was solved.

**Comment by orionpt** [comment]
This problem is still present in 2.3.5p1. Can this issue be re-opened or should a new one be created?

**Comment by jorgb90** [comment]
I can confirm the problem is still there in 2.3.5-p1

**Comment by KooTjoo** [comment]
Issue is still there. It really is unbelievable that this can't be solved indefinitely. Issue is there through versions for over 1 year now.

**Comment by kovinet** [comment]
I have same issue with Magneto 2.4. too.

**Comment by jorgb90** [comment]
@magento-engcom-team reopen? Easy fix so please publish it in the next release!

**Comment by vandark25** [comment]
Any update ? @magento-engcom-team
