### ISSUE TITLE
Rest API Magento 2.4 order update overwrites existing item information

### ISSUE THREAD

**Issue by aschrammel** [magento/magento2#22431]
### Preconditions (*)
magento 2.4-develop

### Steps to reproduce (*)
1. Place an order with a product with custom option.
2. On the order item in the database the custom options are stored in the `sales_order_item` table, `product_options` field in the `info_buyRequest` as "key": "value" pair.
3. Update the order using the Rest API (f.e. just hold order).

4. The `product_options` are manipulated, omitting the custom options (they are present as `options` as object, but missing in the `info_buy_request` as "key": "value" pair.

### Expected result (*)
The  `info_buyRequest` remain as they were before the API Update
![image](https://user-images.githubusercontent.com/51680850/83511195-f6df3000-a4d6-11ea-8a89-5ea1d43d025e.png)

### Actual result (*)
The  `info_buyRequest` data are changed
![image](https://user-images.githubusercontent.com/51680850/83511277-12e2d180-a4d7-11ea-92f9-b0e26e053f76.png)

**Comment by aschrammel** [comment]
@magento-engcom-team It's not possible to reproduce on remote instance, as I don't have database access to this instance.

**Comment by ghost** [comment]
Hi @aschrammel thank you for you report, this issue has already ben fixed in this -> commit https://github.com/magento/magento2/commit/7c6ecc33bf6d5707021548e0920650b7feec265c

**Comment by aschrammel** [comment]
Hi @engcom-backlog-nazar,

thanks for your feedback but unfortunately the fix you mentioned does not fix the problem described.
The custom options stored in the `info_buyRequest` as `options` object with it's corresponding ID but not - as it's done before the update - as textual key and value.

E.g. i have on in the the `product_options` field in `sales_order_item`table something like this:
```
{
    "info_buyRequest": {
        "uenc": "XXX",
        "product": "XXX",
        "serial_number": "XXX",
        "country": "AT",
        "max_qty": "1",
        "related_product": "",
        "qty": "1",
        "options": {
            "17": "XXX",
            "18": "AT"
        }
    },
    "options": [
        {
            "label": "Seriennummer",
            "value": "XXX",
            "print_value": "XXX",
            "option_id": "17",
            "option_type": "field",
            "option_value": "XXX",
            "custom_view": false
        },
        {
            "label": "Installationsland",
            "value": "AT",
            "print_value": "AT",
            "option_id": "18",
            "option_type": "field",
            "option_value": "AT",
            "custom_view": false
        }
    ]
}
```

After updating the order via the API the `product_options` field in `sales_order_item` is contains following:
```
{
    "info_buyRequest": {
        "qty": "1.0000",
        "options": {
            "17": "XXX",
            "18": "AT"
        }
    },
    "options": [
        {
            "label": "Seriennummer",
            "value": "XXX",
            "print_value": "XXX",
            "option_id": "17",
            "option_type": "field",
            "option_value": "XXX",
            "custom_view": false
        },
        {
            "label": "Installationsland",
            "value": "AT",
            "print_value": "AT",
            "option_id": "18",
            "option_type": "field",
            "option_value": "AT",
            "custom_view": false
        }
    ]
}
```

For us it is not an option to rely on the option IDs or the `options` array as for the same content (Serial / Installation Country) various IDs and labels in different languages exist.

So the issue in this case are the missing data in `info_buyRequest`:
```
"uenc": "XXX",
"product": "XXX",
"serial_number": "XXX",
"country": "AT",
"max_qty": "1",
"related_product": "",
```

After placing the order the data is stored on the item correctly - it's only missing after updating the order via API.

I hope it's more clear now.
Thank you in advance :)

**Comment by aschrammel** [comment]
Additionally maybe interesting is the fact, that this happens on virutal products!
As far as I've seen now, there's no `ProductOptionProcessor` for virtuals.

**Comment by dkyosev9** [comment]
Same issue here. Seems like very major/important issue. It works good with Simple but not with Bundle products.

### Preconditions (*)
Magento Version 2.3.1

### Steps to reproduce (*)
    Place an order with a bundle product with custom options
    On the order item in the database the custom options are stored in the product_options column in the info_buyRequest as "key": "value" pair.
    Ship the order from the admin order edit screen or when add a comment and save the order programmatically.
    The product_options are manipulated, omitting the custom options and keeps some new "key": "value" pairs. Most of the `info_buy_request` "key": "value" pairs are missing.

### Expected result (*)
The product_options remain as they were before the order state update

### Actual result (*)
Missing custom options in the product_options column (`sales_order` table).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21450` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kevinjavitz** [comment]
Here is a temp fix if you need to use the item saving api using a preference, if you rely on updating the product_options in the api this will not work though: https://gist.github.com/salesigniter/967f594a7ab34c6f73162e4e92fd34fb

**Comment by magento-engcom-team** [comment]
Hi @aschrammel. Thank you for your report. 
The issue has been fixed in magento/magento2#28483 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [a922551cedec33ab3f831590fa5c5a97ff90d470](https://github.com/magento/magento2/commit/a922551cedec33ab3f831590fa5c5a97ff90d470)
 - [beb41d03ca35b6a423f546f31149df57124475bb](https://github.com/magento/magento2/commit/beb41d03ca35b6a423f546f31149df57124475bb)
 - [3115fe9aca02e3de26163921493bf7a103ea62fe](https://github.com/magento/magento2/commit/3115fe9aca02e3de26163921493bf7a103ea62fe)
 - [15d20cb39f5143aed71f10b7310c38a180f50a14](https://github.com/magento/magento2/commit/15d20cb39f5143aed71f10b7310c38a180f50a14)
 - [ae36ae4cc8f07d8573acf63ed01082715f00c433](https://github.com/magento/magento2/commit/ae36ae4cc8f07d8573acf63ed01082715f00c433)

The fix will be available with the upcoming 2.4.1 release.
