### ISSUE TITLE
Wrong currency sign on creditmemo_grid & sales_order_view > invoice grid

### ISSUE THREAD

**Issue by latenights** [magento/magento2#22490]
### Preconditions (*)

1. Magento 2.3 
2. Magento 2.2

### Steps to reproduce (*)

1. Create order in different currency as configured on default store view
2. Go to Backend > SALES > Credit Memos, create Credit Memo
3. Check Refunded & Subtotal column on Credit Memo grid (sales_creditmemo_index). You should see price in currency configured on default store view (base_currency_code).
4. Go to Backend > SALES > Orders > choose your order and check Invoice grid in Invoices tab. Amount should be base grand total with base_currency_code.

### Expected result (*)

1. Display same price on sales_order_view _credit memo_ & _invoice_ grid. With correct currency sign.
2. Display correct currency & amount on sales_creditmemo_index.

### Actual result (*)

1. sales_order_view > Credit Memos (base grand total):
![image](https://user-images.githubusercontent.com/5650354/56719356-d758ce00-6740-11e9-8972-91adec7c56f8.png)
2. sales_order_view > Invoices (grand total):
![image](https://user-images.githubusercontent.com/5650354/56719369-df187280-6740-11e9-8585-9ddc7eb35461.png)
3. sales_creditmemo_index (wrong currency sign):
![image](https://user-images.githubusercontent.com/5650354/56719386-e770ad80-6740-11e9-94df-acd54bceed7d.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99399`, `MAGETWO-99400` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by latenights** [comment]
Also reproducible on M2.2.5 #22114

**Comment by magento-engcom-team** [comment]
Hi @latenights. Thank you for your report. 
The issue has been fixed in magento/magento2#22123 by @latenights in 2.3-develop branch
Related commit(s):
 - [da3282935c5e97ff54aca034e9a5ab08dc210081](https://github.com/magento/magento2/commit/da3282935c5e97ff54aca034e9a5ab08dc210081)
 - [31427763b4a1e877adf18c098580dd3a9eb70791](https://github.com/magento/magento2/commit/31427763b4a1e877adf18c098580dd3a9eb70791)
 - [18a6653e3fa419331c1909dfdb38ec8e402d1502](https://github.com/magento/magento2/commit/18a6653e3fa419331c1909dfdb38ec8e402d1502)
 - [6833c61c4b6183065ed4d0d55d7facce9a8a8e27](https://github.com/magento/magento2/commit/6833c61c4b6183065ed4d0d55d7facce9a8a8e27)
 - [ae304acdf0cf567add3b5d501a64fe4605877574](https://github.com/magento/magento2/commit/ae304acdf0cf567add3b5d501a64fe4605877574)
 - [4bda471ee4bb32a109bdf564afe7716ebb79d767](https://github.com/magento/magento2/commit/4bda471ee4bb32a109bdf564afe7716ebb79d767)

The fix will be available with the upcoming 2.3.4 release.

**Comment by umarch06** [comment]
That issue is still happening for me on magento 2.3.5-p2. I upgraded from 2.3.3 to 2.3.5-p2.
![Uploading Screenshot 2020-10-14 at 4.52.05 PM.png…]()
 Here are the screenshots:

**Comment by cstergianos** [comment]
@magento-engcom-team could you please re-open this issue? It is happening again on: 2.3.5-p2:

![image](https://user-images.githubusercontent.com/25661926/97166562-5d623480-177d-11eb-85e8-1c1b2b19531e.png)

**Comment by nalinsavaliya** [comment]
Also, this issue happens in Magento 2.4.1

**Comment by sudma** [comment]
I can also confirm issue still happens in Magento 2.4.1.

**Comment by sprajapat770** [comment]
I also confirmed this issue is still exist in magento 2.4.2 Despite magento community try to solve in 2.4.2
