### ISSUE TITLE
Can't access backend without base redirect

### ISSUE THREAD

**Issue by kassner** [magento/magento2#2272]
Hi,

If we use `Auto-redirect to Base URL` as `No` and we can't validate the Base URL for that installation (like Magento is behing a proxy), it's not possible to access the backend (returns a store's 404 page). That happens when the `Host` header is not the same as defined in `web/unsecure/base_url`. We still are able to navigate in the frontend.

Tested version: 2.0.0-rc

Thanks!

**Comment by arkadiych** [comment]
Internally tracking - MAGETWO-45105

**Comment by muasir** [comment]
Internal ticket created MAGETWO-45105

**Comment by dfediuk** [comment]
The solution: http://magento.stackexchange.com/a/89157/18793

**Comment by mazhalai** [comment]
@kassner Please try again, this has been fixed in RC2.

**Comment by KrystynaKabannyk** [comment]
Hello @kassner, this issue has been fixed in the 2.1.0 Release. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by kassner** [comment]
@KrystynaKabannyk can you point me to the commit who fixes this issue? I still experience this problem when I use the latest commit in develop branch (989af631d7ea7365f694e5cb0003a94ab49eb54d).

Thanks!
