### ISSUE TITLE
After upgrading to new version - No such entity with customerId critical logs

### ISSUE THREAD

**Issue by chequille** [magento/magento2#23411]
### Summary
Sorry to say this, but as usually, after upgrading Magento versions something is wrong at the end.
I did have no exceptions and no errors before.
Now upgrading to 2.3.2 I get exceptions like:
`[2019-06-25 21:46:34] main.CRITICAL: Keine Eintrag mit customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): Keine Eintrag mit customerId = 1 at /var/www/vhosts/hopfenmuseum-tettnang.de/magento.hopfenexpress.de/vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []`

### Preconditions

Magento 2.3.2
PHP 7.2
 
### Steps to reproduce
1. Setup vanilla Magento 2.3.2 using composer (no sample data is needed)
2. In the backend, create a category and a product
3. In the frontend, register as a new customer
4. Put the product in your cart and go to the checkout
5 .Enter your shipping address and use the same address in the payment step
6. Place an order
7. Look at the var/log/exception.log file, it contains 4 errors:
```
[2019-06-29 14:34:05] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:06] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:08] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:08] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
```
8. Go to the home page or any other page while still being logged in
9. An additional line is added to the `var/log/exception.log` file each time you visit a page:
```
[2019-06-29 14:36:58] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
```

### Expected result 
No errors

### Actual result
[2019-06-29 14:34:05] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:06] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:08] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:08] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []

### Additional information
From the [comment](https://github.com/magento/magento2/issues/23411#issuecomment-506961956)

This last one seems to come from the ajax request to `/customer/section/load/?sections=cart&force_new_section_timestamp=false&_=1561818997600`

Putting a break point in that `NoSuchEntityException.php` file on line 50 and then calling that ajax endpoint, gives me the following stack trace:
```
Magento\Framework\Exception\NoSuchEntityException::singleField (vendor/magento/framework/Exception/NoSuchEntityException.php:50)
Magento\Quote\Model\QuoteRepository\Interceptor->loadQuote (vendor/magento/module-quote/Model/QuoteRepository.php:232)
Magento\Quote\Model\QuoteRepository\Interceptor->getForCustomer (vendor/magento/module-quote/Model/QuoteRepository.php:149)
Magento\Quote\Model\QuoteRepository\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Quote\Model\QuoteRepository\Interceptor->getForCustomer (generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php:39)
Magento\Quote\Model\QuoteRepository\Interceptor->getActiveForCustomer (vendor/magento/module-quote/Model/QuoteRepository.php:174)
Magento\Quote\Model\QuoteRepository\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Quote\Model\QuoteRepository\Interceptor->getActiveForCustomer (generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php:65)
Magento\Checkout\Model\Session\Interceptor->getQuote (vendor/magento/module-checkout/Model/Session.php:274)
Magento\Checkout\Model\Session\Interceptor->getQuote (generated/code/Magento/Checkout/Model/Session/Interceptor.php:63)
Magento\Checkout\CustomerData\Cart\Interceptor->getQuote (vendor/magento/module-checkout/CustomerData/Cart.php:116)
Magento\Checkout\CustomerData\Cart\Interceptor->getSectionData (vendor/magento/module-checkout/CustomerData/Cart.php:91)
Magento\Checkout\CustomerData\Cart\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Checkout\CustomerData\Cart\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Checkout\CustomerData\Cart\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Checkout\CustomerData\Cart\Interceptor->getSectionData (generated/code/Magento/Checkout/CustomerData/Cart/Interceptor.php:26)
Magento\Customer\CustomerData\SectionPool->getSectionDataByNames (vendor/magento/module-customer/CustomerData/SectionPool.php:79)
Magento\Customer\CustomerData\SectionPool->getSectionsData (vendor/magento/module-customer/CustomerData/SectionPool.php:60)
Magento\Customer\Controller\Section\Load\Interceptor->execute (vendor/magento/module-customer/Controller/Section/Load.php:78)
Magento\Customer\Controller\Section\Load\Interceptor->execute (generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php:24)
Magento\Customer\Controller\Section\Load\Interceptor->dispatch (vendor/magento/framework/App/Action/Action.php:108)
Magento\Customer\Controller\Section\Load\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Customer\Controller\Section\Load\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Customer\Controller\Section\Load\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Customer\Controller\Section\Load\Interceptor->dispatch (generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php:39)
Magento\Framework\App\FrontController\Interceptor->processRequest (vendor/magento/framework/App/FrontController.php:159)
Magento\Framework\App\FrontController\Interceptor->dispatch (vendor/magento/framework/App/FrontController.php:99)
Magento\Framework\App\FrontController\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch (vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:135)
Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch (vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:135)
Magento\Framework\App\FrontController\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Framework\App\FrontController\Interceptor->dispatch (generated/code/Magento/Framework/App/FrontController/Interceptor.php:26)
Magento\Framework\App\Http\Interceptor->launch (vendor/magento/framework/App/Http.php:137)
Magento\Framework\App\Http\Interceptor->launch (generated/code/Magento/Framework/App/Http/Interceptor.php:24)
Magento\Framework\App\Bootstrap->run (vendor/magento/framework/App/Bootstrap.php:261)
{main} (pub/index.php:40)
```

I'm not sure how important this problem is and what is breaks exactly. But it doesn't sound very good..

**Comment by chohanbhagchand** [comment]
I am working on this at #dmcdindia19”

**Comment by engcom-Charlie** [comment]
Hello @chequille ! Thank you for report !
Any 3rd party modules/extensions installed ?

**Comment by chequille** [comment]
Yes, of course some third party modules.
And as well own stuff.
Ok, my own stuff does not access customer classes. So I guess these are not the reason for this exception.

Regarding German Law regulations and privacy I am using "mageplaza module-gdpr". This is some customer related stuff.

How can I find out which extension is causing the exception?

Is there a way to find out?

**Comment by engcom-Charlie** [comment]
Hello @chequille !
Please provide more information about this issue , some steps to reproduce it . Also did you try to reproduce this issue on Vanilla Magento instance ?

**Comment by chequille** [comment]
Hello,
sorry, but I do not relly know what to do with vanilla instance, because I do not know how to install a third party or my own modules.
I thougth this is a test environment for Magento stuff only.

Therefor, I cannot provide more information on this issue.

But what about my question: is there a way to find which module is causing the exception?

**Comment by chequille** [comment]
More information:
I found the point after the exception occurs. It is after placing the order.
Strange is, that the order is placed, but the error in exception.log

I activated my backup of all files and installed my database backup. So, I am again on 2.3.1.
THe exception does not occur as it is in 2.3.2

No extension was change, everything the same except Magento version.

Maybe this help you to have an idea where this happesn now.

Regards,
Chequille

**Comment by Ctucker9233** [comment]
@chequille Have you reached out to mageplaza to see if they have an updated version of that module for 2.3.2? It could be that something has changed between 2.3.1 and 2.3.2 that breaks the extension.

**Comment by chequille** [comment]
Hi Ctucker,
the problem is, that it seems everything is working. Order is placed etc. Everything is fine in the frontend.
As well in the backend. EMails sent etc.

But in the exception.log there is the error.
Mageplaza-gdpr module was just a guess. The module does not influence the checkout process, so I really do not believe, that this is the reason for.

So, if there is no other way to find out which part of the system is causing the error, I do have to disbale one module by the other till I find the point where the exception is not there anymore.

Nice work !?!?!?!?!?!?!?!

Ok, but if nobody does have another idea, I will finally do it like this.

Best regards,
Chequille

**Comment by Ctucker9233** [comment]
@chequille That's exactly what Magento documentation recommends is to disable extensions one by one. A pain in the neck to be sure. you could also try running CLI Commands:
php bin/magento indexer:reset
php bin/magento indexer:reindex
php bin/magento cache:clean

Was there any kind of stack trace that followed after the error in the log?

**Comment by chequille** [comment]
Hi Guys,
deactivated all third party extensions/modules and it still happens.
To answer the question: no stack trace following the error in the log file. It is only the line with saying "No entry for CustomerID = 1" 
Of course, if I am logged in with another customer, it says "No entry for CustomerID = 44" f.e.

What I did not try is using a standard Magento Theme like Luma. WIll do that later.

Any other ideas?

**Comment by chequille** [comment]
Hi Everybody,
just made a fresh new installation on my local computer. Installed the sample data and created a new customer and placed an order.
The exception is as well in the exception.log
[2019-06-29 11:59:31] main.CRITICAL: No such entity with customerId = 2 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 2 at D:\\Internetseiten\\Web Magento2.3\\vendor\\magento\\framework\\Exception\\NoSuchEntityException.php:50)"} []

So, this is a bug in Magento and not in one of my used extensions/modules.
THis exception was not in version 2.3.1
It is now happening with version 2.3.2

So, please have a look at this.
Regards
Chequille

**Comment by hostep** [comment]
@chequille: thanks for the effort to keep testing this problem! I was able to very easily reproduce the problem based on your comments:

1. Setup vanilla Magento 2.3.2 using composer (no sample data is needed)
2. In the backend, create a category and a product
3. In the frontend, register as a new customer
4. Put the product in your cart and go to the checkout
5. Enter your shipping address and use the same address in the payment step
6. Place an order
7. Look at the `var/log/exception.log` file, it contains 4 errors:
```
[2019-06-29 14:34:05] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:06] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:08] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
[2019-06-29 14:34:08] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
```
8. Go to the home page or any other page while still being logged in
9. An additional line is added to the `var/log/exception.log` file each time you visit a page:
```
[2019-06-29 14:36:58] main.CRITICAL: No such entity with customerId = 1 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with customerId = 1 at vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []
```

This last one seems to come from the ajax request to `/customer/section/load/?sections=cart&force_new_section_timestamp=false&_=1561818997600`

Putting a break point in that `NoSuchEntityException.php` file on line 50 and then calling that ajax endpoint, gives me the following stack trace:
```
Magento\Framework\Exception\NoSuchEntityException::singleField (vendor/magento/framework/Exception/NoSuchEntityException.php:50)
Magento\Quote\Model\QuoteRepository\Interceptor->loadQuote (vendor/magento/module-quote/Model/QuoteRepository.php:232)
Magento\Quote\Model\QuoteRepository\Interceptor->getForCustomer (vendor/magento/module-quote/Model/QuoteRepository.php:149)
Magento\Quote\Model\QuoteRepository\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Quote\Model\QuoteRepository\Interceptor->getForCustomer (generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php:39)
Magento\Quote\Model\QuoteRepository\Interceptor->getActiveForCustomer (vendor/magento/module-quote/Model/QuoteRepository.php:174)
Magento\Quote\Model\QuoteRepository\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Quote\Model\QuoteRepository\Interceptor->getActiveForCustomer (generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php:65)
Magento\Checkout\Model\Session\Interceptor->getQuote (vendor/magento/module-checkout/Model/Session.php:274)
Magento\Checkout\Model\Session\Interceptor->getQuote (generated/code/Magento/Checkout/Model/Session/Interceptor.php:63)
Magento\Checkout\CustomerData\Cart\Interceptor->getQuote (vendor/magento/module-checkout/CustomerData/Cart.php:116)
Magento\Checkout\CustomerData\Cart\Interceptor->getSectionData (vendor/magento/module-checkout/CustomerData/Cart.php:91)
Magento\Checkout\CustomerData\Cart\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Checkout\CustomerData\Cart\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Checkout\CustomerData\Cart\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Checkout\CustomerData\Cart\Interceptor->getSectionData (generated/code/Magento/Checkout/CustomerData/Cart/Interceptor.php:26)
Magento\Customer\CustomerData\SectionPool->getSectionDataByNames (vendor/magento/module-customer/CustomerData/SectionPool.php:79)
Magento\Customer\CustomerData\SectionPool->getSectionsData (vendor/magento/module-customer/CustomerData/SectionPool.php:60)
Magento\Customer\Controller\Section\Load\Interceptor->execute (vendor/magento/module-customer/Controller/Section/Load.php:78)
Magento\Customer\Controller\Section\Load\Interceptor->execute (generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php:24)
Magento\Customer\Controller\Section\Load\Interceptor->dispatch (vendor/magento/framework/App/Action/Action.php:108)
Magento\Customer\Controller\Section\Load\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Customer\Controller\Section\Load\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Customer\Controller\Section\Load\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Customer\Controller\Section\Load\Interceptor->dispatch (generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php:39)
Magento\Framework\App\FrontController\Interceptor->processRequest (vendor/magento/framework/App/FrontController.php:159)
Magento\Framework\App\FrontController\Interceptor->dispatch (vendor/magento/framework/App/FrontController.php:99)
Magento\Framework\App\FrontController\Interceptor->___callParent (vendor/magento/framework/Interception/Interceptor.php:58)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:138)
Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch (vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:135)
Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch (vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73)
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure:vendor/magento/framework/Interception/Interceptor.php:104-151} (vendor/magento/framework/Interception/Interceptor.php:135)
Magento\Framework\App\FrontController\Interceptor->___callPlugins (vendor/magento/framework/Interception/Interceptor.php:153)
Magento\Framework\App\FrontController\Interceptor->dispatch (generated/code/Magento/Framework/App/FrontController/Interceptor.php:26)
Magento\Framework\App\Http\Interceptor->launch (vendor/magento/framework/App/Http.php:137)
Magento\Framework\App\Http\Interceptor->launch (generated/code/Magento/Framework/App/Http/Interceptor.php:24)
Magento\Framework\App\Bootstrap->run (vendor/magento/framework/App/Bootstrap.php:261)
{main} (pub/index.php:40)
```

I'm not sure how important this problem is and what is breaks exactly. But it doesn't sound very good...

@engcom-Charlie: can you also test this again?

**Comment by magento-engcom-team** [comment]
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17913` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by southerncomputer** [comment]
This is normal due to loadQuote throwing an exception when no cart/quote exists for the customerId
``` php
 protected function loadQuote($loadMethod, $loadField, $identifier, array $sharedStoreIds = [])
    {
        /** @var CartInterface $quote */
        $quote = $this->cartFactory->create();
        if ($sharedStoreIds && method_exists($quote, 'setSharedStoreIds')) {
            $quote->setSharedStoreIds($sharedStoreIds);
        }
        $quote->setStoreId($this->storeManager->getStore()->getId())->$loadMethod($identifier);
        if (!$quote->getId()) {
            throw NoSuchEntityException::singleField($loadField, $identifier);
        }
        return $quote;
    }

```

**Comment by GordonLesti** [comment]
@southerncomputer Yes, the quote exists, but it is not active anymore at the moment. But this is not normal, cause the order has not been placed yet.

**Comment by chequille** [comment]
Hi Guys,
just a small comment from my site:
Be aware, the eception was not thrown in version 2.3.1.
Therefore, it must be a bug in 2.3.2
Regards,
Chequille

**Comment by southerncomputer** [comment]
It is because there is no quote! I just showed you the routine above! No Quote means when customer-data is called it cannot load the quote that does not exist! Whether this was changed in 2.3.2 i don't know but i've been working around this bug for the last day or so since it messes up onestepcheckout when the quote structure is not existing already!

**Comment by ky2vell** [comment]
I upgraded to 2.3.2 locally and am experiencing this bug as well.  Anyone come up with a solution?  Unknown exceptions cropping up right at the point of sale isn’t exactly comforting.

**Comment by chequille** [comment]
Everybody is facing this problem, because it is a core bug !!!!!
Sorry to the Magento team, but I really cannot understand this. Updates should fix bugs and security stuff, but not introduce new bugs.
I like the system anyway, but sometimes it is really strange what happens.

Nevertheless, do your best to fix this soon. I am waiting !!
BR
Chequille

**Comment by hmphu** [comment]
I'm faced this issue also, Does anybody have a fix?

**Comment by david-fuehr** [comment]
The commit https://github.com/magento/magento2/commit/117d7103de2989168af45de550091e79f815d54e improved quote (error) handling but also introduced a log that is wrong in my opinion. It was first delivered with 2.3.2.

Line 276 from that commit logs a critical error, when a `\Magento\Framework\Exception\NoSuchEntityException` occurs. Inspecting the context of that line, this should not be done:
`\Magento\Checkout\Model\Session.php:268-283`
```PHP
if (!$this->getQuoteId()) {
    if ($this->_customerSession->isLoggedIn() || $this->_customer) {
        $customerId = $this->_customer
            ? $this->_customer->getId()
            : $this->_customerSession->getCustomerId();
        try {
            $quote = $this->quoteRepository->getActiveForCustomer($customerId);
            $this->setQuoteId($quote->getId());
        } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
            $this->logger->critical($e);
        }
    } else {
        $quote->setIsCheckoutCart(true);
        $this->_eventManager->dispatch('checkout_quote_init', ['quote' => $quote]);
    }
}
```
The whole method could use some (or some more) refactoring, but this block should get the last *active* quote for a customer. Especially after placing an order and before adding products to a new quote, there is never an active quote for a customer. Therefore (with the least impact to the method) the line 277 `$this->logger->critical($e);` should be dropped.

I will prepare a pull request for this.

*Additional information:* the critical log is actually a false positive - nothing is wrong except the log entry itself.

**Comment by Userr017** [comment]
@david-fuehr 

This fixes reported issue?[https://github.com/magento/magento2/commit/117d7103de2989168af45de550091e79f815d54e](url)

**Comment by fritzmg** [comment]
Is this issue still on the radar of the Magento developers? Because the [PR](https://github.com/magento/magento2/pull/23952) of @david-fuehr was closed due to inactivity... and it's very annoying to have the exception log flooded with this message. Makes it inconvenient to find _real_ exceptions.

**Comment by uabassguy** [comment]
@fritzmg I use this to filter out that exception to find others, not a real fix but it helps for now.

`cat var/log/exception.log | grep -v customerId`

**Comment by samumaretiya** [comment]
Hi @hostep & @chequille & @david-fuehr ,

I've recently upgraded from Magento 2.2.6 to Magento 2.3.2. I can see that you guys have made a patch to resolve the No such entity with customerId but it just doesn't work yet.

See the code base for session.php that I have. I'd really appreciate any suggestions to fix it or quick help.

`<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magento\Checkout\Model;

use Magento\Customer\Api\Data\CustomerInterface;
use Magento\Framework\App\ObjectManager;
use Magento\Quote\Model\Quote;
use Magento\Quote\Model\QuoteIdMaskFactory;
use Psr\Log\LoggerInterface;

/**
 * Represents the session data for the checkout process
 *
 * @api
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CookieAndSessionMisuse)
 * @since 100.0.2
 */
class Session extends \Magento\Framework\Session\SessionManager
{
    /**
     * Checkout state begin
     */
    const CHECKOUT_STATE_BEGIN = 'begin';

    /**
     * Quote instance
     *
     * @var Quote
     */
    protected $_quote;

    /**
     * Customer Data Object
     *
     * @var CustomerInterface|null
     */
    protected $_customer;

    /**
     * Whether load only active quote
     *
     * @var bool
     */
    protected $_loadInactive = false;

    /**
     * Loaded order instance
     *
     * @var \Magento\Sales\Model\Order
     */
    protected $_order;

    /**
     * @var \Magento\Sales\Model\OrderFactory
     */
    protected $_orderFactory;

    /**
     * @var \Magento\Customer\Model\Session
     */
    protected $_customerSession;

    /**
     * @var \Magento\Quote\Api\CartRepositoryInterface
     */
    protected $quoteRepository;

    /**
     * @var \Magento\Framework\HTTP\PhpEnvironment\RemoteAddress
     */
    protected $_remoteAddress;

    /**
     * @var \Magento\Framework\Event\ManagerInterface
     */
    protected $_eventManager;

    /**
     * @var \Magento\Store\Model\StoreManagerInterface
     */
    protected $_storeManager;

    /**
     * @var \Magento\Customer\Api\CustomerRepositoryInterface
     */
    protected $customerRepository;

    /**
     * @param QuoteIdMaskFactory
     */
    protected $quoteIdMaskFactory;

    /**
     * @param bool
     */
    protected $isQuoteMasked;

    /**
     * @var \Magento\Quote\Model\QuoteFactory
     */
    protected $quoteFactory;

    /**
     * @var LoggerInterface|null
     */
    private $logger;

    /**
     * @param \Magento\Framework\App\Request\Http $request
     * @param \Magento\Framework\Session\SidResolverInterface $sidResolver
     * @param \Magento\Framework\Session\Config\ConfigInterface $sessionConfig
     * @param \Magento\Framework\Session\SaveHandlerInterface $saveHandler
     * @param \Magento\Framework\Session\ValidatorInterface $validator
     * @param \Magento\Framework\Session\StorageInterface $storage
     * @param \Magento\Framework\Stdlib\CookieManagerInterface $cookieManager
     * @param \Magento\Framework\Stdlib\Cookie\CookieMetadataFactory $cookieMetadataFactory
     * @param \Magento\Framework\App\State $appState
     * @param \Magento\Sales\Model\OrderFactory $orderFactory
     * @param \Magento\Customer\Model\Session $customerSession
     * @param \Magento\Quote\Api\CartRepositoryInterface $quoteRepository
     * @param \Magento\Framework\HTTP\PhpEnvironment\RemoteAddress $remoteAddress
     * @param \Magento\Framework\Event\ManagerInterface $eventManager
     * @param \Magento\Store\Model\StoreManagerInterface $storeManager
     * @param \Magento\Customer\Api\CustomerRepositoryInterface $customerRepository
     * @param QuoteIdMaskFactory $quoteIdMaskFactory
     * @param \Magento\Quote\Model\QuoteFactory $quoteFactory
     * @param LoggerInterface|null $logger
     * @throws \Magento\Framework\Exception\SessionException
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     */
    public function __construct(
        \Magento\Framework\App\Request\Http $request,
        \Magento\Framework\Session\SidResolverInterface $sidResolver,
        \Magento\Framework\Session\Config\ConfigInterface $sessionConfig,
        \Magento\Framework\Session\SaveHandlerInterface $saveHandler,
        \Magento\Framework\Session\ValidatorInterface $validator,
        \Magento\Framework\Session\StorageInterface $storage,
        \Magento\Framework\Stdlib\CookieManagerInterface $cookieManager,
        \Magento\Framework\Stdlib\Cookie\CookieMetadataFactory $cookieMetadataFactory,
        \Magento\Framework\App\State $appState,
        \Magento\Sales\Model\OrderFactory $orderFactory,
        \Magento\Customer\Model\Session $customerSession,
        \Magento\Quote\Api\CartRepositoryInterface $quoteRepository,
        \Magento\Framework\HTTP\PhpEnvironment\RemoteAddress $remoteAddress,
        \Magento\Framework\Event\ManagerInterface $eventManager,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\Customer\Api\CustomerRepositoryInterface $customerRepository,
        QuoteIdMaskFactory $quoteIdMaskFactory,
        \Magento\Quote\Model\QuoteFactory $quoteFactory,
        LoggerInterface $logger = null
    ) {
        $this->_orderFactory = $orderFactory;
        $this->_customerSession = $customerSession;
        $this->quoteRepository = $quoteRepository;
        $this->_remoteAddress = $remoteAddress;
        $this->_eventManager = $eventManager;
        $this->_storeManager = $storeManager;
        $this->customerRepository = $customerRepository;
        $this->quoteIdMaskFactory = $quoteIdMaskFactory;
        $this->quoteFactory = $quoteFactory;
        parent::__construct(
            $request,
            $sidResolver,
            $sessionConfig,
            $saveHandler,
            $validator,
            $storage,
            $cookieManager,
            $cookieMetadataFactory,
            $appState
        );
        $this->logger = $logger ?: ObjectManager::getInstance()
            ->get(LoggerInterface::class);
    }

    /**
     * Set customer data.
     *
     * @param CustomerInterface|null $customer
     * @return \Magento\Checkout\Model\Session
     * @codeCoverageIgnore
     */
    public function setCustomerData($customer)
    {
        $this->_customer = $customer;
        return $this;
    }

    /**
     * Check whether current session has quote
     *
     * @return bool
     * @codeCoverageIgnore
     */
    public function hasQuote()
    {
        return isset($this->_quote);
    }

    /**
     * Set quote to be loaded even if inactive
     *
     * @param bool $load
     * @return $this
     * @codeCoverageIgnore
     */
    public function setLoadInactive($load = true)
    {
        $this->_loadInactive = $load;
        return $this;
    }

    /**
     * Get checkout quote instance by current session
     *
     * @return Quote
     * @throws \Magento\Framework\Exception\LocalizedException
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     */
    public function getQuote()
    {
        $this->_eventManager->dispatch('custom_quote_process', ['checkout_session' => $this]);

        if ($this->_quote === null) {
            $quote = $this->quoteFactory->create();
            if ($this->getQuoteId()) {
                try {
                    if ($this->_loadInactive) {
                        $quote = $this->quoteRepository->get($this->getQuoteId());
                    } else {
                        $quote = $this->quoteRepository->getActive($this->getQuoteId());
                    }

                    $customerId = $this->_customer
                        ? $this->_customer->getId()
                        : $this->_customerSession->getCustomerId();

                    if ($quote->getData('customer_id') && (int)$quote->getData('customer_id') !== (int)$customerId) {
                        $quote = $this->quoteFactory->create();
                        $this->setQuoteId(null);
                    }

                    /**
                     * If current currency code of quote is not equal current currency code of store,
                     * need recalculate totals of quote. It is possible if customer use currency switcher or
                     * store switcher.
                     */
                    if ($quote->getQuoteCurrencyCode() != $this->_storeManager->getStore()->getCurrentCurrencyCode()) {
                        $quote->setStore($this->_storeManager->getStore());
                        $this->quoteRepository->save($quote->collectTotals());
                        /*
                         * We mast to create new quote object, because collectTotals()
                         * can to create links with other objects.
                         */
                        $quote = $this->quoteRepository->get($this->getQuoteId());
                    }
                } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                    $this->setQuoteId(null);
                }
            }

            if (!$this->getQuoteId()) {
                if ($this->_customerSession->isLoggedIn() || $this->_customer) {
                    $customerId = $this->_customer
                        ? $this->_customer->getId()
                        : $this->_customerSession->getCustomerId();
                    try {
                        $quote = $this->quoteRepository->getActiveForCustomer($customerId);
                        $this->setQuoteId($quote->getId());
                    } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                        $this->logger->critical($e);
                    }
                } else {
                    $quote->setIsCheckoutCart(true);
                    $this->_eventManager->dispatch('checkout_quote_init', ['quote' => $quote]);
                }
            }

            if ($this->_customer) {
                $quote->setCustomer($this->_customer);
            } elseif ($this->_customerSession->isLoggedIn()) {
                $quote->setCustomer($this->customerRepository->getById($this->_customerSession->getCustomerId()));
            }

            $quote->setStore($this->_storeManager->getStore());
            $this->_quote = $quote;
        }

        if (!$this->isQuoteMasked() && !$this->_customerSession->isLoggedIn() && $this->getQuoteId()) {
            $quoteId = $this->getQuoteId();
            /** @var $quoteIdMask \Magento\Quote\Model\QuoteIdMask */
            $quoteIdMask = $this->quoteIdMaskFactory->create()->load($quoteId, 'quote_id');
            if ($quoteIdMask->getMaskedId() === null) {
                $quoteIdMask->setQuoteId($quoteId)->save();
            }
            $this->setIsQuoteMasked(true);
        }

        $remoteAddress = $this->_remoteAddress->getRemoteAddress();
        if ($remoteAddress) {
            $this->_quote->setRemoteIp($remoteAddress);
            $xForwardIp = $this->request->getServer('HTTP_X_FORWARDED_FOR');
            $this->_quote->setXForwardedFor($xForwardIp);
        }

        return $this->_quote;
    }

    /**
     * Return the quote's key
     *
     * @return string
     * @codeCoverageIgnore
     */
    protected function _getQuoteIdKey()
    {
        return 'quote_id_' . $this->_storeManager->getStore()->getWebsiteId();
    }

    /**
     * Set the current session's quote id
     *
     * @param int $quoteId
     * @return void
     * @codeCoverageIgnore
     */
    public function setQuoteId($quoteId)
    {
        $this->storage->setData($this->_getQuoteIdKey(), $quoteId);
    }

    /**
     * Return the current quote's ID
     *
     * @return int
     * @codeCoverageIgnore
     */
    public function getQuoteId()
    {
        return $this->getData($this->_getQuoteIdKey());
    }

    /**
     * Load data for customer quote and merge with current quote
     *
     * @return $this
     */
    public function loadCustomerQuote()
    {
        if (!$this->_customerSession->getCustomerId()) {
            return $this;
        }

        $this->_eventManager->dispatch('load_customer_quote_before', ['checkout_session' => $this]);

        try {
            $customerQuote = $this->quoteRepository->getForCustomer($this->_customerSession->getCustomerId());
        } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
            $customerQuote = $this->quoteFactory->create();
        }
        $customerQuote->setStoreId($this->_storeManager->getStore()->getId());

        if ($customerQuote->getId() && $this->getQuoteId() != $customerQuote->getId()) {
            if ($this->getQuoteId()) {
                $this->quoteRepository->save(
                    $customerQuote->merge($this->getQuote())->collectTotals()
                );
            }

            $this->setQuoteId($customerQuote->getId());

            if ($this->_quote) {
                $this->quoteRepository->delete($this->_quote);
            }
            $this->_quote = $customerQuote;
        } else {
            $this->getQuote()->getBillingAddress();
            $this->getQuote()->getShippingAddress();
            $this->getQuote()->setCustomer($this->_customerSession->getCustomerDataObject())
                ->setTotalsCollectedFlag(false)
                ->collectTotals();
            $this->quoteRepository->save($this->getQuote());
        }
        return $this;
    }

    /**
     * Associate data to a specified step of the checkout process
     *
     * @param string $step
     * @param array|string $data
     * @param bool|string|null $value
     * @return $this
     */
    public function setStepData($step, $data, $value = null)
    {
        $steps = $this->getSteps();
        if ($value === null) {
            if (is_array($data)) {
                $steps[$step] = $data;
            }
        } else {
            if (!isset($steps[$step])) {
                $steps[$step] = [];
            }
            if (is_string($data)) {
                $steps[$step][$data] = $value;
            }
        }
        $this->setSteps($steps);

        return $this;
    }

    /**
     * Return the data associated to a specified step
     *
     * @param string|null $step
     * @param string|null $data
     * @return array|string|bool
     */
    public function getStepData($step = null, $data = null)
    {
        $steps = $this->getSteps();
        if ($step === null) {
            return $steps;
        }
        if (!isset($steps[$step])) {
            return false;
        }
        if ($data === null) {
            return $steps[$step];
        }
        if (!is_string($data) || !isset($steps[$step][$data])) {
            return false;
        }
        return $steps[$step][$data];
    }

    /**
     * Destroy/end a session and unset all data associated with it
     *
     * @return $this
     */
    public function clearQuote()
    {
        $this->_eventManager->dispatch('checkout_quote_destroy', ['quote' => $this->getQuote()]);
        $this->_quote = null;
        $this->setQuoteId(null);
        $this->setLastSuccessQuoteId(null);
        return $this;
    }

    /**
     * Unset all session data and quote
     *
     * @return $this
     */
    public function clearStorage()
    {
        parent::clearStorage();
        $this->_quote = null;
        return $this;
    }

    /**
     * Clear misc checkout parameters
     *
     * @return void
     */
    public function clearHelperData()
    {
        $this->setRedirectUrl(null)->setLastOrderId(null)->setLastRealOrderId(null)->setAdditionalMessages(null);
    }

    /**
     * Revert the state of the checkout to the beginning
     *
     * @return $this
     * @codeCoverageIgnore
     */
    public function resetCheckout()
    {
        $this->setCheckoutState(self::CHECKOUT_STATE_BEGIN);
        return $this;
    }

    /**
     * Replace the quote in the session with a specified object
     *
     * @param Quote $quote
     * @return $this
     */
    public function replaceQuote($quote)
    {
        $this->_quote = $quote;
        $this->setQuoteId($quote->getId());
        return $this;
    }

    /**
     * Get order instance based on last order ID
     *
     * @return \Magento\Sales\Model\Order
     */
    public function getLastRealOrder()
    {
        $orderId = $this->getLastRealOrderId();
        if ($this->_order !== null && $orderId == $this->_order->getIncrementId()) {
            return $this->_order;
        }
        $this->_order = $this->_orderFactory->create();
        if ($orderId) {
            $this->_order->loadByIncrementId($orderId);
        }
        return $this->_order;
    }

    /**
     * Restore last active quote
     *
     * @return bool True if quote restored successfully, false otherwise
     */
    public function restoreQuote()
    {
        /** @var \Magento\Sales\Model\Order $order */
        $order = $this->getLastRealOrder();
        if ($order->getId()) {
            try {
                $quote = $this->quoteRepository->get($order->getQuoteId());
                $quote->setIsActive(1)->setReservedOrderId(null);
                $this->quoteRepository->save($quote);
                $this->replaceQuote($quote)->unsLastRealOrderId();
                $this->_eventManager->dispatch('restore_quote', ['order' => $order, 'quote' => $quote]);
                return true;
            } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                $this->logger->critical($e);
            }
        }

        return false;
    }

    /**
     * Flag whether or not the quote uses a masked quote id
     *
     * @param bool $isQuoteMasked
     * @return void
     * @codeCoverageIgnore
     */
    protected function setIsQuoteMasked($isQuoteMasked)
    {
        $this->isQuoteMasked = $isQuoteMasked;
    }

    /**
     * Return if the quote has a masked quote id
     *
     * @return bool|null
     * @codeCoverageIgnore
     */
    protected function isQuoteMasked()
    {
        return $this->isQuoteMasked;
    }
}
`

**Comment by j-lloyd-slc** [comment]
Still happening in Magento 2.3.3.

**Comment by sumitvgupta** [comment]
Issue is still for me in Magento 2.3.2 
I have applied all the patch which is mentioned by @david-fuehr.

**Comment by sdzhepa** [comment]
Hello @j-lloyd-slc  @sumitvgupta @samumaretiya

As I can see this issue should be fixed not in the `2.3-develop` the PR with the fix was proposed by @hostep  and delivered in https://github.com/magento/magento2/pull/25307

Could you please confirm that https://github.com/magento/magento2/pull/25307 fixed the issue and we can close it?
or we still have some cases/scenarios that not fixed

**Comment by adamzero1** [comment]
For any that is still getting this and needs it fixing/changing, I have created a patch.
Changes it from and error to an info message, which I feel is more appropriate, as I agreed with @david-fuehr it is a false positive.
  
The patch can be found here: https://magento.stackexchange.com/a/295470/70781
Hope you find it useful

**Comment by vijay-prevaj** [comment]
Any update regrading this issue?

**Comment by interequipment** [comment]
Having the same issue on 2.3.3 when placing an order. (order placed successfully. but confirmation email is not going)

**Comment by magento-engcom-team** [comment]
Hi @chequille. Thank you for your report. 
The issue has been fixed in magento/magento2#25307 by @hostep in 2.3-develop branch
Related commit(s):
 - [bd964566b5e8de180866a14303e8dc168bf3e600](https://github.com/magento/magento2/commit/bd964566b5e8de180866a14303e8dc168bf3e600)
 - [8920923021110fe0d76f1c17dca9adfa9c0d1b9b](https://github.com/magento/magento2/commit/8920923021110fe0d76f1c17dca9adfa9c0d1b9b)
 - [96b969d1e0303fa711f8bf051b0e5d9b6c1759f1](https://github.com/magento/magento2/commit/96b969d1e0303fa711f8bf051b0e5d9b6c1759f1)
 - [36fb3b7e47343425892355d8b63dfd01068ab291](https://github.com/magento/magento2/commit/36fb3b7e47343425892355d8b63dfd01068ab291)
 - [31412e05d1304ded58b4494f21eeb75573dcaee9](https://github.com/magento/magento2/commit/31412e05d1304ded58b4494f21eeb75573dcaee9)
 - [34591623e3fdf5f963d080dfaaed044f6c4aa4fc](https://github.com/magento/magento2/commit/34591623e3fdf5f963d080dfaaed044f6c4aa4fc)

The fix will be available with the upcoming 2.3.5 release.

**Comment by jsdupuis** [comment]
Having the same issue. What am I supposed to do? Apply the email patch and fix my files manually as per the 6 commits above???

**Comment by arnoudhgz** [comment]
@jsdupuis you can use this as patch file: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/25307.diff

Please make sure you make the paths correct when you use a composer installation.

**Comment by sangthieu** [comment]
I have same issue
@arnoudhgz After apply 25307.diff. Checkout page is working. I still have issue on checkout/success page
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with customerId = 4778

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with customerId = 4778
<pre>#1 Magento\Quote\Model\QuoteRepository->loadQuote() called at [vendor/magento/module-quote/Model/QuoteRepository.php:149]
#2 Magento\Quote\Model\QuoteRepository->getForCustomer() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#3 Magento\Quote\Model\QuoteRepository\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#4 Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins() called at [generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php:39]
#6 Magento\Quote\Model\QuoteRepository\Interceptor->getForCustomer() called at [vendor/magento/module-quote/Model/QuoteRepository.php:174]
#7 Magento\Quote\Model\QuoteRepository->getActiveForCustomer() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#8 Magento\Quote\Model\QuoteRepository\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#9 Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins() called at [generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php:65]
#11 Magento\Quote\Model\QuoteRepository\Interceptor->getActiveForCustomer() called at [vendor/magento/module-checkout/Model/Session.php:589]
#12 Magento\Checkout\Model\Session->getQuoteByCustomer() called at [vendor/magento/module-checkout/Model/Session.php:279]
#13 Magento\Checkout\Model\Session->getQuote() called at [generated/code/Magento/Checkout/Model/Session/Interceptor.php:63]
#14 Magento\Checkout\Model\Session\Interceptor->getQuote() called at [vendor/magento/module-checkout/Controller/Onepage.php:153]
#15 Magento\Checkout\Controller\Onepage->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#16 Magento\Checkout\Controller\Onepage\Success\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#17 Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#18 Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins() called at [generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php:39]
#19 Magento\Checkout\Controller\Onepage\Success\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#20 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#21 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#22 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#24 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#26 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#27 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#28 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#29 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#30 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#31 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#32 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

customerId = 4778 created for me.

**Comment by sangthieu** [comment]
I updated function getQuoteByCustomer and it work better.

private function getQuoteByCustomer(): ?CartInterface
    {
        $customerId = $this->_customer
            ? $this->_customer->getId()
            : $this->_customerSession->getCustomerId();
        if(!$customerId) return null;
        try {
            $quote = $this->quoteRepository->getActiveForCustomer($customerId);
        } catch (NoSuchEntityException $e) {
            $quote = null;
        }

        return $quote;
    }

**Comment by interequipment** [comment]
@sangthieu what is the file you modified?

**Comment by sangthieu** [comment]
@interequipment I using patch https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/25307.diff
In file app/code/Magento/Checkout/Model/Session.php funtion getQuoteByCustomer().
I added line if(!$customerId) return null;

**Comment by jackrevate** [comment]
Still appearing on on 2.3.4 - jesus - nothing but bugs.

**Comment by hostep** [comment]
@jackrevate: as mentioned above, the fix should get included in Magento 2.3.5: https://github.com/magento/magento2/issues/23411#issuecomment-554132357

@sangthieu: if you are able to list steps to reproduce the issue after applying [the patch](https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/25307.diff), that would be awesome!

**Comment by perfpcs** [comment]
Does someone have a copy of the patched file handy they can post up? I rather save the original and try the patched file first. thanks

**Comment by ortoDev** [comment]
Hi everyone,
I've got the same error:
The order is complete but no confirmation email was sent

**Comment by xtremevision** [comment]
I am experiencing this issue in the backend admin, in the customer record, Shopping Cart tab. It looks like the getQuote() function returns all cart items (without a parent id), if no active quote is found for customer id [X].

See screenshot:

![image](https://user-images.githubusercontent.com/6533394/78315365-c442a680-752a-11ea-8971-f0c86211cb3e.png)

This getQuote() function is at fault

![image](https://user-images.githubusercontent.com/6533394/78315477-1c79a880-752b-11ea-81f1-a8d14693913c.png)

The quoteRepository->getForCustomer() function throws the exception as shown here:

![image](https://user-images.githubusercontent.com/6533394/78315585-767a6e00-752b-11ea-9861-77b827acd0ee.png)

The trouble is if no quote is found, then _prepareCollection() will return all quote_items regardless of quote id, regardless of customer_id, as shown by this query:

SELECT `main_table`.* FROM `quote_item` AS `main_table` WHERE (`parent_item_id` IS NULL)

I fixed in by adding this check:

`    protected function _prepareCollection()
    {
        $quote = $this->getQuote();

        if ($quote) {
            $collection = $quote->getItemsCollection(false);
        } else {
            $collection = $this->_dataCollectionFactory->create();
        }

        $collection->addFieldToFilter('parent_item_id', ['null' => true]);
        **if(is_null($quote->getId()))
            $collection->addFieldToFilter('quote_id', -1);**

        $this->setCollection($collection);

        return parent::_prepareCollection();
    }
`
It probably isn't the best or most elegant fix, but it works, or so it seems.
Does anyone have a better idea?

Thanks,
Michael Mussulis

**Comment by kennedyabitbol** [comment]
> Still appearing on on 2.3.4 - jesus - nothing but bugs.

A similar error occurs in 2.3.4, i get this error and the user seems to be logged out, but the [patch](https://github.com/magento/magento2/pull/25307) is there. 
> No such entity with customerId = 1 [] []

Anyone encountering the same issue?

**Comment by chequille** [comment]
It seems to be fixed in 2.3.5
I do not have the error anymore.

**Comment by textarea** [comment]
Magento 2.3.5 still get the error:
No such entity with customerId = 175 

```
[
   {
      "file":"/var/www/current/vendor/magento/module-quote/Model/QuoteRepository.php",
      "line":232,
      "function":"singleField",
      "class":"Magento\\Framework\\Exception\\NoSuchEntityException",
      "type":"::",
      "args":[
         "customerId",
         "175"
      ]
   },
   {
      "file":"/var/www/current/vendor/magento/module-quote/Model/QuoteRepository.php",
      "line":149,
      "function":"loadQuote",
      "class":"Magento\\Quote\\Model\\QuoteRepository",
      "type":"->",
      "args":[
         "loadByCustomer",
         "customerId",
         "175",
         [

         ]
      ]
   },
   {
      "file":"/var/www/current/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php",
      "line":37,
      "function":"getForCustomer",
      "class":"Magento\\Quote\\Model\\QuoteRepository",
      "type":"->",
      "args":[
         "175",
         [

         ]
      ]
   },
   {
      "file":"/var/www/current/vendor/magento/module-quote/Model/QuoteRepository.php",
      "line":174,
      "function":"getForCustomer",
      "class":"Magento\\Quote\\Model\\QuoteRepository\\Interceptor",
      "type":"->",
      "args":[
         "175",
         [

         ]
      ]
   },
   {
      "file":"/var/www/current/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php",
      "line":63,
      "function":"getActiveForCustomer",
      "class":"Magento\\Quote\\Model\\QuoteRepository",
      "type":"->",
      "args":[
         "175",
         [

         ]
      ]
   },
   ...
]
```

**Comment by hostep** [comment]
@textarea: it sounds like a different issue than the one mentioned here.

Could you open a new issue and please try to list steps to reproduce so it can be followed up properly.

Thanks! 🙂

**Comment by ChintanKaneriya** [comment]
We habe Magento v2.3.2. we are facing same issue.

Most of our customer facing this issue, it's happening multiple times a day. it seems to be an issue with once they login, and then come back to the site.. not sure what's causing it.

they are seeing the "Invalid customer addres id" error in the checkout page in the front end.

Can someone give me the final patch to solve this issue?

**Comment by ChintanKaneriya** [comment]
> Hi @chequille. Thank you for your report.
> The issue has been fixed in #25307 by @hostep in 2.3-develop branch
> Related commit(s):
> 
> * [bd964566b5e8de180866a14303e8dc168bf3e600](https://github.com/magento/magento2/commit/bd964566b5e8de180866a14303e8dc168bf3e600)
> * [8920923021110fe0d76f1c17dca9adfa9c0d1b9b](https://github.com/magento/magento2/commit/8920923021110fe0d76f1c17dca9adfa9c0d1b9b)
> * [96b969d1e0303fa711f8bf051b0e5d9b6c1759f1](https://github.com/magento/magento2/commit/96b969d1e0303fa711f8bf051b0e5d9b6c1759f1)
> * [36fb3b7e47343425892355d8b63dfd01068ab291](https://github.com/magento/magento2/commit/36fb3b7e47343425892355d8b63dfd01068ab291)
> * [31412e05d1304ded58b4494f21eeb75573dcaee9](https://github.com/magento/magento2/commit/31412e05d1304ded58b4494f21eeb75573dcaee9)
> * [34591623e3fdf5f963d080dfaaed044f6c4aa4fc](https://github.com/magento/magento2/commit/34591623e3fdf5f963d080dfaaed044f6c4aa4fc)
> 
> The fix will be available with the upcoming 2.3.5 release.

Which Commit should I use to solve the issue?

**Comment by hostep** [comment]
@ChintanKaneriya, you need them all, here they are combined: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/25307.diff or alternatively:  https://github.com/magento/magento2/commit/2c43b82f624806d163ffc598cb6d2f8c3ea0c420

**Comment by wajahatbashir** [comment]
I am still facing same issue in Magento 2.4.0. anyone can tell me how to i can fix this issue ?
![account-information](https://user-images.githubusercontent.com/11786908/109002197-b3ad9880-76c7-11eb-8d77-d40ae9dcb7c0.jpg)

**Comment by arnoudhgz** [comment]
@wajahatbashir your error seems to be a different cause. The problem of this issue was not shown on the frontend, but only in the logs (which was a false positive). It also stated a customerid, while it shows empty in your screenshot. 

It seems like your screenshot is from the account edit page, but you are not actually showing an url. I would suggest asking help on stackexchange, since this does not seem a bug in Magento.

If it is a bug in Magento don't hesitate to create a new issue with proper steps to reproduce it.

**Comment by hershkoy** [comment]
For what is worth, we started getting this issue as well few days ago.
Eventually we found that disabling the newsletter made the error disappear (It was part of 3rd party plugin)

**Comment by Calvin495** [comment]
We are getting "No such entity with quote_id" when we are trying to place an order and not able to place the order at all. Magento version is 2.3.5-p1. I have checked "vendor/magento/module-checkout/Model/Session.php" and looks like the patch is already implemented in that file but still we are getting error.

**Comment by martin-landhi** [comment]
@KarunaKhatri2 @Calvin495 Did you find any fix here? it is happening to me after make an upgrade and i dont know if it is an issue on the database or what

**Comment by dchaykas** [comment]
@magento give me 2.4-develop instance
