### ISSUE TITLE
Can't access front end after successful installation

### ISSUE THREAD

**Issue by lgarridoj** [magento/magento2#2342]
When I try to access the front end url: 127.0.0.1/magedos/magento2
the browser redirects to:
127.0.0.1/magedos/magento2/setup/index.php/session/unlogin
and shows the magento logo along with this message:
"Welcome to Magento Admin, your online store headquarters. 
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard"
The title of this page is: {{$state.current.title}}

I can access back end URL but no images and css. After entering credentials and signing in, the browser redirects to the url below and displays "Object not found... 404 error."
127.0.0.1/magedos/magento2/setup/adminkkk/admin/dashboard/index/key/2c7b4d1692182b35cecbedccd27840e5ac4991f3bcbb7d51155d66570daec50b/

**Comment by mazhalai** [comment]
@lgarridoj can you please give us more details? What is your env like? apache or nginx? PHP version? OS? How did you install, via CLI or Web setup? Did you deploy via git or composer?

**Comment by lgarridoj** [comment]
@mazhalai it's a local WAMP env.
Apache 2.4.7
PHP 5.5.8
Installed via Web setup

**Comment by mazhalai** [comment]
@lgarridoj This is a duplicate of https://github.com/magento/magento2/issues/2309.

**Comment by mazhalai** [comment]
@lgarridoj  Please try again, this has been fixed in RC2.

**Comment by kobid** [comment]
you people are just getting confused
in  ubuntu /etc/nginx/site-enabled/website
you just need to add this by replaceing the server section

:########################################################################
############### WEBSITE CONFIGURATION ##################################
upstream fastcgi_backend {
    server   unix:/var/run/php5-fpm.sock;
 } server {
    listen 80;
    server_name mage.dev; #your ip or website
   set $MAGE_ROOT /var/www/magento2; # root directory
   set $MAGE_MODE developer; # or default
    include /vagrant/magento2/nginx.conf.sample;  #this is imp replace "/vag../mag../" with root directory
 }

###########################################################################

if anyone want ngnxpagespeed mod settings i have configured it

**Comment by AYElsharif** [comment]
@mazhalai read the #2309. #2278 and #2272, but unfortunately I still can't access to back end (404 Error)
My environment :

MAC OS X El Capitan
MAMP Server
PHP 5.6.10
MySQL 5.6.25
Magento-CE-2.0.0+Samples-2015-11-17-06-11-18 

Please help me to solve this issues, I'm stuck in this problem 3 days ago :(

**Comment by mazhalai** [comment]
@Elsharif please refrain from commenting on closed issues, please open a new one. Besides this issue for frontend not backend.

**Comment by AYElsharif** [comment]
@mazhalai I opened a new Issue #2614 
Thanks
