### ISSUE TITLE
Guest can't use Paypal Express in cart

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#23761]
### Preconditions (*)

1. Magento 2.3.2
2. Paypal Express checkout enabled
3. Paypal In-Context mode enabled
4. Paypal Show in cart enabled
5. Paypal guest checkout enabled

### Steps to reproduce (*)

1. Guest user, first time on the shop (no localStorage or session)
2. Add any product to cart
3. Click Paypal button to start express checkout

### Expected result (*)

1. Popup to login to Paypal opens

### Actual result (*)

1. Error message `To check out, please sign in with your email address.` appears and checkout is not possible

The problem can also be reproduced by clearing local storege in cart and refreshing the page.
The issue is [here](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Paypal/view/frontend/web/js/in-context/button.js#L25). `customerData.get('cart')` is empty when this code runs for guests or users with no localStorage.

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23761-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23761-2-3-develop.instances.magento-community.engineering/admin](https://i-23761-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @domeglic ! Thank you for your contribution !
I was trying to reproduce this issue on fresh 2.3-develop instance but i can`t do it ( Popup to login to Paypal opens, purchase was successful) . Maybe i missed some steps ? Can you please share your configuration here ?
Feel free to reopen it in case you have some updates .
Thanks in advance !

**Comment by domeglic** [comment]
I was able to reproduce it on the magento instance you created above when it was up. No other configuration should be necessary.
You can also trigger it by clearing all local storage once in the cart, then refresh the page and click the paypal button.

The problem is that when customer-data.js is initialized it will make async requests to actually retrieve sections data (customer, cart). So using customerData.get("cart") before this request has finished will give back no data

**Comment by engcom-Charlie** [comment]
Hi, @domeglic ! I check it on fresh Magento 2.3.2:

**Actual result:**
No errors
GIF:
![Peek 2019-07-26 12-17](https://user-images.githubusercontent.com/51680850/61941153-9bcbdb00-af9f-11e9-8825-4efd267f187c.gif)

----------------------------------------------------------------------------------------------------------------------------
If you wont to test in instance you can write "@magento give me 2.3-develop instance" and wait 1 min than bot will give it to you.

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23761-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23761-2-3-develop.instances.magento-community.engineering/admin](https://i-23761-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by domeglic** [comment]
You need to go to the actual cart page after adding to cart.

**Comment by engcom-Charlie** [comment]
@domeglic , no errors again:
![Peek 2019-07-29 09-54](https://user-images.githubusercontent.com/51680850/62027703-0b7fd700-b1e7-11e9-9e2a-1f7c430fc84f.gif)

**Comment by mikedubinsky-odb** [comment]
I'm also seeing this issue on 2.3.2 in an Incognito session with no local storage (first attempt only). @domeglic, were you able to resolve?

**Comment by domeglic** [comment]
I resolved it by adding a subscriber to cart section if initial value is undefined. If it is undefined it means localstorage is probably empty and sections did not finish loading yet. In `magento/module-paypal/view/frontend/web/js/in-context/button.js`:
```
initialize: function (config, element) {
            var cart = customerData.get('cart'),
                customer = customerData.get('customer');

            this._super();
            this.renderPayPalButtons(element);
            this.declinePayment = !customer().firstname && !cart().isGuestCheckoutAllowed;

            // BEGIN CHANGE
            if (cart().isGuestCheckoutAllowed === undefined) {
                cart.subscribe(function (updatedCart) {
                    this.declinePayment = !customer().firstname && !cart().isGuestCheckoutAllowed;
                    return updatedCart;
                }.bind(this));
            }
            // END CHANGE

            return this;
        }
```

**Comment by pixiemediaweb** [comment]
> I resolved it by adding a subscriber to cart section if initial value is undefined. If it is undefined it means localstorage is probably empty and sections did not finish loading yet. In `magento/module-paypal/view/frontend/web/js/in-context/button.js`:
> 
> ```
> initialize: function (config, element) {
>             var cart = customerData.get('cart'),
>                 customer = customerData.get('customer');
> 
>             this._super();
>             this.renderPayPalButtons(element);
>             this.declinePayment = !customer().firstname && !cart().isGuestCheckoutAllowed;
> 
>             // BEGIN CHANGE
>             if (cart().isGuestCheckoutAllowed === undefined) {
>                 cart.subscribe(function (updatedCart) {
>                     this.declinePayment = !customer().firstname && !cart().isGuestCheckoutAllowed;
>                     return updatedCart;
>                 }.bind(this));
>             }
>             // END CHANGE
> 
>             return this;
>         }
> ```

^^^ spot on, just found this bug putting a client site live tonight, that solves it. Thanks

**Comment by mikedubinsky-odb** [comment]
Same fix for me, but on product page: Magento_Paypal/js/in-context/product-express-checkout 
Thanks!

**Comment by johncarlson21** [comment]
apparently this was never added to code and just closed??????

**Comment by LittleBigDev** [comment]
Please reopen this issue. Nothing was fixed !

**Comment by gigadesign1** [comment]
This issue should be re-opened.

I was also able to reproduce on Safari, but I can't reproduce it on Firefox and Chrome.

It's Javascript. The lines of code are not executed in the same order on every browser and or machine, so your 'we cannot reproduce' doesn't mean that the bug doesn't exist.

And in addition to the report; it also happens when the 'in-context' mode is set to no.

**Comment by hewgim** [comment]
How do you get an issue reopened? This issue still exists in 2.3.5-p2. In fact, you can also see this issue if you add a discount code in the cart and then attempt to checkout using the paypal express in context button. The paypal window flashes up, then disappears. You cant checkout unless you refresh the cart page and try again. I don't know how the guys from Magento can't reproduce this. It happens on all 5 Magento 2 sites that I have built so far.

@domeglic - Thanks so much for your fix. It works a treat

Regards

Mark

**Comment by pako-g** [comment]
Same with magento 2.3.5-p1

**Comment by microdreamltd** [comment]
Same with magento 2.4.1, suggested fix does not work.

**Comment by akhiltanveer** [comment]
Override the file from magento vendor
path to copy the file:
vendor/magento/module-paypal/view/frontend/web/js/in-context/button.js

override the file in your custom them 

app/design/frontend/Vendor/YourThemeName/Magento_Paypal/web/js/in-context/button.js

comment the line 25

            /* this.declinePayment = !customer().firstname && !cart().isGuestCheckoutAllowed;*/

the in-context paypal checkout will now work with guest users and also registered users.

in case you want to check add guestCheckout validation replace the line 25 with the following line

before
            this.declinePayment = !customer().firstname && !cart().isGuestCheckoutAllowed;*/
after
             this.declinePayment = !cart().isGuestCheckoutAllowed;
