### ISSUE TITLE
X-Magento-Tags header too large for child products

### ISSUE THREAD

**Issue by calin-ImDigital** [magento/magento2#23834]
We are experiencing a number of issue with requests for some categories and catalog search on a 20k catalog size. Some requests in a combination of 2 words or higher where the number of results increases we see that X-Magento-Tags header is very large and will not be handled by server.
The only thing that we can find inside the server logs is this 

`upstream sent too big header while reading response header from upstream` 

Now we played around with header sizes and other settings with no success.

This is the case where the application may return a 200ok response but the server can’t handle header size.

Digging around we have found that the change that is affecting cache tags are introduced bu the plugin  on this change https://github.com/magento/magento2/commit/f04154e54a1a5d62932934971acdd07118f98d40#diff-bafb677f96f7c46f8938317006e937c3
on magento 2.3.1 to add additional data for child product for every configurable product, and X-Magento-Tags can quickly escalate to a very large size. For ex. a response with 50 configurable products can append additional 4100 tags on the first request, and it only depends on the number of child products.

### Preconditions (*)
1. magento 2.3.2
2. elasticsearch 5.6/6
3. builtin full page cache enabled
4. catalog of 20k products(1configurable with ~10child)

### Steps to reproduce (*)

1. Search any product in a combination of more one word
2. Only the first request that is not cached will show 502

### Expected result (*)
1. page response is returning the catalog search result

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/48591835/61710321-0be91f80-ad5a-11e9-8a11-e55299f14569.png)
[X-Magento-Tags.log](https://github.com/magento/magento2/files/3421880/X-Magento-Tags.log)

**Comment by engcom-Charlie** [comment]
Hi, @cdiacon-img ! Sorry, but i have to close this issue, because my elasticsearch works fine on 2.3.2 and 2.3-develop branches(no errors and search show result).
Thank for contribution!

**Comment by astorm** [comment]
@cdiacon-img, @gpcrocker -- did either of you find a solution for this? (other than reducing the number of products you were trying to display on a page?)

**Comment by ihor-sviziev** [comment]
Looks like duplicate of https://github.com/magento/magento2/issues/6401

**Comment by gpcrocker** [comment]
@astorm yes, but we just did away with the child product cache invalidation functionality.

We disabled product_identities_extender plugin in Magento\Bundle\Model\Plugin\Frontend\Product and the "bundle" plugin "Magento\Bundle\Model\Plugin\Frontend\Product" in di.xml.

In order to retain that functionality we needed to raise the configuration limits of varnish and maybe even nginx (but I don't remember exactly). For us it was a hassle to do the fix in production and we didn't find it worthwhile, so we went with the option described.

**Comment by davidalger** [comment]
@astorm These are the defaults which I usually roll with any varnish deployment for Magento 2:
```
# Value for workspace_backend must be larger than both http_resp_hdr_len and http_resp_size. These settings must be
# higher than typical varnish defaults to accommodate lengthy magento X-Magento-* headers used for tagging cached pages.
varnish_workspace_backend: 262144
varnish_http_resp_size: 196608
varnish_http_resp_hdr_len: 131072

# Value for workspace_client must be larger than both varnish_http_req_size and varnish_http_req_size. These settings
# may need to be raised on large-catalog sites where PURGE requests to varnish may easily near and/or breach the limits
# with a 1024k+ X-Magento-Tags-Pattern header used for selectively banning items found in the cache.
varnish_workspace_client: 131072
varnish_http_req_size: 65536
varnish_http_req_hdr_len: 32768

# When using secure URLs on the frontend, this is neccessary to prevent backend connect failures
varnish_esi_ignore_https: true
```
ref: https://github.com/davidalger/ansible-role-varnish/blob/master/defaults/main.yml

Not saying there is not an underlying issue, but it definitely remediates in the majority of cases.

**Comment by calin-ImDigital** [comment]
@astorm 
We solved the issue by disabling this plugin product_identities_extender.
<type name="Magento\Catalog\Model\Product">
        <plugin name="product_identities_extender" disabled="true"/>
    </type>

**Comment by NickdeK** [comment]
We are having the same issue but with some configurable products. Disabling the`product_identities_extender` solves the issue. So shouldn't this issue be reopened and solved?

**Comment by ihor-sviziev** [comment]
Re-opened.
@engcom-Charlie please investigate this issue deeper. People still reporting it.

**Comment by engcom-Charlie** [comment]
Hi @cdiacon-img,
I'm trying to reproduce, I've:

- Latest 2.4-develop Magento branch
- Elasticsearch 6
- Varnish cache
- Catalog of 20k products(1configurable with ~10child)

**Steps**:

1. Set Products per Page to _50_ in Magento Admin
![image](https://user-images.githubusercontent.com/51680850/82537712-285d1080-9b53-11ea-8e61-3d3de154806d.png)
2. Open catalog on the storefront


**AR**: 
![image](https://user-images.githubusercontent.com/51680850/82536971-f7c8a700-9b51-11ea-8874-948c7bd15d4c.png)

**Varnsih log screenshot**
![image](https://user-images.githubusercontent.com/51680850/82538204-09ab4980-9b54-11ea-88a7-ad5d7457b473.png)

What do You think?

**Comment by ihor-sviziev** [comment]
Hi @engcom-Charlie,
Looks like issue should be fixed in https://github.com/magento/magento2/commit/3b611a7cc0040c9e5731cbc8e2080c2adb205d86.
Could you confirm that?

**Comment by ihor-sviziev** [comment]
Duplicate of #6401

**Comment by ihor-sviziev** [comment]
I see that issue described above is already fixed in 2.4-develop branch. More info there: https://github.com/magento/magento2/issues/6401#issuecomment-623439883

I'm closing this issue.

**Comment by ThomasMW** [comment]
This issue still persists in the latest release. I'm working on a Magento 2.4.0 instance and had to apply the 'disable the product_identities_extender plugin fix' to get rid of 503s on larger category page after increasing the values for http_resp_size and http_req_hdr_len had failed.

I had to disable the plugin in di.xml for 'Magento\ConfigurableProduct\Model\Plugin\Frontend\ProductIdentitiesExtender' instead of the above described 'Magento\Bundle\Model\Plugin\Frontend\Product'.

Just wanted to report this in case others came across this thread looking for a solution for 2.4.0.

**Comment by hostep** [comment]
According to the bèta release notes for Magento 2.4.1, it will be fixed in that version (is planned to be released on 15 October).

**Comment by zcuric** [comment]
I've updated Magento to 2.4.1 and this issue still persists.

**Comment by ihor-sviziev** [comment]
Hi @zcuric,
I see that issue was fixed in 2.4.1, so you probably shouldn't have this issue anymore. Sometimes there might be few cases when similar issue appears, maybe exact your wasn't fixed yet. 

Are you sure you're having exact the same issue and steps to reproduce? Were you able to reproduce this issue on clean magento installation?

**Comment by zcuric** [comment]
Hi @ihor-sviziev here is the response from my site when trying to open a category with large number of products:
```
curl -I (removed for obviouse resoans)
HTTP/1.1 200 OK
Date: Tue, 10 Nov 2020 21:02:47 GMT
Server: Apache
Pragma: cache
Cache-Control: max-age=86400, public, s-maxage=86400
Expires: Wed, 11 Nov 2020 21:02:47 GMT
X-Magento-Tags:
cat_c,cat_c_179,cat_c_180,cat_c_181,cat_c_182,store,cms_b,cms_b_about-*****,cms_b_useful-links,cms_b_general-information,cms_b_read-more,cms_b_custom-copyright,cms_b_social-media-links,cat_c_p_180,cat_p_15300,cat_p,cat_p_15280,cat_p_15279,cat_p_15220,cat_p_15219,cat_p_15218,cat_p_15214,cat_p_15213,cat_p_15212,cat_p_15208,cat_p_15197,cat_p_15196,cat_p_15195,cat_p_15194,cat_p_15189,cat_p_15188,cat_p_15164,cat_p_15163,cat_p_15162,cat_p_15161,cat_p_15121,cat_p_15086,cat_p_15084,cat_p_15083,cat_p_15082,cat_p_15081,cat_p_15080,cat_p_15079,cat_p_15078,cat_p_15077,cat_p_15076,cat_p_15075,cat_p_15074,cat_p_15073,cat_p_15072,cat_p_15069,cat_p_15068,cat_p_15067,cat_p_15065,cat_p_15064
...
cat_p_7245,cat_p_7237,mobile
X-Magento-Debug: 1
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: PHPSESSID=cac2b267da30f266b36e9a04fffd452b; expires=Tue,
10-Nov-2020 22:02:47 GMT; Max-Age=3600; path=/; domain=********;
HttpOnly
Set-Cookie: X-Magento-Vary=c58cc7336841735bf5ef13185766282824a9d073;
expires=Tue, 10-Nov-2020 22:02:53 GMT; Max-Age=3600; path=/; HttpOnly;
SameSite=Lax
Content-Length: 2813217
X-UA-Compatible: IE=edge
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=UTF-8
Set-Cookie: PH_HPXY_CHECK=s1; path=/
Cache-control: private
```
I deploy my site with gitlab CI/CD and usually it's a clean install with composer.

**Comment by ihor-sviziev** [comment]
Hi @zcuric,
Could you create a new issue with steps to reproduce? Someone from QA will check that additionally.
