### ISSUE TITLE
Layer navigation displaying whenever select Static Block onl

### ISSUE THREAD

**Issue by ankitpatel2931** [magento/magento2#24031]
### Preconditions (*)

1. Magento 2.3.2
2. Sample data installed

### Steps to reproduce (*)

1. Set Display Mode to Static block only on particular category
![Hoodies   Sweatshirts (ID_ 15) _ Categories _ Inventory _ Catalog _ Magento Admin (1)](https://user-images.githubusercontent.com/44745569/62536094-b721ca80-b86a-11e9-9881-23b73723858d.png)

### Expected result (*)

1. Layered Navigation (Shopping Options) should  not be visible
![Hoodies   Sweatshirts - Tops - Men (3) (1)](https://user-images.githubusercontent.com/44745569/62536108-c0ab3280-b86a-11e9-9dc8-6e26d0379f49.png)

### Actual result (*)

1. Layered Navigation (Shopping Options) visible
![Hoodies   Sweatshirts - Tops - Men (2)](https://user-images.githubusercontent.com/44745569/62536119-c99c0400-b86a-11e9-94cc-d43ccc443ccb.png)

**Comment by engcom-Bravo** [comment]
Hello @ankitpatel2931, thanks for applying. The Display Mode has three available options: Products only, Static block only and Static block and products. Seems each option works as expected. There is no option with Layered Navigation and the Layered Navigation itself is not a part and parcel of the product list. If You want the Layered Navigation to stop displaying on that category page You may for example change its display setting of Anchor from Yes to No.

**Comment by ankitpatel2931** [comment]
Hello,

Thanks for the update here.

As I have checked in previous version like magento 2.2.5
It's working fine. Please see below file and below code.

/vendor/magento/module-layered-navigation/Block/Navigation.php

/**
     * Check availability display layer block
     *
     * @return bool
     */
    public function canShowBlock()
    {
        return $this->getLayer()->getCurrentCategory()->getDisplayMode() !== \Magento\Catalog\Model\Category::DM_PAGE
            && $this->visibilityFlag->isEnabled($this->getLayer(), $this->getFilters());
    }

Above things working fine.

But, in Magento 2.3.2 above function looks like below.

/**
     * Check availability display layer block
     *
     * @return bool
     */
    public function canShowBlock()
    {
        return $this->visibilityFlag->isEnabled($this->getLayer(), $this->getFilters());
    }

If I replaced above code with Magento 2.2.5 code than every thing works fine.

I think, I am selecting Static Block here. So, I don't want to display Products in this page. So, no need to display Layer navigation when I select Static Block.

Could you please confirm both function?

Thanks.

**Comment by engcom-Bravo** [comment]
Initially the same issue #7765 was reported on 2.1.2 version. Then fixed in 2.2 by commit 39e0fd9a5366a6d25bc3b9f9ae324aa9be026cb9 but seems that commit was not merged into 2.3.

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19005` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ankitpatel2931** [comment]
Hi @engcom-Bravo , @magento-engcom-team ,

Thanks for confirmation.
Please let me know If I can do any thing in this.

**Comment by engcom-Bravo** [comment]
You are welcome @ankitpatel2931. I think You've already done enough, so thanks for help.

**Comment by magento-engcom-team** [comment]
Hi @ankitpatel2931. Thank you for your report. 
The issue has been fixed in magento/magento2#24497 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [a579c208029c5352d09038665ef7e0d03f3d9d55](https://github.com/magento/magento2/commit/a579c208029c5352d09038665ef7e0d03f3d9d55)
 - [2ed72ca8fbc1c3dc0879c9e39d6a3b05b179130c](https://github.com/magento/magento2/commit/2ed72ca8fbc1c3dc0879c9e39d6a3b05b179130c)

The fix will be available with the upcoming 2.3.4 release.

**Comment by BezV8** [comment]
The fix included in 2.3.4 has fixed the issue on most categories for me, but a few seem to still exhibit the buggy behaviour. All of those with the layered navigation still showing all also have anchor set to no.
