### ISSUE TITLE
Magento_Braintree/js/view/payment/method-renderer/paypal.js accessing undefined variables

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#24618]
### Preconditions (*)

1. Magento 2.2. * - 2.3.2 

### Steps to reproduce (*)

1. initiate paypal payment method when shipping address object is  not filled with data 

### Expected result (*)

1. no js errors on frontend 
2. more checks on getShippingAddress method is needed to validate the address object before usage https://github.com/magento/magento2/blob/de0fc3b767838384df35424bc747fed98bb56453/app/code/Magento/Braintree/view/frontend/web/js/view/payment/method-renderer/paypal.js#L329 

currently only address.postcode is validated however when other fields are missing like street it expects data to be present while it can be missing 

### Actual result (*)

1. its possible to end up in a state where console logs errors 

`Uncaught TypeError: Cannot read property '0' of undefined
    at UiClass.getShippingAddress (/pub/static/version1568411942/frontend/Magento/luma/en_US/Magento_Braintree/js/view/payment/method-renderer/paypal.js:305)
    at UiClass.getPayPalConfig (/pub/static/version1568411942/frontend/Magento/luma/en_US/Magento_Braintree/js/view/payment/method-renderer/paypal.js:268)
    at UiClass.initClientConfig (/pub/static/version1568411942/frontend/Magento/luma/en_US/Magento_Braintree/js/view/payment/method-renderer/paypal.js:167)
    at UiClass.initObservable (/pub/static/version1568411942/frontend/Magento/luma/en_US/Magento_Braintree/js/view/payment/method-renderer/paypal.js:114)
    at UiClass.initObservable (wrapper.js:109)
    at UiClass.initialize (element.js:104)
    at UiClass.initialize (wrapper.js:109)
    at UiClass._super (wrapper.js:106)
    at UiClass.initialize (default.js:62)
    at UiClass.initialize (wrapper.js:109)
    at UiClass._super (wrapper.js:106)
    at UiClass.extendingObj.initialize (default.js:21)
    at UiClass.initialize (wrapper.js:109)
    at new UiClass (class.js:49)
    at Object.initComponent (layout.js:137)
    at fire (jquery.js:3232)`

**Comment by speedupmate** [comment]
without diving in too much besides fixing the exact error stopping site functionality (related PR) would it be meaningful: 

- not to assume that postcode present = all other data present  
- create a whitelist array of required fields from payment gateway 
- iterate over this field and filter out whats there and whats not 
- adjust for region, region_id case 
- adjust for street being string (all values separated with \n) or array (up to 4 members) 
- decide the return values based on iteration 

Given the complexity we have in checkout areas then in Magento 2 address object (both billing and shipping) in different states of application can be:  undefined, null , {} , initiated address object without data,  initiated address object with partially or fully filled data.

**Comment by magento-engcom-team** [comment]
Hi @speedupmate. Thank you for your report. 
The issue has been fixed in magento/magento2#24622 by @speedupmate in 2.3-develop branch
Related commit(s):
 - [d8534d2430f540373262dd3d47a8500f2c752d3e](https://github.com/magento/magento2/commit/d8534d2430f540373262dd3d47a8500f2c752d3e)

The fix will be available with the upcoming 2.3.4 release.

**Comment by ClintTec** [comment]
Still an issue on 2.4.1

![paypal_braintree_magento2_4](https://user-images.githubusercontent.com/17075387/111260166-4e601e00-865b-11eb-82b4-6afbc05f04fa.png)

**Comment by speedupmate** [comment]
> Still an issue on "magento/product-enterprise-edition": "2.4.3-p2"

Your only option is to resubmit this ticket if this still happens
