### ISSUE TITLE
Message at Frontend has No HTML format

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25162]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store-> configuration-> Customer -> Newsletter
3. 
![image](https://user-images.githubusercontent.com/8234209/67148877-c1caf800-f2ce-11e9-8016-22c09cbc9954.png)
"Allow Guest Subscription" is "No"
4. Go to frontend
5. Enter the email "test@localhost.com" , press "Subscribe" at the bottom.
6. Look the message:
![image](https://user-images.githubusercontent.com/8234209/67148912-2ab27000-f2cf-11e9-93e3-4ab0a9f48019.png)

### Expected result (*)

![image](https://user-images.githubusercontent.com/8234209/67148888-eb841f00-f2ce-11e9-92a7-c254c7b30a68.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/67148909-27b77f80-f2cf-11e9-9a6d-ee4b171648d1.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25162-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25162-2-3-develop.instances.magento-community.engineering/admin](https://i-25162-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21942` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [Magento instance](https://i-25162-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25162-2-4-develop.instances.magento-community.engineering/admin](https://i-25162-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#26455 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [690f791cc76e435d15da1c3eb5f8a4e4f63200ea](https://github.com/magento/magento2/commit/690f791cc76e435d15da1c3eb5f8a4e4f63200ea)
 - [141ca96b1ac0973ac1c46f8a225f4e69291c01fd](https://github.com/magento/magento2/commit/141ca96b1ac0973ac1c46f8a225f4e69291c01fd)
 - [f060ee7d46a5a88b97c846c1c37fd3d3c447c32d](https://github.com/magento/magento2/commit/f060ee7d46a5a88b97c846c1c37fd3d3c447c32d)
 - [45cd0fa332f5eb32e4e49a2e055ecb57d8442afa](https://github.com/magento/magento2/commit/45cd0fa332f5eb32e4e49a2e055ecb57d8442afa)
 - [3e2ea3a54e0568e2971fee7df3591a54f40e8b7d](https://github.com/magento/magento2/commit/3e2ea3a54e0568e2971fee7df3591a54f40e8b7d)
 - [d6316cfe9c5ec70cf99689b26c452a2b28986a4e](https://github.com/magento/magento2/commit/d6316cfe9c5ec70cf99689b26c452a2b28986a4e)
 - [1251f01b4ab88d5ef70447667e1f482feb01b055](https://github.com/magento/magento2/commit/1251f01b4ab88d5ef70447667e1f482feb01b055)

The fix will be available with the upcoming 2.4.0 release.

**Comment by dimonovp** [comment]
Hi @slavvka. Can you create back-port for 2.3-develop, because this issue isn't fixed in 2.3-develop?
