### ISSUE TITLE
Search Term synonyms not working

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2519]
I have made a search term synonym for BULDOG (with one "L") that should load the search results for BULLDOG (with two "L"'s) But it doesn't seem to work at all.

![2015-11-25_14h41_07](https://cloud.githubusercontent.com/assets/13572447/11398722/f6255046-9382-11e5-80ed-344fb9d2f094.png)

![2015-11-25_14h43_06](https://cloud.githubusercontent.com/assets/13572447/11398733/0363d976-9383-11e5-9c03-9f9d00bf6cc3.png)

It should work because BULLDOG search returns results:

![2015-11-25_14h43_56](https://cloud.githubusercontent.com/assets/13572447/11398774/1ec45916-9383-11e5-939c-e73f2913abcc.png)

Have tried it with other terms and have same results.

**Comment by choukalos** [comment]
Created bug - MAGETWO-46044 for internal tracking.

**Comment by vzabaznov** [comment]
Hi @SidneyBilliet, issue was fixed, please check it, and if you think that not, feel free to write here or to open new one

**Comment by martinhetschel** [comment]
Search Synonyms still not working on a fresh 2.1.6 installation.
![image](https://cloud.githubusercontent.com/assets/17616012/25506142/7fea455a-2ba5-11e7-94d1-df1d7df6473b.png)
![image](https://cloud.githubusercontent.com/assets/17616012/25506188/b8d9ce58-2ba5-11e7-92a4-a29cb5d3f6a2.png)
![image](https://cloud.githubusercontent.com/assets/17616012/25506214/d9895d12-2ba5-11e7-9e2c-c1c2fb2ddb64.png)

**Comment by yosefkurniawan** [comment]
Anyone have workaround for this issue? I'm facing the issue on 2.1.3.
