### ISSUE TITLE
Magento 2.3.3 - Images lost when re-saving a category

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#25209]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Edit category
2. No images are loaded
3. Save category -> images are lost
4. Edit category - upload images -> save, images are saved
5. Edit category -> images are not loaded

### Expected result (*)
1. Images to exist

### Actual result (*)
1. No images in back end or front end

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25209-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25209-2-3-develop.instances.magento-community.engineering/admin](https://i-25209-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by paul-blundell** [comment]
I have just ran into this exact issue on a 2.3.3 instance.

**Comment by ajijshekh123** [comment]
This issue is related to the:  https://github.com/magento/magento2/issues/22222

I think this issue is related to the DB as per the above issue comment. 
I don't have this issue reproduced. Please see attached screenshot:

![2019-10-22 (4)](https://user-images.githubusercontent.com/24711761/67271953-33769200-f4d9-11e9-8c5b-2982a3445eee.png)

![2019-10-22 (5)](https://user-images.githubusercontent.com/24711761/67271954-33769200-f4d9-11e9-9919-cbec5fa53d33.png)

@craigcarnell - Now I am closing this issue. If you have reproduced this issue again. you can reopen it.

**Comment by paul-blundell** [comment]
@ajijshekh123 So whats the solution?? I can't find anything in that linked issue suggesting a solution. There is an issue here, perhaps when migrating from 2.2 to 2.3. This is happening for me on 3 Magento installs, all of which have been upgraded from 2.2

**Comment by ajijshekh123** [comment]
I think you haven't proper migrating DB that's why this issue found in your magento instance. 
Magento fresh 2.3.3 instance I can't reproduce this issue that's why I have close it.

**Comment by paul-blundell** [comment]
Just to explain what I am seeing happening here:

1. Create a new category
2. Upload an image, e.g. my-image.png
3. Save the category
4. Checking the media/catalog/category folder I can see my-image.png and checking the database table `catalog_category_entity_varchar` I can see my-image.png for attribute ID 48 (image)
5. Reload category and click save
6. Image now missing, checking media folder and its still there BUT checking the database and the entry is now showing my-image_1.png - but that image path obviously doesn't exist.

**Comment by ajijshekh123** [comment]
Magento Provide me Magento 2.3.3 instance and I have verified this issue with your same steps but I can't find it.
If you have querey this issue is related to Default Magento instance you can open it.

Thanks.

**Comment by paul-blundell** [comment]
So you've closed this issue because you can't reproduce it on a fresh installation of Magento, but did you try to reproduce the issue on an upgraded instance? I followed the exact upgrade steps [listed here](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html) and this issue has now occured on 3 instances of Magento.

**Comment by ajijshekh123** [comment]
Okay Fine @paul-blundell, Now I have reopen this issue.

Thanks for the update.

**Comment by paul-blundell** [comment]
I have also just done a completely fresh install, new files and database following these instructions: https://devdocs.magento.com/guides/v2.3/install-gde/composer.html

Same issue.

Thanks for reopening.

**Comment by krishprakash** [comment]
Hi @craigcarnell. Thank you for your report.
Seems similar issue is already open 
Please check  #25099 
And it's only reproduce on 2.3.3 not in 2.3-develop instance
Thanks

**Comment by andreyuok** [comment]
I reproduce this issue now on EE 2.3.3

PRECONDITION:
1. Clean install Magento 2.3.3
2. One Category Created.


STEPS TO REPRODUCE:
1. Go to category that was created in precondition
2  Open tab "Content" and upload "Category Image" (For example: name of file elephant.jpg)
3. Save Category. (Category saved and opened again)
4. Check "Content" tab that image you uploaded is displayed in Category Image attribute.
5. Check "catalog_category_entity_varchar" table. Find name of your file "elephant.jpg" in list of rows (by default in clean install category image attribute has id - 48)
6. Do nothing and save the category again.
7. Check "Content" tab again that image you uploaded earlier is still in Category Image attribute (Actual result is that picture has disappeared)
8. Check "catalog_category_entity_varchar" table. Find name of your file uploaded earlier "elephant.jpg" in list of rows. Note that name has changed from "elephant.jpg" to "elephant_1.jpg"


ACTUAL RESULT:
The already uploaded category image Disappears when the category is saved again.


EXPECTED RESULT:
The already uploaded category image should not disappear when the category saving again.

**Comment by adamrandazzo** [comment]
I am having the same issue on EE 2.3.3 -- was upgraded from previous versions.

**Comment by gfritzdev** [comment]
I just ran into this issue on a fresh install of 2.3.3 community.  It is definitely still an issue.

**Comment by davidpixie** [comment]
Still occurring on fresh install of 2.3.4 too :-(

**Comment by VincentMarmiesse** [comment]
I have the same issue on a EE B2B 2.3.3.

**Comment by APanteleychuk** [comment]
I have the same issue on an EE  2.3.3 too.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25209-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25209-2-4-develop.instances.magento-community.engineering/admin_5d29](https://i-25209-2-4-develop.instances.magento-community.engineering/admin_5d29)
Login: `457a7e0b` Password: `1c16d9ace50a`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi APanteleychuk, Issue is fixed on 2.3.4
Need to move this issue to EE repository.
@sdzhepa kindly move this issue to EE/B2B repository as mentioned in last 2 feedback.
Thanks

**Comment by t-eichmann** [comment]
> Hi APanteleychuk, Issue is fixed on 2.3.4
> Need to move this issue to EE repository.
> @sdzhepa kindly move this issue to EE/B2B repository as mentioned in last 2 feedback.
> Thanks

This issue is definitely not fixed on 2.3.4, it happens to one of our customers all the time.

**Comment by roma84** [comment]
Still happens in 2.4.0:
 - Open some category
 - Upload image and save the category - image attribute value appears in `catalog_category_entity_varchar` table with the path: `/pub/media/catalog/category/gear.jpg`
 - Save the category - path is changed to `/magento/htdocs/pub/media/catalog/category/gear.jpg`
 - Save the category again - attribute value is removed from `catalog_category_entity_varchar` table

**Comment by t-eichmann** [comment]
Can confirm that this still happens with 2.4.

**Comment by sforsarvesh** [comment]
Hi,
Has anybody found a solution ? Because recently i have faced the same issue in EE 2.3 .

**Comment by JonathanHelvey** [comment]
Hi, We have recently upgraded to Magento 2.3.5 and we are noticing a similar issue.

**Comment by sermagnus** [comment]
I am still with 2.3.3 is there any solution?

**Comment by Digitag** [comment]
df

**Comment by robinjoh** [comment]
Also facing this on magento 2.4.1

**Comment by tim-breitenstein-it** [comment]
Also facing to me!

- Magento 2.4.1 fresh installation
- Data Migration from 1.9.3.10

The image is also still uploading to `pub/media/catalog/tmp` folder only.

The `catalog_category_entity_varchar` is only the image name `phone.svg` and not the full path like: `/media/catalog/category/phone.svg`.

If I copy the image to `/media/catalog/category/` and save the correct path + image name `/media/catalog/category/phone.svg` on the `catalog_category_entity_varchar` table it works!

**Comment by PHProDreamy** [comment]
We are also facing this issue on both 2.2.X and 2.4.1 installations

**Comment by ashvinimarwal** [comment]
I'm also facing this issue on Magento 2.3.5 after migration from M1.

**Comment by engcom-Alfa** [comment]
Hi @craigcarnell 

Tried to reproduce in **Magento 2.4-develop** version, and unable to successfully reproduce it. Below are the steps I followed.

1. Admin side: Navigated to the Catalog > Categories
 
2. Opened the existing category.

3. Uploaded one image in the Content section of category and saved.

4. Frontend: Opened the category page; Able to see the uploaded image as expected.

5. Again navigated to to the same category in the backend

6. Uploaded some other image and saved.

7. Frontend: Opened the category page; Able to see the new uploaded image as expected.


Hope I have followed correct steps to reproduce as per my understanding.
- If there is any change you want to do in the execution considering above steps, kindly inform me the required change mentioning that step number.
- If you are expecting other output for any of the steps, kindly mention that expected output with the step number only please.
- If you want to add/remove any step from the list, kindly tell me what is that you want to add/remove and in between which step number.

Note: Kindly upgrade to the latest version, re try the issue please and then update me back about the steps.

**Comment by engcom-Alfa** [comment]
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).
