### ISSUE TITLE
Login pop up link overlap the minicart button on magento 2 checkout page

### ISSUE THREAD

**Issue by onlinejitu** [magento/magento2#25362]
'Sign In' popup link overlapping the Minicart button overlapping on the checkout page

**Preconditions (*)**
Magento 2.3.2
PHP 7.1.19

**Steps to reproduce (*)**
Steps to reproduce
**NOTE**: Please make sure frontend theme should be set to LUMA theme, before proceed to reproduce the layout issue
Step 1: Go to frontend
Step 2: Add any product to cart and go to checkout page
Step 3: See top right corner (Minicart section)
Step 4: There is an additional link i.e. 'Sign In'

**Expected result (*)**
Minicart and Sign In link should be placed separately

**Actual result (*)**
Minicart and 'Sign In' link are overlapping each other, please see attached screenshot:
![image](https://user-images.githubusercontent.com/36662828/67833128-cc289580-fb09-11e9-86e7-2254aa1a0dea.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25362-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25362-2-3-develop.instances.magento-community.engineering/admin](https://i-25362-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@onlinejitu I am not able to reproduced on Magento 2.3-develop instance
![image](https://user-images.githubusercontent.com/50358141/67834600-d056b200-fb0d-11e9-98ee-2809101b21c7.png)

**Comment by onlinejitu** [comment]
@sudheers-kensium thanks for looking into the issue, let me provide you more detail on this.

**Comment by onlinejitu** [comment]
FYI, I am working on Magento-CE-2.3.2-2019-06-13-03-19-34

Are you also checking in this version?

**Comment by sudheers-kensium** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by onlinejitu** [comment]
@magento please provide 2.3.2 instance that was released on 2019-06-13-03-19-34, thanks

**Comment by onlinejitu** [comment]
@sudheers-kensium & @magento
I found one difference that: In Magento-CE-2.3.2-p2-2019-10-09-01-20-50 , minicart and top navigation are hidden, so that you can not reproduce the issue.

If you use Magento-CE-2.3.2-2019-06-13-03-19-34 then you will find it.

For now, my problem has resolved by upgrading Magento to latest version.

Thanks for looking into the issue.

**Comment by sudheers-kensium** [comment]
@onlinejitu Maybe this issue is resolved in latest version, so I am closing this issue.

**Comment by ant-workaholic** [comment]
Still have the issue on Magento 2.3.3

**Comment by ant-workaholic** [comment]
> @onlinejitu I am not able to reproduced on Magento 2.3-develop instance
> ![image](https://user-images.githubusercontent.com/50358141/67834600-d056b200-fb0d-11e9-98ee-2809101b21c7.png)
It seems you disabled the shopping cart on checkout. That is the reason why it was fixed for you. I still have the issue on Magento 2.3.3
