### ISSUE TITLE
Catalog search pagination issue on Elasticsearch 6.x

### ISSUE THREAD

**Issue by gaiterjones** [magento/magento2#25369]
### Preconditions (*)

1. Magento 2.3.3
2. Hotfix Catalog pagination issue on Elasticsearch 6.x patch for Magento 2.3.3 applied
2. Elasticsearch 6.6.2
3. PHP 7.1

### Steps to reproduce (*)

1. Upgrade from 2.3.2 to 2.3.3
2. Perform frontend keyword search
3. First page of multi page results are returned
4. Click next page of results
5. no search results are returned.

![image](https://user-images.githubusercontent.com/3909886/67855166-35140b80-fb12-11e9-9db6-931c829f36c9.png)

### Expected result (*)

1. Magento 2.3.2 perform frontend keyword search
2. First page of multi page results are returned
3. Click next page of results
4. next page of search results are returned.

### Actual result (*)

![image](https://user-images.githubusercontent.com/3909886/67855191-41986400-fb12-11e9-93c9-1144cabc805a.png)

![image](https://user-images.githubusercontent.com/3909886/67855300-786e7a00-fb12-11e9-847b-1bb331dfae3d.png)

**I have applied the hotfix patch to /vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php**

`+        $this->collection->setPageSize(null);`

If I revert to my 2.3.2 image paginated elastic search works as expected.

**Comment by betooliveirame** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @betooliveirame. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @betooliveirame, here is your [Magento instance](https://i-25369-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25369-2-3-develop.instances.magento-community.engineering/admin](https://i-25369-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by betooliveirame** [comment]
fixed on #25378

**Comment by gaiterjones** [comment]
@betooliveirame what is the fix?

**Comment by gaiterjones** [comment]
I applied @pierzakp changes to Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::Apply and the problem still exists.

**Comment by pierzakp** [comment]
@gaiterjones can you dump your select query here or at least it's starting from where part?
Limit and offset on collection is set after:
`\Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::apply`
in:
`\Magento\Eav\Model\Entity\Collection\AbstractCollection::_loadEntities (line 1119)`.
If the `$this->_pageSize` is null and according to my change should be at this stage it should not be executed.

**Comment by gaiterjones** [comment]
@pierzakp if I log $query in \Magento\Eav\Model\Entity\Collection\AbstractCollection::_loadEntities there are many queries per search page reload to know which one you want. If I var_dump $this-`>searchResult->getItems() from \Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::apply on the second page of search results (../catalogsearch/result/index/?p=2&q=blue) I see an array with 24 elements (page size is 24). But get the no products found error.

**Comment by pierzakp** [comment]
@gaiterjones you are testing it in your local environment? Are you using xdebug? If yes please put a breakpoint in line 1119 in method `\Magento\Eav\Model\Entity\Collection\AbstractCollection::_loadEntities` or some logger, please check value of `$this->_pageSize`. Please check also that before 1119 line is executed if 
you check `$this->getSelect()->__toString()` there is no limit/offset in the query, after execution of this line it will be added.

**Comment by engcom-Charlie** [comment]
Hello @gaiterjones  
We are able to reproduce this issue on the lates 2.3-develop branch by provided steps.
But i have to close this issue as a duplicate of #25378 , because PR for this bug are in progress now.

Thanks for your report!
