### ISSUE TITLE
Oauth token Request results in error "cannot create request token because consumer token is not a verifier token"

### ISSUE THREAD

**Issue by bbraspenning** [magento/magento2#2540]
We send the following POST request to /oauth/token/request with in the header Autorization 

> > OAuth 
> > oauth_nonce="5A4856755A5868495330706F5A554E4759564E31", oauth_callback="oob", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1448631572", oauth_consumer_key="l7vs6fqtilnsmcpjn9rpqnmi4qgcdu93", oauth_signature="kCmZlP6mRwfI3aRPap0mmFB0Eds%3D", oauth_version="1.0" 

But we get back the following error

> > Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token

What does this mean? How to fix this?

**Comment by userException** [comment]
any updates on this ? I am also stuck on this issue

**Comment by okorshenko** [comment]
@bbraspenning , thank you for reporting the issue. Internal ticket MAGETWO-46678

**Comment by amansrivastava** [comment]
Any update on this ?
I'm also facing same error.

**Comment by bbraspenning** [comment]
I haven't found a solution on my own.  Last update was 7 days ago by okorshenko. ==>Internal ticket MAGETWO-46678.  I hope that will solve the issue eventually.

**Comment by okorshenko** [comment]
Internal ticket: MAGETWO-47296

**Comment by amansrivastava** [comment]
I got something regarding this.
Magento sends at time of activation
- Magento store URL. For example, http://my-magento-store.com/.
- oauth_verifier
- OAuth consumer key
- OAuth consumer key secret  
  to defined url while creating integration using POST method. You need to read these values and then try the steps again using recieved values.
  Check this again ... http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html#http-post
  Create a PHP script and read POST values and you will be able to get verifier token.  

This is not a bug, The flow should be well defined in documentation. Its lack of definition.

**Comment by keharper** [comment]
@amansrivastava Could you provide more detail about what needs to be fixed in the documentation?

**Comment by amansrivastava** [comment]
@keharper There should be a step by step guide for this. When I was trying to learn OAuth, I found it much confusing either due to complicated structure or insufficient information or tutorials available. 
If someone is just using OAuth integration provided by Magento2, he should get a step by step guide to configure it.
(Its my personal opinion after struggling for a week)

**Comment by IqbalMobarik** [comment]
I am also having this issue
when sending POST request to /oauth/token/request  I get back

Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token

What does this error mean? 

@amansrivastava : You say this is not an issue and  point back to the very poor Magento  documentation. It would be helpful if you say what you specifically saw in the original documentation that helped you get  to get round the issue. Or is your comment generally about oAuth ? 

Has anybody got past this error message?

**Comment by keharper** [comment]
I am working on updating the documentation. I believe the problem is that the page you specify in the Callback URL field in Admin is not extracting the verifier token. Magento sends this when you first click Activate in Admin.

**Comment by keharper** [comment]
@IqbalMobarik  @amansrivastava I've updated the docs. I hope to add some code samples next week. See http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html and http://devdocs.magento.com/guides/v2.0/howdoi/webapi/integration.html#integrate

**Comment by amansrivastava** [comment]
@keharper looks better now. I didn't get time to go in depth and I was already able to run it so steps are easily understandable for me now. I hope other newbies will be able to get help from it.

@IqbalMobarik try to trim the values you are passing in request.

**Comment by brianramseyau** [comment]
I have followed every step and still getting the original error posted here, it says nothing about using the Verifier in the linked documentation to get the Request token? I have added it to my string anyway and still getting the same failure response?

**Comment by brianramseyau** [comment]
UPDATE: this error occurs if you already have a request token created in Magento DB table oauth_token (if you're like me and developing an app and raising multiple requests), clear this table of its entries (request and verify) before retrying and this error disappears...

I feel that if you ask for another request token magento should create another not get upset that there is already a request token created... But that's just me...

**Comment by jmg** [comment]
Struggled with this for a while until applied the solution @EridianBrian proposed. Deleting entries from oauth_token worked for me. Thanks @EridianBrian!

**Comment by astorm** [comment]
@rgoncharuk This still feels like a bug.  While @EridianBrian and @jmg were able to "fix" this by deleting the tokens in `oauth_token`, the system shouldn't get in a state when failure to successfully  complete the request token process results in an unusable integration.

i.e.

1. System Owner (either directly or via a module) creates an integration, listed in `Stores -> Integration`
2. System owner requests activation of integration
3. Application/Service owner successfully receives oauth verifier token
4. Application/Service owner successfully makes request to `oauth/token/request`
5. For [uncontrollable reason x -- tokens expires, failure to capture result of `oauth/token/request`], Application/Service owner fails to call `oauth/token/access`
6. Application/Service owner tells system owner to reactivate

Based on my experience, and the experiences of @EridianBrian and @jmg above, if the system owner attempts to reactive they'll get back the same verifier token.  While the token's expiration will be reset, they **won't** be able to successfully fetch a new request token **without** the system owner manually clearing the old tokens from their tables. 

This means an Integration is rendered useless if the application/server owner fails to successfully get a response token on the first try.  This is bad for developer experience, and could also impact real world users.  This is a bug and should be fixed. 

/cc @piotrekkaminski

**Comment by magento-engcom-team** [comment]
@bbraspenning, thank you for your report.
The issue is already fixed in 2.1.10

**Comment by dbrekelmans** [comment]
@magento-engcom-team I am still experiencing this is **2.2.1**.
Solution by @EridianBrian still works.

**Comment by xi-ao** [comment]
And still experiencing this on **2.2.3**.

**Comment by fabis94** [comment]
Can confirm that this STILL happens on 2.3 when calling multiple 'Get a request token' requests in succession during development...

**Comment by aguszczin** [comment]
Is any news on this- still having this problem in 2.3

**Comment by cmple** [comment]
Any update on this? The issue still exists in v2.3.3.

Edit: **Resolved!** Turns out it was the callback URL of the application failing to load properly; in my case it was the Laravel's CSRF Token protection. I had to add the callback route to the `$except` parameter in `App\Http\Middleware\VerifyCsrfToken` in order for it to work.

**Comment by FrancescoG77** [comment]
Hi All,
I've Magento 2.3.4 but I got the same error
oauth_problem=Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token

I set an Integrations with ConsumerKey and ConsumerSecret.

In Stores -> Setting Oauth -> Expiration Period I need to enter value 1000000000000
If I leave default value (300) I got oauth_problem=Consumer+key+has+expired

Testing with Postman I have this error.

Anyone resolve it?
Best Regards,
Francesco

![magento2_oauth_cannot_create_request](https://user-images.githubusercontent.com/64022569/79766207-f3795600-8327-11ea-8f6e-6231dba4927c.jpg)

**Comment by elioncho** [comment]
Still happens in 2.4

**Comment by klaviyojad** [comment]
Im confused on all the above.  Is it being said that for the [/oauth/token/request ](https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-oauth.html#pre-auth-token) we have to pass verifier token too?  Its clear that we have to for [oauth/token/access](https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-oauth.html#get-access-token) but the Magento docs doesn't explicitly state that.

**Comment by vijendra-4** [comment]
Followed magento devdocs and fixed several issues found online before reaching here. Now completely stuck at this, no idea what to do.
oauth_problem=Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token
Deleting entries from [oauth_token] table doesn't help me, it generates a new error.
oauth_problem=A+token+with+consumer+ID+7+does+not+exist

After creating the integration, it was supposed to be two simple separate requests for fetching request token and access token. Why magento makes things tougher than they should be?

**Comment by msankhla** [comment]
Is this resolved ? I am not able to connect to oauth. Stuck on /oauth/token/request , where getting the same issue as posted originally: "oauth_problem=Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token"

**Comment by MeCapron** [comment]
Hi there,

there is something I completely do not understand. The only way to retrieve a *verifier token* is to activate the integration.

Doing so will create in the database a token with the type *verifier* in it so you can ask for a request token.

Howerver, if you want to retry to have another request token you will be prompted this error "Cannot create request token because consumer token is not a verifier token". Magento had overriden the token type.

The thing I don't understand is that the only way to create a verifier token is to exchange the tokens, meaning that this route is only called when the integration is activated. There is no public route to do so.

So, how can you consume the API if the consumer cannot manually recreate a new valid verifier token?

**Comment by jb-modist** [comment]
This is not resolved
- Activating an integration creates a verifier token (maybe clears old verifier tokens, maybe reuses one if it exists - doesn't really matter)
- Successfully requesting a request token will generate a request token
- At this point any attempt to create a request token again generates this error because both the verifier token and the request token are in the oauth_tokens table, and the create request token function just grabs whatever happens to match the consumer id and pulls the wrong one instead of specifically asking for the perfectly valid verifier token.
- Removing the request token matching the consumer_id resolves the issue.

**Comment by jeroenvermeulen** [comment]
Indeed this is still a bug.
When you have been trying some things with OAuth 1.0a you may keep receiving:
`oauth_problem=Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token`
The workaround for this bug is executing this query:
```sql
DELETE FROM `oauth_token` WHERE `type` = 'request';
```

**Comment by jianhuatu** [comment]
24年，这个错误依旧存在。
./app/code/Magento/Integration/Model/Oauth/Token/Provider.php
 public function createRequestToken($consumer)
if ($token->getType() != Token::TYPE_VERIFIER) {
            throw new \Magento\Framework\Oauth\Exception(
                __('Cannot create request token because consumer token is not a verifier token')
            );
        }

gettype => request. 
Token::TYPE_VERIFIER=> verifier
错误出现在这里，但是我不知道要怎么做

**Comment by key88sf** [comment]
@magento-engcom-team WHY is this issue closed? This is still a bug that is open.
