### ISSUE TITLE
Undefined index `product_id`

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25468]
### Preconditions (*)

1. 2 simple products
2. 1 bundle product with 1 bundle option containing 2 products as dropdown items

### Steps to reproduce (*)

1. Login to admin
2. Find bundle product and start editing
3. Scroll down to bundle items section and expand if not expanded
4. Click Add Option button twice
5. Select "checkbox" as the second item and fill the required fields. Assign the same products as already assigned to the first bundle option
6. Select "dropdown" as the third item and fill the required fields. Assign the same products as already assigned to the first bundle option
7. Drop the second bundle option
8. Save the product

Alternative way:
1. Test AdminCreateAndEditBundleProductOptionsNegativeTest is not skipped
2. Run test 

### Expected result (*)

1. Product successfully saved

### Actual result (*)

1. Undefined index `product_id`
![Magento AcceptanceTest _default Backend AdminCreateAndEditBundleProductSettingsNegativeTestCest AdminCreateAndEditBundleProductSettingsNegativeTest fail](https://user-images.githubusercontent.com/11827230/68136930-bca4b480-ff2e-11e9-9586-f420b92339f2.png)

Alternative:
```
no such element: Unable to locate element: {"method":"css selector","selector":"#messages div.message-success"}
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22855` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-25468-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25468-2-3-develop.instances.magento-community.engineering/admin](https://i-25468-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/magento2#25466 by @TomashKhamlai in 2.3-develop branch
Related commit(s):
 - [5c0f4da5993319c55a30117067e65e27cc5241f4](https://github.com/magento/magento2/commit/5c0f4da5993319c55a30117067e65e27cc5241f4)
 - [962fe8c016405e2f95180650fc1f7debc3aff5b7](https://github.com/magento/magento2/commit/962fe8c016405e2f95180650fc1f7debc3aff5b7)
 - [018a9d620c7d80c861fff97815652d94f39a117d](https://github.com/magento/magento2/commit/018a9d620c7d80c861fff97815652d94f39a117d)
 - [67f33c4c5db7f8b41aaf8111e53b7ac29d24702a](https://github.com/magento/magento2/commit/67f33c4c5db7f8b41aaf8111e53b7ac29d24702a)
 - [f60c70c01e760dabacfcbc846b5aa2dbfe94da3d](https://github.com/magento/magento2/commit/f60c70c01e760dabacfcbc846b5aa2dbfe94da3d)

The fix will be available with the upcoming 2.3.5 release.

**Comment by TomashKhamlai** [comment]
Bot closed the issue because of merged coverage. The issue is still reproducible and is ready for development.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/magento2#25466 by @TomashKhamlai in 2.3-develop branch
Related commit(s):
 - [5c0f4da5993319c55a30117067e65e27cc5241f4](https://github.com/magento/magento2/commit/5c0f4da5993319c55a30117067e65e27cc5241f4)
 - [962fe8c016405e2f95180650fc1f7debc3aff5b7](https://github.com/magento/magento2/commit/962fe8c016405e2f95180650fc1f7debc3aff5b7)
 - [018a9d620c7d80c861fff97815652d94f39a117d](https://github.com/magento/magento2/commit/018a9d620c7d80c861fff97815652d94f39a117d)
 - [67f33c4c5db7f8b41aaf8111e53b7ac29d24702a](https://github.com/magento/magento2/commit/67f33c4c5db7f8b41aaf8111e53b7ac29d24702a)
 - [f60c70c01e760dabacfcbc846b5aa2dbfe94da3d](https://github.com/magento/magento2/commit/f60c70c01e760dabacfcbc846b5aa2dbfe94da3d)

The fix will be available with the upcoming 2.3.5 release.

**Comment by TomashKhamlai** [comment]
Bot closed the issue because of merged coverage. The issue is still reproducible and is ready for development.

**Comment by TomashKhamlai** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](https://i-25468-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25468-2-3-develop.instances.magento-community.engineering/admin](https://i-25468-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22855` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by milindsingh** [comment]
I am working on this in #mm20in
