### ISSUE TITLE
Reorder issue with products that have custom options as checkbox.

### ISSUE THREAD

**Issue by nireshGTM** [magento/magento2#25558]
### Preconditions (*)

1. Magento 2.3.2 and Magento 2.3.3
2. Reordering an order with products that have custom options as checkbox(s).

### Steps to reproduce (*)

1. Create a product with custom option input type as Checkbox(Either Required or not)
2. Add this product to cart by checking the checkbox(s) and place an order.
(Now the order will be in pending state. Before any manual generation like Invoice, Shipment, Cretit Memo,.. user can Re-order successfully)
3. Create an Invoice or Shipment or Credit memo or Cancel the order.
4. Now click Reorder link of same Order either from the admin side or from the Customer dashboard.
4.a. Reorder from admin panel will goes to the Error page. "There has been an error processing your request".
![admin](https://user-images.githubusercontent.com/12773135/68597312-c3996d00-04c2-11ea-9516-4b989caa0f8d.png)

4.b. Reorder from Customer dashboard will be redirected to 'My Orders' page with message "The product's required option(s) weren't entered. Make sure the options are entered and try again."
![user](https://user-images.githubusercontent.com/12773135/68597354-d4e27980-04c2-11ea-9d41-359ae19ddb12.png)

File: vendor\magento\module-catalog\Model\Product\Option\Type\Select.php
Method : validateUserValue()
Note : As analysed the above method, the checkbox option values should be an array all the time. But on above specified case(steps 3 and 4) it is returned as string values so the validation fails and returns validation message.

### Expected result (*)

1. Products should be added to the shopping cart successfull.

### Actual result (*)

1. Failed to add product in cart with validation message(The product's required option(s) weren't entered. Make sure the options are entered and try again.).

**Comment by ghost** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @nireshGTM. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nireshGTM, here is your [Magento instance](https://i-25558-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25558-2-3-develop.instances.magento-community.engineering/admin](https://i-25558-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nireshGTM** [comment]
@magento-engcom-team 

> @nireshGTM do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no

Unable to reproduce this issue in 2.3-develop instance.
It seems this is already fixed in develop branch.

**Comment by ghost** [comment]
@magento-engcom-team 
Unable to reproduce on 2.3-develop instance. It seems issue is fixed in 2.3-develop branch on another similar case with multiple checkbox (https://github.com/magento/magento2/commit/1acde36b19b177b58af916557a3d41dfe0612cc0).

**Comment by patv81** [comment]
@magento-engcom-team 
This issue still not resolve.
- Magento 2.4.5-p2
- Reordering an order with products that have custom options as checkbox(s).
- Only choose one option list checkbox
Step to reproduce.
1. Create a product (simple or virtual)  with custom option (optional or require) input type as Checkbox .
2. Login to customer account
3. In the product page detail only choose 1 option in list checkbox and add to cart.
4. Place order by check mo payment method
5. In customer dashboard click reorder. This error display
![image](https://github.com/magento/magento2/assets/49557978/b7dd6a91-7b5c-42a4-9bff-81dffaa8f2d2)
