### ISSUE TITLE
Can't select new configurable product template (attribute set).

### ISSUE THREAD

**Issue by cfcnn** [magento/magento2#2567]
Hello, 
When adding new configurable products as magento user guide,  I can not select product template (attribute set ) for configurable products, it works for other product types except configurable products.
Please help fix this. 
Thanks and regards.

![can t select template](https://cloud.githubusercontent.com/assets/15027055/11489146/a1ac6278-9807-11e5-9a9c-d8d3fb8e233d.png)

**Comment by duerstd** [comment]
+1

Workaround: Create simple product, and make it to a configurable product.

**Comment by katmoon** [comment]
Hi,

Thanks for reporting the problem and for the workaround.
Internal ticket is MAGETWO-46877

**Comment by EyeWeb** [comment]
+1 noticed this also

**Comment by vzabaznov** [comment]
Hi @cfcnn issue was fixed and delivired, feel free to write here or to open new one if not, thank you for reporting

**Comment by bertvanernie** [comment]
Sorry to drop in on this closed thread but i'm really curious where the fix is delivered?

**Comment by katmoon** [comment]
The fix has been delivered in the current repo: https://github.com/magento/magento2/commit/06bf463bfa8e1a9d185

**Comment by TKlement** [comment]
We are working with version 2.0.7 and the bug is still there.
While adding a configurable product the attribute set will be disabled when page has finished loading.
Can you confirm that?

**Comment by katmoon** [comment]
Hi @TKlement 
The bug was fixed in develop branch and will be available with 2.1 release soon. Alternatively you can manually apply the fix. 
`2.0.7` version is actually `2.0` + most critical issues.

**Comment by imbpp123** [comment]
Bug still exists in 2.1.0 version that i installed using composer. I dont think that you can fix it just adding @param comment to constructor...

**Comment by shashankitsoft** [comment]
I am also facing the same issue on Magento 2.0.9. Amazing it not fixed till this version.

**Comment by johnny-longneck** [comment]
I installed a fresh 2.2.0-dev version. This is still an issue. I can't believe it. I cannot edit my configurable product. Tried to remove the "disabled=true" from the DOM but that didn't do the trick, but that would have been too easy. Anyone taking care of this?
