### ISSUE TITLE
DOMDocument::loadHTML(): Tag date invalid in Entity

### ISSUE THREAD

**Issue by nghelo** [magento/magento2#25738]
### Preconditions (*)

1. Magento 2.3.3 or 2.3-develop
2. Simple Product is created.
3. Customer is created and logged

### Steps to reproduce (*)

1. Add product to cart
2. Place Order
3. Click on the order number
![order](https://user-images.githubusercontent.com/51681435/69724841-6689f200-1125-11ea-8db0-b197d83b8cc0.png)
4. The url is (/sales/order/view/order_id/<order_id>/)
5. See exception.log
### Expected result (*)
No new exception log entries

### Actual result (*)
New Exception Log Entry
![DOM](https://user-images.githubusercontent.com/51681435/69725116-11021500-1126-11ea-9ff2-14e0a5bb176c.png)

### Possible fix
in /module-sales/view/frontend/templates/order/order_date.phtml change "date" tag with "span"

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29223` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by TimQSO** [comment]
> in /module-sales/view/frontend/templates/order/order_date.phtml change "date" tag with "span"

I can confirm this solves the exception error.

**Comment by monotheist** [comment]
@GuiltyNL You mean like below. Replace "date" with "/span"

```
<div class="order-date">
    <?= $block->escapeHtml(__('<span class="label">Order Date:</span> %1', '</span>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</date>'), ['span', 'date']) ?>
</div>

```

**Comment by TimQSO** [comment]
No like this:

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="order-date">
    <?= $block->escapeHtml(__('<span class="label">Order Date:</span> %1', '<span>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</span>'), ['span', 'date']) ?>
</div>
```

**Comment by AndyJAllen** [comment]
I also receive this error when navigating to 'customer/account/'...the page mostly breaks and just displays a white background with the table of orders.
![image](https://user-images.githubusercontent.com/19735797/75344930-a6b65900-5869-11ea-9ebd-516a910d8d25.png)

`main.CRITICAL: DOMDocument::loadHTML(): Tag date invalid in Entity, line: 1 {"exception":"[object] (InvalidArgumentException(code: 2): DOMDocument::loadHTML(): Tag date invalid in Entity, line: 1 at ./public_html/vendor/magento/framework/Escaper.php:89)"} []`

**Comment by magento-engcom-team** [comment]
Hi @nghelo. Thank you for your report. 
The issue has been fixed in magento/magento2#25895 by @AndreyChorniy in 2.4-develop branch
Related commit(s):
 - [1764aa8d357557ca5487ca211828e8c5e9e46137](https://github.com/magento/magento2/commit/1764aa8d357557ca5487ca211828e8c5e9e46137)
 - [e537a76055864b4e3c17f21beb745cab276ec849](https://github.com/magento/magento2/commit/e537a76055864b4e3c17f21beb745cab276ec849)

The fix will be available with the upcoming 2.4.0 release.

**Comment by lewisje** [comment]
I realize that you already made a relevant change about 5 weeks ago, but it would be more semantic if the [`<time>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) were used.

Here's a variant that also depends on making `datetime` an allowed attribute in `\Magento\Framework\Escaper`:

```php
<?php $orderDateTime = (new \DateTime($block->getOrder()->getCreatedAt())); ?>
<div class="order-date">
    <?= $block->escapeHtml(__('<span class="label">Order Date:</span> %1', '<time datetime="' . $orderDateTime->format('c') . '">' . $block->formatDate($orderDateTime, \IntlDateFormatter::LONG) . '</time>'), ['span', 'time']) ?>
</div>
```

Here's a variant that doesn't depend on making `datetime` allowed and is much simpler:

```php
<div class="order-date">
    <?= $block->escapeHtml(__('<span class="label">Order Date:</span> %1', '<time>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</time>'), ['span', 'time']) ?>
</div>
```

**Comment by djamps** [comment]
@lewisje I tried your solution and still receive the same exception.   The original solution is still the answer.

**Comment by lewisje** [comment]
That is quite surprising: It doesn't allow `<time>` either, even though that is a valid HTML5 element; it's not something banned in the `Escaper` class, so it must be a problem in PHP.

**Comment by alxvieira** [comment]
I upgraded from 2.3.3 to 2.3.4 and then from 2.3.4 to 2.3.5 and I still have the same error.
My shopping cart are international language.

Can anyone give me a tip?

**Comment by plastikschnitzer** [comment]
I had the same issue and I can confirm https://github.com/magento/magento2/issues/25738#issuecomment-577567970 is working for me. Version 2.3.5-p1.
