### ISSUE TITLE
Arabic invoice pdf issue Magento 2.3.0 showing as Arabic letters but not correct 

### ISSUE THREAD

**Issue by bibin-alwafaa** [magento/magento2#25769]
### Preconditions (*)
Magento 2.3.0 & 2.3-develop
The store should be in Arabic

### Steps to reproduce (*)
1) Place an order in Arabic store 
2) Customer fill the address and name all in Arabic 
3) Login to the admin panel and open orders 
4) Create an invoice against the order 
5) Download the invoice pdf and compare the content in the admin side with the invoice pdf 

### Expected result (*)
same as content below 
eg: الإسم	ابو بدر المطيري 
![image](https://user-images.githubusercontent.com/58136137/69727778-98f31980-113c-11ea-961a-24c266c37b00.png)

### Actual result (*)
here it's showing in different data
eg : يريطملا ردب وبا 
![image](https://user-images.githubusercontent.com/58136137/69727956-f2f3df00-113c-11ea-9a0b-18d659844037.png)

**Comment by AnnaShepa** [comment]
Hi @Alwafaa123 thank you for the report. Please provide more information. I don't see what the problem you have exactly. More information about reporting you can find [here](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by bibin-alwafaa** [comment]
Preconditions (*)
Magento 2.3.0
The store should be in Arabic
Steps to reproduce (*)
1) Place an order in Arabic store 
2) Customer fill the address and name all in Arabic 
3) Login to the admin panel and open orders 
4) Create an invoice against the order 
5) Download the invoice pdf and compare the content in the admin side with the invoice pdf 
Expected result (*)
same as content below 
eg: الإسم	ابو بدر المطيري 
![image](https://user-images.githubusercontent.com/58136137/69727778-98f31980-113c-11ea-961a-24c266c37b00.png)
Actual result (*) 
here it's showing in different data
eg : يريطملا ردب وبا 
![image](https://user-images.githubusercontent.com/58136137/69727956-f2f3df00-113c-11ea-9a0b-18d659844037.png)

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25769-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25769-2-3-develop.instances.magento-community.engineering/admin](https://i-25769-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by staniag** [comment]
@magento i am working on it

**Comment by bibin-alwafaa** [comment]
@sagaltsev got any solution?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29274` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bibin-alwafaa** [comment]
@engcom-Charlie issue has been resolved?

**Comment by engcom-Charlie** [comment]
@Alwafaa123 we have to wait when some developer will assign this ticket

**Comment by bibin-alwafaa** [comment]
@engcom-Charlie how can we solve the issue? any idea?

**Comment by engcom-Charlie** [comment]
@Alwafaa123 sorry, but i have no idea.

**Comment by fisal77** [comment]
Also, I have the same problem. Do you have any solution or update?

**Comment by bibin-alwafaa** [comment]
@fisal77 not yet waiting for the fix. Let me know if you have any idea about the same.

**Comment by imrandotftr** [comment]
@Alwafaa123 , @fisal77 

Zend pdf library doesn't support Arabic language RTL, if you will check the content from left to right you will found that content is good just direction is changed.

**Comment by fisal77** [comment]
@Alwafaa123 

In this case ... I am very sorry to inform you that Magento is built using Zend framework,
and unfortunately, there are many problems in supporting Arabic, especially in the Zend PDF.

that’s why we use TCPDF http://www.tcpdf.org/

but in your case you have two options as I see:

1st option is create new module with Zend Drawer & TCPDF to support Arabic Characters and solving the reversed characters problem… but  some information are fixed.

 

2nd option with highly recommended from me.. is using this extension

https://www.magetrend.com/magento-2-pdf-invoice

with this extension you can create new templates for (invoice,shipment,order,credit memo).

I have use it a lot .. and it’s really good.

 

I hope my reply is clear to you.

**Comment by magento-engcom-team** [comment]
Hi @Alwafaa123. Thank you for your report. 
The issue has been fixed in magento/magento2#27887 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [41ab016487843b3e19d339111e719f6916816082](https://github.com/magento/magento2/commit/41ab016487843b3e19d339111e719f6916816082)
 - [876519b67486f0d49649fa60105b3dc60bf11c20](https://github.com/magento/magento2/commit/876519b67486f0d49649fa60105b3dc60bf11c20)
 - [27ec0ae0adb8d14b2ea90b537c58e221cfa5ef1f](https://github.com/magento/magento2/commit/27ec0ae0adb8d14b2ea90b537c58e221cfa5ef1f)

The fix will be available with the upcoming 2.4.0 release.

**Comment by ammarabdulsalam** [comment]
After testing the update, The problem still exists.
The Arabic letters now in correct order, but letters disjointed.

**Comment by ihor-sviziev** [comment]
Hi @ammarabdulsalam,
Could you report new issue with exact steps to reproduce with linking to this one? Unfortunately I just googled examples somewhere in internet and it looked to me as good enough solution.

**Comment by EhabAmawi** [comment]
@ihor-sviziev 
isn't there a current solution for this problem I just updated to Magento 2.4 put as @ammarabdulsalam said the Arabic letters are disjointed

**Comment by ihor-sviziev** [comment]
@EhabAmawi @ammarabdulsalam could you report a separate issue with the exact steps to reproduce and data that currently works incorrectly?

**Comment by asma-postpay** [comment]
> @ihor-sviziev isn't there a current solution for this problem I just updated to Magento 2.4 put as @ammarabdulsalam said the Arabic letters are disjointed

Hi Ehab, do you have any solution for this problem ?
