### ISSUE TITLE
Either “offers”, “review”, or “aggregateRating” should be specified

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#26254]
### Preconditions (*)

1. Magento 2.3.3

 ### Steps to reproduce (*)

1.  Log in to google search console
2. Go to products section

### Expected result (*)

1. No errors in search console

### Actual result (*)

1. Error: Either “offers”, “review”, or “aggregateRating” should be specified

**Comment by Jilco** [comment]
@magento-engcom-team it is not possible to reproduce on vanilla instance

**Comment by rav-redchamps** [comment]
@Jilco You might try repeating it using this https://search.google.com/structured-data/testing-tool/u/0/

Create a product on the vanilla instance and test product URL on this tool

**Comment by devchris79** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @devchris79. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @devchris79, here is your [Magento instance](https://i-26254-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26254-2-4-develop.instances.magento-community.engineering/admin](https://i-26254-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devchris79** [comment]
Issue still causes warnings from Google with Magento 2.4 develop instance:

![image](https://user-images.githubusercontent.com/43850303/71891959-adfd9800-313f-11ea-9626-2785bd27e808.png)

Google have been sending us emails for our site (2.3.3) wanting an updated product schema.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30404` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jesperbrejning** [comment]
we see the same issues

**Comment by tuyennn** [comment]
This issue was exist since Magento 2.1.x

**Comment by j-robin-hunter** [comment]
This is an issue with products that are not simple products but, for example, configurable products. The schema for such products does not generate either the offers, review or aggregateRating if the product has not been reviewed or rated. The configurable product does not have an offer either, perhaps because it is not configured?

**Comment by katesuykovskaya** [comment]
I;m gettong such comment for a bundle product that is out of stock - in this case section with bundle options is not present, as well as final/configured price block. And itemprop="offers" is added to the configured price block
Hope such case will help

**Comment by btekbtek** [comment]
For me exsist when signle product, magento 2.4.1

**Comment by oviliz** [comment]
This is a serious issue as it renders the products invalid and not eligible for Google Search's rich results...

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by ihor-sviziev** [comment]
Hi @Jilco,
It looks like the issue was already fixed in the 2.4-develop branch by the following PR https://github.com/magento/magento2/pull/34207.

Could you confirm that?

**Comment by Jilco** [comment]
Ihor,

In 2.4.3-p1 it is still present...

Regards Jilco

________________________________
Van: Ihor Sviziev ***@***.***>
Verzonden: maandag 27 december 2021 14:49
Aan: magento/magento2 ***@***.***>
CC: Jilco ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [magento/magento2] Either “offers”, “review”, or “aggregateRating” should be specified (#26254)


Hi @Jilco<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJilco&data=04%7C01%7C%7C7b1a93b9a6314980ed0708d9c9433bd3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762112871241966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MX9vqZndpUO0MKRnphlW15ISlFLcMdQDsmvrZnYmR60%3D&reserved=0>,
It looks like the issue was already fixed in the 2.4-develop branch by the following PR #34207<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmagento%2Fmagento2%2Fpull%2F34207&data=04%7C01%7C%7C7b1a93b9a6314980ed0708d9c9433bd3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762112871241966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kjXjVLrXuuVnw9Z7QnJWnEP0Cmyglks2xBDaKsifigE%3D&reserved=0>.

Could you confirm that?

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmagento%2Fmagento2%2Fissues%2F26254%23issuecomment-1001578689&data=04%7C01%7C%7C7b1a93b9a6314980ed0708d9c9433bd3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762112871241966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=44EvsAEvVfTRaIONIivoWpBYO7W8CZAjX0hKkmNvExE%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFVAYGW4L63CC6LRKCFXP7DUTBVHJANCNFSM4KCOGG4A&data=04%7C01%7C%7C7b1a93b9a6314980ed0708d9c9433bd3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762112871241966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dd8%2BFnEJazLAARNjUohBl5%2FXJPwwroG2RbWm%2BZh5iZc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C7b1a93b9a6314980ed0708d9c9433bd3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762112871241966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jbKHVWQuiF4ElvZ5fCnsLwQTm5TW5Kv4Te5KsNaFU%2BY%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C7b1a93b9a6314980ed0708d9c9433bd3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762112871398212%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z6xJq2M9Z0QYTFvpljAt4sFeIY7PDpKz2KiXsVWlCDQ%3D&reserved=0>.

**Comment by ihor-sviziev** [comment]
@Jilco, it's still not available in the stable version. You can check it directly on 2.4-develop branch, or apply the changes from that pull request as a patch

**Comment by faminaAlam** [comment]
Still facing the problem
