### ISSUE TITLE
Paypal issue with region on 2.3.4

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#26698]
### Preconditions (*)

1. Magento 2.3.4 & 2.4-develop
2. Clean version, vanilla, with sample data only
3. PHP 7.2.26
4. Paypal Express Checkout

### Steps to reproduce (*)

1. Enable paypal w/o review (haven't tried with review)
2. Add product to cart as guest or logged in (doesn't matter)
3. Go to checkout
4. Enter your shipping address to be in UK for example and enter some state, I used Nottinghamshire
5. Place order, confirm from paypal side
6. You will get error 500

### Expected result (*)

1. Successfully placed order

### Actual result (*)

1. Error 500: NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in httpdocs/vendor/magento/module-paypal/Model/Api/Nvp.php:1527

When I ported back code from 2.3.3 for _applyStreetAndRegionWorkarounds function, it worked.

$regions->getItems() in _applyStreetAndRegionWorkarounds  is empty.

**Comment by justStanislav** [comment]
Same problem

**Comment by medigeek** [comment]
happens to us too after a manual upgrade of enterprise edition. @kerlama @justStanislav are you using enterprise edition of magento2?

**Comment by kerlama** [comment]
@medigeek no, I am on open source one.

**Comment by justStanislav** [comment]
@medigeek no, community.

**Comment by medigeek** [comment]
@kerlama @justStanislav did you use manual upgrade or composer upgrade?
@fascinosum could you have a look at this please? some changes were introduced in Nvp.php ( https://github.com/magento/magento2/commit/42c26724382bcafe0ccdc84cc9fe53427891aadd ) that affect the paypal module, instead of a success page we end up with http error 500 and the error kerlama mentioned in the logs.

**Comment by kerlama** [comment]
@medigeek composer upgrade from 2.3.3.

**Comment by justStanislav** [comment]
@medigeek same way like @kerlama

**Comment by medigeek** [comment]
Thank you both. :) @kerlama I see you have already tested this on a vanilla installation as you have originally posted. I'm not sure if you can reply to the @magento bot "yes" or tick it, don't know how this github bots work heh.
Let's wait on @fascinosum or someone else to check this out.

**Comment by kerlama** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kerlama. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by noeli-eshopguru** [comment]
Hello
I upgraded Enterprise Edition 2.3.3 to 2.3.4 manually. Then I got the same error.
HTTP Error 500
Also I can see an error in Nvp.php:1524.

**Comment by magento-engcom-team** [comment]
Hi @kerlama, here is your [Magento instance](https://i-26698-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26698-2-4-develop.instances.magento-community.engineering/admin_8452](https://i-26698-2-4-develop.instances.magento-community.engineering/admin_8452)
Login: `5d6faf61` Password: `c38757c25a07`
Instance will be terminated in up to 3 hours.

**Comment by kerlama** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @kerlama. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @kerlama, here is your [Magento instance](https://i-26698-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-26698-2-3-4.instances.magento-community.engineering/admin_352b](https://i-26698-2-3-4.instances.magento-community.engineering/admin_352b)
Login: `45be4a03` Password: `9a705053948c`
Instance will be terminated in up to 3 hours.

**Comment by noeli-eshopguru** [comment]
Hi, I replaced some codes in function _applyStreetAndRegionWorkarounds(DataObject $address) to ones of 2.3.3.
            - $regionItems = $regions->getItems();
            - $region = array_shift($regionItems);
            - $address->setRegionId($region->getId());
            - $address->setExportedKeys(array_merge($address->getExportedKeys(), ['region_id']));

            + foreach ($regions as $region) {
               + $address->setRegionId($region->getId());
               + $address->setExportedKeys(array_merge($address->getExportedKeys(), ['region_id']));
               + break;
           + }
Then tested again. So it worked, but it was redirected to the order review page.
I can see the error message on the page and can't place the order.
![image](https://user-images.githubusercontent.com/50664110/73935867-82c3bf80-491c-11ea-9e29-04359e64302c.png)

Any idea?

**Comment by kerlama** [comment]
@noeli-eshopguru  code from 2.3.3 works fine for me (_applyStreetAndRegionWorkarounds).

**Comment by kerlama** [comment]
@magento-engcom-team I was able to reproduce the issue on clean instance you gave me.

![Screenshot_15](https://user-images.githubusercontent.com/4161312/73936105-5be89780-48e2-11ea-9a34-dfd3ba453e75.png)

**Comment by noeli-eshopguru** [comment]
Hi @kerlama but why am I getting the error on the order review page?
And I have already enabled the review page skip option on the paypal settings.
Are you moving to the order success page correctly?

**Comment by kerlama** [comment]
@noeli-eshopguru yes, for me its working fine, payment is charged and I am redirected to success page.

**Comment by noeli-eshopguru** [comment]
Hi @kerlama, do you have any idea with my error?

**Comment by kerlama** [comment]
@noeli-eshopguru not sure, there are few places where this exception is thrown, see at which one it fails and then check if you have any custom observer which might affect on it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31196` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by fascinosum** [comment]
@kerlama, @medigeek, thank you
@odubovyk, you may have more information as the author of these changes. Could you have a look at this issue?

**Comment by stu583** [comment]
Also experiencing on 2.3.4 CE. Composer upgrade from 2.3.3 on 10 Feb.

Order success as expected when using Safari, IE, Edge.  However we are receiving a 500 Error when using the chrome browser across Windows/OSX/IOS platforms. Browser history’s/cookies cleared, Magento cache cleared/flushed but bug persists.

Debug currently switched on and will continue looking tomorrow and will update if I find anything.

**Comment by ajwalks** [comment]
Upgraded from 2.3.3 > 2.3.4 via composer and similar issue. 
At first I thought it was JS Bundling that I had enabled.
Im using Paypal Standard.
When returning from Paypal to site get blank page with url of /paypal/express/return/?token=XXXXXXXXXX&PayerID=XXXXXXXXXX

Error log shows:
`[11-Feb-2020 16:36:10 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/public_html/vendor/magento/module-paypal/Model/Api/Nvp.php:1524
Stack trace:
#0 /home/public_html/vendor/magento/module-paypal/Model/Api/Nvp.php(1493): Magento\Paypal\Model\Api\Nvp->_applyStreetAndRegionWorkarounds(Object(Magento\Framework\DataObject))
#1 /home/public_html/vendor/magento/module-paypal/Model/Api/Nvp.php(849): Magento\Paypal\Model\Api\Nvp->_exportAddresses(Array)
#2 /home/public_html/vendor/magento/module-paypal/Model/Express/Checkout.php(621): Magento\Paypal\Model\Api\Nvp->callGetExpressCheckoutDetails()
#3 /home/public_html/vendor/magento/module-paypal/Controller/Express/AbstractExpress/ReturnAction.php(32): Magento\Paypal\Model\Express\Checkout->returnFromPaypal('EC-9JN953126P91...')
#4 /home/public_html/vendor/magento/framework/App/Action/Action.php(108): Magento\Paypal\Controller\Express\AbstractExpress\ReturnAction->execute()
#5 /home/ in /home/public_html/vendor/magento/module-paypal/Model/Api/Nvp.php on line 1524`

**Comment by jackrevate** [comment]
Having the same issue, causing a lot of website sales to go!

Anyone found a fix? need it asap!

I don't get how Magento release something that's so dam buggy!

**Comment by kerlama** [comment]
> Having the same issue, causing a lot of website sales to go!
> 
> Anyone found a fix? need it asap!
> 
> I don't get how Magento release something that's so dam buggy!

Revert back the function **_applyStreetAndRegionWorkarounds** from 2.3.3 in vendor/magento/module-paypal/Model/Api/Nvp.php

**Comment by stu583** [comment]
@jackrevate

I can confirm that @joridos fix is working for us.

He has been unable to merge due to an error but it appears the error is at line 1618 which was already part of 3.2.4 core and he hasn't even touched!

**Comment by joridos** [comment]
@stu583 yes, the only one error is on a method that I haven't changed

**Comment by stu583** [comment]
@joridos 

Yes I had a look and its very odd. I agree that it's not anywhere near the the method you edited. Maybe already buggy, shouldn't have passed previously and never have made the 2.3.4? I don't know.

Like I said its working perfectly for us. We are taking PayPal payments, in production, with no problems since applying your fix. Thanks for the contribution. 🙂

**Comment by ajwalks** [comment]
Yes @joridos fix works for us also. Thank you

**Comment by jackrevate** [comment]
Sorry guys, I'm not as clued up as others are.

I can't work out the exact line or code you're editing. Could someone break it down by each line/code I need to replace from 2.3.3 - sorry for being stupid, I'm not clued up on this but would really appreciate someones help/time to write up what needs to be changed in the files as I really would like paypal to work again.

Many thanks.

**Comment by jackrevate** [comment]
I've made the following changes, it works - but would like someone to confirm I've done the correct changes please! :)
`	    protected function _applyStreetAndRegionWorkarounds(DataObject $address)`

to this:

`    protected function _applyStreetAndRegionWorkarounds(\Magento\Framework\DataObject $address)`

Along with changing this: 
`	            $regionItems = $regions->getItems();
            $region = array_shift($regionItems);
            $address->setRegionId($region->getId());
            $address->setExportedKeys(array_merge($address->getExportedKeys(), ['region_id']));`

to this:
`	            foreach ($regions as $region) {	
                $address->setRegionId($region->getId());	
                $address->setExportedKeys(array_merge($address->getExportedKeys(), ['region_id']));	
                break;	
            }`

**Comment by jackrevate** [comment]
I've made the following changes, did a test order and it worked so I assume I've made the correct changes from the 2.3.3 file - but would like someone to confirm I've done the correct changes please!

My code is below, assuming nothing else needed changed!

`
	    protected function _applyStreetAndRegionWorkarounds(\Magento\Framework\DataObject $address)
    {
        // merge street addresses into 1
        if ($address->getData('street2') !== null) {
            $address->setStreet(implode("\n", [$address->getData('street'), $address->getData('street2')]));
            $address->unsetData('street2');
        }
        // attempt to fetch region_id from directory
        if ($address->getCountryId() && $address->getRegion()) {
            $regions = $this->_countryFactory->create()->loadByCode(
                $address->getCountryId()
            )->getRegionCollection()->addRegionCodeOrNameFilter(
                $address->getRegion()
            )->setPageSize(
                1
            );
	            foreach ($regions as $region) {	
                $address->setRegionId($region->getId());	
                $address->setExportedKeys(array_merge($address->getExportedKeys(), ['region_id']));	
                break;	
            }
        }
    }
`

**Comment by maxxeh1** [comment]
Personally I am getting very tired of issues arising in patch versions of Magento. 2.3.4 has introduced two major payment bugs - one for Paypal which should NOT have happened and one for certain third party vendor payment methods, such as Magenticity SagePay, see here: [2.3.4 Checkout Infinite Loop](https://github.com/magento/magento2/issues/26786). How does this happen?!

**Comment by hostep** [comment]
It looks like Magento has released a hotfix for this problem on: https://magento.com/tech-resources/download#download2353

Maybe somebody running into this issue can test and report back if this fixes it for them?

**Comment by magento-engcom-team** [comment]
Hi @kerlama. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3.4-p1-develop` branch(es).
Related commit(s):
 - [3d7db6f4fbfe381414b8d19c4a489d71df553f36](https://github.com/magento/magento2/commit/3d7db6f4fbfe381414b8d19c4a489d71df553f36)

The fix will be available with the upcoming `2.3.5` release.

**Comment by Emilietrepanier** [comment]
The patch did not fix it for me.
before I had an: internal Error..... Report ID: webapi
and now the an: Infiniteloo detected, review the trace for the looping path

**Comment by jackrevate** [comment]
Infinite loop detected appeared due to a third party extension 'Stripe' - they have released a newer version.

**Comment by Grumag** [comment]
@jackrevate This is happening to sites that do not have Stripe installed at all.  We have the same issue after upgrade to 2.3.4. Tried the the patch and it didn't do anything. 

This is NOT fixed.

**Comment by Emilietrepanier** [comment]
We do not have stripe either and found that 1 third party tier pricing module was responsible.

**Comment by Grumag** [comment]
@Emilietrepanier Is it maybe from MageWorx, as we do have their extension installed, to add fees.

**Comment by Emilietrepanier** [comment]
@Grumag For us it was Blue Jalapeno Tier Pricing

**Comment by magento-engcom-team** [comment]
Hi @kerlama. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [92d178479561187cd22e810e90b28fbb67507640](https://github.com/magento/magento2/commit/92d178479561187cd22e810e90b28fbb67507640)
 - [f6cfd3a89a57786eb53eed451e120cc358b2f789](https://github.com/magento/magento2/commit/f6cfd3a89a57786eb53eed451e120cc358b2f789)

The fix will be available with the upcoming `2.3.5` release.

**Comment by diazwatson** [comment]
I have tested applying the patch @hostep mentioned in 2.3.4 Cloud instance and it works

**Comment by achleitner** [comment]
Anyone has a fix for this that actually works. Getting a http error instead of the magento success page with paypal express and braintree/paypal module. Nothing in this thread actually works. Thanks

**Comment by magento-engcom-team** [comment]
Hi @kerlama. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [8a73e53ee369b24b95e3c94bc379ce48856ee8ca](https://github.com/magento/magento2/commit/8a73e53ee369b24b95e3c94bc379ce48856ee8ca)
 - [9948da7e013245ec3af6f6e7633ffa08a12b4ad9](https://github.com/magento/magento2/commit/9948da7e013245ec3af6f6e7633ffa08a12b4ad9)

The fix will be available with the upcoming `2.4.0` release.

**Comment by johnorourke** [comment]
> @Grumag For us it was Blue Jalapeno Tier Pricing

Did you find a fix? I use this module.

**Comment by aymansabi** [comment]
Any solution>?

 Failed to connect to 127.0.0.1 port 808: Connection refused at /home/luckyeyesinc/public_html/vendor/magento/module-paypal/Model/Api/Nvp.php:1215)"} []

**Comment by Jeeva-Rathinam** [comment]
> Hello
> I upgraded Enterprise Edition 2.3.3 to 2.3.4 manually. Then I got the same error.
> HTTP Error 500
> Also I can see an error in Nvp.php:1524.

Did you find any solution?

**Comment by Jeeva-Rathinam** [comment]
@noeli-eshopguru Are you directly update code or using any model or preference to achieve this edit? 

FYI - I am using multi-website, website 1 for USA website 2 for Australia i am using Paypal for my MultiWebsite, here website 1(USA) working good, website 2(Australia) getting error. 

Error: If my website 2 customer tries to pay PayPal getting the following error, but website 1 PayPal working well.

Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/test/app/code/Magento/Paypal/Model/Api/Nvp.php:1524

The Conclusion, shall i go with patch or edit code (What is the recommended way to edit the file)?

**Comment by Jeeva-Rathinam** [comment]
Does anyone have a solution?

**Comment by chatlourd** [comment]
@magento-engcom-team I'm getting the same error in **2.4.1** can anyone else confirm? 

I get the error below when trying to apply the patch `PayPal_Express_Checkout_issue_fix_2.3.4_composer-2020-02-13-12-34-09.patch` probably because it's a 2.3.4 patch and I'm on 2.4.1 - can anyone  #help?

`
patching file vendor/magento/module-paypal/Model/Api/Nvp.php
Hunk #1 FAILED at 1512.
Hunk #2 FAILED at 1624.
Hunk #3 FAILED at 1653.
Hunk #4 FAILED at 1694.
Hunk #5 FAILED at 1712.
5 out of 5 hunks FAILED -- saving rejects to file vendor/magento/module-paypal/Model/Api/Nvp.php.rej
`

**Comment by gianisimone** [comment]
The error is still there with Magento Community Edition 2.3.7. Unbelievable
