### ISSUE TITLE
Missing JS file (critical-css-loader) in Magento 2.3.4

### ISSUE THREAD

**Issue by Sathishkumar8731** [magento/magento2#26963]
### Preconditions (*)

1. Magento 2.3.4
2. MYSQL 5.6
3. PHP 7.2.X

### Steps to reproduce (*)

1. Go to the File Path: app/code/Magento/Theme/view/frontend/requirejs-config.js
2. Open the "requirejs-config.js" file and you can find below code in Mapper section

`'criticalCssLoader':      'Magento_Theme/js/view/critical-css-loader', `

3. Whereas, critical-css-loader js file should be available in the file path: app/code/Magento/Theme/view/frontend/web/js/view
### Expected result (*)

1. Loader should need to show while calling criticalcss

### Actual result (*)

1. Loader is not working and unable to customize it on Custom them.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32088` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Sathishkumar8731. Thank you for your report. 
The issue has been fixed in magento/magento2#26987 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [e2c403fa3d9fcaa2341214218e35889b4e83b0b8](https://github.com/magento/magento2/commit/e2c403fa3d9fcaa2341214218e35889b4e83b0b8)
 - [eee02627f468d04d24530ddde87ad30f02cee15e](https://github.com/magento/magento2/commit/eee02627f468d04d24530ddde87ad30f02cee15e)
 - [befbca488671ea50343801ee1232bef4ee066e22](https://github.com/magento/magento2/commit/befbca488671ea50343801ee1232bef4ee066e22)
 - [e22c47c6dce745162a5df8a88873f7f08fb8e290](https://github.com/magento/magento2/commit/e22c47c6dce745162a5df8a88873f7f08fb8e290)
 - [a3218fe7b4b8479f1e4ce2d1d5180a80e3245f12](https://github.com/magento/magento2/commit/a3218fe7b4b8479f1e4ce2d1d5180a80e3245f12)
 - [f98537d818f4dd894a7ba36ef3d56c5865d65ac1](https://github.com/magento/magento2/commit/f98537d818f4dd894a7ba36ef3d56c5865d65ac1)
 - [339c099c79b183c0a8caca37e2caa8b60d276a49](https://github.com/magento/magento2/commit/339c099c79b183c0a8caca37e2caa8b60d276a49)
 - [5843df461626ac32230c2425d07f60b480637333](https://github.com/magento/magento2/commit/5843df461626ac32230c2425d07f60b480637333)
 - [abad8db69e9b66d8b32be10d38e283c09ebd2d72](https://github.com/magento/magento2/commit/abad8db69e9b66d8b32be10d38e283c09ebd2d72)
 - [c40d35c9d1de2d1896e2c9a19c18435d2145c5d5](https://github.com/magento/magento2/commit/c40d35c9d1de2d1896e2c9a19c18435d2145c5d5)
 - [fb839e740c986c7f52469a566b368eb8bf80e8f3](https://github.com/magento/magento2/commit/fb839e740c986c7f52469a566b368eb8bf80e8f3)
 - [e45dd6ee71abfb7b445021281808d86d199cd550](https://github.com/magento/magento2/commit/e45dd6ee71abfb7b445021281808d86d199cd550)
 - [5c29e1998e399696046e8562f8ec1a43bfd2ab42](https://github.com/magento/magento2/commit/5c29e1998e399696046e8562f8ec1a43bfd2ab42)

The fix will be available with the upcoming 2.4.0 release.

**Comment by patruvlad** [comment]
@magento-engcom-team I checked the commits from the pull request , this issue is not fixed, Critical CSS should have a loader when activated and in the commits the only thing that happens is that the js needed for that loader is removed from requirejs-config when the file itself should be added for the loader to work
