### ISSUE TITLE
Configurable product - if variant products removed in Configurations the product loses its Type and becomes a Simple.

### ISSUE THREAD

**Issue by tadhgbowe** [magento/magento2#2703]
Version 2.0.0. (follow on from issue #2564)

Step 1: I import a new configurable product with 2 variant simple products. All three products are imported fine and the Configurations section in the Admin Panel for the configurable product is displaying two variant products. 

Step 2: I then realise that I've assigned the incorrect simple products to the configurable parent. It's an easy mistake to make then filling in a .csv import file. So in the Admin Panel Configurations section I use the Action "Remove Product" for both simple products. But when I remove the last one and save the "Add Products Manually" disappears. So I can no longer select the two simple products (that exist) I wanted. I don't want to have to generate more variants via the wizard.

Step 3: I go back to my original import csv file and put in the correct details for the configurable product row in the "configurable_variations" column. I try importing just that one row. It doesn't work! Oops. It was working a few minutes back when the configurable product was created. So why is this? I then notice that the product type for the configurable says it's now a "Simple" product. Oh dear. So when I removed the incorrect variant products in step 2 after the last was gone Magento decided that this was no longer a configurable product and switched it back to a Simple. Oops. This should not happen.

It must try to remember that the product is configurable and also remember the attributes being used for the configurations e.g. color, size.

Thank you.
Tadhg

**Comment by katmoon** [comment]
Hi,

Thanks for reporting the issue.
An internal ticket `MAGETWO-47700` has been created.

Please note you can also update variations using Actions menu ![Actions menu](https://cloud.githubusercontent.com/assets/1260101/12199159/d3e3df20-b61e-11e5-8c6d-2b6c5fcc169f.png)

**Comment by adifucan** [comment]
Current behavior is expected and is the same as on Magento version 2.0.0

To be able to add products manually user needs to select attribute first to generate product variations with this attribute.

For example, user starts to create product configurations. First he selects attributes or attribute (for example, color). Then he add only 2 values to this attribute (white & black) out of 4 values (red & yellow). Then he generates products and gets 2 products. There is Add Products Manually button and user can click on it and filter products that have attribute color. Now user can add products but only those ones that have color attribute value red & yellow.

So to add products manually you need to select attribute first. That's why there is no Add Products Manually button on empty Configurations section. Attribute is unknown when there is no product variation.

**Comment by shiftedreality** [comment]
Appropriate comment added above.
Closed.

**Comment by tadhgbowe** [comment]
Hello guys. I'm sorry you've not understood the issue correctly. If you remove all the variants (because they were imported incorrectly) you suddenly can't choose a different product. The configurable product itself has reverted back to being a simple. Here are the steps:

Step 1: I import a new configurable product with 2 variant simple products. All three products are imported fine and the Configurations section in the Admin Panel for the configurable product is displaying two variant products.

Step 2: I then realise that I've assigned the incorrect simple products to the configurable parent. It's an easy mistake to make then filling in a .csv import file. So in the Admin Panel Configurations section I use the Action "Remove Product" for both simple products. But when I remove the last one and save the "Add Products Manually" disappears. So I can no longer select the two simple products (that exist) I wanted. I don't want to have to generate more variants via the wizard.

Step 3: I go back to my original import csv file and put in the correct details for the configurable product row in the "configurable_variations" column. I try importing just that one row. It doesn't work! Oops. It was working a few minutes back when the configurable product was created. So why is this? I then notice that the product type for the configurable says it's now a "Simple" product. Oh dear. So when I removed the incorrect variant products in step 2 after the last was gone Magento decided that this was no longer a configurable product and switched it back to a Simple. Oops. This should not happen.

Thanks
Tadhg

**Comment by shiftedreality** [comment]
Thank you for clarification.
Reopened, increased priority caused by incorrect import.

**Comment by tadhgbowe** [comment]
Hello.
Thanks. Doing an incorrect import was only an example of how the real world sometimes messes up data. It could easily be somebody creating a new configurable product in the Admin Panel. Creating it initially works absolutely fine. It's when the user realises their mistake an unassigns all the simple variants first, maybe click save oh oh! the configurable has changed to a simple. Oops. Not good.
Maybe the next version will miraculously fix it :-)
Kind regards,
Tadhg

**Comment by jakobfdev** [comment]
Getting back to @adifucan 's comment, since he posted here (see issue https://github.com/magento/magento2/issues/2564). Do you really mean it is expected behaviour to generate  unnecessary variations (like color black and white), just to replace them afterwards? I mean you would be creating products to delete them afterwards. That sounds unreasonable.
Could you suggest a workflow for many imported simple products, of which many need to be "grouped" as a configurable product?

**Comment by tadhgbowe** [comment]
Hi folks. Thanks for your contributions. 

Nobody is creating variations just to delete them afterwards. I was only giving a real world example. People make mistakes. And it's pretty easy to make them when product importing.

In my example the simple and configurable products do need to exist. They just made the mistake of associating the wrong simples to the wrong parent configurable in the import. So they view the configurable in the Admin Panel, realise their mistake, remove the incorrect associations and oops! when they remove the last one and save the "Add Products Manually" disappears. So I'm in trouble. They are then forced down an incorrect path. And Step 3 described above will not work now either. 

Hope this helps. So what needs to be fixed:
1. We need to always have the "Add Products Manually" available in the Admin Panel whether creating a new configurable in the Admin Panel or fixing up an existing product where we have to remove incorrect associations.

PS. Magento 2 is awesome. I don't know how you community dudes find the time. Well done to everyone :-)

**Comment by atIOCrON** [comment]
+1

**Comment by katmoon** [comment]
I'm closing the ticket since the issue has been fixed and delivered to `develop` branch.

**Comment by ghost** [comment]
where is the fix? is there a patch as it is still an issue in 2.1. and it is burdensome to have to create variations just to get the Add Products Manually link. thanks!

**Comment by katmoon** [comment]
Hi @rosandrest ,

It should be fixed in 2.1

**Comment by ghost** [comment]
It is not.

**Comment by katmoon** [comment]
@rosandrest please open a new ticket and describe the detailed steps, Magento mode, any errors in Magento or php/apache error logs if present.
It can be a different issue.

**Comment by SewHappy58** [comment]
It's not fixed in Magento 2.1.1

**Comment by rma-web** [comment]
I am having this issue too. It would be great to be able to create configurations from existing products instead of relying on the configurable products builder to create them. I am using CE 2.1.1 in developer mode.

**Comment by MarekKarmelski** [comment]
It's not working in MCE 2.1.1 still

**Comment by cdbessig** [comment]
Why are we still having issues from December 2015 in February 2017....I'm experiencing an issue where a configurable product turned into a simple product because its only configurable product was removed.  Now I want to add the simple product back, but I cannot without creating a new dummy product first. 

Anyway seems to be linked to this github issue and a few others that have been marked as closed and in magentos internal backlog.

**Comment by tadhgbowe** [comment]
Hello All.

Yes I reported this a long time ago. I think it got moved into "improvement" somewhere but must now be long forgotten about now.

Yes @cdbessig, you are correct. If all the configurable children are removed and you click Save then it changes the type_id from configurable to simple. So we're immediately in trouble.

In the real world people make mistakes especially when using the product import. They may accidentally assign the wrong simple products to a configurable parent. Or they may have imported simple products first. Then import just the configurable parents separately with the hope of marrying everything up in the Admin Panel. No such luck.  

I will try get this case reopened because some of the previous comments to say it has been fixed are incorrect. I've just retested in 2.1.4 and it's still and issue.

Thanks
Tadhg

**Comment by HenKun** [comment]
I am on 2.3.5-p2 and still encounter this issue, which leads to massive problems. Can anyone guide me to the place where this issue should be fixed? @katmoon, why creating a new ticket, the description is quite exact. The product is transformed to `simple` after all variants are removed from the product and the product is saved. The result can be seen in `catalog_product_entity` in column `type_id`.

**Comment by lbajsarowicz** [comment]
It's 2021, using Magento 2.4.2 and the issue is still there. 

ℹ️  Context: We have a few Product Attributes required for a Simple product. There are no custom Attributes required for the Configurable one.

1. Administrator clicks New Configurable Product button
2. They fill the form, except the available configurations of a Product
3. They click "Save"

❗   No warning or error is displayed, notifying that Configurable options are required

Product is converted to Simple, Administrator realize the mistake, they want to add Configurable options to get Configurable product type (but!) they need to fill all the Simple Product fields that are required

**Comment by cdbessig** [comment]
@lbajsarowicz I would open a new issue as this one is closed.

**Comment by lbajsarowicz** [comment]
There already is - the original author @tadhgbowe created a new one: https://github.com/magento/magento2/issues/30809

**Comment by lbajsarowicz** [comment]
@ihor-sviziev  Can you reopen that one for me, as it's still not resolved?

**Comment by ihor-sviziev** [comment]
@sdzhepa @sivaschenko @gabrieldagama, could you triage this issue? It feels really important to fix it.

**Comment by magento-engcom-team** [comment]
@bgorski Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @bgorski 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42594` were created

**Issue Available**: @bgorski, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bgorski** [comment]
I can confirm that this behavior is still there.

**Comment by ihor-sviziev** [comment]
@gabrieldagama @sivaschenko @sdzhepa, please add this issue to the triage meeting. Looks pretty important to fix.

**Comment by jBOKA** [comment]
This whole thread is a joke. I was part of it years ago, still going

Ihor Sviziev ***@***.***> schrieb am Fr., 2. Juli 2021, 10:44:

**Comment by xpoback** [comment]
@magento-engcom-team Now that an internal ticket has been created, could you please provide us with an estimation how many years this would approximately take until it's fixed?

**Comment by jayankaghosh** [comment]
Lol. I just went to the issues tab and searched for the oldest issue present in Magento. 
I can confirm that I was not disappointed by the thread at all...

**Comment by qsolutions-pl** [comment]
I've just run into this myself! Maybe the issue is not mature enough? It needs to be over 18 years old ;-)

**Comment by qsolutions-pl** [comment]
Seems it should be a quick JS fix in one of those 2 files (or maybe both, will check in few days)
`vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/product-grid.js`
```
        _switchProductType: function (variations) {
            $(document).trigger('changeConfigurableTypeProduct', variations.length);
        },
```
`vendor/magento/module-configurable-product/view/adminhtml/web/js/configurable-type-handler.js`
```
        bindAll: function () {
            $(document).on('changeConfigurableTypeProduct', function (event, isConfigurable) {
                $(document).trigger('setTypeProduct', isConfigurable ?
                    'configurable' :
                    productType.type.init === 'configurable' ? 'simple' : productType.type.init
                );
            });
            $(document).on('changeTypeProduct', this._initType.bind(this));
        },```

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance

**Comment by Usik2203** [comment]
@magento give me 2.4.2-p2 instance

**Comment by Fabicool** [comment]
@magento add to contributors team

**Comment by SergeyP18** [comment]
@magento I’m working on it

**Comment by SergeyP18** [comment]
https://github.com/magento/magento2/issues/2703 I am working on it

**Comment by SergeyP18** [comment]
@magento I’m working on it

**Comment by SergeyP18** [comment]
@magento I am working on this

**Comment by engcom-Delta** [comment]
Hi @tadhgbowe ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4-develop instance and the issue is reproducible. Kindly refer the screenshots.

**Steps to reproduce**
1. Import a configurable product with configurable options.
2. Once product is imported, delete the configurable options manually and save the product.
3. Now, Try to import same configurable product with valid configurable options.
4. Observe, product is not imported correctly as respective product is marked as simple product when user manually removed the configurable options.
![image](https://github.com/user-attachments/assets/9b736808-ed26-4681-a780-552a8b4bdabe)

Thanks.
