### ISSUE TITLE
Whatermark issue | When enabled | Product Maximized Picture shows placeholder image

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#27226]
### Preconditions (*)
1. php 7.2
2. magento 2.3.1

### Steps to reproduce (*)
1. Add Product Image
2- View Product Page
3- Press on Product Image

### Expected result (*)
1. Add Product Image
2- View Product Page
3- Press on Product Image
4- See Maximized Product Image

### Actual result (*)
1. Add Product Image
2- View Product Page
3- Press on Product Image
4- Showes Placeholder Image indicating that it cant find the image

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27226-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27226-2-4-develop.instances.magento-community.engineering/admin_6283](https://i-27226-2-4-develop.instances.magento-community.engineering/admin_6283)
Login: `236394c6` Password: `e0f9660431b4`
Instance will be terminated in up to 3 hours.

**Comment by salehawal** [comment]
what i have is 2.3.1

**Comment by sudheers-kensium** [comment]
@salehawal I have verified on Magento 2.4-develop instance, I am not able to reproduced the issue. Maybe issue is resolved latest version (2.3.4) please verify on  latest ver. Please provide more details still you are facing same issue on 2.3.4.

**Comment by salehawal** [comment]
i did upgrade from my end to 2.3.2, still not solved .. also i have changed the theme to the default one but still not working 
![Screenshot from 2020-03-10 14-40-43](https://user-images.githubusercontent.com/3238761/76315931-54058400-62e2-11ea-8529-481b83df8681.png)

**Comment by devchris79** [comment]
Looks like you are seeing a watermark only, have you tried removing the watermark then flushing the cache?

**Comment by salehawal** [comment]
@devchris79 no, i already checked now .. as you can see bellow the image is a placeholder that shows if there is no image for the product 
https://cdn.jomlah.com/pub/media/catalog/product/cache/a91761d908a13c769011033091e94da3/j/o/jomlah-sport-shoe-142332.jpg

**Comment by salehawal** [comment]
@devchris79 .. no it is not related to opacity, it is just the placeholder image beaing replaced by the original one .. i have attached a screenshot of the settings page
![Screenshot from 2020-03-10 17-12-55](https://user-images.githubusercontent.com/3238761/76327372-95059480-62f2-11ea-8df4-b1ec3aa5d097.png)

**Comment by salehawal** [comment]
ok issue resolved .. i just disabled and then enabled the placeholder and the site is working now (:+1:

**Comment by salehawal** [comment]
after applying the fix in productin, it didnt work, but when i removed the watermark it did (:+1:

**Comment by salehawal** [comment]
now the issue is "why the maximized product picture is replaced" if we add water mark, is it a php issue or what?
