### ISSUE TITLE
Incorrect stock status on category page even when saleable qty is reduced to 0

### ISSUE THREAD

**Issue by lokeshvnaik** [magento/magento2#27460]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Add product to cart with maximum available quantity (e.g. 100 in this case)

![qty-before](https://user-images.githubusercontent.com/16201742/77657478-5f6fd500-6f9b-11ea-958f-8cb72f74ded4.png)

![Cart](https://user-images.githubusercontent.com/16201742/77657500-6860a680-6f9b-11ea-8060-333d3772384c.png)

2. Place order
3. The saleable quantity is reduced to 0

![qty-after](https://user-images.githubusercontent.com/16201742/77657557-7ca4a380-6f9b-11ea-8344-47c9b0917bcf.png)

4. Check product page - the stock status is Out of Stock

![Product](https://user-images.githubusercontent.com/16201742/77657627-91813700-6f9b-11ea-9622-9fab69822f69.png)

5. Check category page - the status still shows In stock with Add to Cart button

![Category](https://user-images.githubusercontent.com/16201742/77657700-ab227e80-6f9b-11ea-8363-e5db14681fd9.png)

### Expected result (*)
1. The stock status in category page should show Out of Stock

### Actual result (*)
1. The stock status in category page is showing In stock
2. On category page, $_product->isSaleable() and $_product->isAvailable() still returns true

### Other Information
1. Checked reindexing and cache flush
2. Issue reproducible on Default Magento 2.3.3 setup

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27460-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27460-2-4-develop.instances.magento-community.engineering/admin_7595](https://i-27460-2-4-develop.instances.magento-community.engineering/admin_7595)
Login: `3ca6dabd` Password: `eb86fe025cfd`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @lokeshvnaik ,
I have verified this issue in the Latest Magento 2.4 Instance as per your steps, expected result and actual result. But this issue is not reproduced in the latest Magento instance.
Please see attached the below screenshot:

![Details](https://user-images.githubusercontent.com/24711761/77723140-9682cc80-7015-11ea-950f-5202ee74cbf0.png)

![Listing](https://user-images.githubusercontent.com/24711761/77723141-984c9000-7015-11ea-90f5-387e6066b87a.png)

Should I close the issue or not? Please update your suggestions.

Thanks.

**Comment by lokeshvnaik** [comment]
Kindly check by enabling Show Out of Products once.

I think Magento CE 2.4 is not available for download yet. I was able to reproduce the issue on Magento CE 2.3.3.

Let me know if this issue is related to any other issue in past which might have been fixed under some other issue and if there are any related commits.

**Comment by ajijshekh123** [comment]
Hello @lokeshvnaik ,
I have to Enable the 'Show Out of Products' - YES and also review the same scenario to reproduce this issue but not able to get this issue.
I have tried to find this issue related to the your issue but not getting.
You can found this issue Using below-attached screenshot:

![AdminConfig](https://user-images.githubusercontent.com/24711761/77725161-c2548100-701a-11ea-8db9-6a436e406924.png)

![Listingnew](https://user-images.githubusercontent.com/24711761/77725166-c41e4480-701a-11ea-886d-57a4c9fe3e45.png)

![MagentoNewIssue](https://user-images.githubusercontent.com/24711761/77725167-c4b6db00-701a-11ea-830e-ca4b23fd41b8.png)

Thanks.

**Comment by lokeshvnaik** [comment]
Just hover on that product in category page and see if Add to cart button is visible or not. If product is Out of stock then Add to cart button should not be visible for that product in category page, instead 'Out of stock' text should be shown.

**Comment by ajijshekh123** [comment]
See the attached screenshot. After applying the hover effect it is displaying 'Out of Stock' text instead of the 'Add to cart' button.

![2020-03-27_11-14-53](https://user-images.githubusercontent.com/24711761/77725850-8f12f180-701c-11ea-82d3-ecb5f9839fb6.png)

**Comment by lokeshvnaik** [comment]
Are you checking on Magento Community Edition 2.3.3?

Can you please try with a new product? And also post screenshot of salable qty in backend catalog grid.

If this is fixed in Magento 2.4 then let me know the related commits.

I checked on Magento 2.3.3 with sample data and was able to reproduce the issue.

**Comment by ajijshekh123** [comment]
1. Are you checking on Magento Community Edition 2.3.3?
 - Nope, I have test only the latest Magento instance which provided by the Magento Team. But let me check my local system Magento 2.3.3 instance.

2. Can you please try with a new product? And also post a screenshot of salable qty in the backend catalog grid.
- Let me Try

3. If this is fixed in Magento 2.4 then let me know the related commits.
- I don't have any.

4. I checked on Magento 2.3.3 with sample data and was able to reproduce the issue.
- Let me try it and update you shortly.

**Comment by lokeshvnaik** [comment]
Hi @ajijshekh123,

Did you check on Magento CE 2.3.3?

**Comment by ajijshekh123** [comment]
Hi @lokeshvnaik ,
I have verified this issue Magento CE 2.3.3. This issue is reproduced.
**See attached the screenshot:**

![1](https://user-images.githubusercontent.com/24711761/78003270-0666bf00-7356-11ea-82ba-8a3725d04be4.png)

![2](https://user-images.githubusercontent.com/24711761/78003273-08308280-7356-11ea-9bb8-a40188f2fb85.png)

![3](https://user-images.githubusercontent.com/24711761/78003275-08c91900-7356-11ea-9514-4f64477c998b.png)

![4](https://user-images.githubusercontent.com/24711761/78003281-0961af80-7356-11ea-9e0d-ac2b3fa27e9e.png)

Thanks.

**Comment by ronn0** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ronn0. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ronn0, here is your [Magento instance](https://i-27460-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27460-2-4-develop.instances.magento-community.engineering/admin_81d1](https://i-27460-2-4-develop.instances.magento-community.engineering/admin_81d1)
Login: `dfc3bc0d` Password: `315dc245800e`
Instance will be terminated in up to 3 hours.

**Comment by karthickannan** [comment]
@ronn0 

This issue is appearing in bundle products also. If a simple product has salable quantity 0 and associated with a bundle product, the simple product should not be shown as an option in the frontend. But it is being shown as an option.

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-27460-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27460-2-4-develop.instances.magento-community.engineering/admin_a0d4](https://i-27460-2-4-develop.instances.magento-community.engineering/admin_a0d4)
Login: `09421928` Password: `91be6344c988`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @lokeshvnaik 

We have re-checked this issue on the latest `2.4-develop` code
And this issue cannot be reproduced now, seems it was already fixed in the scope of some other issue/task.
Closed 

![issue_27460](https://user-images.githubusercontent.com/3409584/88954169-90208d80-d25f-11ea-82b5-24d8ad98c040.gif)

**Comment by codebase-md** [comment]
> Hello @lokeshvnaik
> 
> We have re-checked this issue on the latest `2.4-develop` code
> And this issue cannot be reproduced now, seems it was already fixed in the scope of some other issue/task.
> Closed
> 
> ![issue_27460](https://user-images.githubusercontent.com/3409584/88954169-90208d80-d25f-11ea-82b5-24d8ad98c040.gif)

You verify a bug report for 2.3.3 against 2.4 and close it because the issue is not present in the (upfront) **_wrong_** test environment. This issue is still present in version 2.3.5-p1. Support for 2.3.x is until end of next year! ([Support](https://devdocs.magento.com/release/)) So please reopen and verify correctly. Thank you.

**Comment by lokeshvnaik** [comment]
Faced another issue in Magento 2.3.3 which seems related to this one but with MSI and multi website setup. 
https://github.com/magento/magento2/issues/29683

Can someone let us know the related commits or relevant patch release for 2.3.3 if this has been fixed under some other issue?

As @codebase-md pointed out the issue is still present in version 2.3.5-p1. @sdzhepa Can you please test this on Magento 2.3.3 version and confirm?

**Comment by jimuld** [comment]
@lokeshvnaik, I was facing same issue with Magento 2.3.5 with data migrated from Magento 1. What I found that database table inventory_source_item was causing the issue, if you find any sku in this table which is showing out of stock on category page you will find difference in columns qty and status. Hope it will help!

**Comment by pixel-paul** [comment]
As far as I can see this exists in 2.3.6 too

**Comment by vmasciotta** [comment]
Why this issuee is closed if not solved? I'm facing it on 2.3.5, p1 p2 and 2.3.6 too. It's not solved! So please reopen it!

**Comment by martinnguyen3005** [comment]
:( Please reopen this ticket and should have a patch for 2.3.*!

**Comment by pvalium** [comment]
No news?

**Comment by pixel-paul** [comment]
Magento have changed the way in which they support releases. You are expected to upgrade to 2.4 for the fix as no backport will be made. They are only releasing security patches for the 2.3 branch now. Annoying but that is the reality.

**Comment by khnaim** [comment]
hey @lokeshvnaik , any update on the issue you described?

**Comment by say-my-name-user** [comment]
Hello,
check the observer `\Magento\CatalogPermissions\Observer\ApplyIsSalableToProductObserver`.

If you have `Stores > Configuration > Catalog > Catalog Permitions > Add to cart` disabled in admin panel then this observer set product's IsSalable to false. And based on this property "Out of Stock" is shown.
