### ISSUE TITLE
Integration Tests: DOM Assertion class

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27607]
### Description (*)
We have plenty of integration tests that make assertions on HTML code:
![image](https://user-images.githubusercontent.com/1639941/78465156-4af5b000-76f2-11ea-8914-df186317e27e.png)

With `assertContains` or `preg_match`. This is not the right approach for making assertions on HTML and the correct approach should be possible. The right approach is based on DOM tree.

Example:
https://github.com/magento/magento2/pull/27606/files#diff-dcb208981e520970637c75ff2d89eafcR169-R173

### Expected behavior (*)
We need the DOM assertion class to be introduced to Integration Tests Framework

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33094` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lbajsarowicz** [comment]
Still to be implemented.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27606 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [1ac923d3487a7ce8f65db2bd1191a9349a77c99d](https://github.com/magento/magento2/commit/1ac923d3487a7ce8f65db2bd1191a9349a77c99d)
 - [16cb18d7edaf504e7de2899f6935d33f8fcc42d9](https://github.com/magento/magento2/commit/16cb18d7edaf504e7de2899f6935d33f8fcc42d9)
 - [f882122a3280f3b60706f87d9428f75b11a80112](https://github.com/magento/magento2/commit/f882122a3280f3b60706f87d9428f75b11a80112)
 - [82224a62f63955d1c070e2509298e27acc52cdd4](https://github.com/magento/magento2/commit/82224a62f63955d1c070e2509298e27acc52cdd4)
 - [cd895a5f9cc363166d229888f1780c54255f7710](https://github.com/magento/magento2/commit/cd895a5f9cc363166d229888f1780c54255f7710)
 - [d4b80830e4e21ed16e50170dcefb6468aa3a7ea3](https://github.com/magento/magento2/commit/d4b80830e4e21ed16e50170dcefb6468aa3a7ea3)

The fix will be available with the upcoming 2.4.0 release.

**Comment by lbajsarowicz** [comment]
The issue still needs to be implemented.
What is actually closed in scope of the PR mentioned above was use of such DOM assertions there.
