### ISSUE TITLE
Magento 2.3.4 - Category getImageUrl() returns incorrect value

### ISSUE THREAD

**Issue by jkenneydaniel** [magento/magento2#28100]
### Preconditions (*)
1. Magento 2.3.5-p1 (reproduced only on composer versions)

### Steps to reproduce (*)
1. Go to Admin->Catalog->Categories;
2. Create a new category with an image;
3. Go to Storefront and open created before the category
### Expected result (*)
1. Category image src uses the full URL

### Actual result (*)
1. Category image src is actually just a relative path

### Additional Info
When uploading an image to categories, it would be expected that when loaded on the frontend the category image URL is loaded so that when the media URL is set (i.e. for CDN usage) - the full URL is used to load the image. This is not the case however because of a change introduced in commit 3c3acd75674039f38ee65d81e8daaa9cbb81fadb where it attempts to determine the path of the image value either being relative or absolute. Considering the backend model for the image attribute is using what would be considered an absolute path, it is simply returning the value without prepending the media URL to the file path.

![Example from Magento 2.3.4 with Sample Data](https://user-images.githubusercontent.com/371146/81008723-63f09e80-8e21-11ea-9734-9e1b36f86b7a.png)

**Comment by jkenneydaniel** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @jkenneydaniel. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jkenneydaniel, here is your [Magento instance](https://i-28100-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-28100-2-3-4.instances.magento-community.engineering/admin_e91c](https://i-28100-2-3-4.instances.magento-community.engineering/admin_e91c)
Login: `6b29d693` Password: `0ed39ee02cc2`
Instance will be terminated in up to 3 hours.

**Comment by jkenneydaniel** [comment]
Confirmed the issue:
![image](https://user-images.githubusercontent.com/371146/81009527-d615b300-8e22-11ea-8ceb-f2d29eeec43e.png)

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-28100-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28100-2-4-develop.instances.magento-community.engineering/admin_7c8f](https://i-28100-2-4-develop.instances.magento-community.engineering/admin_7c8f)
Login: `be299754` Password: `5d86697c07be`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
Hi @jkenneydaniel. Thank you for your reporting.

Unfortunately, we are not able to reproduce this issue on a fresh 2.4-develop instance.

**Manual testing scenario:**
1. Add image to category;
2. Go to Storefront-> Category with an image;
3. Open dev tools;

**Actual Result:** :heavy_check_mark: Category image src uses the full URL

![image](https://user-images.githubusercontent.com/51679138/81284023-3c3e4800-9066-11ea-8b34-c610167bf4c6.png)
![image1](https://user-images.githubusercontent.com/51679138/81284038-3fd1cf00-9066-11ea-8915-376ba9f5df95.png)

@jkenneydaniel Could you take a look?
Thanks!

**Comment by jkenneydaniel** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jkenneydaniel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jkenneydaniel, here is your [Magento instance](https://i-28100-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28100-2-4-develop.instances.magento-community.engineering/admin_7596](https://i-28100-2-4-develop.instances.magento-community.engineering/admin_7596)
Login: `ff9671ff` Password: `a51269174d52`
Instance will be terminated in up to 3 hours.

**Comment by jkenneydaniel** [comment]
@engcom-Alfa So I see in 2.4 the functionality for the `image.phtml` was changed to use the Image viewmodel: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/ViewModel/Category/Image.php

Which means that section no longer uses `$category->getImageUrl()` - however on 2.3 this is not the case - so I'm a little confused, will this issue _not_ be fixed in 2.3 but rather we'll have to wait until after 2021 for 2.4 release?

**Comment by engcom-Alfa** [comment]
@jkenneydaniel The issue is reproducible on Magento 2.3.5-p1 composer version.

**Actual Result:**  :heavy_multiplication_x: Category image src is actually just a relative path

![newww](https://user-images.githubusercontent.com/51679138/81393482-1e85e700-9129-11ea-9931-bda26884fc19.png)
![newwwwww](https://user-images.githubusercontent.com/51679138/81393490-20e84100-9129-11ea-84c1-10e0b1239d96.png)

**Comment by CarmineDamore78** [comment]
@magento I am working on this

**Comment by CarmineDamore78** [comment]
Hi @jkenneydaniel 
Unfortunately I can not pull my fix on 2.3-develop
i live you here the link with my fix so you can create a patch and fix your issue
https://github.com/magento/magento2/pull/28296/commits/a39d19dcf59aed693d85e84f5685a54d8f4fb59a

**Comment by Digisha-97** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Digisha-97. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Digisha-97, here is your [Magento instance](https://i-28100-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28100-2-4-develop.instances.magento-community.engineering/admin_61d1](https://i-28100-2-4-develop.instances.magento-community.engineering/admin_61d1)
Login: `6e193aea` Password: `aa48c7a1512f`
Instance will be terminated in up to 3 hours.

**Comment by Digisha-97** [comment]
@magento I am working on this

**Comment by Digisha-97** [comment]
@magento I am working on this
But I am not able to push changes , evenrytime it shows Authentication failed.

**Comment by Digisha-97** [comment]
@magento I am not able to push changes 
Do I have permission for it ?

**Comment by Digisha-97** [comment]
/vendor/magento/module-catalog/Model/Category/Attribute/Backend/Image.php
public function beforeSave($object)

In This method below code is creating issue
$value[0]['url'] = '/' . $baseMediaDir . '/' . $newImgRelativePath;
$value[0]['name'] = $value[0]['url'];

Update it with 
$value[0]['url'] = $baseMediaDir . $newImgRelativePath; 
$value[0]['name'] = $value[0]['name'];

This will fix issue
Do Not forget to forget to override this file from your module to avoid direct core file changes

**Comment by raybog** [comment]
Before official patch is ready we are using following SQL only workaround:

```
DROP TRIGGER catalog_category_entity_varchar_before_update;
DROP TRIGGER catalog_category_entity_varchar_before_insert;

DELIMITER //

CREATE TRIGGER catalog_category_entity_varchar_before_update
  BEFORE UPDATE
  ON catalog_category_entity_varchar FOR EACH ROW
BEGIN
  SET NEW.value = REPLACE(NEW.value, '/media/catalog/category/', '');
END; //

DELIMITER ;

DELIMITER //

CREATE TRIGGER catalog_category_entity_varchar_before_insert
  BEFORE INSERT
  ON catalog_category_entity_varchar FOR EACH ROW
BEGIN
  SET NEW.value = REPLACE(NEW.value, '/media/catalog/category/', '');
END; //

DELIMITER ;

```

**Comment by dverkade** [comment]
Confirmed issues can't be closed automatically.

**Comment by kassner** [comment]
@dverkade see https://github.com/magento/magento2/pull/31223#issuecomment-742112083

**Comment by kassner** [comment]
Bump

**Comment by EmilyPepperman** [comment]
Has this been solved in 2.4.3? Doesn't look like it.

**Comment by stkrelax** [comment]
unbelievable this is not solved yet...
the patch that worked for us:

[magento-2.4.2-p1-issue-28100.log](https://github.com/magento/magento2/files/7292371/magento-2.4.2-p1-issue-28100.log)

rename .log to .patch

**Comment by Organizer21** [comment]
After wasting a lot of time I have landed here and seem to have this issue in 2.4.3 CE, presumably just like @EmilyPepperman (not sure you solved it?). I'm very new to Magento and a quick attempt to apply that patch @stkrelax on 2.4.3 (using ./vendor/bin/ece-patches with the patch in a m2-hotfixeds folder) quickly gave an error about -> No such file or directory: Model/Category/Attribute/Backend/Image.php so I am sort of stuck at this point.

For reference; when I select an Image for a Category it shows correct in the preview/select element, but upon a page refresh the image shows as a broken link. In my case the link applied to it is https://magento.domain.com/pubhttps://magento.domain.com/media/custom-asset/category-banner-1.png and the double up on the domain name is clearly what's breaking it and I have no idea why and how to fix it at this point. Not looked at the SQL workaround above yet , but I think this thread is related to my issue as to maybe attempt that fix.

**Comment by nahall** [comment]
@magento give me 2.4-develop instance

**Comment by nahall** [comment]
@magento give me 2.4-develop instance with extensions magepow/categories

**Comment by nahall** [comment]
I verified that this is still a problem. To verify, upload a category image and look at the database like:
`select * from catalog_category_entity_varchar where attribute_id=37 and entity_id=2135;`

The value field will be set like "/media/catalog/category/test.jpg". When it is set like this, getImageUrl() returns '/media/catalog/category/test.jpg' instead of 'https://domain.com/media/catalog/category/test.jpg'.

By editing the database to change value='test.jpg' then getImageUrl() will return 'https://domain.com/media/catalog/category/test.jpg' properly.

I also tested the patch given by [stkrelax](https://github.com/stkrelax) https://github.com/magento/magento2/issues/28100#issuecomment-935810263 and it fixes the problem.

How can we proceed with getting this merged?

**Comment by engcom-Delta** [comment]
Hi @jkenneydaniel,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4.7 instance and the issue is no more reproducible.

1.Go to Admin->Catalog->Categories
2.Create a new category with an image
3.Go to Storefront and open created before the category


Go to Admin->Catalog->Categories

<img width="1439" alt="Screenshot 2024-05-16 at 2 46 03 PM" src="https://github.com/magento/magento2/assets/51681379/b819c65a-2a89-46b6-96f3-1bbbc86441c7">


Create a new category with an image

<img width="1435" alt="Screenshot 2024-05-16 at 2 52 02 PM" src="https://github.com/magento/magento2/assets/51681379/bd0ea66e-b569-409e-9f78-43b50aa3cf81">


Category image src uses the full URL instead of a relative path

<img width="1436" alt="Screenshot 2024-05-16 at 3 37 57 PM" src="https://github.com/magento/magento2/assets/51681379/16e9352b-0745-42e0-a8c1-8032adb3c3be">


Hence we are closing this issue.

Thanks,

**Comment by nahall** [comment]
https://github.com/magento give me 2.4-develop instance with extensions magepow/categories

**Comment by nahall** [comment]
@magento https://github.com/magento give me 2.4-develop instance with extensions magepow/categories

**Comment by engcom-Delta** [comment]
Hi @nahall ,

Thanks for your input on this issue.

We are reopening this ticket as per your above comment.

Thanks,

**Comment by engcom-November** [comment]
Hello @nahall,

Thank you for the input.

Verified this on 2.4-develop.
I have modified the template file to call `getImageUrl()`, as you can see in the below image:
<img width="860" alt="image" src="https://github.com/magento/magento2/assets/60198231/eda848e0-9eeb-4042-a2e2-f7495980e3e9">

It can be seen that the image is being rendered with relative path.
<img width="1299" alt="image" src="https://github.com/magento/magento2/assets/60198231/8a89f164-aa47-4b04-9f2c-60b180c9fc6d">

The `getImageUrl()` method returns relative path of the image.

Hence this issue can be confirmed.

Thank you.
