### ISSUE TITLE
Issue in Dob field.

### ISSUE THREAD

**Issue by Ankush-Webkul** [magento/magento2#28482]
Getting an issue on the Registration page if the Dob field is enabled from admin.
https://prnt.sc/ssty7t

Preconditions (*)
Use Magento 2.3.5 instance

Steps to reproduce (*)
1. Enable the Dob field from admin.
2. create New customer account with Dob.

Expected result (*)
 The Account is created with customer Dob.

Actual result (*)
The account is not created and shows and error in the Dob field that "Please Enter the correct Dob".

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28482-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28482-2-3-5-p1.instances.magento-community.engineering/admin_c67a](https://i-28482-2-3-5-p1.instances.magento-community.engineering/admin_c67a)
Login: `8a07645c` Password: `0b23c0fb743f`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
The issue is reproducible on Magento 2.3.5pl develop instance 

Please find the attachment below: 
![image](https://user-images.githubusercontent.com/58288685/83613500-7cc7ad80-a5a1-11ea-9e21-ec42ebc11a84.png)

Note: I can able to create account if I try to keep the current month first day(06/1/2020)  as a dob in this instance

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28482-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28482-2-4-develop.instances.magento-community.engineering/admin_f61b](https://i-28482-2-4-develop.instances.magento-community.engineering/admin_f61b)
Login: `a501ebf0` Password: `a10a40d13625`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
The issue is not reproducible on Magento 2.4 develop instance

Please find the attachment below:
![BEmcugVErt](https://user-images.githubusercontent.com/58288685/83616676-c1554800-a5a5-11ea-9d84-39ecd03f8875.gif)

**Comment by swathishs** [comment]
Can be reproduced only on 2.3.5p1 but not on 2.4 develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34824` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by pmgephart** [comment]
Hi @swathishs and @magento-engcom-team,

I was able to reproduce this issue on our instance of Magento 2.3.5-p1. The error given was: 

"Please enter a valid date."

In /vendor/magento/module-customer/Block/Widget/Dob.php I changed the line:

$escapedDateFormat = preg_replace('/[^MmDdYy\/\.\-]/', '', $dateFormat);

to:

$escapedDateFormat = 'M/dd/Y';

It seems the frontend validation wants this date format instead of 'M/d/Y'. Please let me know if this fixes your issue.

**Comment by chandu-pinpoint** [comment]
@magento I am working on this

**Comment by chandu-pinpoint** [comment]
@magento  and @Ankush-Webkul 
I have created a patch for 2.3.5 here: https://github.com/chandu-pinpoint/magento2/commit/d3f8e5407403f78f3b09fe5af3e7a9222d19ba39
I hope this helps.

**Comment by zaietsv** [comment]
> @magento and @Ankush-Webkul
> I have created a patch for 2.3.5-p1 here: [chandu-pinpoint@d3f8e54](https://github.com/chandu-pinpoint/magento2/commit/d3f8e5407403f78f3b09fe5af3e7a9222d19ba39)
> I hope this helps.

Thank you! It really works!
PS: Magento team BOOO...

**Comment by magento-engcom-team** [comment]
Hi @Ankush-Webkul, @chandu-pinpoint. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-34824` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @Ankush-Webkul, @chandu-pinpoint. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-34824` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by hostep** [comment]
I think this got fixed in 2.4-develop with [MC-31117](https://github.com/magento/magento2/commit/4ecae3093cfc04c0a7d66045e0b54b30c73112b3) in scope of https://github.com/magento/magento2/issues/26700, but might be wrong about this.

**Comment by verdde** [comment]
Was not fixed. 2.3.5-p1 The patch made by chandu-pinpoint is temporary fixing the issue.
For 2.4 there is an opened issue #26443

**Comment by sdzhepa** [comment]
Hello @Ankush-Webkul

Update based on internal Jira.
The issue has been fixed by internal team in the scope of `MC-32364` internal ticket. Fix was delivered into 2.3.x branch
Target fix version is next `2.3.6` release

**Comment by VincentMarmiesse** [comment]
This issue still exists in `2.3.6`.
It's OK in front but is not in Admin when the locale is not `en_US`.

**Comment by jignesh6591** [comment]
With admin locale except there is still issue
