### ISSUE TITLE
Custom Admin Domain and Internal Redirects

### ISSUE THREAD

**Issue by pocallaghan** [magento/magento2#28943]
The logic that checks if a redirect is "internal" is broken in the admin panel when using a custom admin domain, which causes a wide variety of admin redirects to redirect you to the homepage of the default store.

The issue is due to `Magento\Store\App\Response\Redirect::_isUrlInternal` using the default stores base url. When in the adminhtml area, this method should respect the config options `admin/url/use_custom` and `admin/url/custom`.

### Preconditions (*)
1. Magento 2.4-develop
2. Custom admin domain set under Stores > Configuration > Advanced > Admin > Admin Base Url > Custom Admin Url
![image](https://user-images.githubusercontent.com/51681379/86767769-27296980-c055-11ea-8745-f9ccd003bb9f.png)
3. **For local environment:** Create additional virtualhost for url `http://admin.magento2dev.loc` and add `admin.magento2dev.loc` to `hosts` file
```
<VirtualHost *:80>
    ServerName          magento2dev.loc
    ServerAlias magento2dev.loc
    DocumentRoot        /var/www/html/magento2dev
<Directory /var/www/html/magento2dev/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
Require all granted
</Directory>
 </VirtualHost>


<VirtualHost *:80>
    ServerName          admin.magento2dev.loc
    DocumentRoot        /var/www/html/magento2dev
<Directory /var/www/html/magento2dev/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
Require all granted
</Directory>
 </VirtualHost>
```

### Steps to reproduce (*)
1. Log in to an account with access to URL Rewrites
2. Navigate to Marketing > URL Rewrites
3. Click Add Url Rewrite
4. Enter `123456789` as the request path and `987654321` as the target path, then hit save.
5. Click Add Url Rewrite again
4. Enter `123456789` as the request path and `xyz` as the target path, then hit save.

### Expected result (*)
1. Expected to be redirected back to the URL Rewrite Edit page with an error message `Request Path for Specified Store already exists.`

### Actual result (*)
1. You're redirected to the homepage of the default store.
![Peek 2020-07-07 13-21](https://user-images.githubusercontent.com/51681379/86768195-d7976d80-c055-11ea-9070-9a787ae2e25e.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hello @pocallaghan 

Could you confirm that the result will be the same as when using the CLI?
`php bin/magento setup:config:set --backend-frontname="newadminpath"`
Where `newadminpath` - new Custom Admin URL
I checked on the Magento 2.4 using CLI and cannot reproduce the issue

**Comment by pocallaghan** [comment]
That is not the same setting, you're setting the "frontname", not the domain name.

**Comment by engcom-Lima** [comment]
Hello @pocallaghan 
Could you show how are you configure Custom admin domain under Stores > Configuration > Advanced > Admin > Admin Base Url > Custom Admin Url? 
It would be great if you attached the GIF file.

**Comment by sunel** [comment]
@engcom-Lima 

This is long pending issue https://github.com/magento/magento2/issues/12354

**Comment by pocallaghan** [comment]
@engcom-Lima you're likely to be unable to replicate in what ever environment you're trying it in. Changing the domain name of the admin panel requires DNS entries to be added so that the domain name you enter points at the same location as the main stores domain and potentially updates to the server hosting configuration so that the domain loads the right VirtualHost. @sunel it is indeed the same issue, but the ticket was marked as non-issue with no good reason. It is 100% an issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35680` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by HenKun** [comment]
This issue also arises, when the default store domain has a subfolder like `https://www.example.com/en-us/`.
Then in `_isUrlInternal()` the check fails because `https://www.example.com/admin/...` does not contain `https://www.example.com/en-us/`. It's the same reason.

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-28943-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28943-2-4-develop.instances.magento-community.engineering/admin_492c](https://i-28943-2-4-develop.instances.magento-community.engineering/admin_492c)
Login: `0388e944` Password: `d6a6f1c51ae8`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @pocallaghan. Thank you for your report. 
The issue has been fixed in magento/magento2#29066 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [c5b320bd105e67d7ceeb86f42fdb1b08367e9a2f](https://github.com/magento/magento2/commit/c5b320bd105e67d7ceeb86f42fdb1b08367e9a2f)

The fix will be available with the upcoming 2.4.1 release.

**Comment by syed-netable** [comment]
Hi @magento-engcom-team 

Downloaded and installed 2.4.1-p1 still not working :(
