### ISSUE TITLE
WEBAPI: bug customer is created although you receive an error in address section

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#2914]
Usage of this method customerCustomerRepositoryV1SaveRequest results in error if you miss some required parameters in the address section (addresses/item), eg lastname, firstname.

But the customer account is created and get his own Id! 

This should not happen, the complete message should be rejected and not 1 part should be processed.

**Comment by vrann** [comment]
Internal ticket is created MAGETWO-47850

**Comment by okorshenko** [comment]
Hi @tinxit . Thank you for reporting the issue. Unfortunately, I can't reproduce this issue using this test data:

```
POST:  http://magento.dev/rest/V1/customers

{
"customer":     {
        "id": null,
        "group_id": 1,
        "default_billing": null,
        "default_shipping": null,
        "created_at": null,
        "updated_at": "2016-01-20 19:59:36",
        "created_in": "Default Store View",
        "email": "user2@example.com",
        "firstname": "First",
        "lastname": "Last",
        "prefix": "test",
        "gender": 1,
        "store_id": 1,
        "website_id": 1,
        "addresses":
        [
            {
                "id": null,
                "customer_id": null,
                "region":
                {
                    "region_code": "TX",
                    "region": "Texas",
                    "region_id": 57
                },
                "region_id": 57,
                "country_id": "US",
                "street":
                [
                    "7700 W Parmer Lane"
                ],
                "company": "Magento",
                "telephone": "1112223344",
                "postcode": "12345",
                "city": "Aystin",
                "firstname": null,
                "lastname": null,
                "default_shipping": true,
                "default_billing": true
            }
        ],
        "disable_auto_group_change": 0
    }
}
```

Response:

```
Status Code: 400 Bad Request

    "message": "One or more input exceptions have occurred.",
    "errors":
    [
        {
            "message": "%fieldName is a required field.",
            "parameters":
            {
                "fieldName": "firstname"
            }
        },
        {
            "message": "%fieldName is a required field.",
            "parameters":
            {
                "fieldName": "lastname"
            }
        }
    ]
}
```

Could you please provide steps to reproduce and test data?
Thank you

**Comment by ericahoekerd** [comment]
that is because we are using SOAP api not REST

**Comment by mazhalai** [comment]
@tinxit this has been resolved in commit 73ef9f559f2888eaa7649686415faa7e89dceef5 and b5078f011a5ad9b3c0586084678d6402de6fad7e, hence closing this issue.

**Comment by ericahoekerd** [comment]
was this part of release 2.05? because in 2.05 I still have the same issue

**Comment by maksek** [comment]
@tinxit, no - currently it is planned only for 2.1.0, and can be found in develop branch.
@elenleonova can you address patch release possibility for API?
