### ISSUE TITLE
Magento 2.4.0 with Sample Data - DDL statements are not allowed in transactions

### ISSUE THREAD

**Issue by maciej-orba** [magento/magento2#29334]
### Preconditions (*)

1. Magento 2.4.0 Open Source
2. MySQL 8.0.21
3. PHP 7.4.8

### Steps to reproduce (*)

1. Ensure Magento is NOT installed in DB
2. Ensure sample data packages are present composer.json
```
"require": {
        "magento/composer-root-update-plugin": "~1.0",
        "magento/module-bundle-sample-data": "100.4.*",
        "magento/module-catalog-rule-sample-data": "100.4.*",
        "magento/module-catalog-sample-data": "100.4.*",
        "magento/module-cms-sample-data": "100.4.*",
        "magento/module-configurable-sample-data": "100.4.*",
        "magento/module-customer-sample-data": "100.4.*",
        "magento/module-downloadable-sample-data": "100.4.*",
        "magento/module-grouped-product-sample-data": "100.4.*",
        "magento/module-msrp-sample-data": "100.4.*",
        "magento/module-offline-shipping-sample-data": "100.4.*",
        "magento/module-product-links-sample-data": "100.4.*",
        "magento/module-review-sample-data": "100.4.*",
        "magento/module-sales-rule-sample-data": "100.4.*",
        "magento/module-sales-sample-data": "100.4.*",
        "magento/module-swatches-sample-data": "100.4.*",
        "magento/module-tax-sample-data": "100.4.*",
        "magento/module-theme-sample-data": "100.4.*",
        "magento/module-widget-sample-data": "100.4.*",
        "magento/module-wishlist-sample-data": "100.4.*",
        "magento/product-community-edition": "2.4.0",
        "magento/sample-data-media": "100.4.*"
    }
```
3. `composer install`
4.  `bin/magento setup:install`

**note:** it works well when you deal with installed Magento and 
`bin/magento sampledata:deploy`
`bin/magento setup:upgrade`
You need to cleaup DB and install again

### Expected result (*)

1. No errors during installation
2. Sample data present in system

### Actual result (*)

1. Error during installation

```
[Progress: 925 / 1281]
Module 'Magento_SalesSampleData':

In Full.php line 174:
                                                  
  DDL statements are not allowed in transactions  
                                                  

In Mysql.php line 528:
                                                  
  DDL statements are not allowed in transactions  
                                                  
[...]

Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 4020 in /var/www/magento/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(256, 'Some transactio...', '/var/www/magent...', 4020, Array)
#1 /var/www/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(4020): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql->__destruct()
#3 {main}
  thrown in /var/www/magento/vendor/magento/framework/App/ErrorHandler.php on line 61

```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jean323** [comment]
I have exactly the same problem

**Comment by mrtuvn** [comment]
See i got similar issue with sample data include magento package
![Screenshot from 2020-07-31 22-44-15](https://user-images.githubusercontent.com/1908873/89053995-467c9380-d382-11ea-9faa-025fb8ff300c.png)

**Comment by haunguyen1989** [comment]
when we upgrade from magento 2.3.5-p1 to magento 2.4.
After upgrade we have run setup:upgrade. It's raise error.
![Screenshot from 2020-08-02 19-46-11](https://user-images.githubusercontent.com/44774202/89124201-5e2d5680-d4ff-11ea-9a03-e058b13bfef8.png)

**Comment by karunakhatri** [comment]
I have facing the same issue during setup upgrade after upgrading my version 2.3.5p2 to 2.4.0


![image](https://user-images.githubusercontent.com/47114777/89133198-c7c95700-d537-11ea-87af-8f7190598d42.png)

**Comment by AGPDev** [comment]
i have this problem too, nice work Magento, no answers in 8 days ?

**Comment by jean323** [comment]
> i have this problem too, nice work Magento, no answers in 8 days ?

hello friend, I solved it by reinstalling magento

**Comment by matutetandil** [comment]
Having the same issue... is an 2.4 EE... but basically the same issue...

```
Module 'Magento_PurchaseOrder':
Unable to apply data patch Magento\PurchaseOrder\Setup\Patch\Data\InitPurchaseOrderSalesSequence for module Magento_PurchaseOrder. Original exception message: DDL statements are not allowed in transactions
```


I debugged the code, and basically the errors is generated here:
vendor/magento/framework/DB/Adapter/Pdo/Mysql.php line 527, The transaction is `CREATE TABLE`, so it fails with this error...

Considering is a Magento Module, I don't know if I can add a "temporary" so the transaction will be 

```sql
CREATE TEMPORARY TABLE ...
```

**Comment by matutetandil** [comment]
> > i have this problem too, nice work Magento, no answers in 8 days ?
> 
> hello friend, I solved it by reinstalling magento

If you are working with a clean install, could work... but what if you are upgrading?? Like I am (and probably lots of people will be)

**Comment by AGPDev** [comment]
> > > i have this problem too, nice work Magento, no answers in 8 days ?
> > 
> > 
> > hello friend, I solved it by reinstalling magento
> 
> If you are working with a clean install, could work... but what if you are upgrading?? Like I am (and probably lots of people will be)

fresh install, and i need the sample data to work

**Comment by mrtuvn** [comment]
Seem i don't get issue with setup follow steps below (use package downloaded from magento homepage)
#1 install magento 2.4.0 no data first (If you don't use sampledata) You ready to go all thing ready. Very quick fastforward
#2 After setup basic modules so you ready install with data (theme data, sales, order , customer. .etc). Replace composer.json include data sample package
Result -> No exception or errors. Install success
@AGPDev @karunakhatri @jean323

**Comment by bjq** [comment]
[Progress: 925 / 1282]
Module 'Magento_SalesSampleData':

In Full.php line 174:
                                                  
  DDL statements are not allowed in transactions  
                                                  

In Mysql.php line 528:
                                                  
  DDL statements are not allowed in transactions  
                                                  

setup:install [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--backend-frontname BACKEND-FRONTNAME] [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retires SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--cache-backend-redis-compress-data CACHE-BACKEND-REDIS-COMPRESS-DATA] [--cache-backend-redis-compression-lib CACHE-BACKEND-REDIS-COMPRESSION-LIB] [--cache-id-prefix CACHE-ID-PREFIX] [--allow-parallel-generation] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-compression-lib PAGE-CACHE-REDIS-COMPRESSION-LIB] [--page-cache-id-prefix PAGE-CACHE-ID-PREFIX] [--lock-provider LOCK-PROVIDER] [--lock-db-prefix LOCK-DB-PREFIX] [--lock-zookeeper-host LOCK-ZOOKEEPER-HOST] [--lock-zookeeper-path LOCK-ZOOKEEPER-PATH] [--lock-file-path LOCK-FILE-PATH] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--search-engine SEARCH-ENGINE] [--elasticsearch-host ELASTICSEARCH-HOST] [--elasticsearch-port ELASTICSEARCH-PORT] [--elasticsearch-enable-auth ELASTICSEARCH-ENABLE-AUTH] [--elasticsearch-username ELASTICSEARCH-USERNAME] [--elasticsearch-password ELASTICSEARCH-PASSWORD] [--elasticsearch-index-prefix ELASTICSEARCH-INDEX-PREFIX] [--elasticsearch-timeout ELASTICSEARCH-TIMEOUT] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]

PHP Fatal error:  Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 4020 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(256, 'Some transactio...', '/var/www/html/v...', 4020, Array)
#1 /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(4020): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql->__destruct()
#3 {main}
  thrown in /var/www/html/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by Mecalux-Developer** [comment]
@mrtuvn  It seems that the problem appears only when the package has LUMA data. The clean install works well.

**Comment by mrtuvn** [comment]
@Mecalux-Developer  yes this issue may happen when you install with sampledata. Maybe related with modules sample data with some logic patch/setup incorrect. When you setup upgrade data magento  will trying to run recursive loop through patch data for update schema.

**Comment by AymericJoubert** [comment]
*As a workaround*, to unlock the `setup:upgrade` process on your development environments, you can add a log the in following class :
`\Magento\SalesSequence\Model\Builder` at line 253

The log :
`echo $this->ddlSequence->getCreateSequenceDdl($this->data['sequence_table'], $this->data['start_value']);`

This will print the query that causes the error. You can run this query manually in your database and re-run `setup:upgrade` command.

Repeat the operation 2-3 times.

**Comment by kyokorin** [comment]
> _As a workaround_, to unlock the `setup:upgrade` process on your development environments, you can add a log the in following class :
> `\Magento\SalesSequence\Model\Builder` at line 253
> 
> The log :
> `echo $this->ddlSequence->getCreateSequenceDdl($this->data['sequence_table'], $this->data['start_value']);`
> 
> This will print the query that causes the error. You can run this query manually in your database and re-run `setup:upgrade` command.
> 
> Repeat the operation 2-3 times.

Can you give more specific steps detail sir?

**Comment by dooblem** [comment]
Thanks @AymericJoubert , here is the file and the patch in order to be able to apply the workaround.

```
--- /tmp/Builder.php	2020-09-24 13:25:27.382487127 +0000
+++ vendor/magento/module-sales-sequence/Model/Builder.php	2020-09-24 13:25:46.962578276 +0000
@@ -250,6 +250,7 @@
             $this->resourceMetadata->save($metadata);
             $connection = $this->appResource->getConnection('sales');
             if (!$connection->isTableExists($this->data['sequence_table'])) {
+                echo $this->ddlSequence->getCreateSequenceDdl($this->data['sequence_table'], $this->data['start_value']);
                 $connection->query(
                     $this->ddlSequence->getCreateSequenceDdl(
                         $this->data['sequence_table'],
```

**Comment by angeline155** [comment]
Even after trying the above, I couldn't successfully complete the installation with the sample date. So, I have done below to fix the issue.
Find `Mysql.php` from in the below location

`vendor\magento\framework\DB\Adapter\Pdo`

And at line no. 527, comment the below

```
if (in_array($startSql, $this->_ddlRoutines) && strcasecmp($sqlMessage[1], 'temporary') !== 0) {
                throw new ConnectionException(AdapterInterface::ERROR_DDL_MESSAGE, E_USER_ERROR);
            }
```
So the function will look like below,

```
/**
     * Check transaction level in case of DDL query
     *
     * @param string|\Magento\Framework\DB\Select $sql
     * @return void
     * @throws Zend_Db_Adapter_Exception
     */
    protected function _checkDdlTransaction($sql)
    {
        if ($this->getTransactionLevel() > 0) {
            $sql = ltrim(preg_replace('/\s+/', ' ', $sql));
            $sqlMessage = explode(' ', $sql, 3);
            $startSql = strtolower(substr($sqlMessage[0], 0, 3));
            /*if (in_array($startSql, $this->_ddlRoutines) && strcasecmp($sqlMessage[1], 'temporary') !== 0) {
                throw new ConnectionException(AdapterInterface::ERROR_DDL_MESSAGE, E_USER_ERROR);
            }*/
        }
    }
```
Now, you could successfully complete the installtion.

**Comment by Mecalux-Developer** [comment]
This problem has been fixed in magento version 2.4.1

**Comment by mrtuvn** [comment]
@maciej-orba can you have time for test it one more

**Comment by guvra** [comment]
I still get the error on a fresh 2.4.1 install, with sample data modules enabled.

```
[Magento\\Framework\\Exception\\LocalizedException]
DDL statements are not allowed in transactions

Exception trace:
  at /app/vendor/magento/module-catalog-inventory/Model/Indexer/Stock/Action/Full.php:174
 Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Action\\Full->execute() at /app/vendor/magento/module-catalog-inventory/Model/Indexer/Stock.php:67
 Magento\\CatalogInventory\\Model\\Indexer\\Stock->executeFull() at /app/vendor/magento/framework/Interception/Interceptor.php:58
 Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->___callParent() at /app/vendor/magento/framework/Interception/Interceptor.php:138
 Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->Magento\\Framework\\Interception\\{closure}() at /app/vendor/magento/framework/Interception/Interceptor.php:153
 Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->___callPlugins() at /app/generated/code/Magento/CatalogInventory/Model/Indexer/Stock/Interceptor.php:32
 Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->executeFull() at /app/vendor/magento/module-indexer/Model/Indexer.php:416
 Magento\\Indexer\\Model\\Indexer->reindexAll() at /app/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:259
 Magento\\Indexer\\Model\\Indexer\\DependencyDecorator->reindexAll() at /app/vendor/magento/framework/Indexer/AbstractProcessor.php:79
 Magento\\Framework\\Indexer\\AbstractProcessor->reindexAll() at /app/vendor/magento/module-sales-sample-data/Setup/Patch/Data/InstallSalesSampleData.php:60
 Magento\\SalesSampleData\\Setup\\Patch\\Data\\InstallSalesSampleData->apply() at /app/vendor/magento/framework/Setup/Patch/PatchApplier.php:157
 Magento\\Framework\\Setup\\Patch\\PatchApplier->applyDataPatch() at /app/setup/src/Magento/Setup/Model/Installer.php:1081
 Magento\\Setup\\Model\\Installer->handleDBSchemaData() at /app/setup/src/Magento/Setup/Model/Installer.php:947
 Magento\\Setup\\Model\\Installer->installDataFixtures() at n/a:n/a
 call_user_func_array() at /app/setup/src/Magento/Setup/Model/Installer.php:388
 Magento\\Setup\\Model\\Installer->install() at /app/setup/src/Magento/Setup/Console/Command/InstallCommand.php:231
 Magento\\Setup\\Console\\Command\\InstallCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\\Component\\Console\\Command\\Command->run() at /app/vendor/symfony/console/Application.php:1009
 Symfony\\Component\\Console\\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:273
 Symfony\\Component\\Console\\Application->doRun() at /app/vendor/magento/framework/Console/Cli.php:115
 Magento\\Framework\\Console\\Cli->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\\Component\\Console\\Application->run() at /app/bin/magento:23
```

**Comment by maciej-orba** [comment]
I alos has this issue. This time also in 2.3.6 ....

**Comment by qsolutions-pl** [comment]
Same issue on 2.4.1  and 2.4.0

**Comment by mrtuvn** [comment]
Maybe we need update code in sampledata repo. Scenario happen when clean install at first try

**Comment by mrtuvn** [comment]
May related with this scenario
https://github.com/magento/magento2/pull/30928

**Comment by fmsthird** [comment]
Same issue, fresh local install Magento CE 2.4.1.

**Comment by fmsthird** [comment]
> May new PR fix related with this issue
> #30928
> @maciej-orba can you recheck this when you have time

how to apply this fix?

**Comment by engcom-Hotel** [comment]
Hello @maciej-orba.
Trying to reproduce the issue and not able to do it.

Steps which I have used:
PHP 7.4
MySQL  Ver 8
1. composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.0 .
 (sample data packages are not present at composer.json file yet)
2. bin/magento setup:install*
3. bin/magento deploy:mode:set developer 
4. bin/magento sampledata:deploy
 (sample data packages are present in the composer.json file)
5. bin/magento se:up
Works as expected.

Could you please provide additional details to reproduce the issue?
Thank you.

**Comment by maciej-orba** [comment]
@engcom-Hotel please refer to first post.
in your case: cleanup DB and install again WITH sample data modules in composer.json
Regards

**Comment by engcom-Hotel** [comment]
Tried, also works as expected.
Steps:
1. https://github.com/magento/magento2/issues/29334#issuecomment-740530131
2. bin/magento se:un
(DB is empty)
3. bin/magento setup:install*
Could you please try my steps and let me know if you are able to reproduce the issue?

**Comment by guvra** [comment]
On my end, on both Magento 2.4.0 and 2.4.1, I can reproduce the issue 100% of the time with the following steps:

1. Create the project using the `composer create-project ...` command
2. Manually add the sample data packages to composer.json
3. Install magento using bin/magento setup/install

We have a set of bash scripts that handles the installation of Magento, everything worked perfectly until 2.4.0.
We're using the following command to add the sample data packages to the composer.json file:
`composer suggest --no-dev | grep "magento/" | grep "sample-data" | xargs -i echo {}^100.4 | xargs composer require`

**Comment by engcom-Hotel** [comment]
@guvra 
Could you please check the issue according to my steps?
Basically, it is just  
"bin/magento sampledata:deploy"
instead of manual customization of the composer.json file.
And let me know if you can reproduce it.

**Comment by fmsthird** [comment]
This might sound unrelated but when I changed my Elasticsearch version to 7.6.0, ddl statements issue and other installation errors were gone.

**Comment by engcom-Hotel** [comment]
@maciej-orba @guvra could you please also check elasticsearch version.
Recommendation for it you may find here:
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html

**Comment by maciej-orba** [comment]
ES Version: 7.6.2

**Comment by guvra** [comment]
@engcom-Hotel I can't test it with your steps because you add the sample data packages AFTER installing magento.
This can't be done with the way we implemented our tools.

But I can confirm it's also 100% reproducible on my side with the following steps:

1. Create the project using the composer create-project ... command
2. Use `bin/magento sampledata:deploy`
3. Install magento using bin/magento setup/install

I get the following error:

```
Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/test24/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 4021 in /var/www/test24/vendor/magento/framework/App/ErrorHandler.php:61
```

Durin the step "Magento_SalesSampleData" of the installation process (same stack trace than the first post).

ES version: 7.9.3

**Comment by guvra** [comment]
Additional stack trace:

```
In Full.php line 174:

[Magento\\Framework\\Exception\\LocalizedException]
DDL statements are not allowed in transactions

Exception trace:
at /var/www/test24/vendor/magento/module-catalog-inventory/Model/Indexer/Stock/Action/Full.php:174
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Action\\Full->execute() at /var/www/test24/vendor/magento/module-catalog-inventory/Model/Indexer/Stock.php:67
Magento\\CatalogInventory\\Model\\Indexer\\Stock->executeFull() at /var/www/test24/vendor/magento/framework/Interception/Interceptor.php:58
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->___callParent() at /var/www/test24/vendor/magento/framework/Interception/Interceptor.php:138
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->Magento\\Framework\\Interception\\{closure}() at /var/www/test24/vendor/magento/framework/Interception/Interceptor.php:153
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->___callPlugins() at /var/www/test24/generated/code/Magento/CatalogInventory/Model/Indexer/Stock/Interceptor.php:32
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->executeFull() at /var/www/test24/vendor/magento/module-indexer/Model/Indexer.php:416
Magento\\Indexer\\Model\\Indexer->reindexAll() at /var/www/test24/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:259
Magento\\Indexer\\Model\\Indexer\\DependencyDecorator->reindexAll() at /var/www/test24/vendor/magento/framework/Indexer/AbstractProcessor.php:79
Magento\\Framework\\Indexer\\AbstractProcessor->reindexAll() at /var/www/test24/vendor/magento/module-sales-sample-data/Setup/Patch/Data/InstallSalesSampleData.php:60
Magento\\SalesSampleData\\Setup\\Patch\\Data\\InstallSalesSampleData->apply() at /var/www/test24/vendor/magento/framework/Setup/Patch/PatchApplier.php:157
Magento\\Framework\\Setup\\Patch\\PatchApplier->applyDataPatch() at /var/www/test24/setup/src/Magento/Setup/Model/Installer.php:1081
Magento\\Setup\\Model\\Installer->handleDBSchemaData() at /var/www/test24/setup/src/Magento/Setup/Model/Installer.php:947
Magento\\Setup\\Model\\Installer->installDataFixtures() at n/a:n/a
call_user_func_array() at /var/www/test24/setup/src/Magento/Setup/Model/Installer.php:388
Magento\\Setup\\Model\\Installer->install() at /var/www/test24/setup/src/Magento/Setup/Console/Command/InstallCommand.php:231
Magento\\Setup\\Console\\Command\\InstallCommand->execute() at /var/www/test24/vendor/symfony/console/Command/Command.php:255
Symfony\\Component\\Console\\Command\\Command->run() at /var/www/test24/vendor/symfony/console/Application.php:1009
Symfony\\Component\\Console\\Application->doRunCommand() at /var/www/test24/vendor/symfony/console/Application.php:273
Symfony\\Component\\Console\\Application->doRun() at /var/www/test24/vendor/magento/framework/Console/Cli.php:115
Magento\\Framework\\Console\\Cli->doRun() at /var/www/test24/vendor/symfony/console/Application.php:149
Symfony\\Component\\Console\\Application->run() at /var/www/test24/bin/magento:23

In Mysql.php line 528: 

[Magento\\Framework\\DB\\Adapter\\ConnectionException (256)]
DDL statements are not allowed in transactions

Exception trace:
at /var/www/test24/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:528
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_checkDdlTransaction() at /var/www/test24/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:556
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_query() at /var/www/test24/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:625
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->query() at /var/www/test24/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:95
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql\\Interceptor->query() at /var/www/test24/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:2646
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->truncateTable() at /var/www/test24/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:482
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql\\Interceptor->truncateTable() at /var/www/test24/vendor/magento/module-catalog-inventory/Model/Indexer/Stock/Action/Full.php:198
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Action\\Full->cleanIndexersTables() at /var/www/test24/vendor/magento/module-catalog-inventory/Model/Indexer/Stock/Action/Full.php:132
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Action\\Full->execute() at /var/www/test24/vendor/magento/module-catalog-inventory/Model/Indexer/Stock.php:67
Magento\\CatalogInventory\\Model\\Indexer\\Stock->executeFull() at /var/www/test24/vendor/magento/framework/Interception/Interceptor.php:58
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->___callParent() at /var/www/test24/vendor/magento/framework/Interception/Interceptor.php:138
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->Magento\\Framework\\Interception\\{closure}() at /var/www/test24/vendor/magento/framework/Interception/Interceptor.php:153
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->___callPlugins() at /var/www/test24/generated/code/Magento/CatalogInventory/Model/Indexer/Stock/Interceptor.php:32
Magento\\CatalogInventory\\Model\\Indexer\\Stock\\Interceptor->executeFull() at /var/www/test24/vendor/magento/module-indexer/Model/Indexer.php:416
Magento\\Indexer\\Model\\Indexer->reindexAll() at /var/www/test24/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:259
Magento\\Indexer\\Model\\Indexer\\DependencyDecorator->reindexAll() at /var/www/test24/vendor/magento/framework/Indexer/AbstractProcessor.php:79
Magento\\Framework\\Indexer\\AbstractProcessor->reindexAll() at /var/www/test24/vendor/magento/module-sales-sample-data/Setup/Patch/Data/InstallSalesSampleData.php:60
Magento\\SalesSampleData\\Setup\\Patch\\Data\\InstallSalesSampleData->apply() at /var/www/test24/vendor/magento/framework/Setup/Patch/PatchApplier.php:157
Magento\\Framework\\Setup\\Patch\\PatchApplier->applyDataPatch() at /var/www/test24/setup/src/Magento/Setup/Model/Installer.php:1081
Magento\\Setup\\Model\\Installer->handleDBSchemaData() at /var/www/test24/setup/src/Magento/Setup/Model/Installer.php:947
Magento\\Setup\\Model\\Installer->installDataFixtures() at n/a:n/a
call_user_func_array() at /var/www/test24/setup/src/Magento/Setup/Model/Installer.php:388
Magento\\Setup\\Model\\Installer->install() at /var/www/test24/setup/src/Magento/Setup/Console/Command/InstallCommand.php:231
Magento\\Setup\\Console\\Command\\InstallCommand->execute() at /var/www/test24/vendor/symfony/console/Command/Command.php:255
Symfony\\Component\\Console\\Command\\Command->run() at /var/www/test24/vendor/symfony/console/Application.php:1009
Symfony\\Component\\Console\\Application->doRunCommand() at /var/www/test24/vendor/symfony/console/Application.php:273
Symfony\\Component\\Console\\Application->doRun() at /var/www/test24/vendor/magento/framework/Console/Cli.php:115
Magento\\Framework\\Console\\Cli->doRun() at /var/www/test24/vendor/symfony/console/Application.php:149
Symfony\\Component\\Console\\Application->run() at /var/www/test24/bin/magento:23"
```

**Comment by engcom-Hotel** [comment]
@guvra 
Provided steps https://github.com/magento/magento2/issues/29334#issuecomment-740530131 just closer to the issue description.
I have tested it in both ways. 
1. composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.0 .
(sample data packages are not present at composer.json file yet)
2. bin/magento sampledata:deploy
(sample data packages are present in the composer.json file)
3. bin/magento setup:install*
4. bin/magento deploy:mode:set developer
5. bin/magento se:up
Also works as expected.

Could you please check it without any additional tools, just be sure that it works or not on your side?

**Comment by guvra** [comment]
@engcom-Hotel It does work when I replicate the same steps directly from the VM.

I don't know how to give you simple steps that would allow you to reproduce the issue for sure.

When I look at the stack trace, the cause of the issue is pretty logic though:
- The InstallSalesSampleData setup triggers a reindexation
- The reindexation triggers a truncate table
- Truncate table is a DDL query, which is forbidden in data setups -> exception thrown

**Comment by mrtuvn** [comment]
@engcom-Hotel have you try scenario install both magento and data at same time ? Composer update with sample data required in file composer.json and after composer downloaded all files you start installing

**Comment by dooblem** [comment]
Hello. This might not be specific to sample data. We got the issue on one project when upgrading to 2.4.

**Comment by engcom-Hotel** [comment]
For those, who have some issues with sample data composer version and can’t find the reason - try to clone it separately from https://github.com/magento/magento2-sample-data
1. gh repo clone magento/magento2-sample-data
2. php -f magento2-sample-data/dev/tools/build-sample-data.php -- --command link --ce-source .
(link it with already installed magento)
*path depends, here sample data has been downloaded to the root of the project.
3. bin/magento se:up

The additional information you may find here
https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-sample-data-clone.html

**Comment by mrtuvn** [comment]
@engcom-Hotel sample data work when install after magento installed success. But it will fails when you install same time with magento
Can you addressing this issue. I found problem with csv file here (invalid json)
https://github.com/magento/magento2-sample-data/blob/2.4-develop/app/code/Magento/CatalogRuleSampleData/fixtures/catalog_rules.csv
This file has never changed 4 years. But now i believe magento have update in core with new code and the old file structure  may not work

**Comment by engcom-Hotel** [comment]
@mrtuvn Could you please provide steps for "install at the same time"?
Is it different from steps from https://github.com/magento/magento2/issues/29334#issuecomment-740686322?
Thank you.

**Comment by mrtuvn** [comment]
Steps
1. Run composer init project (composer create-project)
2. Edit composer.json -> Add manual packages sampledata
3. Run composer update to download files modules related with sample data
4. At step all files ready in vendor 
5. Start install magento via command line

**Comment by mrtuvn** [comment]
I will try your steps mentioned tonight and will back with the results

**Comment by mrtuvn** [comment]
Followed the way https://github.com/magento/magento2/issues/29334#issuecomment-740686322 i can finished install magento full 2.4.1 with sample data without any problem! No issue
The process download sample data via composer seem very slow (Almost 40minutes in my local! I have 70Mb fast Internet connection)
Here is some screenshot 
![Screenshot from 2020-12-09 21-54-31](https://user-images.githubusercontent.com/1908873/101646144-b9e98c80-3a69-11eb-8db7-10e0c498d562.png)
![Screenshot from 2020-12-09 21-39-41](https://user-images.githubusercontent.com/1908873/101646156-beae4080-3a69-11eb-8fbf-fb288f793947.png)

**Comment by maciej-orba** [comment]
Guys, to still do `bin/magento sampledata:deploy` - this way it works.
Issue is whrn you have sample data entirs in your composer.json / lock files and thry to install magento with them

**Comment by ihor-sviziev** [comment]
Hi @maciej-orba,
Thank you for confirmation that the issue isn't reproducing anymore.
I'm closing this issue as not relevant.

**Comment by kanduvisla** [comment]
This issue is also triggered in Magento 2.4.1 and 2.3.6 by the Dotdigitalgroup_Email-module. The `Dotdigitalgroup\Email\Setup\Install\DataMigrationHelper->emptyTables()` seems to trigger the error if I look at the stack trace.

**Comment by ihor-sviziev** [comment]
@kanduvisla, could you contact their support?

**Comment by sdouma** [comment]
When I read "known issues" before I upgrade, I expect to see this.
