### ISSUE TITLE
Magento 2.4.0 release notification not showing up in backend

### ISSUE THREAD

**Issue by hostep** [magento/magento2#29363]
### Preconditions (*)
1. Magento 2.4.0 or 2.4.1 or 2.4.2 or 2.4.3 or 2.4.4 or 2.4.5 or 2.4.6 or 2.4.7 or ...

### Steps to reproduce (*)
1. Setup clean 2.4.0 or 2.4.1 or 2.4.2, ... installation, not a `2.4-develop` instance! (see reasoning below)
2. Login to backend (struggle your way through the whole 2FA process rigmarole)
3. Once finally logged in, seeing a notification at the bottom of the page:
```
We’ll try to show it again the next time you sign in to Magento Admin.
To learn more about new features, see our latest Release Notes in DevDocs' Release Information
```
4. Also notice the strange 'Next >' link in the footer
5. Logout in backend
6. Login to backend
7. Not seeing any release notifications popup

### Expected result (*)
1. Not being confused: if there are release notes for 2.4.0, show them, if there aren't, don't show that `We’ll try to show it again ...` message

### Actual result (*)
1. Being confused: is there a release notes popup for Magento 2.4.0? If yes, why isn't it showing up? If no, why is that message `We’ll try to show it again ...` showing up ...

### Additional information
https://github.com/magento/magento2/issues/29363#issuecomment-754913283

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hello @hostep 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest 2.4 code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please recheck and confirm?

**Comment by hostep** [comment]
@engcom-Oscar: I'm not sure, I think this release notification window should only pop up in fixed release versions as it is supposed to announce new big features in a new version. I don't think I ever saw it in development versions, so it can't be checked on `2.4-develop` I believe, only on 2.4.0 or 2.4.1 (which should already be available [as a beta](https://devdocs.magento.com/release/#release-schedule)).

Can you maybe check internally with the architecture team how this thing is supposed to work and why it has this confusing behavior in 2.4.0?

**Comment by hostep** [comment]
Can still reproduce in a clean 2.4.1 installation.

There is also this weird 'next' link showing up in the footer after a first login into the admin which is part of this thing:
<img width="1085" alt="Screenshot 2021-01-05 at 21 57 37" src="https://user-images.githubusercontent.com/85479/103698799-2d67b680-4fa2-11eb-872c-0b80f2f188b8.png">


This whole thing is part of the [release-notification](https://github.com/magento/magento2/tree/2.4.1/app/code/Magento/ReleaseNotification) module, here's the entire html which is rendered on the adminhtml after your first login after a new installation (in case this helps people who look into this issue to know where to start searching):

```html
<div data-bind="scope: 'release_notification.release_notification'" class="entry-edit form-inline">
        <!-- ko template: getTemplate() -->
<!-- ko foreach: {data: elems, as: 'element'} -->
    <!-- ko if: hasTemplate() --><!-- ko template: getTemplate() -->
<div data-bind="css: modalClass, hasFocus: focused" class="modal-component">
    <!-- ko if: state() || $data.modal --><!-- ko foreach: {data: elems, as: 'element'} --><!-- ko template: getTemplate() -->
<div class="fieldset-wrapper" data-bind="visible: $data.visible === undefined ? true: $data.visible, css: $data.additionalClasses, attr: {'data-level': $data.level, 'data-index': index}" data-level="0" data-index="notification_fieldset">
    <!-- ko if: label --><!-- /ko -->

    <div class="admin__fieldset-wrapper-content _hide" data-bind="css: {'admin__collapsible-content': collapsible, '_show': opened, '_hide': !opened()}">
        <!-- ko if: opened() || _wasOpened || initializeFieldsetDataByDefault --><fieldset class="admin__fieldset" data-bind="foreach: {data: elems, as: 'element'}"><!-- ko template: getTemplate() -->

<div class="admin__field-complex release-notification-text" data-bind="css: $data.additionalClasses, attr: {'data-index': index}" data-index="notification_text">

    <!-- ko if: label --><!-- /ko -->

    <div class="admin__field-complex-elements" data-bind="foreach: {data: elems, as: 'element'}"></div>

    <!-- ko if: $data.content --><!-- /ko -->

    <!-- ko if: $data.text --><div class="admin__field-complex-text" data-bind="html: $data.text"><p>We’ll try to show it again the next time you sign in to Magento Admin.</p>
                        <p>To learn more about new features, see our latest Release Notes in
                        <a href="https://devdocs.magento.com/magento-release-information.html" target="_blank">DevDocs' Release Information</a>.
                        </p></div><!-- /ko -->
</div>
<!-- /ko --><!-- ko template: getTemplate() -->
<!-- ko foreach: {data: elems, as: 'element'} -->
    <!-- ko if: hasTemplate() --><!-- ko template: getTemplate() -->
<!-- ko if: visible --><!-- ko template: elementTmpl -->
<button type="button" data-bind="css: buttonClasses, attr: {'data-index': index}, click: action, disable: disabled" class="release-notification-button-next action-additional" data-index="notification_button_next">
    <span data-bind="text: title">Next &gt;</span>
</button>

<!-- ko if: childError --><!-- /ko -->
<!-- /ko --><!-- /ko -->
<!-- /ko --><!-- /ko -->
<!-- /ko -->
<!-- /ko --></fieldset><!-- /ko -->
    </div>
</div>
<!-- /ko --><!-- /ko --><!-- /ko -->
</div>
<!-- /ko --><!-- /ko -->

    <!-- ko if: hasTemplate() --><!-- ko template: getTemplate() -->
<div data-bind="css: modalClass, hasFocus: focused" class="modal-component">
    <!-- ko if: state() || $data.modal --><!-- /ko -->
</div>
<!-- /ko --><!-- /ko -->

    <!-- ko if: hasTemplate() --><!-- ko template: getTemplate() -->
<div data-bind="css: modalClass, hasFocus: focused" class="modal-component">
    <!-- ko if: state() || $data.modal --><!-- /ko -->
</div>
<!-- /ko --><!-- /ko -->

    <!-- ko if: hasTemplate() --><!-- ko template: getTemplate() -->
<div data-bind="css: modalClass, hasFocus: focused" class="modal-component">
    <!-- ko if: state() || $data.modal --><!-- /ko -->
</div>
<!-- /ko --><!-- /ko -->
<!-- /ko -->
<!-- /ko -->
    </div>
```

This is how the release notification modal used to look back in the days of Magento 2.2.4 for example:
<img width="945" alt="Screenshot 2021-01-05 at 22 32 18" src="https://user-images.githubusercontent.com/85479/103701220-ebd90a80-4fa5-11eb-884c-1b83f9ad8636.png">



@sidolov: can we have some priorities here? It's most likely an S4 unless you guys feel like release notifications for new versions are actually important? (which they sometimes are I guess)

**Comment by hostep** [comment]
Confirming that this issue still exists on Magento 2.4.2.
It only shows up the very first time you login to the Magento admin.

For the people trying to reproduce, this release notification window only shows up on real Magento releases. Not on some development version from the `2.4-develop` or `2.5-develop` branch.

**Comment by hostep** [comment]
Still happening, not stale, it's not my fault that nobody wants to confirm this ...

**Comment by magento-engcom-team** [comment]
@engcom-Oscar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41875` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
Confirming that this issue still exists on Magento 2.4.3.

**Comment by hostep** [comment]
Confirming that this issue still exists on Magento 2.4.5.

@sidolov: if Adobe no longer plans on using the release notifications in the future in the backoffice, I would strongly suggest that the `magento/module-release-notification` package is removed in future versions of Magento, because it has been broken for the last 2 years ... 🙂

**Comment by hostep** [comment]
Still happens in Magento 2.4.7-beta3, so the deprecation of the Magento_ReleaseNotification module done in [AC-9246](https://github.com/magento/magento2/commit/3ee3962f86f422cd45657a27823a360163afcb36) was not enough to fix this.

**Comment by hostep** [comment]
Is still happening in Magento 2.4.8-beta2 😞

**Comment by Munktells** [comment]
Confirming this exact problem in 2.4.7-P4.

**Comment by hostep** [comment]
Still not fixed in 2.4.8 :(
