### ISSUE TITLE
Product Import (HUGE SQL statements/slow)

### ISSUE THREAD

**Issue by hgpit** [magento/magento2#2957]
CentOS 6.7
PHP 5.6
Apache 2.2.15
MariaDB 10.0.23

Hi all,

We are testing the product import procedure of M2CE. We have 77,000 products to bring in, but are finding the whole process to take far too long (over 8 hours - total time to be confirmed!).

Originally, we hit an issue with MariaDB/MySQL's **max_allowed_packet** setting requiring an increase from its default 1MB. We upped it to 16M (based on online recommendations). To arrive at this conclusion though, we were looking at the SQL statements being passed to the DB engine by M2 during the import procedure.

Now I am not a pro coder by any means but the statements seem insane.
For instance, one of the statements was:
"SELECT `catalog_product_entity_varchar`.`store_id`, `catalog_product_entity_varchar`.`entity_id` FROM `catalog_product_entity_varchar` WHERE (attribute_id = '115') AND ((store_id = '1' AND entity_id = '1') OR (store_id = '1' AND entity_id = '2') OR (store_id = '1' AND entity_id = '3') OR (store_id = '1' AND entity_id = '4') OR (store_id = '1' AND entity_id = '5') OR (store_id = '1' AND entity_id = '6')
...
<-- snip -->
...
OR (store_id = '1' AND entity_id = '31133'))"
The statement size was a total of 1,309KB (1,339,860 characters), and it wasn't even half way through our import procedure.

From an SQL point-of-view, is there really not a more efficient way to generate/construct these statements? Let's say the statements are reaching 10M each. That's a 10MB (plus overheads) packet to be sent to the SQL server for every single product which gets imported?
Again, I am not a developer, merely a dabbler in PHP/SQL, but this seems wrong.

Can anyone shed any light on this? Is it a bug? Is it early code which devs forgot to tighten up before release? Or is M2 not geared towards importing more than, say 1000 products at a time if you want to keep network congestion low (which certainly can't be the explanation!).

Thank you.

Elliot

**Comment by hgpit** [comment]
Here's an example of us importing a 77,000 product CSV into Magento 2 (CE & EE behave the same).

You can see that the first 1700 records are imported quite rapidly, but as the process goes on, it gets slower and slower (each database commit uses more and more resources).

We have left this process for 24 hours now (on numerous attempts), and it never completes. It's as though the server just eventually runs out of resources. Watching the system via top/htop never shows the available physical RAM running out, but a HTTPD process is constantly using 100% of a core.

![image](https://cloud.githubusercontent.com/assets/16598973/12294995/22e7540a-b9f6-11e5-80f7-e63d12149ea5.png)

If we inspect the DB engine's query log, it looks like there are over 2000 queries issued IN A SECOND just to commit one product.

Surely there is something wrong here?

Thank you for your consideration.

**Comment by hgpit** [comment]
Am I to assume that this is normal then? M2 starts quick but gradually slows down; eventually taking an infinite amount of time to import a large product list?
Is this because every one just buys third-party product importers, so no-one cares if the default importer works?

I am really disappointed in what I would consider a vital component of an ecommerce platform.
It's very difficult to seriously consider paying for EE licenses when the software performs so badly.

I am praying that someone can come along and tell me, "Oh yes, there's a bug in the import script which is fixed < here >"!

**Comment by asemenenko** [comment]
Hi @hgpit, can you provide your DB dump with import csv file you used? We can not reproduce the issue and need to look at what exactly happend on your side.

**Comment by hgpit** [comment]
Hi Andrii,

Thank you for your response. Give me a day or two, I will need to re-run
the test and host the files for you.

Best Regards,

Elliot

On 18 January 2016 at 10:42, Andrii Semenenko notifications@github.com
wrote:

> Hi @hgpit https://github.com/hgpit, can you provide your DB dump with
> import csv file you used? We can not reproduce the issue and need to look
> at what exactly happend on your side.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/2957#issuecomment-172494253.

## 

Group IT Support
Hayley Group PLC (Site 3)
Shelah Road, Halesowen, West Midlands, B63 3PG, England
Company No: 1257303. VAT No: GB 287546119
[Tel] +44 (0)121 585 5334 | [Fax] +44 (0)121 585 7924 | [www]
http://helpdesk.hayley-group.local

## 

The information contained in this e-mail is intended only for the person or 
entity to which it is addressed and may contain confidential and/or 
privileged material. If you are not the intended recipient of this e-mail, 
the use of this information or any disclosure, copying or distribution is 
strictly prohibited and may be unlawful. If you received this e-mail in 
error, please contact the sender immediately and delete the material from 
any computer.

The views expressed in this e-mail may not necessarily be the views of 
Hayley Group PLC and should not be taken as authority to carry out any 
instruction contained within.

**Comment by hgpit** [comment]
Hello,

I am re-running the import on a new VM and it's behaving the same way (the product import is gradually getting slower and slower, inevitably it will either run out of resources take an almost infinite amount of time to complete).

I would very much like to provide a DB dump and copy of all relevant logs for you to take a look at. As the data is quite sensitive I would prefer to email the download links directly if possible. Is it possible you can provide contact details or alternative method?

Thanks

Elliot

**Comment by mslabko** [comment]
Hello @hgpit,
I’m working on your issue. You can reach me using email from github account. Also, please add the hash  of commit on which you run import last time.

Thank you.

**Comment by hgpit** [comment]
Hello,

Okay, I will email the details over.

Something interesting (I hope) happened today. I built a new VM:
2 cores, 6GB RAM
CentOS 7 / Apache 2.4
PHP 7.0.2 (remi repo)
MariaDB 10.1
Magento 2.0.1

I set it all up and started import of ~80,000 products (with images) from CSV. 
I watched the HTTPD process using strace and strace constantly streamed line after line of events.
I watched top/htop and the HTTPD process was healthily jumping around.
The thing flew! It did ~74,000 products in 35 minutes, which we thought was awesome. Unfortunately, just in the last ~500 products it tripped up on privilege issues accessing some of the referenced images.

So, we corrected the file privileges and re-ran the whole CSV again (effectively 'updating'), expecting it to take around the same duration.
We watched the HTTPD process via strace and saw a short burst of events, then minutes of zero activity went by, before some more events appeared, then zero activity again etc :-/
We watched the process in top/htop and it just hogs 100% CPU constantly.

It sits for hours like this, crawling. Strace data seems to imply that it is working through the products, but at like 10~20 per minute!
We eventually, cancelled the job, rebooted, and tried just a 400 product CSV, but this returned the same result. Same excessive duration, same odd HTTPD process behaviour.

It seems that, on this combination of LAMP apps, on a clean M2 system we can initially import new products fine, but as soon as we attempt to update any, it takes an unusual/unexpected amount of time. It's as though to build one SQL query to 'update' one product, it has to evaluate every existing product (for conflicts etc), so just takes enormous resource. Even though this was only a 6GB VM, there's still plenty RAM spare during the import/update.

We have tried increasing the php_value memory_limit gradually up to 4G.
We have tried increasing MariaDB's max_allowed_packet value gradually up to 1G.
Neither makes any difference.

**Comment by mslabko** [comment]
Hello @hgpit ,
Actually in another issue we eliminated huge query, which you talk at the beginning (https://github.com/magento/magento2/commit/259a422a247432011a2c73de8a303d652fea5ab7#diff-5265af6a6f7b81e0119c8b50e57c15a4L297)
But with this query in our tests it took 2 hours instead ~30 minutes, so we were not sure, that it can fix your issue in whole. In any case I will check it again with your dump.

**Comment by hgpit** [comment]
I just tried my 80,000 product import on a new VM:
CentOS7/Apache2.4/MySQL5.6/PHP5.6/Magento 2.0.1

Same problem! First import 80,000 products okay (around 50 mins this time, but I blame the slower MySQL+PHP).
Then I try to update 433 products with a difference CSV - HTTPD process hangs for hours.

I can consistently and repeatedly replicate this issue on every VM/server/software combo I have thrown at it! It's mad that non-one can replicate it! It must be something in the air by me!

**Comment by mslabko** [comment]
Hello @hgpit, issue was fixed for develop branch. Patch for 2.0 release will be provided as soon as possible

**Comment by KrystynaKabannyk** [comment]
Hello @hgpit, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by Nym77** [comment]
I have a similar problem. 

I am using the version of Magento 2.1.2 and php7

I need to upload 7.5K of products. I tried to reduce the amount of products till 100 per file but is still have problems. Some file is processed quicly, some file is processed but with 1-2 time out and some just wait forever. 

Do you hve any sudgestion?

**Comment by mslabko** [comment]
@Nym77 , could you please provide via email your file I will try to check it: mslabko@magento.com

**Comment by fyudelgado** [comment]
Hi there, anyone solve this issue? I have the same problem.
Using Magento 2.1.7

Regards,
