### ISSUE TITLE
When saving content (cms) page get error

### ISSUE THREAD

**Issue by ovedmo** [magento/magento2#2966]
When saving content (cms) page get error:
Warning: preg_match(): Compilation failed: range out of order in character class at offset 6 in ......vendor\magento\zendframework1\library\Zend\Locale\Format.php on line 527";i:1;s:8623:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'preg_match(): C...', 'D:\bitnami\mage...', 527, Array)

it happen in two diffrent intallation !!

**Comment by mazhalai** [comment]
@ovedmo can you please give us more details of your environment? Version of PHP, Server and OS?

**Comment by ovedmo** [comment]
You can check any online demo, i test it on the online demo also and it act
the same...
בתאריך 12 בינו׳ 2016 6:10 אחה״צ,‏ "mazhalai" notifications@github.com כתב:

**Comment by ovedmo** [comment]
it not influenced by environment!!!
tested on 5 diffrent installations on diffrent servers and with diffrent php ver and dedicated magento hosting and it act the same, please edit cms page (home page let say) and try to save!!

**Comment by alankent** [comment]
Could you provide step by step details on what you did so we can try to repeat? I spun up a M2.0.0 with Luma sample data, went into Admin, Content > Blocks. I then edited "Home Page Block" to add a few extra words, clicked Save. Worked perfectly, no errors. I then went to Content > Pages, and edited the text on the 404 page and saved it. No errors.

If you could say what your set up is and which exact block you edited, we can try to repeat. It might be content sensitive, so the exact block and extact changes you are making would be helpful.

Thanks!

**Comment by ovedmo** [comment]
content -> pages -> edit (home) -> save!

2016-01-13 11:34 GMT+02:00 Alan Kent notifications@github.com:

> Could you provide step by step details on what you did so we can try to
> repeat? I spun up a M2.0.0 with Luma sample data, went into Admin, Content
> 
> > Blocks. I then edited "Home Page Block" to add a few extra words, clicked
> > Save. Worked perfectly, no errors. I then went to Content > Pages, and
> > edited the text on the 404 page and saved it. No errors.
> 
> If you could say what your set up is and which exact block you edited, we
> can try to repeat. It might be content sensitive, so the exact block and
> extact changes you are making would be helpful.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/2966#issuecomment-171230348.

## 

משה עובדיה
_וובמקס - פתרונות אינטרנט_
_נייד: 054-5758942_

**Comment by shiftedreality** [comment]
Hi @ovedmo 

Could you please add here sample content that you try to edit?
I think, it might be encoding error with some special characters

**Comment by ovedmo** [comment]
No change done, and english also...
בתאריך 22 בינו׳ 2016 10:33 לפנה״צ,‏ "Oleg Posyniak" <
notifications@github.com> כתב:

**Comment by ran2345** [comment]
I have the same problem when trying to save pages in my admin.
i get this error

> a:4:{i:0;s:227:"Warning: preg_match(): Compilation failed: range out of order in character class at offset 6 in /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Locale/Format.php on line 527";i:1;s:8368:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'preg_match(): C...', '/home/42690-336...', 527, Array)
> #1 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(527): preg_match('/^[\xE2\x80\x8E--]{0,1}[...', '', Array)
> #2 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/LocalizedToNormalized.php(100): Zend_Locale_Format::isNumber('', Array)
> #3 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Stdlib/DateTime/Filter/Date.php(55): Zend_Filter_LocalizedToNormalized->filter('')
> #4 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter.php(114): Magento\Framework\Stdlib\DateTime\Filter\Date->filter('')
> #5 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(722): Zend_Filter->filter('')
> #6 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(701): Zend_Filter_Input->_filterRule(Array)
> #7 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(785): Zend_Filter_Input->_filter()
> #8 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/zendframework1/library/Zend/Filter/Input.php(381): Zend_Filter_Input->_process()
> #9 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-cms/Controller/Adminhtml/Page/PostDataProcessor.php(54): Zend_Filter_Input->getUnescaped()
> #10 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-cms/Controller/Adminhtml/Page/Save.php(47): Magento\Cms\Controller\Adminhtml\Page\PostDataProcessor->filter(Array)
> #11 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/var/generation/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php(24): Magento\Cms\Controller\Adminhtml\Page\Save->execute()
> #12 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->execute()
> #13 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #14 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
> #15 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
> #16 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callParent('dispatch', Array)
> #17 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Array, 'adminAuthentica...')
> #18 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> #19 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #20 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #21 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Array, 'designLoader')
> #22 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
> #23 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #24 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
> #25 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Array, 'adminMassaction...')
> #26 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
> #27 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #28 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
> #29 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/var/generation/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php(39): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callPlugins('dispatch', Array, Array)
> #30 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #31 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
> #32 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
> #33 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
> #34 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
> #35 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
> #36 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #37 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
> #38 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
> #39 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #40 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> #41 /home/42690-33687.cloudwaysapps.com/vpnrbrjdek/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> #42 {main}";s:3:"url";s:124:"/admin/cms/page/save/key/2a74d8c11f8d3ecf40b413724d340e16ec8b797205b775735f6528403c680d34/back/edit/active_tab/main_section/";s:11:"script_name";s:10:"/index.php";}

I don't change any value. I just press "save" in content-->pages-->edit .

**Comment by Hammad31** [comment]
I also has the same problem, even if i want to apply new theme..

a:4:{i:0;s:182:"Warning: preg_match(): Compilation failed: range out of order in character class at offset 6 in C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Locale\Format.php on line 527";i:1;s:6997:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'preg_match(): C...', 'C:\wamp64\www\v...', 527, Array)
#1 C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Locale\Format.php(527): preg_match('/^[\xE2\x80\x8F--]{0,1}[...', '', Array)
#2 C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Filter\LocalizedToNormalized.php(100): Zend_Locale_Format::isNumber('', Array)
#3 C:\wamp64\www\vendor\magento\framework\Stdlib\DateTime\Filter\Date.php(55): Zend_Filter_LocalizedToNormalized->filter('')
#4 C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Filter.php(114): Magento\Framework\Stdlib\DateTime\Filter\Date->filter('')
#5 C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Filter\Input.php(722): Zend_Filter->filter('')
#6 C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Filter\Input.php(701): Zend_Filter_Input->_filterRule(Array)
#7 C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Filter\Input.php(785): Zend_Filter_Input->_filter()
#8 C:\wamp64\www\vendor\magento\zendframework1\library\Zend\Filter\Input.php(381): Zend_Filter_Input->_process()
#9 C:\wamp64\www\vendor\magento\module-backend\Controller\Adminhtml\System\Design\Save.php(24): Zend_Filter_Input->getUnescaped()
#10 C:\wamp64\www\vendor\magento\module-backend\Controller\Adminhtml\System\Design\Save.php(38): Magento\Backend\Controller\Adminhtml\System\Design\Save->_filterPostData(Array)
#11 C:\wamp64\www\var\generation\Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor.php(25): Magento\Backend\Controller\Adminhtml\System\Design\Save->execute()
#12 C:\wamp64\www\vendor\magento\framework\App\Action\Action.php(102): Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor->execute()
#13 C:\wamp64\www\vendor\magento\module-backend\App\AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#15 C:\wamp64\www\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#16 C:\wamp64\www\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor->___callParent('dispatch', Array)
#17 C:\wamp64\www\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor), Array, 'adminAuthentica...')
#18 C:\wamp64\www\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#19 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 C:\wamp64\www\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#21 C:\wamp64\www\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor), Array, 'designLoader')
#22 C:\wamp64\www\vendor\magento\framework\App\Action\Plugin\Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#23 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 C:\wamp64\www\vendor\magento\framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#25 C:\wamp64\www\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor), Array, 'adminMassaction...')
#26 C:\wamp64\www\vendor\magento\module-backend\App\Action\Plugin\MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#27 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 C:\wamp64\www\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#29 C:\wamp64\www\var\generation\Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor.php(40): Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#30 C:\wamp64\www\vendor\magento\framework\App\FrontController.php(55): Magento\Backend\Controller\Adminhtml\System\Design\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 C:\wamp64\www\vendor\magento\framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#33 C:\wamp64\www\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#34 C:\wamp64\www\vendor\magento\framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#35 C:\wamp64\www\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 C:\wamp64\www\vendor\magento\framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#38 C:\wamp64\www\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#39 C:\wamp64\www\vendor\magento\framework\App\Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#40 C:\wamp64\www\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#41 C:\wamp64\www\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#42 {main}";s:3:"url";s:120:"/admin/admin/system_design/save/key/0aa005b8c4364caa4ffb42412da7ba06e87947d841ccacb74a217fb9dbdf3add/active_tab/general/";s:11:"script_name";s:10:"/index.php";}

**Comment by shemayas** [comment]
Hi,
I had the same problem in Hebrew based store magento 1.9. 
In the file lib/Zend/Locale/Data/he.xml there are this rows:

```
<plusSign>‎+</plusSign> <!-- includes LRM before sign -->
<minusSign>‎-</minusSign> <!-- includes LRM before sign (002D) -->
```

Somehow the LRM sign is messing up the preg_match regular expression.
If  i remove the LRM sign all is well.

If someone has an idea how to resolve this without removing the LRM i will be happy to hear.

**Comment by POLYPERFORMANCE** [comment]
I'm having a similar issue saving content that contains javascript to Pages and Blocks in M2.1, 2 stores.

content -> pages -> edit (home) -> save page -> You saved the page! (Content: text only) 
content -> pages -> edit (home) -> save page -> 404 error: Page not found. (Content: text + javascript)

I get "404 Page not found" when I only input `<script></script>` into the Content field.

**Comment by NZLNick** [comment]
I have the same issue as Polyperformance
Version 2.1.0 Magento running on nexcess servers.
Any content with javascript I can open, edit but as soon as I save, returns 404 error page.

Any thoughts?

**Comment by POLYPERFORMANCE** [comment]
@NZLNick 
I contacted Nexcess support and they were able to track down the error and fix it.

It appears that the secondary domain located under our account was triggering a modsecurity error. Nexcess was able to identify the rules and added the needed exceptions. This appears to have fixed our particular issue.

**Comment by NZLNick** [comment]
Thanks Polyperformance.  Hadn't thought of the obvious and asking the host !!

**Comment by ovedmo** [comment]
וi try different host, it act the same!!

**Comment by arielmorry** [comment]
Had the same bug with Magento 2.1.0 + Hebrew Locale + Developer Mode. fixed it by:
find **$symbols = Zend_Locale_Data::getList($options['locale'],'symbols');**  >> in function _getRegexForType (vendor/magento/zendframework1/library/Zend/Locale/Format.php Line 554)

add after the above line:

```
    foreach ($symbols as &$symbol) {
        $symbol = preg_quote($symbol);
    }
```

This escapes special signs, and more specifically the **minus sign** in he.xml that is making all the mess.

**Comment by AVoskoboinikov** [comment]
Hi guys,

@shemayas and @arielmorry, could anyone of you provide detailed steps to reproduce issue? By 'detailed' I mean that I need to know what you have done with magento configuration after installing it. I've tried to use Magento CE 2.1.0 version with Hebrew locale but it works fine for me. Moreover, I've tried to save different texts in hebrew, japanese, korean and chinese languages and again - it works fine. 

It is possible that problem is in magento configuration or in your environment configuration. So, could you help with that steps? I will appreciate for your effort.

Thanks

**Comment by shemayas** [comment]
Hi @AzVo ,

As I mentioned it was in Magento 1.9 and was some time ago so I don't really remember the specific configuration.. 

The error was happening when trying to enter the product edit page on admin panel.

Shemaya

**Comment by arielmorry** [comment]
Hi @AzVo 
1. Install fresh copy of Magento 2.1 (Magento-CE-2.1.0-2016-06-23-02-28-19.tar.gz)
2. Set Default time zone to > Israel Standard Time (Asia/Jerusalem)
3. Set Default Currency to > Israeli New Sheqel (ILS)
4. Set Default Language to Hebrew
5. Set Developer mode
6. Deploy static content with Locale he_IL and en_US (for admin)
7. Admin > Stores > Configuration > Customers > Customer Configuration > Name And Address Options > **Enable Date of Birth** (I set it to required, but I don't think that matters)
8. Fronted Store > go to "Create New Customer Account" (Registration link > http://local.magento-test/customer/account/create/)
9. See on Screen: Exception #0 (Exception): Warning: preg_match(): Compilation failed: range out of order in character class at offset 6 in C:\wamp\www\Magento-Test\vendor\magento\zendframework1\library\Zend\Locale\Format.php on line 527 

Environment:
Wampserver 3 (64bit)
PHP 7.0.6
Apache 2.4.18
Windows 10
All Browsers of course 

Thank you

**Comment by AVoskoboinikov** [comment]
Hi, @arielmorry 

Thanks for steps. Have you installed any language packages for he_IL locale ?

**Comment by arielmorry** [comment]
@AzVo 
Hi, I have not.

In general I did install a language pack for M2 from https://github.com/Magento2Translations/language_he_il in my own project when first stumbled this error, but I installed a clean copy when wrote those steps in order to re-produce the error without any language pack installed.

**Comment by AVoskoboinikov** [comment]
Yep, I got it! I have created ticket in our locale JIRA #MAGETWO-58071 for fix. This issue will be closed after fix.

Thanks for reporting!

**Comment by slavvka** [comment]
Hi all, the issue has been fixed and delivered to mainline.

**Comment by Ctucker9233** [comment]
Is this fix just for develop or is it ready for 2.1? If it's not ready for 2.1 yet, is there an estimated time frame for when it might be ready?

**Comment by obynewman** [comment]
I am using Magento 2.1.2 version and still have this error when i am trying to save a cms block or page. Can someone tell me where can I find/apply the fix?

**Comment by arielmorry** [comment]
see my comment above: https://github.com/magento/magento2/issues/2966#issuecomment-237814927

**Comment by obynewman** [comment]
@arielmorry thanks a lot. I saw that the blocks are saved ok now. Can you advise on how to fix a similar issue for Content Pages too?

**Comment by arielmorry** [comment]
@obynewman I'm sorry, but I haven't experienced it on content pages, so I'll have to try and re-create that state locally. can you provide installation/env details: active languages, php version, steps to reproduce the error, etc.

**Comment by obynewman** [comment]
@arielmorry It's a similar situation.  Here's a practical scenario:
1. Create a new Page.
2. Add the following content, per example:
`<h2 style="text-align: center;">Best Sellers</h2>
{{block class="Infortis\Base\Block\Product\ProductList\Featured" template="product/list_featured_slider.phtml" category_id="3" product_count="12" breakpoints="[0, 1], [480, 2], [640, 3], [992, 4]" img_width="274" timeout="0" pagination="1" centered="1" hide_button="1" sort_by="name" sort_direction="DESC" block_name=""}}</div>
</div>`
3. Click Save.
I checked all the html code I have in my block and when I remove this piece of code from above, for Featured Products, the page is saved successfully. but when I am putting it back, is triggering the 404 Error message.

Platform: Magento CE 2.1.2
Timezone: GMT ( Europe/London)
Locale: English(United Kingdom)
PHP 7.0.12 

Thanks

**Comment by jtcosta** [comment]
had the same error... traced back to a lamme error on logs -> Integrity constraint violation: 1048 Column 'place' cannot be null, query was: INSERT INTO `cms_block` (`block_id`, `title`, `identifier`, `content`, `place`, `is_active`) VALUES (?, ?, ?, ?, ?, ?)

**Comment by rab14191** [comment]
any solution for this problm ???? nothing is working in yet

**Comment by romeof1980** [comment]
hi @POLYPERFORMANCE ,
thanks for pointing it out, it's helped us a lot.
The solution turned out to be as simple as contacting Nexcess and asking them to adjust apache mod_security

cheers!
