### ISSUE TITLE
Mixins js do not appear when we open product links in a new tab

### ISSUE THREAD

**Issue by Mecalux-Developer** [magento/magento2#29694]
### Preconditions (*)

1. Our ecommerce: Magento 2.3.4-p2
2. php version:  7.3.16
3. Database: Mysql 5.7
4. Varnish: 6.2.3
5. Elasticsearch: 6.8.7
6. Redis: 5.0.4
7. Apache: 2.4.6
8. Our website: https://www.shelvingdirect.com/

### Steps to reproduce (*)

1. Create a mixin of some file on the product page. For example, override some method of the Magento_Catalog/js/price-box.js module
2. Go to the homepage of Magento 
3. Move the mouse over a product. Right-click and click "open the page in a new tab" for several products in the homepage

![image](https://user-images.githubusercontent.com/69892724/90731912-9dfb8880-e2ca-11ea-8a38-feff7e877f02.png)

### Expected result (*)

1. We must see the mixin of price-box-mixin.min.js

![image](https://user-images.githubusercontent.com/69892724/90732185-0480a680-e2cb-11ea-86b3-d682b195c2f7.png)

2. The mixin file appears when we click directly on the product instead of the right button and open the link in a new tab
### Actual result (*)

1. We see the price-box.min.js .The file price-box-mixin.min.js doesn't appear

![image](https://user-images.githubusercontent.com/69892724/90732356-46115180-e2cb-11ea-8dca-719c3e2d4f35.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Mecalux-Developer** [comment]
Thanks for your answer. We have the requirejs-config.js file created.
To reproduce this problem, we have to go to the home page, then right-click the mouse and _**open the product in a new browser tab for several products.**_

The folder structure of the example module is the following:

 
![image](https://user-images.githubusercontent.com/69892724/91009425-dbb92380-e5e0-11ea-9bfe-9c781cb1bef5.png)

The content of the files is: 

**registration.php**

```php
<?php
    \Magento\Framework\Component\ComponentRegistrar::register(
        \Magento\Framework\Component\ComponentRegistrar::MODULE,
        'Mecalux_Ejemplo',
        __DIR__
    );
```

module.xml

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Mecalux_Ejemplo" setup_version="1.0.0"/>
</config>

```

**price-box-mixin.js**

```js
define([
    'jquery',
    'Magento_Catalog/js/price-utils',
    'underscore',
    'mage/template',
    'jquery/ui'
], function ($, utils, _, mageTemplate) {
    'use strict';

    return function (priceBox) {
        $.widget('mage.priceBox', priceBox, {
            _setDefaultsFromDataSet: function _setDefaultsFromDataSet() {
               console.log("Hello world");
            },
        });

        return $.mage.priceBox;
    };
});
```
**requirejs-config.js**

```
var config = {
    config: {
        mixins: {
            'Magento_Catalog/js/price-box': {
                'Mecalux_Ejemplo/js/price-box-mixin': true
            }
        }
    }
};
```

**Comment by Mecalux-Developer** [comment]
It seems the problem is fixed in 2.4. We have not been able to reproduce this problem in 2.4 either. But we have been able to reproduce this problem in 2.3.4-p2 LUMA (Vainilla)

**Comment by mrtuvn** [comment]
Don't know but from my knowleadges in 2.4 magento brings update with some improvements in JavaScript . Mixin module has been refactored to improve the loading and application of mixins for advanced bundled modules. But consider update maybe risky for live site running. We can't know problem something went wrong when some 3rd-party modules may breaks compatible

**Comment by Mecalux-Developer** [comment]
Thanks for your reply,
We urgently need a fix for this version (2.3.4-p2). Can you review this case? Some patch etc.
We are really concerned that mixins will not work when we open the pages in a new tab with the right mouse button.
Thanks again, Regards

**Comment by mrtuvn** [comment]
check a couple PRs
https://github.com/magento/magento2/pull/27690
https://github.com/magento/magento2/pull/25869
https://github.com/magento/magento2/pull/25587

**Comment by ihor-sviziev** [comment]
As it was already discussed - issue was already fixed in 2.4.x https://github.com/magento/magento2/issues/29694#issuecomment-678999702, I'm closing this issue as not relevant.

**Comment by denistrator** [comment]
@ihor-sviziev hi. the issue is still reproducible on 2.4 when using an alias instead of a path to the component in js layout
