### ISSUE TITLE
"Pending, in queue" message remain even after bulk action - update of product attributes is done

### ISSUE THREAD

**Issue by MrPotatox** [magento/magento2#29797]
- Summary of the issue,
After attempting to update product attributes in bulk I have a "stuck" system message of
[Task "Update attributes for 679 selected products": 0 item(s) have been scheduled for update.]
This has been in "Pending, in queue" status for about 2 weeks now.

### Preconditions
Magento ver. 2.3.5-p2, 2.4-develop
Using Magento Cloud Commerce (Valid for Magento Open Source as well) 

### Steps to reproduce
1. In Admin navigate to Catalog -> Products page.
2. Select all products.
3. In drop-down 'Actions' menu select "Update attributes"
4. Change desired value of any attribute (like description) and save.

### Expected result
After all product attributes changed to the desired value, bulk action message should inform about task complete 

### Actual result
Bulk actions / system message still displaying at top of page.

![image](https://user-images.githubusercontent.com/63432576/91551143-a171be00-e921-11ea-9085-7d8f0feaa433.png)
![image](https://user-images.githubusercontent.com/63432576/91551264-cb2ae500-e921-11ea-91ab-71fbdbc85379.png)

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by jackrevate** [comment]
Having same issue with 2.4.0, upgraded from 2.3.5-p1 to 2.3.5-p2 then to 2.4.0.

It's really annoying, hoping this can be fixed asap.

**Comment by codemastering** [comment]
Having the same issue with 2.4.0, upgraded from 2.3.5 to 2.4.0, Thankfully, I took back up before upgrade to 2.4.0, Restored back to 2.3.5

Looking forward to any temporary fix for this issue.

Thanks

**Comment by perfpcs** [comment]
I am having this same problem with 3 different servers running M 2.4.0. All have stuck tasks that used to process in minutes sitting in the bulk task grid and notices for weeks. Using rabbitmq for message broker. So is someone working on this issue? I can't see how anyone on M 2.4.0 is not having this problem. I would be happy even with a temporary fix if anyone has any ideas on this. How could M 2.4.0 even have been released with such a bad bug?? Thanks in advance if anyone can help.

**Comment by perfpcs** [comment]
To add further info for us it is various consumers and tasks getting stuck and not just the mass product attribute updates. For us we have 50-100 tasks involving Nosto extension and their product updates that are done via cron jobs:

Task "Sync 1500 Nosto products": 15 item(s) have been scheduled for update.

These seem to complete too because I have seen the number of tasks from 50-165 just for this Nosto task. So because the number goes up and down I have to think some of these are processing but then they are not updating status in the grid. I never see any of them "completed" like I used to see in previous Magento versions where I would dismiss the completed task notices. I have never had no unfinished tasks  where the tasks are completed fairly fast and none show pending like is the case for 90% of the time in previous Magento versions (you see nothing pending for tasks in bulk actions grid).

I am curious @codemastering and @jackrevate  are you guys using mysql or rabbitmq messaging?

**Comment by TonMarton** [comment]
Hi, I am using **mysql** and **CE** and having the exact same issue. 

For me all the updates were completed (I changed price on 10 products only). But the system messages are stuck. 

I don't know if it is helpful or not, but my **queue_message** table has the following contents: 
`+----+---------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | topic_name                      | body                                                                                                                                                                                                                                                                                                                                                                                                                               |
+----+---------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10 | product_action_attribute.update | {"id":null,"bulk_uuid":"95891348-0c1b-478e-9d69-8e36c356977d","topic_name":"product_action_attribute.update","serialized_data":"{\"meta_information\":\"Update product attributes\",\"product_ids\":[\"3\",\"4\",\"5\",\"7\",\"8\",\"9\",\"16\",\"17\",\"18\",\"19\"],\"store_id\":0,\"website_id\":\"0\",\"attributes\":{\"price\":\"99999\"}}","result_serialized_data":null,"status":4,"result_message":null,"error_code":null} |
+----+---------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
`

**Comment by perfpcs** [comment]
The more I look at this the more it appears that the bulk jobs are not actually stuck but are actually done and complete but the notice of completion is not getting back to the bulk task grid and therefore it never updates all these "pendings" to "completes". So it seems to be a communication issue to tell the bulk task notices that they are complete. You never see any bulk tasks listed as "complete" in M 2.4.0 like i used to see in M 2.3.5. Then I would click the "Dismiss all the completed tasks" link. It never gets to this state to dismiss any of them as the tasks are not updating that they are complete. So that is what the problem is as I see it.
Anyone have any ideas how to resolve? Anyone having these same issues with M 2.4.0?

**Comment by codemastering** [comment]
100% agreed with @perfpcs 

i am facing same issue with Magento 2.4

anyone, please provide the fix for this.

**Comment by HamishBlank** [comment]
Also seeing this issue in Magento 2.4, job has been carried out but notification is still being displayed as "Pending, in queue..."

**Comment by perfpcs** [comment]
@VladimirZaets ..any update to this issue since it appears to be widespead Magento bug?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37717` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by perfpcs** [comment]
@engcom-Oscar to be clear which issue are you addressing here to fix. Most of us posting here are not saying the tasks are really stuck but that they only appear to be stuck . We believe the tasks are actually complete but the notices at the top of admin and the bulk action log are not updating to "complete" for the tasks listed so we can dismiss them. This is true using mysql and RabbitMQ. If you need anymore details I'd be happy to provide. Thank you.

**Comment by perfpcs** [comment]
It is good to see the title changed and that the issue is confirmed. Looking forward to any patch or fix you can provide for this as soon as it has passed QA. Thank you for your help in resolving this problem.

**Comment by hostep** [comment]
Not 100% sure, but isn't this a duplicate of https://github.com/magento/magento2/issues/29718 which was fixed by https://github.com/magento/magento2/pull/29814?

**Comment by gwharton** [comment]
#29814 fixes it for me. Although I did clear out old items from magento_bulk. New bulk attribute assignments completed properly, and I was able to dismiss the completed message as designed.

**Comment by perfpcs** [comment]
Hello guys, I read that other thread and am not seeing what exactly is the fix?? Could someone clarify what file(sd) need to be updated to fix this? thanks

**Comment by codemastering** [comment]
I am also having the same question as @perfpcs 

Thanks.

**Comment by perfpcs** [comment]
I read that whole trhreadf and must be blind as I see no fix mentioned. :(

**Comment by gwharton** [comment]
https://github.com/magento/magento2/pull/29814/files

**Comment by perfpcs** [comment]
Thank you @gwharton ! So its one file edit and 1 new file. I will test it out tonight.
thanks again.

**Comment by gwharton** [comment]
Checkout how to apply patches with composer rather than editing core files directly.

**Comment by nuzil** [comment]
So I mark it fixed by https://github.com/magento/magento2/pull/29814/files then

**Comment by perfpcs** [comment]
For me this fix does not appear to solve anything. Now the message says the update has failed even though I can see the action completed successfully on the products. Then no tasks are showing complete still where I can dismiss them. They appear pending and then after some time or days they wont be in the bulk task grid anymore but new ones will have replaced. Those would be the Nosto consumers. I don't understand why it is not showing all the completed tasks like it used to be in 2.3.5

![image](https://user-images.githubusercontent.com/22109696/94294130-5ef5ce00-ff2d-11ea-9fa5-2e04146308df.png)

 
![image](https://user-images.githubusercontent.com/22109696/94294162-6cab5380-ff2d-11ea-9325-c37babf0d827.png)

**Comment by perfpcs** [comment]
Do I need to create a new post since you closed this?

**Comment by perfpcs** [comment]
Could anyone from Magento team comment on what I should do here? Also could the others in this post ( @codemastering , @HamishBlank , @TonMarton, @jackrevate, @MrPotatox )that were having problems, has this fix worked for you or is your situation like mine where this fix does not solve anything?
Thank you.

**Comment by engcom-Oscar** [comment]
Hi @perfpcs ! I think first of all you can try that fix that been mentioned above, but please notice that it for 2.4-develop code, so you need to upgrade and check if it works for you. If it doesn't fix your issue, you feel free to reopen the ticket - just update the description if you have more details how to reproduce your issue

**Comment by perfpcs** [comment]
Hi @engcom-Oscar I did try the fix on M 2.4 and it did not solve anything with the issue. Is "2.4-develop code" something else?
How do you reopen the ticket? I can update a bit more but I pretty much have listed what is occurring in my above posts. Thank you.

**Comment by engcom-Oscar** [comment]
2.4-develop - is default branch from this repository https://github.com/magento/magento2. If you have not button 'Reopen' on the bottom of this ticket, just create a new post.

**Comment by gwharton** [comment]
I have 29814 applied ontop of 2.4.0. I've just created a new bulk attribute update task and it went through to completion successfully. Although I did get an error when displaying the log. See attached, but it atleast shows the task completed and was not stuck in pending.

![image](https://user-images.githubusercontent.com/30697781/94531257-370bb080-0234-11eb-9885-a01492907579.png)

I'll look into the 400 error separately.

![image](https://user-images.githubusercontent.com/30697781/94531399-6d493000-0234-11eb-9356-7fc22145ea57.png)

Note though that I'm not sure the 29814 fix will clear out old pending tasks. I had to manually clear them from magento_bulk table in SQL.

**Comment by perfpcs** [comment]
@gwharton did the notice and the grid list that task as completed and did you get to dismiss the notice by clicking the link?

![image](https://user-images.githubusercontent.com/22109696/94532152-7f62a880-020b-11eb-8aef-460a980d4086.png)

**Comment by gwharton** [comment]
In your case Dismiss All Completed Tasks will do nothing as it doesn't think any of your tasks have completed. I went into the database and cleared all of the rows from the magento_bulk and magento_bulk_acknowledged tables. Then the grid is clear. Now new tasks that you create will go through to completed state, where the dismiss all tasks button should work. HOWEVER, I am repeatedly getting database integrity constraint violations when hitting the Dismiss All Completed Tasks button. I have no idea if fix 29814 fixes new jobs getting to the completed state, but also breaks the dismiss all completed tasks button with database integrity constraint violation or not!

**Comment by perfpcs** [comment]
OK good news in my case. So I notice that 30 of the tasks of the 61 in the grid were dated Sept 26 and not started. The other tasks that stated on Sept 28 and 29th were actually marked that the task was "completed" So I went in the database and deleted the 30 that were listed as "not started" from the magento_bulk table. After I did this the link that says "Dismiss all completed tasks" now in fact works again! My only gripe now is that it says "dismiss all tasks" but in fact it only dismisses like 5 at one time. So I had to click the link like 6 times and then, sure enough, all my tasks were completed and no longer listed in the notices at the top. So this fix in fact **DOES WORK!:)**  Could someone though check how to make the link actually dismiss all like it says and not only 5 at one time? Thanks for everyone's help and actually posting this fix!

![image](https://user-images.githubusercontent.com/22109696/94538754-67425780-0212-11eb-8cbf-cd00fbf73cfc.png)

**Comment by forcecodema** [comment]
This issue still exists in 2.4.1.

**Comment by gwharton** [comment]
@forcecodema It will be fixed in 2.4.2 In the meantine, here is the fix https://github.com/magento/magento2/pull/29814/files

**Comment by magecoders** [comment]
I have the same issue in magento 2.3.5-p1, as per the fix https://github.com/magento/magento2/pull/29814/files, such column not exists in magento 2.3.5,  How to fix that ?

**Comment by gwharton** [comment]
Unfortunately that patch is only compatible with 2.4.xxx codebase. Not sure of the fix for 2.3.xxx.

**Comment by hostep** [comment]
@magecoders: this isn't a bug in Magento 2.3.x, this bug only existed in Magento 2.4.0 and 2.4.1

If you are running against a queue problem, try searching around some more, there is a lot of information here on github and probably out on the web which can help you narrow down your particular issue.

**Comment by forcecodema** [comment]
I changed the line in /magento_root/vendor/magento/module-asynchronous-operations/etc/db_schema.xml then run bin/magento setup:upgrade, but nothing changed...

**Comment by gwharton** [comment]
The change probably worked, its just that it only allows you to acknowledge new bulk tasks. I think existing bulk tasks that are stuck need to be manually cleared from the database unfortunately. Check and clear ut the offending items from magento_bulk, and hopefully new ones will work properly now.

**Comment by forcecodema** [comment]
I cleared all the messages. And when the new showed up i tried to dismiss them. Operation clears/acknowledges them in database (if you refresh the page they are gone), but the ui returns "Attention Something went wrong". It looks like the problem is with AJAX call?

/admin_xxxxxx/bulk/notification/dismiss/key/39e1eb81366237663820b4026c18b2a14d0e433c039549b46f4da305e2ea7d22/?isAjax=true

It returns an empty response - no errors in system.log

**Comment by forcecodema** [comment]
I found solution - the problem was JSON response in Dismiss.php action - I fixed it modifying the file as follows:

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magento\AsynchronousOperations\Controller\Adminhtml\Notification;

use Magento\AsynchronousOperations\Model\BulkNotificationManagement;
use Magento\Backend\App\Action\Context;
use Magento\Backend\App\Action;
use Magento\Framework\Controller\Result\JsonFactory;

/**
 * Class Bulk Notification Dismiss Controller
 */
class Dismiss extends Action
{
    /**
     * @var BulkNotificationManagement
     */
    private $notificationManagement;

    /**
     * @var JsonFactory
     */
    protected $resultJsonFactory;

    /**
     * Class constructor.
     *
     * @param Context $context
     * @param BulkNotificationManagement $notificationManagement
     * @param JsonFactory $resultJsonFactory
     */
    public function __construct(
        Context $context,
        BulkNotificationManagement $notificationManagement,
        JsonFactory $resultJsonFactory
    ) {
        parent::__construct($context);
        $this->notificationManagement = $notificationManagement;
		$this->resultJsonFactory = $resultJsonFactory;
    }

    /**
     * @inheritDoc
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Magento_Logging::system_magento_logging_bulk_operations');
    }

    /**
     * {@inheritdoc}
     */
    public function execute()
    {
        $bulkUuids = [];
        foreach ((array)$this->getRequest()->getParam('uuid', []) as $bulkUuid) {
            $bulkUuids[] = (string)$bulkUuid;
        }

        $isAcknowledged = $this->notificationManagement->acknowledgeBulks($bulkUuids);

        /** @var \Magento\Framework\Controller\Result\Json $result */
        $result = $this->resultJsonFactory->create(ResultFactory::TYPE_JSON);
        $response = new \Magento\Framework\DataObject();
        if (!$isAcknowledged) {
            $result->setHttpResponseCode(400);
            $response->setError(true);
        } else {
            $result->setHttpResponseCode(200);
            $response->setError(false);
        }

        $result->setData($response);

        return $result;
    }
}

```

**Comment by bhaveshpp** [comment]
After update, Magento 2.3.4 to Magento 2.4 and I was facing this issue.
Now the issue is solved after the update: https://github.com/magento/magento2/pull/29814/files
Thank you @gwharton

**Comment by bibz0r** [comment]
How can we apply this fix?

**Comment by gaiterjones** [comment]
@bibz0r for Magento 2.4.x in `app/code/Magento/AsynchronousOperations/etc/db_schema.xml` change

`<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="false"`

to

`<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="true"`

then `run bin/magento s:up`

Old jobs might well still be stuck but new jobs should complete.

**Comment by davirs** [comment]
I have same situation here with magento 2.4.0.

I did the fix in Dismiss.php as mentionated above and I did the fix inside db_schema.xml.
After did this procidures I did a setup upgrade, I cleared cache, I forced cron:run... but the problem persists.

Someone can help me to clear this queue?:
![image](https://user-images.githubusercontent.com/4355062/104770006-ec646480-574e-11eb-8820-9f2ac86f11c1.png)

there is some more thing to do to solve this problem? Thank you

**Comment by in-session** [comment]
The problem still exists even on Magento 2.4.1
Mentioned fix does not solve the problem: https://github.com/magento/magento2/pull/29814/files
The cron is running so far, even starting it via SSH did not help.

![Ashampoo_Snap_Donnerstag, 21  Januar 2021_18h26m49s_003_](https://user-images.githubusercontent.com/16542619/105387951-5df05700-5c16-11eb-9e64-0b11875e3239.png)

**Comment by OvalMedia** [comment]
The fix works as the bulk actions get executed via cron. But the message queue in magento_bulk does not get cleared.

**Comment by sumeetmagento** [comment]
> I have the same issue in magento 2.3.5-p1, as per the fix https://github.com/magento/magento2/pull/29814/files, such column not exists in magento 2.3.5, How to fix that ?

Are you able to solve it because I am also getting in 2.3.5

**Comment by sumeetmagento** [comment]
This problem also arises in Magento 2.3.5
Does anyone know how to solve this?
![update_attributes](https://user-images.githubusercontent.com/42702943/106011770-c93b9c80-60e0-11eb-8772-f0233edfeda2.png)

Cron is working fine I cross-check with indexing and when run this command - `php bin/magento queue:consumers:start product_action_attribute.update ` then the problem is solved but it's not a good way, again and again, to run these commands

**Comment by sumeetmagento** [comment]
> I have the same issue in magento 2.3.5-p1, as per the fix https://github.com/magento/magento2/pull/29814/files, such column not exists in magento 2.3.5, How to fix that ?

@magecoders 
are you able to solve on Magento 2.3.5 ?

**Comment by SAPIGMBH** [comment]
> @bibz0r for Magento 2.4.x in `vendor/magento/module-asynchronous-operations/etc/db_schema.xml` change
> 
> `<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="false"`
> 
> to
> 
> `<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="true"`
> 
> then `run bin/magento s:up`
> 
> Old jobs might well still be stuck but new jobs should complete.

For me, this solved this issue on 2.4.1. Existing "stuck" jobs I had manually removed from the database..but all "new bulk changes" after fix run without any problems.

**Comment by SAPIGMBH** [comment]
> @bibz0r for Magento 2.4.x in `vendor/magento/module-asynchronous-operations/etc/db_schema.xml` change
> 
> `<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="false"`
> 
> to
> 
> `<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="true"`
> 
> then `run bin/magento s:up`
> 
> Old jobs might well still be stuck but new jobs should complete.

For me, this solved this issue on 2.4.1. Existing "stuck" jobs I had manually removed from the database..but all "new bulk changes" after fix run without any problems.

**Comment by JustADude-86** [comment]
> @bibz0r for Magento 2.4.x in `vendor/magento/module-asynchronous-operations/etc/db_schema.xml` change
> 
> `<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="false"`
> 
> to
> 
> `<column xsi:type="int" name="operation_key" padding="10" unsigned="true" nullable="true"`
> 
> then `run bin/magento s:up`
> 
> Old jobs might well still be stuck but new jobs should complete.

For me, this solved this issue on 2.4.1. Existing "stuck" jobs I had manually removed from the database..but all "new bulk changes" after fix run without any problems.

**Comment by in-session** [comment]
In my case it seems like there were problems with the cron after the update the magento.

After reinstall the cron `bin/magento cron:install [--force]` removed old jobs manually in the DB and add the fix, it works fine
[https://github.com/magento/magento2/pull/29814/files](https://github.com/magento/magento2/pull/29814/files)

**Comment by Eddcapone** [comment]
I have this issue with Magento 2.4.2 Enterprise. I also tested with a fresh magento.

**Comment by Eddcapone** [comment]
@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment]
I updated the weight attribute of some products, lets keep an eye to it:
https://4ac6ac9a19ad3ca16429aeb14bf67949-2-4-develop.instances.magento-community.engineering/admin_1213/bulk/bulk/details/uuid/679e50be-a03c-40ac-9569-75300cf2c6aa/

**Comment by Eddcapone** [comment]
I figured out that the jobs are suddenly running successfully if you execute `php bin/magento queue:consumer:start product_action_attribute.update`. So it looks like the cron job fails to execute this command for unknown reasons

**Comment by tuyennn** [comment]
Applied this patch https://github.com/magento/magento2/pull/29814 on magento cloud 2.4.0-p1
Database changed
MariaDB [main]> EXPLAIN magento_operation;
+------------------------+------------------+------+-----+---------+----------------+
| Field                  | Type             | Null | Key | Default | Extra          |
+------------------------+------------------+------+-----+---------+----------------+
| id                     | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| operation_key          | int(10) unsigned | YES  |     | NULL    |                |
| bulk_uuid              | varbinary(39)    | YES  | MUL | NULL    |                |
| topic_name             | varchar(255)     | YES  |     | NULL    |                |
| serialized_data        | blob             | YES  |     | NULL    |                |
| result_serialized_data | blob             | YES  |     | NULL    |                |
| status                 | smallint(6)      | YES  |     | 0       |                |
| error_code             | smallint(6)      | YES  |     | NULL    |                |
| result_message         | varchar(255)     | YES  |     | NULL    |                |
+------------------------+------------------+------+-----+---------+----------------+
9 rows in set (0.00 sec)

It's actually nothing was fixed

**Comment by davirs** [comment]
Hi guys. I solved this problem editing the file env.php. I don't know why my magento had this parameters:

`    'cron_consumers_runner' => [
        'cron_run' => true,
        'max_messages' => 20000,
        'consumers' => [
            'consumer1',
            'consumer2'
        ]
    ]`

I removed this code and all catalog updates worked pretty.

I hope it helps somebody

**Comment by ueltonVeslei** [comment]
> Hi guys. I solved this problem editing the file env.php. I don't know why my magento had this parameters:
> 
> ` 'cron_consumers_runner' => [ 'cron_run' => true, 'max_messages' => 20000, 'consumers' => [ 'consumer1', 'consumer2' ] ]`
> 
> I removed this code and all catalog updates worked pretty.
> 
> I hope it helps somebody

Worked for me, thx buddy

**Comment by trojson** [comment]
I got the same issue today on 2.4.2, removed the jobs from DB - table bulk back to normal, not sure what happen on it but I think probably about the cron jobs incorrectly, also catalog price rule cron job issue once applied.

**Comment by tuyennn** [comment]
https://github.com/magento/magento2/commit/269b47af3e37fbbe76e9f38d45fdb0cf969d45e3
https://github.com/magento/magento2/commit/1d9e07b218c7c8ad1f05706828cb2dd47d2d2d58
https://github.com/magento/magento2/pull/31495
