### ISSUE TITLE
[DevX]: Forcing "Pre-Encryption" of config set via ENV is awkward and creates poor developer behaviors

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#29980]
### Summary (*)
As a developer doing deployments, I'd like to be able to set certain sensitive values at deploy time via environment configuration. Unfortunately, Magento v2.4.X requires that configuration settings set via ENV (that would otherwise be set and encrypted in the database or `app/etc/env.php`) are encrypted. 

This leads to awkward deployment behaviors where ENV configuration must be computed for an environment ahead of time with the crypt key. This leads to the following bad behaviors for developers:

1. More developers having knowledge of the value of the Magento 2 `crypt` key (a bad habit).
2. Developers explicitly setting pre-production encryption keys to the same as production encryption keys (Empiric examples of this can be provided, but this isn't a name-and-shame) 
3. Poor automation heuristics as certain kinds of deployments become exceedingly manual.

### Examples (*)
Set the following config key as an ENV variable:

```bash
CONFIG__DEFAULT__SOME_PATH_VALUE=DECRYPTED_VALUE
```

Attempt any behavior in the platform that requires using `DECRYPTED_VALUE`. Get an error because it will look like some non-sense Unicode characters.

### Proposed solution
I propose that configuration settings that require encryption and that are set via ENV are explicitly "whitelisted" from requiring encrypted storage in ENV and therefore decryption at run-time. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by damienwebdev** [comment]
Not stale.

**Comment by damienwebdev** [comment]
Stop it. This isn't stale. You are a bad bot and should be ashamed of yourself.

**Comment by LeanderFS** [comment]
Is there any progress on this issue? This issue was moved to "dev in progress" on June 11th 2021, we're currently in 2024.

**Comment by maksymz** [comment]
@LeanderFS Try configuring the config itself like this:
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd"
>
    <default>
        <some_section>
            <some_group>
                <password backend_model="Magento\Config\Model\Config\Backend\Encrypted"/>
            </configuration_option>
        </smtp>
    </default>
</config>
```

Without this "config for config" environment variables are not decrypted.

Note that we had to patch some modules like "Vertex_Tax" because configs with custom paths like this are problematic: 
 `<config_path>tax/vertex_settings/trustedId</config_path>`

**Comment by ihor-sviziev** [comment]
@LeanderFS, I'm pretty sure that was a mistake. Fixed now

**Comment by maderlock** [comment]
I can't believe this is still an issue. It would be so useful for development to allow keys to be set locally without having to pre-encrypt them. All that happens currently is that we have to move these out to separate scripts which adds complexity.
