### ISSUE TITLE
The value specified in the URL Key field would generate a URL that already exists. To resolve this conflict, you can either change the value of the URL Key field (located in the Search Engine Optimization section) to a unique value, or change the Request Path fields in all locations listed below:

### ISSUE THREAD

**Issue by elizad** [magento/magento2#30144]
### Preconditions (*)

1. Magento2.4 

### Steps to reproduce (*)

1.do a category 
2. move the category to the desired place 
3. and voila The value specified in the URL Key field would generate a URL that already exists.
To resolve this conflict, you can either change the value of the URL Key field (located in the Search Engine Optimization section) to a unique value or change the Request Path fields in all locations listed below:

### Expected result (*)

1. the category moved to its place
2.

### Actual result (*)

1. bug 
2.The value specified in the URL Key field would generate a URL that already exists.
To resolve this conflict, you can either change the value of the URL Key field (located in the Search Engine Optimization section) to a unique value, or change the Request Path fields in all locations listed below: your-categ-url

**Comment by engcom-Oscar** [comment]
Hello @elizad 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed or we missed some steps or preconditions. Could your please give some more details how to reproduce this issue and update the description?

**Comment by krishprakash** [comment]
Hi @elizad. Thank you for your report.
Feel free to reopen once you confirm that issue reproduce on 2.4-develop instance

**Comment by magefast** [comment]
Still exist bug.

New Magento 2.4.6

1) create category with name - test & Save
2) create product with name - test & Save
- will return error "The value specified in the URL Key field would generate a URL that already exists."




![New_Product___Products___Inventory___Catalog___Magento_Admin](https://github.com/magento/magento2/assets/1673611/c504173f-e784-4874-a957-874f73641ef0)

**Comment by hostep** [comment]
@magefast: that's expected behavior.

We can't have the same url point both to a category and a product. You should make all url key's unique.
