### ISSUE TITLE
Getting an issue working with Grunt

### ISSUE THREAD

**Issue by ezequielalba** [magento/magento2#3037]
I'm getting this issue after run `grunt exec:<theme>`, this shows up:

```
Processed Area: frontend, Locale: en_US, Theme: Ids/prueba, File type: less.
>> [Magento\Framework\Exception\FileSystemException]                                                                                                                                                                
>>   Cannot create a symlink for "/usr/local/devs/magento2/htdocs/vendor/magento/theme-frontend-blank/web/css/source/_reset.less" and place it to "/usr/local/devs/magento2/htdocs/pub/static/frontend/Ids/prueba/en_US/css/source/_reset.less" Warning!file_get_contents(/usr/local/devs/magento2/htdocs/var/cache//mage-tags/mage---e39_INTERCEPTION): failed to open stream: No such file or directory  

>> dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
>> Exited with code: 1.
Warning: Task "exec:prueba" failed. Use --force to continue.
```

And after i run `grunt refresh`, shows the same after it cleans all the paths.

Now, running the command for the bin/magento `dev:source-theme:deploy` got this:

```
Processed Area: frontend, Locale: en_US, Theme: Magento/luma, File type: less.

  [Magento\Framework\Exception\FileSystemException]                                                                                                                   
  Cannot create a symlink for "/usr/local/devs/magento2/htdocs/vendor/magento/theme-frontend-blank/web/css/source/_reset.less" and place it to "/usr/local/devs/mage  
  nto2/htdocs/pub/static/frontend/Magento/luma/en_US/css/source/_reset.less"                                                                                          

dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
```

I was triyng to fix this by following a lot of instructions on other issues already, nothing worked. 

Any ideas why this might be happening?
I have a VM configured running of Ubuntu 14.04.3 LTS , and have node 5.4.1 with npm 3.3.12

Update of the issue: If a run the bin/magento static:deploy and after that i run grunt less:theme it gives no errors, but when watching isnt detecting the changes in the .less files of the theme.

**Comment by mrkhoa99** [comment]
I met this issue on Windows OS, I tried to run CMD as Administrator. This issue was solved. 
I also run Grunt successfully on Ubuntu. You try to set file system permission and ownership: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by ezequielalba** [comment]
@mrkhoa99 Mmm, i tried that too, i just checked if the permission and ownership changed, but are ok. The error still there after i execute the deploy or Grunt. Let me see if the VM misses something. But i don't think so.

**Comment by ezequielalba** [comment]
@mrkhoa99 Nope, it isnt about permission. Got the same result.

**Comment by ezequielalba** [comment]
Update of the issue: If a run the bin/magento static:deploy and after that i run grunt less:theme it gives no errors, but when watching isnt detecting the changes in the .less files of the theme.

**Comment by anton-huz** [comment]
Hi @ezequielalba 
We'll do investigation under internal ticket MAGETWO-53822.

Thanks.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Getting-an-issue-working-with-Grunt/idi-p/48465).

**Comment by Quartermain** [comment]
Hi @piotrekkaminski and all

Please help me. I cazy this bug and lot many time. 
I use Win10, run CMD, Xam by administrator and have change
Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink
to
>Magento\Framework\App\View\Asset\MaterializationStrategy\Copy
 but still ERROR. 

Some time run ok

Thanks
