### ISSUE TITLE
Reorder issue with product  custom option  error "The product has required options. Enter the options and try again." on cart Page

### ISSUE THREAD

**Issue by akgola** [magento/magento2#30437]
**Preconditions (*)**

    1. Magento 2.4
    2. Reordering an order with products that have custom options as Drop Down type.

**Steps to reproduce (*)**

    1. install and Setup Fresh Magento 2.4.
    2. Create a product with custom option input type as Drop Down(Either Required or not)
    3.Add this product to cart by checking the Drop down and place an order with any payment method.
    (Now the order will be in pending state. Before any manual generation like Invoice, Shipment, Cretit Memo,.. user can Re-order successfully)
    Create an Invoice or Shipment or Credit memo or Cancel the order.
    4. Now click Reorder link of the same Order  from the Customer dashboard.
    5. Redirected to cart page with errors  "Some of the products below do not have all the required options." and "The product has required options. Enter the options and try again.".

![Shopping_Cart](https://user-images.githubusercontent.com/72659941/95657780-f2392100-0b33-11eb-9b2c-40cf248f1b6a.png)

**Expected result (*)**

    Products should be added to the shopping cart successfull by automatic selecting custom option.

**Actual result (*)**

    Failed to add product in cart with error message("Some of the products below do not have all the required options." and "The product has required options. Enter the options and try again.".

**Note:**  First this issue is reflected one of my existing websites which was upgraded to Magento 2.4. After that in R&D process we setup Fresh Magento 2.4 and tested same and found this issue also exist in fresh Installation.

**Comment by waseemids** [comment]
Hi @akgola, @krishprakash,

Given the issue has been replicated and already fixed in the **2.4-develop branch** on Reorder.php details are given below.

**Git File Path:** https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Reorder/Reorder.php
**Vendor File Path:** vendor/magento/module-sales/Model/Reorder/Reorder.php
**Function Name:** getOrderProducts
**Start Line No.** 221
**Missing Code:** ->addOptionsToResult(); before return

**Sample Code:** 

`private function getOrderProducts(string $storeId, array $orderItemProductIds): array
    {
        /** @var Collection $collection */
        $collection = $this->productCollectionFactory->create();
        $collection->setStore($storeId)
            ->addIdFilter($orderItemProductIds)
            ->addStoreFilter()
            ->addAttributeToSelect('*')
            ->joinAttribute('status', 'catalog_product/status', 'entity_id', null, 'inner')
            ->joinAttribute('visibility', 'catalog_product/visibility', 'entity_id', null, 'inner')
            ->addOptionsToResult();

        return $collection->getItems();
    }`

**Comment by engcom-Bravo** [comment]
Hello @akgola 

Thank you for your report.

This issue is already fixed in the latest 2.4-develop

Successfully reordered an order with products that have custom options as Drop Down type, the custom option is selected automatically
![Reordering](https://user-images.githubusercontent.com/51680745/97999502-123ac800-1df4-11eb-8671-c8de2065427a.gif)
So we are closing this issue. Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by DevAwesomeK** [comment]
The issue is there in magento 2.4.2 EE. Above changes are there but still the issue persist. Does anyone faced the same issue in 2.4.2?

**Comment by DevAwesomeK** [comment]
@engcom-Bravo Can you please reopen the issue?

**Comment by rockgold22** [comment]
Hi @DevAwesomeK The same is in community edition, I am working on version 2.4 and facing the same issue as in Enterprise Edition. Is it resolved and rolled out with patch? 

Kindly let me know ?

**Comment by DevAwesomeK** [comment]
@rockgold22 It is not resolved yet.

**Comment by waseemids** [comment]
@DevAwesomeK if still, you have to face any issues so please follow the above steps. I hope it will be resolved.

https://github.com/magento/magento2/issues/30437#issuecomment-707721920

**Comment by DevAwesomeK** [comment]
@waseemids  Above code is already there in 2.4.2 EE. But still the issue persist.

**Comment by DevAwesomeK** [comment]
I've found that this issue reproduces when we install magento commerce B2B modules.
