### ISSUE TITLE
Undefined index: configurable_attribute

### ISSUE THREAD

**Issue by rey8a** [magento/magento2#3053]
I keep receiving this error when trying to add configurable products. Currently running Magento ver. 2.0.1

Notice: Undefined index: configurable_attribute in /vendor/magento/module-configurable-product/Model/Product/Validator/Plugin.php on line 115

Please let me know what I can do to resolve this issue.
Thanks in advance.

**Comment by katmoon** [comment]
Hi rey8a,

Could you describe the exact steps how you create a configurable product?

Thanks,
Kateryna.

**Comment by rey8a** [comment]
Hi Kateryna, here's the steps I take when creating a configurable product. 
1. Product > Catalog
2. Add Product 
   - Configurable Product
3. Input Product Details
4. Click "Create Configurations"
   4a. Select Attributes (Selected Attributes: Color, Size)
   4b. Select colors and sizes
   4c. Add images, price and quality
5. Generate Products
6. Click save and at this point I sometimes get the error.
   "Notice: Undefined index: configurable_attribute in /vendor/magento/module-configurable-product/Model/Product/Validator/Plugin.php on line 115

Thanks,
Rey

**Comment by rey8a** [comment]
Anyone? I've been waiting patiently, can someone please let me know what I need to do to resolve this issue.

Thanks

**Comment by tanya-soroka** [comment]
@rey8a Thanks for the reporting the issue.
Ticket for the investigation has been created: MAGETWO-48393.

**Comment by joebusby** [comment]
I just noticed that this is very similar to #3228 where the same error happens  with 2.0.2 due a large number of configurations.  Also maybe #3154 
I have found I can work around (lot of work) the problem if I don't add any images during the generation of configurations, and then add them in later one at a time.  I think you need to add php memory and max variables to php.ini first to get it to work  without images.

**Comment by duhon** [comment]
Hello @rey8a ,

It looks like this issue already fixed in develop branch and will be available in 2.1 version.
Could you please check this issue on develop branch? 

Also please note, if you are trying to create more than 50 variation, then it needs to change php setting “max_input_vars” to 5000 (is set to 1000 by default)

**Comment by mslabko** [comment]
closed due to no feedback.
@rey8a, please open issue if it still reproduce on develop branch

**Comment by Crossmotion** [comment]
I can confirm the problem still exists on version 2.1.0. I have max_input_vars set to 10000 and have 100 grouped products. Error I get while trying to save an existing product is: 

Notice: Undefined index: position in .../www/vendor/magento/module-grouped-product/Model/Product/Initialization/Helper/ProductLinks/Plugin/Grouped.php on line 99

**Comment by duhon** [comment]
Hello @Crossmotion 
Please create a separate issue with other steps, because you have another error.

**Comment by vikrantbliss** [comment]
I have increased max_input_vars 7000 , But still facing same issue . Anyone please help to resolve this issue
