### ISSUE TITLE
Magento 2.4.1 Media Gallery....not ready for prime time. Fails when you have large amounts of data (images)

### ISSUE THREAD

**Issue by perfpcs** [magento/magento2#30596]
### Preconditions (*)

The new media gallery introduced in Magento 2.4.1 certainly was not vetted using a large robust shop. Maybe it was designed with 100-200 products like the using Magento sample data but I can tell you from my experience trying to use this, it does NOT work when you have a large amount images. Since we use compression software to have images ready for desktop, table, phone and WEBP use.  We have generated over a half a million images for our shop. What happens is that the images will load but the directory tree fails to generate due to sessions being destroyed and memory exhaustion. Even setting php.ini to basically unlimited use of ram and setting our instance to 192 GB physical ram, the media gallery still fails to load the directory tree. This is very disappointing! What I don't understand either is why would the media galley be set with  /media as the storage root? This is the main problem as 95% of the images in the media gallery are product images. Most shops don't use product images to create banners or make CMS blocks or pages. The correct root for media gallery in my opinion should have been the /wysiwyg directory. That is what is used when dealing with media and the CMS block and pages creation. If this was set as root then these issues with session destruction and memory failures would never happen. Or, the media gallery should exempt the catalog/product images like it is in the old media gallery. If you go to those catalog/product folders you will see there are no images. That is another correct way this gallery should have been setup, in my humble opinion.

### How to produce error (*)
1. Install M 2.4.1
2. Move your media content from your current or old website that has 500,000 or more images
3. Go to content/media galley
4. Media gallery will open with images but directory tree is missing.  You can't find folders or see any folders or even see new ones if you make any. Note the folders are created but because the tree is not there, you cannot see the folders. Also it is random whether the search, sort or other fields show up. Sometimes they do and sometimes they dont.

### Steps to reproduce (*)

1. Install M 2.4.1
2. Move your media content from your current or old website that has 500,000 or more images
3. Go to content/media galley
4. Open Media gallery 

### Expected result (*)

1. I expect that the directory tree, search, sort and full media gallery opens, not a crippled version of the media gallery that does not even work.

see various images. It should look like this:

![image](https://user-images.githubusercontent.com/22109696/96794909-149d2b00-13cd-11eb-819c-83ec3078c73d.png)

### Actual result (*)

1. Many errors in php log:

[19-Oct-2020 04:26:51 UTC] PHP Fatal error: Allowed memory size of 792723456 bytes exhausted (tried to allocate 8192 bytes) in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Filesystem/Driver/File.php on line 962
[19-Oct-2020 04:26:51 UTC] PHP Fatal error: Allowed memory size of 792723456 bytes exhausted (tried to allocate 135168 bytes) in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Session/SessionManager.php on line 151
[19-Oct-2020 04:26:51 UTC] PHP Fatal error: Allowed memory size of 792723456 bytes exhausted (tried to allocate 65536 bytes) in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 793
[19-Oct-2020 04:26:51 UTC] PHP Fatal error: Uncaught RuntimeException: Unknown: Cannot call session save handler in a recursive manner in [no active file]:0[19-Oct-2020 08:29:18 UTC] PHP Warning: DOMXPath::query(): Invalid expression in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/pelago/emogrifier/src/Emogrifier.php on line 494
[19-Oct-2020 08:29:18 UTC] PHP Warning: DOMXPath::query(): Invalid expression in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/pelago/emogrifier/src/Emogrifier.php on line 494
[19-Oct-2020 08:29:18 UTC] PHP Warning: Invalid argument supplied for foreach() in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/pelago/emogrifier/src/Emogrifier.php on line 503
[19-Oct-2020 09:06:41 UTC] PHP Fatal error: Allowed memory size of 792723456 bytes exhausted (tried to allocate 8192 bytes) in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Filesystem/Driver/File.php on line 962
[19-Oct-2020 09:06:41 UTC] PHP Fatal error: Allowed memory size of 792723456 bytes exhausted (tried to allocate 40960 bytes) in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Session/SessionManager.php on line 151
[19-Oct-2020 09:06:41 UTC] PHP Fatal error: Allowed memory size of 792723456 bytes exhausted (tried to allocate 65536 bytes) in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 793
[19-Oct-2020 09:06:41 UTC] PHP Fatal error: Uncaught RuntimeException: Unknown: Cannot call session save handler in a recursive manner in [no active file]:0[19-Oct-2020 09:54:47 UTC] PHP Fatal error: Uncaught RuntimeException: ObjectManager isn't initialized in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/App/ObjectManager.php:36
Stack trace:
#0 /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Filesystem/Directory/Read.php(78): Magento\Framework\App\ObjectManager::getInstance()
#1 /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Filesystem/Directory/Read.php(212): Magento\Framework\Filesystem\Directory\Read->validatePath()
#2 /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Code/GeneratedFiles.php(123): Magento\Framework\Filesystem\Directory\Read->isExist()
#3 /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/Code/GeneratedFiles.php(98): Magento\Framework\Code\GeneratedFiles->isCleanGeneratedFilesAllowed()
#4 /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/App/ObjectManagerFactory.php(114): Magento\Framework\Code\GeneratedFiles->cleanGeneratedFiles()
#5 /home/ in /home/cloudpanel/htdocs/www.performance-pcs.com/vendor/magento/framework/App/ObjectManager.php on line 36

2. Screenshots
![image](https://user-images.githubusercontent.com/22109696/96794647-93459880-13cc-11eb-8d43-343cde835cc7.png)
![image](https://user-images.githubusercontent.com/22109696/96794747-c38d3700-13cc-11eb-9af6-2e6fcd791284.png)

### Things we tried and results:

1. Our Host of AWS Cloud server adjusted these settings in this order:
     a. From the error shown you have reached the limit of 768M that was set on the php config file. 
         We have increased it and set to memory_limit = 1024M 
     b. The php-fpm of cli had memory_limit = 4048M. We have set this to unilimited 
     c. So we have increased the memory limit to :8092M on file ".user.ini" on Magento root & inside pub/ location.
         mgt@performance-pcs:/home/cloudpanel/htdocs/www.performance-pcs.com/pub$ cat .user.ini
         memory_limit = 8092M 
2. How we fixed: Well we didn't fix actually but we proved to ourselves that it was the number of images that caused the problem. So we moved all our images out of media except for about 200 or so. And vola! The media gallery opened fine with the proper tree structure, search and sort fields and all functions worked.

![image](https://user-images.githubusercontent.com/22109696/96798289-904ba780-13ce-11eb-98f7-e32ad6f909c8.png)

So now what?? We need to access all our **NON-PRODUCT IMAGES!**. I can turn back on old media gallery and it does work but I would like to use the new one with the Adobe image features, that is handy!
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### Additional info from Engcom
To reproduce the issue 
1. Execute this file to generate empty txt files in media folder https://gist.github.com/Nazar65/61c756ce76afa8c6718bf670794d548c execute in CMD bash glob.sh
2. Set memory_limit in php to 100MB
3. Open Media Galley

Actual Result: Media gallery directory tree component renders directory tree component

**Comment by Nazar65** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38701` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
### Additional info from Engcom
To reproduce the issue 
1. Execute this file to generate empty txt files in media folder https://gist.github.com/Nazar65/61c756ce76afa8c6718bf670794d548c execute in CMD bash glob.sh
2. Set memory_limit in php to 100MB
3. Open Media Galley

Actual Result: Media gallery directory tree component renders directory tree component

**Comment by perfpcs** [comment]
Just an update here, the new file does render the directory tree but no images show up when you go to each folder. Also the whole media gallery locks up with a spinning ajax wheel with most times no search box, no filter or sort shows up. So, yes the tree now shows but the gallery is useless to use as it is now.

**Comment by perfpcs** [comment]
So I spent many many hours testing things this weekend and trying every possible combination of fixes. What I finally determined was the problem for me was having both my static files and media files on 2 different AWS Cloudfront Distributions. Here is what I determined this weekend:

1. #30629 this pull does actually work properly with large amounts of images, In my case over 2 million images. This is true only when using **NO CDN** and Magento Base URL's are set as URL's local to the server and not pointed to AWS Cloudfront CDN distributions. See settings:

![image](https://user-images.githubusercontent.com/22109696/106410427-d2927500-6410-11eb-9b7a-9be1bcf4d608.png)

2. #31749 this pull does actually work properly with large amounts of images, In my case over 2 million. Again this works with settings pointing Static and Media to the local server via URL. Same as above.

3. Both #30629 and 31749 **DO NOT** work when Magento Static Files and Media files are served from an AWS CDN. While the directory tree loads, the images do not always load. Clicking on folders changes nothing in views. Also the search bar does not appear and clicking on any folder shows no active filters to view or click and cancel. Also Adobe Stock Images does not work at all, you can not click and save images or previews. Clicking on anything in Adobe Stock does nothing.

![image](https://user-images.githubusercontent.com/22109696/106411378-2a31e000-6413-11eb-8894-b703ac928dfb.png)

4.#30629 DOES work fine with large amounts of images (in my case over 2 million images) when the Static URL is change back to local server. I **WAS** able to use the media Cloudfront distribution though. So, something about Magento files does not like the static files being served from a Cloudfront Distribution. Bottom line, with #30629 pull, Static URL pointed to local and media URL pointed to Cloudfront server, everything worked perfect. The search bar shows, clicking on folders adds them as the active filters that you can X out and close. Search terms work fine. Adobe Stock Images works perfectly and I can add previews and images with no problems. Basically, I can say everything works perfectly as expected with #30629 and just changing Static URL to the local server.

![image](https://user-images.githubusercontent.com/22109696/106411151-80eaea00-6412-11eb-8d20-60e1e4ee7e12.png)

![image](https://user-images.githubusercontent.com/22109696/106411509-78df7a00-6413-11eb-8fe3-e81ec455552e.png)

5. #31749 for me does not work using any CDNs. I tried both Static and Media both, individual each, and nothing works with AWS Cloudfront. So #31749 **ONLY** works with static and media URLs pointed to local URLs.

So, I hope this is helpful to those working on these files. I would love to have a fix to be able to use my Static file CDN on AWS. I am not sure what the issue is, I can only report what is happening. Thanks

**Comment by thomas-kl1** [comment]
Right now I don't see the correlation between the base_url of statics and media and the filesystem lookup. Do you have many environments where sometimes you have NAS or EFS?

**Comment by perfpcs** [comment]
@thomas-kl1 I am not sure I really understand your question. But many shops use Cloundfront, Cloudflare, Fastly, etc for CDN of static and media. All I can report is that when changing the URLs in the General/Web Magento settings pointing to the CDN server vs the local server url's, for both my Magento 2.41 projects, the gallery does not work at all using your 2 files.  I don't know why though, sorry.

**Comment by thomas-kl1** [comment]
what is actually interesting is that you say the directory tree works (which the two PR tend to fix). So your issue is about filters and images when CDN is used, right?

**Comment by perfpcs** [comment]
@thomas-kl1 yes Sir, the directory tree is now forming with large data amount with both PR. So the remaining issues is with CDN and active filters and using the folders.

**Comment by perfpcs** [comment]
Just an update, after Amasty fixed some issues with their Extended Product Grid Extension that was conflicting with the new media gallery js files, I am finally able to have a fully working media gallery in the latest Magento 2.4.2 with the one file changed from #30629.
vendor/magento/module-media-gallery-ui/Model/Directories/GetDirectoryTree.php

With this one file change all now works correctly for us including using static files on CDN. The directory tree forms, the active filters work fine now and all aspects of Adobe Stock and adding images works properly.

So hopefully #30629 is added to the next Magento release and I think all will be fine.
thanks for peoples help.

**Comment by Nazar65** [comment]
@perfpcs  it would be great to have it on next release, but they decided to deliver this only in 2.5 :(

**Comment by perfpcs** [comment]
@Nazar65 well I think a lot of people with big catalogs will struggle with the new media gallery as it probably wont work for them. But, I guess It's the Magento teams decision, not mine.

**Comment by oscarsanch** [comment]
@Nazar65 Hello, I think this issue has already been fixed, **MC-41854: Page builder gallery load issue** (https://github.com/magento/magento2/commit/84e590c66b0fd3c3585bc50d784325f8dfcd81eb)
The issue was recursively reading directories(magento2.4.2)
`\Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Tree::getTreeJson
line 79
$nestedDirectories = $this->getMediaDirectory()->readRecursively($item->getFilename());`

Could you check it out?

**Comment by Nazar65** [comment]
@oscarsanch  looks like, no bcs. this commit is for the default gallery, but also does not looks good at all :) it still go over all directories and files , which is very bad if you have a lot of images. My changes which magneto does not want accept is a performance fix which allows you to open new media gallery with large catalog, but still does not resolve issue when you have really a lot of folders like 20k or 30k which will be displayed in media gallery. To Fix it at all we need to change implementation of Folder tree to load one by one only when you click for that directory. But issue that you mention not related at all to the new media gallery.

**Comment by jorgb90** [comment]
Damn I am glad this issue is fixed! Performance is terrible out of the box! #30629 did the trick for me.

Is there a way to make the wysiwyg directory as root for the gallery? No one needs access to the complete media dir..

**Comment by thomas-kl1** [comment]
@jorgb90 you can exclude directories with the following file, in the etc folder of your module:

`directory.xml`

```xml
<?xml version="1.0"?>
<!--
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_MediaGalleryApi:etc/directory.xsd">
    <exclude>
        <patterns>
            <pattern name="myIdentifier">/^myFolder/</pattern>
        </patterns>
    </exclude>
</config>
```

**Comment by pmonosolo** [comment]
I have the same issue on 2.4.2-p1 with 300,000 products. The #30629 fixes the issue. Just using the XML folder exclude does not work.  

This issue also bricks the old media gallery, so it definitely needs to be fixed.

**Comment by thomas-kl1** [comment]
@pmonosolo the exclude config does not works because it's applied once that all files are resolved by Magento instead of filtering directories while discovering the files. (this is true, no joke...)

**Comment by pmonosolo** [comment]
> @pmonosolo the exclude config does not works because it's applied once that all files are resolved by Magento instead of filtering directories while discovering the files. (this is true, no joke...)

I already did a override for the GetDirectoryTree.php file, is there a way to resync the directories?

I have seen this:
```
php bin/magento media-gallery:sync
php bin/magento media-content:sync
```
but have not tried it.

**Comment by pmonosolo** [comment]
> I have seen this:
> 
> ```
> php bin/magento media-gallery:sync
> php bin/magento media-content:sync
> ```
> 
> but have not tried it.

Nope, this didn't help.

**Comment by pmonosolo** [comment]
How'd ya'll override this class? I have tried preference and plugin methods but both did not work.

**Comment by luka4** [comment]
I fixed this with following patch (logic taken from magento version 2.3.3-p1)
`
Index: vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree_original.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- a/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree.php	(revision a5387d040efc9efcbaebd6a6c28ba591f87d07b5)
+++ b/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree.php	(date 1628075064738)
@@ -76,8 +76,7 @@
                 'path' => substr($item->getFilename(), strlen($storageRoot)),
                 'cls' => 'folder',
             ];
-            $nestedDirectories = $this->getMediaDirectory()->readRecursively($item->getFilename());
-            $hasNestedDirectories = count($nestedDirectories) > 0;
+            $hasNestedDirectories = count(glob($item->getFilename() . '/*', GLOB_ONLYDIR)) > 0;
 
             // if no nested directories inside dir, add 'leaf' state so that jstree hides dropdown arrow next to dir
             if (!$hasNestedDirectories) {
`

**Comment by barryvdh** [comment]
This also broke our Image browser. It caused the browser to logout the admin session everytime. Replacing it with the global like in previous versions fixed it.

**Comment by cjnewbs** [comment]
@luka4 Thank you for this! I was using a custom patch that just commented out lines 79-85 but your patch kept the functionality.

For context we had about 260K files in 40K directories and were getting Cloudflare 524 timeout errors. Bypassing Cloudflare resulted in a 7 min TTFB for when loading the media root.

Applying this patch reduced the TTFB to 1.7 sec. Thats on my local so on staging/prod is likely to be less.

**Comment by perfpcs** [comment]
@cjnewbs Did you load the 3 files in the official fix and adjust these 3 lines? Or use the default Magento files and only adjust these 3 lines?   I've loaded the patch but, I'm still very disappointed on how long it takes to load the media gallery compared to the old version of media gallery. This version of media gallery, although flashy looking and access to Adobe,  is so incredibly slow that it takes at least 30-60 seconds on first load in admin. And even then it is 50% chance the directory tree is missing. Maybe with 2-5 page reloads I can get it to appear. So I do not consider this a good patch or really fixed. Right now its like putting a small Bandaid on a giant bloody wound. Is anyone working on anything better to fix this glaring problem??

**Comment by cjnewbs** [comment]
@perfpcs I simply placed the patch in https://github.com/magento/magento2/issues/30596#issuecomment-892613935 (nothing more) into a file in my `m2-hotfixes` directory. The project I applied it to was a Magento Cloud project so this is auto-applied during the build stop of depoyment. (or use `vendor/bin/ece-patches apply` on your local). For non-cloud projects I normally use `cweagans/composer-patches` to apply patches. Let me know if that still is not working for, you happy to lend a hand. This has been driving me nuts over the last few days.

**Comment by perfpcs** [comment]
What is 30596(comment)? Link does not go to anything.

**Comment by cjnewbs** [comment]
The link should take you to the comment about 5 messages up (maybe a browser issue?).

Either way the patch I used is this:
```Index: vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree_original.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- a/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree.php	(revision a5387d040efc9efcbaebd6a6c28ba591f87d07b5)
+++ b/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree.php	(date 1628075064738)
@@ -76,8 +76,7 @@
                 'path' => substr($item->getFilename(), strlen($storageRoot)),
                 'cls' => 'folder',
             ];
-            $nestedDirectories = $this->getMediaDirectory()->readRecursively($item->getFilename());
-            $hasNestedDirectories = count($nestedDirectories) > 0;
+            $hasNestedDirectories = count(glob($item->getFilename() . '/*', GLOB_ONLYDIR)) > 0;
 
             // if no nested directories inside dir, add 'leaf' state so that jstree hides dropdown arrow next to dir
             if (!$hasNestedDirectories) {
```

This is working for me on 2.4.2-p2

**Comment by perfpcs** [comment]
OK I understand now. But you installed these 3 files first right?
https://github.com/magento/magento2/pull/31749

**Comment by cjnewbs** [comment]
Nope, just the patch in the comment a few messages up. Nothing else.

**Comment by perfpcs** [comment]
Hmmm...OK. I've already installed the fix in the link above. I'll try this on top and see if any improvement in speed. Thank you.

**Comment by perfpcs** [comment]
So I just checked and you must not have the latest version of all the modules as my Tree.php file does not have these lines. My composer.json for the cms module is version": "104.0.3".

**Comment by cjnewbs** [comment]
The project I applied it to is on `2.4.2-p2` and the package version of `magento/module-cms` is `104.0.2-p2`. Assuming you are on 2.4.3 and it looks more like this? https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Block/Adminhtml/Wysiwyg/Images/Tree.php#L79

Looking at that and the patch I'm using the glob method still seems much more performant. I tweaked the patch to work with the current latest version in the Magento repo:
```
Index: vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree_original.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- a/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree.php	(revision a5387d040efc9efcbaebd6a6c28ba591f87d07b5)
+++ b/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Tree.php	(date 1628075064738)
@@ -76,7 +76,7 @@
                 'path' => substr($item->getFilename(), strlen($storageRoot)),
                 'cls' => 'folder',
             ];
-            $hasNestedDirectories = $this->hasNestedDirectories($storageRoot, $item->getFilename());
+            $hasNestedDirectories = count(glob($item->getFilename() . '/*', GLOB_ONLYDIR)) > 0;

             // if no nested directories inside dir, add 'leaf' state so that jstree hides dropdown arrow next to dir
             if (!$hasNestedDirectories) {

```

Note, I have not tested this but give it a go. It does leave `hasNestedDirectories()` in the code as an unused method but the patch should still be ok.

**Comment by perfpcs** [comment]
@cjnewbs Thank you for doing this. Yes I am on latest 2.4.3. I will give it a go!

**Comment by perfpcs** [comment]
@cjnewbs So this did not work for me or should I say it made no difference. Basically, the only thing that works for me with all these patches is using these files:

GetDirectoryTree.php.30629
GetDirectoryTreeTest.php.30629
IsExcluded.php.31749

This is the only combo that gets me the tree, otherwise the dir tree never shows. All patches still take about 30 seconds on first load which is really rather poor but uses after the first after are much faster in same document. New document start slow 1st load again.
Hopefully, someone figures out something better and faster.

**Comment by perfpcs** [comment]
Actually I take that back. The files above end uo trying to insert images with thr directory "media" missing so the image is broken. And 30629 doesnt seem to work anymoew with the latest Magento. On setup:upgrade I get this error:

  Type Error occurred when creating object: Magento\MediaGallery\Model\Directory\IsExcluded, Too few arguments to function Magento\MediaGallery\Model\Directory\
  IsExcluded::__construct(), 1 passed in /home/cloudpanel/htdocs/test.performance-pcs.com/releases/2020_11_08_6_27_06_branch_mgtsys/vendor/magento/framework/Obj
  ectManager/Factory/AbstractFactory.php on line 121 and exactly 2 expected

**Comment by jlenzstaysafe** [comment]
Still an issue- How's this make it to production?

**Comment by iphigenie** [comment]
> This is also a problem in Magento 2.4.4. Directory tree is missing. 

Have you tried a super restrictive config.xml just to see if anything works at all? https://developer.adobe.com/commerce/php/tutorials/backend/modify-image-library-permissions/

Pick one tiny folder you have with a few images and put only that in the xml, just to see if it works.

eg. on 2.4.3-p1  for a folder pub/media/mytest put this in the config.xml of your main customisation module

`        <system>
            <media_storage_configuration>
                <allowed_resources>
                    <media_gallery_image_folders>
                        <mytest_image_folder>mytest</mytest_image_folder>
                    </media_gallery_image_folders>
                </allowed_resources>
            </media_storage_configuration>
        </system>`

you should see in gallery:
- category
- mytest
- wysiwyg

if you don't, it's possible something else is wrong perhaps left over from all the testing

**Comment by perfpcs** [comment]
@iphigenie  I don't think any of us are using Commerce Edition. I want to see a proper fix for the directory tree in Open Source.
If you have any ideas, we are all open to them, thanks.

**Comment by magenizr** [comment]
> @iphigenie I don't think any of us are using Commerce Edition. I want to see a proper fix for the directory tree in Open Source. If you have any ideas, we are all open to them, thanks.

Here you go https://github.com/magenizr/Magenizr_MediaGalleryFolder

**Comment by iphigenie** [comment]
> @iphigenie I don't think any of us are using Commerce Edition. I want to see a proper fix for the directory tree in Open Source. If you have any ideas, we are all open to them, thanks.

this was on open source - from the release notes

**Comment by perfpcs** [comment]
@magenizr while I appreciate you trying to make an extension to help fix this ongoing issue that the Magento team refuses to fix, I think most all of us now are on M 2.4.4 and php 8.1. Unfortunately your extension does not work for this :(
Will you release a version for the latest Magento?

![image](https://user-images.githubusercontent.com/22109696/182670928-bb00d6d4-47c2-4223-a516-fdb673f8e531.png)

**Comment by magenizr** [comment]
> @magenizr while I appreciate you trying to make an extension to help fix this ongoing issue that the Magento team refuses to fix, I think most all of us now are on M 2.4.4 and php 8.1. Unfortunately your extension does not work for this :( Will you release a version for the latest Magento?
> 

Working on it and will keep you all posted.

**Comment by perfpcs** [comment]
@magenizr 

"Working on it and will keep you all posted."

You deserve a medal if you can do this and it works! :)

**Comment by perfpcs** [comment]
@magenizr  You emailed me and I replied but your email is broken:

Delivery incomplete
--
There was a temporary problem delivering your message to tobias@magenizr.com. Gmail will retry for 45 more hours. You'll be notified if the delivery fails permanently.

Here is what I sent:

-------------------------------
Are you using all stock files from 2.4.4? Because I have 1 or 2 files edited files to the ones from the patches that others have provided as fixes to this issue.

Before I reinstall your extension and retest, please let me know if I should reset all files or use any of the file patches?

Thanks for your help with this!

Patches tried

#30629

app/code/Magento/MediaGalleryUi/Model/Directories/GetDirectoryTree.php

app/code/Magento/MediaGalleryUi/Test/Integration/Directories/GetDirectoryTreeTest.php

To fix CDN location error:

Magento\Cms\Model\Wysiwyg\Images\GetInsertImageContent.php

https://magento.stackexchange.com/questions/344757/2-4-3-page-builder-404-on-images-from-media-gallery/347679#347679

    "I use a CDN where the media path is / instead of /media. On the backend, the preview loads fine in the Media Gallery, but when the image is inserted, the CDNs domain is removed from the URL, leaving /path/to/image.jpg, which causes the image to load from the hostname of my store https://example.com/path/to/image.jpg, and https://media.mycdn.com/media/path/to/image.jpg on the frontend.

    To solve this, I have modified Magento\Cms\Model\Wysiwyg\Images\GetInsertImageContent.php, changing:

    if ($forceStaticPath) {
    // phpcs:ignore Magento2.Functions.DiscouragedFunction
    return parse_url($this->imagesHelper->getCurrentUrl() . $filename, PHP_URL_PATH);
    }

    To

    if ($forceStaticPath) {
    // phpcs:ignore Magento2.Functions.DiscouragedFunction
    return $this->imagesHelper->getCurrentUrl() . $filename;
    }

    This is because parse_url with the PHP_URL_PATH component removes the host from the URL, leaving only the path. By removing parse_url, the full URL is used on both the frontend and backend."


#31749


Files changed:

app/code/Magento/MediaGallery/Model/Directory/IsExcluded.php

app/code/Magento/MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php

app/code/Magento/MediaGalleryUi/Model/Directories/GetDirectoryTree.php

To fix CDN location error:

Magento\MediaGalleryUi\Model\InsertImageData\GetInsertImageData.php


https://magento.stackexchange.com/questions/344757/2-4-3-page-builder-404-on-images-from-media-gallery/347679#347679

    "I use a CDN where the media path is / instead of /media. On the backend, the preview loads fine in the Media Gallery, but when the image is inserted, the CDNs domain is removed from the URL, leaving /path/to/image.jpg, which causes the image to load from the hostname of my store https://example.com/path/to/image.jpg, and https://media.mycdn.com/media/path/to/image.jpg on the frontend.

    To solve this, I have modified Magento\Cms\Model\Wysiwyg\Images\GetInsertImageContent.php, changing:

    if ($forceStaticPath) {
    // phpcs:ignore Magento2.Functions.DiscouragedFunction
    return parse_url($this->imagesHelper->getCurrentUrl() . $filename, PHP_URL_PATH);
    }

    To

    if ($forceStaticPath) {
    // phpcs:ignore Magento2.Functions.DiscouragedFunction
    return $this->imagesHelper->getCurrentUrl() . $filename;
    }

    This is because parse_url with the PHP_URL_PATH component removes the host from the URL, leaving only the path. By removing parse_url, the full URL is used on both the frontend and backend."

**Comment by pmonosolo** [comment]
2.4.5 same issue, too many files (5780) and the process crashes and stalls.

**Comment by perfpcs** [comment]
2 years time and no one at Magento gives a sh*t. Still broken and they don't care. They don't have anyone that can fix quite a few of the major bugs. Its no wonder everyone is moving to Shopify. Magento has become a joke sorry to say.

**Comment by pmonosolo** [comment]
This commit seems to improve performance on my DEV server:
https://github.com/magento/magento2/blob/919ce7022aa553c0a5b28c0e1e155bce51a7464f/app/code/Magento/MediaGalleryUi/Model/Directories/GetDirectoryTree.php

My dev server would stall for 10-20 seconds to generate the folder structure, but now it's almost instant.

**Comment by pmonosolo** [comment]
Well, this fix is better, but its still buggy:

- doesnt show some old files in the folders (tried to change permissions to 777 no change)

**Comment by perfpcs** [comment]
@pmonosolo , if you don't see the issue, then you do not have a large amount of images. We have like 2 million product images on the server. The server uses Nginx. If we move say 1/2 or more of the images out of the directory, then the tree works. It just can't handle ALOT of images.

**Comment by pmonosolo** [comment]
@perfpcs hmmm, I'm in similar situation /catalog/product has millions of images on PRODUCTION, but DEV does not. 

The thing is that it should be skipping that whole folder completely:

https://developer.adobe.com/commerce/php/tutorials/backend/modify-image-library-permissions/

![image](https://user-images.githubusercontent.com/66754347/195652365-ad5886e2-b2fd-4abf-b864-01ba7700bde6.png)

The documentation here really needs an update as it's not clear what needs to be done:

- are all folders in /media blocked by default from 2.4.3-p1?
- do I need exclude list like in 2.4.3? (directory.xml)
- what needs to happen to exclude these folders?

**Comment by perfpcs** [comment]
@pmonosolo  Yes I agree with you and don't have the answer. I believe it is the catalog/product folder that's the problem. So why is it not excluded by default. Or is it? That is the million dollar question..how to do this????

**Comment by perfpcs** [comment]
I will recheck this and get back to you.

thank you.


Best Regards,

Hank Baron

/President and CEO/

<http://performance-pcs.com>

1701 Robert J. Conlan Blvd. NE, Unit #5
Palm Bay, FL 32905, USA
--------------------------------------------------------------------------------------
Toll Free: 888-381-8222 | Phone: 321-725-9969 | Fax: 321-549-5001
--------------------------------------------------------------------------------------
***@***.***>
***@***.*** ***@***.***> - Email us!
<http://www.facebook.com/PerformancePCs>
www.facebook.com/PerformancePCs <http://www.facebook.com/PerformancePCs> 
- Like us in Facebook!
<http://www.twitter.com/PerformancePCs>
www.twitter.com/PerformancePCs <http://www.twitter.com/PerformancePCs> - 
Follow us on Twitter!
<https://www.facebook.com/groups/PPCsBuildersClub>
www.facebook.com/groups/PPCsBuildersClub 
<https://www.facebook.com/groups/PPCsBuildersClub> - Loop Design, Mods, 
Builds and Layout!

**Comment by perfpcs** [comment]
@pmonosolo What is the path to directory.xml? I've never heard of this file and where it is stored and how to configure fully. Is this even found in Community?

**Comment by thomas-kl1** [comment]
Hi, Don't remember exactly but when this new feature was out with the new media gallery, the algorithm was a joke. Magento was collecting every files and folders recusively from pub/media and was iterating a second time over this list in order to exclude the files according to the patterns from the configuration.

This PR modification aims to reduce iteration (check for at each level): https://github.com/magento/magento2/pull/35404/files#diff-f9876dbb5d6835b068311c3353b9ea2d0b535c7069bf474429822a3db8c960e9R81

I've also tried to fix by using the SPL methods RecursiveIterator and filters: https://github.com/magento/magento2/pull/31749/files#diff-f9876dbb5d6835b068311c3353b9ea2d0b535c7069bf474429822a3db8c960e9R98-R107

@perfpcs directory.xml is stored like any other configuration file, in etc/
E.g: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/MediaGallery/etc/directory.xml

There's also these settings to check: https://github.com/magento/magento2/blob/735a01b39779fa7ab3f83bb39c65375f88de4748/app/code/Magento/Catalog/etc/config.xml#L67-L76

**Comment by perfpcs** [comment]
OK, I have to thank you guys because Magento has never made any of this clear. Catalog Products is NOT excluded by default. So with the suggestion from @pmonosolo my directory.xml now looks like this:

<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_MediaGalleryApi:etc/directory.xsd">
    <exclude>
        <patterns>
            <pattern name="captcha">/^captcha/</pattern>
            <pattern name="customer">/^customer/</pattern>
            <pattern name="downloadable">/^downloadable/</pattern>
            <pattern name="import">/^import/</pattern>
            <pattern name="theme">/^theme/</pattern>
            <pattern name="theme_customization">/^theme_customization/</pattern>
            <pattern name="tmp">/^tmp/</pattern>
            <pattern name="directories-with-dots">/^\./</pattern>
			<pattern name="catalog-products">/^catalog\/.*</pattern>
        </patterns>
    </exclude>
</config>

And so with this, the tree finally loads! So the question is, why is Mageno not excluding this directory by default like they mention?? Also why is my catalog/category showing? How to exclude this too? The excluded above seems like it should exclude all from the catalog folder.

![image](https://user-images.githubusercontent.com/22109696/195906901-3765055a-c4cc-4ba8-850a-30b9aeebf560.png)

Thanks for you guys help!

**Comment by pmonosolo** [comment]
> And so with this, the tree finally loads! So the question is, why is Mageno not excluding this directory by default like they mention?? Also why is my catalog/category showing? How to exclude this too? The excluded above seems like it should exclude all from the catalog folder.

@perfpcs This should be excluded, but I dont know why it's not. 

Magento 2.4.3 had this file explained, but Adobe has killed the documentation on directory.xml for some reason - I cant find it anywhere.

If you grep -r "</exclude>" vendor/magento you will see that there are a bunch of files that are doing this exclusion. So this "feature" is still a thing in 2.4.5.

You can set up more folders if you need. I used regex tester to send you the previous code:
https://regex101.com/

I had directory.xml for 2.4.3, but I thought it's ok to remove because we're using media [folder whitelisting,](https://developer.adobe.com/commerce/php/tutorials/backend/modify-image-library-permissions/) - my thought was that all the folders are blocked by default. But from what I understand now, its just blacklisting them so you cant view them, it doesnt actually block the Media Gallery from going throught it - DOH!

**Comment by perfpcs** [comment]
@pmonosolo  thank you for this. No that didnt work. Still Catalog/category is showing:

![image](https://user-images.githubusercontent.com/22109696/195911263-d681e181-6e1c-4fd5-b581-92a4ef25bea6.png)

**Comment by perfpcs** [comment]
So I've done more testing and and now even more confused. Seems maybe this was already fixed in 2.4.5 or now I am on 2.4.5-p1 but, the tree does work now. Problem is, directory.xml seems to have no function. No matter how I edit this file even excluding wysiwyg, etc, nothing ever changes with the tree. Matter of fact I've even deleted the directoryy.xml file and still the tree generates but nothing changes. For me, no matter how I edit or even if I delete the file the tree looks like this:

![image](https://user-images.githubusercontent.com/22109696/195967938-f57b87f7-5d44-4274-a31d-1b863f9d68bc.png)

Also I have noticed that the media gallery has also lost the "search box" and also the "sort by" and ascending or descending.

![image](https://user-images.githubusercontent.com/22109696/195967981-be6d01e3-84b6-4386-a175-f5e37abb359e.png)

So, I'm confused again and have no idea what to do because there is no documentation. But seems directory.xml has no function

I would love the excludes to work properly and regain the search and sort.
If anyone has any ideas, please post.
thanks.

**Comment by keerthisuresh** [comment]
Hi, 
I have a similar problem, the directory tree shows in DEV but not in production. 
The catalog/product is not present in the directory tree in the DEV. 
So I am not sure if it is already excluded. 

@perfpcs 
> Seems maybe this was already fixed in 2.4.5 or now I am on 2.4.5-p1 but, the tree does work now. 
Do you mean that upgrading magento from fixed the problem? 

I am currently on 2.4.3-p1 so might try upgrading. 

Thank you so much for your time!

**Comment by perfpcs** [comment]
@keerthisuresh 

To answer your question, I am on the latest M 2.4.5-p1 and STILL, the media gallery after all these months or years, still does not work properly. Everything is still exactly as described in my post above yours. directory.xml does nothing to change the tree and both the sort and the search are missing from my "add media" page. In addition the Adobe stock also does not work anymore. I can log in and see results from my last search but the search and sort boxes are missing here too and so I cannot choose or find any new media. I basically can do nothing with Adobe stock. So, as far as I'm concerned, the new media gallery is still broken. I'm surprised more are not complaining.

![image](https://user-images.githubusercontent.com/22109696/213258348-45215934-5363-4d8f-8440-2e0f45d39af9.png)

and you are welcome BTW. Wish someone would fix this properly.

**Comment by thomas-kl1** [comment]
Hi @perfpcs sadly the community can try to fix these issues, but without Adobe support it won't go far..

**Comment by pmonosolo** [comment]
> Do you mean that upgrading magento fixed the problem?
> I am currently on 2.4.3-p1 so might try upgrading.

@keerthisuresh no the issue is worse on 2.4.5-p1. I had to switch to old style which works ok.

**Comment by perfpcs** [comment]
@pmonosolo   wow, hard to believe that this continues to get worse instead of better. I guess Magento team is lacking good programmers for this sort of thing. This is all very disappointing and why many now go over to Shopify.

**Comment by pmonosolo** [comment]
> @pmonosolo wow, hard to believe that this continues to get worse instead of better. I guess Magento team is lacking good programmers for this sort of thing. This is all very disappointing and why many now go over to Shopify.

I think there's maybe not enough of devs - the project is huge and there are 1239187298371929 technologies included. So the complexity of issues is high.

**Comment by perfpcs** [comment]
That's for sure but still its been broken since day one of the new media gallery so I think that is over 2 years now that it is still not fixed. It's been a long time!

**Comment by jlenzstaysafe** [comment]
So, here we are, in 2023, on Magento 2.4.5-p1 Commerce/Enterprise... Issue still not fixed.

**Comment by magenizr** [comment]
Are you guys still trying add custom folders to the media gallery? Our module https://github.com/magenizr/Magenizr_MediaGalleryFolder will fix that. Happy to extend our module if something is missing.

**Comment by perfpcs** [comment]
@magenizr ...None of us need anything custom, we just need the feature to work as designed. But after 2 years I think a lot of us are just giving up. The Magento team just doesn't seem to know how to fix all the problems with this new media gallery and so we all just go back to the old media gallery. It's extremely disappointing.

**Comment by BouBooo** [comment]
A patch exists since 2.4.4 instance => ACSD-47137 (available with package magento/quality-patches)

And this is fixed in the core code with new release 2.4.6

**Comment by nazarklovanych** [comment]
The patch is only limiting folders for directory tree, but still can't handle a lot of files in it. So issue with performance not fixed at all.

**Comment by nazarklovanych** [comment]
As i sad in some of my commets, don't remember exact year ;) The only way to resolve it  correctly is rework directory tree initialization by loading only first level folders, and then others sub folders when we are clicking on a parent level. But for now i'm not interested in it, since have a lot of other things to do. But if someone from adobe can implement it, it would be great!

**Comment by arnoudhgz** [comment]
@BouBooo the patch you mentioned did the trick for us. We had a lot of images and the folder structure did not load. I came to this page because I had the same issue and the patch worked.

**Comment by tuyennn** [comment]
Any back-port available for this? the issue is no longer on 2.4.7 anymore, apparently a commit of this fix must be provided

**Comment by tuyennn** [comment]
https://github.com/magento/magento2/issues/34709

**Comment by lbajsarowicz** [comment]
All three linked fix attempts (#30629, #31749, #35404) were closed unmerged, and the original author commented on 2024-09-22 that the issue no longer reproduces on 2.4.7, pointing instead to #34709 (open, different symptom: 'Could not create directories'). Please re-QA on current 2.4-develop to confirm whether this specific issue is resolved and can be closed in favor of #34709.
