### ISSUE TITLE
Widget parameter depends does not work correctly on specified block

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2#30691]
### Preconditions (*)
1. Magento 2.4-develop
1. PHP 7, MySQL: ANY
1. Related issues / prs: https://github.com/magento/magento2/issues/6868 https://github.com/magento/magento2/issues/13316 https://github.com/magento/magento2/pull/30570

### Steps to reproduce (*)
1. Create a custom widget with widget.xml file
1. Create **required** select option chooser
```xml
<parameter name="category*id" xsi:type="block" visible="true" required="true" sort*order="50"]
    [label translate="true"]Category[/label]
    [depends]
        [parameter name="type" value="category" /]
    [/depends]
    [block class="Magento\Catalog\Block\Adminhtml\Category\Widget\Chooser"]
        [data]
            [item name="button" xsi:type="array"]
                [item name="open" xsi:type="string" translate="true"]Select Category...[/item]
            [/item]
        [/data]
    [/block]
[/parameter]
{code}
1. Create a **custom input/textarea** with validation classes using a custom block
{code:xml}
[parameter name="reviews*to_display" xsi:type="block" visible="true" required="true" sort*order="60"]
    [label translate="true"]Reviews to Display[/label]
    [depends]
        [parameter name="type" value="category" /]
    [/depends]
    [block class="Vendor\Module\Block\Adminhtml\Widget\Parameter\Number" /]
[/parameter]
{code}
{code:php}
[?php

declare(strict_types=1);

namespace Vendor\Module\Block\Adminhtml\Widget\Parameter;

use Magento\Backend\Block\Template;
use Magento\Backend\Block\Template\Context;
use Magento\Framework\Data\Form\Element\AbstractElement;
use Magento\Framework\Data\Form\Element\Factory as ElementFactory;

class Number extends Template
{
    /**
    * @var ElementFactory
     */
    private $elementFactory;

    /**
    * @param Context $context
    * @param ElementFactory $elementFactory
    * @param array $data
     */
    public function __construct(
        Context $context,
        ElementFactory $elementFactory,
        array $data = []
    ) {
        $this-]elementFactory = $elementFactory;
        parent::__construct($context, $data);
    }

    /**
    * @param AbstractElement $element
    * * @return AbstractElement
     */
    public function prepareElementHtml(AbstractElement $element)
    {
        $input = $this->elementFactory->create('text', ['data' => $element->getData()>);
        $input->setId($element->getId());
        $input->setForm($element->getForm());
        $input->setData('class', 'widget-option input-text admin__control-text');
        $input->addClass('validate-number')->addClass('validate-greater-than-zero');
        if ($element->getData('required')) {
            $input->addClass('required-entry');
        }

        $element->setData('after*element*html', $input->getElementHtml());
        $element->setData('value', null);

        return $element;
    }
}
```
1. Create new Widget
1. Change depended select
1. Press Save button

### Expected result (*)
1. When the chooser is hidden, the validation does not run on hidden nested inputs
![image](https://user-images.githubusercontent.com/1055999/97455685-2b053280-1949-11eb-8835-927dfc1be4ca.png)
1. The input location and associated label should be hidden according to the dependency
![image](https://user-images.githubusercontent.com/1055999/97455685-2b053280-1949-11eb-8835-927dfc1be4ca.png)

### Actual result (*)
1. Validation triggers on hidden nested input fields
![image](https://user-images.githubusercontent.com/1055999/97455895-6273df00-1949-11eb-8023-24b9a63cc2a4.png)
Switch select to display chooser
![image](https://user-images.githubusercontent.com/1055999/97455958-715a9180-1949-11eb-8482-3c3e122783c8.png)

1. Only the input field is hidden, the label remains visible
![image](https://user-images.githubusercontent.com/1055999/97455565-0c06a080-1949-11eb-9a78-31cf8b7b14c5.png)

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by engcom-Alfa** [comment]
The issue is reproducible on fresh 2.4-develop.

**Actual Result:** :heavy_multiplication_x: 

![Peek 2020-11-16 10-57](https://user-images.githubusercontent.com/51679138/99232684-e7d90980-27fa-11eb-8398-02070d58c797.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39096` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @DmitryFurs. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39096` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.2` release.

**Comment by DmitryFurs** [comment]
@magento-engcom-team @engcom-Alfa Chooser validation now works correctly, but the dependent custom field still hides only the input, and the label remains visible.
![image](https://user-images.githubusercontent.com/1055999/100577539-7ec0be00-32f1-11eb-80fa-d499d72bf2d6.png)

Point 2 in Steps to Reproduce and point 2 in Actual Results

This can also be seen in the screenshot confirming the issue
> The issue is reproducible on fresh 2.4-develop.
> 
> **Actual Result:** ✖️
> 
> ![Peek 2020-11-16 10-57](https://user-images.githubusercontent.com/51679138/99232684-e7d90980-27fa-11eb-8398-02070d58c797.gif)

**Comment by DmitryFurs** [comment]
@magento-engcom-team @engcom-Alfa I think that the task is not done to the end, in the comments above there are details. can someone reopen the issue?

**Comment by DmitryFurs** [comment]
@ihor-sviziev maybe you can help? There is no answer for a long time, but I would like this issue to be completely fixed in the next release. Or should I create a separate ticket?

**Comment by engcom-Alfa** [comment]
@DmitryFurs I'll check it.

**Comment by engcom-Alfa** [comment]
Hi @DmitryFurs.

The issue, described in the comment https://github.com/magento/magento2/issues/30691#issuecomment-735590948, is still reproducible on fresh 2.4-develop.

**Actual Result:** :heavy_multiplication_x: Only the input field is hidden, the label remains visible

![Peek 2020-12-14 09-33](https://user-images.githubusercontent.com/51679138/102056015-61f9af80-3df4-11eb-81d5-fb87bc4a0b44.gif)

So, we will reopen the issue.

**Comment by ihor-sviziev** [comment]
@engcom-Alfa the labels just disappeared. Could you add them back?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39096` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zakdma** [comment]
Additional case described in comment fixed in scope of internal code delivery of MC-39096.

**Comment by hostep** [comment]
Found 2 commits tagged with `MC-39096`, just putting them here in case this is helpful:
- https://github.com/magento/magento2/commit/f1e5c457c922aad8f6b0d439a696c61d6dc018cc (already included in Magento 2.4.2)
- https://github.com/magento/magento2/commit/95e5361be18fd2064febb8c4fbe03e7239897761 (unreleased so far)
