### ISSUE TITLE
Elastic Search interferes with the default sort order of products (changing newest first to oldest first)

### ISSUE THREAD

**Issue by zigojacko** [magento/magento2#31043]
### Preconditions (*)
1. Magento 2.4-develop
2. 2.3.5-p1 is all I have tested this in so far.

### Steps to reproduce (*)
- Create a category in Magento with several products in it, all have the position in the category set to the value 1
![image](https://user-images.githubusercontent.com/51681379/106890207-a9fcca80-66f1-11eb-8c0a-3b6f625e27d0.png)

- Go to category page

### Expected result (*)
1. The newest products in the database (the one with the highest entity_id) are shown first
![image](https://user-images.githubusercontent.com/51681379/106890774-7a9a8d80-66f2-11eb-8261-91c77a9001e9.png)
2. The Order by for the SQL query for retrieving the products
```
 SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=33
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1' ORDER BY `cat_index`.`position` asc, `e`.`entity_id` DESC
```

### Actual result (*)
1. The oldest products(with the lower entity_id) are shown first
![image](https://user-images.githubusercontent.com/51681379/106890806-84bc8c00-66f2-11eb-8b31-d15f21fab822.png)
2. The Order by for the SQL query for retrieving the products
```
SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, IFNULL(review_summary.reviews_count, 0) AS `reviews_count`, IFNULL(review_summary.rating_summary, 0) AS `rating_summary`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1'
 LEFT JOIN `review_entity_summary` AS `review_summary` ON e.entity_id = review_summary.entity_pk_value AND review_summary.store_id = 1 AND review_summary.entity_type = (SELECT `review_entity`.`entity_id` FROM `review_entity` WHERE (entity_code = 'product'))
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1 WHERE (stock_status_index.stock_status = 1) AND (e.entity_id IN (1201, 1202, 1203)) ORDER BY FIELD(e.entity_id,1201,1202,1203)
```

:warning: **Note**: In Magento 2.3.6 with `Search Engine=MySQL` the newest product in the database (the one with the highest entity_id) was shown first. With Magento 2.4-develop with `Search Engine= Elasticsearch 7` this behaviour changed. The oldest product is shown first, the newest last.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

The severity of this issue will differ between niches but for some businesses, this is quite critical. Like designer or boutique fashion retailers where the target audience frequent the website to view the latest items to hit the fashion lines etc.

---

I can't believe there are not more reports of this... I did [ask the question](https://magento.stackexchange.com/questions/326729/elastic-search-v7-changing-magento-default-product-sort-position-in-categories) on Magento Stack Exchange and it is passed by will hardly any views and zero interaction.

I'm obviously assuming this is a bug and not meant to happen.

**Comment by engcom-Delta** [comment]
Hi @zigojacko  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop with [elasticsearch](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#elasticsearch)
**Manual testing scenario:**
- Install magento with elasticsearch 
- Set Price default sort order of products on category page
![image](https://user-images.githubusercontent.com/51681379/106751971-98a0b900-6632-11eb-86d5-a98c80ddaf60.png)
- Go to category page
**Result:**
:heavy_check_mark: Products is sorted by price on category page
![Peek 2021-02-03 15-18](https://user-images.githubusercontent.com/51681379/106752963-b4588f00-6633-11eb-8339-b291c36d6490.gif)
- Go to Catalog->Categories
- Set Display Settings->Default Product Listing Sort By=Product Name for another category
- Go to category page

 **Result:**
 :heavy_check_mark: Products is sorted by product name on category page
![Peek 2021-02-03 15-19](https://user-images.githubusercontent.com/51681379/106752941-adca1780-6633-11eb-9c25-a34fd5e1dd0f.gif)


Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.

**Comment by zigojacko** [comment]
@engcom-Delta you haven't understood the problem and don't show the testing of it.

This has been confirmed in a fresh install of Magento 2 and the problem is apparent.

It is also reported across the other web by other users.

The issue is not that sorting by attribute is not working at all. It is that the default sorting is reversed. So by default, sort order will be in the order that the products have been added (newest first) providing custom sort position not set in category.

Your test doesn't show this at all.

Please can you re-open and test for the actual issue?

**Comment by zigojacko** [comment]
As an example, see this demo store.

In this category, I just added a new product and set the same 'Position' for the product as all the others ('1').

You will see the product is at the end of the list. Even though it is newer than all the others.

If I then switch Elastic Search off and revert to the default MySQL, the newest product will switch to first in the list (as will the entire product listing reverse).

This is the problem @engcom-Delta 

Please could someone re-open this issue?

**Comment by engcom-Delta** [comment]
@zigojacko I will check with updated information

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40758` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by devchris79** [comment]
Sorting by position also doesn't work #32522.

**Comment by devchris79** [comment]
This fixed for me :-)

vendor/magento/module-catalog/Block/Product/ProductList/toolbar.php at line 221
Remove the if its a position sort function, it works fine with the else function!
So you get: 

```
public function setCollection($collection)
    {
        $this->_collection = $collection;

        $this->_collection->setCurPage($this->getCurrentPage());

        // we need to set pagination only if passed value integer and more that 0
        $limit = (int)$this->getLimit();
        if ($limit) {
            $this->_collection->setPageSize($limit);
        }
        if ($this->getCurrentOrder()) {
                $this->_collection->setOrder($this->getCurrentOrder(), $this->getCurrentDirection());
        }
        return $this;
    }
```

**Comment by perryholden** [comment]
What is strange is that this was originally reported on 2.3.5-p1, but one of our sites running on 2.3.6-p1 didn't show this issue, despite it being a later version. But after upgrading to 2.4.2, it does show the issue here.

In that upgrade, we changed to Elasticsearch 7 (we were running Elasticsearch 6 on 2.3.6), so I'd way it is 100% related to Elasticsearch 7. I don't think anything in Magento changed, code-wise.

**Comment by zigojacko** [comment]
18 months on and this issue is still present...? :/

Just upgraded a store to 2.4.3-p2 and still have the default sort issue.

**Comment by jigneshc3** [comment]
The issue is still there. We have a site on Magento 2.4.5-p1 and we can still reproduce the issue. Its strange that after these many years, there is no proper solution found. 

I already tried solutions give on #34502  and #32522 . Still no luck. 

@zigojacko were you able to find solution yet? Would be great if you can share. Thanks.

**Comment by Ahmet-Djedovic** [comment]
@jigneshc3 i have implemented a fix


Model:
MODULE_DIR/Model/CatalogSearch/ResourceModel/Fulltext

`<?php

namespace Ahmet\SortOrderAddon\Model\CatalogSearch\ResourceModel\Fulltext;

use Magento\Framework\App\ObjectManager;

class Collection extends \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection
{
    protected function _renderFiltersBefore()
    {
        /**
        * @var \Magento\Framework\App\RequestInterface $request
        */
        if (isset($_SERVER['REQUEST_URI']) && !stristr($_SERVER['REQUEST_URI'], "catalogsearch")) {
            $request = ObjectManager::getInstance()->create("\Magento\Framework\App\RequestInterface");
            $attribute = $request->getParam("product_list_order", "position");
            $direction = $request->getParam("product_list_dir", "asc");
            if ($direction == 'asc') {
                $this->addAttributeToSort($attribute, \Magento\Framework\Data\Collection::SORT_ORDER_ASC);
            } elseif ($direction == 'desc') {
                $this->addAttributeToSort($attribute, \Magento\Framework\Data\Collection::SORT_ORDER_DESC);
            }
        }

        parent::_renderFiltersBefore();
    }
}`


di.xml

`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">

    <virtualType name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory" type="Magento\Catalog\Model\ResourceModel\Product\CollectionFactory">
        <arguments>
            <argument name="instanceName" xsi:type="string">Ahmet\SortOrderAddon\Model\CatalogSearch\ResourceModel\Fulltext\Collection</argument>
        </arguments>
    </virtualType>

    <virtualType name="elasticsearchCategoryCollection" type="Ahmet\SortOrderAddon\Model\CatalogSearch\ResourceModel\Fulltext\Collection"/>
    <virtualType name="elasticsearchFulltextSearchCollection" type="Ahmet\SortOrderAddon\Model\CatalogSearch\ResourceModel\Fulltext\Collection"/>

    <preference for="Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection" type="Ahmet\SortOrderAddon\Model\CatalogSearch\ResourceModel\Fulltext\Collection"/>

</config>`

**Comment by engcom-Bravo** [comment]
Hi @zigojacko,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in latest 2.4-develop instance and the issue is still reproducible.kindly refer the screenshots.


<img width="1431" alt="Image" src="https://github.com/user-attachments/assets/373a9fb2-cceb-4856-bbb4-b540ef7334f5" />




![Image](https://github.com/user-attachments/assets/4ed3404c-7f70-4bd5-853c-5433cb510d34)




 The oldest products(with the lower entity_id) are shown first.Hence confirming the issue.


Thanks.
