### ISSUE TITLE
Order remains in status 'processing' after shipping, if items get partially refunded

### ISSUE THREAD

**Issue by SchranzKatharina** [magento/magento2#31063]
We have the following problem: If an article is partially refunded (the rest of the ordered amount is sent) - the status of the order remains in the status 'processing' after shipping.

### Preconditions (*)

1. Magento 2.4.1 & 2.4-develop

### Steps to reproduce (*)

1. Create an order with multiple items ordered.
2. From the admin, create an invoice for the order.
3. From the admin, create a credit memo and refund an item only partially.
4. From the admin, create a shipping for the order and the remaining items.
5. Observe the order status.

### Expected result (*)

1. Status of the order should be 'Complete'. (As it is, when one item is fully refunded) 

### Actual result (*)

1. Status of the order stays 'Processing'.

### Additional info from Engcom
1. Create an order for a Product in the quantity of 10
2. From Admin, create an Invoice for the order. (for all 10 items)
3. Create a Credit Memo for a quantity of 5 items
4. Ship the remaining 5 items

**Expected Result**
The order should be in Status Complete as 5 items have been refunded and 5 items shipped
![order_status1](https://user-images.githubusercontent.com/51680745/100369530-abcd5200-300d-11eb-8d45-0134d5d1a509.png)

**Comment by SchranzKatharina** [comment]
@magento give me 2.4-develop instance

**Comment by SchranzKatharina** [comment]
I could recreate it with the steps mentioned above on this Magento Instance - be sure to not refund one whole item, but just a partial amount of it (We sell fabrics by the meter, not just whole units).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39445` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
Hello @SchranzKatharina 

Thank you for your report 

We Confirm that the issue is reproducible on Magento 2.4-develop

Additional info from Engcom is added to the description

**Comment by magento-engcom-team** [comment]
Hi @SchranzKatharina. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39445` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by JeroenVanLeusden** [comment]
@magento-engcom-team Do you know the commit where this is fixed?

**Comment by visualwebs** [comment]
If I inspect Magento 2.4 develop branch, still I see the same code. I think the old version fixes the bug?

https://github.com/magento/magento2/commit/cbc352e0d0235f1e8e200eee1f6587d08b1ec7ca

I recall this old version was working fine in my Magento 2.3.x projects.

One way to reproduce is very simple. Get an order with 2 items:
-  item A qty 1 
-  item B qty 2

Invoice the order, ship A and B for 1 unit.
Now refund the last item. The order still appears in process.
This happens to me in 2.4.1-p1.

**Comment by captainyoung** [comment]
I am still getting this issue. When 2 items are purchased, one is shipped, one is refunded, the status remains as "Processing".

**Comment by Goeny** [comment]
We also experienced this issue on 2.4.3

**Comment by dnd-kallard** [comment]
I've the same issue on 2.4.3

**Comment by toddliningerdesign** [comment]
@magento-engcom-team wrote:

> The related internal Jira ticket `MC-39445` was closed as `Fixed`.
> 
> The fix will be available with the upcoming `2.4.3` release.

Why wasn't this included in the 2.4.3 release as you said it would be? We have also been able to reproduce the issue in 2.4.4.

**Comment by tgreeve** [comment]
Order is still in "Processing" after invoiced and shipped, when partial quantity of a product was refunded. This problem exists in still 2.4.3-p2. Can we reopen this issue?

**Comment by dpdesignthatfits** [comment]
We have a site with this same issue in 2.4.5

**Comment by kwilliams-concentrix** [comment]
Can we get a patch for our version? 2.4.5p-2
