### ISSUE TITLE
[GraphQl] Exception are not translated to store scope.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#31351]
### Preconditions (*)

Reproduced on
1. Magento 2.3.5-p2
2. Magento 2.4.1

### Steps to reproduce (*)

1. Set the locale of a store to anything but en_US.
2. Create a translation file/database entry with one of the translatable exception strings (eg: 'currentPage value must be greater than 0.' to 'This text is translated')
3. Make a GraphQl request that will cause the exception to trigger with the Store header for the store set in 1.
````
query productList{
    products( currentPage: 0) {
        items {
            id
            name
        }
    }
}
````

### Expected result (*)

````
{
    "errors": [
        {
            "message": "This text is translated.",
            "extensions": {
                "category": "graphql-input"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "products"
            ]
        }
    ],
    "data": {
        "products": null
    }
}
````

### Actual result (*)

````
{
    "errors": [
        {
            "message": "currentPage value must be greater than 0.",
            "extensions": {
                "category": "graphql-input"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "products"
            ]
        }
    ],
    "data": {
        "products": null
    }
}
````

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment]
Having the same issue, can confirm for Magento 2.4.1.

**Comment by oneserv-heuser** [comment]
This works as a temporary solution: https://stackoverflow.com/questions/61770306/while-working-with-the-magento-2-graphql-it-seems-that-the-string-translation-do

**Comment by ReggieTe** [comment]
I'm experiencing the same issue on Magento 2.3.4   and the patch on https://stackoverflow.com/questions/61770306/while-working-with-the-magento-2-graphql-it-seems-that-the-string-translation-do seems not to be working

**Comment by Hexmage** [comment]
> I'm experiencing the same issue on Magento 2.3.4 and the patch on https://stackoverflow.com/questions/61770306/while-working-with-the-magento-2-graphql-it-seems-that-the-string-translation-do seems not to be working

It only seems to translate to the default store locale so if you have multiple locales it breaks.

**Comment by Hexmage** [comment]
````
<?php

namespace RightSpirits\GraphQlExceptionMessageFix\Plugin\Controller;

use Magento\Framework\App\Area;
use Magento\Framework\App\AreaList;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\App\State;
use Magento\Framework\Locale\ResolverInterface;
use Magento\Framework\TranslateInterface;
use Magento\GraphQl\Controller\GraphQl;
use Magento\Store\Model\StoreManagerInterface;

class GraphQlPlugin
{
    /** @var AreaList $areaList */
    private $areaList;

    /** @var State $appState */
    private $appState;
    /**
     * @var StoreManagerInterface
     */
    private $storeManager;
    /**
     * @var ResolverInterface
     */
    private $localeResolver;

    public function __construct(
        AreaList $areaList,
        State $appState,
        TranslateInterface $translation,
        ResolverInterface $localeResolver,
        StoreManagerInterface $storeManager
    ) {
        $this->areaList = $areaList;
        $this->appState = $appState;
        $this->translation = $translation;
        $this->localeResolver = $localeResolver;
        $this->storeManager = $storeManager;
    }

    public function beforeDispatch(GraphQl $subject, RequestInterface $request)
    {
        $area = $this->areaList->getArea($this->appState->getAreaCode());
        $storeIdOrCode = $request->getHeader('store') ?: 0;
        $locale = $this->storeManager->getStore($storeIdOrCode)->getConfig('general/locale/code');
        $this->localeResolver->setLocale($locale);
        $this->translation->setLocale($locale);
        $area->load(Area::PART_TRANSLATE);
    }
}
````
Working version of the plugin at https://stackoverflow.com/questions/61770306/while-working-with-the-magento-2-graphql-it-seems-that-the-string-translation-do

**Comment by rikwillems** [comment]
@Hexmage when I patch the GraphQL controller the translation works at store level too. In that case there is no need to determine the correct language.

**Comment by Hexmage** [comment]
@rikwillems I determine the correct language because it can be different for each storeview. 

The original fix only looked at the locale set at the highest level. So if you had multiple storeviews with different locales it didn't work.

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko seems like quite an important issue for single-page applications, like PWA, or by using GraphQL on the frontend and showing exceptions to users.
Let's set priority to p2 or even p1.

**Comment by shikhamis11** [comment]
@ihor-sviziev I agree. It's an quite important bug, since multi store and multi language features are already there at pwa studio with the release of 2.4.2. This should be addressed soon.

**Comment by gabrieldagama** [comment]
Error messages may be changed to error codes, and PWA and any other application consuming the GraphQL API should perform the translation on the frontend application, similar issue with https://github.com/magento/magento2/pull/27600

Cc. @cpartica

**Comment by Hexmage** [comment]
@gabrieldagama 
This feels like a waste of having the entire translation functionality in Magento. Adding Error Codes is fine because you might want to do something different based on the error code. But seeing as all other endpoints (soap, rest, the html frontend) do translate their output based on the store scope it would be weird that only graphql doesn't do this. 

And by putting the burden of translations on the frontend application, you'll increase it's size which you are trying to prevent especially if it will be running client side.

**Comment by rikwillems** [comment]
In my case I'm reading the cart/quote items that have custom made options. The labels of these options were not translated which doesn't make any sense, also not regarding PWA. My fix is:
```
Load the translations when the GraphQL controller is dispatched.
===================================================================
--- Controller/GraphQl.php
+++ Controller/GraphQl.php
@@ -7,6 +7,7 @@

 namespace Magento\GraphQl\Controller;

+use Magento\Framework\App\Area;
 use Magento\Framework\App\FrontControllerInterface;
 use Magento\Framework\App\Request\Http;
 use Magento\Framework\App\RequestInterface;
@@ -89,6 +90,9 @@
      */
     private $contextFactory;

+    /** @var \Magento\Framework\App\State $appState */
+    private $appState;
+
     /**
      * @param Response $response
      * @param SchemaGeneratorInterface $schemaGenerator
@@ -114,7 +118,8 @@
         QueryFields $queryFields,
         JsonFactory $jsonFactory = null,
         HttpResponse $httpResponse = null,
-        ContextFactoryInterface $contextFactory = null
+        ContextFactoryInterface $contextFactory = null,
+        \Magento\Framework\App\AreaList $areaList
     ) {
         $this->response = $response;
         $this->schemaGenerator = $schemaGenerator;
@@ -127,6 +132,7 @@
         $this->jsonFactory = $jsonFactory ?: ObjectManager::getInstance()->get(JsonFactory::class);
         $this->httpResponse = $httpResponse ?: ObjectManager::getInstance()->get(HttpResponse::class);
         $this->contextFactory = $contextFactory ?: ObjectManager::getInstance()->get(ContextFactoryInterface::class);
+        $this->areaList = $areaList;
     }

     /**
@@ -138,6 +144,8 @@
      */
     public function dispatch(RequestInterface $request) : ResponseInterface
     {
+        $this->areaList->getArea(Area::AREA_GRAPHQL)->load(Area::PART_TRANSLATE);
+
         $statusCode = 200;
         $jsonResult = $this->jsonFactory->create();
         try {

```

**Comment by cpartica** [comment]
> Error messages may be changed to error codes, and PWA and any other application consuming the GraphQL API should perform the translation on the frontend application, similar issue with #27600
> 
> Cc. @cpartica

**Comment by cpartica** [comment]
I think we can scope this for 2.4.3. 
We only have to move that scope area code in dispatch and not a plugin 
https://github.com/magento/magento2/issues/31351#issuecomment-792933568

**Comment by rikwillems** [comment]
@cpartica do you want me to provide a PR or will you take this on?

**Comment by cpartica** [comment]
you can take this if you don't mind

**Comment by denis-zyk** [comment]
Just to double check with you guys - the fix for GraphQL translations hasn't been integrated yet to any of Magento versions, correct? If so, then we'll stick with patching approach using the proposed code changes from @rikwillems comment.

**Comment by cpartica** [comment]
> Error messages may be changed to error codes, and PWA and any other application consuming the GraphQL API should perform the translation on the frontend application, similar issue with #27600
> 
> Cc. @cpartica

It is somehow similar but not the same.
The #27600 purpose was to add query in GQL so you could translate a phrase.
This one is different because the phrases we return are not properly translated.

It is true that we want translations on the frontend application, but that's done through error codes. Until we reach that phase, and we're far from it graphql schema wise, we need these phrases to be localized and translated

**Comment by ilnytskyi** [comment]
Why not just bootstrap correct store from map by header and init correct translation? 
nginx example ?
```
 map $http_store $MAGE_RUN_CODE {
        default "default";
        my_store_en "my_store_en";
      ... and so on
    }

```

**Comment by Hexmage** [comment]
@ilnytskyi The graphql endpoints dont initiate the translation module currently. So nothing is translated even if you set storecodes.

**Comment by slackerzz** [comment]
Is this fixed? In with magento version?

**Comment by cpartica** [comment]
2.4.4 - you just have to wait for it
Back in December we diverged branches for 2.4.4 and 2.4-develop and for ~ 3 months this process is invisible to the main branch
You will see the PR automerged when 2.4.4 is released

**Comment by engcom-November** [comment]
Hi, 
This issue got fixed in the scope of the internal Jira ticket AC-1946 by the internal team 
Related commits: https://github.com/magento/magento2/search?q=AC-1946&type=commits
Based on Jira, target version is 2.4.4
Thank you.

**Comment by zakdma** [comment]
This issue is still present for 2.4.7. I see changes but they does not work

**Comment by Beraa995** [comment]
> This issue is still present for 2.4.7. I see changes but they does not work

Just tested 2.4.7 and works fine. Make sure you don't keep translations inside theme.
