### ISSUE TITLE
Error when add product to cart with attachment

### ISSUE THREAD

**Issue by vincent2090311** [magento/magento2#32121]
### Preconditions (*)

1. Magento 2.4.2
2.Nginx 1.19
3.MariaDB 10.4

### Steps to reproduce (*)

1.Create simple product with custom option file (create 2 or more file custom options)
2.Go to product page, add product to cart with file attachment
3.Can not add product to cart because error Call to undefined method Magento\Catalog\Model\Product\Option\Type\File\ValidatorFile::setIsValid() in /vendor/magento/module-catalog/Model/Product/Type/AbstractType.php:521

### Expected result (*)

1. Can add product to cart without any issue
2.

### Actual result (*)

1. Got error when try to add product to cart with attachment
2.The problem: /vendor/magento/module-catalog/Model/Product/Type/AbstractType.php:521 call $queueOptions['option']->setIsValid(false); but vendor/magento/module-catalog/Model/Product/Option/Type/File/ValidatorFile.php:193 defined 'option' => $this, but this class doesn't have function setIsValid

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by redati** [comment]
I also have the problem

**Comment by redati** [comment]
I also have the problem

**Comment by redati** [comment]
@magento give me 2.4-develop instance

**Comment by redati** [comment]
Product successfully added to cart with attachment. Is this instance really the same as 2.4.2?

https://6c3bfcbc397191d071c41ec3e859bd68-2-4-develop.instances.magento-community.engineering/product-with-attachment.html

**Comment by redati** [comment]
@magento give me 2.4.2 instance

**Comment by redati** [comment]
Bug confirmed in 2.4.2 could not add item to cart

https://6c3bfcbc397191d071c41ec3e859bd68-2-4-2.instances.magento-community.engineering/product-with-attachment.html

**Comment by redati** [comment]
in if (empty($src) || empty($dst) || !$isUploaded) {


remove  || !$isUploaded and upload work.

$isUploaded it is an array and has the correct value.

**Comment by redati** [comment]
the error only appears if there are two or more attachments in the product.

!$isUploaded return true.

**Comment by engcom-Alfa** [comment]
Hi @vincent2090311. Thank you for your report!
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop. Looks like the problem has already been fixed by the commit - 9ce80c9914b740d30aef5cef7bbca8febe64a0c5

**Actual Result:** :heavy_check_mark: Can add product to cart without any issue

![Peek 2021-02-12 10-00](https://user-images.githubusercontent.com/51679138/107743202-222e4600-6d19-11eb-9373-d5260ca49ead.gif)

So, we have to close it. 
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Comment by redati** [comment]
This committee is not included in release 2.4.2

**Comment by reense** [comment]
@redati have you managed to fixed the issue? We're still having this problem on 2.4.2.

**Comment by adamstapley** [comment]
Has anybody got a fix for this? We've upgraded to 2.4.2 from 2.3.2 and have this issue. We have Weltpixel Pearl theme installed along with Mageplaza smtp and one step checkout. If anybody else with the issue can confirm if they have these extensions that would help.

**Comment by hostep** [comment]
@adamstapley: look [a bit above](https://github.com/magento/magento2/issues/32121#issuecomment-778042202), the following commit should fix it: https://github.com/magento/magento2/commit/9ce80c9914b740d30aef5cef7bbca8febe64a0c5
You can try [to turn that commit into a patch](https://support.magento.com/hc/en-us/articles/360005484154) and see if that fixes it in your case.

**Comment by sathyaraj819** [comment]
@adamstapley the above commit [9ce809](https://github.com/magento/magento2/commit/9ce80c9914b740d30aef5cef7bbca8febe64a0c5) fixed the issue in my environment.
