### ISSUE TITLE
2.0.1 CSV Export hangs until timeout

### ISSUE THREAD

**Issue by robfico** [magento/magento2#3217]
One of our clients has a 2.0.1 store that has 8,585 products in it (all imported through CSV imports). Everything looks fine with the data, no errors, nothing in debug. When we go to export the products, the pages hangs, and CPU usage is pegged. MySQL queries stop after one minute, but CPU runs until timeout is reached (we upped timeout to one hour and still times out). Once timeout is reached, export file appears in /var in its entirety.

It appears the export does initially complete in a minute, but the file does not get generated until the timeout occurs. Up until the timeout, CPU is pegged. Even if we exclude all fields but SKU and name, same behavior. Nothing in system.log or debug.log. Looks like a bug causing an infinite loop somehow, but I don't see what exactly.

**Comment by robfico** [comment]
An strace output of the php process stops with the following last few lines and then hangs until timeout:

```
sendto(5, "\270\1\0\0\3SELECT `def`.*, IF(store.us"..., 444, MSG_DONTWAIT, NULL, 0) = 444
sendto(5, "(\2\0\0\3SELECT `main_table`.*, `tdv"..., 556, MSG_DONTWAIT, NULL, 0) = 556
sendto(5, "h\4\0\0\3SELECT `entity`.`sku`, `sup"..., 1132, MSG_DONTWAIT, NULL, 0) = 1132
sendto(5, "\204\0\0\0\3SELECT `main_table`.* FROM "..., 136, MSG_DONTWAIT, NULL, 0) = 136
sendto(5, "\20\2\0\0\3SELECT `e`.*, `link_table`."..., 532, MSG_DONTWAIT, NULL, 0) = 532
sendto(5, "\233\v\0\0\3SELECT `t_d`.`entity_id`, `"..., 2975, MSG_DONTWAIT, NULL, 0) = 2975
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\343\2\0\0\3SELECT `main`.`value_id`, `"..., 743, MSG_DONTWAIT, NULL, 0) = 743
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\270\1\0\0\3SELECT `def`.*, IF(store.us"..., 444, MSG_DONTWAIT, NULL, 0) = 444
sendto(5, "(\2\0\0\3SELECT `main_table`.*, `tdv"..., 556, MSG_DONTWAIT, NULL, 0) = 556
sendto(5, "h\4\0\0\3SELECT `entity`.`sku`, `sup"..., 1132, MSG_DONTWAIT, NULL, 0) = 1132
sendto(5, "\204\0\0\0\3SELECT `main_table`.* FROM "..., 136, MSG_DONTWAIT, NULL, 0) = 136
sendto(5, "\20\2\0\0\3SELECT `e`.*, `link_table`."..., 532, MSG_DONTWAIT, NULL, 0) = 532
sendto(5, "s\v\0\0\3SELECT `t_d`.`entity_id`, `"..., 2935, MSG_DONTWAIT, NULL, 0) = 2935
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\343\2\0\0\3SELECT `main`.`value_id`, `"..., 743, MSG_DONTWAIT, NULL, 0) = 743
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\270\1\0\0\3SELECT `def`.*, IF(store.us"..., 444, MSG_DONTWAIT, NULL, 0) = 444
sendto(5, "!\2\0\0\3SELECT `main_table`.*, `tdv"..., 549, MSG_DONTWAIT, NULL, 0) = 549
sendto(5, "h\4\0\0\3SELECT `entity`.`sku`, `sup"..., 1132, MSG_DONTWAIT, NULL, 0) = 1132
sendto(5, "\204\0\0\0\3SELECT `main_table`.* FROM "..., 136, MSG_DONTWAIT, NULL, 0) = 136
sendto(5, "\20\2\0\0\3SELECT `e`.*, `link_table`."..., 532, MSG_DONTWAIT, NULL, 0) = 532
sendto(5, "\233\v\0\0\3SELECT `t_d`.`entity_id`, `"..., 2975, MSG_DONTWAIT, NULL, 0) = 2975
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\343\2\0\0\3SELECT `main`.`value_id`, `"..., 743, MSG_DONTWAIT, NULL, 0) = 743
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\270\1\0\0\3SELECT `def`.*, IF(store.us"..., 444, MSG_DONTWAIT, NULL, 0) = 444
sendto(5, "(\2\0\0\3SELECT `main_table`.*, `tdv"..., 556, MSG_DONTWAIT, NULL, 0) = 556
sendto(5, "h\4\0\0\3SELECT `entity`.`sku`, `sup"..., 1132, MSG_DONTWAIT, NULL, 0) = 1132
sendto(5, "\204\0\0\0\3SELECT `main_table`.* FROM "..., 136, MSG_DONTWAIT, NULL, 0) = 136
sendto(5, "\20\2\0\0\3SELECT `e`.*, `link_table`."..., 532, MSG_DONTWAIT, NULL, 0) = 532
sendto(5, "\233\v\0\0\3SELECT `t_d`.`entity_id`, `"..., 2975, MSG_DONTWAIT, NULL, 0) = 2975
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\343\2\0\0\3SELECT `main`.`value_id`, `"..., 743, MSG_DONTWAIT, NULL, 0) = 743
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\270\1\0\0\3SELECT `def`.*, IF(store.us"..., 444, MSG_DONTWAIT, NULL, 0) = 444
sendto(5, "(\2\0\0\3SELECT `main_table`.*, `tdv"..., 556, MSG_DONTWAIT, NULL, 0) = 556
sendto(5, "h\4\0\0\3SELECT `entity`.`sku`, `sup"..., 1132, MSG_DONTWAIT, NULL, 0) = 1132
sendto(5, "\204\0\0\0\3SELECT `main_table`.* FROM "..., 136, MSG_DONTWAIT, NULL, 0) = 136
sendto(5, "\20\2\0\0\3SELECT `e`.*, `link_table`."..., 532, MSG_DONTWAIT, NULL, 0) = 532
sendto(5, "\233\v\0\0\3SELECT `t_d`.`entity_id`, `"..., 2975, MSG_DONTWAIT, NULL, 0) = 2975
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\343\2\0\0\3SELECT `main`.`value_id`, `"..., 743, MSG_DONTWAIT, NULL, 0) = 743
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\314\3\0\0\3SELECT `main`.`value_id`, `"..., 976, MSG_DONTWAIT, NULL, 0) = 976
sendto(5, "\270\1\0\0\3SELECT `def`.*, IF(store.us"..., 444, MSG_DONTWAIT, NULL, 0) = 444
sendto(5, "(\2\0\0\3SELECT `main_table`.*, `tdv"..., 556, MSG_DONTWAIT, NULL, 0) = 556
sendto(5, "h\4\0\0\3SELECT `entity`.`sku`, `sup"..., 1132, MSG_DONTWAIT, NULL, 0) = 1132
open("/home/xxx/www/vendor/magento/module-grouped-import-export/Model/Export/RowCustomizer.php", O_RDONLY) = 8
open("/home/xxx/www/vendor/magento/module-grouped-import-export/Model/Export/RowCustomizer.php", O_RDONLY) = 8
```

**Comment by robfico** [comment]
Some additional information if it helps. The store has only simple and configurable products. It did have grouped products in the past, but they were all deleted. Maybe this is what triggers the bug?

**Comment by kandy** [comment]
Thanks for reporting. 
We have created ticket MAGETWO-48721 to for timeout issue and MAGETWO-48722 for performance improvment

**Comment by KrystynaKabannyk** [comment]
Hello @robfico, the reported issues have been fixed in 2.0.5 patch release that's why I'm closing the issue. Thanks for your help! If you have additional questions or information feel free to create another issue!

**Comment by rqsakai** [comment]
Same issue on 2.0.7 with a 25k catalog of all simple products

**Comment by anupwankhede** [comment]
HI there @magento-engcom-team  , may I know in which versions this issue is fixed?
and if you can provide link to the PR of patch to let us accomodate this change in versions we are using if not fixed in these versions.

Thanks in advance :)
