### ISSUE TITLE
error resetting sample data using sampledata:reset

### ISSUE THREAD

**Issue by jason-vivid** [magento/magento2#3229]
This is pretty straightforward.  I ran the command below and it produced the following errors.

The test site was installed using the composer create-project command and the sample data using magento sampledata:deploy.

`magento sampledata:reset`

Result:

```
  [Zend_Db_Statement_Exception]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'module' cannot be null, query was: INSERT INTO `setup_module` (`module`, `data_version`) VALUES (?, ?)

  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'module' cannot be null

sampledata:reset
```

**Comment by magedmik** [comment]
The same

**Comment by wrurik** [comment]
Same here

**Comment by vrann** [comment]
@jason-vivid Thanks for reporting! seems like a bug in sample data.

**Comment by katmoon** [comment]
The issue has been reported as `MAGETWO-46697` and it is fixed now. See 1919e7ed823c24f1cfac

Thank you!

**Comment by hamdrew** [comment]
Has this made it into a release? Still seeing the behavior in 2.0.2

**Comment by davidalger** [comment]
@hamdrew I don't believe so, as the referenced commit shows as only in develop.

**Comment by hamdrew** [comment]
Is it marked for a future release?
