### ISSUE TITLE
Shipping method csv import issue

### ISSUE THREAD

**Issue by mattyj714** [magento/magento2#3256]
When trying to upload a CSV file into shipping -> Table Rates the temp directory is incorrect and different to what is in the loaded php.ini file.

The file*\* "/tmp/home/username/tmp/php2VLzjb"*\* doesn't exist

**php.ini file lists the tmp upload directory as "home/username/tmp/"**
As you can notice, magento seems to be adding an extra "tmp" to the front of the directory. I have looked around to see if it is in a setting or conf file somewhere with no luck.

**Comment by mattyj714** [comment]
I fixed this issue and it was a php.ini issue.
For some reason when magento uploaded the CSV file it was joining both
sys_temp_dir and upload_tmp_dir 
together.
By setting the system temp dir to the same as upload_tmp_dir it then uploaded.
This issue only happened on my WebMin/VirtualMin system and not a plain apache setup.

**Comment by soydemadrid** [comment]
Hi I also have this issue with Webmin/Virtual min.

Tried setting the upload temp folder in PHP > Directory Settings to /tmp but I still get the error even after restarting apache.

I wonder if you could please let me know where you changed this setting?

**Comment by soydemadrid** [comment]
Hi I have now also fixed this from within Webmin/Virtualmin.

For anyone else needing to do this just change the Virtual Server's own php.ini file found in /home/username/etc/php.ini - then comment out (put a semi-colon in front of) ; upload_tmp_dir = /home/username/tmp

Restart apache and everything should work correctly.

**Comment by thedoofus** [comment]
Going on what @mattyj714 said, if magento is joining both sys_temp_dir and upload_temp_dir together. Doesn't that make this a magento issue and not a php.ini issue?

What's the reason for magento doing this?
