### ISSUE TITLE
Varnish VCL prevent Link headers (for HTTP2 preload / server push)

### ISSUE THREAD

**Issue by samy-m-dev** [magento/magento2#32836]
### Preconditions
Magento 2 (any versions) and Varnish enabled with default VCL

### Steps to reproduce
1. Default install of Magento (any versions) 
2. Configure and enable Varnish with default VCL
3. Customize header to send HTTP2 preload/server push link like:

`Link: <https://magento2-domain.org/static/_cache/merged/89e1e4264a5da4c028da48f231925246.js>; rel=preload; `

### Expected result

Link headers sent by the application should be in the response.

### Actual result

Link headers are stripped due to `unset resp.http.Link;` in Varnish configuration file.

**Comment by webtekindo** [comment]
Our hosting cloud provider is using the default varnish VCL of Magento and they don't want to make adjustments to the VCL unless this is adjusted by Magento. 

So it will be nice if this fix is implement.

Thank you.

**Comment by engcom-Echo** [comment]
Hi @webtekindo ,

Can you please provide the varnish version that you are using , also please provide the response screenshot so that we can understand the issue.

Thanks

**Comment by webtekindo** [comment]
The version of varnish is irrelevant, all the default magento VCL contains this line:

`unset resp.http.Link;`

You can test it by installing a module like:

https://github.com/yireo/Yireo_LinkPreload

See how the header is set:

https://github.com/yireo/Yireo_LinkPreload/blob/master/Plugin/ResponsePlugin.php#L145

example: Link: <link_to_magento_asset.js>; rel=preload;

On the frontend If you inspect the response header you will see that it was removed due to the VCL.

If there's no specific reason to `unset resp.http.Link;` then I will recommend to remove it, allowing more flexibility to developer to use HTTP2 preload if they want to.

**Comment by engcom-Hotel** [comment]
Hello @webtekindo,

We have tried to reproduce the issue in Magento 2.4-develop branch, but are unable to do so. We have followed below steps in order to reproduce the issue:
1. Enable varnish from the admin panel. We have Varnish 6 installed.
2. Follow the steps documented in [Link](https://devdocs.magento.com/guides/v2.4/config-guide/varnish/config-varnish-magento.html).
3. Remain uncomment the line `unset resp.http.Link` in default.vcl file.
4. Verify that if varnish is enabled successfully.
5. Check the `Link` attribute in the response header. The `Link` header is found. Please find the screenshot below for reference:

<img width="1440" alt="Screenshot 2021-07-15 at 3 07 24 PM" src="https://user-images.githubusercontent.com/51681618/125767561-1720fe98-726a-4f93-a027-6613f673e5f8.png">

Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @webtekindo,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by webtekindo** [comment]
@engcom-Hotel I tried again on last version and same result for me.

That like `unset resp.http.Link` is meant to remove Link from header, so I don't know why in your case you still see the Link header.

In our case we have Nginx SSL > Varnish > Nginx so it make sense that `unset resp.http.Link` is removing the Link Header that was set from Nginx.

What is your stack?
