### ISSUE TITLE
Graphql, As a logged-in user setShippingAddressesOnCart mutation returns error on a magento backend with Guest Checkout disabled

### ISSUE THREAD

**Issue by eperezbanana** [magento/magento2#33046]
While using the Graphql api, as a logged-in user the setShippingAddressesOnCart mutation returns error on a magento 2.4.2 backend with Guest Checkout disabled

### Preconditions (*)

1. Magento version 2.4.2
2. Set _Allow Guest Checkout_ to **No** on the admin page: **Stores -> Configuration -> Sales -> Checkout -> Checkout options**

### Steps to reproduce (*)

1. Create User
2. Log in
3. Create cart
4. Create a shipping address while logged in (ie: having the Authorization Bearer token on the headers for the graphql requests)
5. Try to call the **setShippingAddressesOnCart** graphql mutation with the created cart id and the created shipping address id
like so: 
![image](https://user-images.githubusercontent.com/68245962/118869425-9fca9a80-b8a2-11eb-9ec2-b960f788aa5e.png)

### Expected result (*)

1. Expect the operation to be successful and return the graphql query results that we asked, for example: 
![image](https://user-images.githubusercontent.com/68245962/118868943-07ccb100-b8a2-11eb-8163-ab667185f097.png)

### Actual result (*)

1. It returns "Guest checkout is not allowed. Register a customer account or login with existing one." "graphql-authorization" authorization error: 
![image](https://user-images.githubusercontent.com/68245962/118869194-55491e00-b8a2-11eb-99cc-45a0d695bce3.png)
2. This error would be valid if i wasn't logged-in, but in this case i am, therefore its not a valid error/its a bug
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment]
@magento give me 2.4.2 instance

**Comment by shikhamis11** [comment]
Hi @eperezbanana 
Thank you for reporting this issue. 
I am able to reproduce this issue on 2.4.2 but not in the 2.4-develop instance. so it seems the issue is fixed in the 2.4-develop latest branch. 
Can you also test on the 2.4-develop instance? 
also I tried to find the patch for the fix. I am not sure but you can check commit [this](https://github.com/magento/magento2/commit/c26432f7582ad61542ba8d4b5895ca976cc95126#diff-e82ad414cfeacaa6861e011d34bd5c8eedf2f75d480e3f8be41ea23b23da227b)

**Comment by Jupagar77** [comment]
Hi @shikhamis11 , I am part of @eperezbanana team, yesterday we upgraded our magento version to 2.4.2-p1 and we are still seeing the issue, the commit you are pointing is from 26 days ago and that magento version was released 13 days ago so it seems that is not the solution :(

**Comment by fooman** [comment]
@Jupagar77 The commit is very likely not part of 2.4.2-p1 see https://github.com/magento/magento2/blob/2.4.2-p1/app/code/Magento/QuoteGraphQl/Model/Cart/MergeCarts/CartQuantityValidator.php

The cut off date for a release is usually quite some time prior to the release date.

**Comment by engcom-Lima** [comment]
Hi @eperezbanana,

We tried to reproduce this on 2.4-develop version but everything worked as expected.

Here is what we did on 2.4-develop instance:
1. We created user and logged in using Graphql.
2. We created cart and created shipping address as suggested in 'Steps to reproduce’.
3. Tried to call setShippingAddressesOnCart graphql mutation but instead of errors shown, we got expected result.

So, in order to check if this issue still exists, can you please explain if you did anything differently or if you can test same on 2.4-develop instance and let us know if this issue still persists?

**Comment by engcom-Lima** [comment]
Closing this issue as there has been no update from the reporter on the same.

**Comment by iba-1** [comment]
I'm encountering the same error on a clean instance in 2.4.1, could it be possible? Maybe this issue should be reopened?

While I was logged in:
```
curl 'https://staging.jumboffice.it/graphql' \
  -H 'authority: staging.jumboffice.it' \
  -H 'sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"' \
  -H 'dnt: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'authorization: Bearer bllxqfdmlp8im16yxb5a88yhcg8onfxu' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'origin: http://localhost:3000' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:3000/' \
  -H 'accept-language: en-GB,en;q=0.9,it-IT;q=0.8,it;q=0.7,en-US;q=0.6' \
  --data-raw $'{"operationName":"setBillingAddressOnCart","variables":{"cart_id":"8YT7HN7NAuIZP1MEhHYVJfJ2WG7MDrSt","firstname":"test","lastname":"sadfsdf","company":"asdasd","postcode":"asda","country_code":"IT","region_code":0,"city":"asda","telephone":"asd","street":["asda","",""],"same_as_shipping":true},"query":"mutation setBillingAddressOnCart($cart_id: String\u0021, $firstname: String\u0021, $lastname: String\u0021, $company: String, $city: String\u0021, $street: [String]\u0021, $postcode: String\u0021, $telephone: String\u0021, $country_code: String\u0021, $region_code: Int, $same_as_shipping: Boolean\u0021) {\\n  setBillingAddressOnCart(\\n    input: {cart_id: $cart_id, billing_address: {address: {firstname: $firstname, lastname: $lastname, company: $company, city: $city, street: $street, postcode: $postcode, telephone: $telephone, country_code: $country_code, region_id: $region_code}, same_as_shipping: $same_as_shipping}}\\n  ) {\\n    cart {\\n      billing_address {\\n        firstname\\n        lastname\\n        company\\n        street\\n        city\\n        region {\\n          code\\n          label\\n          __typename\\n        }\\n        postcode\\n        telephone\\n        country {\\n          code\\n          label\\n          __typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n"}' \
  --compressed
```

Got this response: 
```json
{"errors":[{"message":"Guest checkout is not allowed. Register a customer account or login with existing one.","extensions":{"category":"graphql-authorization"},"locations":[{"line":2,"column":3}],"path":["setBillingAddressOnCart"]}],"data":{"setBillingAddressOnCart":null}}
```
