### ISSUE TITLE
Footer Miscellaneous HTML Not working

### ISSUE THREAD

**Issue by atishgoswami** [magento/magento2#3333]
I'm trying add a tracking code to a Magento2 using admin panel from

General -> Design -> Footer -> Miscellaneous HTML.

The data is getting saved properly, but it does not get displayed on the HTML (just before body closing tag).

I did a code base search for the config setting `absolute_footer` but could not find any reference of the system setting in the code.

**Comment by aoldoni** [comment]
Can confirm this bug in "2.0.0".

**Comment by atishgoswami** [comment]
I experienced this bug in "2.0.2" CE

**Comment by stefandoorn** [comment]
Having the same issue in here. Saving goes perfect, but it doesn't get fetched and included in the HTML.

**Comment by stefandoorn** [comment]
I've created a PR to insert this functionality: #3579.

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-51905

**Comment by stefandoorn** [comment]
@sevos1984 Connected PR's feedback has been completed.

**Comment by slavvka** [comment]
@atishgoswami, the fix has been merged. See 5e9691d, 0b47c71 and d46fb12. Thank you for your contribution to Magento 2!

**Comment by jehzlau** [comment]
Currently using Magento 2.1.2, but still bug isn't fixed yet.

**Comment by slavvka** [comment]
@jehzlau the issue was fixed in the mainline (2.2-dev). I cannot predict when or whether it is going to be backported. If you need the fix please use sultion in 5e9691d, 0b47c71 and d46fb12.

**Comment by jehzlau** [comment]
Oic. I'll just wait for the 2.2 release. :D
Sent from my Oculus Rift® VR e-mail app

-----Original Message-----

**Comment by boris-nanni** [comment]
Hello guys and girls! You must be save the config for each store view, this solution work for me.

**Comment by kuvar0158** [comment]
my question is that how i am using miscellaneous html in footer

**Comment by LiamKarlMitchell** [comment]
Still a problem in 2.3.2

**Comment by tarikuli** [comment]
Still a problem in 2.4.6
