### ISSUE TITLE
Multiple store newsletter subscription bug in the customers search API

### ISSUE THREAD

**Issue by stephan-cream** [magento/magento2#33565]
### Preconditions (*)
1. Magento 2.4.2
2. PHP 7.3 or higher
3. Stores > Settings > Configuration > Customers > Customer Configuration -> Account Sharing Options:
Share Customer Accounts = Global
4. Multiple storeviews
5. One customer account

### Steps to reproduce (*)
1. Have the above conditions.
2. Go to the first store.
3. Log in with the customer account.
4. Sign up for the newsletter subscription.
5. Go to the second store.
6. Log in with the same customer account.
7. Sign up for the newsletter subscription.
8. Make an API call to the following REST endpoint:
`https://{your website url}/rest/V1/customers/search?searchCriteria[filter_groups][0][filters][0][field]=entity_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]={your customer id}`
Replace bracketed text with the corresponding info.

### Expected result (*)
1. Customer is properly retrieved.
2. Both subscriptions are shown independently within the extension attributes.
3. No error occurs.

### Actual result (*)
1. Error is thrown in the system.log: `main.CRITICAL: Report ID: webapi-xxxxxx; Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "{customer id}" already exists. {"exception":"[object] (Exception(code: 0): Report ID: webapi-xxxxxx; Message: Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"{customer id}\" already exists. at /vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"{customer id}\" already exists. at /vendor/magento/framework/Data/Collection.php:408)"} []`
2. The following error is shown in the API response: `{  "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-xxxxxx" }`

---
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by stephan-cream** [comment]
As a sidenote, this also occurs if you subscribe a customer to the newsletter in the backoffice, after which the customer also subscribes him-/herself to the newsletter on the frontend.

**Comment by engcom-Delta** [comment]
@magento give me magento 2.4.2

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @stephan-cream ,
We tried to reproduce the issue in Magento 2.4 Develop. unfortunately it is not reproducible , it works as expected.
Kindly fine the attached response.

{
    "items": [
        {
            "id": 2,
            "group_id": 1,
            "default_billing": "2",
            "default_shipping": "2",
            "created_at": "2021-08-25 01:34:04",
            "updated_at": "2021-08-25 01:36:36",
            "created_in": "Default Store View",
            "email": "tester@gmail.com",
            "firstname": "tester",
            "lastname": "test",
            "store_id": 1,
            "website_id": 1,
            "addresses": [
                {
                    "id": 2,
                    "customer_id": 2,
                    "region": {
                        "region_code": "MS",
                        "region": "Mississippi",
                        "region_id": 35
                    },
                    "region_id": 35,
                    "country_id": "US",
                    "street": [
                        "7123 19 Mile Rd"
                    ],
                    "telephone": "(257) 563-7401",
                    "postcode": "49305",
                    "city": "Barryton",
                    "firstname": "tester",
                    "lastname": "test",
                    "default_shipping": true,
                    "default_billing": true
                },
                {
                    "id": 3,
                    "customer_id": 2,
                    "region": {
                        "region_code": "MI",
                        "region": "Michigan",
                        "region_id": 33
                    },
                    "region_id": 33,
                    "country_id": "US",
                    "street": [
                        "712 Saint Charles Ct"
                    ],
                    "telephone": "(616) 466-6866",
                    "postcode": "48067",
                    "city": "Royal Oak Michigan(MI)",
                    "firstname": "tester",
                    "lastname": "test"
                },
                {
                    "id": 4,
                    "customer_id": 2,
                    "region": {
                        "region_code": "MI",
                        "region": "Michigan",
                        "region_id": 33
                    },
                    "region_id": 33,
                    "country_id": "US",
                    "street": [
                        "7123 19 Mile Rd"
                    ],
                    "telephone": "(989) 382-7518",
                    "postcode": "49305",
                    "city": "Barryton",
                    "firstname": "tester",
                    "lastname": "test"
                }
            ],
            "disable_auto_group_change": 0,
            "extension_attributes": {
                "is_subscribed": true
            }
        }
    ],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "entity_id",
                        "value": "2",
                        "condition_type": "eq"
                    }
                ]
            }
        ],
        "page_size": 20
    },
    "total_count": 1
}

![postman_response](https://user-images.githubusercontent.com/51681379/131853165-95f2ade0-69e2-4383-ac9d-e7e150a58a6f.JPG)

**Comment by stephan-cream** [comment]
@engcom-Delta See the above.

**Comment by jsamhall** [comment]
Chiming in here to share that I too am experiencing this same bug.

In our case, the REST request is:
`https://www.storeurl.com/index.php/rest/V1/customers/search?searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=2021-10-09+06%3A55%3A20&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gt&searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=DESC&searchCriteria%5BcurrentPage%5D=24&searchCriteria%5BpageSize%5D=50`

The only search criteria here is finding accounts updated more recently than the given date, along with some paging.

To be clear:
`newsletter_subscriber` contains multiple occurrences of the same customer_id which share the same subscriber_email but are associated to different store_ids

The `newsletter_subscriber` table holds data like this. I have censored the user's email; the two rows have the same email address.
![subscriber-bug](https://user-images.githubusercontent.com/13559547/141000818-3ff2522f-eb94-472a-85f6-418c4f08a11c.png)

The query that raised the Exception is this: 
```
SELECT `e`.*, `extension_attribute_is_subscribed`.`subscriber_status` AS `extension_attribute_is_subscribed_subscriber_status`, CONCAT(IF(e.prefix IS NOT NULL AND e.prefix != '', CONCAT(LTRIM(RTRIM(e.prefix)), ' '), ''), LTRIM(RTRIM(e.firstname)), ' ', IF(e.middlename IS NOT NULL AND e.middlename != '', CONCAT(LTRIM(RTRIM(e.middlename)), ' '), ''), LTRIM(RTRIM(e.lastname)), IF(e.suffix IS NOT NULL AND e.suffix != '', CONCAT(' ', LTRIM(RTRIM(e.suffix))), '')) AS `name`, `at_billing_postcode`.`postcode` AS `billing_postcode`, `at_billing_city`.`city` AS `billing_city`, `at_billing_telephone`.`telephone` AS `billing_telephone`, `at_billing_region`.`region` AS `billing_region`, `at_billing_country_id`.`country_id` AS `billing_country_id`, `at_billing_company`.`company` AS `billing_company` FROM `customer_entity` AS `e`
 LEFT JOIN `newsletter_subscriber` AS `extension_attribute_is_subscribed` ON e.entity_id = extension_attribute_is_subscribed.customer_id
 LEFT JOIN `customer_address_entity` AS `at_billing_postcode` ON (`at_billing_postcode`.`entity_id` = `e`.`default_billing`)
 LEFT JOIN `customer_address_entity` AS `at_billing_city` ON (`at_billing_city`.`entity_id` = `e`.`default_billing`)
 LEFT JOIN `customer_address_entity` AS `at_billing_telephone` ON (`at_billing_telephone`.`entity_id` = `e`.`default_billing`)
 LEFT JOIN `customer_address_entity` AS `at_billing_region` ON (`at_billing_region`.`entity_id` = `e`.`default_billing`)
 LEFT JOIN `customer_address_entity` AS `at_billing_country_id` ON (`at_billing_country_id`.`entity_id` = `e`.`default_billing`)
 LEFT JOIN `customer_address_entity` AS `at_billing_company` ON (`at_billing_company`.`entity_id` = `e`.`default_billing`) WHERE ((`e`.`updated_at` > '2021-10-09 06:55:20')) ORDER BY `e`.`updated_at` DESC
 LIMIT 50 OFFSET 1150
 ```
Simply removing the WHERE clause will yield the problematic results.

**Comment by engcom-Delta** [comment]
Hi @stephan-cream ,
We tried to reproduce it on Magento 2.4 Develop with latest branch, we could not find duplicate records for multiple store news letter subscriptions.
I have followed below steps:
1. Go to the first store.
2. Log in with the customer account.
3. Sign up for the newsletter subscription.
![store_india](https://user-images.githubusercontent.com/51681379/144827102-05103735-afa7-4574-8c20-44d0fb23e06d.JPG)
4.Go to the second store.
5. Log in with the same customer account.
6. Sign up for the newsletter subscription.

![store_com_subscribed](https://user-images.githubusercontent.com/51681379/144827165-d834a0b3-b370-47a7-aeef-770d5d1a6b1d.JPG)

in DB: 
![Uploading DB_Query_results.JPG…]()

**Comment by stephan-cream** [comment]
Note that your example only has the subscription for store 1 in your given example.
The issue describes a situation when there are 2 entries with the exact same email address and customer id but a different store id.

This no longer seems possible to occur naturally in 2.4.3 as it doesn't seem to add a new entry anymore if the account is set to global.
However the current situation is also not as desired.
In this case, the customer will only ever be subscribed to the first store it made the subscription to, never to any other stores, despite the account being 'global'.

Your current construction would either result in scenario A or B depending on the logic you implemented.

**Scenario A:**
- The subscription only counts towards the first storeview they subscribed to (but this is shown on every storeview as being subscribed, which is incorrect).
- The customer cannot subscribe to other newsletters from different storeviews and will only receive one storeview's newsletter.

**Scenario B:**
- The subscription always counts towards both storeviews (but the customer only intended to subscribe to one).
- The customer gets multiple newsletters, despite not having signed up for the other ones.

As you can see, the current construction is inadequate for any scenario.

**Comment by engcom-Delta** [comment]
Hi @stephan-cream ,
We tried the steps provided in the issue description , at this movement we could not get error that you got ,it works fine on Magento 2.4 Develop with latest branch. Here is video attached and screenshots attached.
Kindly have a look and confirm .
Before subscribe in DB:
------------------------
![before_subscriptionDB](https://user-images.githubusercontent.com/51681379/145374430-03a67e1d-1506-4b52-96e4-f0d1ea989352.JPG)

After store 2 subscribed:
---------------------------
![INdia_storeSubscription_store2](https://user-images.githubusercontent.com/51681379/145374615-f4d7c3b4-4224-4b67-a10e-62c93ff8b6dc.JPG)
in DB:
-------
![DB_after_subscription](https://user-images.githubusercontent.com/51681379/145374671-85e4a793-d9eb-4841-a3f0-3336481e3b30.JPG)
After store 1 subscribed:
--------------------------
![DB_after_subscription2](https://user-images.githubusercontent.com/51681379/145374869-c4af89a9-24b4-4225-a2bf-a8356abef822.JPG)

API response:
--------------
![API_response](https://user-images.githubusercontent.com/51681379/145375115-9a026715-ad24-4493-81df-c7545e9ec02b.JPG)

https://user-images.githubusercontent.com/51681379/145375159-ddce46b0-9aaa-4358-9e7e-54dc9d69e828.mp4

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by evs-xsarus** [comment]
How could this be closed? the issue still exists for instance when upgrading from 2.4.2 to a later version. The data with the problem is still there, thus breaking the API call. @engcom-Delta the logic where an existing record in the subscription table is updated, seems wrong. How can a customer subscribe to multiple store fronts this way?
