### ISSUE TITLE
Unable to place order after applying discount code in  review & payment checkout step and if this affects shipping method selected previously

### ISSUE THREAD

**Issue by emiliatereanu** [magento/magento2#33697]
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Enable free shipping delivery method with condition minimum order amount value 200 ( for example)
2. Create a cart price rule with voucher code that gives a fixed amount
3. Add product(s) to cart so that cart amount is greater or equal than 200
4. Proceed to checkout, fill address, then select the free shipping delivery method.
5. Proceed to payment step. Choose a payment method, Check/Money order for example
6. Apply discount code, making sure now the total amount is less than what free shipping requires.
7. Try to place order.
8. User gets an error "The shipping method is missing. Select the shipping method and try again." Message fades after a few seconds.

### Expected result (*)

1. User is redirected to previous Shipping step and is informed to select one of the available delivery methods.

### Actual result (*)

1. User is stuck in review & payment step and is displayed an error message, that fades after a few seconds: "The shipping method is missing. Select the shipping method and try again."
2. 
![actual_result_issue](https://user-images.githubusercontent.com/9749035/128475730-88a823cb-cdf8-4418-afbb-e3863a3862c8.png)

### Additional information
1. Mentioned in https://github.com/magento/magento2/issues/29938
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by emiliatereanu** [comment]
@magento give me 2.4-develop instance

**Comment by emiliatereanu** [comment]
I confirm this is reproducing on 2.4-develop
![issue_reproducing_develop](https://user-images.githubusercontent.com/9749035/128491106-67d9bcb7-2738-4c9f-9f6c-a0928809f08c.png)

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
This issue is reproducible on **2.4-develop** branch, with the given steps to reproduce.
Would like to highlight few points w.r.t issue
1. The Error message displayed to the user "The shipping method is missing. Select the shipping method and try again." , seems very confusing from user perspective, considering the fact that the user had already selected his/her shipping method on the previous(shipping) page.
2. In the scenario mentioned in the issue, the user has to be redirected back to the page where he/she can choose other shipping methods.
3. Also in the scenario mentioned in the issue if the user uses the back button from the browser and navigate back from the review & payments page to the shipping page, the free shipping method which the user had earlier selected is missing from the choices(as the coupon has been applied by now), without any message or indications to the user, which could be perplexing.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by rahimimo** [comment]
Hi, has there been any update on this?

**Comment by VivekShingala** [comment]
> Hi, has there been any update on this?

Yeah, waiting on this since long.

**Comment by Usik2203** [comment]
@magento I am working on this

**Comment by glo71317** [comment]
Since long this issue is open. So, Internal team is started working on this and will complete soon

**Comment by engcom-Hotel** [comment]
Hello @<reporter>,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-937 by the internal team
Related commits: https://github.com/magento/magento2/commit/fd7e45e945796afcb39ef96c57121f494d651754

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by mibbin** [comment]
The issue is still persist in the 2.4.6 also.

Just checked with 2.4.6
<img width="1289" alt="Screenshot 2023-03-17 at 10 52 58 AM" src="https://user-images.githubusercontent.com/22273037/225819638-f84692d8-8d24-4177-b706-c6748091c441.png">
