### ISSUE TITLE
Found SalesRule condition is ignoring the attribute scope ("Children only"/"Parent only")

### ISSUE THREAD

**Issue by leeroybrun** [magento/magento2#33736]
### Preconditions (*)

1. Magento 2.4.2
2. In our case the problem occurred with Amasty Shipping Restrictions module, which is using SalesRules.
3. The problem will occurs with every module using the sales rules.

### Steps to reproduce (*)

1. Define a rule using the "Found" condition and an attribute scope ("Children only"/"Parent only").
<img width="615" alt="Capture d’écran 2021-08-10 à 11 24 51" src="https://user-images.githubusercontent.com/1729528/128842944-4b93598d-2970-440c-9424-39288ef5065b.png">
2. In our case with Amasty Shipping Restrictions :
    - The parent product had the field "Livraison possible par poste" set to `false`
    - The child product had the attribute set to `true`
    - The condition was used to check if any product in the cart ("Children Only")  had the attribute to `false` and in that case it should disable a shipping method.

### Expected result (*)

1. The condition should return false, because it should check only the children product and not the parent.

### Actual result (*)

- The condition return true (because the parent's attribute was set to `false`), even though we had used the "Children Only" attribute
- In our case, the shipping method was disabled, when it should be enabled because it should check only the children products.

This is a big problem because all the sales rules using a "found" condition with an attribute scope ("Children Only"/"Parent Only") will not work as expected.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by leeroybrun** [comment]
For anyone interested, here is a patch you can apply while waiting for the pull request to be merged :

````
diff --git a/Model/Rule/Condition/Product/Combine.php b/Model/Rule/Condition/Product/Combine.php
index 35e7e6214461..eeefbb5c29de 100644
--- a/Model/Rule/Condition/Product/Combine.php
+++ b/Model/Rule/Condition/Product/Combine.php
@@ -143,7 +143,7 @@ private function validateEntity($cond, \Magento\Framework\Model\AbstractModel $e
      * @param \Magento\Framework\Model\AbstractModel $entity
      * @return \Magento\Framework\Model\AbstractModel[]
      */
-    private function retrieveValidateEntities($attributeScope, \Magento\Framework\Model\AbstractModel $entity)
+    protected function retrieveValidateEntities($attributeScope, \Magento\Framework\Model\AbstractModel $entity)
     {
         if ($attributeScope === 'parent') {
             $parentItem = $entity->getParentItem();
diff --git a/Model/Rule/Condition/Product/Found.php b/Model/Rule/Condition/Product/Found.php
index 9cb852292b1f..fabe8f18df49 100644
--- a/Model/Rule/Condition/Product/Found.php
+++ b/Model/Rule/Condition/Product/Found.php
@@ -65,10 +65,12 @@ public function validate(\Magento\Framework\Model\AbstractModel $model)
         foreach ($model->getAllItems() as $item) {
             $found = $all;
             foreach ($this->getConditions() as $cond) {
-                $validated = $cond->validate($item);
-                if ($all && !$validated || !$all && $validated) {
-                    $found = $validated;
-                    break;
+                foreach ($this->retrieveValidateEntities($cond->getAttributeScope(), $item) as $validateEntity) {
+                    $validated = $cond->validate($validateEntity);
+                    if ($all && !$validated || !$all && $validated) {
+                        $found = $validated;
+                        break;
+                    }
                 }
             }
             if ($found && $true || !$true && $found) {

```

Here is how to apply a patch : https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/composer.html

**Comment by engcom-Lima** [comment]
Hi @leeroybrun,

Thank you for reporting the issue.

I tried to reproduce this on 2.4-develop instance without Amasty Shipping Restrictions but the SalesRules are working as expected.

Here is what I tried on Magento 2.4-develop version:
1. Created a new Cart Price Rules with Found condition for attribute Size(Children Only) set to XS.
2. I tried to use the coupon for products with any other size which may be for Parent but the coupon always shows Invalid except for XS size which was accepting the coupon as intended.
3. I tried with multiple scenarios like this but all are working fine.

So we need some additional information in order to reproduce this:
1. Can you please check and verify if this issue is reproducible on Magento 2.4-develop instance ?
2. Please update if this issue is happening without Amasty Shipping Restrictions also ?

**Comment by engcom-Hotel** [comment]
Dear @leeroybrun,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by artttj** [comment]
The bug still persists.

The solution from @leeroybrun seems to be working.
