### ISSUE TITLE
Customer getStoreId is wrong when operating on customers in the admin panel

### ISSUE THREAD

**Issue by philcali** [magento/magento2#3376]
There's an adminhtml di.xml definition for loading Customer models using a "Backend" model:

```
<type name="Magento\Customer\Model\ResourceModel\Customer\Collection">
        <arguments>
            <argument name="modelName" xsi:type="string">Magento\Customer\Model\Backend\Customer</argument>
        </arguments>
</type>
```

The Backend model overwrites the `getStoreId` method, which essentially hides which store view the customer **actually** belongs to:

```
    /**
     * Get store id
     *
     * @return int
     */
    public function getStoreId()
    {
        if ($this->getWebsiteId() * 1) {
            return $this->_getWebsiteStoreId();
        }
        return parent::getStoreId();
    }
```

This was a source of frustration, because the resulting behavior is very much unexpected. I fail to see how this implicit behavior would ever be desired. Please consider removing this injection for the admin view.

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-49197

**Comment by magento-engcom-team** [comment]
@philcali, thank you for your report.
The issue is already fixed in develop branch, 2.1.10, 2.2.1

**Comment by sebfie** [comment]
Where is the fix for that? I still have the issue on magento 2.2.6.

**Comment by slavvka** [comment]
Hey @philcali feel free to create an issue if you still feel it exists
