### ISSUE TITLE
Swatch behavior becomes annoying when user want to see all product images before choose an option

### ISSUE THREAD

**Issue by JeffersonTeixeira** [magento/magento2#33893]
### Summary (*)
About the configurable product, it is very comfortable to the user navigate between all images product before select an option, but may be confusing show all images when user has an option selected.
Swatch behavior becomes annoying when user want to see all product images before choose one, further if its a dropdown.

### Examples (*)
Currently all images are not displayed when user has no option selected yet. Only configurable is showing.

### Proposed solution
Once configurable product is a "group" of simple product:
Before user select an option, should display all product thumbnails in gallery (simple products + configurable). When user select an option hide all other images except the selected simple product image + configurable (like it is today). 
When user has no option selected the images in gallery user should see only one of each simple product, I guess it is the best option (show all might be a configuration in backend but I think its confusing to the user in some cases). Example considering:

- Configurable product with 3 options (3 simple products)
- Configurable product has 1 image
- Each simple product 2 images

When user has no option selected, the total images available to navigate in is 4 (1 configurable +1 each simple)
when user click in any option in this example should be 3 images to navigate in (1 configurable + 2 selected option)

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @JeffersonTeixeira 
Thanks for reporting this issue.
Could you please help us by adding the **Steps to reproduce** the issue that you are facing , **actual** & **expected** results. If you could also attach some screenshots of the issue that you are facing, it would definitely help us better to look into your issue.
Thank you.

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by JeffersonTeixeira** [comment]
The issue is not fixed.

### Steps to reproduce (*)
Any configurable product (swatch) which has some configuration (simple product) with different image each one.

### Actual result (*)
When there is no option selected, it shows only the configurable product's image.
Bellow, screenshot using swatch with dropdown which is the most annoying example in my opinion:
![image](https://user-images.githubusercontent.com/23153235/132760794-0d2d4803-9735-4a01-9348-45704003c9f8.png)

If the product has some variations, see all of them becomes a boring task:
![image](https://user-images.githubusercontent.com/23153235/132760588-7e684f4d-af5f-44d7-93e4-f565d1d737f3.png)

### Expected result (*)
It should show all products' images if the user has not selected any option yet, This way the user could see all images before choose one, something like that:
![Screenshot_20210909_204012](https://user-images.githubusercontent.com/23153235/132776911-2ccf4186-755c-4b31-b6e2-0c29d5fb01b1.png)

When the user select an option it should keep the current behaviour: Show only the product selected images + configurable product image, like bellow
![image](https://user-images.githubusercontent.com/23153235/132760733-1a9ac4ea-c43b-4fc8-b986-189434a2b9ea.png)


About which images to show when there is no option selected I don't know what is the best way if the variation (simple product) has more than one image:
Show all images of each product configuration or
Show only the image with a specific role (Base, Swatch, Thumbnail etc)
So would be perfect a way to choose between these configuration

**Comment by engcom-Lima** [comment]
Hi @JeffersonTeixeira,

So if I understood correctly, what you want is 'If any configurable product is added with multiple Simple Products under Swatch behaviour, all the images of the Simple products should also show in a sidebar but currently only default Configurable product image is being displayed.'

I think you can directly add all the images you are using for Simple products in Configurable product itself irrespective of the swatch behaviour. When the customer opens the product, it’ll display all configured product images including simple product ones as you want. Now if any customer particularly choose any variant, then it should display image relating to that specific simple product.

Now, I don’t see this issue as bug but it is an expected behaviour of Magento. So please advise if I understood your issue correctly ? Or otherwise provide more information accordingly.

**Comment by JeffersonTeixeira** [comment]
> Hi @JeffersonTeixeira,
> 
> So if I understood correctly, what you want is 'If any configurable product is added with multiple Simple Products under Swatch behaviour, all the images of the Simple products should also show in a sidebar but currently only default Configurable product image is being displayed.'
> 
> I think you can directly add all the images you are using for Simple products in Configurable product itself irrespective of the swatch behaviour. When the customer opens the product, it’ll display all configured product images including simple product ones as you want. Now if any customer particularly choose any variant, then it should display image relating to that specific simple product.
> 
> Now, I don’t see this issue as bug but it is an expected behaviour of Magento. So please advise if I understood your issue correctly ? Or otherwise provide more information accordingly.
You understood correctly. I could do this workaround to have it working and change the swatch's behaviour to replace instead merge, right?
But this way becomes a little "boring" add images 2x. And what happens to image loading this way? Will it load from server 2x once it is the same image but its in two different product? 1x for configurable once again when I select a option? (I just want understand server traffic). Or magento know somehow its the same image?

**Comment by engcom-Lima** [comment]
Hi @JeffersonTeixeira,

I understood your point but since Magento's expected behaviour is like this as of now, we can't call it a bug. 

What I can suggest is, you can raise the same issue on [Community Features](https://github.com/magento/community-features) and team can look into it if its a viable option for future versions.

And since it is not a bug, we are closing it. If you still feel it is a bug related to Magento Dev, please raise a fresh ticket or re-open this ticket with more details so that we can look further.

Thanks
