### ISSUE TITLE
Bugged Interaction Between Collection Cache and Configurable Products Gallery

### ISSUE THREAD

**Issue by JamesFX2** [magento/magento2#33965]
We noticed occasional errors in site logs 

### Preconditions (*)

1. 2.3.5 - 2.4 develop

### Steps to reproduce (*)

1.  When the getOptionsMediaGalleryDataJson() method is called in \Magento\Catalog\Block\Product\View\Gallery
2. If the product is a configurable product, the plugin at [\Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/Block/Plugin/Product/Media/Gallery.php#L45) is called and calls the type instance's getUsedProducts method.
3. This is then intercepted by the plugin as [Magento\ConfigurableProduct\Model\Plugin\Front\UsedProductsCache](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/Model/Plugin/Frontend/UsedProductsCache.php#L168-L186) which serializes the array of items loaded. 
4. The next time another instance of the Product needs to pull in getUsedProducts, it's loaded from the frontend cache which unserializes the data, creates new instances of Products via the Factory method but the problem occurs when somehow, one of the array of Products that was saved has already called getMediaGalleryImages() so has a value set for 'media_gallery_images' - when this is unserialized, it's just created as 'media_gallery_images' => [] 
5. So when the block now calls getOptionsMediaGalleryDataJson() since the [Product](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product.php#L1560) has a value for 'media_gallery_images', line 1560 causes an error. Please consider modifying this to check.

### Expected result (*)

1. Collection of DataObjects returned with images from the gallery / JSON array

### Actual result (*)

1.  > [31-Aug-2021 21:26:44 UTC] PHP Fatal error:  Uncaught Error: Call to a member function count() on array in /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-catalog/Model/Product.php:1533
> Stack trace:
> #0 /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-configurable-product/Block/Plugin/Product/Media/Gallery.php(62): Magento\Catalog\Model\Product->getMediaGalleryImages()
> #1 /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-configurable-product/Block/Plugin/Product/Media/Gallery.php(49): Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery->getProductGallery(Object(Magento\Catalog\Model\Product\Interceptor))
> #2 /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/framework/Interception/Interceptor.php(146): Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery->afterGetOptionsMediaGalleryDataJson(Objec in /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-catalog/Model/Product.php on line 1533
> [31-Aug-2021 21:26:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function count() on array in /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-catalog/Model/Product.php:1533
> Stack trace:
> #0 /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-configurable-product/Block/Plugin/Product/Media/Gallery.php(62): Magento\Catalog\Model\Product->getMediaGalleryImages()
> #1 /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-configurable-product/Block/Plugin/Product/Media/Gallery.php(49): Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery->getProductGallery(Object(Magento\Catalog\Model\Product\Interceptor))
> #2 /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/framework/Interception/Interceptor.php(146): Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery->afterGetOptionsMediaGalleryDataJson(Objec in /home/cloudpanel/htdocs/www.redacted.com/releases/2021_08_27_10_55_43_branch_v2.3.5-72/vendor/magento/module-catalog/Model/Product.php on line 1533

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @JamesFX2,

Thank you for reporting the issue. But the information provided is not enough for me to reproduce this.

I think you were explaining the inner functionality of how errors might be coming but it is unclear about how I can replicate this issue on 2.4-develop instance. Can you be more specific with the details like if you are facing this issue on Admin Panel or Frontend ? Update the 'Steps to reproduce' so that I can follow it to produce these errors.

**Comment by JamesFX2** [comment]
Yeah, I just put a plugin on Magento\Catalog\Model\Product

```
<?php

namespace Company\Module\Plugin\Catalog\Model;

class Product
{
    public function beforeGetMediaGalleryImages(\Magento\Catalog\Model\Product $subject)
    {
        
        if($subject->hasData('media_gallery_images')){
            $images = $subject->getData('media_gallery_images');
            if(!is_object($images)){
                $subject->unsetData('media_gallery_images');
            }
        }
    }
}`
```

**Comment by serzhik** [comment]
@JamesFX2 in my case https://github.com/PHOENIX-MEDIA/magento2-mediastoragesync breaks standard flow as you described.

**Comment by convenient** [comment]
FWIW i saw this dropping off after upgrading to 2.4.3

**Comment by friendscottn** [comment]
This is still an issue in 2.4.5

**Comment by skoval-auchan** [comment]
Still an issue in 2.4.5-p1

**Comment by serzhik** [comment]
Issue still present in 2.4.5-p1

**Comment by artttj** [comment]
Same here. We faced that issue in 2.4.5-p1 - when you open dozens of configurable products simultaneously in new tabs.

**Comment by Buzzorus** [comment]
Had same issue. **Plugin fixed the problem**

Fetched with Frontend response
![bug](https://github.com/magento/magento2/assets/93948782/8756d759-ba61-4e38-9116-d8e9ada3a33c)

    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function count() on array in /data01/virt65663/domeenid/www.pood24.ee/htdocs/vendor/magento/module-catalog/Model/Product.php:1533
Stack trace:
#0 /data01/virt65663/domeenid/www.pood24.ee/htdocs/vendor/magento/module-configurable-product/Helper/Data.php(52): Magento\Catalog\Model\Product-&gt;getMediaGalleryImages()
#1 /data01/virt65663/domeenid/www.pood24.ee/htdocs/vendor/magento/module-configurable-product/Block/Product/View/Type/Configurable.php(262): Magento\ConfigurableProduct\Helper\Data-&gt;getGalleryImages(Object(Magento\Catalog\Model\Product\Interceptor))
#2 /data01/virt65663/domeenid/www.pood24.ee/htdocs/vendor/magento/module-configurable-product/Block/Product/View/Type/Configurable.php(239): Magento\ConfigurableProduct\Block\Product\View\Type\Configurable-&gt;getOptionImages()
#3 /data01/virt65663/domeenid/www.pood24.ee/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\ConfigurableProduct\Block\Product\View\Type\Configurable-&gt;getJsonConfig()
#4 /data01/ in <b>/data01/virt65663/domeenid/www.pood24.ee/htdocs/vendor/magento/module-catalog/Model/Product.php</b> on line <b>1533</b><br />

**Comment by zaietsv** [comment]
The issue still presents at Magento 2.4.6-p3

**Comment by buderus199** [comment]
Issue still present in 2.4.5-p5. It happens randomly. I haven't find why it is triggered.

**Comment by zaietsv** [comment]
@buderus199 that's funny that the @engcom-Lima supposes the task is resolved.

**Comment by MartinVanVan** [comment]
Still get this bug with Adobe Commerce Ver.-2.4.7-p3. Definitely not resolved @engcom-Lima

**Comment by zaietsv** [comment]
Hey, @engcom-Hotel wouldn't you like to reopen the issue?

**Comment by engcom-Hotel** [comment]
Hello @zaietsv,

We would be happy to reopen the issue, but we request you to please go through with https://github.com/magento/magento2/issues/33965#issuecomment-919981193 and provide us the required information.

Thanks

**Comment by mpchadwick** [comment]
Regardless of whether there area clear steps to reproduce this code is clearly buggy:

```php
if (!$this->hasData('media_gallery_images')) {
    $this->setData('media_gallery_images', $this->_collectionFactory->create());
}
if (!$this->getData('media_gallery_images')->count() && is_array($this->getMediaGallery('images'))) {
```

`hasData` checks if `the array_key_exists` on it's data 

https://github.com/magento/magento2/blob/5044c28da09573f273429f9a070b89d1dae0c9cc/lib/internal/Magento/Framework/DataObject.php#L243

This means it can return `true` in the case of an array, so it's not safe to call `->count()` on it as it cannot be guaranteed that it will be an object with that method defined.

It would be safer to at minimum validate that it's an object.  Code not tested, but something like this

```php
if (!$this->hasData('media_gallery_images') || !is_object($this->getData('media_gallery_images'))) {
    $this->setData('media_gallery_images', $this->_collectionFactory->create());
}
if (!$this->getData('media_gallery_images')->count() && is_array($this->getMediaGallery('images'))) {
```

Just to note I am also seeing these in logs on a production project, but unsure what sequence of steps caused the application to get into this state

**Comment by engcom-Bravo** [comment]
Hi @JamesFX2

Adobe Commerce Engineering team started working on this issue. We will reach out to you if we need more information and you will get notified once the issue is fixed. Please leave comments for any further questions. Thank you!

**Comment by kestraly** [comment]
@KevinAjax-tm  - Ahhh, I had that too and then had to update module.xml with

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Developer_GalleryFix" setup_version="0.0.1">

        <sequence>
            <module name="Magento_Catalog"/>
        </sequence>

    </module>

</config>

```
