### ISSUE TITLE
Composer require fills lock file with 2tvenom/cborencode src and dist

### ISSUE THREAD

**Issue by marceldekoning** [magento/magento2#34325]
### Summary
When I execute the composer require command after a clean installation, all the packages in the composer.lock file are replaced with references to the 2tvenom/cborencode package which makes it impossible afterwards to execute the composer install command because all the packages are returned 404.

### Preconditions (*)
1. Magento 2.4.3
2. PHP 7.4
3. Composer V1

### Steps to reproduce (*)
1. Clone a clean copy of Magento 2.4.3 with `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition`
2. Require a package with `composer require a/module-b`
3. Inspect your composer.lock file.

### Expected result (*)
1. All packages should have their own source and dist URL

### Actual result (*)
1. All packages have the source URL set to https://github.com/2tvenom/CBOREncode.git
2. All distributions come from https://api.github.com/repos/2tvenom/CBOREncode/zipball/[randomstring]

![2tvenom](https://user-images.githubusercontent.com/22954410/136974319-73441cf1-5aa4-4a85-a899-4638e0194e08.png)

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pemann** [comment]
I had this same weird problem after upgrading from 2.4.2 to 2.4.3.
What I did to resolve this was:
(1) Remove dependency  "magento/composer-root-update-plugin": "^1.1" from composer.json
(2) Remove composer.lock file
(3) Remove vendor folder
(4) Run composer install

**Comment by denis-zyk** [comment]
I've observed this weird behaviour some time ago, and none of the above workarounds have worked back then, except for the following one (similar to @Axel29):

0. rollback `composer.lock` file or remove it completely
1. `rm -rf vendor/*`
2. `rm -rf var/vendor/*`
3. switch to composer V2
4. `composer clear-cache`
5. `composer install` (`composer.lock` should be OK afterwards)
6. switch back to composer V1 - the issue should not be reproducible anymore

**Comment by jankovandeventer** [comment]
I had this issue today where my Magento 2 Base was replaced by 2tvenom. 
![Screenshot from 2021-12-02 11-27-28](https://user-images.githubusercontent.com/10960505/144405276-ffb08bc5-d5f4-4a9c-9e9c-837a579db48f.png)
![Screenshot from 2021-12-02 11-27-51](https://user-images.githubusercontent.com/10960505/144405280-53cbef5b-d9b2-46da-9ec4-2fbeec5bb94b.png)

workaround:
magento/composer-dependency-version-audit-plugin

1. composer remove magento/composer-dependency-version-audit-plugin
2. magento/composer-root-update-plugin
2. removed composer.lock
2. removed vendor folder
3. `composer clearcache`
4. `composer install

What a hassle.

**Comment by engcom-Bravo** [comment]
Hi @marceldekoning 

We have tried to reproduce this issue but for us, it is not reproducible.

Precondition: 
Php 7.4
Compose 2.1.6
Magento 2.4.3

 We have followed below steps 

1.Installed magento version 2.4.3

<img width="452" alt="Install" src="https://user-images.githubusercontent.com/51680745/147568595-5a0d9b80-7d1c-402c-96ea-bc5c0e069ecd.png">

2. composer require shipperhq/module-shipper
<img width="452" alt="composer-require" src="https://user-images.githubusercontent.com/51680745/147568862-f5ee2f80-2c95-40dd-98fa-b8a86d64f882.png">

3. Composer.lock file contains correct dist and source
<img width="452" alt="composerlock" src="https://user-images.githubusercontent.com/51680745/147568882-5e792439-3e9e-40ff-9244-c0b1f251efdd.png">


Please let us know if we are missing any steps here.

**Comment by JonathanBBD** [comment]
This is still a problem.

Just reproduced  during my own Magento upgrade from 2.3.7-p2 to 2.4.3-p1.

I followed these steps in https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html

(not within the steps, but since it's a composer issue, start with `composer clear-cache`)

```
composer require magento/composer-root-update-plugin ~2.0 --no-update
composer update
composer remove magento/product-community-edition --no-update
composer require-commerce magento/product-community-edition 2.4.3-p1 --no-update
composer update
```

Now `composer.lock` is now full saturated of 2tvenom/cborencode.

Thanks to @jankovandeventer I could fix the composer.lock file. You cannot skip any of his steps _(I tried skipping the 'remove vendor' part but it fixed it when I removed the folder, clear my composer cache, deleted composer.lock and updated it)_

**Comment by pdohogne-magento** [comment]
@JonathanBBD One note about the steps you have listed:

> ```
> composer remove magento/product-community-edition --no-update
> composer require-commerce magento/product-community-edition 2.4.3-p1 --no-update
> ```

If you are just moving between versions and not editions (e.g. from 2.3.7-p2 to 2.4.3-p1 and not from Magento Open Source to Adobe Commerce), you don't need the remove command.  I don't think that's related to the issue here, but it's worth trying.  I'll see if we can get that clarified in the docs.

Also, if you ever remove composer.lock it's a good idea to remove vendor as well; composer expects vendor to be empty if there's no lock file and thus doesn't clean it properly if it still exists (it tries to do the minimum necessary for the expected state for performance).

**Comment by zuongthaotn** [comment]
I have same problem, it is happen every time I installed a new extension by composer.

**Comment by edward-simpson** [comment]
Is there any chance there's a malicious nature to this?  Imagine there's a fair amount of data to be gained by proxying all composer installs through a single endpoint?

**Comment by dfelton** [comment]
For what it is worth, I just reviewed a PR of a web agency's contribution to my company's project, and when reviewing the diff for the `composer.lock` file I too discovered this exact same issue was present in the PR that had been submitted.

Some searching around led me to this GitHub issue, and it relieved me (a little, not much) that others have experienced this problem too. I highly suspected something malicious was going on (still not entirely convinced there isn't...).

Despite attempting to reproduce the issue on my end with both Composer v1 and v2 I had no luck. Localhost testing showed that performing a `rm -rf vendor/ && git reset --hard HEAD && composer install` with the bad lock file in place did succeed in successfully installing packages, still, I will be rejecting the PR and asking the web agency what the heck happened for the file to get this way.

**Comment by rob-gonz** [comment]
Just had this occur to us on EE version going from 2.4.2 to 2.4.3. Something weird is going on with composer proxying in my opinion.

**Comment by tales-desde-mileto** [comment]
I can reproduce if I use composer 1 (1.10.24)
But:
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html
Magento 2.4.3 --> "required" composer 2
Composer 1 with 2.4.3 is not in matrix of "system requirement"
Perhaps the fix could be use composer 2
Same problem if you use composer 2?

**Comment by vandijkstef** [comment]
> I had this same weird problem after upgrading from 2.4.2 to 2.4.3. What I did to resolve this was: (1) Remove dependency "magento/composer-root-update-plugin": "^1.1" from composer.json (2) Remove composer.lock file (3) Remove vendor folder (4) Run composer install

Reproduced with Composer 1.10.25 Mage 2.4.3-p1, upon new module install, and fixed by quoted above

**Comment by vandijkstef** [comment]
As this issue bothered me again, I went and tried to find something more:

I can confirm this issue using the steps in the original issue, using 'composer require picqer/php-barcode-generator' on both OSX (PHP 7.4.21 / composer 1.10.25) and WSL Ubuntu (PHP 7.4.27 / composer 1.10.23) using a fresh Magento 2.4.3.

I can also confirm that you have to delete both 'composer.lock' and 'vendor/' dir to be able to fix the issue with 'composer install'.

Here is the (final) composer.json file:

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "version": "2.4.3-p1",
    "require": {
        "magento/composer-dependency-version-audit-plugin": "~0.1",
        "magento/composer-root-update-plugin": "~1.1",
        "magento/product-community-edition": "2.4.3-p1",
        "picqer/php-barcode-generator": "^2.2"
    },
    "autoload": {
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ],
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "psr-4": {
            "Magento\\": "app/code/Magento/",
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/"
        }
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.4",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~2.18.1",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": "^0.12.77",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "^6.0.3",
        "squizlabs/php_codesniffer": "~3.5.4",
        "symfony/finder": "^5.2"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/",
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```


> I can reproduce if I use composer 1 (1.10.24)
> But:
> https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html
> Magento 2.4.3 --> "required" composer 2

I see composer 2 only required starting at Mage 2.4.4+, besides theres still packages not available in Composer 2 for me. Maybe it changed in the meantime.

May I stress that installing and/or updating a package takes A LOT more time with this issue around?

> Please let us know if we are missing any steps here.

@engcom-Bravo  You missed we're all doing this on Composer 1, which should be the version according to the documentation right now.

Furthermore I tried 'composer update' with composer-dependency-version-audit-plugin and composer-root-update-plugin REMOVED, but this didn't solve anything. I assume the others that have been lucky, accidently also deleted both the lock-file and the vendor dir

**Comment by agorbulin** [comment]
I confirm the problem on Magento Cloud 2.4.4 + composer 1.10.22
After switching to composer 2.3.2, problem solved. After switching back to composer 1.10.22, problem comes back.

**Comment by yuriichayka** [comment]
Seems the issue appears only when you specify the exact version when requiring some module, for example - `composer require amasty/meta:1.3.2`

My STR:
        1. Have Magento 2.4.3 EE installed with PHP 7.4.28 and composer 1.10.22.
        2. composer require magento/product-enterprise-edition:2.4.4 --no-update
        3. composer update
        4. composer require amasty/meta:1.3.2

And a workaround seems to be removing 'magento/composer-dependency-version-audit-plugin', as follows in the root composer.json:
        1. Add the following to the root composer.json:
        ```
            "replace": {
                "magento/composer-dependency-version-audit-plugin": "*"
            }
        ```
        2. remove vendor directory
        3. composer update
OR just add the mentioned instruction to compose.json before doing `composer update` for 2.4.4 version.

**Comment by yuriichayka** [comment]
Hi @engcom-Bravo 
Can you please try reproducing it again by the steps provided above?

**Comment by fabrice-dresscodes** [comment]
Hi,

I got the same problem today when migrating from Community 2.3.3 to 2.4.4.

Deleting the composer.lock and vendor/* folder let the composer installation finishing.

**Comment by necrojan** [comment]
Got the same problem.  Mine's fixed by following @n2diving-dgx instructions.

**Comment by janssensjelle** [comment]
Got the same issue here. The steps mentioned above didn't resolve it for me. 

Magento 2.4.3-p2 - PHP 7.4.26 - composer 1.10.26

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4.4 && 2.4.5** branch.

**Description:**
While installing extension all the packages in the `composer.lock` file ,source and dist url are replaced with references to the `2tvenom/cborencode ` package.

**Pre-requisite:**
1. Magento 2.4.3
2. PHP 7.4
3. Composer V1

**Steps to reproduce:**
1.  Upgrade magento `2.4.3` to magento `2.4.4` .
2.  Give `shipperhq/module-shipper` in require section of `composer.json`.
3.  Run `composer require shipperhq/module-shipper` in terminal.
4.  Inspect your `composer.lock` file.

**Expected result:**
1. All packages should have their own source and dist URL

**Actual result:**
1. All packages have the source URL set to https://github.com/2tvenom/CBOREncode.git
2. All distributions come from
https://api.github.com/repos/2tvenom/CBOREncode/zipball/[randomstring]

**Screenshots:**
![image](https://user-images.githubusercontent.com/60198022/186366225-a4dcc2ca-8b6a-4e76-b0ed-37cc1a069f61.png)

**Note :**Same issue observed while upgrading from 2.4.3 to 2.4.5.

Hence,confirming the issue.

**Comment by devteam-carmelo** [comment]
Using composer 2 seems to solve the issue.

**Comment by vandijkstef** [comment]
> Using composer 2 seems to solve the issue.

Yes. But 2.4.3-X and 2.4.4-X has a support for Composer 1 according to the documentation (https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html).

And half this thread has been about making aware that this is limited to Composer 1. If we wait till EOL of 2.4.3/2.4.4 we can close this issue indeed

**Comment by DominicWatts** [comment]
If you are staying with Composer 1 the Solution for me was as follows:

  -  rename `./vendor` and `composer.lock`
  -  hard set a load of versions in `composer.json` to match current versions (to stop unnecessary upgrades)
  -  run `composer install`

Some development tools (require-dev) were upgraded but otherwise I got a clean composer.lock and a stable site.

**Comment by lbajsarowicz** [comment]
This only affects Composer 1, which is end of life and no longer supported by Magento. 2.4-develop requires composer/composer ^2.2, and the reporters confirmed Composer 2 does not produce the bloated lock file.

cc @hostep

**Comment by engcom-Bravo** [comment]
@lbajsarowicz Thanka for your update.

Hi @marceldekoning,

As per this comment https://github.com/magento/magento2/issues/34325#issuecomment-5548374692 closing this issue.

Thanks.
