### ISSUE TITLE
Creditmemos: The store that was requested wasn't found. Verify the store and try again.

### ISSUE THREAD

**Issue by jdereus87** [magento/magento2#34349]
### Preconditions (*)
1. Magento 2.4.3 

### Steps to reproduce (*)
1. Change website name + storename to something that has a number. Example: '2 Unlimited'
2. Refund an order
3. Tab: Credit Memos now gives an error
The store that was requested wasn't found. Verify the store and try again.
Exception in /data/web/magento2/vendor/magento/module-store/Model/StoreRepository.php:75
4. Menu -> Sales -> Credit Memos gives an identical error 

### Expected result (*)
1. Credit memo grid Shows

### Actual result (*)
1. Credit Memo Grid gives an error. 

**Workaround:** Remove the numbers from the store name and website name

Tested it on an existing 2.4.3 installation + a fresh 2.4.3. installation. I have processed this through xdebug.

1. It recursively loops trough components starting in: vendor/magento/framework/View/Element/UiComponent/Context.php:255, changing values by pass by reference.
2. Eventually it will get to the store_id component. It will run the store ID parameter through the following function:
vendor/magento/module-store/Ui/Component/Listing/Column/Store.php:93 -> PrepareItem().
3. Since the functions are all passed by reference, the data changes. The store_id value changes from a simple integer to the following: "2unlimited.nl<br/>&nbsp;&nbsp;&nbsp;2unlimited<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;unlimited<br/>"
**Note: the string contains nbsp and br tags**
4. Eventually it loops to the 'subtotal' component: vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php
The store_id value that was changed is being used there.
Function: prepareDataSource(); 

`                    $storeId = isset($item['store_id']) && (int)$item['store_id'] !== 0 ? $item['store_id'] :
                        $this->context->getFilterParam('store_id', Store::DEFAULT_STORE_ID);
                    $store = $this->storeManager->getStore(
                        $storeId
                    );
`
Normally it gives a true & false value on the check, which causes the store_id to be set back to 0. However because there is a number in the storename (see string above), the (int) cast sets the int to 2. It now gives a true & true, and the store_id stays the strange string.
5. In the storerepository it eventually gets to the get() function, where it fails and gives the error.
vendor/magento/module-store/Model/StoreRepository.php: line 63, error on line 75.

### Additional Info (*)
Note:
1. There is no issue when Website name is given as "Unlimitted 2" (Issue raises)
2.  In 2.4-develop we can't even refund! If we try to navigate to the Credit Memo, we get the error in page loading itself.
![image](https://user-images.githubusercontent.com/60198231/137735045-89265c79-769c-48ea-adb7-dd020203ca74.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by jdereus87** [comment]
Bug reproduced in dev instance.

Placing a 2 on both the store name + store website directly breaks the sales -> credit memos grid with error:
The store that was requested wasn't found. Verify the store and try again.

**Comment by j-stam** [comment]
Ran into the same problem yesterday. We also have digits in our website name and group name. 

The problem originates from Magento/Sales/Ui/Component/Listing/Column/Price.php Line 81.

```php
$storeId = isset($item['store_id']) && (int)$item['store_id'] !== 0 ? $item['store_id'] :
    $this->context->getFilterParam('store_id', Store::DEFAULT_STORE_ID);
```
adding a numeric check fixes the issue.

```php
$storeId = isset($item['store_id']) && is_numeric($item['store_id']) && (int)$item['store_id'] !== 0
    ? $item['store_id']
    : $this->context->getFilterParam('store_id', Store::DEFAULT_STORE_ID);
```

I'm not sure why the data source provides the store name as the store id (probably something to do with displaying data in the grid) but because this store name string is typecasted to an integer, the digits remain and the `getStore` function tries to load the store with this string instead of the fallback (default store).

I've created a pull request to fix this: https://github.com/magento/magento2/pull/34716
commit: https://github.com/magento/magento2/pull/34716/commits/5b1b00d33f6cbb8d036fd3a7b367361e303c355c

**Comment by nazarklovanych** [comment]
@magento I am working on this

**Comment by nazarklovanych** [comment]
this is already fixed in 2.4.4 @jdereus87  we can close.

**Comment by eBusinessAtlantique** [comment]
Where can we get the fix for M2.4.3 ? Thanks.

**Comment by seungwooc-23** [comment]
Hi @jdereus87 and @nazarklovanych , we are on 2.4.4 and still experiencing this problem on the creditmemo page.

**Comment by eBusinessAtlantique** [comment]
When a store is deleted the credit memo grid is sending an error and do not displays.
Solution :
Remove these lines in this file : \vendor\magento\module-store\Model\StoreRepository.php
around line 112

        if ($store->getId() === null) {
            throw new NoSuchEntityException(
                __("The store that was requested wasn't found. Verify the store and try again.")
            );
        }

**Comment by simonmaass** [comment]
I can confirm this issue in magento 2.4.6-p3.... i get this error when i sort the credit memo grid for the column "Credit Memo"...

<img width="881" alt="image" src="https://github.com/magento/magento2/assets/32599710/2a713670-b9b2-4b18-b067-cd58d77e1015">

error in response in console:
```
{
    "error": "The store that was requested wasn&#039;t found. Verify the store and try again.",
    "errorcode": "0"
}
```

**Comment by roman204** [comment]
Still got this issue on 2.4.5-p6

**Comment by roman204** [comment]
maybe someone can use it...
```
Index: vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php b/vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php
--- a/vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php
+++ b/vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php	(date 1719395045132)
@@ -8,6 +8,7 @@
 namespace Magento\Sales\Ui\Component\Listing\Column;

 use Magento\Framework\App\ObjectManager;
+use Magento\Framework\Exception\NoSuchEntityException;
 use Magento\Framework\View\Element\UiComponent\ContextInterface;
 use Magento\Framework\View\Element\UiComponentFactory;
 use Magento\Store\Model\Store;
@@ -82,7 +83,11 @@
                     $itemStoreId = $item['store_id'] ?? '';
                     $storeId = $itemStoreId && is_numeric($itemStoreId) ? $itemStoreId :
                         $this->context->getFilterParam('store_id', Store::DEFAULT_STORE_ID);
-                    $store = $this->storeManager->getStore($storeId);
+                    try {
+                        $store = $this->storeManager->getStore($storeId);
+                    } catch (NoSuchEntityException $entityException){
+                        $store = $this->storeManager->getStore(Store::DEFAULT_STORE_ID);
+                    }
                     $currencyCode = $store->getBaseCurrency()->getCurrencyCode();
                 }
                 $basePurchaseCurrency = $this->currency->load($currencyCode);

```

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @jdereus87,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1375" alt="Screenshot 2024-09-06 at 11 04 52" src="https://github.com/user-attachments/assets/ee181704-8d49-4c27-be6d-560ea3edaf8c">


Credit memo grid Shows

Hence we are closing this issue.

Thanks.
