### ISSUE TITLE
Mobile and desktop image showing at 768px when using pagebuilder

### ISSUE THREAD

**Issue by bas-hendriks** [magento/magento2#34551]
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Add an image to a page using the pagebuilder 

### Expected result (*)

1. Show the mobile version of the image

### Actual result (*)

1. The mobile and desktop version of the image is shown on 768px, since this is a very common width (iPad portrait) this should be fixed
2. As shown in the screenshots below the 768px media query is not being handled in a proper way resulting in the 2 images being shown

![pagebuilder-desktop](https://user-images.githubusercontent.com/19948878/140527112-d1b8b506-fb98-4a28-b204-e16b2b40760a.jpg)
![pagebuilder-mobile](https://user-images.githubusercontent.com/19948878/140527115-563d0a13-7fcd-4dd5-a78c-b73ebc8d70bb.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @bas-hendriks,

We have tried to reproduce the issue in Magento 2.4-develop, but the issue is not reproducible for us. Please have a look at the below screenshot for reference (For iPad Portrait mode):
<img width="1424" alt="Screenshot 2021-11-08 at 2 47 51 PM" src="https://user-images.githubusercontent.com/51681618/140715800-32fspecific 06-a980-40f3-8041-79fe2fc32206.png">

For us the single image is showing for both images, please let us know if you are using any specific resolution.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @bas-hendriks,

Thanks for the update. As per your last comment, it seems that this issue has been fixed in Magento 2.4-develop branch. So we are closing this issue.

Thanks

**Comment by amcguireweb** [comment]
This issue was not fixed, it was made much worse by this commit: https://github.com/magento/magento2/commit/04012ba8e939377c626fb853e75794e093173a68

No one should be surprised though, it's the Magento/Adobe way.
