### ISSUE TITLE
New account create issue when set gender field required in address from backend

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#3457]
Hello,

When we set the gender field required from backend and when we try to checkout with new account creation than **gender field doesn't display in billing form or shipping form**.  After placing order on success page magento ask for new account creation [ There is new button Create Account] and when we click this button **it gives error like gender is required field.**

![success page](https://cloud.githubusercontent.com/assets/17308601/13134782/463c2650-d630-11e5-978f-5f8161be1189.png)

**To reproduce this issue**
- Login into magento admin panel
- Go Stores > Configuration
- Customers > Customer Configuration>Name and Address Option 
- set Show Gender field to required 

![configuration settings stores magento admin](https://cloud.githubusercontent.com/assets/17308601/13134869/04f50fe4-d631-11e5-8a10-2e166f550b37.png)

**I think this is bug for magento2 because when we set this option than this field should display in checkout form and it must be required field if we set required like magento1.**

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-49820

**Comment by keyurshah070** [comment]
@sevos1984 Any updates on this ?

**Comment by slavvka** [comment]
Hi @keyurshah070. MAGETWO-49820 has been fixed and delivered, please see at commits.

**Comment by keyurshah070** [comment]
@slavvka 

Thank you for resolving this issue.

**Comment by ludwig-gramberg** [comment]
in which version will this be fixed? in 2.0.6 its still an issue

**Comment by ludwig-gramberg** [comment]
just upgraded to 2.0.7 definetly not fixed:

![bildschirmfoto_2016-06-09_um_14_43_41](https://cloud.githubusercontent.com/assets/2245065/15929975/a581032e-2e50-11e6-9eb9-661ad4bc38a1.png)

**Comment by slavvka** [comment]
It is in the latest code in https://github.com/magento/magento2 repo not in releases yet

**Comment by han-yue** [comment]
This problem still exists in version 2.1.6. Is there a way to self help and fix this rather than wait for the fix from the team?

**Comment by orlangur** [comment]
```
git checkout 2.1.6
git log --grep MAGETWO-49820
```

=>

```
commit d05b3bf6a51cf40c8003aa9008792406376dca28
Merge: b85e8ea7c98 2aa6e5ac94b
Author: Sergey Semenov <ssemenov@magento.com>
Date:   Thu May 5 18:07:34 2016 +0300

    Merge remote-tracking branch 'origin/MAGETWO-49820-Customer-validation' into BUGS

commit 2aa6e5ac94b7f3468e7f2875291a635a8d7a08fd
Merge: b634b2a3f70 135f9670f14
Author: Sergey Semenov <ssemenov@magento.com>
Date:   Thu May 5 17:40:35 2016 +0300

    Merge remote-tracking branch 'mainline/develop' into MAGETWO-49820-Customer-validation

commit b634b2a3f707ecc45fa21fe5a152c97a4d542326
Author: Volodymyr Sevostianov <vsevostianov@ebay.com>
Date:   Fri Apr 29 18:03:39 2016 +0300

    MAGETWO-49820: Can't register customer if customer attribute is required but not visible (#3457)

commit 500177a6cedcacada732dbc0c59619c00c657606
Author: Sviatoslav Mankivskyi <smankivskyi@magento.com>
Date:   Fri Apr 29 16:57:01 2016 +0300

    MAGETWO-49820: Can't register customer if customer attribute is required but not visible (#3457)

commit 334db5c9773a4f72f3298dfca2a9ef2b8a7e0ab9
Author: Oleksandr Karpenko <okarpenko@magento.com>
Date:   Wed Apr 27 18:28:31 2016 +0300

    MAGETWO-49820: Can't register customer if customer attribute is required but not visible (#3457)

commit 41d7ede1574a20bd0845638692aa55dc1d344254
Author: Oleksandr Karpenko <okarpenko@magento.com>
Date:   Wed Apr 27 14:07:03 2016 +0300

    MAGETWO-49820: Can't register customer if customer attribute is required but not visible (#3457)
```

Should work in 2.1.6. Maybe you have slightly different steps to reproduce?

**Comment by han-yue** [comment]
It's the same steps to reproduce. In backend set gender and date of birth to required. But guest checkout did not have fields to ask for gender and date of birth. Hence when creating account after the checkout, it prompts the gender and date of birth is required error.

**Comment by speedupmate** [comment]
this is not fixed the issue is in magento2/app/code/Magento/Sales/Model/Order/CustomerManagement.php in create() method and the cause of this is that customer is  created based on order address data and not including customer_* values from order itself 

on top of that you can't have gender field in checkout address forms cause it's not implemented

**Comment by ajayjaiswalweb** [comment]
Hi, @keyurshah070 @sevos1984 @slavvka 
I am getting same Error for Customer Login.

We have an old customer's on the website who have not entered their gender when they signup in past. Now we have made Gender required for the signup on the website. Here the problem comes - when old customer trying to login to their account they couldn't able to log in. They are getting Error:- "Gender Required" when trying to login using correct username & password.

Note:- This problem is for only old customers who have not selected their gender.

Please find the screenshot for your reference. Need your help! please advise.

![gender_required_error](https://user-images.githubusercontent.com/14846878/38997168-7647a514-440a-11e8-97b4-fc7b4a790271.jpg)

**Comment by Jackcar** [comment]
Any update on this? I am still facing the same issue on version 2.2.4
