### ISSUE TITLE
Catalog Product Gallery UpdateHandler class not extending CreateHandler correctly

### ISSUE THREAD

**Issue by SolsWebdesign** [magento/magento2#34814]
### Summary (*)
Currently the class UpdateHandler (agento\Catalog\Model\Product\Gallery\UpdateHandler.php) prevents developers from writing a preference for CreateHandler due to an incorrect extend of this class that happens to be in the same directory.

### Examples (*)
Let's say you would like to rewrite a function in CreateHandler and you have in your module a di.xml containing the following line of code:
`<preference for="Magento\Catalog\Model\Product\Gallery\CreateHandler" type="Vendor\ProductImporter\Model\Rewrite\Catalog\Model\Product\Gallery\CreateHandler" />`

You will find that Magento happily accepts your di.xml but never uses your preference. After some debugging you find that because UpdateHandler extends CreateHandler without listing it in its "use" list, UpdateHandler in fact instantiates CreateHandler before your preference. Hence it will never work and you can never write a preference for this class.

### Proposed solution
The proposed solutions is fairly straight forward 
`class UpdateHandler extends \Magento\Catalog\Model\Product\Gallery\CreateHandler`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @SolsWebdesign ,

Thank you for raising an issue , Kindly provide steps to reproduce , clear issue discerption, actual results ,expected results and screenshots.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @SolsWebdesign,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by valentin-debris** [comment]
Since this issue still exists (complains also here https://magento.stackexchange.com/questions/229407/magento-2-override-model-file) , you can use this patch to fix the file

```
diff --git a/Catalog/Model/Product/Gallery/UpdateHandler.php b/Catalog/Model/Product/Gallery/UpdateHandler.php
index edee9ae..5b8689b 100644
--- a/Catalog/Model/Product/Gallery/UpdateHandler.php
+++ b/Catalog/Model/Product/Gallery/UpdateHandler.php
@@ -26,7 +26,7 @@ use Magento\Store\Model\StoreManagerInterface;
  * @since 101.0.0
  * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
  */
-class UpdateHandler extends CreateHandler
+class UpdateHandler extends \Magento\Catalog\Model\Product\Gallery\CreateHandler
 {
     /**
      * @var AttributeValue

```
