### ISSUE TITLE
Magento 2 version 2.4.3-p1 “Page Builder was rendering for 5 seconds without releasing locks” error. 

### ISSUE THREAD

**Issue by ZephyrDogma** [magento/magento2#34898]
So friends im having an issue with saving my page at the pagebuilder:

Ubuntu 20.04 Magento Version 2.4.3-p1
So i attempt to create a new page(has same effect as i try to edit an existing one) and i add some elements to the page, afterwards i click save

It should have made the page successfully 

1.  And here i get the spinning wheel of death perpetually there and the error "Page Builder was rendering for 5 seconds without releasing locks." that was supposedly fixed in version 2.3.6 of magento

2. ![image](https://user-images.githubusercontent.com/77338971/147594439-1258074b-ad3d-4a41-a318-b70ac03ae35c.png)

### Additional Information
The issue was `data-content-type="heading"`. In 2.4.3p1 EE when I'm adding content from scratch then i don't see this attr getting added. But it was there in 2.3.2 EE. After removing this attribute from the page now it saves. I have removed that attribute from all pages using MySQL replace statement.

What you can try, is to add some content and include this

<h2 contenteditable="true" data-placeholder="Edit Heading Text" data-content-type="heading" data-appearance="default" data-element="main"><span data-pb-style="6235E010E29C8">NOS SOLUTIONS</span></h2>

You can edit any h2 tag and include data-content-type="heading" there directly in the DB, as normally there is no option to edit the text in the pagebuilder. And then try to save the page.

**Comment by ZephyrDogma** [comment]
@magento I am working on this

**Comment by engcom-Echo** [comment]
Hi @ZephyrDogma,

Thank you for reporting the issue.

However, I tried to replicate the same on Magento 2.4.3-p1 version but not facing any issue as you are having. Below screenshots of the same.

<img width="1433" alt="Screenshot 2021-12-29 at 6 51 32 PM" src="https://user-images.githubusercontent.com/51681435/147666757-02cb5980-9c10-4ada-b35c-dd01a75fe1e0.png">

<img width="1434" alt="Screenshot 2021-12-29 at 6 50 43 PM" src="https://user-images.githubusercontent.com/51681435/147666771-290ec757-aae3-429c-a592-aaf6db01f754.png">

As you can see, page is getting saved with any info I add in Page Builder. Based on it, can you please update if you upgraded from older versions which were having this issue or if you can provide more info on what you did differently that you are getting this issue ?

Thanks

**Comment by ZephyrDogma** [comment]
> Hi @ZephyrDogma,
> 
> Thank you for reporting the issue.
> 
> However, I tried to replicate the same on Magento 2.4.3-p1 version but not facing any issue as you are having. Below screenshots of the same.
> 
> <img alt="Screenshot 2021-12-29 at 6 51 32 PM" width="1433" src="https://user-images.githubusercontent.com/51681435/147666757-02cb5980-9c10-4ada-b35c-dd01a75fe1e0.png">
> 
> <img alt="Screenshot 2021-12-29 at 6 50 43 PM" width="1434" src="https://user-images.githubusercontent.com/51681435/147666771-290ec757-aae3-429c-a592-aaf6db01f754.png">
> 
> As you can see, page is getting saved with any info I add in Page Builder. Based on it, can you please update if you upgraded from older versions which were having this issue or if you can provide more info on what you did differently so that I can try to reproduce it again ?
> 
> Thanks

Hello friend i didnt update magento from older versions i just installed it from scracth on my ubuntu, if this would help i will post the rest of the console output after i press save
![image](https://user-images.githubusercontent.com/77338971/147676709-59008be9-fba2-405e-be1d-a76971f58448.png)

**Comment by engcom-Echo** [comment]
Hi @ZephyrDogma,

Thank you for providing with the console errors info but it is not helpful since I am not getting same errors. The issue was there before but as documentation said, it was fixed and I am not getting it in the same version 2.4.3-p1 as you suggested now. 

If you are getting it, there might be a set of steps through which I can also get the same. Can you please try with some other browser and check if you are still getting it ? If you can help me some more info, perhaps I'll be able to reproduce it.

Thanks

**Comment by janisverins** [comment]
Facing the same issue. Magento ver. 2.4.3-p1.

**Comment by Green2Matter** [comment]
@janisverins it's exactly same as I can see in my instance.

**Comment by miteshdhaduk** [comment]
Same issue on Magento ver. 2.4.3-p1. nothing to save from the backend where page builder exists.

**Comment by akkaweb** [comment]
I feel this issue keeps on propping up everywehere without a good solution.

**Comment by jayesh1712** [comment]
I face the same issue. Is there any update?

**Comment by engcom-November** [comment]
Verified this issue on Magento 2.4-develop branch but cannot able to reproduce the issue even after saving CMS page multiple times with page builder content (Rows, columns and elements added). Its recommended to verify the issues on Magento 2.4-develop branch as the issue might have got fixed and it the upcoming 2.4.x release having latest code base.
@ZephyrDogma , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/159850045-66f041fd-2392-4dda-9b88-307847154481.png)

Thank you.

**Comment by chazzs** [comment]
I am having this problem as well. however, this is only happening to me when i use an added "appearance" to the Banner component.  I followed documentation (https://devdocs.magento.com/page-builder/docs/content-types/extend/add-appearances.html) to add a new appearance.  i am able to select the appearance, and it renders correctly in the preview as well. when i go to save the CMS page, that is when the error happens.

If i reload the page and change the banner to one of the default appearances the save works fine.  I get the feeling that there is an important detail missing from the documentation.

**Comment by manhtranisobar** [comment]
This issue is happening for me when I edit a product with more Page Builder attributes (around 20)

**Comment by engcom-Hotel** [comment]
Hello @manhtranisobar,

Have you tried the solution given in [this comment](https://github.com/magento/magento2/issues/34898#issuecomment-1042906884). Let us know if this resolves your problem.

Thanks

**Comment by manhtranisobar** [comment]
Hi @engcom-Hotel 
I have not tried that solution because we are using Magento Cloud. But I think It is not solution because I am getting that JS console error message when edit CMS page but I still can save CMS page successfully. If It is solution, Magento Cloud should update that config as default.

**Comment by kingshukdeb** [comment]
Having the same issue on 2.4.3p1 EE. I have upgraded from 2.3.2 EE. Its really weird issue. For some page it gets saved properly. Sometime i see the error in console and the loader keeps loading and sometime the page saves without actually saving the data.

**Comment by agarcia2-pk** [comment]
I've encountered the same issue on 2.4.2-p2. It's weird because it happens on one specific page, i can edit others without problem but this specific one does not let me.

**Comment by engcom-Hotel** [comment]
Hello @kingshukdeb,

Thanks for the contribution!

We have tried this as well, and post the content something like below in page, but still we are not ablet to reproduce the issue:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/51681618/175926691-625b6bb7-00bb-48f9-ab8c-0265dd068054.png">

We request you to please provide the text in which you are facing the issue.

Thanks

**Comment by kingshukdeb** [comment]
@engcom-Hotel, Can you try to add that text in 2.3.2 EE and then upgrade to 2.4.3p1 EE and check if you can save the page.

**Comment by kingshukdeb** [comment]
@engcom-Hotel For me the issue was **_data-content-type="heading"_**. In 2.4.3p1 EE when i'm adding content from scratch then i dont see this attr getting added. But it was there in 2.3.2 EE. After removing this attribute from page now it saves. I have removed that attribute from all pages using mysql replace statement.

What you can try, is to add some content and include this

<h2 contenteditable="true" data-placeholder="Edit Heading Text" data-content-type="heading" data-appearance="default" data-element="main"><span data-pb-style="6235E010E29C8">NOS SOLUTIONS</span></h2>

You can edit any h2 tag and include data-content-type="heading" there directly in the db, as normally there is no option to edit text in the pagebuilder. And then try to save the page.

**Comment by engcom-Hotel** [comment]
Hello @kingshukdeb,

Thanks for the update!

The issue is reproducible for us by following the below steps:
1. Create a new Page from Admin Panel `Content -> Pages -> Add New Page`
2. After saving the newly created page, edit its content from the database in table `cms_page` column `content` and add the below H2 tag with the specified attributes:
```
<h2 contenteditable="true" data-placeholder="Edit Heading Text" data-content-type="heading" data-appearance="default" data-element="main"><span data-pb-style="6235E010E29C8">NOS SOLUTIONS</span></h2>
```
3. Refresh the page in Admin Panel.
4. Try to save the page

But if we remove `data-content-type="heading"` from the `H2` tag then the page is saving successfully. 

I have a query here, I haven't found any option to add that attribute `data-content-type="heading"` from the admin panel. In order to reproduce the issue, we need to edit the content from the database directly. So please help us understand how this attribute is saved previously there for you. 

Thanks

**Comment by kingshukdeb** [comment]
@engcom-Hotel Its coming from 2.3.2 EE. In that version when we edited pages it used to automatically add those attributes. Like for color it used to add like data-desktop-style="color: rgb(255, 255, 255); (the rgb can be diff for sure, its an example) but now if you add color it doesn't add data-desktop-style.

**Comment by engcom-Hotel** [comment]
Hello @kingshukdeb,

Thanks for the reply!

So the issue is related to the Magento upgrade. I am confirming this issue for further process.

Thanks

**Comment by allanmfx** [comment]
> I have the exact same issue in Ubuntu 20.04 with clean installation of magento 2.4.4 and nginx. This is my first installation of magento in localhost for developing a site so I have never seen a functional magento 2 working as it should in order to compare. What I can say is that whenever I try to add content to a product (new or existing) system hangs and I get the same error as described in the first post here. Can you please suggest a solution? I have been reading about it the last 2 days but I really cannot find a solution! Really frustrated as this is my first contact with magento and although I have setup all the system without any issues I hit the wall here and now I'm stack...
> 
> UPDATE!!: What solved my issue was adding the following line in my server configuration in nginx
> 
> ```
> add_header X-Frame-Options SAMEORIGIN always;
> ```
> 
> I am searching for a solution 2 days now and this was nowhere suggested in the internet. Hope it helps someone!

I've faced this issue so many times and it is always caused by this little tricky header. The problem is that the nginx.conf.sample that comes with Magento has this X-Frame-Options set to a correct value, so people got confused and think that the problem is caused by another thing. But they need to look at other nginx files, for example: If you set up SSL locally following some internet tutorials, there's a high chance of you having a file called ssl-params.conf, and inside this file there's the **add_header X-Frame-Options DENY;** that you need to remove.

**Comment by Jeffrey-H** [comment]
Recently I'm facing this same issue on a much used Magento environment. The problem appeared out of thin air. After adding the suggested headers, the problem still continues. I'm really frustrated since I can no longer edit any products or categories.

**Comment by jspoe** [comment]
Submitted a support ticket for a commerce client for this.

I asked them if they could add a more specific notice about what pagebuilder element has an error and should be fixed.
From support perspective, they could not deliver a fix or script to do this, but managed to get some information that might help someone.

The issue (besides the header) resides pagebuilder elements that were created pre 2.4.3
If there is 'illegal' nested HTML, this scenario is (also) happening.

I'll quote:

"I checked the provided database backup prior to the migration, I still saw invalid contents to those cms pages/blocks. Some contents have "data-content-type="text"" inside another "data-content-type="text"", and some have "data-content-type="heading" inside "data-content-type="text"" that are all invalid"

So this is invalid:

`<div data-content-type="text">
<div data-content-type="text">
</div>
</div>
`

`<div data-content-type="text">
<h2 data-content-type="heading"></h2>
</div>
`

The problem is that most of the shop owners will not be able to fix this, as they don't have the knowledge or access to the raw HTML to fix this themself.

**Comment by engcom-Hotel** [comment]
Hello @ZephyrDogma @kingshukdeb @jspoe ,

We have again tried to reproduce the issue in the latest Magento 2.4-develop branch and the issue is more able to reproducible. 

We have tried the below ways in order to reproduce the issue:

- By adding the below attribute in the `H2` tag:
`data-content-type="heading"`
- By adding the below content:
```
<div data-content-type="text">
	<div data-content-type="text">
	</div>
</div>
```
```
<div data-content-type="text">
<h2 data-content-type="heading"></h2>
</div>
```

It seems the issue has been fixed and merged with the latest development branch. I request you to please review it in the development branch.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @ZephyrDogma @kingshukdeb @jspoe,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by magejof** [comment]
please add some user permission on media gallery 
<img width="411" alt="Screenshot 2022-11-20 at 12 32 39 PM" src="https://user-images.githubusercontent.com/117264332/202895025-349d1dda-ecbc-46b2-a88d-5296ff2ea609.png">

**Comment by RobertSokolovSW** [comment]
Hello,

The solution by removing the `data-content-type="heading"` worked for me. However, now some of the CMS Page's content is not visible when editing in the Admin Panel, and if you hit 'save', the content is lost on the FE as well.

Magento version: 2.4.3-p3

Is there some other solution I could try?

Thanks!

**Comment by jspoe** [comment]
Hi @RobertSokolovSW 

Unfortunately, no other solution was provided yet, other than information about the fact that nested elements are invalid.
A colleague also found out that in some situations, column-group was also nested and found invalid in > 2.4.3-p3

I did opted in a Magento Commerce ticket that elements that are invalid should be highlighted in page builder itself or with an error-message of some kind, because indeed there is no way to tell from the pagebuilder perspective what elements are invalid. You can only tell and solve that by editing the raw HTML from the database. **_For the end-user, editing raw HTML in the database is not a solution_**.

So I think the solution for you at the moment is to extract the raw HTML from the database, edit it manually and place back the edited version. Elements should remain visible with removing the data-content-type="heading" property, I haven't seen problems there before.

**Comment by kamephis** [comment]
I've got a the same error in the console. In my case I was adding a link around the pagebuilder row and added the link option to the row component. You can enter an url, you can even save the row. But as soon you put something in the row, you can't save anymore and the spinner spins around and the pagebuilder 5s error is shown in the console.

**Comment by RobertSokolovSW** [comment]
Hello @kamephis 

I solved the problem with the help of this comment https://github.com/magento/magento2/issues/34898#issuecomment-1273092646

I made a patch to rename the nested elements in those cases and the problem is gone now.

**Comment by kingshukdeb** [comment]
Who are having trouble with this issue, its also because of our non ability to edit the html part of the editor. You can use this great module by Mark Shust to be able to do that if that helps.

https://github.com/markshust/magento2-module-pagebuildersourcecode

**Comment by kamephis** [comment]
@RobertSokolovSW I am having this problem in general. I just tried it with the FAQ example, after fixing the <render></render> bug the same issue appears when adding more than one FAQ item to the component (Magento 2.4.4 community).

**Comment by engcom-Hotel** [comment]
Hello @kamephis @kingshukdeb @RobertSokolovSW,

Please help us with the issue reproduction steps. So that we will analyze this issue more.

Thanks

**Comment by serzhik** [comment]
I'm experiencing same issue in 2.4.5-p1 Community version

**Comment by akartavtsev** [comment]
I fixed that issue with this patch:
`--- vendor/magento/module-page-builder/view/adminhtml/web/js/stage-builder.js	(date 1676459396611)
+++ vendor/magento/module-page-builder/view/adminhtml/web/js/stage-builder.js	(date 1676459396611)
@@ -49,9 +49,11 @@
       _.each(styles, function (stylesArray, selector) {
         var element = document.querySelector(selector);
 
-        _.each(stylesArray, function (style) {
-          element.setAttribute("data-" + name + "-style", element.getAttribute("data-" + name + "-style") ? element.getAttribute("data-" + name + "-style") + style.cssText : style.cssText);
-        });
+        if (element) 
+          _.each(stylesArray, function (style) {
+            element.setAttribute("data-" + name + "-style", element.getAttribute("data-" + name + "-style") ? element.getAttribute("data-" + name + "-style") + style.cssText : style.cssText);
+          });
+        }
       });
     });
 `

**Comment by akartavtsev** [comment]
I fixed that issue with this patch:

`--- vendor/magento/module-page-builder/view/adminhtml/web/js/stage-builder.js	(date 1676459396611)`
`+++ vendor/magento/module-page-builder/view/adminhtml/web/js/stage-builder.js	(date 1676459396611)`
`@@ -49,9 +49,11 @@`
`       _.each(styles, function (stylesArray, selector) {`
 `        var element = document.querySelector(selector);`
 
`-        _.each(stylesArray, function (style) {`
`-          element.setAttribute("data-" + name + "-style", element.getAttribute("data-" + name + "-style") ? element.getAttribute("data-" + name + "-style") + style.cssText : style.cssText);`
`-        });`
`+        if (element) `
`+          _.each(stylesArray, function (style) {`
`+            element.setAttribute("data-" + name + "-style", element.getAttribute("data-" + name + "-style") ? element.getAttribute("data-" + name + "-style") + style.cssText : style.cssText);`
`+          });`
`+        }`
`       });`
`     });`

**Comment by its24** [comment]
I have the same problem with page builder version Magento 2.4.5-p1. This solution doesn't work!!
`page-builder.js:96 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at PageBuilder.toggleFullScreen (page-builder.js:96:56)
    at events.js:85:26
    at Array.forEach (<anonymous>)
    at trigger (events.js:82:18)
    at Object.trigger (events.js:160:20)
    at Function.trigger (events.js:45:29)
    at target.trigger (events-mixin.js:25:32)
    at UiClass.toggleFullScreen (wysiwyg.js:169:20)
    at UiClass.pageBuilderEditButtonClick (wysiwyg.js:78:18)
    at HTMLButtonElement.<anonymous> (knockout.js:4669:74)`

**Comment by Asitis** [comment]
> Hello @kamephis @kingshukdeb @RobertSokolovSW,
> 
> Please help us with the issue reproduction steps. So that we will analyze this issue more.
> 
> Thanks

Let me try to expand on the issue. 

We have this problem as well (started on 2.2, still an issue on 2.4.5) on multiple installations when saving a category, which all of them have multiple custom added WYSIWYG fields. We've added these via a custom module according to the docs, and when they work, they work fine. However since we added them, 90% of the time the category cannot be saved because of this "Page Builder was rendering for 5 seconds without releasing locks.".

I've tried all manner of things, and sometimes I think I'm successful and the page saves, however, this seems to be rare occurrence because the next time it will still give the same error. All the patches / fixes / edits listed in all the many topics around this issue don't solve the problem.

And that is why it's so hard to fix it; I cannot recreate the problem 100% of the time. I do notice on pages where those multiple WYSIWYG fields are empty that the chances of it saving correctly are fastly increased, but if I try to save the same page 20 times, it will succeed once or twice.

This only happens on live servers, which are cached by Cloudflare. On my development server, I rarely if ever see this error. So I'm pretty sure the problem lies in the caching/priority of files rendered.

**Comment by its24** [comment]
I'm guessing the problem might be in the server settings. All servers have different settings, for example, with saving sessions.

**Comment by mnowakCode** [comment]
@RobertSokolovSW I think I have a similar problem in my project. When I change something in the page builder and save, sometimes the content isn't changed. This issue occurs only in the production mode.

**Comment by vovayatsyuk** [comment]
After the recent update of Google Chrome (Version 112.0.5615.165, private mode), this issue is reproducible in 100% of cases for me. CMS page is now saved for more than 20 seconds (always), or never gets saved (rarely).

1. Add row component
2. Add columns component
3. Add wysiwyg text to the first column
4. Add the image to the second column
5. Save the page. It will be saved but you have to wait.
6. Delete the image from the second column and save the page again. This time you have to wait even more.

<details markdown="1"><summary>View Screenshot</summary>

![image](https://user-images.githubusercontent.com/306080/234608324-77e75ef5-f5b7-4aca-ac10-5a82a6bd5d73.png)

</details>

**Comment by bartoszkubicki** [comment]
I can confirm what @vovayatsyuk says. I am using Chrome 112.0.5615.137 + Magento EE 2.4.5
Steps to reproduce:

1. Open category page
2. Add row in PB editor for description attribute and for example Text element.
3. Save
4. Remove PB elements from description
5. Save
6. Spinner of death and title error in console

**Comment by n0kit31** [comment]
There is official patch now that fix the issue https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-28/acsd-48857-unable-to-save-changes-after-editing-with-pagebuilder.html

**Comment by JonathanHelvey** [comment]
Hi just wanted to say. We did everything in this thread and we were still getting error. Even after adding the Magento2 Page Builder patch, we still got error. What we had to do was disable and set to NO `Enable Page Builder Content Preview`. The magento2 patch does work and does let us enable Page builder. However, you will still get error, even with the patch if 
Enable Page Builder Content Preview is enabled. Just wanted to give a heads up. 


So Add this patch  https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-28/acsd-48857-unable-to-save-changes-after-editing-with-pagebuilder.html and disable `Enable Page Builder Content Preview` and the error will go away.

**Comment by n0kit31** [comment]
Under Firefox works correctly as well. Issue is still in Chrome.

**Comment by VitaliyBoyko** [comment]
I've made some investigation. There is a problem with the initialization of PB.

https://github.com/magento/magento2/issues/25620#issuecomment-1540478599

**Comment by edward-simpson** [comment]
I find this happens on `2.4.3` when changing product attribute set.  A second Page Builder instance gets initialized for the product description, but on save, the form mixin checks for locks on both the old and the new instance - the old instance still seems to have locks against it, which don't resolve.

I've got a bit of an ugly patch which resolves it, it adds additional information (the attribute data scope) to the intialized Page Builder instance, which then gets checked against to see if an instance of page builder exists for an attribute (which then gets replaced instead of pushed onto the array) - although I don't recommend applying this patch without thorough testing


```
diff --git i/view/adminhtml/web/js/form/element/wysiwyg.js w/view/adminhtml/web/js/form/element/wysiwyg.j
s
index 2f68cde5..50e5c528 100644
--- i/view/adminhtml/web/js/form/element/wysiwyg.js
+++ w/view/adminhtml/web/js/form/element/wysiwyg.js
@@ -44,6 +44,13 @@ define([
         initialize: function () {
             this._super();

+            this.wysiwygConfigData({
+                ...this.wysiwygConfigData(),
+                customConfig: {
+                    dataScope: this.dataScope,
+                }
+            })
+
             if (!this.wysiwygConfigData()['pagebuilder_button'] ||
                 this.wysiwygConfigData()['pagebuilder_content_snapshot']) {
                 this.initPageBuilder();
diff --git i/view/adminhtml/web/js/form/form-mixin.js w/view/adminhtml/web/js/form/form-mixin.js
index 82d385e0..cd6aacca 100644
--- i/view/adminhtml/web/js/form/form-mixin.js
+++ w/view/adminhtml/web/js/form/form-mixin.js
@@ -26,7 +26,15 @@ define([

             events.on('pagebuilder:register', function (data) {
                 if (data.ns === self.ns) {
-                    self.pageBuilderInstances.push(data.instance);
+                    const existingInstanceIndex = self.pageBuilderInstances.findIndex(function (instance) {
+                        return !!instance.config.customConfig?.dataScope && !!data.instance.config.customConfig?.dataScope && instance.config.customConfig?.dataScope === data.instance.config.customConfig?.dataScope;
+                    })
+
+                    if (existingInstanceIndex !== -1) {
+                        self.pageBuilderInstances[existingInstanceIndex] = data.instance;
+                    } else {
+                        self.pageBuilderInstances.push(data.instance);
+                    }
                 }
             });

```

**Comment by gh-darvishani** [comment]
Google Chrome v 124 doesn't work but v 123 works
it seems it's a Chrome issue, not Magento ( I'm using Magento v 2.4.7)

**Comment by amiyoghoshstar** [comment]
Its still happening on Magento ver. 2.4.3-p1
Also, its seems like browser issue :(
