### ISSUE TITLE
GraphQL Schema becomes invalid if a custom `type` product attribute is defined.

### ISSUE THREAD

**Issue by barnard-b** [magento/magento2#34929]
### Preconditions (*)

1. Magento 2.4.3
2. A custom product attribute:
    - Attribute Code: `type`
    - Default Label: Type
    - Catalog Input Type for Store Owner: Dropdown
    - Values Required: No
    - Manage Options (Values of Your Attribute)
        - Art
        - Books
        - ...
    - Scope: Global
    - Unique Value: No
    - Add to Column Options: No
    - Use in Filter Options: No
    - Use in Search: Yes
    - Visible in Advanced Search: Yes
    - Comparable on Storefront: Yes
    - Use in Layered Navigation: Filterable (with results)
    - Use in Search Results Layered Navigation: Yes
    - Use for Promo Rule Conditions: No
    - Allow HTML Tags on Storefront: Yes
    - Visible on Catalog Pages on Storefront: Yes
    - Used in Product Listing: No
    - Used for Sorting in Product Listing: No

### Steps to reproduce (*)

1. Create a custom product attribute as described above in preconditions.
2. Clear the Magento configuration cache to remove the cached GraphQL schema.
3. Open the GraphQL endpoint with a tool that validates the schema like GrapiQL or Apollo Studio.

### Expected result (*)

1. The GraphQL schema is valid.

### Actual result (*)

1. The schema is invalid because the `type` attribute on products types has been overwritten with the custom `type` attribute.
<img width="987" alt="image" src="https://user-images.githubusercontent.com/44757473/148119743-d189630d-04d1-491f-ad12-c84d1fd1b52a.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by barnard-b** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @barnard-b,

Thank you for reporting the issue.

Can you please provide some more info on Point 1 of 'Steps to reproduce' ? Like what are the configurations you set for Attribute Code 'type' ? Bcoz a lot of it is dependent on your configurations which you did while creating new attribute. We'll try to reproduce accordingly.

Thanks

**Comment by barnard-b** [comment]
@engcom-Echo Attribute configuration has been added. Thanks.

**Comment by cpartica** [comment]
let me reiterate the problem here, as this this not a problem of system attributes collision but a schema stitching type collision based on dynamically generated schema originated from custom attributes:
1.`RoutableInterface` contains `type: UrlRewriteEntityTypeEnum`
2. `ProductInterface` inherits `RoutableInterface` and `RoutableInterface.type:UrlRewriteEntityTypeEnum`
3. ProductInterface injects dynamically and stitches a custom attribute named `type:Int`
4. Collision of schema stitching happens

The problem here is that we inject in the same namespace, "inline", all custom attributes increasing the chance of collision.
And now we do have an alternative, https://github.com/magento/magento2-pwa/blob/main/CatalogGraphQlAux/etc/schema.graphqls#L23

Is there still a need for inline custom attributes? if yes, and my guess is that we can read them through introspection without running a query and identify them by name directly - then we can move them to a new namespace part of 
```
interface ProductInterface {
  custom_attributes_list: 
}
```
or something like that - This new new "namespace: will reduce collisions

**Comment by engcom-November** [comment]
Hi @barnard-b ,
This issue got fixed in the scope of the internal Jira ticket `AC-2371` by the internal team
Related commits: https://github.com/magento-commerce/magento2ce/pull/7671/commits/12cbbe5574e012a118f8e3ea455c72474e5496ff
Based on Jira, target version is 2.4.5

**Comment by mustanguy69** [comment]
Hello is there any news on this ? I can't access the commit mentionned in previous comment ...

**Comment by tomhaire87** [comment]
I'm still seeing this same issue in 2.4.5-p1 and like above I can't see the commit

**Comment by mayur434** [comment]
Hi, I am facing this issue on Adobe Commerce Cloud project (_version: 2.4.6_), while Introspection Query validation.

Below is the reference screenshot of Graphql client which is highlighting the schema issue.

![image](https://github.com/magento/magento2/assets/35799734/45893a2f-4d2b-4379-831e-544b122fbc25)

**Comment by Shreepadha-Bhat** [comment]
I don't think this issue is resolved. I am still getting the same error
![Screenshot 2024-07-10 134718](https://github.com/magento/magento2/assets/121386585/64dc3cee-1e9e-4b56-987f-b42bc1159b59)

**Comment by alwinjoseph02** [comment]
Hi Team, 

Does this issue been really resolved? I can see this issue can be replicated  in 2.4.7-p3 too.
