### ISSUE TITLE
filter product collection by id on category page not working

### ISSUE THREAD

**Issue by support-smartebusiness** [magento/magento2#34974]
### Preconditions (*)
- Magento version - 2.4.3-p1 (enterprise) with sample data

### Steps to reproduce (*)
1. Create a custom module
2. Add Plugin which uses `Magento\Catalog\Model\ResourceModel\Product\Collection`
3. Add filter for the product which is not appeared on the first page, means it will appear on the >= 2 page of the category.
```
public function afterPrepareProductCollection(
        $layer,
              $result,
        Collection $collection
    ) {
        if (!$this->applied) {
            $collection->addAttributeToFilter('entity_id', ['in' => ['12', '14']]);
            $this->applied = true;
        }
        return $result;
    }
```
5. Try to access the category from frontend. For my case its `gear/bags.html`
6. Here only the product id `12` is showing but product id `14` is not visible:
![image](https://user-images.githubusercontent.com/51681618/162428895-d9574c22-72a2-46be-9d4c-bf970af34075.png)

### Expected result (*)

1. Only two products should show on `gear/bags.html` page

### Actual result (*)

1. Product related to first page is showing only.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment]
Hi @support-smartebusiness ,
adi smarte is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. May I  close this issue as community is not able to provide fix for it in this repository. 
All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page.Thank you.

**Comment by support-smartebusiness** [comment]
Hi,

the module **https://github.com/adiSmarte/filter-products** is not a third party module, its a code that can replicate the issue and all the code in **https://github.com/adiSmarte/filter-products/blob/master/Smart/Test/Plugin/Model/LayerPlugin.php** in doing is filter product collection by product id, and filtering product collection by id is a common practice and its broken in magento 2.4.3-p1.

Thanks

**Comment by engcom-Delta** [comment]
Hi @support-smartebusiness ,
We tried to reproduce the issue on magento 2.4 develop with provided module .Fortunately issue is reproducible .
<img width="1440" alt="Screenshot 2022-03-10 at 12 10 49 PM" src="https://user-images.githubusercontent.com/51681379/157604350-4fc1e7b6-8d5e-43d4-85f0-4eb75b822429.png">

Kindly suggest us how to replicate this issue without provided module?

Thanks

**Comment by support-smartebusiness** [comment]
Hi @engcom-Delta 

To replicate the issue

- filter product collection on category page by entity_id (product id) in a way that product ids used for filtering the collection are not in first page of the collection.
- Example here - https://github.com/adiSmarte/filter-products/blob/master/Smart/Test/Plugin/Model/LayerPlugin.php

Thanks

**Comment by engcom-Hotel** [comment]
Hello @support-smartebusiness,

Thanks for reporting this issue!

We have tried to reproduce the issue in Magento 2.4-develop branch via making a plugin on Product collection. The issue is reproducible for us.

Hence confirming the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @sdzhepa,

We have updated the main description.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @support-smartebusiness,

We have rechecked this and found that the issue is happening `after plugin` is added in the wrong place.

Before reaching prepareProductCollection() method, pagination is already set in the setCollection() method of \Magento\Catalog\Block\Product\ProductList\Toolbar . So this is why any changes in the pagination can’t work on the after plugin for prepareProductCollection(). Filtering must be performed earlier in the execution chain as per the above explanation.

Perhaps a more suitable solution for this implementation could be by using an observer. 

Thanks

**Comment by engcom-Hotel** [comment]
Dear @support-smartebusiness,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by adiSmarte** [comment]
this is still an issue, I don't think it should matter when a filter is added to the collection as long as it is added before the collection is loaded. So the explanation here (https://github.com/magento/magento2/issues/34974#issuecomment-1108161644) is not accurate. I've tried to add the filter before the pagination too and the collection result still does not contain the filtered products. I think it is due incorrect pagination data sent to elasticsearch.
