### ISSUE TITLE
Constant critical errors in system.log

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3507]
Critical errors constantly logged in var/log/system.log:

```
[2016-02-22 14:36:09] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-02-22 14:36:09] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-02-22 14:36:09] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
...
[2016-02-22 14:39:46] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-02-22 14:39:46] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-02-22 14:39:46] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-02-22 14:39:46] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-02-22 14:39:46] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-02-22 14:39:46] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
...
[2016-02-22 14:40:18] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
```

From what I can tell - it happens from both adminhtml and frontend.
Magento version 2.0.2 with default theme and pretty much default setup(except 3 store views and couple of products imported).

**Comment by vzaporozhets** [comment]
@werdlv, are you able to see frontend/admin while receiving such errors? Which OS is used?

**Comment by jsakars** [comment]
@vzaporozhets yes, both admin & front-end are accessible and seems to work fine in general. Ubuntu 14.04 is used along PHP7 and Nginx

**Comment by lutpiero** [comment]
```
[2016-04-09` 15:25:13] main.CRITICAL: Broken reference: the 'currency' element cannot be added as child to 'header.panel', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'header.links' element cannot be added as child to 'header.panel', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'catalog.leftnav' element cannot be added as child to 'sidebar.main', because the latter doesn't exist [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'currency' tries to reorder itself towards 'store_language', but their parents are different: 'header.panel' and '' respectively. [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and '' respectively. [] []
[2016-04-09 15:25:13] main.CRITICAL: Broken reference: the 'catalog.leftnav' tries to reorder itself towards '', but their parents are different: 'sidebar.main' and ''
```

I am experiencing same issue, as a result the main menu in frontend not showing up

**Comment by vzaporozhets** [comment]
@lutpiero I noticed the same issue when installed M2 on Windows using "localhost" in the base URL. Adding any alias with domain part (ex. "magento.local") to "hosts"-file resolve this issue and M2 works just fine. But do not forget to use this alias for the base URL while installing Magento.

@werdlv Can you tell a bit more about store views configuration?

**Comment by jsakars** [comment]
@vzaporozhets there is nothing specific about store views - `en`, `ru`, `lv` for example

**Comment by vzaporozhets** [comment]
@werdlv we can't reproduce this problem with 2.0.4 using the same environment. Can you please re-test this issue with latest version and report more details if it is still faced.

**Comment by anisagrebi** [comment]
[2016-05-07 08:11:14] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' tries to reorder itself towards '', but their parents are different: 'left' and '' respectively. [] []
[2016-05-07 08:11:14] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
[2016-05-07 08:11:14] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_56f1b068ec7ccf4878f9284dd1137afd1: Please correct the XML data and try again.  [] []
[2016-05-07 08:11:21] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_5c7461af04bb11fe209659d7147d2c579: Please correct the XML data and try again.  [] []
[2016-05-07 08:11:21] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_50a98983867a1770682b48d9a0ad63441: Please correct the XML data and try again.  [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.bottom' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.bottom' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-05-07 08:11:21] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' tries to reorder itself towards '', but their parents are different: 'right' and '' respectively. [] []

**Comment by adragus-inviqa** [comment]
@vzaporozhets - you're kidding, right? :)
I **always** get those. My logs are full of it. So much so that I've come to accept it as a feature. Unfortunately, I'm not looking at system.log anymore. Nothing _critical_ to see in there. Just a lot of noise.

**Comment by jsakars** [comment]
issue still persists

**Comment by medinadato** [comment]
Yes, the issue still persists. I've installed Magento 2.0.5 and the errors keep popping up. Pretty disappoint having an application with those kind of bugs out of the box. 

```
main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
```

**Comment by vzaporozhets** [comment]
@adragus-inviqa No, I'm not kidding :-) I checked logs of our environment with PHP7/nginx where 2.0.X has been tested and didn't find such messages. If Magento works and all layouts are fine - this is fail error reporting which need to be fixed. We just need to reproduce it - I'll keep you informed.

**Comment by springerin** [comment]
same errors with:
Server version: Apache/2.4.18 (Ubuntu) Server built:   2016-04-15T18:00:57
PHP 7.0.6-13+donate.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
Description:    Ubuntu 16.04 LTS  Release:  16.04 Codename: xenial

[2016-05-20 14:11:02] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-05-20 14:11:02] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-05-20 14:11:02] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2016-05-20 14:11:04] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
[2016-05-20 14:11:10] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-05-20 14:11:10] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-05-20 14:11:10] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []

**Comment by vkorotun** [comment]
Ok, guys. There is no bug here ) Really.
There are two reasons, why you all see such a logs.

Reason 1
People keep forgetting remove "before" and "after" attributes for blocks which have been moved to another parent, so those are no longer relevant. Internal ticket in progress MAGETWO-53410 and we will clean up legacy references soon.

Reason 2
As an example, let's take `<referenceContainer name="sidebar.additional">`
Such references mostly (if not all) reside in default.xml files (so will be applied to all pages without exclusions), while the container "sidebar.additional” is added by 2columns-left.xml layout only. So, on pages where different page layout is used, the reference will lead to nowhere, and you will see CRITICAL error logged (while it is not critical at all).

The tricky thing is that sometimes that could be a normal case and developer understands why it happens (if want to add a block to specific container to all pages on which target container available, and don’t need that block to be added to the pages where target container is not available).

Short excerpt from internal ticket description: "Stop logging such cases at all, or at least stop marking them as CRITICAL (ensure that it’s not logged in production mode). Also it will be helpful if logged message will say the URL of the page where target container is missed". 

So, as you see, we still think that logging such "broken" references is a right thing to do, since some of them are really could be caused by misspells in layout files.

**Comment by springerin** [comment]
definitively usefull having the url in order to investigate what is the real issue
thanks

**Comment by piotrekkaminski** [comment]
The issue is fixed internally and will be delivered in 2.1

**Comment by Crossmotion** [comment]
I just installed version 2.1. Issue is still very alive here. Also since the update the sidebar in the admin product edit page is gone.

Errors in System.log: 

[2016-06-29 13:51:00] main.CRITICAL: Broken reference: the 'product.reviews' element cannot be added as child to 'product_tabs', because the latter doesn't exist [] []
[2016-06-29 13:51:00] main.CRITICAL: Broken reference: the 'catalog.product.edit.tab.grouped.container' element cannot be added as child to 'product_tabs', because the latter doesn't exist [] []
[2016-06-29 13:51:00] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-06-29 13:51:00] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-06-29 13:51:00] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []

**Comment by ghost** [comment]
Error still exists for me. Even after 2.1 update.

**Comment by azeemism** [comment]
Still persists in version 2.1

**Production Mode:** Looks good

**Developer Mode:** Refreshed the home page once
var/log/systemlog

```
New version of deployed files: 1468354842 [] []
[2016-07-12 20:53:17] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2c7461af04bb11fe209659d7147d2c579 and handles default, cms_index_index, cms_page_view, cms_index_index_id_home: Please correct the XML data and try again.  [] []
[2016-07-12 20:53:17] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_20a98983867a1770682b48d9a0ad63441 and handles 1column: Please correct the XML data and try again.  [] []
[2016-07-12 20:53:17] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:17] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:17] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:17] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:17] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:17] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-07-12 20:53:18] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2cf9ab1b1723bedc1dcd665a812b00335 and handles admin-1column: Please correct the XML data and try again.  [] []
[2016-07-12 20:53:18] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:18] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:18] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:18] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-12 20:53:18] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
```

debug.log

```
[2016-07-12 20:45:53] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2016-07-12 20:45:55] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"servers":["[object] (Zend\\Uri\\Uri: http://127.0.0.1:6018/)"],"tagsPattern":".*"},"is_exception":false} []
[2016-07-12 20:53:15] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://example.com/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
```

Other links on the home page have the same issue.

Note: Varnish is setup on 127.0.0.1:6018

**Comment by frameworkerrs** [comment]
**hi im facing problem with magento 2.1.1 with below.**

```
[2016-10-05 19:02:33] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_46f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-10-05 19:02:58] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_49779d713e3fbb1543956771d12cf7164 and handles default, checkout_index_index: Please correct the XML data and try again.  [] []
[2016-10-05 19:02:59] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_40a98983867a1770682b48d9a0ad63441 and handles 1column: Please correct the XML data and try again.  [] []
[2016-10-05 19:02:59] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-05 19:02:59] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-05 19:02:59] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-05 19:02:59] main.CRITICAL: Broken reference: the 'currency' tries to reorder itself towards 'store_language', but their parents are different: 'header.panel' and 'porto_header' respectively. [] []
[2016-10-05 19:02:59] main.CRITICAL: Broken reference: the 'catalog.compare.link' tries to reorder itself towards 'top.links', but their parents are different: 'header.links' and 'header.panel' respectively. [] []
[2016-10-05 19:03:04] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_46f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
```

**can anybody give some idea.. due to this .. my checkout page went empty**

**Comment by jvreeken** [comment]
I'm having a simillar problem, the cart page suddenly is blank except for:
    Item    Price   Qty Subtotal
Logs shows:
[2016-10-05 21:29:23] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_58b339880b77f9b5253e900377b8d0e64 and handles default, catalog_category_view, catalog_category_view_type_layered, catalog_category_view_id_83, catalog_category_view_layout_update_d41d8cd98f00b204e9800998ecf8427e: Please correct the XML data and try again.  [] []
[2016-10-05 21:29:23] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_5a7ccd8094436548b564a588f6303121c and handles 2columns-left: Please correct the XML data and try again.  [] []
[2016-10-05 21:29:23] main.CRITICAL: Broken reference: the 'storepickup-header-link' element cannot be added as child to 'header.links', because the latter doesn't exist [] []
[2016-10-05 21:29:23] main.CRITICAL: Broken reference: the 'search-term-popular-link' element cannot be added as child to 'footer_links', because the latter doesn't exist [] []
[2016-10-05 21:29:23] main.CRITICAL: Broken reference: the 'contact-us-link' element cannot be added as child to 'footer_links', because the latter doesn't exist [] []
[2016-10-05 21:29:23] main.CRITICAL: Broken reference: the 'minicart' tries to reorder itself towards 'logo', but their parents are different: 'header-wrapper' and 'header' respectively. [] []
[2016-10-05 21:29:23] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_56f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []

**Comment by frameworkerrs** [comment]
Hi, I'm trying to solve this. But I'm not sure, is this related to
knockoutjs or XML layout.

Sometimes knockoutjs also breakup the sites.

I will inform once solved..

**Comment by attiquer** [comment]
Same issue, don't know why it's marked as closed when so many people are having the issue

`[2016-10-12 13:41:22] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_391fccd54da687afc76a5d6559b714906 and handles default, adminhtml_dashboard_index: Please correct the XML data and try again.  [] []
[2016-10-12 13:41:22] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3cf9ab1b1723bedc1dcd665a812b00335 and handles admin-1column: Please correct the XML data and try again.  [] []
[2016-10-12 13:41:22] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-10-12 13:41:22] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-10-12 13:41:22] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2016-10-12 13:41:22] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_36f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []`

**Comment by mohsinrasool** [comment]
I have the same issue. Tried several methods, none worked yet. I am using Magento 2.1.1 with sample data on Windows 7

```
[2016-10-18 09:42:19] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_29779d713e3fbb1543956771d12cf7164 and handles default, checkout_index_index: Please correct the XML data and try again.  [] []
[2016-10-18 09:42:19] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2177627f91af678a9b03e993f1a91917f and handles checkout: Please correct the XML data and try again.  [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'header.panel.wrapper' element cannot be added as child to 'header.container', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'header-wrapper' element cannot be added as child to 'header.container', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'navigation.sections' element cannot be added as child to 'page.top', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'top.container' element cannot be added as child to 'page.top', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'breadcrumbs' element cannot be added as child to 'page.top', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'footer' element cannot be added as child to 'footer-container', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'header.panel.wrapper' tries to reorder itself towards '', but their parents are different: 'header.container' and '' respectively. [] []
[2016-10-18 09:42:19] main.CRITICAL: Broken reference: the 'navigation.sections' tries to reorder itself towards '', but their parents are different: 'page.top' and '' respectively. [] []
[2016-10-18 09:42:19] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-10-18 09:46:13] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-10-18 09:46:13] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-10-18 09:46:13] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
```

**Comment by cizgidekiadam** [comment]
Same issue with 2.1.2

<pre>
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product-sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product.info.top' tries to reorder itself towards 'page.main.title', but their parents are different: 'product.info.main' and 'columns.top' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product.info.price' tries to reorder itself towards 'page.main.title', but their parents are different: 'product.info.top' and 'columns.top' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product.info.general' tries to reorder itself towards 'product.info.addtocart', but their parents are different: 'product.info.main' and 'product.info.form.content' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product.info.sku' tries to reorder itself towards 'product.info.type', but their parents are different: 'product.info.general' and 'product.info.stock.sku' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product.price.tier' tries to reorder itself towards 'product.info.price', but their parents are different: 'product.info.main' and 'product.info.top' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product.info.social' tries to reorder itself towards 'product.info.overview', but their parents are different: 'product.info.extrahint' and 'product.info.main' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'view.addto.wishlist' tries to reorder itself towards 'view.addto.requisition', but their parents are different: 'product.info.addto' and '' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'detail.bottom' tries to reorder itself towards 'product-info-main', but their parents are different: 'product.view.container' and '' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'product.info.details' tries to reorder itself towards 'product.info.media', but their parents are different: 'detail.bottom' and 'product.view.container' respectively. [] []
[2016-10-18 05:08:22] main.CRITICAL: Broken reference: the 'bml.right.logo' tries to reorder itself towards 'product.info.addtocart.paypal', but their parents are different: 'product.info.addtocart' and '' respectively. [] []
.....
....
...
..
[2016-10-18 05:08:32] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 05:08:32] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 05:08:32] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-10-18 05:08:32] main.CRITICAL: Broken reference: the 'product-sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
</pre>

**Comment by Ctucker9233** [comment]
@mohsinrasool @rbostan have you tried removing the entire vendor folder and then reloading a clean vendor folder from your magento version? Worked for me.

**Comment by eldonbite** [comment]
Using 2.1.0 before and encountered this. Upgraded to 2.1.2 and still experiencing this error.

```
[2016-11-02 06:32:44] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_5c6690f29cb80c2b881a7311e8632bc3e and handles 2columns-right: Please correct the XML data and try again.  [] []
[2016-11-02 06:32:44] main.CRITICAL: Broken reference: the 'minicart' tries to reorder itself towards 'logo', but their parents are different: 'header-wrapper' and 'header.panel' respectively. [] []
[2016-11-02 06:32:44] main.CRITICAL: Broken reference: the 'rewards-link' tries to reorder itself towards 'signout.link', but their parents are different: 'top.links' and 'header.links' respectively. [] []
[2016-11-02 06:32:44] main.CRITICAL: Broken reference: the 'store_language_desktop' tries to reorder itself towards 'top.search', but their parents are different: 'top.mini.links' and 'header-wrapper' respectively. [] []
[2016-11-02 06:32:44] main.CRITICAL: Broken reference: the 'store_currency_desktop' tries to reorder itself towards 'top.search', but their parents are different: 'top.mini.links' and 'header-wrapper' respectively. [] []
[2016-11-02 06:32:44] main.CRITICAL: Broken reference: the 'top.mini.links' tries to reorder itself towards 'minicart', but their parents are different: 'header.panel' and 'header-wrapper' respectively. [] []
[2016-11-02 06:32:44] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_56f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
```

It causes Error 500s on initial page load but gets displayed on subsequent reloads. This is probably the reason why we also keep on getting Error 500s whenever we enable Varnish.

**Comment by pantaoran** [comment]
I also have always had this problem, since the very beginning, now using Magento 2.1.0.
We have learned over time to ignore these, but it's a lot of logging noise and very annoying.

**Comment by luongduy** [comment]
I'm having the same problem when accessing the Url corresponding to the following layout file (an empty one) (Magento 2.1.2):

```
<!-- File: app/code/AVendor/ModuleName/view/frontend/layout/gateway_search_amazon.xml -->
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">

</page>
```

system.log: 

```
[2016-11-08 20:11:11] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2b91f14814c5d97a52a9d21b9dc6d5951 and handles default, gateway_search_amazon: Please correct the XML data and try again.  [] []
[2016-11-08 20:11:11] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2cf9ab1b1723bedc1dcd665a812b00335 and handles admin-1column: Please correct the XML data and try again.  [] []
[2016-11-08 20:11:11] main.CRITICAL: Broken reference: the 'header.panel.wrapper' element cannot be added as child to 'header.container', because the latter doesn't exist [] []
[2016-11-08 20:11:11] main.CRITICAL: Broken reference: the 'head.components' element cannot be added as child to 'after.body.start', because the latter doesn't exist [] []
[2016-11-08 20:11:11] main.CRITICAL: Broken reference: the 'requirejs-config' element cannot be added as child to 'after.body.start', because the latter doesn't exist [] []
[2016-11-08 20:11:11] main.CRITICAL: Broken reference: the 'translate-config' element cannot be added as child to 'after.body.start', because the latter doesn't exist [] []
[2016-11-08 20:11:11] main.CRITICAL: Broken reference: the 'translate' element cannot be added as child to 'after.body.start', because the latter doesn't exist [] []
[2016-11-08 20:11:11] main.CRITICAL: Broken reference: the 'js_cookies' element cannot be added as child to 'after.body.start', because the latter doesn't exist [] []
```

**Comment by marcobax** [comment]
This problem still exists, it's flooding the system logs.

**Comment by Morgon** [comment]
@piotrekkaminski - Please re-open this; it's still a pervasive problem for a large number of users (including every one of my client instances)

**Comment by KalaiarasanSeetharaman** [comment]
I also have same issue in Magento 2.0.6 in production mode . 
[2016-11-24 16:54:31] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_56d8767dd4262d264658fca15bbee81f9: Please correct the XML data and try again.  [] []
[2016-11-24 16:54:31] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_50a98983867a1770682b48d9a0ad63441: Please correct the XML data and try again.  [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'brand.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'social.login.customer.links' element cannot be added as child to 'customer.login.container', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'social.facebook.page.plugin' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'storelocator' element cannot be added as child to 'header.links', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'pslogin.theme.html.header.photo' element cannot be added as child to 'header.links', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'search-term-popular-link' element cannot be added as child to 'footer_links', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'contact-us-link' element cannot be added as child to 'footer_links', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'social.login.customer.links' tries to reorder itself towards '', but their parents are different: 'customer.login.container' and '' respectively. [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'social.facebook.page.plugin' tries to reorder itself towards '', but their parents are different: 'sidebar.additional' and '' respectively. [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'minicart' tries to reorder itself towards 'logo', but their parents are different: 'header-wrapper' and 'header' respectively. [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'pslogin.theme.html.header.photo' tries to reorder itself towards 'customer', but their parents are different: 'header.links' and '' respectively. [] []
[2016-11-24 16:54:31] main.CRITICAL: Broken reference: the 'currency' tries to reorder itself towards 'store_language', but their parents are different: 'store_language' and 'header' respectively. [] []
[2016-11-24 16:54:31] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_56f1b068ec7ccf4878f9284dd1137afd1: Please correct the XML data and try again.  [] []

**Comment by ksiamro** [comment]
Same problem with Magento 2.1.1

```
[2016-11-29 14:52:46] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2a7ccd8094436548b564a588f6303121c and handles 2columns-left: Please correct the XML data and try again.  [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.bottom' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.bottom' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'customer.form.login.popup' element cannot be added as child to 'side.navbar.popup.login', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'customer.form.register.popup' element cannot be added as child to 'side.navbar.popup.login', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.catalog.sidebar.right.top' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.catalog.sidebar.right.bottom' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.catalog.sidebar.left.top' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.catalog.sidebar.left.bottom' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' tries to reorder itself towards '', but their parents are different: 'right' and '' respectively. [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' tries to reorder itself towards '', but their parents are different: 'left' and '' respectively. [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.catalog.sidebar.right.top' tries to reorder itself towards '', but their parents are different: 'right' and '' respectively. [] []
[2016-11-29 14:52:46] main.CRITICAL: Broken reference: the 'bannerslider.catalog.sidebar.left.top' tries to reorder itself towards '', but their parents are different: 'left' and '' respectively. [] []
[2016-11-29 14:52:46] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-11-29 14:53:06] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2c7461af04bb11fe209659d7147d2c579 and handles default, cms_index_index, cms_page_view, cms_index_index_id_home: Please correct the XML data and try again.  [] []
[2016-11-29 14:53:06] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_20a98983867a1770682b48d9a0ad63441 and handles 1column: Please correct the XML data and try again.  [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.bottom' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.bottom' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'customer.form.login.popup' element cannot be added as child to 'side.navbar.popup.login', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'customer.form.register.popup' element cannot be added as child to 'side.navbar.popup.login', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' tries to reorder itself towards '', but their parents are different: 'right' and '' respectively. [] []
[2016-11-29 14:53:06] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' tries to reorder itself towards '', but their parents are different: 'left' and '' respectively. [] []
[2016-11-29 14:53:07] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-11-29 14:54:00] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2d41d8cd98f00b204e9800998ecf8427e and handles : Please correct the XML data and try again.  [] []
[2016-11-29 15:03:34] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2c7461af04bb11fe209659d7147d2c579 and handles default, cms_index_index, cms_page_view, cms_index_index_id_home: Please correct the XML data and try again.  [] []
[2016-11-29 15:03:34] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_20a98983867a1770682b48d9a0ad63441 and handles 1column: Please correct the XML data and try again.  [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.bottom' element cannot be added as child to 'right', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.bottom' element cannot be added as child to 'left', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'customer.form.login.popup' element cannot be added as child to 'side.navbar.popup.login', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'customer.form.register.popup' element cannot be added as child to 'side.navbar.popup.login', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.right.top' tries to reorder itself towards '', but their parents are different: 'right' and '' respectively. [] []
[2016-11-29 15:03:34] main.CRITICAL: Broken reference: the 'bannerslider.sidebar.left.top' tries to reorder itself towards '', but their parents are different: 'left' and '' respectively. [] []
[2016-11-29 15:03:35] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-11-29 15:03:39] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2a69fc3348bccf3161d216e06e4a724cc and handles default, catalog_category_view, catalog_category_view_type_layered, catalog_category_view_id_3: Please correct the XML data and try again.  [] []

```


My homepage is empty. Other pages works 'fine'.

**Comment by mattcoz** [comment]
Please reopen, it is obviously not fixed.

**Comment by converge** [comment]
My installation is broken because of this issue. Can't advance in the shopping process.

**Comment by ksiamro** [comment]
Still:

```
[2016-11-30 15:38:16] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3d41d8cd98f00b204e9800998ecf8427e and handles : Please correct the XML data and try again.  [] []
[2016-11-30 16:03:31] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2c7461af04bb11fe209659d7147d2c579 and handles default, cms_index_index, cms_page_view, cms_index_index_id_home: Please correct the XML data and try again.  [] []
[2016-11-30 16:03:31] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_20a98983867a1770682b48d9a0ad63441 and handles 1column: Please correct the XML data and try again.  [] []
[2016-11-30 16:03:31] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-30 16:03:31] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-30 16:03:31] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-30 16:03:31] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-30 16:03:31] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-11-30 16:03:33] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-12-01 00:35:30] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2c7461af04bb11fe209659d7147d2c579 and handles default, cms_index_index, cms_page_view, cms_index_index_id_home: Please correct the XML data and try again.  [] []
[2016-12-01 00:35:30] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_20a98983867a1770682b48d9a0ad63441 and handles 1column: Please correct the XML data and try again.  [] []
[2016-12-01 00:35:30] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 00:35:30] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 00:35:30] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 00:35:30] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 00:35:30] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 00:35:31] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
[2016-12-01 01:11:38] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_2c7461af04bb11fe209659d7147d2c579 and handles default, cms_index_index, cms_page_view, cms_index_index_id_home: Please correct the XML data and try again.  [] []
[2016-12-01 01:11:38] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_20a98983867a1770682b48d9a0ad63441 and handles 1column: Please correct the XML data and try again.  [] []
[2016-12-01 01:11:38] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 01:11:38] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 01:11:38] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 01:11:38] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 01:11:38] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-12-01 01:11:39] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_26f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.  [] []
```


Should we open new issue? 
Magento v 2.1.2

**Comment by PascalBrouwers** [comment]
@ksiamro sure. The only other threads I could find are: https://github.com/magento/magento2/issues/3900 (closed, status that it's fixed in 2.1 but obviously it's not) and https://github.com/magento/magento2/issues/6399 (open, but pretty old)

**Comment by jmellon** [comment]
2.1.2 Install,  having this issue too.   I can create static blocks but not CMS pages.

**Comment by zamson** [comment]
2.1.2, same here.

`[2017-01-02 13:52:14] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-01-02 13:52:14] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-01-02 13:52:14] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2017-01-02 13:54:14] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-01-02 13:54:14] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-01-02 13:54:14] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []`

**Comment by nbennett25** [comment]
2.1.3, unable to load admin page content with the layout 'admin-2columns-left':

`[2017-01-03 16:20:59] report.CRITICAL: Broken reference: the '[layout element name]' element cannot be added as child to 'left', because the latter doesn't exist [] []`

**Comment by peterjaap** [comment]
2.1.4, still here.

**Comment by maksek** [comment]
Reopened for review.

**Comment by thdoan** [comment]
I'm getting this in v2.1.2 developer mode.

var/log/support_report.log:
```
[2017-02-14 03:08:44] report.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE0_5174f85fdde1ae62ce661cc88639b20f3 and handles default, catalog_product_edit, catalog_product_configurable: Please correct the XML data and try again. complex type 'handleType', attribute 'base': The QName value 'layoutType' does not resolve to a(n) simple type definition.
Line: 47
 [] []
[2017-02-14 03:08:44] report.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE0_5cf9ab1b1723bedc1dcd665a812b00335 and handles admin-1column: Please correct the XML data and try again. complex type 'handleType', attribute 'base': The QName value 'layoutType' does not resolve to a(n) simple type definition.
Line: 47
 [] []
[2017-02-14 03:08:44] report.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-02-14 03:08:44] report.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-02-14 03:08:44] report.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2017-02-14 03:08:44] report.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE0_56f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again. complex type 'handleType', attribute 'base': The QName value 'layoutType' does not resolve to a(n) simple type definition.
Line: 47
 [] []
```

> @vzaporozhets yes, both admin & front-end are accessible and seems to work fine in general.

Unlike for @vzaporozhets, this _is_ causing an issue for me in Admin -- I'm not able to edit any products. When loading the product in Admin, I get a vague "Attention Something went wrong" error, which prevents me from saving any changes. I have a feeling the critical errors reported in `support_report.log` are somehow related to the "Attention Something went wrong" error in Admin (only on the edit product page from what I could see) because we have another dev environment that does not have this Admin issue, and that environment also has no such critical errors in `support_report.log`.

**Comment by Morgon** [comment]
@thdoan - Actually, do you have Profiling enabled in this affected dev environment? I've noticed that the 'Something went wrong' happens with Admin AJAX requests when Profiling is enabled. A related issue is being tracked in #7068

**Comment by astorm** [comment]
It's worth noting that there are two distinct problems here.   The first: Magento ships with code that triggers these `CRITICAL` log messages.  I just installed Magento CE 2.1.4 via the composer `create-project` method, turned on developed mode, and when I load and then refresh the admin page, I get the following in my logs

    [2017-02-14 16:59:25] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
    [2017-02-14 16:59:25] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
    [2017-02-14 16:59:25] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []

Magento shouldn't ship with code that drop critical warnings in the logs immediately after a fresh install with no third party extensions. 

The second problem here is third party code that introduces layout rules that cause similar problems.  Some of the previous comments in this thread send the message that since Magento 
Inc. can't control what other people do, that this isn't worth pursuing.  While that's certainly a problem, until Magento fixes the initial problem (the default themes ship with layout rules that trigger these error), third party developers will have zero incentive to fix these problems in their own module.  That's probably where the initial effort should go. 

It would also be nice if people could tell folks like @thdoan that the problem they're seeing in the admin console is probably **not** related to these specific errors, but instead related to something else that may not be logged.  Also also, fixing the problem with the dirty logs means folks like @thdoan will have clean logs and be less likely to attribute an unrelated admin error to problems with the structure of their layout handle XML files. 

/cc @maksek @piotrekkaminski

**Comment by pguedesbr** [comment]
Great answer,  @astorm !
Long story short, this issue should've  been marked as acknowledged long time ago by Magento team.

**Comment by thdoan** [comment]
Thanks @astorm , glad to know they're not related. For the record, I'm only seeing the admin issue when I go to edit a product, nowhere else, and it does NOT help that Magento's error message is so nondescript.

**Comment by cscd98** [comment]
I totally agree, these messages should have been fixed a long time ago. Get it fixed Magento. It's over 1 year since release!

**Comment by orlangur** [comment]
Viable implementation approach is described [here](https://github.com/magento/magento2/issues/5627#issuecomment-279440749). #5627 could be closed in favor of this one with proper linking of MAGETWO-42812.

**Comment by pantaoran** [comment]
Please get this fixed! It's very difficult to detect real problems in the logs when it's spammed with things that can be ignored. @astorm is absolutely right, how can Magento report many CRITICAL errors right out of the box after a fresh install?

**Comment by PaulodoPorto** [comment]
Ver: 2.1.5 - Win 7, Apache 2.4,  PHP 7.0.16,  MySQL 5.7.17 

Today 18:02 06.03.2017,  I´m facing the same Issue of you, now i´m going to Magento Forum to see what the guys says:

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the global.search tries to reorder itself towards logo, but their parents are different: 'header' and '' respectively. [] []`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'user' tries to reorder itself towards '', but their parents are different: 'header' and '' respectively. [] []`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'page.actions.toolbar' tries to reorder itself towards '', but their parents are different: 'page.main.actions' and '' respectively. [] []
`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'system_messages' tries to reorder itself towards '', but their parents are different: 'notifications' and '' respectively. [] []
`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'unread_system_messages' tries to reorder itself towards 'system_messages', but their parents are different: 'notifications' and '' respectively. [] []
`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header' and '' respectively. [] []
`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'header.inner.left' tries to reorder itself towards '', but their parents are different: 'header' and '' respectively. [] []
`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'header.inner.right' tries to reorder itself towards 'header.inner.left', but their parents are different: 'header' and '' respectively. [] []
`

`[2017-03-06 16:27:43] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and '' respectively. [] []
`

`[2017-03-06 16:28:06] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_391fccd54da687afc76a5d6559b714906 and handles default, adminhtml_dashboard_index: Please correct the XML data and try again.  [] []
`

`[2017-03-06 16:28:06] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
`

`[2017-03-06 16:28:06] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
`

`[2017-03-06 16:28:06] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
`

`[2017-03-06 16:28:16] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3e6fe115ba31d500509103893a62701cf and handles default, catalog_product_index: Please correct the XML data and try again.  [] []
`

`[2017-03-06 16:28:16] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
`

`[2017-03-06 16:28:16] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
`

`[2017-03-06 16:28:16] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
`

**Comment by haitaoseven** [comment]
me too .. can anybody know how to fix this problem ?

**Comment by orlangur** [comment]
@PaulodoPorto @haitaoseven 
**TL;DR:** these log entries are not that critical in fact and are present even in vanilla Magento installation without any customizations. Thus they do not mean anything works wrong in your store.

Proper implementation approach to fix this problem is described here: https://github.com/magento/magento2/issues/5627#issuecomment-279440749

This is something that should be fixed on Magento Team side, or at least enforced on CI as I described and then announced as `'up for grabs'`. I did not try to fix by myself but I doubt that simple patch eliminating all such problems even exist, most of the problems are caused by wrong layout XML files.

**Comment by PaulodoPorto** [comment]
@orlangur Thank you for your approach! About the your implementation.

1° step: activate this mechanism on CI, what signify CI please, it´s a folder or a specific file?
2° step: eliminate all critical errors! from the var/log/system.log ?
Where should i deploy this block of code that you suggest on #5627 ?

thank you in advance.

The terrible point is: I have no access to Produts > Catalog and Stores > Configuration on Admin Panel...the long error page is here.
Ver.2.1.5
Developer Mode

**Comment by orlangur** [comment]
@PaulodoPorto for integration tests you can simply change severity here: https://github.com/magento/magento2/blob/develop/dev/tests/integration/phpunit.xml.dist#L67 For instance, to see only critical errors first and then eliminating less and less important issues step-by-step.

Approach I described is just to not have `system.log` polluted in case of vanilla Magento installation, so that you can spot real issue. But in vanilla installation log is full of errors but there are no (I hope) critical issues which could be observed in Admin UI or storefront.

In your case I don't think searching for details in log could be helpful. Just enable developer mode, `error_reporting` and `display_errors` at maximum level and look into what kind of fatal error you face with.

> the long error page is here

Please show stack trace (better report separate issue as it does not seem to be related to the problem with littered log).

**Comment by Ctucker9233** [comment]
@magento-team Please take a look at this. It creates bloated system logs and creates so much noise it's impossible to tell what are real errors and which ones are not.

**Comment by NLightenedNL** [comment]
The same here: Magento 2.1.5

![error-log](https://cloud.githubusercontent.com/assets/26542784/24352568/6dfb5d76-12ea-11e7-94cb-f5ad3b3ece75.JPG)

**Comment by ghost** [comment]
Same issue with Magento 2.1.5

system.log
`[2017-03-29 12:05:38] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_36f1b068ec7ccf4878f9284dd1137afd1 and handles catalog_product_prices: Please correct the XML data and try again.`

debug.log
`[2017-03-29 12:37:02] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://sndev.calapo.at/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []`

**Comment by atomixstar** [comment]
Same issue with Magento 2.1.5, checkout page is broken when add a product with Text Swatch attribute and I do not know if is related to this, I am trying to clear all errors to found the issue:

```
[2017-03-29 14:30:52] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_6d41d8cd98f00b204e9800998ecf8427e and handles : Please correct the XML data and try again.  [] []
[2017-03-29 14:30:53] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_6d41d8cd98f00b204e9800998ecf8427e and handles : Please correct the XML data and try again.  [] []
[2017-03-29 14:30:56] main.CRITICAL: Broken reference: the 'div.sidebar.main' tries to reorder itself towards 'main', but their parents are different: 'columns' and 'columns-left' respectively. [] []
[2017-03-29 14:36:47] main.CRITICAL: Broken reference: the 'div.sidebar.main' tries to reorder itself towards 'main', but their parents are different: 'columns' and '1column' respectively. [] []
[2017-03-29 14:36:47] main.CRITICAL: Broken reference: the 'homepageslider' tries to reorder itself towards 'page.top', but their parents are different: 'col.home.slider' and 'page.wrapper' respectively. [] []
[2017-03-29 14:36:47] main.CRITICAL: Broken reference: the 'content.top.home' tries to reorder itself towards 'content', but their parents are different: 'page.top' and 'main' respectively. [] []
[2017-03-29 14:37:42] main.CRITICAL: Broken reference: the 'div.sidebar.main' tries to reorder itself towards 'main', but their parents are different: 'columns' and '1column' respectively. [] []
[2017-03-29 14:38:53] main.CRITICAL: Broken reference: the 'div.sidebar.main' tries to reorder itself towards 'main', but their parents are different: 'columns' and '1column' respectively. [] []
[2017-03-29 14:38:53] main.CRITICAL: Broken reference: the 'homepageslider' tries to reorder itself towards 'page.top', but their parents are different: 'col.home.slider' and 'page.wrapper' respectively. [] []
[2017-03-29 14:38:53] main.CRITICAL: Broken reference: the 'content.top.home' tries to reorder itself towards 'content', but their parents are different: 'page.top' and 'main' respectively. [] []
[2017-03-29 14:39:55] main.CRITICAL: Broken reference: the 'div.sidebar.main' tries to reorder itself towards 'main', but their parents are different: 'columns' and 'columns-left' respectively. [] []
[2017-03-29 14:40:03] main.CRITICAL: Broken reference: the 'div.sidebar.main' tries to reorder itself towards 'main', but their parents are different: 'columns' and '1column' respectively. [] []
[2017-03-29 14:40:18] main.CRITICAL: Broken reference: the 'checkout.cart.item.renderers.gift-card.actions.gift_options' element cannot be added as child to 'checkout.cart.item.renderers.gift-card.actions', because the latter doesn't exist [] []
[2017-03-29 14:40:18] main.CRITICAL: Broken reference: the 'div.sidebar.main' tries to reorder itself towards 'main', but their parents are different: 'columns' and '1column' respectively. [] []
[2017-03-29 14:40:18] main.CRITICAL: Broken reference: the 'checkout.cart.item.renderers.gift-card.actions.gift_options' tries to reorder itself towards '', but their parents are different: 'checkout.cart.item.renderers.gift-card.actions' and '' respectively. [] []
```

**Comment by okorshenko** [comment]
@malachy-mcconnnell please check this commit 5ceb0820676e4593b68e1991abd348d99adac09c 
This is fix for 2.2 (develop branch). So we can reimplement this solution for 2.1.x release line

**Comment by okorshenko** [comment]
Closing this issue for develop branch (release 2.2). There is a related issue for 2.1 https://github.com/magento/magento2/issues/5627
