### ISSUE TITLE
Checkout navigation scrolling behavior inconsistent between browsers

### ISSUE THREAD

**Issue by mfickers** [magento/magento2#35126]
### Preconditions (*)

1. Any Magento > 2.3.0
2. Firefox browser
### Steps to reproduce (*)

1. Add a shippable product to cart and go to checkout
2. Enter valid email, shipping address and select shipping method
3. Click on 'Next' button, wait for step 2 to load
4. Click on the pencil icon next to the selected shipping method in the bottom right corner

### Expected result (*)

1. Get directed to step 1, page scrolls down to shipping method list

### Actual result (*)

1. Get directed to step 1, page scrolls down to shipping address

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mfickers** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
what theme in your case used ? Would be great if we have some screenshot or video recorded

**Comment by mrtuvn** [comment]
also can you add context for scenario 
guest or customer

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Attached video for reference.
Issue: Front -end - Payment Step - On clicking Pencil Icon of Shipping Method, page is not scrolled down to Shipping Methods but instead user is displayed with Shipping Address.
Both Ship To and Shipping Methods sections edit, redirect to shipping address section.
Expected behavior: On clicking Pencil icon of Shipping Method, User should be redirected to Shipping Methods section.
[1ac439e5-58f4-4f17-9a71-b4fb4f9a02e8.zip](https://github.com/magento/magento2/files/8113970/1ac439e5-58f4-4f17-9a71-b4fb4f9a02e8.zip)

**Comment by mfickers** [comment]
@mrtuvn 

This is on 2.4-develop, with Luma theme and sample data. I've added any product to cart and proceeded to checkout as a guest.

As you can see in the screen cast below, when navigating back to the shipping methods by clicking on the pencil icon in step 2, the page is scrolled to the top of the shipping address form. Or to be more exact, it is scrolled to the element with the id #shipping, as the hash is set on the url.

https://user-images.githubusercontent.com/12683535/155087416-e8209371-6e60-4e6e-aad6-552bbb5af21b.mov

This is the code that handles the pencil icon click, from Magento_Checkout/js/view/shipping-information:
```js
backToShippingMethod: function () {
    sidebarModel.hide();
    stepNavigator.navigateTo('shipping', 'opc-shipping_method');
}
```

The second parameter (`opc-shipping_method`) is the element's id the page should be scrolled down to, from 'Magento_Checkout/js/model/step-navigator':
```js
navigateTo: function (code, scrollToElementId) {
```

The element with the id `opc-shipping_method` is the shipping method list that is below the shipping address form. This is a screen cast of the expected behavior. The page is scrolled down to the shipping method list after clicking the pencil icon:

https://user-images.githubusercontent.com/12683535/155086837-9923da5b-9aa4-4112-b748-553529383807.mov

**Comment by mrtuvn** [comment]
look reasonable ! I think this one affected to a lot of stores. Not a critical blocker. But should fix it as soon as possible

**Comment by mrtuvn** [comment]
should P2-P3 priority update

**Comment by engcom-Bravo** [comment]
Hi @mfickers,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop magento instance and the issue is still reproducible.Kindly refer the attached video.


https://github.com/user-attachments/assets/fc06c0c5-baa2-42c7-b72c-c8577dc8515f



Get directed to step 1, page scrolls down to shipping address

Hence Confirming the issue.


Thanks.
