### ISSUE TITLE
Magento2 don't work with redis in cluster mode

### ISSUE THREAD

**Issue by ByJacob** [magento/magento2#35140]
### Preconditions (*)

1. Magento 2.4.3
2. Redis 6 configured in cluster mode (or use AWS ElastiCache in cluster mode with 3 masters)

### Steps to reproduce (*)

1. Run magento
2. Configure redis config and cache (redis is configured in [cluster mode](https://redis.io/topics/cluster-tutorial))

### Expected result (*)

1. All `./bin/magento` comands works correct and return status code `0`
2. Cache in redis works

### Actual result (*)

1. `magento` command returns status code `1` with error text, example `MOVED 2482 122[IP:PORT]`
2. Cache don't work

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magenx** [comment]
this page explain everything

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Replication.Redis-RedisCluster.html

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.ConnectToCacheNode.html

**Comment by engcom-Hotel** [comment]
Hello @ByJacob,

I hope your problem has been solved by going through the documentation link in this [comment](https://github.com/magento/magento2/issues/35140#issuecomment-1053615007).

Thanks

**Comment by ByJacob** [comment]
Unfortunately, that does not solve the problem. The documentation only shows the different methods for configuring ElastiCache and how to connect to it when Cluster Mode is turned off and on.
My probleme is that I cannot configure redis backend when redis is running with **cluster mode enabled**.

- The colinmollenhour/Cm_Cache_Backend_Redis package in use [does not support cluster configuration](https://github.com/colinmollenhour/Cm_Cache_Backend_Redis#deprecation-notice).
- [The cache backend documentation](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html) does not describe how to configure a cluster.
- [Session documentation in redis](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-session.html) describes the use of sentinel in redis, however it is master -> multiple replicas configuration. The configuration of the cluster in redis can operate on several masters.
- The php client that handles the redis configuration is [predis](https://github.com/predis/predis).
- [Tutorial for redis-cluster](https://redis.io/topics/cluster-tutorial)

Without special cluster handling, the master switches during writing, which the current php code interprets as an error. For example, in the `redis-cli` command, use the special **-c** flag so that it can properly communicate with the redis cluster.

**Comment by engcom-Hotel** [comment]
Hello @ByJacob,

Thanks for the confirmation!

We have tried to reproduce the issue by following the Redis cluster documentation [here](https://redis.io/topics/cluster-tutorial). And after setting up the Redis cache by following the [Magento docs](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html), we are able to reproduce the issue in the latest Magento 2.4-develop branch.

Please have a look at the below screenshot for reference:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/51681618/156980667-e47210ce-06c9-406a-a1cb-36afb1ee9802.png">

Hence confirming this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @ByJacob,

We have further investigated this issue and we have integrated the Redis cluster in `app/etc/env.php`. (Attached is the screenshot for the same):

<img width="672" alt="image" src="https://user-images.githubusercontent.com/51681618/165308014-435a521f-6bee-4e0d-b601-b9ece724684d.png">

Below are the points that come up in the investigation:

- The function which is used for redis cluster setup in credis_client is in the ColinMollenHour module, is not using it anymore which is also mentioned in the code in file vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php line no 436. 
- Credis client method 'isMulti' which needs to be 'TRUE' in order to work with redis cluster and the default value is set as 'False' in file vendor/colinmollenhour/credis/Client.php. The exception is thrown when __call function is called from Credis_Client class for 'hGet' before 'multi' hence not converting isMulti = 'True'. 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/51681618/165308803-f2ef88aa-af88-4b4d-b4df-43be9f300e1a.png">

<img width="609" alt="image" src="https://user-images.githubusercontent.com/51681618/165308842-7e209676-9f8f-4a77-b263-1d3b69c4c745.png">

<img width="609" alt="image" src="https://user-images.githubusercontent.com/51681618/165309107-189eff23-044f-4678-ac42-964196552871.png">


Hence the issue is not related to the Magento core library. 

Thanks

**Comment by ByJacob** [comment]
hello,
So one question, why is `colinmollenhour/Cm_Cache_Backend_Redis` used instead of the more elaborate`predis/predis`, since predis supports almost all redis functionality?
And another question, what does `Component: Bundled Extension` mean then, waiting for the library to have this functionality? If so, why not use `predis` which has php 8.1 support already (https://github.com/predis/predis/commit/acb2460f4c023cef319afe9a68bb12d391707912)?

**Comment by engcom-Hotel** [comment]
Hello @ByJacob,

Hence this issue is not related to Magento core code, so I suggest you refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for technical questions, feature requests, etc.

Thanks

**Comment by robsoned** [comment]
As on the way it's implemented right now, it causes an issue to integrate redis, a system requirement to run the application on production with good performance. With that said, why this issue would not be related to Magento core code?

**Comment by engcom-Hotel** [comment]
Hello,

The related issue has been fixed now and is unable to reproduce on the latest development branch i.e. 2.4-develop. Hence closing this ticket.

Thanks

**Comment by vishwanathkharabe** [comment]
Hi @engcom-Hotel ,
Earlier you were able to reproduce this issue, 
https://github.com/magento/magento2/issues/35140#issuecomment-1060242326 
but in your latest comment https://github.com/magento/magento2/issues/35140#issuecomment-1343940398
 you said it is fixed. Can we know what changes you made to fix this, is there any PR ?
 Thanks!

**Comment by devops-digitalsilk** [comment]
I still have the same issue, version 2.4.3-p3. Configuration the cluster always returning MOVED in the first line of magento bin composer.

**Comment by hugodeaguiar** [comment]
Still the same issue on Magento 2.4.8-p1. 
@engcom-Hotel can you please review this topic?
