### ISSUE TITLE
Unsecured URLs returned for product images 

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#35192]
### Preconditions (*)

1. Magento 2.4.2 / 2.4.3
2. Magento 2.3.x
3. Multistore installation with following setup:
-- store nr 1 has different URLs for media 
-- store nr 2 has only secured URL for media different
4. set secure URLs to be used in frontend

### Steps to reproduce (*)

1. create a CLI method to iterate through all the stores and try to fetch main product image for each store
```
        /** @var \Magento\Store\Api\Data\StoreInterface $store */
        foreach ($this->storeManager->getStores() as $store) {
            foreach ($this->storeManager->getStores() as $store) {
            // force store emulation for helpers and image getters
            $this->appEmulation->startEnvironmentEmulation($store->getId(), \Magento\Framework\App\Area::AREA_FRONTEND, true);
```
2. fetch product collection
3. display product image using `imageHelper` class
4. to make it easier, use the code from sitemap generation
```
/**
     * Get product image URL from image filename
     *
     * @param string $image
     * @return string
     */
    private function getProductImageUrl(string $image): string
    {
        return $this->imageUrlBuilder->getUrl($image, 'product_page_image_large');
    }
```
### Expected result (*)

1. image URLs for all product images are per configured URL

### Actual result (*)

1. Media URL for each product is set to the default one

### Source of the issue (*)
1. in this file `vendor/magento/module-catalog/Model/Product/Media/Config.php` there is no `isSecure` check 
2. so it returns the same media URLs for all products

### Solution (*)
1. issue can be solved with proper store configuration
2. introduce code fix to check if secure frontend is used for that media path 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @qsolutions-pl,

Thanks for reporting the issue!

We request you to please elaborate below on the point from the main description. Screenshot will also help us in reproduction:
> 3\. Multistore installation with following setup:
>     -- store nr 1 has different URLs for media
>     -- store nr 2 has only secured URL for media different

Thanks

**Comment by qsolutions-pl** [comment]
I'll provide some screenshots, but the error is clear in the file I've listed.

**Comment by engcom-Hotel** [comment]
Hi @qsolutions-pl,

Thanks for your reply!

We are waiting for your reply.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @qsolutions-pl,

Thanks for your reply!

We have tried to reproduce the issue, below steps we have followed:
Steps

1. Create multistore:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/51681618/161233358-0089e121-7d12-4158-bc2b-a446a13ff44e.png">

2. Setup different base url for main and another store:
**Main Store**
![image](https://user-images.githubusercontent.com/51681618/161233702-f727da7b-488a-4324-a532-526214d47896.png)

**Another Store**
![image](https://user-images.githubusercontent.com/51681618/161233947-db1cda61-1e17-4f7b-bdde-a715a2a0def9.png)

3. Create a CLI module to get image URL for another store:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/51681618/161234152-97676174-672e-4b17-9a88-2ee61156c94b.png">

You can see in the 2nd step, the configuration is proper for another store, still we are getting unsecured URL. Please have a look into below screenshot for reference:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/51681618/161234430-e897d17b-d684-4b8b-bb8d-6316c6615633.png">

Let us know in case we have missed anything.

Thanks

**Comment by qsolutions-pl** [comment]
So you have reproduced the issue :-) 
The problem is that with such settings `Use Secure URL in Frontend` you should get `HTTPS` link not `HTTP`

**Comment by sanganinamrata** [comment]
@qsolutions-pl I recently got the same issue. Fixed temporary by changing baseurl to be a secure one. But using "Use Secure URL in Frontend" to detect the URL is a better solution.

**Comment by engcom-Hotel** [comment]
Hello @qsolutions-pl,

But as per the main description, the issue can be fix, if the store configuration is proper:

> ### Solution (*)
> 1. issue can be solved with proper store configuration

And As per my comment [here](https://github.com/magento/magento2/issues/35192#issuecomment-1085666413), the configuration is proper but still we are getting `http` link instead of `https`. Am I missed anything or we can edit the main description that even if with the proper configuration the `https` link not getting.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @qsolutions-pl,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by andreidragutu** [comment]
@engcom-Hotel The issue is not fixed. http (unsecure) URL images are written even in sitemaps: media/sitemap/sitemap-products0.xml

Magento 2.4.6-p3 on Adobe Commerce Cloud

**Comment by engcom-November** [comment]
Hello @andreidragutu,

Thank you for the update, we are reopening this issue.

Thank you.

**Comment by engcom-November** [comment]
Hello @qsolutions-pl,

We were able to reproduce this issue on 2.4-develop.
As mentioned here https://github.com/magento/magento2/issues/35192#issue-1168699284, we used `UrlBuilder` to get the url of the image, and we got the default url.

Please take a look at the screenshots below:
**This is the main website with default url configuration**
<img width="990" alt="image" src="https://github.com/magento/magento2/assets/60198231/4714005e-d388-4d00-b958-76b4c5ef3898">
<img width="948" alt="image" src="https://github.com/magento/magento2/assets/60198231/6443c2ef-a75d-430a-ad06-999b3e10f2fa">

**This is the greek website with custom url configuration.**
<img width="947" alt="image" src="https://github.com/magento/magento2/assets/60198231/978494fe-686a-4118-bfaf-9cfbbe953f85">
<img width="940" alt="image" src="https://github.com/magento/magento2/assets/60198231/27491062-c39f-4b1e-9254-318b73aa320d">

**We created a custom module with CLI method to get the url of the image, we got the below result:**
<img width="955" alt="image" src="https://github.com/magento/magento2/assets/60198231/0ba6a177-6b6a-4f9d-9aa9-8724604f3a04">
Here we got the default url not the configured secured url.
Hence confirming the issue.

Please find the custom module used to reproduce this issue.
[ImageVendor.zip](https://github.com/magento/magento2/files/13216144/ImageVendor.zip)

Thank you.

**Comment by lbajsarowicz** [comment]
getBaseMediaUrl() in Media/Config.php (lines 76-79) delegates secure-URL handling to UrlInterface::getBaseUrl(URL_TYPE_MEDIA); the store-emulation-order root cause isn't confirmable statically, though engcom-November reproduced this on 2.4-develop on 2023-10-31. Please re-QA with the exact store-emulation scenario to confirm this is still current.
