### ISSUE TITLE
Magento 2.4.4 Admin Login Not Working After Upgrade

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#35297]
### Preconditions (*)
1. Magento 2.4.3-p1
2. Developer mode
3. PHP 7.4

### Steps to reproduce (*)
1. composer require magento/product-community-edition 2.4.4 --no-update
2. composer update & setup:upgrade
4. Go to admin (we have custom admin path) and try to login.

### Expected result (*)
1. Being able to login at the admin panel.

### Actual result (*)
1. Redirect happens after pressing login, but no login occurs.
2. There is also no visible reason displayed or anything outputted in the logs.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JelleGe** [comment]
We faced the same issue and also have custom admin path. Upgrade from 2.3.4-p1

**Comment by mikemoooo** [comment]
We also have this issue with 2.3.4-p1 and custom admin path.

**Comment by jorgb90** [comment]
@JelleGe @mikemoooo No solution found as of yet?

**Comment by lcw-media** [comment]
Aber some debugging we recognized that when authenticate the formkey validation always failed

**Comment by rjm87** [comment]
I am experiencing the same bug. After updating to 2.4.4 the form never validates and login is impossible. Tried clearing cookies and updating backend admin path. Also upgraded from 2.4.3-p1.

**Comment by CollegeSewing** [comment]
I was experiencing the same bug, using Redis for Session storage.

However, changing the session save to files, then allowed access to the admin
'session' => [
        'save' => 'files'

I did also have to reset 2FA for the user account

**Comment by mikemoooo** [comment]
We are using files for session storage, but have the error anyway

**Comment by jorgb90** [comment]
Found the issue! In Magento 2.4.4 it seems that a value of "0" for Max Session Size in Admin breaks it. In normal behaviour "0" should disable the size. I set mine now to "2560000" cause the default setting of "25600" isn't working for us (too low) and that solved this issue for now.

**Comment by lcw-media** [comment]
> max_session_size_admin

Also did it for me, thank you!

**Comment by mikemoooo** [comment]
Solved the issue for me as well!

**Comment by JelleGe** [comment]
Sadly we get the following error when trying to set the Max Session Size in Admin using CLI;

bin/magento config:set system/security/max_session_size_admin 2560000
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /vendor/magento/framework/Reflection/TypeProcessor.php on line 550

**Comment by jorgb90** [comment]
@JelleGe That has nothing to do with this. One of your modules is not 2.4.4 ready, you probably get the same error when running setup:upgrade.

**How to fix?** add PHPDOC block for all consumer class in your custom module.

**How to find all consumer class?** you can set break point debugger in vendor/magento/framework/Reflection/MethodsMap.php or just wrap this method in try/catch block and print the class you need to fix.

**Or if you dont care to fix the modules now** You can change line 550 of vendor/magento/framework/Reflection/TypeProcessor.php to "return $type;" that way you can proceed with setup:upgrade.

**Comment by JelleGe** [comment]
@jorgb90 Thanks a lot for the help! We will digg deeper into this issue.

**Comment by jorgb90** [comment]
@engcom-November You should install 2.4.3-p1 and set maximum session size to 0 and then upgrade to 2.4.4. Now you can't login anymore. Or just install 2.4.4 directly without upgrade and set session size to 0 to disable it and you can't login anymore. The "0" option isn't working while Magento says "Use 0 to disable." that it should work.

**Comment by engcom-November** [comment]
Hi @jorgb90 , "Setting maximum session to  0" and login not working this behavior exists in 2.4-develop instance as well. 
Bug report for the same: https://github.com/magento/magento2/issues/35312 
Can we close this issue (#35297) as the issue is not happening due to upgrade from 2.4.3-p1.
Thank you.

**Comment by jorgb90** [comment]
@engcom-November  It does gives issues for people who upgrade, but yes don't care how its explained and which report to use, it should be fixed.

**Comment by rjm87** [comment]
> bin/magento config:set system/security/max_session_size_admin 2560000

This fixed the issue for me as well! Thanks!

**Comment by mgwalk** [comment]
Still having issue after running
php bin/magento config:set system/security/max_session_size_admin 2560000
I restarted varnish
php bin/magento c:c
php bin/magento c:f
Cleared cookies and site data.  
still no error, it just looks like it refreshes.

**Comment by mgwalk** [comment]
> @JelleGe That has nothing to do with this. One of your modules is not 2.4.4 ready, you probably get the same error when running setup:upgrade.
> 
> **How to fix?** add PHPDOC block for all consumer class in your custom module.
> 
> **How to find all consumer class?** you can set break point debugger in vendor/magento/framework/Reflection/MethodsMap.php or just wrap this method in try/catch block and print the class you need to fix.
> 
> **Or if you dont care to fix the modules now** You can change line 550 of vendor/magento/framework/Reflection/TypeProcessor.php to "return $type;" that way you can proceed with setup:upgrade.

Do you have Magefan Blog?  I have Magefan 2.10.6
I get this error.  
When I edit \app\etc\config.php
and Disable Magefan blog setup:upgrade works

**Comment by mgwalk** [comment]
I was able to fix by updating frontend and admin before upgrading to 2.4.4.
I also had magefan blog which needed updated.

**Comment by stalinraj-indian** [comment]
> Sadly we get the following error when trying to set the Max Session Size in Admin using CLI;
> 
> bin/magento config:set system/security/max_session_size_admin 2560000 Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /vendor/magento/framework/Reflection/TypeProcessor.php on line 550

Edit this file: vendor/magento/framework/Reflection/TypeProcessor.php  on line 550

 #return $this->resolveFullyQualifiedClassName($param->getDeclaringClass(), $type); 
 return $type;

**Comment by puntable** [comment]
> bin/magento config:set system/security/max_session_size_admin 2560000

Can confirm, this did the trick for me aswell. Upgraded from 2.4.3-p1 > 2.4.4

**Comment by barryvdh** [comment]
I'm not sure, but I changed my development site from 'admin' to 'admin_<some random string>' and it worked again.

**Comment by mtkumar82** [comment]
> bin/magento config:set system/security/max_session_size_admin 2560000

This one works for me. Thanks

**Comment by ClintTec** [comment]
Still no fix for this? 

`bin/magento config:set system/security/max_session_size_admin 2560000`

did not work for me.

**Comment by j-lloyd-slc** [comment]
I did not see this problem until the upgrade was deployed to an environment that uses Redis for session storage.

The fix posted by @jorgb90 resolved the issue.

**Comment by Citizen4our** [comment]
`bin/magento config:set system/security/max_session_size_admin 2560000`

This one works for me. Thanks

**Comment by lykhouzov** [comment]
The issue happens because in v2.4.4 it was changed a way of Session handler reads session data
in the version 2.4.3-p1 (p2 and p3)
https://github.com/magento/magento2/blob/2.4.3-p3/lib/internal/Magento/Framework/Session/SaveHandler.php#L100
it just read a session data
```php
public function read($sessionId)
    {
        return $this->callSafely('read', $sessionId);
    }
```
where in version 2.4.4
https://github.com/magento/magento2/blob/2.4.4/lib/internal/Magento/Framework/Session/SaveHandler.php#L123
```php
public function read($sessionId): string
    {
        $sessionData = $this->callSafely('read', $sessionId);
        $sessionMaxSize = $this->sessionMaxSizeConfig->getSessionMaxSize();
        $sessionSize = strlen($sessionData);

        if ($sessionSize !== null && $sessionMaxSize < $sessionSize) {
            $sessionData = '';
            if ($this->appState->getAreaCode() === Area::AREA_FRONTEND) {
                $this->messageManager->addErrorMessage(
                    __('There is an error. Please Contact store administrator.')
                );
            }
        }

        return $sessionData;
    }
```
it also checks set session Max Size and if session data is bigger than configured session size it cleans the data, so it looks like the session never was read

**Comment by ivan-herrera-pro** [comment]
✨In my case, I had installed a Magento 2.4.x environment when the problem occurred. I solved the issue by executing the SQL statement in the Magento DB: 

**`select * from core_config_data where path like "%cookie_domain%";`**

and modifying the **value** attribute by my local magento url. Note that you should not type https, neither slash.

🖼Example: https://imgur.com/5y5462B

**Comment by Tejas108** [comment]
Fixed it, thanks!

**Comment by beatdemon** [comment]
What is amazing is that our development firm and extension provider have no idea this issue exists! I found it here myself and was able to fix. Thank you @jorgb90 for your post! All we did was upgrade from 2.4.3 P1 to 2.4.4 and the development firm blamed it on the extension provider, and visa-versa! I'll send this link along to them along with a face slap emoji. ;)

**Comment by ZoeZhong-AAXIS** [comment]
> > bin/magento config:set system/security/max_session_size_admin 2560000

Thanks. This also works for me.

**Comment by danielpugh** [comment]
bin/magento config:set system/security/max_session_size_admin 2560000

worked for me (phew!)

**Comment by tiwarimukesh** [comment]
If all the given solutions given in previous comments are not working.  The reason may be that the password strength is not meeting the security requirements. (You may have a weaker password set for the admin user.)

By default, in Magento 2, the password that meets security requirements must consist of:

Uppercase letters

Lowercase letters

Numeric

Special characters

Minimum of 8 characters

Run the following command in the MySQL to update password to a complex password.

`UPDATE admin_user SET password = CONCAT(SHA2('xxxxxxxYourNewPassword', 256), ':xxxxxxx:1') WHERE username = 'admin';`

The xxxxxxx character sequence is a cryptographic salt, it is saved in app\etc\env.php file

**Note:**

1. Use a complex password instead of YourNewPassword.
2. Replace admin with your username.
3. This solutions works if you are not able to login after upgrading to Magento 2.4.x from a lower version.

Then after try to login again, it will work.

**Comment by sharmdx41** [comment]
> Found the issue! In Magento 2.4.4 it seems that a value of "0" for "Max Session Size in Admin" breaks it. In normal behaviour "0" should disable the size. I set mine now to "2560000" cause the default setting of "256000" isn't working for us (too low) and that solved this issue for now.
> 
> You can set it to this value through CLI (flush cache after):
> 
> bin/magento config:set system/security/max_session_size_admin 2560000

@jorgb90 Unfortunately the solution you suggested is not working for me. Is there anything else that can be done to resolve this.

**Comment by sharmdx41** [comment]
> ✨In my case, I had installed a Magento 2.4.x environment when the problem occurred. I solved the issue by executing the SQL statement in the Magento DB:
> 
> **`select * from core_config_data where path like "%cookie_domain%";`**
> 
> and modifying the **value** attribute by my local magento url. Note that you should not type https, neither slash.
> 
> 🖼Example: https://imgur.com/5y5462B

@ivan-herrera-pro This solution is not working for me, any other suggestions?

**Comment by sharmdx41** [comment]
Hi @jorgb90 @ivan-herrera-pro, 

Following command worked for me 
bin/magento config:set system/security/max_session_size_admin 2560000

But after I logged in MBO, the links lie Saels/customer/Catalog etc are not working.

**Comment by hafizjee** [comment]
> sparklesIn my case, I had installed a Magento 2.4.x environment when the problem occurred. I solved the issue by executing the SQL statement in the Magento DB:
> 
> **`select * from core_config_data where path like "%cookie_domain%";`**
> 
> and modifying the **value** attribute by my local magento url. Note that you should not type https, neither slash.
> 
> framed_pictureExample: https://imgur.com/5y5462B

Working fine for me 2.4.5!

**Comment by bogdanignat** [comment]
If this dont work
`bin/magento config:set system/security/max_session_size_admin 256000`

try to see if max session is not 0 on your websites - check `core_config_data` table

`bin/magento config:set --scope=websites --scope-code=base system/security/max_session_size_admin 256000`

where 'base' is ur website code - find it in this table `store_website`

**Comment by Kishorchhugani** [comment]
neither or 
bin/magento config:set system/security/max_session_size_admin 256000
nor this
select * from core_config_data where path like "%cookie_domain%";

working for me ,
clear browser cookies but still not working

**Comment by wasimhc** [comment]
For upgrading to Magento 2.4.6, I do the following attempts to resolve the admin login issue:

bin/magento config:set system/security/max_session_size_admin 2560000

SELECT *, REPLACE(value,'http://domain.com/', 'https://domain.com/') FROM core_config_data WHERE path LIKE '%web/%/base_url%';
UPDATE core_config_data SET value = REPLACE(value,'http://domain.com/', 'https://domain.com/') WHERE path LIKE '%web/%/base_url%';

SELECT * FROM core_config_data WHERE path LIKE '%secure%';
UPDATE core_config_data SET `value`='1' WHERE  `config_id`=4;
UPDATE core_config_data SET `value`='1' WHERE  `config_id`=5;

SELECT * FROM core_config_data WHERE path = 'web/cookie/cookie_domain';
UPDATE core_config_data SET `value`='domain.com' WHERE  `config_id`=50;

I encountered a few common issues that can be resolved using the same methods every time.
