### ISSUE TITLE
2.4.3-p2 breaks OAuth integrations, does not upgrade secrets and tries to decrypt them

### ISSUE THREAD

**Issue by evolbug** [magento/magento2#35313]
### Preconditions (*)

1. Have OAuth integrations created before forced secret encryption
2. Upgrade to 2.4.3-p2

### Steps to reproduce (*)

1. Create and connect an integration on a version before 2.4.3-p2
2. Upgrade to 2.4.3-p2

### Expected result (*)

1. OAuth integration can be successfully reauthorized

### Actual result (*)

1. Authorization fails with `The attempt to post data to consumer failed due to an unexpected error. Please try again later.`
2. The secrets are not upgraded along with the update, so it attempts to decrypt unencrypted values
![image](https://user-images.githubusercontent.com/19688801/163426449-9a79cd22-5a75-49c7-9cd6-d4e487c9110e.png)
4. Internal exception: ```[2022-04-14 15:01:08] main.CRITICAL: Notice: iconv_strlen(): Detected an illegal character in input string in /var/www//data/releases/20220414144351/vendor/magento/zendframework1/library/Zend/Validate/StringLength.php on line 250 {"exception":"[object] (Exception(code: 0): Notice: iconv_strlen(): Detected an illegal character in input string in /var/www//data/releases/20220414144351/vendor/magento/zendframework1/library/Zend/Validate/StringLength.php on line 250 at /var/www//data/releases/20220414144351/vendor/magento/framework/App/ErrorHandler.php:61)"} []```
5. Patch list shows that OAuth upgrade patches were applied 
![image](https://user-images.githubusercontent.com/19688801/163428822-a73491be-ab3a-4c8f-afba-1c17bb23d8fe.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue by upgrading Magento version from 2.3.7 to 2.4.3-p2 but could not able to reproduce the issue.
Admin - System - Integrations - Created new integration before upgrade
Upgraded to 2.4.3-p2
Reauthorize integration - No issue/ Exception
![image](https://user-images.githubusercontent.com/60198231/164021936-1b132825-f89d-45db-b7ea-d10b6303485f.png)

![image](https://user-images.githubusercontent.com/60198231/164021574-de156fc7-ffc0-4bf2-ac6b-259b7b1e81e7.png)
@evolbug kindly recheck the issue again and elaborate steps to reproduce if you are still facing issues.
Thank you.

**Comment by kenseiatwork** [comment]
I encountered this problem as well.  It looks to be an issue for older magento sites when the module.xml's setup_version was still in use. 

The last setup_version for the integration module looks to be 2.2.0, you can check the row for Magento_Integration in the  setup_module table.

In the patch files for UpgradeConsumerSecret.php and UpgradeOauthToken.php, the method for getVersion() is set to 2.0.0. I believe this should be 2.2.1 or greater -- or removed altogether.

    public static function getVersion()
    {
        return '2.0.0';
    }


Per devdocs
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/declarative-schema/data-patches.html#will-old-scripts-work-in-newer-versions

You would also need to remove the rows in the table patch_list:
Magento\Integration\Setup\Patch\Data\UpgradeOauthToken
Magento\Integration\Setup\Patch\Data\UpgradeConsumerSecret

Then rerun setup:upgrade

**Comment by evolbug** [comment]
@engcom-November You need to reauthorize the integration, also check the integration details for incorrectly displaying secrets

**Comment by YiffyToys** [comment]
We can confirm this updating 2.4.3-p1 to 2.4.3-p2 
@evolbug reauthorize does NOT help. The consume secret stays mangled and unusable.
You have to recreate the integration with every single access permission the old one had.
A very time consuming process exagerated by the fact that you can't right clitk "open in new tab" most links in the admin area.

**Comment by YiffyToys** [comment]
Reauthorize can be performed here too but entering the integration damaged in the upgrade
still shows a mangled and unusable "Consumer Secret" and using the new token yields 401 unauthorized.
Completely new integrations created after the update to 2.4.2-p2 work just fine.

**Comment by engcom-Dash** [comment]
Hi @evolbug 
We have tried to reproduce the issue in Magento 2.4.3-p2. the issue is not reproducible. 
![Screenshot from 2022-05-31 16-44-03](https://user-images.githubusercontent.com/60198592/171349861-46542d86-49c2-4087-bdff-efb7d1ae4350.png)
![Screenshot from 2022-06-01 15-02-34](https://user-images.githubusercontent.com/60198592/171374065-44b3ff83-f2a7-4743-8e5c-e13c7d91c8bd.png)


1.Verified the issue again by upgrading from 2.4.3-p1 to 2.4.3-p2
2.Recreated the Integration with same Resources access as the old one is also working fine
3.Reauthorize Integration also worked fine in 2.4.3-p2

 Let us know in case we have missed anything. Thanks

**Comment by hostep** [comment]
Can reproduce due to [the hints](https://github.com/magento/magento2/issues/35313#issuecomment-1102715046) of @kenseiatwork, thanks for that!

@engcom-Dash: please try the following:

1. Using composer v1 and PHP 7.2, setup a clean Magento 2.2.11 installation
2. In the backoffice, configure at least one integration and activate it
3. Now, switch to composer v2, PHP 8.1, remove your entire `vendor` directory and use composer to upgrade to Magento 2.4.4
4. Execute `bin/magento setup:upgrade`
5. In the backoffice, click on Edit in your integration(s) and notice that the consumer secret now contains a bunch of weird symbols

**Comment by engcom-Hotel** [comment]
Hello @hostep,

Thanks for the support!

Hello @evolbug,

We have tried to reproduce the issue by following this https://github.com/magento/magento2/issues/35313#issuecomment-1146795806. But for us, the issue is still not reproducible.

We are able to reauthorize the integrations but we have observed that after the upgrade `Consumer Secret` is looks like below:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/51681618/175053809-879d5f20-f900-4b7c-89f6-5f5b8958cc85.png">

Also please refer to the screencast of reauthorizing after the upgrade:

https://user-images.githubusercontent.com/51681618/175054741-a1a6b0c0-374a-41ec-9296-3f86c59cbd3c.mov

Thanks

**Comment by evolbug** [comment]
@engcom-Hotel the garbled consumer secret is a reproduction of the issue, this is due to the secret not being encrypted in the migration

**Comment by YiffyToys** [comment]
> @engcom-Hotel the garbled consumer secret is a reproduction of the issue, this is due to the secret not being encrypted in the migration, so after it, it ends up trying to decrypt the plaintext value from the db

Exactly.
A correct consumer secret would only ever contain lower ASCII character (as you must be able to type it into a client configuration).

**Comment by YiffyToys** [comment]
> @engcom-Hotel the garbled consumer secret is a reproduction of the issue, this is due to the secret not being encrypted in the migration, so after it, it ends up trying to decrypt the plaintext value from the db

Exactly.
A correct consumer secret would only ever contain character allowed in HTTP headers.

**Comment by engcom-Hotel** [comment]
Hello @evolbug @YiffyToys,

Thanks for the reply!

I am confirming the issue for further process.

Please refer to this https://github.com/magento/magento2/issues/35313#issuecomment-1163177171 for more information.

Thanks

**Comment by zepgram** [comment]
I'm not sure that you realise it can break whole service using API integration: **this should be a P1** ticket

By launching a 2.4.3-p2 or 2.4.4 Magento on production you could break every API service.

Guys uou should atleast create a quality patch for this issue.

**Comment by nimbus2300** [comment]
Upgraded to 2.4.4 over the weekend. This bug has broken all my Royal Mail Click and Connect integrations.

> I'm not sure that you realise it can break whole service using API integration: **this should be a P1 ticket**
> 
> By launching a 2.4.3-p2 or 2.4.4 Magento on production you could break every API service.
> 
> Guys you should at least create a quality patch for this issue.

**Comment by nimbus2300** [comment]
> Upgraded to 2.4.4 over the weekend. This bug has broken all my Royal Mail Click and Connect integrations.
> 
> > I'm not sure that you realise it can break whole service using API integration: **this should be a P1 ticket**
> > By launching a 2.4.3-p2 or 2.4.4 Magento on production you could break every API service.
> > Guys you should at least create a quality patch for this issue.

I think the fix /might/ be to ensure that:

When the magento version is upgraded to the new secure version (>2.4.3-p2?):
   - Ensure that a one-time upgrade script/activity takes place, that:
        -  Crypts all existing stored integration keys, and rewrites them, now encrypted, to the same row in the database.

The new version of Magento would then be able decrypt the keys successfully (rather than appearing garbled as in the screenshots in the above thread).

Needs verification from someone else though to verify this thinking.

Does Magento has a mechanism for one-time data manipulation scripts to be run on minor version upgrades?

**Comment by onepack** [comment]
Same issue here with two clients after upgrading from 2.3 to 2.4.4-p2.
All integrations are broken.
![image](https://user-images.githubusercontent.com/475598/199190951-fb87530f-b5a2-4f54-8ef5-e19a4e49cb4f.png)

**Comment by willbrammer** [comment]
Hi

I just want to add this issue is happening on Magento 2.4.5-p1 too. 

I have also raised a ticket with Magento Support to see if they have anything for this.

Bit surprised how long this has been open. Deleting and re-creating the integrations is not ideal for some systems

Thanks
Will

**Comment by zepgram** [comment]
Still waiting for a <b>quality patch</b> since July @magento.

It's just my opinion but security patch **SHOULD** never include a `data`/`schema` patch or any database changes.
You should talk about this with your architecture team.

The reason is simple: you may break Magento on a security patch, which is a total non-sense by doing this you are also breaking customer's confidence on security release.

At least, you may warn everyone in your release patch notes when a database patch is included in your security release.

**Comment by engcom-Hotel** [comment]
Hello @zepgram @willbrammer,

The related JIRA status is `Deployment Queue`, it will be merged soon with the development branch. I will keep you posted.

Thanks

**Comment by ninjacoder30** [comment]
Hello @engcom-Hotel 

I am facing same issue on 2.4.4-p1 , i deleted the patch entries and still not able to fix the issue.

Also when i try to active new key its giving me below error
The attempt to post data to consumer failed due to an unexpected error. Please try again later.

Below is the trace

`
2022-11-04T18:11:58+00:00 INFO (6): Unable to read response, or response is empty
2022-11-04T18:11:58+00:00 INFO (6): #0 vendor/magento/framework/HTTP/ZendClient.php(52): Zend_Http_Client->request()
#1 vendor/magento/module-integration/Model/OauthService.php(242): Magento\Framework\HTTP\ZendClient->request()
#2 vendor/magento/module-integration/Controller/Adminhtml/Integration/TokensExchange.php(59): Magento\Integration\Model\OauthService->postToConsumer()
#3 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange->execute()
#4 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callParent()
#5 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->Magento\Framework\Interception\{closure}()
#6 generated/code/Magento/Integration/Controller/Adminhtml/Integration/TokensExchange/Interceptor.php(23): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callPlugins()
#7 vendor/magento/framework/App/Action/Action.php(111): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->execute()
#8 vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#9 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#10 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callParent()
#11 app/code/WeltPixel/Backend/Plugin/Utility.php(76): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->Magento\Framework\Interception\{closure}()
#12 vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#13 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->Magento\Framework\Interception\{closure}()
#14 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#15 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->Magento\Framework\Interception\{closure}()
#16 generated/code/Magento/Integration/Controller/Adminhtml/Integration/TokensExchange/Interceptor.php(32): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->___callPlugins()
#17 vendor/magento/framework/App/FrontController.php(245): Magento\Integration\Controller\Adminhtml\Integration\TokensExchange\Interceptor->dispatch()
#18 vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#19 vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#20 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#21 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#22 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#23 generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#24 vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#25 vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#26 pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#27 {main}`

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3752 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-3752&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by goivvy** [comment]
Create two scripts in /path/to/magento/root

runOauth.php:

`ini_set('memory_limit','12000M');
use Magento\Framework\App\Bootstrap;
require __DIR__.'/app/bootstrap.php';
$params = $_SERVER;
$bootstrap = Bootstrap::create(BP,$params);
$obj = $bootstrap->getObjectManager();
$state = $obj->get('Magento\Framework\App\State');
$state->setAreaCode('frontend');

try{
$encryptor = $obj->get('Magento\Framework\Encryption\Encryptor');
$tokenCollection = $obj->get('Magento\Integration\Model\ResourceModel\Oauth\Token\CollectionFactory')->create();
$tokenResourceModel = $obj->get('Magento\Integration\Model\ResourceModel\Oauth\Token');
        $tokenCollection->addFieldToSelect('entity_id');
        $tokenCollection->addFieldToSelect('secret');
        $tokenCollection->addFieldToSelect('type');
        $tokenCollection->setPageSize(100);
        $connection = $tokenResourceModel->getConnection();
        $pages = $tokenCollection->getLastPageNumber();
        $tableName = $tokenResourceModel->getMainTable();

        for ($currentPage = 1; $currentPage <= $pages; $currentPage++) {
            $tokenCollection->setCurPage($currentPage);

            foreach ($tokenCollection as $token) {
                $existingSecret = $token->getSecret();
                $entityId = $token->getEntityId();
                $type = $token->getType() !== null ? strtolower($token->getType()) : '';

                if ($entityId && $existingSecret && $type === 'access') {
                    if (strlen($existingSecret) <= 32) {
                        echo $existingSecret."\n";
                        $data = ['secret' => $encryptor->encrypt($existingSecret)];
                        $where = ['entity_id = ?' => $entityId, 'type = ?' => 'access'];
                        try {
                            $connection->update($tableName, $data, $where);
                        } catch (\Exception $exception) {
                            die($e->getMessage());
                        }
                    }
                }
            }
            $tokenCollection->clear();
        }
}catch(\Exception $e){die('||'.$e->getMessage());}`

and 

runConsumer.php:

`ini_set('memory_limit','12000M');
use Magento\Framework\App\Bootstrap;
require __DIR__.'/app/bootstrap.php';
$params = $_SERVER;
$bootstrap = Bootstrap::create(BP,$params);
$obj = $bootstrap->getObjectManager();
$state = $obj->get('Magento\Framework\App\State');
$state->setAreaCode('frontend');

try{
$encryptor = $obj->get('Magento\Framework\Encryption\Encryptor');
$consumerCollection = $obj->get('Magento\Integration\Model\ResourceModel\Oauth\Consumer\CollectionFactory')->create();
$consumerResourceModel = $obj->get('Magento\Integration\Model\ResourceModel\Oauth\Consumer');

        $consumerCollection->addFieldToSelect('entity_id');
        $consumerCollection->addFieldToSelect('secret');
        $connection = $consumerResourceModel->getConnection();
        $consumerCollection->setPageSize(100);
        $pages = $consumerCollection->getLastPageNumber();
        $tableName = $consumerResourceModel->getMainTable();

        for ($currentPage = 1; $currentPage <= $pages; $currentPage++) {
            $consumerCollection->setCurPage($currentPage);

            foreach ($consumerCollection as $consumer) {
                $existingSecret = $consumer->getSecret();
                $entityId = $consumer->getEntityId();

                if ($entityId && $existingSecret) {
                    if (strlen($existingSecret) <= 32) {
                        $data = ['secret' => $encryptor->encrypt($existingSecret)];
                        $where = ['entity_id = ?' => $entityId];
                        try {
                            $connection->update($tableName, $data, $where);
                        } catch (\Exception $exception) {
                            die($e->getMessage());
                        }
                    }
                }
            }
            $consumerCollection->clear();
        }
}catch(\Exception $e){die('||'.$e->getMessage());}`

Then run:

php runOauth.php
php runConsumber.php

Your existing secrets should be fixed afterwards.

**Comment by cfortin** [comment]
How is this issue closed? I just upgraded to 2.4.5-p3 and am still seeing this issue.

**Comment by hostep** [comment]
@cfortin: according to [a few comments earlier](https://github.com/magento/magento2/issues/35313#issuecomment-1352568604), you'll need to upgrade to at least Magento 2.4.6 to get it fixed. And based on the commit mentioned, it could be that the upgrade is not enough to fix it and you might need to make sure the `UpgradeConsumerSecret` patch gets executed again, even if it was already executed before, like mentioned in [this comment](https://github.com/magento/magento2/issues/35313#issuecomment-1102715046)

**Comment by cfortin** [comment]
Thank you very much @hostep.
