### ISSUE TITLE
Remote image not found breaks import - Magento 2.4.3-p1

### ISSUE THREAD

**Issue by xtremevision** [magento/magento2#35522]
### Preconditions and environment

- Magento version: 2.4.3-p1
- CentOS 7 x64
- PHP 7.4.28
- nginx 1.20.2-3
- MariaDB 10.4.21
- CSV file with a remote image like: "https://someurl.com/someimage.jpg"

### Steps to reproduce

1. Navigate to System -> Import
2. Choose "Skip errors", increase the maximum errors to 10,000
3. Upload a CSV file with 3 sample lines. Make sure rows 1 and 3 have images that can be found, row 2 make sure the image is not found.
4. Validate the data
5. Import

You will get this error:
Additional data: <div class=“messages”><div class=“message message-error error”><div data-ui-id=“messages-message-error” >Warning: hash_file(https://fromastorage.blob.core.windows.net/romaapp/7501033961779-1.png): failed to open stream: HTTP request failed! HTTP/1.1 404 The specified blob does not exist. in /app/vendor/magento/module-catalog-import-export/Model/Import/Product.php on line 1961</div></div></div>

### Expected result

Import to succeed, ignoring images not found.

### Actual result

You get this erro:

Additional data: <div class=“messages”><div class=“message message-error error”><div data-ui-id=“messages-message-error” >Warning: hash_file(https://fromastorage.blob.core.windows.net/romaapp/7501033961779-1.png): failed to open stream: HTTP request failed! HTTP/1.1 404 The specified blob does not exist. in /app/vendor/magento/module-catalog-import-export/Model/Import/Product.php on line 1961</div></div></div>

See screenshot
![image (1)](https://user-images.githubusercontent.com/6533394/169840541-581ae917-0358-4e2e-9a7a-c623285e0628.png)

### Additional information

I fixed this by creating an override to the import export file

vendor/magento/module-catalog-import-export/Model/Import/Product.php

this code:

    private function getFileHash(string $path): string
    {
        return hash_file(self::HASH_ALGORITHM, $path);
    }

to:

    private function getFileHash(string $path): string
    {
        try
        {			
            return hash_file(self::HASH_ALGORITHM, $path);
        }
        catch(\Exception $e)
        {
            return false;
        }
    }

Please merge this into core code base.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by xtremevision** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by xtremevision** [comment]
https://github.com/magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by xtremevision** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Delta** [comment]
Hi @xtremevision ,
Thank you for raising an issue , unfortunately need clarification for step# 1 that is which entity should be selected.
Please confirm.
<img width="1440" alt="Screenshot 2022-05-25 at 6 25 22 PM" src="https://user-images.githubusercontent.com/51681379/170266977-2095516c-acf8-4a48-b6a8-e8468975ba1e.png">

**Comment by hostep** [comment]
@engcom-Delta: Since the error happens in `module-catalog-import-export/Model/Import/Product.php`, I'm almost 100% sure it's "Products" as entity ... (please next time use your brain a bit and don't stop issue handling because of such a silly question)

**Comment by xtremevision** [comment]
Firstly if you will notice I tried to reproduce the issue with a dev instance per sop but my requests failed every time, see above.

Secondly, if you look closely at my report, you will notice EXTREMELY clearly I specified app/vendor/magento/module-catalog-import-export/Model/Import/Product.php line 1961, as per my suggested fix, so your question is/was quite redundant. I did want to reply, but I got sidetracked with work, overseas trips, and lack of time.

Thirdly, besides what other import with an image could it be??? Customer imports don't have images. Stock doesn't. Addresses don't. So what import could I be doing that could possibly fail an image upload???

And lastly, did you just insult me!?!? Seriously!?!? Is this the behavior and attitude of a professional company, i.e. Adobe!?!?

Kindly review your attitude sir, and provide an apology. This is completely unacceptable!

**Comment by engcom-Delta** [comment]
Hi @xtremevision ,
Thank you for providing the details, we have tried again to reproduce the issue on Magento 2.4 develop instance. issue is not reproducible.
We are able to import the file successfully .

1. Navigate to System -> Import
2. Choose "Skip errors", increase the maximum errors to 10,000

<img width="1440" alt="Screenshot 2022-06-06 at 3 56 44 PM" src="https://user-images.githubusercontent.com/51681379/172147546-bb413b90-73f4-4cf4-b260-b678ed352baf.png">

3. Upload a CSV file with 3 sample lines. Make sure rows 1 and 3 have images that can be found, row 2 make sure the image is not found.
4. Validate the data

<img width="1440" alt="Screenshot 2022-06-06 at 4 15 50 PM" src="https://user-images.githubusercontent.com/51681379/172148995-4957afa5-7a53-42fa-8100-d5bcd7407b54.png">

5. Import

<img width="1440" alt="Screenshot 2022-06-06 at 4 16 25 PM" src="https://user-images.githubusercontent.com/51681379/172149042-6938d927-95f4-4fb8-be20-68052ce6c2a1.png">

**Error for image is not found :**

<img width="1440" alt="Screenshot 2022-06-06 at 4 17 24 PM" src="https://user-images.githubusercontent.com/51681379/172149115-7777ff01-2aff-4985-ac55-4b325b295a82.png">

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by leonhelmus** [comment]
@xtremevision i have the same issue. This looks like the solution to me thanks. This is still an issue in 2.4.4.
