### ISSUE TITLE
[Confirmed] REST API - Bundle products have empty prices when updating in multiple storeviews

### ISSUE THREAD

**Issue by NickvdMeij** [magento/magento2#35595]
### Preconditions and environment

- Magento version 2.4.3-p1, 2.4.4, 2.4-develop
- Multistore Setup (3 different Websites assigned to 3 stores up and running)
- REST API access

### Steps to reproduce

1. Create 2 or 3 Virtual products - assign to all websites and save.
2. Stores - Settings - Configuration - Catalog - Catalog -  Price scope - set to website and save
3. Reindex and clear cache
4. Create Bundle Product using POST Rest API request: /rest/all/V1/products with virtual products assigned to bundle options using below sample payload:
_{
  "product": {
    "sku": "bunelee",
    "name": "bundlee",
    "attribute_set_id": 4,
    "price": 0,
    "status": 1,
    "visibility": 4,
    "type_id": "bundle",
    "extension_attributes": {
      "stock_item": {
        "qty": 100,
        "is_in_stock":true
      },
      "website_ids": [
        1,2,3
      ],
      "category_links": [
            {
                "position": 0,
                "category_id": "32"
            }
      ],
      "bundle_product_options": [
        {
          "option_id": 0,
          "position": 1,
          "sku": "virtual1",
          "title": "virtual1",
          "type": "checkbox",
          "required": true,
          "product_links": [
            {
              "sku": "virtual1",
              "option_id": 1,
              "qty": 1,
              "position": 1,
              "is_default": false,
              "price": 450,
              "price_type": 1,
              "can_change_quantity": 0
            }
          ]
        },
        {
          "option_id": 1,
          "position": 2,
          "sku": "virtual2",
          "title": "virtual2",
          "type": "checkbox",
          "required": true,
          "product_links": [
            {
              "sku": "virtual2",
              "option_id": 2,
              "qty": 1,
              "position": 1,
              "is_default": false,
              "price": 850,
              "price_type": 1,
              "can_change_quantity": 0
            }
          ]
        },
        {
          "option_id": 2,
          "position": 3,
          "sku": "virtual3",
          "title": "virtual3",
          "type": "checkbox",
          "required": true,
          "product_links": [
            {
              "sku": "virtual3",
              "option_id": 3,
              "qty": 1,
              "position": 1,
              "is_default": false,
              "price": 340,
              "price_type": 1,
              "can_change_quantity": 0
            }
          ]
        }
      ]
    },
    "custom_attributes": [
      {
        "attribute_code": "price_view",
        "value": "1"
      },
      {
        "attribute_code": "price_type",
        "value": "1"
      }
    ]
  },
  "saveOptions": true
}_

No issue: Bundle product is created and assigned to all websites.
5. Update with different prices for bundle options for only one store view using same API request by passing specific store code in URL /rest/<Store_code>/V1/products
6. Verify Admin UI - Product edit page for all Store view scopes

### Expected result

All store view scope - Old price should be displayed.
other store view scope - New price set should be displayed
Note: There is no issue when this operation is performed from UI - User is able to set different price for bundle options in different store views. Behavior should be consistent when this is done from API as well.

### Actual result

Only the last store has their prices set correctly. All other stores have their option prices set to 0

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by NickvdMeij** [comment]
@magento give me 2.4-develop instance

**Comment by NickvdMeij** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by NickvdMeij** [comment]
@magento give me 2.4.3-p1 instance

**Comment by NickvdMeij** [comment]
@magento give me 2.4.3-p1 instance

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,

Thank you for raising an issue and need your assistance on rest api for optionId.
Kindly confirm below rest api what we have tried for updating.

<img width="1440" alt="Screenshot 2022-06-20 at 5 35 23 PM" src="https://user-images.githubusercontent.com/51681379/174599422-726a22c5-393a-4490-b2d0-aad8d2105984.png">

From Frontend options for bundle product:

<img width="1331" alt="Screenshot 2022-06-20 at 5 38 56 PM" src="https://user-images.githubusercontent.com/51681379/174599483-e4f4bfd7-71d7-4633-9457-87861097b22d.png">

**Comment by NickvdMeij** [comment]
@magento give me 2.4.3-p1 instance

**Comment by NickvdMeij** [comment]
> Hi @NickvdMeij ,
> 
> Thank you for raising an issue and need your assistance on rest api for optionId. Kindly confirm below rest api what we have tried for updating.
> 
> <img alt="Screenshot 2022-06-20 at 5 35 23 PM" width="1440" src="https://user-images.githubusercontent.com/51681379/174599422-726a22c5-393a-4490-b2d0-aad8d2105984.png">
> 
> From Frontend options for bundle product:
> 
> <img alt="Screenshot 2022-06-20 at 5 38 56 PM" width="1331" src="https://user-images.githubusercontent.com/51681379/174599483-e4f4bfd7-71d7-4633-9457-87861097b22d.png">

This is not the bug i was reffering to. The bug happens currently since update 2.4.3-p1 but sadly i cant get a clean magento instance to test it for you guys, or setup a testcase for that matter.

Like in the bug description, if you have multiple stores, it removed all bundle options from the previous siteview if you update them in a different site view using the REST api. So the next sequence happens:

* create bundle product
** product is now available in all site views
* update bundle options in site 1
** product options are now only available in site 1, but site 2 and 3 have their options deleted
* update bundle options in site 2
** product options are now only available in site 2, but site 1 and 3 have their options deleted
* update bundle options in site 3
** product options are now only available in site 3, but site 1 and 2 have their options deleted

**Comment by NickvdMeij** [comment]
> Hi @NickvdMeij, unfortunately there is no ability to deploy Magento instance at the moment. Please try again later.

@engcom-Delta please fix this. Been trying to get a test instance for a while now and it always seems to be unavailable...

**Comment by NickvdMeij** [comment]
@magento give me 2.4-develop instance

**Comment by NickvdMeij** [comment]
After finally being able to do some testing on a clean magento image, I sadly did not manage to reproduce it in the 2.4.4-develop branch. However, I did come across another illogical bug surrounding the same workflow.

In the test instance, i created 3 websites+stores+storeviews names store_view_1 to store_view_3. I created 3 virtual products, 1 meant as "main product", which is always required in the configuration of the bundle, and 2 optional virtual products, who are not required in the bundle product.

When doing a `POST` to https://7ff998fa60b9f771262155e3bd82428a.instances.magento-community.engineering/rest/store_view_1/V1/products (keep in mind the `store_view_1` in the url, this is the storeview we want to update), it updates the prices. Below you can find the body:

```
{
   "product":{
      "sku":1004,
      "name":"Bundle product 1",
      "attribute_set_id":4,
      "price":0,
      "status":1,
      "visibility":4,
      "type_id":"bundle",
      "extension_attributes":{
         "stock_item":{
            "is_in_stock":1,
            "qty":1000000
         },
         "bundle_product_options":[
            {
               "option_id":0,
               "title":"main product",
               "required":1,
               "type":"checkbox",
               "position":0,
               "product_links":[
                  {
                     "id":"2049",
                     "sku":"1001",
                     "option_id":0,
                     "qty":1,
                     "price":700,
                     "price_type":0,
                     "is_default":1,
                     "can_change_quantity":0
                  }
               ]
            },
            {
               "option_id":1,
               "title":"optional product 1",
               "required":0,
               "type":"checkbox",
               "position":1,
               "product_links":[
                  {
                     "id":"2050",
                     "sku":"1002",
                     "option_id":1,
                     "qty":1,
                     "price":150,
                     "price_type":0,
                     "is_default":0,
                     "can_change_quantity":0
                  }
               ]
            },
            {
               "option_id":2,
               "title":"optional product 2",
               "required":0,
               "type":"checkbox",
               "position":2,
               "product_links":[
                  {
                     "id":"2051",
                     "sku":"1003",
                     "option_id":2,
                     "qty":1,
                     "price":150,
                     "price_type":0,
                     "is_default":0,
                     "can_change_quantity":0
                  }
               ]
            }
         ]
      },
      "custom_attributes":[
         {
            "attribute_code":"price_view",
            "value":1
         },
         {
            "attribute_code":"price_type",
            "value":1
         },
      ]
   }
}
```

It will create the product in the specified storeview. All seems to work perfect.

*HOWEVER*

when making a POST to https://7ff998fa60b9f771262155e3bd82428a.instances.magento-community.engineering/rest/store_view_2/V1/products (keep in mind the difference in storeview) with the following body:

```
{
   "product":{
      "sku":1004,
      "name":"Bundle product 1",
      "attribute_set_id":4,
      "price":0,
      "status":1,
      "visibility":4,
      "type_id":"bundle",
      "extension_attributes":{
         "stock_item":{
            "is_in_stock":1,
            "qty":1000000
         },
         "bundle_product_options":[
            {
               "option_id":0,
               "title":"main product",
               "required":1,
               "type":"checkbox",
               "position":0,
               "product_links":[
                  {
                     "id":"2049",
                     "sku":"1001",
                     "option_id":0,
                     "qty":1,
                     "price":999,
                     "price_type":0,
                     "is_default":1,
                     "can_change_quantity":0
                  }
               ]
            },
            {
               "option_id":1,
               "title":"optional product 1",
               "required":0,
               "type":"checkbox",
               "position":1,
               "product_links":[
                  {
                     "id":"2050",
                     "sku":"1002",
                     "option_id":1,
                     "qty":1,
                     "price":999,
                     "price_type":0,
                     "is_default":0,
                     "can_change_quantity":0
                  }
               ]
            },
            {
               "option_id":2,
               "title":"optional product 2",
               "required":0,
               "type":"checkbox",
               "position":2,
               "product_links":[
                  {
                     "id":"2051",
                     "sku":"1003",
                     "option_id":2,
                     "qty":1,
                     "price":999,
                     "price_type":0,
                     "is_default":0,
                     "can_change_quantity":0
                  }
               ]
            }
         ]
      },
      "custom_attributes":[
         {
            "attribute_code":"price_view",
            "value":1
         },
         {
            "attribute_code":"price_type",
            "value":1
         },
      ]
   }
}
```

It updates the prices ***IN ALL STOREVIEWS***. Is this normal? Because from what i can read in the documentation it should only update the prices for the specified storeview (in this case store_view_2) and not in store_view_1 or store_view_3.

In our own 2.4.3-p1 instance of magento, doing the same flow results in store_view_1 with all its virtual products with a price of 0, and only have the store_view_2 with all virtual products on 999 as specified in the request above. So something definately changed between these 3 versions (prior to `2.4.3-p1`, in `2.4.3-p1` and in `2.4.4-develop`)

**Comment by NickvdMeij** [comment]
https://github.com/magento give me 2.4.3-p1 instance

**Comment by NickvdMeij** [comment]
@magento give me 2.4.3-p1 instance

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,
Thank you for providing details. We tried to process the it but its not working and throwing different error for first request.

Request:
{
   "product":{
      "sku":1004,
      "name":"Bundle product 1",
      "attribute_set_id":4,
      "price":0,
      "status":1,
      "visibility":4,
      "type_id":"bundle",
      "extension_attributes":{
         "stock_item":{
            "is_in_stock":1,
            "qty":1000000
         },
         "bundle_product_options":[
            {
               "option_id":0,
               "title":"main product",
               "required":1,
               "type":"checkbox",
               "position":0,
               "product_links":[
                  {
                     "id":"2049",
                     "sku":"1001",
                     "option_id":0,
                     "qty":1,
                     "price":700,
                     "price_type":0,
                     "is_default":1,
                     "can_change_quantity":0
                  }
               ]
            },
            {
               "option_id":1,
               "title":"optional product 1",
               "required":0,
               "type":"checkbox",
               "position":1,
               "product_links":[
                  {
                     "id":"2050",
                     "sku":"1002",
                     "option_id":1,
                     "qty":1,
                     "price":150,
                     "price_type":0,
                     "is_default":0,
                     "can_change_quantity":0
                  }
               ]
            },
            {
               "option_id":2,
               "title":"optional product 2",
               "required":0,
               "type":"checkbox",
               "position":2,
               "product_links":[
                  {
                     "id":"2051",
                     "sku":"1003",
                     "option_id":2,
                     "qty":1,
                     "price":150,
                     "price_type":0,
                     "is_default":0,
                     "can_change_quantity":0
                  }
               ]
            }
         ]
      },
      "custom_attributes":[
         {
            "attribute_code":"price_view",
            "value":1
         },
         {
            "attribute_code":"price_type",
            "value":1
         },
      ]
   }
}

Response: 
Specified request cannot be processed.
Hence , request to review the provided information.

**Comment by NickvdMeij** [comment]
@engcom-Delta perhaps have a look at your own test instances. It seems that they are once more broken. I've already debugged this twice for you guys now, its getting a bit annoying I must say.
I'd suggest you setup a test image yourself and go through the steps i described twice (and applied on the by you  provided test image which is now totally broken for some reason) to reproduce this issue.

![image](https://user-images.githubusercontent.com/4169805/177283929-8585a919-1e1c-4a88-b165-0b5ac154a429.png)

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,

Thank you for more details. We tried to reproduce the issue on magento 2.4 develop instance. We observed that after creating bundle product with multiple virtual products , we could not able to modify the price for options .
Please correct me if my steps are wrong .

Here is reference video.
https://www.loom.com/share/3818aaa8c89d4a9e9f8b0dc2fd3a1c2a

**Comment by NickvdMeij** [comment]
@engcom-Delta this is incorrect. You can setup prices for bundle options:

![image](https://user-images.githubusercontent.com/4169805/177729881-157be0b5-b706-4878-904e-8cfb9448fd6b.png)

I'll try once (for the **FINAL** time) try to set it up in one of the test environments you guys provide. Please, **DO NOT** remove this test image before you verify it!!!!!!!

**Comment by NickvdMeij** [comment]
@magento give me 2.4.3-p1 instance

**Comment by NickvdMeij** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by NickvdMeij** [comment]
@magento give me 2.4-develop instance

**Comment by NickvdMeij** [comment]
@magento give me 2.4-develop instance

**Comment by NickvdMeij** [comment]
@engcom-Delta test image is setup again. Please do not lose it this time and verify it a.s.a.p. please.
Also here is a video explaining the steps i took: https://youtu.be/4FZlHBSJXm4

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,
Yes, Same instance throws error like "The server returned a "404 Not Found".". let me try on local instance once again .

Thanks

**Comment by NickvdMeij** [comment]
> Hi @NickvdMeij ,
> 
> 1. We observed that if we set for bundle product of 'Dynamic price =No' , then we can see that options price presence as below.
> 
> <img alt="Screenshot 2022-07-08 at 5 35 17 PM" width="1008" src="https://user-images.githubusercontent.com/51681379/178014590-b3c42e83-f2f2-4f9f-8c11-00906b788c36.png">
> 
> <img alt="Screenshot 2022-07-08 at 5 31 39 PM" width="1345" src="https://user-images.githubusercontent.com/51681379/178015031-a1c62bf4-d645-43ed-ad5e-8e9850e2357e.png">
> 
> 2. Still we are working on API, right now we have been getting error for processing the request.
> 
> Thanks

on #1, this was not any of the related issues i opened the issue for, but thanks for the information.
on #2, thanks for the info, any ETA when the fix will be available?

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,
Thank you for providing  detailed information, We tried to reproduce the issue on magento 2.4 develop instance , We found that if we update the price from store 1 , that updated price is getting reflected across all the store_view's. Moreover , it is expected behaviour  i believe, Kindly correct me if i am wrong or share me the document if you have.

<img width="855" alt="Screenshot 2022-07-14 at 11 19 50 AM" src="https://user-images.githubusercontent.com/51681379/178977132-9886617c-ea6a-4d00-ad0b-dff94c76be99.png">

<img width="1440" alt="Screenshot 2022-07-14 at 11 23 43 AM" src="https://user-images.githubusercontent.com/51681379/178977183-30f2b167-e80a-4569-acd5-be5d0325d148.png">

<img width="904" alt="Screenshot 2022-07-14 at 11 32 41 AM" src="https://user-images.githubusercontent.com/51681379/178977288-ec08c8d2-8a8e-4159-a200-0419e74b2b83.png">

**Comment by NickvdMeij** [comment]
> aviour i believ

Hey @engcom-Delta,

Sorry for comming back a bit later than usual, had a few busy days.
Regarding your question, I believe its not expected behaviour. In the documentation (https://developer.adobe.com/commerce/webapi/rest/tutorials/) it stated the following:

> <html>
> <body>
> <p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Although some steps require that you configure Commerce in some way, you perform most steps by sending one or more REST calls to Commerce. Each step that makes a REST call provides the following information:</p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="font-weight: var(--spectrum-body-m-strong-text-font-weight,var(--spectrum-global-font-weight-bold));">Endpoint:</strong></p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This section lists the HTTP verb and full path to the endpoint. The basic structure of a REST call in Commerce is</p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="spectrum-Code spectrum-Code--sizeS spectrum-Well css-v5m9i" style="font-family: var(--spectrum-code-s-text-font-family,var(--spectrum-alias-code-text-font-family)); font-size: var(--spectrum-code-s-text-size,var(--spectrum-alias-font-size-default)); font-style: var(--spectrum-code-s-text-font-style,var(--spectrum-global-font-style-regular)); font-weight: var(--spectrum-code-s-text-font-weight,var(--spectrum-alias-code-text-font-weight-regular)); letter-spacing: var(--spectrum-code-s-text-letter-spacing,var(--spectrum-global-font-letter-spacing-none)); line-height: var(--spectrum-code-s-text-line-height,var(--spectrum-alias-code-text-line-height)); margin: 0px; color: var(--spectrum-code-s-text-color,var(--spectrum-alias-text-color)); --spectrum-well-padding:var(--spectrum-global-dimension-size-200); --spectrum-well-border-width:var(--spectrum-alias-border-size-thin,var(--spectrum-global-dimension-static-size-10)); --spectrum-well-margin-top:var(--spectrum-global-dimension-size-50); --spectrum-well-min-width:var(--spectrum-global-dimension-size-3000); background-color: var(--spectrum-global-color-gray-100); border-color: var(--spectrum-well-border-color); border-radius: var(--spectrum-alias-border-radius-regular,var(--spectrum-global-dimension-size-50)); border-style: solid; border-width: var(--spectrum-well-border-width,var(--spectrum-alias-border-size-thin)); display: inline-block; min-width: auto; padding: 0 var(--spectrum-global-dimension-size-50); word-break: break-word; text-align: left;">&lt;HTTP verb&gt; http://&lt;host&gt;/rest/&lt;scope&gt;/&lt;endpoint&gt;</code></p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">where:</p>
> 
> ELEMENT | DESCRIPTION
> -- | --
> HTTP verb | One of GET, POST, PUT, or DELETE
> host | The hostname or IP address (and optionally, port) of the Commerce installation.
> scope | Specifies which store the call affects. In this tutorial, this value is default.
> endpoint | The full URI (Uniform Resource Identifier) to the endpoint. These values always start with /V1. For example, /V1/orders/4.
> 
> <p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="font-weight: var(--spectrum-body-m-strong-text-font-weight,var(--spectrum-global-font-weight-bold));">Scope:</strong></p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The<span> </span><strong style="font-weight: var(--spectrum-body-m-strong-text-font-weight,var(--spectrum-global-font-weight-bold));">Scope:</strong><span> </span>section is included when the tutorial requires that you send requests to different stores.</p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="font-weight: var(--spectrum-body-m-strong-text-font-weight,var(--spectrum-global-font-weight-bold));">HTTP headers:</strong></p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This section indicates which key/value pairs you must specify in the HTTP headers. All calls require one or more HTTP headers.</p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="font-weight: var(--spectrum-body-m-strong-text-font-weight,var(--spectrum-global-font-weight-bold));">Payload:</strong></p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This section lists the information that is sent to Commerce. All payload samples are valid and can be copied and pasted into your calls, but you might need to change the<span> </span><code class="spectrum-Code spectrum-Code--sizeS spectrum-Well css-v5m9i" style="font-family: var(--spectrum-code-s-text-font-family,var(--spectrum-alias-code-text-font-family)); font-size: var(--spectrum-code-s-text-size,var(--spectrum-alias-font-size-default)); font-style: var(--spectrum-code-s-text-font-style,var(--spectrum-global-font-style-regular)); font-weight: var(--spectrum-code-s-text-font-weight,var(--spectrum-alias-code-text-font-weight-regular)); letter-spacing: var(--spectrum-code-s-text-letter-spacing,var(--spectrum-global-font-letter-spacing-none)); line-height: var(--spectrum-code-s-text-line-height,var(--spectrum-alias-code-text-line-height)); margin: 0px; color: var(--spectrum-code-s-text-color,var(--spectrum-alias-text-color)); --spectrum-well-padding:var(--spectrum-global-dimension-size-200); --spectrum-well-border-width:var(--spectrum-alias-border-size-thin,var(--spectrum-global-dimension-static-size-10)); --spectrum-well-margin-top:var(--spectrum-global-dimension-size-50); --spectrum-well-min-width:var(--spectrum-global-dimension-size-3000); background-color: var(--spectrum-global-color-gray-100); border-color: var(--spectrum-well-border-color); border-radius: var(--spectrum-alias-border-radius-regular,var(--spectrum-global-dimension-size-50)); border-style: solid; border-width: var(--spectrum-well-border-width,var(--spectrum-alias-border-size-thin)); display: inline-block; min-width: auto; padding: 0 var(--spectrum-global-dimension-size-50); word-break: break-word; text-align: left;">id</code><span> </span>values that Commerce returns.</p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="font-weight: var(--spectrum-body-m-strong-text-font-weight,var(--spectrum-global-font-weight-bold));">Response:</strong></p><p class="spectrum-Body spectrum-Body--sizeM css-9ytko9" style="font-size: var(--spectrum-body-m-text-size,var(--spectrum-global-dimension-font-size-200)); font-style: normal; font-weight: 400; letter-spacing: normal; line-height: var(--spectrum-body-m-text-line-height,var(--spectrum-alias-body-text-line-height)); margin-bottom: 0px; margin-top: var(--spectrum-global-dimension-size-300); text-transform: none; font-family: adobe-clean, &quot;Source Sans Pro&quot;, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Trebuchet MS&quot;, &quot;Lucida Grande&quot;, sans-serif; color: rgb(75, 75, 75); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This section lists the information that Commerce sends to the REST client. These values are often referenced in other steps in the tutorial. The values Commerce returns might be different than the values listed in the examples provided in this tutorial.</p>
> </body>
> </html>

As you can see, it states the following regarding the scope: "Specifies which store the call affects. In this tutorial, this value is default.". This means the expected behaviour would be that only the siteview/scope given in the API request, should be affected by the REST API call to update the product. Therefor, having the prices set to 0 for other siteviews/scopes (behaviour shown prior to v2.4.4, for example in v2.4.3-p1) or like you yourself experienced having the prices set to all siteviews (behaviour shown in version later than v2.4.4) is not expected behaviour.

Let me know what you think?

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,
Thank you for your inputs. We have moved this ticket to 'On Hold' at this movement , we will update you after confirmation from product owner.

Regards,

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,
We have got update from Product Owner like If we are trying to set different prices for bundle options for different storeviews of the same website, then we cannot do this since bundle options as well as their prices are the global level attributes and cannot be customized on storeview level, the only thing we can customize is the option’s title. 

Thanks

**Comment by NickvdMeij** [comment]
@engcom-Delta I honestly am very displeased with that answer. In versions prior to 2.4.3, this worked and was in use for many years and we as end consumers of the API count on this to work like it did before. This functionality now **broke** because of changes you guys made, without any documentation or clearification in the release logs. I report this bug and now you refuse to fix the thing you broke. This to me sound more like an excuse to not have to fix the bug.

While you are at it, can you please tell me which other API endpoint **ARE NOT AFFECTED BY THE SCOPE**, cause there is absolutely no documentation to be found anywhere on which calls should or shouldn't be affected by scope.

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij ,
We are apologize for causing inconvenience, surely we will take a look into it once again and confirm you .
Thanks for understanding.

Regards,

**Comment by NickvdMeij** [comment]
2 weeks pass, legend has it they are still in the sprint meeting

**Comment by engcom-Hotel** [comment]
Hello @NickvdMeij,

We are still working on this and provide you with an update soon on this.

Thanks

**Comment by NickvdMeij** [comment]
Any update regarding this issue? It's been almost 4 weeks now

**Comment by engcom-Delta** [comment]
Hii @[NickvdMeij](https://github.com/NickvdMeij),

We have tried to reproduce this issue in magento 2.4.2-p2, 2.4.3 and 2.4-develop  but the issue is not reproducible .

Steps are followed to reproduce the issue.

1.Created three websites namely Main Website,website1 and website2 and respective stores are Main Website store, store1 and store2 and respective store_views are Default Store View.

<img width="1397" alt="Screenshot 2022-09-08 at 6 32 03 PM" src="https://user-images.githubusercontent.com/51681379/189142493-22d521b0-a412-436e-9842-7f1dd3bd9030.png">


2. Created three virtual product

<img width="1401" alt="Screenshot 2022-09-08 at 6 33 46 PM" src="https://user-images.githubusercontent.com/51681379/189139767-2ac58502-6616-4cf5-b471-f80caf3256c7.png">

3.Created Bundle product through REST API(POSTMAN)
<img width="1512" alt="Screenshot 2022-09-08 at 6 45 42 PM" src="https://user-images.githubusercontent.com/51681379/189140149-0b3cb5c5-87fb-48bf-ba84-af25785b7005.png">

<img width="1389" alt="Screenshot 2022-09-08 at 6 47 24 PM" src="https://user-images.githubusercontent.com/51681379/189140491-22a9687a-119b-442f-b5a2-49970c99ebf7.png">
 
<img width="1455" alt="Screenshot 2022-09-08 at 6 50 16 PM" src="https://user-images.githubusercontent.com/51681379/189143052-2f7741b5-daf7-460b-b731-96634abc98ca.png">


4.update bundle product in  storeview1 with modifying the price of bundle product’s options
<img width="1458" alt="Screenshot 2022-09-08 at 6 59 09 PM" src="https://user-images.githubusercontent.com/51681379/189141220-41f67d41-0728-4fe0-a8f3-2b0335ad62c4.png">
5  Enabling in all websites
<img width="1463" alt="Screenshot 2022-09-08 at 7 01 59 PM" src="https://user-images.githubusercontent.com/51681379/189141365-df017aab-02bc-461d-b178-521d373e8ffd.png">
6.update bundle product in  storeview2 with modifying the price of bundle product’s options
<img width="610" alt="Screenshot 2022-09-08 at 7 04 21 PM" src="https://user-images.githubusercontent.com/51681379/189141649-69baae18-cebc-45d6-804c-f32a04b036b5.png">
7. We checked in all store views the price value is reflected in all store views. 
<img width="1395" alt="Screenshot 2022-09-08 at 7 09 17 PM" src="https://user-images.githubusercontent.com/51681379/189141868-548c170e-3be1-4ea6-8547-fa29337de238.png">

In all above specified M2 versions, The price value is reflected in all store views which is the expected behavior.

Please let us know if we are missing any steps here.

Thanks.

**Comment by engcom-Delta** [comment]
Hi @NickvdMeij 

We have noticed that, this issue has not been updated for a period of 14 Days.Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by NickvdMeij** [comment]
@magento give me 2.4-develop instance

**Comment by NickvdMeij** [comment]
@engcom-Delta here you go, yet another video **proving** the bug still exist: [youtube link ](https://youtu.be/iWd1pNuEGW0) . Please do a better job actually _following_ the 2 video's I made now, as well as the written guide how to reproduce it! I really get the feeling I'm being trolled, already spend way too much time trying to have you guys recognize the problem....

**Comment by engcom-Hotel** [comment]
Hello @NickvdMeij,

We are an apology for this. We are reopening this ticket for further investigation and marking the other issue as a duplicate of this.

Thanks

**Comment by engcom-November** [comment]
This issue is reproducible on 2.4-develop instance with above steps followed mentioned in youtube [link](https://www.youtube.com/watch?v=iWd1pNuEGW0)

**Comment by engcom-November** [comment]
Hi @NickvdMeij ,
The issues mentioned in the youtube [video](https://www.youtube.com/watch?v=iWd1pNuEGW0) are actually not issues.
Please find the reasons below:
**Issue 1**: Rest API - not assigning bundle product to all websites - This is because of not passing "website_ids" in the payload. There is no issue on Magento 2.4-develop instance if all "website_ids" are given in the payload during product creation.
![image](https://user-images.githubusercontent.com/60198231/197199546-50268635-582d-4803-ad4d-5a1663e7cf97.png)

**Issue 2**: Price is getting updated to all Store views even though we are updating only for specific store view 3. This is because of the catalog price scope configuration.
Stores - Settings - Configuration - Catalog - Catalog - Price scope - Set to "Website" and save. Reindex and cache clean then this issue 2 is not reproducible. Price is only updated for specific store view when updated from API or UI.
However on doing the same, **Price is becoming 0 for other store views** which is an issue actually. Hence updating the description with clear steps and confirming the issue as its not reproducible on UI.
User is able to save different price for bundle options in different store scopes when updated from UI but not able to do from API.

**Comment by NickvdMeij** [comment]
Bug still exists in Magento version 2.4.7-p1 and causes issues when dealing with multiple stores. Is there any sight on when this will be picked up, its been open for 2 years now....
