### ISSUE TITLE
Description text moves to the top of the product page

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#3559]
Description text which contains a `<span>` tag, moves to the top of the page.

Example:
Description text in back end - "Buy this beautiful `<span class="blue">blue</span>` dress today. Free shipping."

In front end the description text displays correctly. However, at the very top of the product page, the text following the `<span>` tag is also displayed:

"blue dress today. Free shipping."

**Comment by vil11** [comment]
Hello, @lgarridoj!

HTML tags do not brake the "View Product" Storefront page layout neither for Blank nor for Luma theme.
The described issue is about Storefront page **source** which contains unexpected tags, isn't it? If so, take a look on [this one](https://github.com/magento/magento2/issues/2613). Thx!

FYI:
- It would be really great to add a screenshot in order to clarify the description in case of questions like mine;
- [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

:sunny: Dmytro Vilchynskyi, M2 QA engineer.

**Comment by jibrandlr** [comment]
@vil11 Hi, please see the screenshots attached.
![meta](https://cloud.githubusercontent.com/assets/8398744/13438567/27235364-dfaf-11e5-83c6-c9be112fc25a.jpg)
![top](https://cloud.githubusercontent.com/assets/8398744/13438565/271f2d02-dfaf-11e5-8348-79498132eaad.jpg)
![details](https://cloud.githubusercontent.com/assets/8398744/13438568/2724c6f4-dfaf-11e5-84b7-d5b50bf744c7.jpg)
![description](https://cloud.githubusercontent.com/assets/8398744/13438566/27219aa6-dfaf-11e5-9d5f-ef21e6baea17.jpg)
![html](https://cloud.githubusercontent.com/assets/8398744/13438569/2726cf1c-dfaf-11e5-8721-851465b2d929.jpg)

**Comment by vil11** [comment]
Thanks for screenshots. Looks like these issues are related indeed. Internal ticket **MAGETWO-48511**.

**Comment by katmoon** [comment]
The issue has been fixed.
@lgarridoj, thank you for reporting it!

Thanks,
Kateryna.

**Comment by katmoon** [comment]
Internal ticket was `MAGETWO-51832`

**Comment by jibrandlr** [comment]
@katmoon I just upgraded to ver. 2.0.6 (composer installation) and the issue is still present

**Comment by katmoon** [comment]
@lgarridoj 

2.0.6 is a patch version for individual fixes. The issue is in develop branch and will be included into 2.1 release.
