### ISSUE TITLE
AlertProcessor - Argument #2 ($storeId) must be of type int, string given

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#35602]
### Preconditions and environment

- Magento version 2.4.4
- PHP8.1

### Steps to reproduce
- Enable product alert stock in BO (Configuration > Catalog >Product Alerts > Allow Alert When Product Comes Back in Stock > Yes, Allow Alert When Product Price Changes - Yes)
- Reindex and cache flush
- Front end - Login as customer - Select a Product without stock - Register to a product stock alert
(Notify me when the price drops, Notify me when this product is in stock)
- Add stock to that product from admin
- Launch consumers

### Expected result

Alert stock email being sent

### Actual result
Emails not triggered for Product Alerts

```
[2022-06-10T07:31:56.520650+00:00] .CRITICAL: Magento\ProductAlert\Model\Mailing\ErrorEmailSender::execute(): Argument #2 ($storeId) must be of type int, string given, called in /var/www/html/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php on line 130 [] []
```

### Additional information

I guess (not tested) that change could solve the issue 
```
Magento\Store\Model\Store

ACTUAL CODE
   /**
     * Get store identifier
     *
     * @return  int
     */
    public function getId()
    {
        return $this->_getData(self::STORE_ID);
    }


PROPOSED FIX

   /**
     * Get store identifier
     *
     * @return  int
     */
    public function getId(): int
    {
        return (int) $this->_getData(self::STORE_ID);
    }

```
(of course, StoreInterface interface should be modified accordingly.)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch using MailHog for emails and the issue is reproducible.
Emails are not getting triggered for Product alerts.
`[2022-06-27T11:32:50.359599+00:00] main.CRITICAL: The specified "/var/www/html/magento2/generated/code/Magento/AsynchronousOperations/Api/Data/AsyncResponseInterfaceFactory.php.116986" file couldn't be written. Warning!file_put_contents(/var/www/html/magento2/generated/code/Magento/AsynchronousOperations/Api/Data/AsyncResponseInterfaceFactory.php.116986): Failed to open stream: Permission denied
Class Magento\AsynchronousOperations\Api\Data\AsyncResponseInterfaceFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []
[2022-06-27T11:32:50.359932+00:00] main.ERROR: Impossible to process constructor argument Parameter #5 [ <required> Magento\AsynchronousOperations\Api\Data\AsyncResponseInterfaceFactory $asyncResponse ] of Magento\WebapiAsync\Controller\Rest\AsynchronousRequestProcessor class [] []
[2022-06-27T11:32:50.360515+00:00] main.CRITICAL: ReflectionException: Class "Magento\AsynchronousOperations\Api\Data\AsyncResponseInterfaceFactory" does not exist in /var/www/html/magento2/lib/internal/Magento/Framework/GetParameterClassTrait.php:34
Stack trace:
#0 /var/www/html/magento2/lib/internal/Magento/Framework/GetParameterClassTrait.php(34): ReflectionClass->__construct()
#1 /var/www/html/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(42): Magento\Framework\Code\Reader\ClassReader->getParameterClass()
#2 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor()
#3 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters()
#4 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#5 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#6 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#7 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#8 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#9 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#10 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#11 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#12 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#13 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#14 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#15 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#16 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#17 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#18 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\ObjectManager\ObjectManager->get()
#19 /var/www/html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#20 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#21 /var/www/html/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#22 {main}

Next ReflectionException: Impossible to process constructor argument Parameter #5 [ <required> Magento\AsynchronousOperations\Api\Data\AsyncResponseInterfaceFactory $asyncResponse ] of Magento\WebapiAsync\Controller\Rest\AsynchronousRequestProcessor class in /var/www/html/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:57
Stack trace:
#0 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor()
#1 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters()
#2 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#3 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#4 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#5 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#6 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#7 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#8 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#9 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#10 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#11 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#12 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#13 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#14 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#15 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#16 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\ObjectManager\ObjectManager->get()
#17 /var/www/html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#18 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#19 /var/www/html/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#20 {main} {"report_id":"d5ef304eba52ee58e1c5b104ba085a424ddbf968eed10c41359010b6ea0f44bf"} []`

**Comment by artskirk** [comment]
@magento I am working on this

**Comment by renatocason** [comment]
In case anybody stumbles upon this issue, the store id type is only coming up when trying to send an error email caused by another error in the `getFilteredContent` function. The following patch applies a self-contained fix for both, is can be applied directly to `magento/module-product-alert`.

```
diff --git a/Block/Email/AbstractEmail.php b/Block/Email/AbstractEmail.php
index 5708180..d81a362 100644
--- a/Block/Email/AbstractEmail.php
+++ b/Block/Email/AbstractEmail.php
@@ -69,6 +69,10 @@ abstract class AbstractEmail extends \Magento\Framework\View\Element\Template
      */
     public function getFilteredContent($content)
     {
+        if (is_null($content)) {
+            return '';
+        }
+
         return $this->_maliciousCode->filter($content);
     }
 
diff --git a/Model/Mailing/AlertProcessor.php b/Model/Mailing/AlertProcessor.php
index 83ac4ab..754bb56 100644
--- a/Model/Mailing/AlertProcessor.php
+++ b/Model/Mailing/AlertProcessor.php
@@ -126,7 +126,7 @@ class AlertProcessor
         if (!empty($errors)) {
             /** @var Website $website */
             $website = $this->storeManager->getWebsite($websiteId);
-            $defaultStoreId = $website->getDefaultStore()->getId();
+            $defaultStoreId = (int)$website->getDefaultStore()->getId();
             $this->errorEmailSender->execute($errors, $defaultStoreId);
         }
     }
```

**Comment by APanteleychuk** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by nobodyfamouz** [comment]
Any official progress on this? It is blocking #35674 which is a pretty big problem. Thanks!

**Comment by katmoon** [comment]
The fix is available as a QPT patch with ACSD-47937 ID. See https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-26/acsd-47937-price-drop-notifications-are-not-sent.html?lang=en

**Comment by shunmugakumaran** [comment]
Hi still the issue is reproducible in magento 2.4.6-p1 adobe commerce .. after running the CRON also mail not triggering.. the issue logs in debug as follows 

report.CRITICAL: Magento\ProductAlert\Model\Mailing\ErrorEmailSender::execute(): Argument #2 ($storeId) must be of type int, string given, called in /app/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php on line 130

Kindly give the solution..! Thank u

**Comment by hostep** [comment]
Why did this issue got closed? @katmoon: do you have an explanation? Can you link to some commits that fixed it?

**Comment by engcom-Hotel** [comment]
As per the [JIRA](https://jira.corp.adobe.com/browse/AC-5969) comment, the issue is no more reproducible. Hence JIRA and GitHub issue has been closed.

**Comment by nicolasmanezimprontus** [comment]
I have the same issue in version 2.4.5-p3.

**Comment by engcom-Dash** [comment]
Hi @Nuranto 

The issue is still reproducible. So reopening the ticket again.

Thanks.

**Comment by hostep** [comment]
Closed without telling us why? But it seems like some commits made it to `2.4-develop` branch, that mention this error: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-5969&type=commits (not sure if it actually fixes the issue, the changes are not what I would expect, but I may be missing something...)

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5969 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-5969&type=commits


Thanks

**Comment by HenKun** [comment]
I second @hostep . I cannot imagine those commits are fixing the actual issue.

**Comment by jsuchocki** [comment]
Like it was mentioned earlier by @hostep , issue is definitely not fixed. Store ID is nowhere casted to int and fixes with name AC-5969 are not even related to the issue described in the first post. 2 years and still not fixed in core while there were multiple fixes suggested already.

**Comment by hostep** [comment]
@engcom-Bravo, given the previous few comments, can you try to ask the internal team about this? What their thoughts are on the discussion if this issue is really fixed or not?

**Comment by engcom-Dash** [comment]
Hi @Nuranto 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance and the issue is not reproducible.

Steps to reproduce

1. Enable product alert stock in BO (Configuration > Catalog >Product Alerts > Allow Alert When Product Comes Back in Stock > Yes, Allow Alert When Product Price Changes - Yes)
2. Reindex and cache flush
3. Front end - Login as customer - Select a Product without stock - Register to a product stock alert
4. (Notify me when the price drops, Notify me when this product is in stock)
5. Add stock to that product from admin
6. The locale in configuration>general>general should be locale time(eg:Asia/Kolkatta)
7. in Configuration>catalog>catalog>Product run alert settings > set frequency as daily and time
8. Run cron:run once the set time is passed
9. Reindex and clear the cache
10. Check the UI if the product is back in stock and the product alert mail is received

We are able to receive the alert mails after the cron:run is successful

Please refer the attached screenrecording and let us know if we missed anything.


https://github.com/magento/magento2/assets/60198592/b345edc9-1510-4e10-add0-10faeabc698d

**Comment by gzldx** [comment]
I found the root cause which I reproduced from my local. If someone subscribe product alert, and his account is destroyed, the product alert process is stuck by the error.

report.ERROR: Cron Job catalog_product_alert has an error: No such entity with customerId = xxxxx.
report.CRITICAL: Magento\Framework\Exception\NoSuchEntityException: No such entity with customerId = xxxxx in /vendor/magento/framework/Exception/NoSuchEntityException.php:50

> public function process(string $alertType, array $customerIds, int $websiteId): void
>     {
>         $this->validateAlertType($alertType);
>         $errors = $this->processAlerts($alertType, $customerIds, $websiteId);
>         if (!empty($errors)) {
>             /** @var Website $website */
>             $website = $this->storeManager->getWebsite($websiteId);
>             $defaultStoreId = $website->getDefaultStore()->getId();
>             $this->errorEmailSender->execute($errors, $defaultStoreId);
>         }
>     }

When the process execute and has errors, it will call $this->errorEmailSender->execute($errors, $defaultStoreId), but the defaultStoreId is not int, and met error again:
report.CRITICAL: Magento\ProductAlert\Model\Mailing\ErrorEmailSender::execute(): Argument #2 ($storeId) must be of type int, string given, called in /var/www/html/eshop/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php on line 130

I deleted that record in table product_alert_stock, it is normal again.

**Comment by hostep** [comment]
Thanks!

@engcom-Dash, is this enough info for you to try to reproduce again?

**Comment by engcom-Dash** [comment]
Hi @Nuranto @gzldx 

We have verified the issue on Magento 2.4.7 and the issue is not reproducible.

We have followed the below steps:

1. Create 2 customer accounts - c1 and c2
2. Subscribe for product alert mails for both customers.
3. Add stock to that product from admin
4.The locale in configuration>general>general should be locale time(eg:Asia/Kolkatta)
5. In Configuration>catalog>catalog>Product run alert settings > set frequency as daily and time
6. Delete the c2 customer account.
7. Run cron: run after the time set in frequency has passed
8. Check if you got the product stock alert mail from c1 

We are getting product mails for customer c1 and not getting the mails or any errors for c2.

Please let us know if this is the expected behavior. Refer to the screen recording.

https://github.com/magento/magento2/assets/60198592/eecc13d0-e407-436d-a194-52a908b26d6f

Thanks.

**Comment by shunmugakumaran** [comment]
@Nuranto @engcom-Dash @gzldx We faced the same issue while we do upgrade from 2.4.3-p2 to 2.4.6-p2. Applied below patch resolved the issue


```
diff --git a/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php b/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php
index 83ac4ab..bb4c83a 100755
--- a/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php
+++ b/vendor/magento/module-product-alert/Model/Mailing/AlertProcessor.php
@@ -24,6 +24,7 @@ use Magento\ProductAlert\Model\Stock;
 use Magento\Store\Api\Data\WebsiteInterface;
 use Magento\Store\Model\StoreManagerInterface;
 use Magento\Store\Model\Website;
+use Magento\ProductAlert\Model\Mailing\ErrorEmailSender;
 
 /**
  * Class for mailing Product Alerts
@@ -126,8 +127,8 @@ class AlertProcessor
         if (!empty($errors)) {
             /** @var Website $website */
             $website = $this->storeManager->getWebsite($websiteId);
-            $defaultStoreId = $website->getDefaultStore()->getId();
-            $this->errorEmailSender->execute($errors, $defaultStoreId);
+            $defaultStoreId = (int)$website->getDefaultStore()->getId();
+            $this->errorEmailSender->execute($errors, (int)$defaultStoreId);
         }
     }
 
-- 
2.25.1
```

**Comment by gzldx** [comment]
@shunmugakumaran Because the $errors variable is not empty, it will execute the errorEmailerSender to report the errors, so you still need to check the $errors why is not empty.

@engcom-Dash Please try to create c1 and c2, and subscribe the alert of the product, in table catalog_product_alert, you can see the records of c1 and c2, the entity of record of c2 is greater than c1's, remove the account of c1, c2 wont get the email, and found the error "No such entity with customerId = (c1)"

**Comment by engcom-Dash** [comment]
Hi @Nuranto @gzldx @shunmugakumaran 

We have tested the scenarios mentioned below :

Scenario 1. Updated the instance from 2.4.3-p2 to 2.4.7-p1
Scenario 2. Please try to create c1 and c2, and subscribe to the alert of the product, in table catalog_product_alert, you can see the records of c1 and c2, the entity of record of c2 is greater than c1's, remove the account of c1, c2 won't get the email, and found the error "No such entity with customerId = (c1)"

We are getting the product alert emails in both scenarios and not getting any errors.

Please take a look at the screenshots I've attached. Let us know if we missed anything.

Scenario 1. Updated the instance from 2.4.3-p2 to 2.4.7-p1

<img width="1440" alt="Screenshot 2024-06-28 at 2 26 57 PM" src="https://github.com/magento/magento2/assets/60198592/9967f817-6a7e-4d02-bfb2-4d3a286907c2">

Scenario 2. Please try to create c1 and c2, and subscribe to the alert of the product, in table catalog_product_alert, you can see the records of c1 and c2, the entity of record of c2 is greater than c1's, remove the account of c1, c2 won't get the email, and found the error "No such entity with customerId = (c1)"

<img width="1440" alt="Screenshot 2024-06-28 at 1 45 48 PM" src="https://github.com/magento/magento2/assets/60198592/6ceb80c3-9e0f-4ac4-a7f5-bcc728d03997">
<img width="1440" alt="Screenshot 2024-06-28 at 1 48 42 PM" src="https://github.com/magento/magento2/assets/60198592/0c8f24d5-87c4-4f75-a506-d6c5d9f5c3b8">
<img width="1440" alt="Screenshot 2024-06-28 at 1 48 54 PM" src="https://github.com/magento/magento2/assets/60198592/6caf83b2-a3d6-4356-a44f-3f60a28ac621">
<img width="1440" alt="Screenshot 2024-06-28 at 1 52 04 PM" src="https://github.com/magento/magento2/assets/60198592/ba3c03b5-4bac-45ff-9295-ca09cb176f60">

Thanks.

**Comment by gzldx** [comment]
@engcom-Dash I saw your image of catalog_product_alert, I mean if customer entity id not exist, the record of catalog_product_alert behind wont execute , because interrupt by the error.

and my magento version is 2.4.6-p5, perhaps fixed in 2.4.7
