### ISSUE TITLE
Add Amqp as a dependency for ProductAlert

### ISSUE THREAD

**Issue by Bartiema** [magento/magento2#35790]
### Summary (*)
If the amqp module is not installed in your magento 2.4.4 instance and you want to use the ProductAlert module functionality you will never be able to send alert emails because when the cronjob catalog_product_alert is run there will be a critical error with the message: "Publisher 'product_alert' is not declared"

### Steps to reproduce
- Set a specific product to be out of stock
- Go to frontend and subscribe to product inventory alert, so the customer gets notified as soon as the product is back in stock
- Make sure, that the customer alert appears in the product view in the admin area in the `Product Alerts` section.
- Put the product back to stock
- To manually run this cron job from the CLI you could do this
```
mysql -e "INSERT INTO cron_schedule ( job_code, scheduled_at ) VALUES ( 'catalog_product_alert', CURENT_TIMESTAMP );" && php bin/magento cron:run
```
- You will directly get the error message `CRITICAL: Publisher 'product_alert' is not declared. [] []`
- Activate `Magento_Amqp` and do the same again
- The error will be gone

### Examples (*)
`.CRITICAL: Publisher 'product_alert' is not declared. [] []`
is the error you can find in debug.log after running bin/magento cron:run when the cronjob catalog_product_alert is trying to send an alert.

### Proposed solution
Add the amqp module as a dependency for the ProductAlert module, both in composer and in the module.xml

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
@Bartiema

Thanks for reporting the issue. 

As you mentioned that "amqp module is not installed " so, could you please confirm if you uninstalled or disabled the module "module-amqp" in config.php file then run the cron manually from terminal so you got that exception.

Please provide the exact steps to reproduce the same and share the screenshots so we can try to reproduce the same at our end.

Thanks,

**Comment by engcom-Echo** [comment]
Hello @Bartiema,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Comment by norgeindian** [comment]
@engcom-Echo , I can verify the issue still persists on `Magento 2.4.5-p1`.
You can reproduce it, like @Bartiema said, by disabling `Magento_Amqp` and then doing the following steps:

- Set a specific product to be out of stock
- Go to frontend and subscribe to product inventory alert, so the customer gets notified as soon as the product is back in stock
- Make sure, that the customer alert appears in the product view in the admin area in the `Product Alerts` section.
- Put the product back to stock
- Run `bin/magento cron:run`
- You will directly get the error message `CRITICAL: Publisher 'product_alert' is not declared. [] []`
- Activate `Magento_Amqp` and do the same again
- The error will be gone

**Comment by PromInc** [comment]
I can confirm the same situation.

Never needed the amqp module in the past.  But it appears with v2.4.5-p1 (or maybe one of the versions prior) it is required???  Can't find any documenation to support that, but appears to be the case if you want to send product alerts...

**Comment by APanteleychuk** [comment]
I can confirm the same situation too.

**Comment by HenKun** [comment]
@engcom-Echo This issue is closed, but reproducible on 2.4.6-p2

**Comment by engcom-Hotel** [comment]
Hello @norgeindian,

Thanks for the steps to reproduce the issue. We have followed the same but the issue is not reproducible for us.

- We have disabled the `Magento_Amqp` module:
![image](https://github.com/magento/magento2/assets/51681618/8040428a-ec3b-444a-a445-b2e5e51d1687)

- Make Product out of stock
- Signup for `Notify me when this product is in stock`
- Make product in stock
- Ran `bin/magento cron:run`
![image](https://github.com/magento/magento2/assets/51681618/f542a53a-6512-4c29-97f0-86f75efa4475)

The command ran successfully, it might be possible the issue is resolved in the latest 2.4-develop branch. I request you to please try to reproduce the issue in the latest development branch.

Thanks

**Comment by HenKun** [comment]
Note that the cron for `catalog_product_alert` is only scheduled once a day (depending on the settings). So not every `cron:run` will trigger the issue.

Furthermore, the Exception is thrown in `Magento\Framework\MessageQueue\Publisher\Config::getPublisher($topic)`.
The class comment states: "Publisher config provides access data declared in etc/queue_publisher.xml".
And indeed, all modules having a `communication.xml` file, also have a `queue_publisher.xml` file, only ProductAlert module does not have this file. According to https://developer.adobe.com/commerce/php/development/components/message-queues/configuration/ and https://developer.adobe.com/commerce/php/development/components/message-queues/migration/:

> If you only want to consume from an existing queue, you will only need the queue_consumer.xml config file.

Since `product_alert.queue` is not an existing queue, a `etc/queue_topology.xml` must be created. Since we want to publish to this queue, a `etc/queue_publisher.xml` must be created.

I can't tell why it works with activated `Magento_Amqp`. I have not tested it with activated `Magento_Amqp`.

**Comment by engcom-Hotel** [comment]
Hello @HenKun,

Thanks for the detailed explanation!

Can you please suggest to us the steps to reproduce of this issue?

Thanks

**Comment by HenKun** [comment]
I just can restate the steps described before:
https://github.com/magento/magento2/issues/35790#issuecomment-1359054097

However when executing cron:run you have to go sure the job is actually scheduled, since this is done only once a day.

**Comment by engcom-Hotel** [comment]
Hello @HenKun,

Thanks for the reply!

We have tried to reproduce this issue with the mentioned steps here https://github.com/magento/magento2/issues/35790#issuecomment-1359054097 in the 2.4-develop branch, but the issue is still not reproducible for us.

We have made changes in the setting of product alert cron from the admin panel as well. Please refer to the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/722b719d-2ca0-48b0-b10d-140036eac9b1)

We request you to please try to reproduce the issue in the 2.4-develop branch.

Thanks

**Comment by HenKun** [comment]
@engcom-Hotel Was the product alert mail actually sent? So did you receive the alert email? We have to go sure the cron job is actually executed when verifying the issue. Otherwise the issue cannot occur. 

Is it possible to run a specific cronjob via CLI without it being scheduled and without using cron:run? This way we could explicitly trigger the process without depending on any cron schedule.

I cannot imagine how this can work, since the publisher is indeed just not declared, so the issue must occur.

**Comment by PromInc** [comment]
@HenKun to manually run this cron job from the CLI you could do this:

```
mysql -e "INSERT INTO cron_schedule ( job_code, scheduled_at ) VALUES ( 'catalog_product_alert', CURENT_TIMESTAMP );" && php bin/magento cron:run
```

This will enter a new entry into the `cron_schedule` table scheduled for now and then run the cron jobs.
NOTE: you need to have CLI access to MySQL setup for `mysql` to function.  You could also run the query via a GUI or any other MySQL connection you have then run the `php bin/magento cron:run` portion.

**Comment by engcom-Hotel** [comment]
Hello @PromInc,

Thanks for the missing step to reproduce the issue. Now we are able to reproduce the issue. But we are getting the mentioned error in `system.log` file:

![image](https://github.com/magento/magento2/assets/51681618/5b07f1a7-f361-4230-a67b-806dbbf9bd20)

Hence confirming the issue.

Thanks

**Comment by yegxr** [comment]
@magento I am working on this

**Comment by rostilos** [comment]
@magento I am working on this
