### ISSUE TITLE
Magento 2.4.4 shows an error, not a warning when using deprecated functionality for PHP 8.1

### ISSUE THREAD

**Issue by m2-amn** [magento/magento2#35875]
### Preconditions and environment

- Magento 2.4.4
- PHP 8.1
The release notes for Mangento 2.4.4 state that Magento 2.4.4 is compatible with PHP 8.1.

### Steps to reproduce

Using deprecated functionality for PHP 8.1

### Expected result

When using deprecated functionality for PHP 8.1, it's expected to be shown as a warning, not as an error.
It should be different from the update that doesn't have backward compatibility.

### Actual result

An error occurs instead of a warning

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @m2-amn ,

Thanks for your contribution and collaboration.

Kindly provide more information regarding the steps to reproduce the issue. So, that we can proceed further process.

Thanks

**Comment by m2-amn** [comment]
Hello, @engcom-Lima,

Thank you for your support.

Here is more information about errors.
Magento 2.4.4 shows an error to pass null as an argument of a deprecated functionality  for PHP 8.1 other than that that explicitly allow null. 
For instance:
strlen(), nl2br()

Thank you

**Comment by engcom-Lima** [comment]
Hi m2-amn ,

I have tried to reproduce the issue but issue is not reproducible to me.
I have used strlen(),nl2br() in `index.php` but I didn't got any error in logs as well as on frontend.
Kindly provide more information, so , that issue can be reproducible.

Thanks

**Comment by m2-amn** [comment]
Hello @engcom-Lima,

It seems that other factors are involved, so please put this matter on hold at present.
Thank you for your time.

**Comment by pmonosolo** [comment]
> Hello @engcom-Lima,
> 
> It seems that other factors are involved, so please put this matter on hold at present. Thank you for your time.

Can you please let us know what did you find? I'm hitting the same issue on 2.4.5:
https://github.com/magento/magento2/issues/35901

**Comment by jasuten** [comment]
Hi @pmonosolo ,

We had the same issues. I think PHP 8 changed the default error reporting level or is not listening to the display errors setting properly.

As a short term fix we modified **app/bootstrap.php** and changed the line:
`error_reporting(E_ALL);`
to:
`error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);`

**Comment by engcom-Hotel** [comment]
Hello @jasuten,

Thanks for the report!

Can you please help us with the reproduction steps for your case?

Thanks

**Comment by pmonosolo** [comment]
> Hi @pmonosolo ,
> 
> We had the same issues. I think PHP 8 changed the default error reporting level or is not listening to the display errors setting properly.
> 
> As a short term fix we modified **app/bootstrap.php** and changed the line: `error_reporting(E_ALL);` to: `error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);`

Thanks!

I think it might be related to this:
https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg

Problem is that the error is not a depreciation error - unless I'm confused.  It just shows up as normal error instead of a warning.

**Comment by engcom-November** [comment]
Hi @pmonosolo / @m2-amn 
I see, this [issue](https://github.com/magento/magento2/issues/35901) got fixed in the scope of the internal Jira ticket AC-6385 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6385&type=commits
Based on the Jira ticket, the target version is 2.4.6.
Can you please check with [this](https://github.com/magento/magento2/commit/4bfb545ebc97a2748596c84743176cea06aff222) and elaborate steps / configuration details if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment]
Hi @m2-amn,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Comment by willtran** [comment]
Request for this to be re-open -Commit https://github.com/magento/magento2/commit/4bfb545ebc97a2748596c84743176cea06aff222 does not fix the root cause
