### ISSUE TITLE
TypeError: explode(): Argument #2 ($string) must be of type string, null given in /var/www/php/folder/vendor/magento/module-config/ViewModel/CountryFilter.php:46

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#35901]
### Preconditions and environment

- Magento version - 2.4.5 CE
- Visit Stores -> Configuration and see error 
- Error reporting turned on
- Page shows an error
- PHP 8.1.9

### Steps to reproduce

1. Login into Admin Site
2. Go to Stores->Configuration

### Expected result

Configuration page visible

### Actual result

Error is thrown:

TypeError: explode(): Argument #2 ($string) must be of type string, null given in /var/www/php/folder/vendor/magento/module-config/ViewModel/CountryFilter.php:46
Stack trace:
#0 /var/www/php/folder/vendor/magento/module-config/ViewModel/CountryFilter.php(46): explode(',', NULL)
#1 /var/www/php/folder/vendor/magento/module-config/view/adminhtml/templates/system/config/js.phtml(81): Magento\Config\ViewModel\CountryFilter->getEuCountryList()
#2 /var/www/php/folder/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/php/mo...')
#3 /var/www/php/folder/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Template), '/var/www/php/mo...', Array)
#4 /var/www/php/folder/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#5 /var/www/php/folder/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Backend\Block\Template), '/var/www/php/mo...', Array)
#6 /var/www/php/folder/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)
#7 /var/www/php/folder/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Magento\Backend\Block\Template), '/var/www/php/mo...', Array)
#8 /var/www/php/folder/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView('/var/www/php/mo...')
#9 /var/www/php/folder/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#10 /var/www/php/folder/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#11 /var/www/php/folder/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#12 /var/www/php/folder/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#13 /var/www/php/folder/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#14 /var/www/php/folder/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('js.system_confi...')
#15 /var/www/php/folder/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout->renderNonCachedElement('js.system_confi...')
#16 /var/www/php/folder/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('js.system_confi...')
#17 /var/www/php/folder/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('js.system_confi...', false)
#18 /var/www/php/folder/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('js', false)
#19 /var/www/php/folder/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout->renderNonCachedElement('js')
#20 /var/www/php/folder/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('js')
#21 /var/www/php/folder/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('js', false)
#22 /var/www/php/folder/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#23 /var/www/php/folder/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#24 /var/www/php/folder/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#25 /var/www/php/folder/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#26 /var/www/php/folder/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#27 /var/www/php/folder/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#28 /var/www/php/folder/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#29 /var/www/php/folder/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('backend.page', false)
#30 /var/www/php/folder/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#31 /var/www/php/folder/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout->renderNonCachedElement('root')
#32 /var/www/php/folder/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#33 /var/www/php/folder/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')
#34 /var/www/php/folder/generated/code/Magento/Framework/View/Layout/Interceptor.php(50): Magento\Framework\View\Layout->getOutput()
#35 /var/www/php/folder/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#36 /var/www/php/folder/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#37 /var/www/php/folder/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#38 /var/www/php/folder/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#39 /var/www/php/folder/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#40 /var/www/php/folder/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#41 {main}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmonosolo** [comment]
The code responsible is this:

![image](https://user-images.githubusercontent.com/66754347/183780476-d2456c30-df9e-478c-95e3-0beade26cd86.png)

I wonder if the list was not generated or something during the upgrade?

I've tried flushing cache and disabling it completely.

**Comment by jorgb90** [comment]
Running 2.4.5 here and not having this issue. Perhaps some external module is altering this list?

**Comment by pmonosolo** [comment]
> Running 2.4.5 on PHP 8.1 here and not having this issue. Perhaps some external module is altering this list?

Hmmm, not sure yet. Just starting to dig into this again.

So far I have:
rm -rf vendor/*

Then upgraded composer to v2 and reinstalled everything. Still getting the same error. 

Found mentions of CountryFilter in two plugins:
```
vendor/webshopapps/module-matrixrate/src/Model/ResourceModel/Carrier/Matrixrate/Collection.php:    public function setCountryFilter($countryId)
vendor/mageside/canada-post-shipping/Model/Source/Province.php:        $this->addCountryFilter('CA');
vendor/mageside/canada-post-shipping/Model/Service/Postoffice.php:            $collection->addCountryFilter('CA')->load();
```

Going to try to go around them or deinstall. Will report back.

**Comment by pmonosolo** [comment]
Disabling those two plugins did not work. 

I assume this is a data problem - something broke when initial upgrade script ran (did not finish successfully on first try).

Going to try uploading new backup of DB and re-running the upgrade command.

**Comment by pmonosolo** [comment]
Could it be related to: https://github.com/magento/magento2/issues/35875
?

**Comment by pmonosolo** [comment]
Hmmm same error after redoing upgrade command on new DB backup. 

Must be something else.

**Comment by pmonosolo** [comment]
Checked the DB:

![image](https://user-images.githubusercontent.com/66754347/184008056-e01028f7-702f-4576-8879-ea5547a348e9.png)

Looks like the values are empty. Are they supposed to be any other way?

**Comment by pmonosolo** [comment]
After doing this:

![image](https://user-images.githubusercontent.com/66754347/184009355-f2805df9-efbe-4da6-8b67-5dd706f679d6.png)

Then going to General -> Countries -> European Union Countries -> Clicking "Use system value"

Then undoing the code back to initial state:

![image](https://user-images.githubusercontent.com/66754347/184009556-ac933bc9-fd3d-4f25-bea6-d31b797b32cb.png)

The page now shows up correctly:

![image](https://user-images.githubusercontent.com/66754347/184009246-652d9cb6-2879-4091-88a3-58a7aa337f8c.png)

**Comment by pmonosolo** [comment]
I think this was a bug somewhere in 2.4.3, or in the earlier version of Magento 2.3.3 which the site went through that the values were not defaulted when you uncheck them and uncheck "Use system value".

Now on 2.4.5 when you uncheck the "Use System Value" it defaults the fields to:

![image](https://user-images.githubusercontent.com/66754347/184010953-ff2316c7-56dc-4338-8d08-4f532bd3f0a8.png)

If you uncheck all those countries and save again, it puts them back in.

UPDATE:
Yes, confirmed 2.4.3 does not default the values, it nulls them when "Use System Value" is unchecked.

When 2.4.5 upgrade happens it expects the value not to be NULL, thats where the issue is coming from.

**Comment by engcom-November** [comment]
Hi @pmonosolo ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3 to 2.4.5 in production mode but could not able to reproduce the issue.
Kindly elaborate the steps / configuration details or any other modules enabled if any is causing the issue. 
Thank you.

**Comment by rogerdz** [comment]
It was fixed in commit https://github.com/magento/magento2/commit/29f065842df8485c6300c4056eac134dfaa906c6

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6385 by the internal team
Related commits: https://github.com/search?q=AC-6385&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by davirs** [comment]
@engcom-Hotel 
I updated my magento 2.4.4 to 2.4.6-p3 and this error persists.
I checked the files within the latest commit AC-6385 and they are present in version 2.4.6-p3.
Is there any provision for merging this commit?

**Comment by engcom-Hotel** [comment]
Sure @davirs, let us check, we will get back to you.

**Comment by webcreative24** [comment]
@engcom-Hotel Same here after update from 2.4.2 to 2.4.6-p3

**Comment by webcreative24** [comment]
Here is the solution:
find in your DB 
`SELECT * FROM core_config_data WHERE path = 'general'`
and then remove these records from the DB. clear cache - enjoy

**Comment by ingmarnet** [comment]
> And 2.4.7 same issue. Its not soo hard to fix it. Magento Dev needs to be more faster to fix that problems.

2025, its still there, with Magento Commerce 2.4.7-p3

**Comment by arunrai91** [comment]
Below code work for me and my Magento ver.sion is 2.4.7-p, it was null so I deleted it

`delete  FROM `core_config_data` WHERE `path` = 'general/country/eu_countries';`
