### ISSUE TITLE
Magento Admin Product Custom Options Not Movable / Draggable in 2.4.4

### ISSUE THREAD

**Issue by ksenia-zlotin** [magento/magento2#36051]
### Preconditions and environment

-Magento 2.4.4
-jQuery 3.6.0

### Steps to reproduce

1. In a clean Magento 2.4.4 instance, create a product in the admin with 3 custom options.
2. Try to drag the second option up to the first position.

### Expected result

Custom option should drag and move to the first position while the first option should move down.

### Actual result

The dragging action stops and gets stuck, does not complete.

### Additional information

The issue comes from src/vendor/magento/module-ui/view/base/web/js/dynamic-rows/dnd.js:138 where the calculation is made:
```
drEl.minYpos =
                $table.offset().top - originRecord.offset().top + $table.children('thead').outerHeight();
```
jQuery updated the way it handles `outerHeight` function calls. Previously, in Magento 2.4.3-p1 which uses a jQuery version of 1.12.4, jQuery returned `Null` when `outerHeight` was called on a non-existent element. Then the `minYpos` value still returned a number value. This is why in the older Magento version, the drag and move action of custom options in Magento worked. This newer jQuery version used in the newer Magento version, however, returns `undefined`. Which is why the calculation referenced above returns `Nan` which breaks the drag and move action.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @ksenia-zlotin ,
Thank you for raising an issue and happy to assist you . We tried to reproduce the issue on magento 2.4.4 instance , but we could not able to drag & drop the options from Product --> custom options --> Option 1 or Option 2 section.
Usually , drag & drop should happen from Catalog--> Category --> section where we can modify its position.

Hence request to review the provided steps.
<img width="1440" alt="Screenshot 2022-08-30 at 7 15 22 PM" src="https://user-images.githubusercontent.com/51681379/187455650-4322d4fa-5d1f-4a2b-9ddd-efc3f6385fee.png">

Reference video.
https://www.loom.com/share/8c7e649dfa92416f9a038d965826f476

**Comment by ksenia-zlotin** [comment]
It looks like the video shows the reproducing of this issue. What else am I to provide?

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:**
Drag and Drop feature is not working, when trying to do with customizable options of a product.
**Pre-requisite:**
1. 2.4-develop

**Steps to reproduce:**
1.Create a product with 3 custom options

2.Try to drag the second option up to the first position


**Expected result:** 
Drag and drop feature should be work ,   

**Actual result:** 
The dragging action stops and gets stuck, does not complete

**Screenshots:**
1.Create a product with 3 custom options.
  

2.Try to drag the second option up to the first position.

The dragging action was stopped and stuck and drag and drop is incomplete.

Hence confirming the issue.

Thanks.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:**

Drag and Drop feature is not working, when trying to do with customizable options of a product.

**Pre-requisite:**
 2.4-develop

**Steps to reproduce:**

1.Create a product with 3 custom options

2.Try to drag the second option up to the first position


**Expected result:** 

Drag and drop feature should be work ,   

**Actual result:** 

The dragging action stops and gets stuck, does not complete

**Screenshots:**
1.Create a product with 3 custom options.
  
<img width="607" alt="Screenshot 2022-09-05 at 6 48 46 PM" src="https://user-images.githubusercontent.com/51681379/188642931-e0c926fd-9b5a-47f1-ac68-b8ddd3ca103d.png">


2.Try to drag the second option up to the first position.

https://user-images.githubusercontent.com/51681379/188644237-f610b076-852b-430a-9f0c-738b636372ef.mov



The dragging action was stopped and stuck and drag and drop is incomplete.

Hence confirming the issue.

Thanks.

**Comment by maxlussier** [comment]
The solution provided with the PR has resolved the issue on my project in Adobe Commerce 2.4.5. I hope someone approves and merges that PR quickly.

**Comment by ihor-sviziev** [comment]
I'm increasing the priority of this ticket to P2 because this is a regression issue (in 2.4.3 it worked fine) and it breaks pretty-basic functionality - the ability to manage custom options for the products.

**Comment by ihor-sviziev** [comment]
Hi @engcom-Delta,
Could you please re-validate this issue because it seems like it got fixed in [ACP2E-980](https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-980&type=commits)

**Comment by engcom-Lima** [comment]
Hi @ihor-sviziev ,

This issue is partially fixed.
**Scenario is**  create multiple custom options but donot expand the tabs and try to drag from down to up.
<img width="1412" alt="Screenshot 2023-03-07 at 2 23 04 PM" src="https://user-images.githubusercontent.com/60198022/223399369-d9bb57d0-4a49-4ebe-9f82-339b0fb66df5.png">


Thanks

**Comment by norgeindian** [comment]
I just applied the changes from [ACP2E-980](https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-980&type=commits), but unfortunately this does not really solve it.
Does anyone have another approach?

**Comment by ihor-sviziev** [comment]
The issue was fixed in https://github.com/magento/magento2/commit/dd7803a9b6360e78ccca25c3f6bec16849c49e45.

**Comment by norgeindian** [comment]
@ihor-sviziev , I just tested.
Unfortunately, this does not solve the issue completely.
I can now only move the first of all options to the bottom, but nothing else. 
Would you be so kind and check again?

**Comment by ihor-sviziev** [comment]
@norgeindian very strange... According to https://github.com/magento/magento2/pull/36072#issuecomment-1457936604 it should work as expected

**Comment by norgeindian** [comment]
@ihor-sviziev , it seems as if according to https://github.com/magento/magento2/pull/36072#issuecomment-1529651488 it also does not work for others.

**Comment by ihor-sviziev** [comment]
@norgeindian could you pls report the separate issue for that? Thank you!
TBH it's very strange that it wasn't properly fixed and tested at first.

**Comment by norgeindian** [comment]
@ihor-sviziev , I tested again, and it seems as if I had a corrupted test product. I now created a new one, and it actually works.
Thanks for your replies and help.
