### ISSUE TITLE
Cannot empty Customer`s Custom Attribute (Text Field) after Save it with any Value

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#36151]
### Preconditions and environment

- Magento version: Latest version, Magento Open Source 2.4.5
- you just need to install Magento Open Source Version 2.4.5
- Create Customer Attribute in any way you want

### Steps to reproduce

1. Install Magento Open Source Version 2.4.5 by composer  (https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/composer.html)
2. Create Custom Text Field in any way, for my example I used an article that already exists on Adobe Magento website [https://developer.adobe.com/commerce/php/tutorials/admin/custom-text-field-attribute/](https://developer.adobe.com/commerce/php/tutorials/admin/custom-text-field-attribute/)
3. Create a Customer from the backend
4. fill in the attribute mentioned in the article with any value (EX: "External ID" = "Test")
5. try to delete the value 

### Expected result

the value of this attribute [External ID] should be empty

### Actual result

Magento ignores the empty value and keeps saving the old value

### Additional information

Nothing more, for easy use I have attached the extension which creates the attribute 
[ExampleCorp.zip](https://github.com/magento/magento2/files/9590886/ExampleCorp.zip)

![image](https://user-images.githubusercontent.com/2926032/190839865-b1081db6-3ea4-4465-9218-3480cde3c8b2.png)

this function that causes the issue "**populateWithOrigData**", here is the place of it
**Magento\Customer\Model\ResourceModel\CustomerRepository** line 306

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @zexperto,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch and the issue has been reproducible for us. We have followed the below steps:
1. Create a new module for the custom customer attributes. Please find attached as a reference:
[Magz.zip](https://github.com/magento/magento2/files/9646116/Magz.zip)
2. Try to edit the customer and update the value of the newly added attribute. We are able to update that.
3. Try to remove that value and try to save the empty value in the text box. but we are unable to do so.

Hence confirming the issue.

Thanks

**Comment by CallMeSudhanshu** [comment]
hi @engcom-Dash @rogerdz  , what is the status of this issue ? Do we have a patch for this already ? When can we expect a release ?

**Comment by engcom-Hotel** [comment]
Hello @CallMeSudhanshu,

As per the JIRA status, the issue is fixed and no more reproducible now. We request you please review the issue in the latest Magento 2.4-develop branch. And let us know if the issue reproducible for you there.

Thanks

**Comment by tthierryEra** [comment]
Issue is still happening on my 2.4.5-p1 for backend type text and textarea frontend input :-(

**Comment by engcom-Hotel** [comment]
Hello @tthierryEra,

Have you tried it in the latest Magento development branch i.e. 2.4-develop?

Thanks

**Comment by kenseiatwork** [comment]
@engcom-Hotel Hello,
Is there a specific commit(s) that you can point us to with the fix?
Thanks!

**Comment by engcom-Hotel** [comment]
Hello @kenseiatwork,

Let me check and will get back to on this.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @kenseiatwork,

It seems that the below is the commit link:

https://github.com/magento/magento2/commit/f05da7543d49ccf4af553a91cc905988ec7d8408

Thanks

**Comment by jesse-thomas** [comment]
How are people patching 2.4.5? I see two pull requests but they are addressing it at a lower level than just the customer entity, and this issue doesn't seem to effect products etc. The commit above seems to address other issues as well. I dont see a quality patch for this issue either. Upgrading to 2.4.6 to fix the issue is a decent amount of work. Any hints about a fix would be appreciated. Thanks!

**Comment by pkarsai** [comment]
This patch fixed it for us:
```diff --git a/vendor/magento/module-eav/Model/Entity/AbstractEntity.php b/vendor/magento/module-eav/Model/Entity/AbstractEntity.php
index 08823bacc..6c0be486e 100644
--- a/vendor/magento/module-eav/Model/Entity/AbstractEntity.php
+++ b/vendor/magento/module-eav/Model/Entity/AbstractEntity.php
@@ -12,6 +12,7 @@ use Magento\Eav\Model\Entity\Attribute\Frontend\AbstractFrontend;
 use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
 use Magento\Eav\Model\Entity\Attribute\UniqueValidationInterface;
 use Magento\Eav\Model\ResourceModel\Attribute\DefaultEntityAttributes\ProviderInterface as DefaultAttributesProvider;
+use Magento\Framework\Api\CustomAttributesDataInterface;
 use Magento\Framework\App\Config\Element;
 use Magento\Framework\App\ObjectManager;
 use Magento\Framework\DataObject;
@@ -1289,6 +1290,11 @@ abstract class AbstractEntity extends AbstractResource implements EntityInterfac
              * not needed after introduction of partial entity loading
              */
             foreach ($origData as $k => $v) {
+                if ($k === CustomAttributesDataInterface::CUSTOM_ATTRIBUTES) {
+                    foreach ($v as $custom_attribute => $data) {
+                        $origData[$custom_attribute] = $data['value'] ?: '';
+                    }
+                }
                 if (!array_key_exists($k, $newData)) {
                     unset($origData[$k]);
                 }

**Comment by jublm** [comment]
I don't understand why this has not been patched for Magento 2.4.5.
