### ISSUE TITLE
getGroupId method returns wrong group ID when FPC is disabled.

### ISSUE THREAD

**Issue by marceldekoning** [magento/magento2#36541]
### Preconditions and environment

- Magento version: 2.4.5-p1
- PHP 8.1
- NGINX
- Varnish & Build In.

### Steps to reproduce

1. Disable FPC.
2. Set a default customer group where new customers have to be placed in, under: Stores > Configuration > Customers > Customer Configuration > Create New Account Options > Default Group.
3. Add some code where group ID is requested from the customerSession's customer.

```
use Magento\Customer\Model\Session;

/**
 * @param Session $customerSession
 */
public function __construct(
    private readonly Session $customerSession
) {}

$customerGroupId = $this->customerSession
  ->getCustomer()
  ->getGroupId();
```

4. Run your code as a "Not Logged In" user.

### Expected result

The result of getGroupId() should be of type Magento\Customer\Model\Group::NOT_LOGGED_IN_ID.

### Actual result

The result of getGroupId() is the result of Magento\Customer\Model\Customer::getGroupId(), which is the default group ID that's set for new logged in customers.

### Additional information

When FPC is enabled, the depersonalize plugin in Magento\Customer\Model\Layout\DepersonalizePlugin sets a new customer model with the group ID that is retrieved by $this->customerSession->getCustomerGroupId(), which returns the right group ID. When FPC is disabled, the $this->depersonalizeChecker->checkIfDepersonalize($subject) check is never passed and the customer group ID is never set to 0.

I know that $this->customerSession->getCustomerGroupId() returns the right group ID, but the core of Magento also uses the getGroupId method numerous times, so that must go wrong as well at some point.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @marceldekoning,

Thanks for the report and collaboration!

We have tried to reproduce this issue in Magento 2.4-develop branch by making a custom module. We are attaching that module below for reference:

[Magz.zip](https://github.com/magento/magento2/files/10391761/Magz.zip)

We have followed the below steps:
1. Disable the FPC via the following command:
`bin/magento cache:disable full_page`
2. Update the value of `Default Group` as `Retailer` in the admin panel:
<img width="979" alt="image" src="https://user-images.githubusercontent.com/51681618/211793964-735aa6bb-edaa-4068-b5f5-338d1a64c1bb.png">

3. Try to access the controller attached above to print the Group Id and we are getting `3` which means `Retailer`.
4. But when we tried the same with FPC enabled we are getting the same result instead of getting `NOT_LOGGED_IN_ID `.

Do we miss anything?

Thanks

**Comment by marceldekoning** [comment]
Hi @engcom-Hotel,

There are two things here that need some explanation. 

1. The **Default Group** that is set up in the configuration is for new (logged in) customers that create an account on the frontend.  Why is your controller outputting the group ID of "Retailer" when you're logged out? 
2. The resetting of the group ID is done _after_ generating the layout in Magento\Customer\Model\Layout\DepersonalizePlugin::afterGenerateElements(LayoutInterface $subject). So the var_dump in your module comes too soon. When you add `die(var_dump($this->customerSession->getCustomer()->getGroupId()));` in the end of the if statement in the afterGenerateElements method, you will see that the groupId is now set to 0. Make sure FPC is enabled.

![image](https://user-images.githubusercontent.com/22954410/213398280-4cadb470-07ad-4dc2-870f-368e70bbc294.png)

Thanks.

**Comment by engcom-Hotel** [comment]
Hello @marceldekoning,

Thanks for the reply!

I am also wondering about the same, actually, you are right, if we are setting the default customer group, which should apply for the new user signed up but it is showing "Retailer" for the not logged-in state. 

One more thing, as per the steps reproduction, we need to disable the FPC then only the issue is reproducible, with enabled FPC issue is not reproducible. But in my case, the issue is reproducible in both cases.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @marceldekoning,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by marceldekoning** [comment]
@engcom-Hotel This issue is definitely not fixed, like you said yourself two weeks ago.  Please reopen and thank you for looking into it.

**Comment by sprajapat770** [comment]
@engcom-Hotel @magento-engcom-team  can you repone this issue? this is not fixed yet.
