### ISSUE TITLE
Magento Catalog Permissions Module Bug: Product set to Hidden

### ISSUE THREAD

**Issue by Vishrootways** [magento/magento2#36614]
### Preconditions and environment

- Magento Version: Commerce Cloud 2.4.3
- Magento Shared Catalog is setup.

### Steps to reproduce

Below are steps to reproduce this issue,
$product->getData('grant_catalog_category_view') value should be -2 and
$this->_catalogPermData->isAllowedCategoryView() value should 1 and then you will face this issue.

### Expected result

Expected result is that product should access from the website front-end.

### Actual result

Actual Result is product is not accessible and redirects to home page

### Additional information

From last few days, we faced one issue of product is not accessible from the website front-end and redirecting to the home page.

Below is the error log in the exception.log file.

report.CRITICAL: You may need more permissions to access this product. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): You may need more permissions to access this product. at /app/fgvmfeeirpu5w/vendor/magento/module-catalog-permissions/Observer/ApplyProductPermissionObserver.php:94)"} []

 We debug the code and found that the below code is responsible for that. and it hides the product for the login customer group.

```
file location: \Magento\CatalogPermissions\Observer\ApplyPermissionsOnProduct.php
public function execute($product)
{
        if ($product->getData('grant_catalog_category_view') == -2
            || $product->getData('grant_catalog_category_view') != -1
            && !$this->_catalogPermData->isAllowedCategoryView()
        ) {
            $product->setIsHidden(true);
        }
        ......
}
```

I think this is due to wrong OR AND added to the if statement.
I think OR condition should be wrapped in ( ) as below.

```
file location: \Magento\CatalogPermissions\Observer\ApplyPermissionsOnProduct.php
public function execute($product)
{
        if (($product->getData('grant_catalog_category_view') == -2
            || $product->getData('grant_catalog_category_view') != -1)
            && !$this->_catalogPermData->isAllowedCategoryView()
        ) {
            $product->setIsHidden(true);
        }
        ......
}
```

If we update the if condition as above, then I think that issue will be fixed.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Vishrootways,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop instance with EE but the issue is not reproducible for us. We are able to browse the category.

Please refer to the screenshots for reference:

### Stores => Configuration
![image](https://user-images.githubusercontent.com/51681618/208441940-1bb5c1df-00c2-4a32-9948-9951ae7113ac.png)

### Category Configuration
![image](https://user-images.githubusercontent.com/51681618/208442068-996b5da3-30bd-4e89-8a8b-64dbd99cc4f0.png)

### Frontend for logged person
![image](https://user-images.githubusercontent.com/51681618/208442238-b4cb287f-b813-45b7-ab4d-4513b59b336d.png)

Please help us with the screenshots of your configurations.

Thanks

**Comment by Vishrootways** [comment]
Hello @engcom-Hotel 

Thank you for your feedback but the issue is not in category page but it's on product detail page.

Just set product like below condition meets in if condition of **public function execute($product)** of this file \Magento\CatalogPermissions\Observer\ApplyPermissionsOnProduct.php



$product->getData('grant_catalog_category_view') value should be -2 and
$this->_catalogPermData->isAllowedCategoryView() value should 1

When product meets above condition you will face issue like product view page can not be accessed.

Kindly review my original message again for more details.

Thanks,
Vish

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Hotel** [comment]
Hello @Vishrootways,

Thanks for the reply!

We have gone through as per your comment, to make the below condition true:

```
if ($product->getData('grant_catalog_category_view') == -2
            || $product->getData('grant_catalog_category_view') != -1
            && !$this->_catalogPermData->isAllowedCategoryView()
        ) {
            $product->setIsHidden(true);
        }
```

For this we have made the below configurations:
1. Create a user with the "General" type.
2. Pick a category and make "Deny" for `Browsing Category`, `Display Product Prices`, and `Add to Cart`:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/51681618/208924169-9cbc9914-2b04-466e-ac5a-eafa7bce2350.png">

In the above case, `$product->setIsHidden(true` this function has been called. And as per the configuration, the user should not allow viewing that page, which is working as expected.

Please let us know if we missed anything.

Thanks

**Comment by Vishrootways** [comment]
@engcom-Hotel 
This condition **should not be true** when the value of if is as below.

$product->getData('grant_catalog_category_view') value is -2 and 
$this->_catalogPermData->isAllowedCategoryView() value is 1

Please check do you get above values in that function? If yes then THIS CONDITION SHOULD NOT BE TRUE AND PRODUCT SHOULD NOT BE SET AS HIDDEN.


Thanks,
Vish

**Comment by engcom-Hotel** [comment]
Hello @Vishrootways,

Thanks for your reply!

Let me explain the flow here:
1. For us we have a "Test" category in which we have some products. So we are setting the permission for this category. The permission for the "Test" category is looking as follows:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/51681618/209087592-2304196a-007f-4ac9-821a-40e13cb4e734.png">

2. After saving the above permissions, the database entry for the table `magento_catalogpermissions_index` is as follows:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/51681618/209087792-2c7ed246-25b8-4e55-bbe2-97402a2acbf1.png">

You can see the value for column `grant_catalog_category_view` is `-2`.

3. And in the file `ApplyPermissionsOnProduct.php` line no. `$this->_catalogPermData->isAllowedCategoryView()` this line is returning `false` which makes the condition `true`.

due to which the product has been set to hidden.

Please let us know if we missed anything in order to get this issue.

Thanks

**Comment by Vishrootways** [comment]
@engcom-Hotel 
When `$this->_catalogPermData->isAllowedCategoryView()` is `true `at that time it **should not call that if condition** right? If yes then this is what i want to tell from my first message that when `$this->_catalogPermData->isAllowedCategoryView()` is true then also if condition called and product set to hidden.

I think simple trick is just set static value for this if condition and check from your side and you will understand what i am trying to tell you here

Thank you.

**Comment by engcom-Hotel** [comment]
Hello @Vishrootways,

Thanks for the reply!

As per your comment, we have used the trick to set the static value for that condition and the issue is reproducible but still we need proper steps without any trick to reproduce the issue.

So we request you to please provide the same.

Thanks

**Comment by Vishrootways** [comment]
@engcom-Hotel We are not sure exactly which changes of product or category meets this condition and but currently we have few products on our website which meets this condition and we are having this issue.

We only knows that this is due to shared catalog but unfortunately we don't know how to reproduce this but this is happens many time on our cloud website.

Thanks,
Vish

**Comment by engcom-Hotel** [comment]
Hello @Vishrootways,

Thanks for the reply!

In this case, Is this possible for you to share the screenshot for the below configuration:

- Catalog -> Categories (for which Category Permissions is applied)
- Stores -> Configurations -> Catalog -> Catalog -> Category Permissions
- Catalog -> Products (For which the condition is true)

It will help us in getting the issue exactly.

Thanks

**Comment by Vishrootways** [comment]
@engcom-Hotel Here are the screenshots. 
![2022-12-30_175410](https://user-images.githubusercontent.com/12792977/210069946-9a429b1b-b0a7-4a9c-8039-4fd5b35cd5a6.png)
![2022-12-30_175217](https://user-images.githubusercontent.com/12792977/210069951-f3f1c938-68bc-45b0-b9ff-a5c893f4b82d.png)
![2022-12-30_175307](https://user-images.githubusercontent.com/12792977/210069954-6e5b3638-4e2d-49c3-a221-ebe15ff5c575.png)

**Comment by engcom-Hotel** [comment]
Hello @Vishrootways,

Thanks for the reply!

We have gone through with the Shared catalog documentation from the below link:

https://experienceleague.adobe.com/docs/commerce-admin/b2b/shared-catalogs/catalog-shared.html

According to the documentation:

> When the shared catalog feature is enabled in the configuration, each [category permission](https://experienceleague.adobe.com/docs/commerce-admin/catalog/categories/category-permissions.html?lang=en) for the catalog is set to Deny for all customer groups automatically. Also, when a new category is created, it has the Deny category permissions by default to prevent showing that category on the storefront site before assignment to the shared catalog.

> All existing [group permission settings](https://experienceleague.adobe.com/docs/commerce-admin/config/catalog/catalog.html?lang=en#category-permissions) are ignored by all categories in the catalog when the Shared Catalog feature is enabled. Shared Catalog fully controls all category permissions in the catalog when it is enabled.

May this is the reason, that particular products redirect to the home page.

Thanks

**Comment by Vishrootways** [comment]
Hello @engcom-Hotel 
The shared catalog is already assigned to category and product both.

Just forget about the everything and let us know did you you not find anything wrong with below condition? Do you think below if condition code is correct? If yes then you can close this ticket. Thank you.

```
if ($product->getData('grant_catalog_category_view') == -2
            || $product->getData('grant_catalog_category_view') != -1
            && !$this->_catalogPermData->isAllowedCategoryView()
        ) {

        }
```

Thanks,
Vish

**Comment by engcom-Hotel** [comment]
Hello @Vishrootways,

As per my comment [here](https://github.com/magento/magento2/issues/36614#issuecomment-1363959659), I already told you that, if we are using changes in the codebase, the issue is reproducible for us.

But as the process and also to fix any issue we need a proper scenario that can be generated via without making any code changes.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Vishrootways,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by Vishrootways** [comment]
@engcom-Hotel This is not fixed yet but anyway you can close this ticket. 
We know where is the issue but unfortunately don't have steps to reproduce the issue and as we don't have it Magento/Adobe team may not solve the issue so please close this. Thank you.
