### ISSUE TITLE
Custom Wysiwyg Style Formats Disappeared After Upgrade to 2.4.5-p1 

### ISSUE THREAD

**Issue by rodrigotripp** [magento/magento2#36950]
### Preconditions and environment

* Magento 2.4.5-p1

### Steps to reproduce

1. Create a custom module
2. Add custom style format according to the instructions for Extending the TinyMCE editor given in the [Magento DevDocs](https://developer.adobe.com/commerce/frontend-core/ui-components/components/wysiwyg/configure-tinymce-editor/#extending-the-tinymce-editor)
3. Clear cache and load the Wyswig in the Pagebuilder
4. Using "text" content type to see if the customized styles are listed.
5. No custom styles will be found.

### Expected result

Custom style format is present in the formats list

### Actual result

Custom style format is ignored and only the default formats load

Headings from 1 to 6 are there, and bedfore the update, the formats were available to be used

### Additional information

Magento was upgraded from 2.4.3-p2  to 2.4.5-p1.

### Release note

No response

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @rodrigotripp,

Thanks for the report and collaboration!

We have tried to reproduce the issue by upgrading Magento from 2.4.3-p2 to 2.4.5-p1 and it seems the issue is reproducible for us.

Please refer to the screenshot and video for the same:

**Before Upgrading**
![Dashboard-Magento-Admin-2 4 3-p2](https://user-images.githubusercontent.com/51681618/224004788-d51e3829-427e-4073-8122-5ffbe4281d87.png)

![Module_2 4 3-p2](https://user-images.githubusercontent.com/51681618/224004832-fee5688c-fe94-4053-98b3-c2fb969fab19.jpg)

**After Upgrade**
![Dashboard-Magento-Admin-2 4 5-p1](https://user-images.githubusercontent.com/51681618/224005022-3670de41-0c28-489e-b1f8-de1004723325.png)

https://user-images.githubusercontent.com/51681618/224005047-a968ad57-b948-4d3f-8155-902e239f6a0a.mov

Hence confirming the issue.

Thanks

**Comment by rodrigotripp** [comment]
Is this gonna move forward?

**Comment by glo35082** [comment]
Team has started working on the issue. Will post further update shortly

**Comment by engcom-Bravo** [comment]
Hi @rodrigotripp,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by rodrigotripp** [comment]
@engcom-Bravo Well, I mean you can see that it was reproducible by other user and later it was confirmed to be an issue, and now you decided to close it.  What a dissapointment.

**Comment by Hoargarth** [comment]
Can confirm this is still an issue.
It's only a problem with `style_formats`, hence why @engcom-Hotel was able to reproduce it.
But @engcom-Bravo didn't test `style_formats`, only other formats.

This should be reopened!

**Comment by cemag44300** [comment]
I confirm the issue. I can't modfy style_formats with xml

**Comment by VitaliyBoyko** [comment]
Hi guys.

Here is the [fix](https://www.tiny.cloud/blog/custom-font-sizes-in-tinymce/) for missing font size issue.

TinyMCE in the 7th version has changed config keys for:
fontsizeselect -> fontsize
fontsize_formats -> font_size_formats

So plugin arguments need to be like this:
```
<type name="Custom\PageBuilder\Plugin\Wysiwyg\ConfigPlugin">
        <arguments>
            <argument name="additionalSettings" xsi:type="array">
                <item name="toolbar" xsi:type="string">
                    undo redo | styles | fontsize | lineheight | forecolor backcolor
                    | bold italic underline | alignleft aligncenter alignright | numlist bullist
                    | link image table charmap
                </item>
                <item name="fixed_toolbar_container" xsi:type="string">.pagebuilder-content-type</item>
                <item name="font_size_formats" xsi:type="string">10px 12px 14px 16px 18px 20px 24px 26px 28px 32px 34px 36px 38px 40px 42px 48px 52px 56px 64px 72px</item>
            </argument>
        </arguments>
    </type>

**Comment by MartinVanVan** [comment]
Instead of a Plugin you can just overwrite the config key by creating another `adminhtml/di.xml`.
The original definition is in `vendor/magento/module-page-builder/etc/adminhtml/di.xml` which uses the wrong config key 'fontsize_formats' like mentioned in this issue. 

So create a custom module e.g. MyVendor_ExtendPageBuilder
and add a` adminhtml/di.xml.` Remember to add Magento_PageBuilder to the module.xml

The `adminhtml/di.xml` should look like this.

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\PageBuilder\Model\Wysiwyg\DefaultConfigProvider">
        <arguments>
            <argument name="additionalSettings" xsi:type="array">
                <item name="font_size_formats" xsi:type="string">10px 12px 14px 16px 18px 20px 24px 26px 28px 32px 34px 36px 38px 40px 42px 48px 52px 56px 64px 72px</item>
            </argument>
        </arguments>
    </type>
</config>
```
