### ISSUE TITLE
Backend Bootstrap JS form Key causing an error on json

### ISSUE THREAD

**Issue by forgeonline** [magento/magento2#3707]
## Steps to reproduce
1. Create web api to manage POST to update database table.

API CURL works fine. But when Post data from magento backend, it's not updating the table

Curl command
<code>
curl -X POST -d '{"availabilityInformation":{"productid":3,"bookingdate":"10-03-2016","timefrom":"11:30","noofunits":"56","is_active":"0"}}' -H "Content-Type:application/json" http://mydomain.com/rest/V1/updateavailability
</code>
2. Create JS file to post

```
        serviceUrl = urlBuilder.createUrl('/updateavailability/availability',{});
        payload = {
            availabilityInformation:{
                productid: availability.productid,
                bookingdate: availability.bookingdate,
                timefrom: availability.timefrom,
                noofunits: availability.noofunits,
                is_active: availability.isactive
            },
        };

        return storage.post(
                serviceUrl, JSON.stringify(payload), false
        ).done(
            function (response) {
                console.log(response);
                return response;
            }
        ).fail(
            function (response) {
                console.log('fail');
                console.log(response);
                return response;
            }
        );
```
1. Once the data is posted it will capture from json and create an error. Decoding error.
## Expected result
1. Should update or create new record in database
## Actual result
1. Once the data is posted and captured from json it create an error. 

Message : Decoding error.

Boostrap is adding form_key to the json and break the decoding. Below is captured request for json decoding
<code>
{"availabilityInformation":{"productid":3,"bookingdate":"10-03-2016","timefrom":"10:30","noofunits":"56","is_active":"0"}}&form_key=nKyaw8AG3fmTGtBv
</code>
This is caused by backend/bootstrap.js

Question ?
1. Is there a way to remove bootstrap from adding form_key to post 
2. Another issue is it's adding isAjax=true is there a way to remove this

Note: In backend bootstrap
<code>
    $.ajaxSetup({
        /*
         \* @type {string}
         */
        type: 'POST',

```
    /*
     * Ajax before send callback
     * @param {Object} The jQuery XMLHttpRequest object returned by $.ajax()
     * @param {Object}
     */
    beforeSend: function(jqXHR, settings) {
        var form_key = typeof FORM_KEY !== 'undefined' ? FORM_KEY : null;
        if (!settings.url.match(new RegExp('[?&]isAjax=true',''))) {
            settings.url = settings.url.match(
                new RegExp('\\?',"g")) ?
                settings.url + '&isAjax=true' :
                settings.url + '?isAjax=true';
        }
        if (!settings.data) {
            settings.data = {
                form_key: form_key
            };
        } else if ($.type(settings.data) === "string" &&
            settings.data.indexOf('form_key=') === -1) {
            settings.data += '&' + $.param({
                form_key: form_key
            });
        } else if($.isPlainObject(settings.data) && !settings.data.form_key) {
            settings.data.form_key = form_key;
        }
    },
```

</code>

**Comment by forgeonline** [comment]
Hi,

Since it took while to update we need a solution fast so I've made some changes to mage\backend\bootstrap.js to work

Please add this to repository so for json string works without any decoding error

Changed from line no 38

<code>
                settings.data.indexOf('form_key=') === -1) {
                settings.data += '&' + $.param({
                    form_key: form_key
                });
</code>

To 

<code>
                settings.data.indexOf('form_key=') === -1 && 
        settings.contentType !== "application/json" ) {
                settings.data += '&' + $.param({
                    form_key: form_key
                });
</code>

Happy to make change with pull request if needed.

Thanks
Nuwinda

**Comment by anton-huz** [comment]
Hi Nuwinda,
Wow! Great investigation! Thanks.

We will deliver changes under internal ticket MAGETWO-50523.

**Comment by piotrekkaminski** [comment]
Issue was resolved in 2.1

**Comment by chris-pook** [comment]
Pretty sure this is still an issue. Those same steps from @forgeonline still result in the same error in Magento 2.3

**Comment by benhath** [comment]
Still an issue in 2.4.6-p3
