### ISSUE TITLE
Order History Search Filter mysql query is really show

### ISSUE THREAD

**Issue by igorwulff** [magento/magento2#37345]
### Preconditions and environment

- any recent Adobe Commerce version
- have a lot of orders and utilize the order search history feature.

This will trigger the following query:
```
SELECT `main_table`.* FROM `sales_order_item` AS `main_table` WHERE ((`name` LIKE ?) OR (`sku` LIKE ?))
```

And Query Analysis:
```
Query analysis
Show details
Table
main_table
Hint
No index was used in this part of the query.
This table was retrieved with a full table scan, which is often quite bad for performance, unless you only retrieve a few rows.
You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.
Approximately 3506322 rows of this table were scanned.
```

With stacktrace:
```

                             in PDOStatement::execute called at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php (90)
…\Mysql::Magento\Framework\DB\Statement\Pdo\{closure} called at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php (106)
…Magento\Framework\DB\Statement\Pdo\Mysql::tryExecute called at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php (91)
…o\Framework\DB\Statement\Pdo\Mysql::_execute called at /vendor/magento/zendframework1/library/Zend/Db/Statement.php (313)
         in Zend_Db_Statement::execute called at /vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php (480)
in Zend_Db_Adapter_Abstract::query called at /vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php (238)
                 in Zend_Db_Adapter_Pdo_Abstract::query called at /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php (564)
      in Magento\Framework\DB\Adapter\Pdo\Mysql::_query called at /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php (631)
…Framework\DB\Adapter\Pdo\Mysql::query called at /vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php (737)
…d_Db_Adapter_Abstract::fetchAll called at /vendor/magento/module-resource-connections/DB/Adapter/Pdo/MysqlProxy.php (1261)
…\DB\Adapter\Pdo\MysqlProxy::fetchAll called at /vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php (21)
…Data\Collection\Db\FetchStrategy\Query::fetchAll called at /vendor/magento/framework/Data/Collection/AbstractDb.php (782)
…\Framework\Data\Collection\AbstractDb::_fetchAll called at /vendor/magento/framework/Data/Collection/AbstractDb.php (677)
…to\Framework\Data\Collection\AbstractDb::getData called at /vendor/magento/framework/Data/Collection/AbstractDb.php (580)
…b::loadWithFilter called at /generated/code/Magento/Sales/Model/ResourceModel/Order/Item/Collection/Interceptor.php (32)
…rder\Item\Collection\Interceptor::loadWithFilter called at /vendor/magento/framework/Data/Collection/AbstractDb.php (565)
       in Magento\Framework\Data\Collection\AbstractDb::load called at /vendor/magento/framework/Data/Collection.php (333)
in Magento\Framework\Data\Collection::getItems called at /vendor/magento/module-sales/Model/Order/ItemRepository.php (129)
…del\Order\ItemRepository::getList called at /vendor/magento/module-order-history-search/Model/Filter/ProductSku.php (90)
…r\ProductSku::applyFilter called at /vendor/magento/module-order-history-search/Model/OrderFilterBuilderService.php (71)
```

The following patch will fix the issue, but I can't commit to the Adobe Commerce codebase:
```
Index: Model/Filter/ProductSku.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Model/Filter/ProductSku.php b/Model/Filter/ProductSku.php
--- a/Model/Filter/ProductSku.php
+++ b/Model/Filter/ProductSku.php	(date 1664528084555)
@@ -71,6 +71,12 @@
         /** @var SearchCriteriaBuilder $itemCriteria */
         $itemCriteria = $this->searchCriteriaBuilderFactory->create();

+        $ordersCollectionForFilter = clone $ordersCollection;
+        $orderFilter = $this->filterBuilder->setField(OrderItemInterface::ORDER_ID)
+            ->setValue($ordersCollectionForFilter->getColumnValues('entity_id'))
+            ->setConditionType('in')
+            ->create();
+
         $nameFilter = $this->filterBuilder->setField(OrderItemInterface::NAME)
             ->setValue('%' . $value . '%')
             ->setConditionType('like')
@@ -81,11 +87,16 @@
             ->setConditionType('like')
             ->create();

-        $filterGroup = $this->filterGroupBuilder->addFilter($nameFilter)
+        $filterGroupOrder = $this->filterGroupBuilder
+            ->addFilter($orderFilter)
+            ->create();
+
+        $filterGroup = $this->filterGroupBuilder
+            ->addFilter($nameFilter)
             ->addFilter($skuFilter)
             ->create();

-        $itemCriteria->setFilterGroups([$filterGroup]);
+        $itemCriteria->setFilterGroups([$filterGroupOrder, $filterGroup]);

         $items = $this->itemRepository->getList($itemCriteria->create());

@@ -94,7 +105,17 @@
             $orderIds[] = $item->getOrderId();
         }

-        $ordersCollection->addFieldToFilter(OrderInterface::ENTITY_ID, ['in' => array_unique($orderIds)]);
+        $ordersCollection->getSelect()->joinLeft(
+            ['sop' => $ordersCollection->getTable('sales_order_payment')],
+            'sop.parent_id = main_table.entity_id',
+            ['po_number']
+        );
+        $orderIds = implode(',', array_unique($orderIds));
+        $quotedValue = $ordersCollection->getConnection()->quote("{$value}%");
+        $query = $orderIds ?
+            sprintf('main_table.entity_id in (%s) or sop.po_number like %s', $orderIds, $quotedValue) :
+            sprintf('sop.po_number like %s', $quotedValue);
+        $ordersCollection->getSelect()->where($query);

         return $ordersCollection;
     }

```

### Steps to reproduce

Utilize the Order Search History feature and try to lookup a product with the search history when you have a lot of orders.

### Expected result

A fast and quick result of orders that contains the orders that contain this product sku or name in their order items.

### Actual result

A slow loading page... taking sometimes 20 or more seconds to load.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @igorwulff,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by sdaugherty-af** [comment]
Still an issue in adobe commerce unless it's been fixed in later versions

**Comment by asinghnetz98** [comment]
This is still an issue on 2.4.6-p4, The issue is `main_table`.* takes too much resources and new relic catches it as a slow query. For us we have over 900000 order data and the query takes almost 7 seconds to execute.

**Comment by igorwulff** [comment]
Sorry I totally missed the replies and forgot about this one. 

Yes, this is still an issue. Start testing with a large dataset or by analyzing the query itself to understand the problem.

**Comment by igorwulff** [comment]
> Hello @igorwulff,
> 
> Thanks for the report and collaboration!
> 
> We are still working on this issue reproduction. We have a query, are you talking about the below page from Admin panel:
> 
> ![image](https://user-images.githubusercontent.com/51681618/230929262-0fd9f3a6-99fd-40d7-9718-b6b262272f71.png)
> 
> Thanks

I'm talking about the order history search feature on a My Account level for the frontend. The module-order-history-search module is part of the magento/extension-b2b suite.
