### ISSUE TITLE
Reorder side bar causes issue when product has complex custom options

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#37390]
### Preconditions and environment

- Magento version 2.4.5-p2
- Create a product with a date as required custom option,

### Steps to reproduce

1. As a customer create an order with a product that has a custom option of type date,
2. Use the reorder sidebar to add this product back to the cart and see that the date shows up on the cart item,
3. Select the edit option on the cart item and see that the date field is not filled in,
4. Return to cart without filling the date in and proceed to place the order,
5. Order will be placed successfully but the buy request only contains the date string and not the complex type,
6. Try to reorder this new order and see the message "Please specify date required option(s)."

### Expected result

Order is created as expected and the buyrequest contains the fully required date object.

### Actual result

Order is placed but only contains the date value as a simple string.

### Additional information

It seems that the issue comes in the class Cart with trying to add the item to the cart. See (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/Cart.php#L266) here when creating the buyRequest the items are all treated as simple types rather than the required complex type for date.

```
            if ($productOptions !== null && !empty($productOptions['options'])) {
                $formattedOptions = [];
                foreach ($productOptions['options'] as $option) {
                    $formattedOptions[$option['option_id']] = $option['option_value'];
                }
                $info->setData('options', $formattedOptions);
            }
```

I see a few possible fixes.

1. Update the addgroup controller (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Controller/Cart/Addgroup.php) to not use the deprecated cart model,
2. Update the cart model to use the new OrderInfoBuyRequestGetter class,

For use we fixed this locally with the second option with the following patch.

```
diff --git a/vendor/magento/module-checkout/Model/Cart.php b/vendor/magento/module-checkout/Model/Cart.php
index 3c1a70e..350f38c 100644
--- a/vendor/magento/module-checkout/Model/Cart.php
+++ b/vendor/magento/module-checkout/Model/Cart.php
@@ -9,8 +9,10 @@ namespace Magento\Checkout\Model;
 use Magento\Catalog\Api\ProductRepositoryInterface;
 use Magento\Catalog\Model\Product;
 use Magento\Checkout\Model\Cart\CartInterface;
+use Magento\Framework\App\ObjectManager;
 use Magento\Framework\DataObject;
 use Magento\Framework\Exception\NoSuchEntityException;
+use Magento\Sales\Model\Reorder\OrderInfoBuyRequestGetter;
 
 /**
  * Shopping cart model
@@ -131,7 +133,8 @@ class Cart extends DataObject implements CartInterface
         \Magento\CatalogInventory\Api\StockStateInterface $stockState,
         \Magento\Quote\Api\CartRepositoryInterface $quoteRepository,
         ProductRepositoryInterface $productRepository,
-        array $data = []
+        array $data = [],
+        OrderInfoBuyRequestGetter $orderInfoBuyRequestGetter = null
     ) {
         $this->_eventManager = $eventManager;
         $this->_scopeConfig = $scopeConfig;
@@ -145,6 +148,8 @@ class Cart extends DataObject implements CartInterface
         $this->quoteRepository = $quoteRepository;
         parent::__construct($data);
         $this->productRepository = $productRepository;
+        $this->orderInfoBuyRequestGetter = $orderInfoBuyRequestGetter ?:
+            ObjectManager::getInstance()->get(OrderInfoBuyRequestGetter::class);
     }
 
     /**
@@ -281,21 +286,7 @@ class Cart extends DataObject implements CartInterface
             } catch (NoSuchEntityException $e) {
                 return $this;
             }
-            $info = $orderItem->getProductOptionByCode('info_buyRequest');
-            $info = new \Magento\Framework\DataObject($info);
-            if ($qtyFlag === null) {
-                $info->setQty($orderItem->getQtyOrdered());
-            } else {
-                $info->setQty(1);
-            }
-            $productOptions = $orderItem->getProductOptions();
-            if ($productOptions !== null && !empty($productOptions['options'])) {
-                $formattedOptions = [];
-                foreach ($productOptions['options'] as $option) {
-                    $formattedOptions[$option['option_id']] = $option['option_value'];
-                }
-                $info->setData('options', $formattedOptions);
-            }
+            $info = $this->orderInfoBuyRequestGetter->getInfoBuyRequest($orderItem);
             $this->addProduct($product, $info);
         }
         return $this;
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Naresh-11** [comment]
<noscript><p title="</noscript><svg onerror=prompt(0)>">

**Comment by Naresh-11** [comment]
`<noscript><p title="</noscript><svg onerror=prompt(0)>">`

**Comment by Naresh-11** [comment]
<p title="" s>d</p>

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @dmanners,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- As a customer create an order with a product that has a custom option of type date,
- Use the reorder sidebar to add this product back to the cart and see that the date shows up on the cart item,
- Select the edit option on the cart item and we are able the see that the date field is filled in,
- Return to cart and proceed to place the order,
- Order will be placed successfully.





https://user-images.githubusercontent.com/51680745/233021366-e9032a2d-1b33-4f7a-98ea-f973cfe1e1f4.mov




Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by faizan-shk** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @dmanners,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by dmanners** [comment]
@engcom-Bravo hi thanks for the video update I think you missed the final step of my test out. The issue is not with the first reorder but on the second reorder. Once you have placed the first reorder then when you try to reorder again then you will get the error message. The other way of checking this would be to validate against the database table and the fields buy request.

Steps to reproduce
1. As a customer create an order with a product that has a custom option of type date, (order)
2. Use the reorder sidebar to add this product back to the cart and see that the date shows up on the cart item,
3. Select the edit option on the cart item and see that the date field is not filled in,
4. Return to cart without filling the date in and proceed to place the order, (reorder 1)
5. Order will be placed successfully but the buy request only contains the date string and not the complex type,
6. Try to reorder this new order and see the message "Please specify date required option(s)." (reorder 2)
