### ISSUE TITLE
Must override at least one static content file or custom theme static content won't deploy 

### ISSUE THREAD

**Issue by dnadle** [magento/magento2#3754]
## Steps to reproduce
1. I created a custom theme with Magento/blank as parent, to override a template.
2. I did not override any static content. (nothing in the theme's web folder).
3. I ran bin/magento setup:static-content:deploy
## Expected result

The static content requests would fall back to load from the Magento/blank theme.
## Actual result

All of the static content links in pub/static/theme 404'd.
## Workaround

I added a logo file to theme/web/images and reran setup:static-content:deploy. This time all the files were generated in pub/static.

**Comment by zanilee** [comment]
Hi, @dnadle!

Thank you for reporting this issue.
Internal ticket MAGETWO-52102

**Comment by piotrekkaminski** [comment]
The issue is currently in progress.

**Comment by Krapulat** [comment]
Same problem in Magento 2.1.

**Comment by tarnagas** [comment]
Same problem in Magento 2.0.7

**Comment by wert2all** [comment]
Fixed

**Comment by pinkdigital** [comment]
This is still an issue in 2.1. Without an image in theme/web/image it ignores the theme.

**Comment by keyurshah** [comment]
had this same issue in 2.1. took a while to figure out until I saw the workaround.

**Comment by OLTC-fperrin** [comment]
Still an issue in 2.0.9. I had to create an empty test.js file in `app/design/adminhtml/[Package]/[Theme]/web` for the theme to deploy

**Comment by fxdegroot** [comment]
Why is this closed ? Still an issue in CE 2.1.1

**Comment by MarekKarmelski** [comment]
Confirm! Still bug in CE 2.1.2

**Comment by shahankitb997** [comment]
Yes. I face same issue in Magento 2 CE Version 2.1.2. What is solution?

**Comment by mrkhoa99** [comment]
When creating a new custom theme, if we don't have any assets files under `web` folder, your theme may be ignored when executing deploy command.

**Comment by jurgisl** [comment]
Still a bug in CE 2.1.3.

**Comment by Nguyen-Cong-Anh** [comment]
still a bug CE 2.1.4

**Comment by dersam** [comment]
This issue still exists in 2.1.5.

**Comment by lfolco** [comment]
Please reopen this!

**Comment by pguedesbr** [comment]
Issue still exists. 
I've had to create a dummy static file (dummy.js) so the child theme wouldn't be ignored by setup:static-content:deploy command

**Comment by DnDDeployer** [comment]
Still exist in 2.1.6

**Comment by JoJuhasz** [comment]
I confirm still present in 2.1.6.
Ok workaround is quite simple, but still an issue :)

**Comment by charmeleon-zz** [comment]
Still an issue in 2.1.7... that's two days of my life I won't get back :(

**Comment by erfanimani** [comment]
Yeah, same issue on 2.1.7..

**Comment by rouralberto** [comment]
Please reopen this, is still an existing issue.

**Comment by Igloczek** [comment]
It will be released with 2.2.0 unless someone will create a backport for 2.1.x.

**Comment by Anshu-Mishra** [comment]
I have experienced this issue in 2.1.8 as well.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72253
