### ISSUE TITLE
Minicart items height

### ISSUE THREAD

**Issue by Totarenx** [magento/magento2#3762]
Steps to reproduce
I.
1. Install Magento 2.0.2.
2. Add 4 Products to the cart.
3. Refresh page!!!
4. Open minicart

Expected result
![image](https://cloud.githubusercontent.com/assets/14783879/13740420/c6e22894-e9e1-11e5-9172-d25270150411.png)

Actual result
![image](https://cloud.githubusercontent.com/assets/14783879/13740489/17b25aaa-e9e2-11e5-9592-acd699e2b5e8.png)

II.
1. Install Magento 2.0.2.
2. Add 4 Products to the cart.
3. Open minicart
4. Scroll to bottom
5. Close/open minicart few times

Expected result
![image](https://cloud.githubusercontent.com/assets/14783879/13740617/da6da216-e9e2-11e5-9a82-5ffa45235611.png)

Actual result
![image](https://cloud.githubusercontent.com/assets/14783879/13740587/aa7077f0-e9e2-11e5-84a9-9e9121a16d2f.png)

**Comment by ishakhsuvarov** [comment]
@Totarenx Thank you for reporting this issue.
It is already fixed and delivered to the `develop` branch. Most likely the fix will be available with the next major release.

**Comment by AndyArcherKG** [comment]
@ishakhsuvarov What version of M2 was this fixed in?

**Comment by santanajames** [comment]
This issue still exists. Any update of when this will be release?

**Comment by nmallepally** [comment]
Hi,

This issue still exists on Magento 2.1.6 and 2.1.8.
Any fix available ? 


Best Regards,
Navya

**Comment by Krupaly2k-zz** [comment]
Hi,

I am using 2.1.7 and this issue still there.
Please advise for solution.

Thanks,
Krupal
