### ISSUE TITLE
js-translation.json is not generated

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#3771]
I have Magento2 localized to es_ES. Translations work partially.

First of all, I have generated the CSV using Magento2 way but some translations were not included in CSV file.

Well.. for those non-translated sentences, I have being adding to the file manually.

The problem I always have is that js-translation.json file were not generated automatically. So I have created it manually and copied inside i18n/[company]/es_es/ folder, in the same location as CSV file.

With that action, that json file were copied automatically to pub/static folder, but today, I did that again, but it is impossible the  json file to be copied.

I think this a bug in translation system.

Any workaround on this?

By the way. I am in development mode, with full cache disabled.

Regards
Jaime

**Comment by thomvanderboon** [comment]
Known problem: https://github.com/magento/magento2/issues/2056

**Comment by hshar7** [comment]
Hi @jaimestuardo I have tried translations with latest develop branch and I can say almost all phrases are translated. Could you please use develop branch and let us know if this issue persists? Otherwise we can close :)

**Comment by piotrekkaminski** [comment]
@antboiko please review and create ticket if needed

**Comment by antboiko** [comment]
Hi @jaimestuardo , I've created internal ticket MAGETWO-54632 to investigate this.

Thanks,
Anton.

**Comment by avra911** [comment]
Hi, @antboiko!

I can confirm this issue still persist in 2.1.3 version. However in `developer` mode seems fine, while in `production` mode the generated file `js-translation.json` contains only `[]`. Maybe this can help.

**Comment by ekupelian** [comment]
As a workaround it seems that deleting js-translation.json from pub/static/frontend/Magento/[theme]/[lang_code]/ allows "setup:static-content:deploy [lang_code]" to correctly generate the file.

**Comment by veloraven** [comment]
We have internal ticket MAGETWO-61923 for ver. 2.1

**Comment by magento-engcom-team** [comment]
@jaimestuardo thank you for the report. The issued fixed in MAGETWO-59042 and available in 2.2.0

**Comment by pitangaweb** [comment]
It still does not work on Magento 2.2. My js-translation.json contains only "[]"

**Comment by Eddcapone** [comment]
Does still not work in Magento 2.4.4
