### ISSUE TITLE
Trying to access array offset on value of type null in BulkInventoryTransfer.php on line 131

### ISSUE THREAD

**Issue by dennismetz** [magento/magento2#37743]
### Preconditions and environment

Magento version 2.4.5-p3
PHP8.1.x
Apache/NGINX, both

### Steps to reproduce

Under Stores->Sources add new Source.
Under Stores->Stocks add new Stock (Main Website, Assign new Source from above)

Go to catalog -> products -> select 2 or more products (one with assigned source, one without) -> Actions -> Transfer Inventory to Source.
Transfer from the origin source to the destination source.
Check (or check not) "Unassign the origin source from selected products after transfer."
Hit "Transfer Inventory" button.

### Expected result

Display Error Message like:
Selected products are not assigned to any source.

### Actual result

Warning: Trying to access array offset on value of type null in vendor/magento/module-inventory-catalog/Model/ResourceModel/BulkInventoryTransfer.php on line 131

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @dennismetz,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached vidoe.


**Steps to reproduce**


- Under Stores->Sources add new Source.
- Under Stores->Stocks add new Stock (Main Website, Assign new Source from above)
- Go to catalog -> products -> select 2 or more products (one with assigned source, one without) -> Actions -> Transfer Inventory to Source.
- Transfer from the origin source to the destination source.
- Check (or check not) "Unassign the origin source from selected products after transfer."
- Hit "Transfer Inventory" button.


https://github.com/magento/magento2/assets/51680745/e26c5ccb-4bf3-46cc-a782-281bb1f14b78


We are not getting error.for one of the product we are not assigned any source.



As per this document https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/inventory-transfer.html?lang=en. every product should have assigned source otherwise the product will be skipped.Kindly refer this document.


<img width="1063" alt="Screenshot 2023-07-11 at 12 28 08 PM" src="https://github.com/magento/magento2/assets/51680745/586a7a2c-ba80-4993-8b32-d699157235e2">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @dennismetz,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37743#issuecomment-1630262520  still you are working on the issue if you are able to reproduce the issue please elaborate the steps to reproduce and let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @dennismetz,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by MihaiComan90** [comment]
@engcom-Bravo i can validate that this issue is still reproducible for Magento 2.4.6-p1 so it is valid with the steps provided above.

**Comment by arion-p** [comment]
I can also validate the issue in 2.4.6-p1. Furthermore, if some (but not all) of the products are assigned to the "from" source, ALL products are skipped not just the ones without the source (i.e. the entire operation is aborted).
