### ISSUE TITLE
Null Eciflag Value from Braintree Can Result in Captured Payment with No Order

### ISSUE THREAD

**Issue by xaevik** [magento/magento2#37896]
### Preconditions and environment

Magento Version: 2.4.6-p2

Currently, a boundary case exists within the braintree module that can cause orders not to be created but the payment still to be captured when the eciFlag result is `null`. This occurs usually with 3D Secure response codes such as `authentication_unavilable` and `lookup_error`. 

This is due to the method `PayPal\Braintree\Gateway\Response\ThreeDSecureDetailsHandler::getEciFlagInformation()` not accepting a nullable string.

### Steps to reproduce

1. Configure **3D Secure Verification Settings** within Braintree
2. Place an order using a [test card](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live/php) that will ensure no `eciFlag` value is returned such as `status: lookup_error`

### Expected result

Order (and invoice if **Payment Action** is set to `Intent Sale`) created

### Actual result

An exception is thrown under the covers, user is presented with `Something went wrong with your request. Please try again later.` message and no order is created. 

Side effect: If `Intent Sale` is configured for **Payment Action** the payment is captured but there is no associated order.

#### Truncated Stack Trace

```php
TypeError: PayPal\Braintree\Gateway\Response\ThreeDSecureDetailsHandler::getEciFlagInformation(): Argument #1 ($eciFlagValue) must be of type string, null given, called in /var/www/html/vendor/paypal/module-braintree-core/Gateway/Response/ThreeDSecureDetailsHandler.php on line 73 and defined in /var/www/html/vendor/paypal/module-braintree-core/Gateway/Response/ThreeDSecureDetailsHandler.php:85
Stack trace:
#0 /var/www/html/vendor/paypal/module-braintree-core/Gateway/Response/ThreeDSecureDetailsHandler.php(73): PayPal\Braintree\Gateway\Response\ThreeDSecureDetailsHandler->getEciFlagInformation(NULL)
```

#### Proposed Patch
```diff
--- a/vendor/paypal/module-braintree-core/Gateway/Response/ThreeDSecureDetailsHandler.php	2023-08-18 10:53:23.969992018 -0400
+++ b/vendor/paypal/module-braintree-core/Gateway/Response/ThreeDSecureDetailsHandler.php	2023-08-18 10:53:28.499938934 -0400
@@ -82,7 +82,7 @@
      * @param string $eciFlagValue
      * @return mixed|string
      */
-    public function getEciFlagInformation(string $eciFlagValue)
+    public function getEciFlagInformation(?string $eciFlagValue)
     {
         if ($eciFlagValue !== null && array_key_exists($eciFlagValue, self::ECI_ACCEPTED_VALUES)) {
             return self::ECI_ACCEPTED_VALUES[$eciFlagValue];

```

#### Truncated Response
```
        'threeDSecureInfo' =>
        \Braintree\ThreeDSecureInfo::__set_state(array(
           '_attributes' =>
          array (
            'liabilityShifted' => false,
            'liabilityShiftPossible' => false,
            'status' => 'lookup_error',
            'enrolled' => NULL,
            'cavv' => NULL,
            'xid' => NULL,
            'acsTransactionId' => NULL,
            'dsTransactionId' => NULL,
            'eciFlag' => NULL,
            'acsUrl' => NULL,
            'paresStatus' => NULL,
            'threeDSecureAuthenticationId' => '2tm82nsd8fvgq4dw7j',
            'threeDSecureServerTransactionId' => 'fe188c71-b75b-4cb5-9d27-309c6c00348a',
            'threeDSecureVersion' => '2.1.0',
            'lookup' =>
            array (
              'transStatus' => NULL,
              'transStatusReason' => NULL,
            ),
            'authentication' =>
            array (
              'transStatus' => NULL,
              'transStatusReason' => NULL,
            ),
          ),
        )),
```
        

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @xaevik ,

verified the issue latest stable version  2.4.7beta1 instance and the issue is not reproducible,Kindly recheck the behaviour.
Kindly refer the below screenshots:
<img width="1438" alt="Screenshot 2023-08-18 at 9 14 53 PM" src="https://github.com/magento/magento2/assets/60198592/24c28677-cde3-4bce-8ebb-aa34c4ba9b5a">
<img width="1504" alt="Screenshot 2023-08-18 at 9 17 37 PM" src="https://github.com/magento/magento2/assets/60198592/dffb00db-0ca3-4bf2-91fc-7222899f9960">
<img width="1504" alt="Screenshot 2023-08-18 at 9 18 33 PM" src="https://github.com/magento/magento2/assets/60198592/9d37b088-93af-40a0-a2ab-d019c7a14dcb">
<img width="1504" alt="Screenshot 2023-08-18 at 9 20 26 PM" src="https://github.com/magento/magento2/assets/60198592/fcf8ef76-f536-44c2-a21b-99fb7c6dbb57">
Thanks.

**Comment by xaevik** [comment]
Why was this reproduction done on a version other than what was reported? We are not (and customers should not) be running beta releases in a production environment.

With that said, we still do not feel that this conclusion is accurate. Looking at the code in 2.4.7-beta1 the method only has a slightly different signature from 2.4.6-p2

## 2.4.6
```php
public function getEciFlagInformation(string $eciFlagValue = null)
```

## 2.4.7
```php
public function getEciFlagInformation(string $eciFlagValue = null): string
```

Now with that said, we did fail to initial report that we are running on PHP `8.2` and for all our environments, was this test conducted with that version of PHP or was it with `8.1` as type safety changed slightly in `8.2` with regards to `null`, `true`, and `false` handling.

We were able to reproduce this bug both in our local environment and in the Adobe Commerce Cloud environment, both of which are running PHP `8.2`.

**Comment by andy-igoo** [comment]
We're experiencing this error also on 2.4.5-p3 and PHP 8.1.18.

**Comment by engcom-Dash** [comment]
Hi @xaevik ,

Verified the issue in 2.4.6 as per your last [comment](https://github.com/magento/magento2/issues/37896#issuecomment-1686164215)and the issue can be reproducible,Kindly refer the below screenshot:
<img width="1512" alt="Screenshot 2023-08-22 at 10 20 06 PM" src="https://github.com/magento/magento2/assets/60198592/9e7dcee5-8cdd-4a67-b3ab-595fdd62a036">
But the Problem we are not getting in latest stable version of 2.4.7-beta1 issue may got fixed latest version.

Thanks.

**Comment by xaevik** [comment]
Hi @engcom-Dash 

Are there any plans to address this bug in the upcoming `2.4.6-p3` or `2.4.5-p5` (as someone has already reported that it is present in `2.4.5-p3`)? It is an impediment for anyone using 3D Secure with Braintree (especially in Europe where PSD2 is a requirement) if they are capturing payment at time of order and not time of fulfillment as credits must be issued if the transaction settled before it could be voided, adding further costs.

Right now we are solving it with a home-grown composer patch but this feels like it should be a candidate either for a quality patch or inclusion into the next patch release.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by RajasekarPanneerselvam** [comment]
@magento give me 2.4-develop instance

**Comment by ThisIsRuddy** [comment]
@xaevik 100% agree with everything you've been saying here

+1000

**Comment by engcom-Dash** [comment]
Hi @xaevik 

Thanks for reporting and collaboration.

Verified the issue in Magento 2.4 dev instance but the issue is not reproducable.

Able to place the order successfully when the Payment Action is set to Intent Sale via braintree.

Please refer the screenshot attached.

<img width="1422" alt="image (1)" src="https://github.com/magento/magento2/assets/60198592/b0a971bd-a15a-4fb2-b418-4fa32d1a8f2c">

Please check the issue in latest magneto 2.4 dev instance and let us know if you are still facing the issue.

Thanks.

**Comment by engcom-Dash** [comment]
Hi @xaevik 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Comment by joesken** [comment]
Can confirm this issue is still occurring on 2.4.5-p7 / PHP 8.1.28. Verified the cause with Braintree also.

**Comment by engcom-Dash** [comment]
Hi @xaevik 

Verified the issue again on magento 2.4 dev instance and the issue is not reproduca

Able to place the order successfully when the Payment Action is set to Intent Sale and 3D Secure Verification is enabled via braintree.

Steps to reproduce

1. Configure 3D Secure Verification Settings within Braintree
2. Place an order using a [test card](https://developer.paypal.com/braintree/docs/guides/3d-secure/testing-go-live/php) that will ensure no eciFlag value is returned such as status: lookup_error

Please refer the screenshot attached. Let us know if we missed anything.


https://github.com/magento/magento2/assets/60198592/ccbc7d96-6380-406b-8e09-c13a18666adc

**Comment by xaevik** [comment]
@magento give me 2.4-develop instance

**Comment by xaevik** [comment]
Hi @engcom-Dash:

So, after some investigation, it appears that yes, it is fixed but **only** for users that are using release [4.6.1](https://support.gene.co.uk/support/solutions/articles/35000228529-braintree-release-notes-for-v4-6-1-adobe-commerce-magento-open-source-v2-4-7-) of the GENE Commerce module.

![image](https://github.com/magento/magento2/assets/62903002/a0b4193e-e672-41f1-b7dc-7e9df57eb2a4)

As the instances being deployed by the magento-deployment-service bot are running the dev-develop branch (2.4.7.x), this means the issue cannot be accurately reproduced.

However, users running Magento < 2.4.7 will be locked to 4.5.0 (or lower) of the GENE Commerce extension due to an explicit version lock.

![image](https://github.com/magento/magento2/assets/62903002/e1c89d61-f4ba-4cb4-bb80-8d98d6e11a1d)
![image](https://github.com/magento/magento2/assets/62903002/e57a2467-19f4-4cbe-8e45-4b59fff6f772)

With that said, the bug is still definitely present for users of any in-support branch that is not 2.4.7 (supported by the numerous comments on this issue). So, with that said, a fix needs to be deployed. Preferably this means that **paypal/module-braintree** needs new patch releases (4.5.0-p2 for 2.4.6.x, 4.4.0-p3 for 2.4.5.x and 4.3.0-p2 for 2.4.4.x).

Until then, users will be forced to install a composer patch (such as the one I provided in the initial issue comment) or they will encounter the problem.

**Comment by engcom-Dash** [comment]
Hi @xaevik 

Thanks for reporting and collaboration.

We have verified the issue on Magento 2.4 latest dev instance and the issue is not reproducible for us.

Please try upgrading your instance to the latest Magento instance.

Thanks

**Comment by xaevik** [comment]
Hi @engcom-Dash 

There is a communication breakdown here because it is obvious that the scope of the problem is not being understood. Yes, as pointed in https://github.com/magento/magento2/issues/37896#issuecomment-2139337759, the issue is resolved because the underlying dependency was fixed.

However, it *is not fixed* for any users that have an in-support branch (2.4.4, 2.4.5, 2.5.6) installed. Given that these releases are still considered in-support and that many users (ourselves included) are still running them and that the problem affects any user of the payment method, the issue fix should be backported (as per https://github.com/magento/magento2/issues/37896#issuecomment-2139337759). Upgrading to a newer release that has significant breaking changes is not a viable option.
