### ISSUE TITLE
Infinite loading after 999 page was selected

### ISSUE THREAD

**Issue by lghelghe** [magento/magento2#37941]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

log in
Changed to 999 per page
infinite loading will never stop then show error popup
but no way to get out

### Expected result

either it gives me an option to change # per page, or way to reset all filters to default

### Actual result

infinite loading & error popup > repeat

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @lghelghe,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- log in
- Changed to 999 per page



https://github.com/magento/magento2/assets/51680745/482da746-6953-4891-80af-d96f28381451




Could you please provide screenshots or video which error you are getting while filtering the page.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @lghelghe,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37941#issuecomment-1700899113  still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @lghelghe,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by lghelghe** [comment]
Hi,
Still experiencing the issue.
I was able to see the result with 999 per page option; however, the issue started to occur few days after with 999 per page option saved
![image](https://github.com/magento/magento2/assets/143628070/1cd04783-b171-47a4-97c1-1ba0d89490aa)
