### ISSUE TITLE
Magento 2.4.6-p2 : Product import not working and its showing exception "Invalid Stock data for insert" and same inventory import also not working

### ISSUE THREAD

**Issue by Banuchanthiran-N** [magento/magento2#37952]
### Preconditions and environment

- Magento Version is 2.4.6-p2
- Error is showing on the import screen
![error_for_product_import](https://github.com/magento/magento2/assets/69510029/8ad98bb0-b07e-40d7-9132-0fdbfc32d4e1)
![Screenshot 2023-09-02 105119](https://github.com/magento/magento2/assets/69510029/5f04fb27-39fd-49ea-a2b3-06138e2abcea)

### Steps to reproduce

1. Import done using the following csv file: 
[Magento_products_delta_2023-09-01 -testing.csv](https://github.com/magento/magento2/files/12503467/Magento_products_delta_2023-09-01.-testing.csv)

2. Navigate to System> Imports
3. Select Entity Type: Products, Import Behaviour: Add/Update, Validation Strategy: Skip error entries, Multiple value Separator: |
4. Click "Check Data" (No errors should surface)
5. Import (error should appear on next screen)

### Expected result

Successful upload without errors as we have uploaded this product successfully before.

### Actual result

1. Product Type is invalid or not supported in row(s): 2, 3, 4, 5
General system exception happened
Additional data: <div class="messages"><div class="message message-error error"><div data-ui-id="messages-message-error" >Invalid Stock data for insert</div></div></div>
![error_for_product_import](https://github.com/magento/magento2/assets/69510029/a6870194-b712-49d2-9dc2-436acdb5aae4)
![Screenshot 2023-09-02 105119](https://github.com/magento/magento2/assets/69510029/411c0cb9-1074-4bef-b6f9-139b5766c1b2)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Banuchanthiran-N,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Import done using the following csv file:
- [Magento_products_delta_2023-09-01 -testing.csv](https://github.com/magento/magento2/files/12503467/Magento_products_delta_2023-09-01.-testing.csv)
- Navigate to System> Imports
- Select Entity Type: Products, Import Behaviour: Add/Update, Validation Strategy: Skip error entries, Multiple value Separator: |
- Click "Check Data" (No errors should surface)
- Import (error should appear on next screen)


<img width="1480" alt="Screenshot 2023-09-04 at 12 39 34 PM" src="https://github.com/magento/magento2/assets/51680745/fa7fa456-16ea-4ccb-867c-724d5a1ab727">



<img width="1512" alt="Screenshot 2023-09-04 at 12 39 41 PM" src="https://github.com/magento/magento2/assets/51680745/148c3fb1-91a7-4ee0-9a7c-efa8c81ca447">




<img width="1485" alt="Screenshot 2023-09-04 at 12 40 08 PM" src="https://github.com/magento/magento2/assets/51680745/a5287ee5-8365-431f-b206-969e939ff7ee">




We are able to import successfully with the given CSV file without any errors.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @Banuchanthiran-N,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37952#issuecomment-1705151207 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @Banuchanthiran-N,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by andreidragutu** [comment]
@engcom-Bravo Hi, this is not fixed. Reproducing on Magento 2.4.6-p3 on Adobe Commerce Cloud.
