### ISSUE TITLE
Cms repository implementation does not adhere to interface

### ISSUE THREAD

**Issue by samtay** [magento/magento2#3796]
This is true for at least blocks and pages, and might be true of other entities as well.

[Here](https://github.com/magento/magento2/blob/798a8420e5738ceb5f2dcb332a59c7ee60b83444/app/code/Magento/Cms/Api/Data/PageSearchResultsInterface.php#L19) you can see that the `Magento\Cms\Api\Data\PageSearchResultsInterface::getItems` should return an array of a data objects that implement `\Magento\Cms\Api\Data\PageInterface`.

Instead in [your implementation](https://github.com/magento/magento2/blob/798a8420e5738ceb5f2dcb332a59c7ee60b83444/app/code/Magento/Cms/Model/PageRepository.php#L174-L188) you are returning an array of arrays.

This causes unexpected behavor. When a developer is iterating over the array returned from `getItems`, I expect to be able to call `$page->getId()`, but `$page` is just an array so this results in fatal error: call to undefined function.

**Comment by samtay** [comment]
Furthermore, one would expect the array to at least have all of the data keys identified in the `PageInterface`, but the `page_id` key is missing (arguably the most important data piece!)

**Comment by shiftedreality** [comment]
Hi @SamTay 

Looks like a bug. Created internal ticket MAGETWO-50578 for further investigation.
Thank you for your submission.

**Comment by piotrekkaminski** [comment]
This isssue is fixed.

**Comment by JamesonNetworks** [comment]
I'm still seeing this on 2.1.7. Do we know what official version of Magento 2 this will make it into? @shiftedreality @piotrekkaminski
