### ISSUE TITLE
Catalog search index process error indexation process

### ISSUE THREAD

**Issue by dariovranjkovic** [magento/magento2#38254]
### Preconditions and environment

- Magento version 2.4.3.
- Elasticsearch 7.10

### Steps to reproduce

1. Run re-index command 

### Expected result

Reindex without error messages

### Actual result

Catalog Search index process error during indexation process:
Processed schema file: public_html/vendor/magento/module-elasticsearch/etc/esconfig.xsd
complex type 'mixedDataType': The content model is not determinist.

### Additional information

Site was working fine long time, and after run re-index I got error message:

Catalog Search index process error during indexation process:
Processed schema file: public_html/vendor/magento/module-elasticsearch/etc/esconfig.xsd
complex type 'mixedDataType': The content model is not determinist.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devbikash07** [comment]
Hi @dariovranjkovic , It is an issue related to updated ea-libxml2 package. Please downgrade that package using command

`yum downgrade ea-libxml2-2.11.*`

and retry running reindex.

**Comment by engcom-Bravo** [comment]
@devbikash07 Thanks for your contribution & collaboration over here.

Hi @dariovranjkovic,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Screenshot from 2023-12-11 13-25-22](https://github.com/magento/magento2/assets/51680745/a86bcf7c-5fe2-416e-a210-7359b6b38764)

Could you please refer this comment https://github.com/magento/magento2/issues/38254#issuecomment-1847465089


Thanks.

**Comment by ainigma32** [comment]
It is true that downgrading xmllib to a version below 2.12.0 will resolve the problem but only because those versions of libxml allowed invalid XML schemas. See [this issue](https://gitlab.gnome.org/GNOME/libxml2/-/issues/624) for more info.
If we check the files vendor/magento/module-elasticsearch/etc/esconfig.xml and vendor/magento/module-elasticsearch/etc/esconfig.xsd through xerces using [this online service](https://www.softwarebytes.org/xmlvalidation/) we get the error: [Error] esconfig.xsd:18:38:cos-nonambig: default and WC[##any] (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.

I am not an expert on XSD's so I could be wrong but this would suggest the XSD is actually invalid and should be corrected.

**Comment by engcom-Bravo** [comment]
@ainigma32 Thanks for your contribution & collaboration over here.

@dariovranjkovic Could you please refer this document https://github.com/magento/magento2/issues/38254#issuecomment-1855451601 and please let us know if you are still facing any issue.

Thanks.

**Comment by Kishorchhugani** [comment]
I am facing the same issue , @dariovranjkovic   can you find out any solution ?

**Comment by dariovranjkovic** [comment]
@Kishorchhugani yes we found solution

It is an issue related to updated ea-libxml2 package. Please downgrade that package using command
yum downgrade ea-libxml2-2.11.*

**Comment by CalamityJames** [comment]
> @Kishorchhugani yes we found solution
> 
> It is an issue related to updated ea-libxml2 package. Please downgrade that package using command yum downgrade ea-libxml2-2.11.*

Thanks for that temporary fix. Hopefully the details @ainigma32 provided will let the Magento team provide a more permanent fix. Currently this issue reoccurs daily due to our server host forcing WHM to update daily with no apparent way to disable this any more.

**Comment by Kishorchhugani** [comment]
This Works For me ,
I don't know it is safe or not but it works  !!

 remove one line check it
vendor/magento/module-elasticsearch/etc/esconfig.xsd
<xs:element type="xs:string" name="default" minOccurs="1" maxOccurs="1" />

**Comment by ainigma32** [comment]
> I don't know it is safe or not but it works !!

Yes that also works and as long as you don't add any invalid esconfig.xml files it should be fine.
Removing that line will make the XSD valid in the eyes of libxml but it will no longer check if your esconfig.xml files contain a "default" element.

**Comment by engcom-Bravo** [comment]
As per this https://github.com/magento/magento2/issues/38254#issuecomment-1857679183 we are closing this issue.As issue has been resolved.

Thanks.

**Comment by CalamityJames** [comment]
Sorry, but downgrading a built in library that actually implements a correct schema checking for XML is not a fix. This will break any magento installs for anyone with automatic updates enabled who runs EasyApache on WHM and also anyone else who updates libxml.

Can this be reopened please?

**Comment by CalamityJames** [comment]
@engcom-Bravo please see my above comment re the "solution" that was accepted.

**Comment by maxq** [comment]
Our host made an automatic upgrade, breaking two of our sites, I figured out to change it to using MySql or they both still be broken.
14 days later they just figured out they did this. So it's very much a reproducible error.

Great timing right in the middle of the holiday rush.
Hope a fix is found soon (apart from downgrading the library)

**Comment by hostep** [comment]
Issue makes sense, seems like core bug, @engcom-Bravo or @ihor-sviziev, can we get this reopened?

If I understand it correctly, it's because this code in [the xsd file](https://github.com/magento/magento2/blob/881ca232849cfa37205747b6b87625fc0fd6e0b4/app/code/Magento/Elasticsearch/etc/esconfig.xsd#L20-L21):
```xml
        <xs:element type="xs:string" name="default" minOccurs="1" maxOccurs="1" />
        <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
```

It first says: we need an element `<default>` that needs to exists and it also says, next to that we can have "any" element (so including `<default>`) 0, 1 or multiple times. Both statements conflict with each other.

Out of curiosity, does changing `minOccurs="0"` to `minOccurs="1"` on that `xs:any` also fix the issue? I currently can't install libxml 2.12.0 so can't test it out myself I'm afraid.

**Comment by dossy** [comment]
> It is true that downgrading xmllib to a version below 2.12.0 will resolve the problem but only because those versions of libxml allowed invalid XML schemas. See [this issue](https://gitlab.gnome.org/GNOME/libxml2/-/issues/624) for more info. If we check the files vendor/magento/module-elasticsearch/etc/esconfig.xml and vendor/magento/module-elasticsearch/etc/esconfig.xsd through xerces using [this online service](https://www.softwarebytes.org/xmlvalidation/) we get the error: [Error] esconfig.xsd:18:38:cos-nonambig: default and WC[##any] (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.
> 
> I am not an expert on XSD's so I could be wrong but this would suggest the XSD is actually invalid and should be corrected.

See also: https://stackoverflow.com/questions/37486498/xsdany-other-elements-inside-choice

In particular, it says that using `xs:choice` with `xs:element` and `xs:any` will work with XSD 1.1, but not XSD 1.0, where it fails the [Unique Particle Attribution](https://www.w3.org/TR/xmlschema-1/#cos-nonambig) constraint.  And, sure enough, using that online schema validator service and selecting `Select an XSD version to use, during validation = 1.1` yields the following output:

```
You selected XSD 1.1 validation.

XML document is assessed as valid with the XSD document(s) you have provided.
```

Given that:

1. Magento is [using `DOMDocument::schemaValidate()`](https://github.com/magento/magento2/blob/881ca232849cfa37205747b6b87625fc0fd6e0b4/lib/internal/Magento/Framework/Config/Dom.php#L353-L396),
2. and the [PHP documentation for `DOMDocument::schemaValidate()`](https://www.php.net/manual/en/domdocument.schemavalidate.php) indicates that "Only XML Schema 1.0 is supported"
3. and the [PHP bug about this](https://bugs.php.net/bug.php?id=79391) points out that PHP is just using [libxml2](https://gitlab.gnome.org/GNOME/libxml2)
4. and that [libxml2 only implements XML Schema 1.0](https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home)

It looks like using an XSD that requires XML Schema 1.1 is out of the question, at least in the short term.

I think the we should comment out `<xs:element type="xs:string" name="default" minOccurs="1" maxOccurs="1" />` and add a comment before it indicating that uncommenting it would require a XML Schema 1.1 validator, and if PHP ever gets a XML Schema 1.1 validator, and Magento implements whatever changes are necessary to use it, then uncomment the line then.

**Comment by engcom-November** [comment]
Thank you @dossy for detailed breakdown of the issue.

As mentioned here https://github.com/magento/magento2/issues/38254#issuecomment-1887524551, magento is using [`DOMDocument::schemaValidate()`](https://github.com/magento/magento2/blob/881ca232849cfa37205747b6b87625fc0fd6e0b4/lib/internal/Magento/Framework/Config/Dom.php#L353-L396) to validate XML, and this method in turn is using libxml2.
 
`xs:choice` with `xs:element` and `xs:any` are only compatible with XSD 1.1, whereas libxml2 only supports XSD 1.0.
In the older version of libxml2, invalid XML Schemas(1.1) were not handled, but in the recent release they have addressed this bug. This is what causing the issue.
This can be seen [here](https://gitlab.gnome.org/GNOME/libxml2/-/issues/624).

Hence confirming this issue.

Thank you.

**Comment by hostep** [comment]
I've just send in this PR: https://github.com/magento/magento2/pull/38553 which seems to fix this problem. Feedback would be appreciated :)

**Comment by engcom-Bravo** [comment]
Hi,

Internal team has started to work on it

Thanks.

**Comment by ihor-sviziev** [comment]
For history: The fix was delivered to 2.4-develop branch in https://github.com/magento/magento2/commit/308e26105c97006d74e87d7c9e4c29d1ad5873f9 (cherry-picked changes from https://github.com/magento/magento2/pull/38553)

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-10838 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-10838&type=commits


Thanks

**Comment by Mereep** [comment]
Using latest Magento 2.4.7-p4. This error still happens. In the Storefront as well as in the indexing process.
