### ISSUE TITLE
CSS minifiying sometimes results in blank CSS file due to PREG_JIT_STACK_LIMIT_ERROR in tubalmartin/cssmin

### ISSUE THREAD

**Issue by nahall** [magento/magento2#38313]
### Preconditions and environment

Magento 2.4+
PHP 8+

### Steps to reproduce

Enable CSS minify

### Expected result

CSS is minified properly

### Actual result

Minified CSS ends up blank

### Release note

Magento uses the tubalmartin/cssmin dependency to do CSS minification. In PHP 8+ this can results in blank minified CSS files, depending on the content of the CSS that is being minified. This is due to a bug in vendor/tubalmartin/cssmin/src/Minifier.php line 324:

>         $css = preg_replace_callback(
>             '/(?:"(?:[^\\\\"]|\\\\.|\\\\)*")|'."(?:'(?:[^\\\\']|\\\\.|\\\\)*')/S",
>             array($this, 'processStringsCallback'),
>             $css
>         );

Where this regexp is causing the backtrack limit to be reached and generating a PREG_JIT_STACK_LIMIT_ERROR. However, Minifier.php is not checking for this error so the $css variable ends up being set to null which ends up causing the deprecation message:

exception: Deprecated Functionality: preg_replace(): Passing null to parameter #3 ($subject) of type array|string

However, this is a red herring as the reason $css is null is due to this error not being caught in the earlier function call.

The bug report in tubalmartin/cssmin is https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/issues/66

It seems like the options would be to fix the tubalmartin/cssmin dependency or switch Magento to a different library for CSS minification.

Current workaround is to disable CSS minification in Magento's config.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @nahall 

Thanks for reporting and collaboration.

Verified the issue on magento develop instance and issue is not reproducible.

We have followed the below steps to reproduce:

1. Log in to your Magento 2 admin panel
2.Navigate to Stores>Configuration
3.Go into the advanced tab and then the developer tab under configuration.
4.Go to CSS settings and set the minify option to ‘Yes'

The CSS is minified. properly. Please refer the attached screenshot.
<img width="1440" alt="cssminified" src="https://github.com/magento/magento2/assets/60198592/4f97c5de-ddd9-4499-a8da-d19c860e7d21">

**Comment by nahall** [comment]
This does not fail with the stock Magento CSS but only in certain cases.

Since the problematic regexp in the CSS minifier is:
```
    $css = preg_replace_callback(
        '/(?:"(?:[^\\\\"]|\\\\.|\\\\)*")|'."(?:'(?:[^\\\\']|\\\\.|\\\\)*')/S",
        array($this, 'processStringsCallback'),
        $css
    );
```

It seems likely that the CSS needs to contain a number of quotation marks in order to encounter the problem.

**Comment by engcom-Dash** [comment]
Hi @nahall 

Thanks for reporting and collaboration.

Can you please check if you are using any third party modules and try to reproduce the issue by disabling one by one. 
Please let us know if you are still facing the issue.

Thanks

**Comment by engcom-Dash** [comment]
Hi @nahall 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by nahall** [comment]
The bug is still happening. It is not because of third party modules but rather in certain cases of CSS.

**Comment by VladyslavSikailo** [comment]
The issue still exists. Can someone reopen this?
