### ISSUE TITLE
Add new eva attribute to category

### ISSUE THREAD

**Issue by gizmocn** [magento/magento2#3843]
In Magento CE 2.0.2 we can add new attribute from Setup/InstallData.php by using below code:

`$eavSetup->addAttribute(
            \Magento\Catalog\Model\Category::ENTITY,
            'category_label',
            [
                'group'         => 'Mega Menu',
                'input'         => 'text',
                'type'          => 'varchar',
                'label'         => 'Category Label',
                'backend'       => '',
                'visible'       => true,
                'required'      => false,
                'visible_on_front' => true,
                'note'          => 'Add label for category. Example "New", "Hot", "Sale"',
                'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
            ]
        );`

We develop a menu extension for Magneto2, and the extension work for Magento ce 2.0.2. 
but when we test in newest development version, it failed to add new attribute to category, how can I solve the issue?

**Comment by gizmocn** [comment]
What is "MX Label", I will provide more info if you need

**Comment by Vinai** [comment]
"MX" stands for "Merchant Experience" and is the problem domain related to the issue. It has to do with the delegation to internal teams.

**Comment by digimix** [comment]
@voleye has this been resolved in the newest dev version or yesterdays release? Having the same problem.

**Comment by gizmocn** [comment]
Just try 2.1 branch, the problem is still exist, any one can help?

**Comment by gizmocn** [comment]
@voleye Can you help for this?

**Comment by vkublytskyi** [comment]
@gizmocn, sorry for delay with response. I've tried to reproduce this issue but attribute with provided configuration was successfully created.

Would you provide more details on issue? What exactly errors appears during installation (PHP or SQL error messages, etc.)? Is any other extension installed except your Mega Menu extension? Would you provide content of etc/module.xml and list of required Magento modules specified in your composer.json?

**Comment by gizmocn** [comment]
@vkublytskyi , thanks, I have found some info about the issue, RC 2.1 use form component for category, so except to add attribute to table "eva_attribute",  it also need to extend category_form.xml to add field and fieldset.

So I close the case now, thanks!
