### ISSUE TITLE
[Issue] Cannot update Order status in 2.4.7

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38659]
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Try to update status from admin order page view

### Expected result

Status updated

### Actual result

Status not updated

### Additional information

I don't understand this change introduced in 2.4.7 : 
https://github.com/magento/magento2/issues/36562

```
private function getOrderStatus(string $orderStatus, string $historyStatus): string
    {
        return ($orderStatus === Order::STATE_PROCESSING || $orderStatus === Order::STATUS_FRAUD) ? $historyStatus
            : $orderStatus;
    }
```

Why would we be able to change status only if current status is processing or fraud ? (Also, `Order::STATE_PROCESSING` instead of `Order::STATUS_PROCESSING` )

If I understand correctly the issue #36562, the fix should be something like this instead : 
```
private function getOrderStatus(OrderInterface $order, string $historyStatus): string
    {
        $statuses = $this->orderConfig->getStateStatuses($order->getState());
        
        if (!in_array($status, array_keys($statuses))) {
            return $order->getStatus();
        }
        return $historyStatus;
    }
```

Or am I missing something ?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @Nuranto 

Thanks for reproting and collaboration.

Can you please provide detailed steps to reproduce with screenshots which would help us reproduce the issue accurately?

Thanks!

**Comment by Nuranto** [comment]
(https://fe74e6b08484c0858eb929e57e74a885.instances-prod.magento-community.engineering/admin_058a/sales/order/view/order_id/3/) 

https://github.com/magento/magento2/assets/1633463/5237d99c-86ec-4281-a216-2c7d84ed5854

**Comment by engcom-Dash** [comment]
Hi @Nuranto 

Verified the issue in 2.4.7 and 2.4 dev instances. 

But I am seeing only processing and suspend fraud options in order status after generating invoice.

Please refer to the screenshots. Let us know if we are missing anything.

<img width="1440" alt="Screenshot 2024-04-29 at 2 41 49 PM" src="https://github.com/magento/magento2/assets/60198592/d2e5f5ec-0fb3-4013-a95b-476c01441929">

**Comment by Nuranto** [comment]
I added a custom status on your temporary env.

As you can see in the code : 
```private function getOrderStatus(string $orderStatus, string $historyStatus): string
    {
        return ($orderStatus === Order::STATE_PROCESSING || $orderStatus === Order::STATUS_FRAUD) ? $historyStatus
            : $orderStatus;
    }```
We can update status, but only if current status is processing or fraud.

**Comment by engcom-Dash** [comment]
Hi @Nuranto 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev and 2.4.7 instances and the issue is reproducible. Hence, we are confirming the issue.

We are able to update the status only if the current status is in a processing or fraud state. If the status is anything other than processing or fraud state we are not able to update the status.

Please refer the attached screen recording.

https://github.com/magento/magento2/assets/60198592/6b72cbc4-fdc1-4b7c-b09c-48d80e667aba

**Comment by redati** [comment]
Related to the order status update, this commit  https://github.com/magento/magento2/commit/632f253106e0a2d68cbf0b5a58b12eeeb0a014bf also involves integration with Bling Erp. This integration updates the order via comment.

**Comment by dennismetz** [comment]
We have the same error in our Magento instances. Is there already a patch?

**Comment by superdav42** [comment]
I used a workaround and sharing it so it can be helpful to anyone:

Create app/code/DevStone/Bugfix/Controller/Adminhtml/Order/AddComment.php
```php
<?php

namespace DevStone\Bugfix\Controller\Adminhtml\Order;

use Magento\Framework\App\Action\HttpPostActionInterface;
use Magento\Sales\Model\Order\Email\Sender\OrderCommentSender;

/**
 * Class AddComment
 *
 * Controller responsible for addition of the order comment to the order
 */
class AddComment extends \Magento\Sales\Controller\Adminhtml\Order implements HttpPostActionInterface
{
    /**
     * Authorization level of a basic admin session
     *
     * @see _isAllowed()
     */
    public const ADMIN_RESOURCE = 'Magento_Sales::comment';

    /**
     * ACL resource needed to send comment email notification
     */
    public const ADMIN_SALES_EMAIL_RESOURCE = 'Magento_Sales::emails';

    /**
     * Add order comment action
     *
     * @return \Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        $order = $this->_initOrder();
        if ($order) {
            try {
                $data = $this->getRequest()->getPost('history');
                if (empty($data['comment']) && $data['status'] == $order->getDataByKey('status')) {
                    $error = 'Please provide a comment text or ' .
                             'update the order status to be able to submit a comment for this order.';
                    throw new \Magento\Framework\Exception\LocalizedException(__($error));
                }

                $order->setStatus($data['status']);
                $notify = $data['is_customer_notified'] ?? false;
                $visible = $data['is_visible_on_front'] ?? false;

                if ($notify && !$this->_authorization->isAllowed(self::ADMIN_SALES_EMAIL_RESOURCE)) {
                    $notify = false;
                }

                $comment = trim(strip_tags($data['comment']));
                $history = $order->addStatusHistoryComment($comment, $data['status']);
                $history->setIsVisibleOnFront($visible);
                $history->setIsCustomerNotified($notify);
                $history->save();

                $order->save();
                /** @var OrderCommentSender $orderCommentSender */
                $orderCommentSender = $this->_objectManager
                    ->create(\Magento\Sales\Model\Order\Email\Sender\OrderCommentSender::class);

                $orderCommentSender->send($order, $notify, $comment);

                return $this->resultPageFactory->create();
            } catch (\Magento\Framework\Exception\LocalizedException $e) {
                $response = ['error' => true, 'message' => $e->getMessage()];
            } catch (\Exception $e) {
                $response = ['error' => true, 'message' => __('We cannot add order history.')];
            }
            if (is_array($response)) {
                $resultJson = $this->resultJsonFactory->create();
                $resultJson->setData($response);
                return $resultJson;
            }
        }
        return $this->resultRedirectFactory->create()->setPath('sales/*/');
    }
}
```
Create app/code/DevStone/Bugfix/etc/di.xml:
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Sales\Controller\Adminhtml\Order\AddComment" type="DevStone\Bugfix\Controller\Adminhtml\Order\AddComment" />
</config>
```

Of course update the paths and namespace to match an existing module you may have or create a new one with the usual module.xml and registration.php

This will revert the behavior to pre 2.4.7

**Comment by YiffyToys** [comment]
Issue can be reproduced with 2.4.7-p1

**Comment by YiffyToys** [comment]
Something like this should work too

cat patches/github-issue-38659_cannot-update-orderstatus-magento-2-4-7.diff

```
diff --git a/vendor/magento/module-sales/Controller/Adminhtml/Order/AddComment.php b/vendor/magento/module-sales/Controller/Adminhtml/Order/AddComment.php
index ea8af5828c..34608db2bd 100644
--- a/vendor/magento/module-sales/Controller/Adminhtml/Order/AddComment.php     2024-06-29 09:53:19.997829986 +0200
+++ b/vendor/magento/module-sales/Controller/Adminhtml/Order/AddComment.php     2024-06-29 10:15:35.983809521 +0200
@@ -91,7 +91,12 @@
      */
     private function getOrderStatus(string $orderStatus, string $historyStatus): string
     {
-        return ($orderStatus === Order::STATE_PROCESSING || $orderStatus === Order::STATUS_FRAUD) ? $historyStatus
-            : $orderStatus;
+           // BUGFIX for https://github.com/magento/magento2/issues/38659
+           return $historyStatus;
+
+
+//        return ($orderStatus === Order::STATE_PROCESSING || $orderStatus === Order::STATUS_FRAUD) ? $historyStatus
+//            : $orderStatus;
+
     }
 }
```

cat magento/composer.json

```
...
 "extra": {
        "magento-force": "override",
        "enable-patching": true,
        "composer-exit-on-patch-failure": true,
        "patches": {
...
            "magento/module-sales": {
                "fix Magento 2.4.7 can not set update order status": "patches/github-issue-38659_cannot-update-orderstatus-magento-2-4-7.diff"
            }
        }
    }
```

**Comment by YiffyToys** [comment]
Nothing seems to have happend with the pull request #38659 in all of May and all of June.
While absolutely basic functionality is broken for all users out there.

**Comment by NeoM-dev** [comment]
Having same issue with 2.4.7 - Need solution soon have to send email for every process to update customers.

**Comment by joshbourke** [comment]
Having same issue. Major functionality broken. Issue been open for nearly 2 months. Fixes like this are taking far too long to review/release. I am not sure why we always need 100's of fixes in each release; it shouldn't be a huge deal to release a 2.4.7.1, 2.4.7.2, etc. with a couple dozen critical fixes.

**Comment by BeggiNN** [comment]
@magento I am working on this

**Comment by Quazz** [comment]
The order state should be checked rather than the status to begin with; no clue how this got greenlit.

You can make custom order statuses for a singular order state. With the changes that have been made it's impossible to change order status after it's been set.

You should be able to switch freely between order statuses for a similar order state. 

This needs to be rectified ASAP.

**Comment by dennismetz** [comment]
Almost four months since the bug was reported... is there any hope that a patch will be released soon?

**Comment by Henryrchurchill** [comment]
We are also waiting for a patch for this issue.

**Comment by redati** [comment]
I haven't seen it yet, but does 2.4.7-p2 solve this?

**Comment by YiffyToys** [comment]
At least the patch was still applied by Compose.

As you can see here,
even the current 2.4 development branch doesn't have a fix yet.
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Controller/Adminhtml/Order/AddComment.php#L94

**Comment by redati** [comment]
in a quick solution for an integration here, i just removed this code from that file.

vendor/magento/module-sales/Model/Service/OrderService.php

/**
         * change order status is not allowed during add comment to the order
         */
        if ($statusHistory->getStatus() && $statusHistory->getStatus() != $order->getStatus()) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('Unable to add comment: The status "%1" is not part of the order
                 status history.', $statusHistory->getStatus())
            );
        }

**Comment by chittima** [comment]
Internal team is working on this issue

**Comment by pkd87** [comment]
Any update on issue? We are using Magento 2.4.7.

**Comment by chittima** [comment]
The internal team already fixed this issue. Currently, in delivery queue.

**Comment by YiffyToys** [comment]
> The internal team already fixed this issue. Currently, in delivery queue.

So what about tagging this ticket with the milestone/release it is intended for?

**Comment by o-iegorov** [comment]
> > The internal team already fixed this issue. Currently, in delivery queue.
> 
> So what about tagging this ticket with the milestone/release it is intended for?

we can determine relese when the code changes will be delivered, since they are in delivery process and not delivered yet we can't specify release which will contain the changes

**Comment by hostep** [comment]
Possibly fixed by https://github.com/magento/magento2/commit/18dee3d979ed8ee68a44324e892e6b7f570c987c?

**Comment by chittima** [comment]
@hostep Yes

**Comment by engcom-Bravo** [comment]
Hi,

As per this comment https://github.com/magento/magento2/issues/38917#issuecomment-2348086896 we are closing this issue.

Thanks.

**Comment by YiffyToys** [comment]
No milestone = release set?

**Comment by hostep** [comment]
> Based on the Jira ticket, the target version is 2.4.8-beta1.

**Comment by guilhermemap** [comment]
same issue here on 2.4.7-p2

**Comment by guilhermemap** [comment]
We are still with the same issue in the 2.4.7-p2 version, via the admin page we can only change from the default processing status (processing state) once to a custom state. After this we can't change to another status in the same state, not even the default one. Also, in the complete state we can't change the status at all. 
Our current solution is to use the rest api (POST in the /orders/ endpoint with entity: {entity_id, state, status}, the /orders/<id>/comments endpoint does not work to change the status in this situation).

**Comment by engcom-Delta** [comment]
Hi @guilhermemap ,

Thanks for reporting and collaboration.
We have re-verified the issue in 2.4.7-p3 and 2.4.8-beta1 instance. Issue is only reproducible in 2.4.7 instance and fixed in latest versions.
Can you please reverify in latest 2.4 develop or 2.4.8-beta 1 instance.

Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3178&type=commits

Thanks.

**Comment by vbidou** [comment]
We can witness that the issue is still there in v2.4.7-p3
It applies also to Order STATE "Complete"
Waiting for 2.4.8 release, hoping that it will be fully resolved.
Status updates are a vital component of eCommerce experience.

**Comment by engcom-Delta** [comment]
Hi @vbidou ,

Thanks for reporting and collaboration.
We have re-verified the issue in 2.4.7-p3 and 2.4 develop instance. Issue is only reproducible in 2.4.7 instance and fixed in latest versions.
Can you please reverify in latest 2.4 develop.

https://github.com/user-attachments/assets/fbf8a8f4-43be-48ac-8383-4522dcc6fcde

Thanks.

**Comment by onepack** [comment]
Just as a point of attention. The file Magento\Sales\Model\Service\OrderService.php should also be checked as it prevents adjusting the comment status via the API in Magento 2.4.7.
