### ISSUE TITLE
Integrity constraint violation when filtering sales order grid by date

### ISSUE THREAD

**Issue by cjohnsen1** [magento/magento2#38818]
### Preconditions and environment

Magento 2.4.7. I have reproduced this issue on an upgrade from 2.4.6-p3 as well as a clean install of 2.4.7.

### Steps to reproduce

1. Navigate to storefront admin.
2. Navigate to Sales/Orders.
3. Click "Filters".
4. Select a "From" and "To" purchase date.
5. Click "Apply Filters"

### Expected result

Order grid is updated with a list of orders placed during the time period selected.

### Actual result

Dialog "Attention: Something went wrong." along with a message stating "Something went wrong with processing the default view and we have restored the filter to its original state."

### Additional information

Error Message (Store URL redacted):

Next Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT `main_table`.*, `braintree_transaction_details`.`transaction_source`, `sales_order`.`dispute_status` FROM `sales_order_grid` AS `main_table`
 LEFT JOIN `braintree_transaction_details` ON braintree_transaction_details.order_id = main_table.entity_id
 LEFT JOIN `sales_order` ON sales_order.entity_id = main_table.entity_id WHERE  (((`created_at` >= '2024-06-03 05:00:00'))) AND (((`created_at` <= '2024-06-06 04:59:59'))) ORDER BY main_table.increment_id DESC
 LIMIT 20 in /var/www/vhosts/[storeURL]/httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cjohnsen1** [comment]
@magento give me 2.4-develop instance

**Comment by cjohnsen1** [comment]
@magento give me 2.4-develop instance

**Comment by cjohnsen1** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @cjohnsen1 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev and 2.4.7 instances but the issue is not reproducible.

We can see the filtered orders.

Steps to reproduce:

1. Navigate to storefront admin.
2. Navigate to Sales/Orders.
3. Click "Filters".
4. Select a "From" and "To" purchase date.
5. Click "Apply Filters"

Please refer to the screen-recording and let us know if we missed anything.


https://github.com/magento/magento2/assets/60198592/7d18c869-be0e-4bb1-ae94-87f96be6e548

<img width="1440" alt="38818_2" src="https://github.com/magento/magento2/assets/60198592/4c888426-66da-4e2a-b28f-71256d24ce9b">

**Comment by netzkollektiv** [comment]
We experience this issue in one of our instances too after upgrading to v2.4.7

**Comment by SolsWebdesign** [comment]
It looks like it is any module that adds columns to the sales order and does something with date. In our case it is a GLS module. And in 2.4.4 no problem, as of 2.4.6 this error pops up.

**Comment by EA-SK** [comment]
vendor/paypal/module-braintree-core/Plugin/SalesOrderGridPlugin.php causing error

Braintree using left join on sales_order table. Conflict with sales_order.created_at and sales_order_grid.created_at

```
public function beforeLoad(Collection $subject, bool $printQuery = false, bool $logQuery = false): array
    {
        if (!$subject->isLoaded()) {
            $primaryKey = $subject->getResource()->getIdFieldName();
            $tableName = $subject->getResource()->getTable('braintree_transaction_details');
            $salesOrderTable = $subject->getResource()->getTable('sales_order');

            $subject->getSelect()->joinLeft(
                $tableName,
                $tableName . '.order_id = main_table.' . $primaryKey,
                $tableName . '.transaction_source'
            );
            $subject->getSelect()->joinLeft(
                $salesOrderTable,
                $salesOrderTable . '.entity_id = main_table.' . $primaryKey,
                $salesOrderTable . '.dispute_status'
            );
        }

        return [$printQuery, $logQuery];
    }
```

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @cjohnsen1 

Verified the issue on Magento 2.4.7-p1 and we can reproduce the issue. However, we are not able to reproduce the issue on the 2.4 dev instance.

We can see the filtered orders.

Steps to reproduce:

Navigate to storefront admin.
Navigate to Sales/Orders.
Click "Filters".
Select a "From" and "To" purchase date.
Click "Apply Filters"

Please refer to the screenshots attached. Let us know if we missed anything.

In 2.4.7-p1

<img width="1440" alt="38818_1" src="https://github.com/magento/magento2/assets/60198592/3a59afba-c3de-494e-b448-aeaae02f3054">

<img width="1440" alt="38818-2" src="https://github.com/magento/magento2/assets/60198592/09e9a917-7655-404e-b160-780bdaa7bac6">


In 2.4 dev 

<img width="1440" alt="Screenshot 2024-06-28 at 3 34 16 PM" src="https://github.com/magento/magento2/assets/60198592/865bac61-27b6-4388-9735-5184e8cc1521">

**Comment by engcom-Dash** [comment]
Hi @cjohnsen1 

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank y

**Comment by xpoback** [comment]
@engcom-Dash the issue hasn't been resolved. It's still a problem in 2.4.7-p1. As I understand it's been already fixed in `2.4-dev` so no further steps are to be done. 
My sad experience with things "fixed in 2.x-dev" is that it sometimes can takes years (yes, years) until they actually get released. So a quality patch would be a lot of help.
May we hope for a quality patch being published here: https://github.com/magento/quality-patches ?

**Comment by Bashev** [comment]
@engcom-Dash where this was fixed?

**Comment by Bashev** [comment]
Fixed in https://github.com/magento/magento2/pull/36818

**Comment by mariusboia** [comment]
Solved it by disabling the braintree plugin. Create **etc/adminhtml/di.xml** in your module with this content:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <!-- Disable braintree Sales order grid plugin -->
    <type name="Magento\Sales\Model\ResourceModel\Order\Grid\Collection">
        <plugin name="braintreeSalesOrderGrid" disabled="true"/>
    </type>
</config>
```

**Comment by amjedomar** [comment]
@Bashev any idea if this fix was released? if yes then in which magento version? I'm still experiencing the same issue with version `2.4.7-p2` (even with a fresh magento install)

Yes as @mariusboia said if the `braintreeSalesOrderGrid` plugin is disabled the issue is solved, but I don't wanna disable it

**Comment by Bashev** [comment]
Will be in 2.4.8 (actually, it is merged already in 2.4.8-beta1)

**Comment by rishibankaradicle** [comment]
Did anyone apply the solution present here: https://github.com/magento/magento2/pull/36818/files and confirm if the fix is actually working!

**Comment by rishibankaradicle** [comment]
@Bashev I am unable to reproduce the issue while applying the date filter under sales > invoices. Is the issue only occur when we filter the sales > order?

@Bashev Is there a patch available for the above fix as I am currently on 2.4.7-p5 but the fix is available on 2.4.8?

**Comment by shreyarock123** [comment]
I have created a patch for Magento 2.4.8-p1 because we faced the same issue, and I have resolved it through the patch below.


diff --git a/vendor/paypal/module-braintree-core/Plugin/SalesOrderGridPlugin.php b/vendor/paypal/module-braintree-core/Plugin/SalesOrderGridPlugin.php
index 0a589f3e9f4..0d08e83f273 100648
--- a/vendor/paypal/module-braintree-core/Plugin/SalesOrderGridPlugin.php
+++ b/vendor/paypal/module-braintree-core/Plugin/SalesOrderGridPlugin.php

@@ -53,10 +53,11 @@
                             $condition
                         );
                     }
-                    if (!str_contains($condition, "`created_at`")) {
-                        continue;
+
+                    // Fix created_at column reference
+                    if (str_contains($condition, "`created_at`") && !str_contains($condition, "`main_table`.`created_at`")) {
+                        $wherePart[$key] = str_replace("`created_at`", "`main_table`.`created_at`", $condition);
                     }
-                    $wherePart[$key] = str_replace("`created_at`", "`main_table`.`created_at`", $condition);
                 }
                 $subject->getSelect()->setPart('where', $wherePart);
             }
