### ISSUE TITLE
Magento 2.4.7 Admin Category Page keeps loading forever

### ISSUE THREAD

**Issue by talsan74** [magento/magento2#38828]
### Preconditions and environment

- PHP 8.3
- Magento 2.4.7

### Steps to reproduce

1. Install default magento 2.4.7
2. Inserted and deleted categories through rest api
3. login to admin, goto catalog > category

### Expected result

Category Page has to be loaded

### Actual result

Category page keeps loading, refreshing the screen or tried with different user or else reindex steps nothing fix the problem. 

![image](https://github.com/magento/magento2/assets/122008280/b9d428a5-1984-4673-87d6-4968577a3508)

we can see some error on Developer Tools > console
![image](https://github.com/magento/magento2/assets/122008280/4b900cb9-dbe2-4cd5-ae13-53bded0d93d8)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @talsan74 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 instance and the issue is not reproducable.

Steps to reproduce :

1. Install default magento 2.4.7
2. Inserted and deleted categories through rest API
3. login to admin, goto catalog > category
4. 

Please refer the attached screenshots. Let us know if we missed anything.

<img width="1440" alt="38828_1" src="https://github.com/magento/magento2/assets/60198592/0037bb80-a32f-4aef-bd27-5d579da7993d">

<img width="1440" alt="38828_2" src="https://github.com/magento/magento2/assets/60198592/c77f1f5a-839f-4fa3-b1e0-6ee881ba3153">
<img width="1440" alt="38828_3" src="https://github.com/magento/magento2/assets/60198592/1a38bfc3-d293-4ed0-92ed-913e98d124a7">

**Comment by engcom-Dash** [comment]
Hi @talsan74 

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.

**Comment by matiasgaletto** [comment]
Okay, as far as I have tested, the issue is caused by having the name of a category with a trailing empty space. Instead of "Category Name" it has to be "Category Name ".
I haven't been able to reproduce the issue in version 2.4.6-p4 but I was able to do it in 2.4.7 and 2.4.7-p1. So anyone who updates to any of these versions will have this error, which cannot be fixed by a common user. It can only be fixed by making a SQL query to the database.
If you check the Dev Tools Console and go to where the parsing error happens you can verify the issue.

Steps to reproduce:

1. Install Magento 2.4.7 or 2.4.7-p1
2. Add a category with a trailing space in the name. "Category Name "
3. Go to Admin Panel > Catalog > Category
4. Should stay loading forever.
5. Check Chrome Dev Tools Console, you should see an error message.
6. Click on the error and see in the file that the parsing error happens where the category name has a trailing space.

**Comment by matiasgaletto** [comment]
@engcom-Dash could you reopen this? A lot of people are going to have issues if not fixed soon.

**Comment by xpoback** [comment]
@engcom-Dash Please consider extending your testcase and reopen this issue.
I can confirm it is reproducible as mentioned by @matiasgaletto. 
An additional test case is when the category name has a carriage return symbol in it (`\r`). Yes, I know that it isn't supposed to be in a category name but neither should the whole page be broken because of a wrong character in the category name.
Many customer will be affected by this, especially those who get their data imported from a PIM and not added by hand in the admin area.

**Comment by JohnnnyG** [comment]
@engcom-Dash : I also think this needs to be reopened.

I have struggled with this issue  for over a month now and by following the above information I was able to run  the following query in phpmyadmin to find the problem category names

`SELECT *  FROM `catalog_category_entity_varchar` WHERE `value` LIKE '%\r\n';`

Once I edited these to remove any new lines or white spaces on the end of the string the category list populated on the admin part of Magento straight away.

**Comment by engcom-Dash** [comment]
Hi @talsan74 

Thanks for reporting and collaboration.

Verified the issue on the Magento 2.4 dev instance and the issue is reproducible. Hence, we are confirming the issue.

Steps to reproduce:

1. Install Magento 2.4.7 or 2.4.7-p1
2. Add a category with a trailing space in the name. "Category Name "
3. Go to Admin Panel > Catalog > Category
4. Should stay loading forever.
5. Check Chrome Dev Tools Console, you should see an error message.
6. Click on the error and see in the file that the parsing error happens where the category name has a trailing space.

The admin category page keeps loading forever.

Please refer the attached screenshots.

Creating category when category name has a carriage return symbol in it (\r)


<img width="1440" alt="Screenshot 2024-07-17 at 6 23 24 PM" src="https://github.com/user-attachments/assets/7b68175b-37b4-44fc-a5f2-eee041ff29fc">

<img width="1440" alt="Screenshot 2024-07-17 at 6 23 20 PM" src="https://github.com/user-attachments/assets/63b6f9b3-91d9-4795-a124-2702c09ef7af">

Try to open the category in admin panel

<img width="1440" alt="Screenshot 2024-07-17 at 6 22 57 PM" src="https://github.com/user-attachments/assets/7e2e881f-6fd7-4708-92a2-3791faee20be">


Error in chrome dev tools console

<img width="1440" alt="Screenshot 2024-07-17 at 6 23 12 PM" src="https://github.com/user-attachments/assets/5126ac5b-a873-410c-984f-5239be093f9b">

**Comment by marctbb** [comment]
Hi all, is there a workaround I can apply while the bug is being officially resolved?

Thanks

**Comment by lucafuser** [comment]
@magento give me 2.4-develop instance

**Comment by lucafuser** [comment]
Hi @engcom-Dash i verified the issue on my local Magento 2.4-develop instance and i'm not able to reproduce the issue, could you please verify?

Steps to reproduce (rif. https://github.com/magento/magento2/issues/38828#issuecomment-2233271664):

- Install Magento 2.4-develop
- Add a category via Rest API with a \r and trailing space in the name. "test \rcat 1 "
- Go to Admin Panel > Catalog > Category
- Should stay loading forever.
- Check Chrome Dev Tools Console, you should see an error message.
- Click on the error and see in the file that the parsing error happens where the category name has a trailing space.

**Comment by engcom-Delta** [comment]
Hi @talsan74 ,

Thanks for your reporting and collaboration.
We have re-verified the issue in Latest 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Inserted and deleted categories through rest api
![image](https://github.com/user-attachments/assets/951f5e43-1015-4c2f-8ea2-8993b69d380c)
![image](https://github.com/user-attachments/assets/7cc53a59-15a5-4be0-a023-fdc1f042988e)
2. login to admin, goto catalog > category
3. Observe, page is loading as expected
![image](https://github.com/user-attachments/assets/7bef9e2d-1725-43a9-99f9-e573b7eb9283)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment]
Hi @talsan74 ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
