### ISSUE TITLE
Custom customer attributes not saved

### ISSUE THREAD

**Issue by luciodiri** [magento/magento2#3943]
## Steps to reproduce
1. Download Magento EE 2.0.2
2. Go to admin->Stores->Attributes:Customer and click "Add New Attribute
3. Add custom Customer attribute
4. Go to customer edit form and add value in new Custom field.
5. save 
## Expected result
1. Custom attribute value is saved in database.
2. Custom attribute value is displayed in customer edit form.
## Actual result
1. Value not saved.
2. Value not displayed in customer details (originated in 1).
3. No error/log reported.

Alternatively, tried to add the same functionality in CE when installing module:
[IInstallData.php.txt](https://github.com/magento/magento2/files/197560/IInstallData.php.txt)
Same behavior, form field is added to customer edit form, but value is not saved in DB.

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-51416

**Comment by quienti** [comment]
Same problem with Magento 2.0.4

**Comment by dnadle** [comment]
I found that the save was throwing an exception because one of my custom attributes was set to input type 'checkbox'. When I changed it to 'text' the save was successful. Details here:

https://community.magento.com/t5/Technical-Issues/Customer-custom-attribute-with-checkbox-input-throws-exception/m-p/34737

**Comment by luciodiri** [comment]
Hi @sevos1984 
Any estimate on that?

**Comment by sevos1984** [comment]
Issue is already resolved in MAGETWO-51413, check latest develop code

**Comment by cykirsch** [comment]
@sevos1984 Did this fix ever make it into 2.1? I'm on 2.1.6 at the moment, and still experiencing this issue. I could maybe pull the fix from develop if I knew what it was, but it's more likely we'll jump to 2.2 when it gets past the RC stage. Just trying to figure out if the problem I'm seeing is a known issue for the version I'm using.

**Comment by orlangur** [comment]
@cykirsch among two mentioned tickets there are no commits related to `MAGETWO-51416` and few related to `MAGETWO-51413`: https://github.com/magento/magento2/search?q=MAGETWO-51413&type=Commits&utf8=✓

Those commits are released starting from 2.1.0, so, it would be not redundant to check if issue is reproducible in `2.2.0-preview`.
