### ISSUE TITLE
Integration Identity link URL not working

### ISSUE THREAD

**Issue by jpreed2** [magento/magento2#3999]
## Steps to reproduce
1. Using latest Magento 2.0.4.
2. In Magento Admin: System > Extensions > Integrations click Add New Integration.
3. Enter an integration name, email address, callback url and identity link url.
4. Click API tab on the left and choose Resource Access All.
5. Click Save.
6. The new integration displays in the list of integrations.  Click the "Authorize" link for the new integration.
7. Verify API authorizations and click the Authorize button.
## Expected result
1. The user should see an iFrame containing or be redirected to the Indentity Link URL to enter their credentials on the integration site.
## Actual result
1. The following message is displayed: "Please setup or sign in into your 3rd party account to complete setup of this integration." with an Ok link.

**Comment by choukalos** [comment]
Noted this could be related to internal issue - MAGETWO-50878 .

**Comment by cspruiell** [comment]
Yes, this was fixed by MAGETWO-50878 and pushed to the develop branch.

**Comment by jpreed2** [comment]
I just installed the latest develop branch and tested this functionality.  It's still not working.  It never opens an iFrame of my identity link url and my access logs show that URL is never hit.  I've verified I have the latest develop branch because I now see a "Current User Identity Verification" field which wasn't there before.

Does the callback have to return something in order for the identity link url to be displayed?

**Comment by paliarush** [comment]
@jim5359 Please make sure you have popup windows allowed in your browser, they are usually blocked by default.

**Comment by jpreed2** [comment]
Ok, I disabled popup blocker and I got the popup.  As you stated, popups are usually blocked by default.  So shouldn't there be instructions that tell the user to disable their popup blocker before continuing?  Also, popups are not blocked if they are a direct result of user input.  So perhaps after calling the callback you could provide a link for the user to authenticate on their 3rd party system.  This would avoid the popup blocker.

**Comment by paliarush** [comment]
@jim5359 Thank you for the feedback, we will definitely improve the flow to eliminate described issue.

**Comment by smaeder** [comment]
@paliarush - do you know how soon you may be able to implement this improved flow so that your  OAuth process works with popup blockers?
