### ISSUE TITLE
Cart shipping methods not updating when address changed

### ISSUE THREAD

**Issue by jpreed2** [magento/magento2#4059]
### Preconditions
Magento `develop` branch

## Steps to reproduce
1. Install Magento from `develop` branch.
2. Enable UPS shipping method via admin.
3. Add an item to your cart from the store front end.
4. Go to checkout.
5. Shipping methods show "Sorry, no quotes are available for this order at this time"
6. Enter an address.
## Expected result
1. The shipping methods should update and list rates for UPS.
## Actual result
1. Shipping methods still shows "Sorry, no quotes are available for this order at this time"
2. This was working in 2.0.4, but seems to have broken in the develop branch.

**Comment by jpreed2** [comment]
Note, a related issue on the current 2.0.4 release:  I installed my module that provides custom shipping methods and rates.  As long as I have one of the built in Magento shipping methods enabled (such as flat rate) then the Ajax calls work fine.  Changing the zip code triggers the Ajax call to to update the shipping methods and rates, as expected.  But if I have all the built in Magento shipping methods disabled then the Ajax calls stop working completely.

As noted above, in the develop branch the Ajax calls don't work even with built-in shipping methods enabled.

**Comment by wclansar** [comment]
I Also Having same issue when i change country in section "Estimate Shipping and Tax" .

Ajax is not working

Thanks

**Comment by alena-marchenko** [comment]
Hi @jim5359 

We have MAGETWO-50504 ticket created regarding this issue already

Thank you

**Comment by birchestx** [comment]
Timeline on getting a fix into a release?  Causing issues for many SIs trying to push Magento2 live. It's pretty fundamental that it does an ajax callback when the address changes.

**Comment by pboisvert** [comment]
bug shows as fixed in mainline. Trying to see if this will go with the next patch.

**Comment by ishakhsuvarov** [comment]
@jim5359 Closing this issue as the fix had been delivered to the `develop` branch with the commit [`cca6a48`](https://github.com/magento/magento2/commit/cca6a48).
Please feel free to reopen if the issue persists.

**Comment by jpreed2** [comment]
I just tested the latest develop branch and this is still not fixed.  It's fixed specifically for the built in methods, like UPS.  But for custom shipping methods (added via extension) it is still not triggering the update.

**Comment by Khaleel** [comment]
Also having the same issue..

**Comment by piotrekkaminski** [comment]
cc @elenleonova  @antboiko I reopened this issue as it seems it was not fully fixed (not fixed for custom shipping methods)

**Comment by ishakhsuvarov** [comment]
@jim5359 @Khaleel 
Please check if your custom shipping module follows this doc: http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_carrier.html
If carrier module does not provide the list of required fields – rates may not update.

**Comment by domeglic** [comment]
@ishakhsuvarov I had the same problem and this solves it, however there is a case where the shipping methods are not updated.
In my case the carrier is dependent on postcode but if you enter a postcode that is not considered valid it will trigger the "_Provided Zip/Postal Code seems to be invalid. Example: 12345. If you believe it is the right one you can ignore this notice._" warning and the shipping methods are then not updated.

**Comment by ishakhsuvarov** [comment]
@domeglic Thanks for reporting, we will look into it and update you with the result.

**Comment by mattf10** [comment]
Anyone facing this issue - there is a workaround:  https://github.com/magento/magento2/issues/5490
In brief, shipping methods don't update when using one custom shipping method.  If you add in a built in Magento method (eg Free Shipping for orders over a very large amount), then shipping methods update when address fields change.

**Comment by magento-engcom-team** [comment]
@jim5359, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by p06pratibha** [comment]
my magento ver. is 2.1.8, still same issue coming, please review this once.

**Comment by emmathepossum** [comment]
can confirm this for magento 2.2.6 

custom shipping methods are only updated when there is at least one magento default shipping method enabled

adding a validator as described [here](https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_carrier.html) does not help

**Comment by johnorourke** [comment]
For anyone finding this having trouble with a custom shipping method, it could be the wrong carrier code in checkout_index_index.xml. This sounds like the issue @mattf10 and @dwirt had above:

From the Magento doc: "You must add <your-validation-name> like %carrier%-rates-validation - where carrier has to match the actual carrier code."

eg. we discovered the DHL Express Rates module has the carrier code 'dhlexpress', but in the XML, it had:

```
<item name="shipping-rates-validation" xsi:type="array">
    <item name="children" xsi:type="array">
        <item name="**dhl-express**-rates-validation" xsi:type="array">
            <item name="component" xsi:type="string">Dhl_ExpressRates/js/view/register-shipping-rates-validator</item>
        </item>
    </item>
</item>  
```

This validator was being removed, because the code 'dhl-express' was not the same as the carrier code 'dhlexpress'.  This happens in module-checkout/Block/Checkout/LayoutProcessor.php - it retrives a list of active carriers (where the config path carrier/<code>/active is set) and removes any validators whose code is not listed.

Hope this helps someone else... v1.0.3 of DHL Express is affected, I will submit a patch.

**Comment by VuThuan** [comment]
> For anyone finding this having trouble with a custom shipping method, it could be the wrong carrier code in checkout_index_index.xml. This sounds like the issue @mattf10 and @dwirt had above:
> 
> From the Magento doc: "You must add like %carrier%-rates-validation - where carrier has to match the actual carrier code."
> 
> eg. we discovered the DHL Express Rates module has the carrier code 'dhlexpress', but in the XML, it had:
> 
> ```
> <item name="shipping-rates-validation" xsi:type="array">
>     <item name="children" xsi:type="array">
>         <item name="**dhl-express**-rates-validation" xsi:type="array">
>             <item name="component" xsi:type="string">Dhl_ExpressRates/js/view/register-shipping-rates-validator</item>
>         </item>
>     </item>
> </item>  
> ```
> 
> This validator was being removed, because the code 'dhl-express' was not the same as the carrier code 'dhlexpress'. This happens in module-checkout/Block/Checkout/LayoutProcessor.php - it retrives a list of active carriers (where the config path carrier/`/active is set) and removes any validators whose code is not listed.`
> 
> ` Hope this helps someone else... v1.0.3 of DHL Express is affected, I will submit a patch.`

Thank you for your information. I resolved my issue
