### ISSUE TITLE
Catalog search indexer process unknown error

### ISSUE THREAD

**Issue by colyield** [magento/magento2#4107]
I have a website in production and tried to copy all the content to a local centos server for testing purpose.

The first time to reindex using command line on the testing server, there is an error occurred " Catalog search indexer process unknown error, Error while sending query packet, PID=44972". And "Catalog Search" index always shows "processing".

Tried to change the     value of catalogsearch_fulltext in database to invalid, but when reindex again, the error will be there again.

The testing server is centos 7, php7.0 (also tried php5.6), the magento version is 2.0.4.

The interesting thing is, the original website is working well. It has centos 6, php5.6, Tried a few days to figure out what problem is, but still no clue. Please advise. Thanks.

**Comment by mazhalai** [comment]
@colyield what version of Magento? There were some issues with PHP 7 regarding indexers, which were addressed in https://github.com/magento/magento2/tree/2.0.1 related thread https://github.com/magento/magento2/issues/2750

**Comment by colyield** [comment]
@mazhalai As I mentioned, the magento version is 2.0.4. It was upgraded from 2.0.0. And I tried the php5.6 and php7, same issue. Is there a way to fix this?

**Comment by colyield** [comment]
@mazhalai Today I tried centos 6, apache 2.2, php5.6. mysql 5.6, the problem is still the same. Please help.

Do you think it is because the magento was updated from 2.0? But I tried new system files with the current database, got the same situation.

**Comment by colyield** [comment]
I figured out what the problem is. First, I found one of the file has readiness permission problem according to the file .setup_cronjob_status, so the cron job does not work well. After fix that, it shows "2006 MySQL server has gone away" when reindexing. Changed the max_allowed_packet for mysql to 64M, the problem is gone.
