### ISSUE TITLE
UTF-8 special character issue in widgets

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#4232]
## Steps to reproduce
1. Install Magento 2.0.4
2. Add CMS Page Link or other widget type which accepts input parameters
3. Enter Latvian UTF-8 special characters `glāžšķūņu rūķīši` in input parameter
4. See [video](http://screencast.com/t/TNzgeDti2) for details
## Expected result
1. Widget is added correctly with UTF-8 characters
## Actual result
1. Widget is added but UTF-8 special characters are broken
2. [Error](http://screencast.com/t/PmJW27gv) is show when hiding editor, fixing characters manually and showing editor again

**Comment by kristaps-aksjonovs** [comment]
Same issue. Maby any ideas about quickfix ?

**Comment by kristaps-aksjonovs** [comment]
@werdlv One way is to add widget using Insert widget not wysiwyg, error pop will show up, but on frontend content will be ok.

**Comment by shiftedreality** [comment]
Hi @werdlv 

Thank you for reporting. Looks like an issue with TinyMCE. I created internal ticket MAGETWO-52850 to investigate and fix.

**Comment by piotrekkaminski** [comment]
We are nearly done fixing this issue and should be merged soon.

**Comment by jsakars** [comment]
@piotrekkaminski FYI - still present in 2.1.0

**Comment by pantaoran** [comment]
Looks like my report in #5708 duplicates this older issue more or less. I didn't find this one when I searched...

**Comment by tkacheva** [comment]
@pantaoran Issue is fixed in https://github.com/magento/magento2/commit/54df23a2cddd92d6961dfda3b80e480c6d7c822e. I checked it's not reproachable any more. 
![coding](https://cloud.githubusercontent.com/assets/5603216/17170065/26812f36-53f3-11e6-9aeb-7fdfffa463af.png)

Let me know if it works for you

**Comment by janepoltoratskaya** [comment]
is there any update on this issue?

**Comment by DevXeni** [comment]
Just now I've got the same error. Bug is not fixed (magento 2.1, installed  - July 2016). I think it's TinyMCE configuration. Maybe, need to set "entity_encoding" to "raw" and it will not convert our utf8 characters to a  "named entity"...

**Comment by enrico69** [comment]
Idem. Still present in Magento EE 2.1 (installed in july 2016).

**Comment by ziiljuks** [comment]
Still present in Magento CE 2.1.1

**Comment by tkacheva** [comment]
Issue is fixed in mainline (not 2.1.x)
https://github.com/magento/magento2/commit/54df23a

**Comment by irenelagno** [comment]
This issue will be delivered to 2.1.x in the scope of MAGETWO-57051

**Comment by mhauri** [comment]
Would be great to get this released as soon as possible.

**Comment by mhauri** [comment]
@piotrekkaminski Still present in 2.1.3, why wasn't this merged from develop into 2.1.3?

**Comment by mhauri** [comment]
Still present in 2.1.4

**Comment by maksek** [comment]
The fix scheduled for 2.1.9

**Comment by mhauri** [comment]
@maksek why so late, 2.1.5 will be a copyright update version only, but why not in 2.1.6?
What's the planned release cycle, based on the latest releases it's around 2 months between each release, so 2.1.9 will be 8 to 10 months away.

**Comment by maksek** [comment]
@mhauri 2.1.9 will be sooner. We will share our patch release roadmap soon. 2.1.6 will be security update, 2.1.7 will be fixes. But if the issue will have more votes, it may be sooner than 2.1.9. Use upvoting.

**Comment by koenner01** [comment]
Relates to https://github.com/magento/magento2/issues/7249.
Commit where this has been fixed is referenced there too in case you want to patch this in your project

**Comment by pantaoran** [comment]
@maksek Is that promised patch release roadmap out yet? I would be very interested to see it.

**Comment by veloraven** [comment]
Internal ticket for ver. 2.0 - MAGETWO-57816, for ver. 2.1 - MAGETWO-57051
It has been already fixed and will be available in one of nearest releases.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-67621
