### ISSUE TITLE
multiselect product attribute bugs in mass action, grid and grid filter

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#4312]
## Steps to reproduce
1. Install Magento 2.0.4
2. Create a product attribute with frontend input "multiselect" (and assign it to the necessary attribute sets).
## Expected result
1. You can set values via mass action.
2. All selected values are shown in the corresponding grid column.
3. You can use the filter in the grid to search for products with the selected options.
## Actual result
1. If you want to use it via mass action from the grid, it does not set the selected values on the product(s).
2. Values are not shown in the corresponding grid column if more than one option is selected for a product. If a product only has one option selected, then it will be shown in the grid.
3. If you want to filter for the values, instead of a multiselect box, you will see a dropdown menu. If you choose option "A", but a product has option "A" and "B" selected, then the product will not be shown in the search results

**Comment by piotrekkaminski** [comment]
Internal ticket MAGETWO-52775

**Comment by KrystynaKabannyk** [comment]
Hello @bh-ref, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by bh-ref** [comment]
Thank you for fixing the problems 2) and 3).

I think, problem 1) still exists: I cannot use mass update with multiselect attributes.

**Comment by afavata** [comment]
I do confirm... 2.1.0 has not resolved the issue. Mass action from product grid does not update multiselect attribute

Please reopen this ticket

**Comment by bh-ref** [comment]
@KrystynaKabannyk could you please reopen the issue? It seems that I am not able to do it.

**Comment by afavata** [comment]
Normally only who closed the issue can reopen. @KrystynaKabannyk is up to you.

**Comment by bh-ref** [comment]
@KrystynaKabannyk @afavata I created a new ticket https://github.com/magento/magento2/issues/5459, so you can keep this ticket closed.
