### ISSUE TITLE
Credit memo error 

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4349]
## Steps to reproduce
1. We use magento with table rate shipping prices including tax
2. Tax Settings:
   ![2016-04-29_16h24_00](https://cloud.githubusercontent.com/assets/13572447/14919115/883462b4-0e27-11e6-933a-a268bbc2a787.png)
3. Tabel rates:
   ![2016-04-29_16h28_20](https://cloud.githubusercontent.com/assets/13572447/14919189/ef1b9dd0-0e27-11e6-86d8-8e94d6de06bc.png)

When creating a credit memo for an order we get the following "error" message: "Maximum shipping amount allowed to refund = €4.13"
![2016-04-29_16h35_13](https://cloud.githubusercontent.com/assets/13572447/14919379/d856e090-0e28-11e6-9531-1e74af161c3d.png)

This is the shipping amount EXCLUDING TAX
While when entering the information to refund the field for refund shipping cleary shows including tax:
![2016-04-29_16h37_58](https://cloud.githubusercontent.com/assets/13572447/14919472/4d346d1a-0e29-11e6-862f-6e9b03824970.png)

So when clicking "Refund Offline"
You always get this "Maximum shipping amount allowed to refund = ...." message.....

This seems not correct ....
## Expected result
1. You should be able to click Refund without getting any error message static you can only refund a excluding tax amount when you have cleary set your shipping amount settings in the backend to tax including
## Actual result
1. "Maximum shipping amount allowed to refund = ...."  
   Where .... = shipping amount excl tax

**Comment by piotrekkaminski** [comment]
internal ticket MAGETWO-52773

**Comment by alena-marchenko** [comment]
Hi @SidneyBilliet 

Could you specify Magento version that you are using? Also, are you able to reproduce this issue on the develop branch?

**Comment by SidneyBilliet** [comment]
@alena-marchenko 
We are using v2.0.5.
I have not tried to reproduce it on the develop branch.
I don't know how to....

**Comment by alena-marchenko** [comment]
Hi @SidneyBilliet 

This bug is already resolved in develop branch. Closing the issue, please feel free to reopen it if you still can reproduce it on develop branch.

**Comment by SidneyBilliet** [comment]
@alena-marchenko 

Alena, I do not know how to test this on develop branch. However I have tested in in the 2.0.7 version and the problem still exists. How do I know If this fix was added to the 2.0.7 version?

**Comment by SidneyBilliet** [comment]
@piotrekkaminski 
This is still an issue in 2.0.7
![2016-06-29_11h42_58](https://cloud.githubusercontent.com/assets/13572447/16447965/526b212a-3def-11e6-88e9-f060caeffcd6.png)
