### ISSUE TITLE
Git Ignore Rules Vanished from Project Meta-Package

### ISSUE THREAD

**Issue by davidalger** [magento/magento2#4358]
Composer package `magento/project-community-edition@2.0.5` is missing the `.gitignore` file which is crucial to setting up a project without committing _everything_ to the repository:

``` shell
dalger:01:31 PM:/server/proj/test$ composer create-project --repository-url https://repo.magento.com/ magento/project-community-edition m2 2.0.4 --no-install
Installing magento/project-community-edition (2.0.4)
  - Installing magento/project-community-edition (2.0.4)
    Downloading: 100%         

Created project in m2
dalger:01:32 PM:/server/proj/test$ ls -lha m2
total 32
drwxr-xr-x  3 dalger  admin   204B Apr 30 13:32 .
drwxr-xr-x  6 dalger  admin   340B Apr 30 13:32 ..
-rw-r--r--  1 dalger  admin   1.0K Mar 31 22:10 .gitignore
-rw-r--r--  1 dalger  admin   4.3K Mar 31 22:10 README.md
-rw-r--r--  1 dalger  admin   1.8K Mar 31 22:10 composer.json
drwxr-xr-x  7 dalger  admin   476B Apr 30 13:32 update
dalger:01:32 PM:/server/proj/test$ composer create-project --repository-url https://repo.magento.com/ magento/project-community-edition m2-205 2.0.5 --no-install
Installing magento/project-community-edition (2.0.5)
  - Installing magento/project-community-edition (2.0.5)
    Loading from cache

Created project in m2-205
dalger:01:32 PM:/server/proj/test$ ls -lha m2-205
total 8
drwxr-xr-x  3 dalger  admin   136B Apr 30 13:32 .
drwxr-xr-x  7 dalger  admin   374B Apr 30 13:32 ..
-rw-r--r--  1 dalger  admin   1.8K Apr 28 02:15 composer.json
drwxr-xr-x  7 dalger  admin   476B Apr 30 13:32 update
dalger:01:33 PM:/server/proj/test$ 
```

Why has this file gone missing? Can we please bring it back?

**Comment by piotrekkaminski** [comment]
@davidalger escalated

**Comment by alankent** [comment]
The .gitignore file is created during the "install" phase. It copies lots of files out of the base package into the root directory. So the --no-install is why the .gitignore file does not exist in this case.

Note: I think we copy too many things out of the base package into the root directory at present - e.g. some of the COPYING.txt, LICENSE, README files etc really are Magento files, not customer project files.

The reason we copy files out of the base package is because then they will be patched. If we patch the base package, we will copy the patched versions of those files into the project. (Long term plan is to minimize/eleminate this - but it is what happens today.)

So how best to decide what to put into the default project and what in base? Anything we should patch should go in base so we can copy it up to the root directory every patch. Anything that we provide an initial version of and not patch should go in the project. I think the .gitignore file makes sense moving into the project on this basis - we give a good starting point, but after that the project owns the file. It will be customized. index.php might be similar...

**Comment by davidalger** [comment]
@alankent The response / effort you made in replying is appreciated, but I'm wondering if you tried reproducing the stated issue :)

The purpose of my using --no-install was to de-clutter the bug report. In 2.0.4 and prior, the .gitignore file (as indicated by the first series of above commands) was in fact brought in via the create-project prior to the install phase, not copied in from base. In 2.0.5 this changed, and post-install there is no .gitignore file present.

If you'll inspect the following command sequence, you'll find the .gitignore file is not there post-install:

``` shell
dalger:09:23 PM:/server$ composer create-project -q --repository-url https://repo.magento.com/ magento/project-community-edition m205 2.0.5
dalger:09:24 PM:/server$ ls -lh m205/.gitignore
ls: m205/.gitignore: No such file or directory
dalger:09:26 PM:/server$ ls -lha m205
total 1680
drwxr-xr-x  12 dalger  admin   986B May 12 21:24 .
drwxrwxr-x  31 dalger  admin   1.4K May 12 21:24 ..
-rw-r--r--   1 dalger  admin   7.4K May 12 21:24 .htaccess
-rw-r--r--   1 dalger  admin   6.3K May 12 21:24 .htaccess.sample
-rw-r--r--   1 dalger  admin   1.6K May 12 21:24 .php_cs
-rw-r--r--   1 dalger  admin   3.6K May 12 21:24 .travis.yml
-rw-r--r--   1 dalger  admin   429K May 12 21:24 CHANGELOG.md
-rw-r--r--   1 dalger  admin   3.3K May 12 21:24 CONTRIBUTING.md
-rw-r--r--   1 dalger  admin   9.8K May 12 21:24 CONTRIBUTOR_LICENSE_AGREEMENT.html
-rw-r--r--   1 dalger  admin   631B May 12 21:24 COPYING.txt
-rw-r--r--   1 dalger  admin   2.9K May 12 21:24 Gruntfile.js
-rw-r--r--   1 dalger  admin    10K May 12 21:24 LICENSE.txt
-rw-r--r--   1 dalger  admin    10K May 12 21:24 LICENSE_AFL.txt
drwxr-xr-x   4 dalger  admin   272B May 12 21:24 app
drwxr-xr-x   2 dalger  admin   136B May 12 21:24 bin
-rw-r--r--   1 dalger  admin   1.8K Apr 28 02:15 composer.json
-rw-r--r--   1 dalger  admin   310K May 12 21:24 composer.lock
drwxr-xr-x   4 dalger  admin   170B May 12 21:24 dev
-rw-r--r--   1 dalger  admin   1.3K May 12 21:24 index.php
drwxr-xr-x   4 dalger  admin   170B May 12 21:24 lib
-rw-r--r--   1 dalger  admin   4.0K May 12 21:24 nginx.conf.sample
-rw-r--r--   1 dalger  admin   1.4K May 12 21:24 package.json
-rw-r--r--   1 dalger  admin   804B May 12 21:24 php.ini.sample
drwxr-xr-x   2 dalger  admin   170B May 12 21:24 phpserver
drwxr-xr-x   6 dalger  admin   374B May 12 21:24 pub
drwxr-xr-x   7 dalger  admin   306B May 12 21:24 setup
drwxr-xr-x   7 dalger  admin   476B May 12 21:24 update
drwxr-xr-x   2 dalger  admin   102B May 12 21:24 var
drwxr-xr-x  27 dalger  admin   986B May 12 21:24 vendor
dalger:09:26 PM:/server$ 
```

**Comment by erikhansen** [comment]
+1 for this issue, as many people installing Magento 2 via `composer create-project` won't know what files to add to their `.gitignore` file and will end up committing the `vendor` directory along with many other directories/files that ought to be ignored.

@alankent In your https://alankent.me/2016/03/31/m2-project-source-code-management-recommendation/ blog post you make some great points about the importance of a `.gitignore` file:

> When you create a new project, Magento creates a ‘.gitignore’ file. We may tune this file over time, but it is set up based on what we recommend committing to a project source code directory. For example, it ignores the ‘vendor’ directory. Local customizations specific to that project go under ‘app/code’ (modules) and ‘app/design’ (themes); code downloaded via Composer (and hence not “owned” by that project) do not belong with the rest of the project source code.
> 
> Put more simply, source code should be managed in source code management system which represents the “source of truth” of that code. Committing the ‘vendor’ directory is “wrong” because the source of truth is not the current project.

I just installed Magento 2.0.7 CE using the "composer create-project" approach and can confirm that the `.gitignore` file is not being created. I hope this will be rectified quickly.

**Comment by KrystynaKabannyk** [comment]
Hello @davidalger, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by davidalger** [comment]
@KrystynaKabannyk Unfortunately this is not resolved (at least not from my perspective...). There is a .gitignore included now, yes, but it is different than it was before and not appropriate for use in setting up a project.

The .gitignore which create-project outputs should create should be one ready to manage the source code of a version controlled project with all dependencies managed by composer. The .gitignore file which is now there in 2.1, however, is geared for development on the main magento/magento2 repository.

The 2.0.x releases which had a .gitignore added by composer create-project shipped with this file: https://github.com/magento/magento2-community-edition/blob/master/.gitignore

The 2.1 release includes a very different file, found here: https://github.com/magento/magento2/blob/2.1/.gitignore

The definition of done here isn't "a .gitignore file is there after create-project is run" but rather "a working .gitignore for managing a project based on Magento2 is there after create-project is run". Please consider how this should be managed internally. I'm looking forward to seeing a new file shipped in the next 2.1 patch release if at all possible! :)

**Comment by magento-engcom-team** [comment]
@davidalger thank you for your report.
The fix for this issue is already fixed in 2.2.0 release
