### ISSUE TITLE
Disable debug output to debug.log

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#4362]
Can't figure out how to disable debug output to debug.log for things like cache invalidation, etc. In production mode this information is not necessary to log.

`[2016-05-01 02:17:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://endohaus.com/checkout/cart/","invalidateInfo":{"tags":["rewards_purchase"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:17:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://endohaus.com/checkout/cart/","invalidateInfo":{"tags":["rewards_purchase_55","rewards_purchase"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:17:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://endohaus.com/checkout/cart/","invalidateInfo":{"tags":["rewards_purchase_55","rewards_purchase"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:17:21] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://endohaus.com/checkout/cart/","invalidateInfo":{"tags":["rewards_purchase"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:17:21] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://endohaus.com/checkout/cart/","invalidateInfo":{"tags":["rewards_purchase_55","rewards_purchase"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:17:21] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://endohaus.com/checkout/cart/","invalidateInfo":{"tags":["rewards_purchase_55","rewards_purchase"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway_1","helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway_1","helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway_2","helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway_2","helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway_3","helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-01 02:18:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["helpdesk_gateway_3","helpdesk_gateway"],"mode":"matchingAnyTag"},"is_exception":false} []`

Same thing is with system.log
Anyone has an idea?

**Comment by adragus-inviqa** [comment]
https://github.com/magento/magento2/blob/958164768b3eea3dcba7427bc82fdd15b836b031/app/etc/di.xml#L257

I think I'll PR a debug switch for that. Logs gets too cluttered.

**Comment by devdesco-ceo** [comment]
Yes, there should be an interface or option to set logging verbosity level directly in app/etc/env.php

**Comment by piotrekkaminski** [comment]
@adragus-inviqa that would be very helpful

**Comment by piotrekkaminski** [comment]
Internal ticket MAGETWO-52767

**Comment by atIOCrON** [comment]
I'm also interested in this

**Comment by werdlv** [comment]
I wonder how such a mainline functionality has been missed. After all - M2 is using Monolog by default.

**Comment by adragus-inviqa** [comment]
Sorry, peeps. Not much time to do this. Consider it "up for grabs".

**Comment by andimov** [comment]
This issue has been fixed and delivered to mainline.

**Comment by nikonratm** [comment]
DId this ever actually make it into the core? Still having this issue on 2.1.3, dont see where to change it.

**Comment by erikhansen** [comment]
I'm also interested to hear how to configure a production instance of M2 to _not_ log the `cache_invalidate` strings to `var/log/debug.log`

**Comment by nikonratm** [comment]
@okorshenko @andimov Any idea why this never actually made it to the core?

**Comment by LucScu** [comment]
So, how to decrease log verbosity level to debug.log in production mode?

**Comment by orlangur** [comment]
@nikonratm @erikhansen @LucScu looking at commits in this issue it seems that  `dev/debug/debug_logging` configuration option is responsible for this in `dev` mode. However, it looks like the fix is only present in `develop` branch currently.

As a workaround I believe it would not hurt simply symlink `var/log/debug.log` to `/dev/null`: http://serverfault.com/a/779437

**Comment by LucScu** [comment]
@orlangur Great, i'll see if it is fixed in last release.

**Comment by SAN1TAR1UM** [comment]
I don't see anything in EE 2.1.7 can we get some more info on where this setting is in the Admin Panel?

**Comment by sunilit42** [comment]
<preference for="Magento\Framework\Logger\Handler\Debug" type="Magento\Developer\Model\Logger\Handler\Debug"/>

=> i added that preference , but some how it called first Magento\Framework\Logger\Handler\Debug
then Magento\Developer\Model\Logger\Handler\Debug,

so still magento creating debug.log file.


Any idea?

**Comment by shimouniak** [comment]
I still have the same debug log entry in 2.2.2:

[2018-01-09 17:01:16] main.DEBUG: cache_invalidate:  {"method":"GET","ur...

**Comment by scottsb** [comment]
@simonmaass and any others: it appears this will be fixed in 2.3.

**Comment by AndyJAllen** [comment]
Experiencing this in 2.4. Upgraded from 2.3.

>  [2018-05-15 11:05:03] main.INFO: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:05:03] main.INFO: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:05:03] main.INFO: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:05:03] main.INFO: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:05:03] main.INFO: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:05:03] main.INFO: Broken reference: the 'currency' tries to reorder itself towards 'store_language', but their parents are different: 'header.panel' and 'porto_header' respectively. [] []
> [2018-05-15 11:05:03] main.INFO: Broken reference: the 'catalog.compare.link' tries to reorder itself towards 'top.links', but their parents are different: 'header.links' and 'header.panel' respectively. [] []
> [2018-05-15 11:15:26] main.INFO: Broken reference: the 'currency' tries to reorder itself towards 'store_language', but their parents are different: 'header.panel' and 'porto_header' respectively. [] []
> [2018-05-15 11:15:26] main.INFO: Broken reference: the 'catalog.compare.link' tries to reorder itself towards 'top.links', but their parents are different: 'header.links' and 'header.panel' respectively. [] []
> [2018-05-15 11:18:59] main.INFO: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:18:59] main.INFO: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:18:59] main.INFO: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
> [2018-05-15 11:18:59] main.INFO: Broken reference: the 'checkout.cart.item.renderers.gift-card.actions.gift_options' element cannot be added as child to 'checkout.cart.item.renderers.gift-card.actions', because the latter doesn't exist [] []
> [2018-05-15 11:18:59] main.INFO: Broken reference: the 'currency' tries to reorder itself towards 'store_language', but their parents are different: 'header.panel' and 'porto_header' respectively. [] []
> [2018-05-15 11:18:59] main.INFO: Broken reference: the 'catalog.compare.link' tries to reorder itself towards 'top.links', but their parents are different: 'header.links' and 'header.panel' respectively. [] []
> [2018-05-15 11:18:59] main.INFO: Broken reference: the 'checkout.cart.item.renderers.gift-card.actions.gift_options' tries to reorder itself towards '', but their parents are different: 'checkout.cart.item.renderers.gift-card.actions' and '' respectively. [] []

**Comment by erikhansen** [comment]
I'm leaving this here incase anyone looks at this issue thread and tries to figure out why the `debug.log` file is empty on 2.2.x: [Stack Exchange - debug.log file is empty in Magento 2.2.x](https://magento.stackexchange.com/questions/226311/debug-log-file-is-empty-in-magento-2-2-x/226312)
