### ISSUE TITLE
Widget cache error

### ISSUE THREAD

**Issue by twslade** [magento/magento2#4389]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add two widgets of type 'Catalog Product List' to the 'CMS homepage' at location content.bottom with different titles, but the same conditions. For example, condition could be product price is greater than 0
3. Refresh cache and visit homepage
## Expected result
1. Two widgets appear on homepage with the same products, but different titles.
## Actual result
1. First widget loaded shows twice depending on sort order
2. See: Magento\CatalogWidget\Block\Product\ProductList::getCacheKeyInfo which doesn't take into consideration the widget_id.

``` php
    /**
     * Get key pieces for caching block content
     *
     * @return array
     */
    public function getCacheKeyInfo()
    {
        $conditions = $this->getData('conditions')
            ? $this->getData('conditions')
            : $this->getData('conditions_encoded');

        return [
            'CATALOG_PRODUCTS_LIST_WIDGET',
            $this->_storeManager->getStore()->getId(),
            $this->_design->getDesignTheme()->getId(),
            $this->httpContext->getValue(\Magento\Customer\Model\Context::CONTEXT_GROUP),
            intval($this->getRequest()->getParam(self::PAGE_VAR_NAME, 1)),
            $this->getProductsPerPage(),
            $conditions
        ];
    }
```

**Comment by oserediuk** [comment]
Hello @twslade! Thank you for the report! We have created issue in our bugtracker system MAGETWO-54008 . It will be fixed as soon as possible.

**Comment by mcspronko** [comment]
Hi @oserediuk 

Do you have any update for timeframe of the MAGETWO-54008 issue?

Thanks

**Comment by oserediuk** [comment]
Hi @mcspronko ! Nope

**Comment by mcspronko** [comment]
Hi @pboisvert 

Are there any deadlines for this issue? 

Thanks,
Max

**Comment by loekderooij** [comment]
This is not caused by the cache key. The rule property is a shared object. This can be solved by defining the rule argument in the constructor as not shared in di.xml.

```
<type name="Magento\CatalogWidget\Block\Product\ProductsList">
    <arguments>
        <argument name="rule" xsi:type="object" shared="false">Magento\CatalogWidget\Model\Rule</argument>
    </arguments>
</type>
```

**Comment by pinicio** [comment]
@LuckyLoek solution doesn't seem to work for me. If someone found a solution to this bug and share it, it would be greatly appreciated.

**Comment by twslade** [comment]
@pinicio I think @LuckyLoek misunderstood the problem. The issue is that the widget_id isn't stored within the cache key. 

I fixed it by adding the widget ID to the \Magento\CatalogWidget\Block\Product\ProductsList::getCacheKeyInfo function in the return. See below. I only came across this scenario because I was making lots of widgets that were the same conditions for mocking client data during a project.

``` php
    public function getCacheKeyInfo()
    {
        $conditions = $this->getData('conditions')
            ? $this->getData('conditions')
            : $this->getData('conditions_encoded');

        return [
            'CATALOG_PRODUCTS_LIST_WIDGET',
            $this->_storeManager->getStore()->getId(),
            $this->_design->getDesignTheme()->getId(),
            $this->httpContext->getValue(\Magento\Customer\Model\Context::CONTEXT_GROUP),
            intval($this->getRequest()->getParam($this->getData('page_var_name'), 1)),
            $this->getProductsPerPage(),
            $conditions . $this->getData('id'),
            serialize($this->getRequest()->getParams())
        ];
    }
```

**Comment by loekderooij** [comment]
@twslade, I didn't misunderstand the problem as I had exactly the same problem. The situations might still be different however. 

I had unique conditions and therefor a unique cache key for each widget. Still this didn't produce the result I expected. I can't test right now but I guess it depends on the widget settings. I think both solutions should be considered depending on the situation.

**Comment by twslade** [comment]
@LuckyLoek The reason I thought you misunderstood the problem is because I had no context into how you came across the bug/solution you provided. As described above, my conditions were the same in both widgets, so the same products were assigned to each widget. The titles were different even though the frontend showed the same block each time, because they had identical cache keys.

I noticed that you said above that the issue doesn't have to do with cache key, but instead the shared rules. Can you give details on steps to reproduce and expected/actual results?

**Comment by loekderooij** [comment]
@twslade,  it was also too easy from my side to assume the problem as described was exactly the same as mine. I will provide details to reproduce as soon as I find some time on my hands.

**Comment by pinicio** [comment]
@LuckyLoek @twslade great, thank you both. I wasn't setting any conditions, so I was able to make it work just by passing the widget id.

``` php
public function getCacheKeyInfo()
{
    return [
        'CATALOG_PRODUCTS_LIST_WIDGET',
        $this->_storeManager->getStore()->getId(),
        $this->_design->getDesignTheme()->getId(),
        $this->httpContext->getValue(\Magento\Customer\Model\Context::CONTEXT_GROUP),
        intval($this->getRequest()->getParam($this->getData('page_var_name'), 1)),
        $this->getProductsPerPage(),
        'my_widget_id',
        serialize($this->getRequest()->getParams())
    ];
}
```

**Comment by henk-hypershop** [comment]
Any fixes for this yet? Has been over 6 months, but the issue still remains in 2.1.3.

**Comment by magento-engcom-team** [comment]
@twslade, thank you for your report.
We've created internal ticket(s) MAGETWO-54008 to track progress on the issue.

**Comment by AlexandrKozyr** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@AlexandrKozyr thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @twslade. Thank you for your report. 
The issue has been fixed in magento/magento2#12764 by @AlexandrKozyr in 2.2-develop branch
Related commit(s):
 - [30b512390dc22ac03079bef839b91ae254834bdc](https://github.com/magento/magento2/commit/30b512390dc22ac03079bef839b91ae254834bdc)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @twslade. Thank you for your report. 
The issue has been fixed in magento/magento2#14816 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [7241aa48f049101c551062cb0ce94ddf9f6e6cd9](https://github.com/magento/magento2/commit/7241aa48f049101c551062cb0ce94ddf9f6e6cd9)

The fix will be available with the upcoming 2.3.0 release.

**Comment by abhaykhatariya** [comment]
It's still existing into magento 2.2.5 when we add cms static block using widget

**Comment by Hoszi** [comment]
It's still existing in magento 2.3.2. when I add the same widget twice in one cms page.
