### ISSUE TITLE
XML Sitemap refers to non-watermarked images

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#4511]
I 've been reviewing the generated XML Sitemap and noticed that the url of the image in the Sitemap refers to a non-watermarked image
## Steps to reproduce
1. Install Magento from 2.0.5 branch.
2. Add  Product with image
3. Add watermarks to all images
4. Add and generate XML Sitemap

Expected result
1. Reference to watermarked image in XML sitemap

Actual result
1. Reference to non-watermarked image. The reference is to the full resolution base image of the product.

**Comment by Stas94** [comment]
@thomvanderboon Thanks for reporting this issue. Created internal issue MAGETWO-70374 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@thomvanderboon, thank you for your report.
We've created internal ticket(s) MAGETWO-70374 to track progress on the issue.

**Comment by superdav42** [comment]
I must point out that this goes beyond XML sitemaps. They should be fixed to use the watermarked images but we also need to ensure only watermark images are stored and made accessible to the public. As it is it's really easy to guess the non watermarked url from the watermarked url.
Watermarked:
/pub/media/catalog/product/cache/31daca0335ff17117734e43b9856c7ed/s/k/sku.jpg
Non-Watermarked
/pub/media/catalog/product/s/k/sku.jpg
I would like the image to only ever have a watermark after it's uploaded and even in the backend there would be a watermark.

**Comment by teoteo** [comment]
@superdav42
> but we also need to ensure only watermark images are stored and made accessible to the public.

On some sites it is a big issue. I’ve partially solved adding rewrite rules in .htaccess in var/media/catalog folder, but a wrong behaviour of some extension can still copy in cache folder the not watermarked image.

**Comment by teoteo** [comment]
May be it is enough specifying the role/type of the image ('image', 'small_image', etc.) in vendor/magento/module-sitemap/Model/Sitemap.php to get the watermarked image?

**Comment by krisdante** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
Hi @thomvanderboon. Thank you for your report. 
The issue has been fixed in magento/magento2#24605 by @krisdante in 2.3-develop branch
Related commit(s):
 - [6ab019b21eb90d9ebe119d8777a111a4b88bfad8](https://github.com/magento/magento2/commit/6ab019b21eb90d9ebe119d8777a111a4b88bfad8)
 - [b7059a615b59b673690f0f3d8187f684213fc72d](https://github.com/magento/magento2/commit/b7059a615b59b673690f0f3d8187f684213fc72d)
 - [861e9f9401dd7845a77e63fb6cddd5359064c027](https://github.com/magento/magento2/commit/861e9f9401dd7845a77e63fb6cddd5359064c027)

The fix will be available with the upcoming 2.3.4 release.
