### ISSUE TITLE
Invalid credentials for 'https://repo.magento.com/packages.json', aborting

### ISSUE THREAD

**Issue by itaymesh** [magento/magento2#4617]
## Steps to reproduce
1. Followed the steps http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html
2. Ran the command: Composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <installation directory name>
## Expected result
1. Install fresh Magento installation via Composer
## Actual result

 [Composer\Downloader\TransportException]  
  Invalid credentials for 'https://repo.magento.com/archives/magento/project-community-edition/magento-project-community-edition-2.0.6.0.zip', aborting. 

---

Note: I am using the same Magnento credetnails for a few weeks now and had no problem connecting to Magento repo. so far.

**Comment by refaelgold** [comment]
same problem  - i get 500 when i try to install it

**Comment by redboxmarcins** [comment]
same problem here, tried 2 different set of keys and both are not working

**Comment by refaelgold** [comment]
thats a bug .
i try with auth.json
i try regenerage 
i try on server with auth.json that allrdy work..

we need to wait for response from magento 
@alankent  do you know about the composer  installation  problem?

**Comment by ghost** [comment]
Same issue here

**Comment by lundsted** [comment]
I have the exact same issue. Was hoping to get some work done today, but now im not so sure.

**Comment by Vinai** [comment]
Ups, didn't mean to close the issue, sorry.
In fact, I wanted to add that the issue also occures when upgrading a composer project:

``` bash
$ composer update
Loading composer repositories with package information
Invalid credentials for 'https://repo.magento.com/packages.json', aborting.
https://repo.magento.com could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
```

Looking forward to a response on Monday I guess.

**Comment by redboxmarcins** [comment]
Whole ecosystem is dependant on one system. If it fails all fails. This is not right

**Comment by ghost** [comment]
That's correct. Was looking to get some work done. Been getting this error for the past 12 hours.

**Comment by refaelgold** [comment]
https://twitter.com/php4u/status/734096597798297604

**Comment by ghost** [comment]
+1. I hadn't tried it since RC1, maybe that's when it started.
I reported this to the proper authorities, will update when one is available.

**Comment by daim2k5** [comment]
Official Statement https://twitter.com/MagentoDevDocs/status/734357914492805120

**Comment by ryantfowler** [comment]
+1 I have also been experiencing the same problem when attempting to create a project (not specifying the rc1 version). I didn't know this was a repo issue until finding this [magento.stackexchange.com](http://magento.stackexchange.com/a/116428) post. Just a thought, it would be nice to have a developer email list where emails regarding these types of issues could be sent to so that we're notified as soon as something like this happens.

Also, @redboxmarcins 's comment is totally valid. It would be nice to have a redundant repo in place for resilience and higher availability.

**Comment by xcomSteveJohnson** [comment]
@itaymesh @refaelgold @ryantfowler The issue is resolved. You _cannot_, however, get 2.1.0-rc1 this way yet.

**Comment by maksek** [comment]
@all Currently we have issues with repo.magento.com, we are working on resolving it. Meanwhile you can use code from GitHub.

**Comment by ryantfowler** [comment]
Steve,

Thank you for the update. I am still experiencing the issue though. It
appears that the issue hasn't been fully resolved. I appreciate you
notifying us with an update.

**Comment by ryantfowler** [comment]
@xcomSteveJohnson Thank you for the update. I am still experiencing the issue though. It
appears that the issue hasn't been fully resolved. I appreciate you
notifying us.

**Comment by ryantfowler** [comment]
@maksek I just wanted to point out that while you're right that we could use code from GitHub, it's not really compatible with a project that was created via Composer. For instance, the structure of the project is slightly different (lib/internal/Magento vs vendor/Magento ), and there would be conflicts in our projects being saved to our own VCS/SCM repository...or we could copy/paste code from GitHub to our own projects (if the project was created with Composer...if not, then shifting gears back to Composer afterwards would require copying/pasting our custom code to the Composer-based M2 project), but that kind of defeats the purpose of using dependency management with Composer, as well as having multiple installation methods (Integrator vs Contributor).

This again goes back to [Issue 4619](https://github.com/magento/magento2/issues/4619). I'm not complaining, just pointing this out.

Thank you for your hard work!

**Comment by leoquijano** [comment]
Thanks everybody for keeping us updated. I would like to add a couple of suggestions:
1. Having redundant repo connections would be awesome to prevent shutting down the entire ecosystem in case of an issue.
2. For important Magento upgrades (such as 2.0.6), it's really, really important that there's a way to upgrade without going through the repo. I agree with @ryantfowler that using Github would not be a simple thing for those of us that use Composer-based project.  
3. I suggest publishing Composer-ready packages for M2 releases (2.0.6, etc). This would work similar as with Magento 1: you just download a package and replace your local copy. Maybe in this case it would involve removing your vendor directory before copying the new contents.

**Comment by gewaechshaus** [comment]
Thanks for the update @maksek .

**Comment by xcomSteveJohnson** [comment]
@ryantfowler  FWIW, an archive install is the same as a Composer install. The structure is identical.

**Comment by ryantfowler** [comment]
@itaymesh @all the problem has been resolved...Please close the ticket.

**Comment by maksek** [comment]
@ryantfowler, you are right, if you originally installed via composer, github won't suite the same installation, but it works for new installations. 
But likely, the issue with repo.magento.com were resolved, and now you can use composer as usual. 
Thank @all for your patience, and don't forget - We, together, are Magento.

**Comment by ghost** [comment]
This issue is still occurring, for me anyway.

**Comment by itaymesh** [comment]
@maksek , I can confirm the issue was solved.
Thanks a lot.

**Comment by Kdtv1977** [comment]
Just a question. So if you credentials works you should be able to connect via https://repo.magento.com/login right? I always get the message "Invalid credentials"? Any ideas

**Comment by daim2k5** [comment]
@Kdtv1977 no the credentials are for https://username:password@repo.magento.com/packages.json

**Comment by hostep** [comment]
Is it possible that in the last hour this is down once again? :(
Is getting a bit frustrating if you need it to work.

**Comment by ryantfowler** [comment]
It is happening again. Check out @blackbooker's Tweet: https://twitter.com/blackbooker/status/738376650002305024?s=09.

Please note. https://github.com/magento/magento2/issues/4619

**Comment by vnahalpara** [comment]
[Composer\Downloader\TransportException]
  Invalid credentials for 'https://repo.magento.com/archives/ingenico/library-ops-m2/ingenico-library-ops-m2-3.1.2.0.
  zip', aborting.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by ai-nick** [comment]
is this just a luck of the draw sort of deal at this point?

**Comment by bastianhilton** [comment]
this is far from resolved but as usual it works for some but for others it doesn't but the community closes the issue. Is there a fix to this or at least provide us with a upload option for extensions through the install

**Comment by bman0147** [comment]
Ok I just got this working, same issue, I just decided to delete the auth.json file and then I was prompted for the user name and password "Authkeys" and it worked

**Comment by bastianhilton** [comment]
i fixed my issue as well, once i connected my install to the marketplace with my keys it worked like a charm when attempting to install extensions via the command line.

**Comment by MaximeCulea** [comment]
> Whole ecosystem is dependant on one system. If it fails all fails. This is not right

@redboxmarcins Just saying you could use Satis to avoid this dependency which works like a proxy ;)

**Comment by fannycqcang** [comment]
@bastianhilton   How did you solve it？My credential was still working a few days ago, but I can't today
