### ISSUE TITLE
Wrong sitemap product url

### ISSUE THREAD

**Issue by teokolo** [magento/magento2#4788]
### Preconditions
1. Magento 2.0.6

### Steps to reproduce
1. "Use Categories Path for Product URLs" set to NO in configuration -> catalog -> catalog -> Search Engine Optimization
2. Create Categories with products
3. Generate sitemap

### Actual result
1. Sitemap is generating wrong urls containing category slug, e.g.:
`<loc>site/category-name/product-name</loc>`

### Expected result
1. `<loc>site/product-name</loc>`

### Additinal information
I also suggest to remove references to cms page used as homepage because it leads to duplicate page indexing, e.g.:
store1.x/
store1.x/home

### In versions 2.1.9 and later problem is converse:
Sitemap is generating urls without containing category slug regardless of the settings
Configuration -> catalog -> catalog -> Search Engine Optimization -> Use Categories Path for Product URLs

**Comment by andidhouse** [comment]
I can confirm this on 2.0.7 version.
Sitemap is generating both urls with and without category.
It should only create what is setup in the backend (with OR without category url).

**Comment by magento-engcom-team** [comment]
We updated description:

### In versions 2.1.9 and later problem is converse:
Sitemap is generating urls without containing category slug regardless of the settings
Configuration -> catalog -> catalog -> Search Engine Optimization -> Use Categories Path for Product URLs

**Comment by magento-engcom-team** [comment]
@teokolo, thank you for your report.
We've created internal ticket(s) MAGETWO-80809 to track progress on the issue.

**Comment by arthurpro** [comment]
Hi! I can fix these issues

**Comment by maksek** [comment]
Hi @arthurpro, looking forward to accept PR :) I sent you invitation to collaborator group, accept it, so I can assign ticket on you.

**Comment by arthurpro** [comment]
Thank you! I will submit my PR when ready.

**Comment by magento-engcom-team** [comment]
Hi @teokolo. Thank you for your report. 
The issue has been fixed in magento/magento2#14338 by @DenisSaltanahmedov in 2.2-develop branch
Related commit(s):
 - [56811a821db00a62cc2072ef075841af45b62d6b](https://github.com/magento/magento2/commit/56811a821db00a62cc2072ef075841af45b62d6b)
 - [79621fb4ab7d7edee62f9091f35b2dc716e42217](https://github.com/magento/magento2/commit/79621fb4ab7d7edee62f9091f35b2dc716e42217)
 - [ba5a5ffb99a0c795c6f51dbcde5a0db2bbca3b94](https://github.com/magento/magento2/commit/ba5a5ffb99a0c795c6f51dbcde5a0db2bbca3b94)
 - [b983a37e0cf3888f24c07ed3a086a3d98845dca0](https://github.com/magento/magento2/commit/b983a37e0cf3888f24c07ed3a086a3d98845dca0)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @teokolo. Thank you for your report. 
The issue has been fixed in magento/magento2#14786 by @mastiuhin-olexandr in 2.3-develop branch
Related commit(s):
 - [986f2c1e55b878eeaafce0210ce9b3e37e31f304](https://github.com/magento/magento2/commit/986f2c1e55b878eeaafce0210ce9b3e37e31f304)
 - [6b770272ca589815320f262a161a1a0ce28d8eed](https://github.com/magento/magento2/commit/6b770272ca589815320f262a161a1a0ce28d8eed)
 - [d823d183e920a2813e137e0b63121a000ca9504f](https://github.com/magento/magento2/commit/d823d183e920a2813e137e0b63121a000ca9504f)
 - [c1f7233e01a8454c2d88456025ce91c69455e127](https://github.com/magento/magento2/commit/c1f7233e01a8454c2d88456025ce91c69455e127)

The fix will be available with the upcoming 2.3.0 release.

**Comment by naydav** [comment]
Reopened because the changes were reverted from 2.3-develop branch (internal ticket MC-16312).
Cause:
```
In https://jira.corp.magento.com/browse/ENGCOM-1351 was changed sitemap's product url generation.
This fix added second logic for sitemap product url generation in case when option "Use Categories Path for Product URLs" enabled.

After check was founded that this fix don't generate native product url and generate just one category/product url (it don't use all category/product urls when product located in few categories)

For example I created simple-1 product that located in category-1 and category-2.
After that Magento 2 can open this product by next links:

simple-1.html
category-1/simple-1.html
category-2/simple-1.html
But sitemap product url generation create only category-2/simple-1.html link
```

**Comment by AlexWorking** [comment]
Hello @naydav. We retested the issue on the latest 2.3-develop version and did not detected the behavior You've described above. Probably it has changed though it still appears to be incorrect. So we deem it better to close the current issue and open a new one related to this one. The new issue is #22934.

**Comment by naydav** [comment]
> Hello @naydav. We retested the issue on the latest 2.3-develop version and did not detected the behavior You've described above. Probably it has changed though it still appears to be incorrect. So we deem it better to close the current issue and open a new one related to this one. The new issue is #22934.

Hello @AlexWorking, could you ask about this issue in #performance channel in the Slack?
Thanks

**Comment by AlexWorking** [comment]
@naydav, I've started a direct message conversation between You and me on Slack as  I'm not a member of the #performance channel, If I do understand it correctly. So please, attend to Your Slack.
