### ISSUE TITLE
Issues with login sesion

### ISSUE THREAD

**Issue by Deepthi57** [magento/magento2#4842]
Note: Version 2.0.7 EE

Steps to reproduce
1.Login into magento frontend
Expected result
1.Customer name displayed after login
Actual result
1.Default welcome msg is being displayed.

Pre-condition:
Have multiple websites ex. main website and website 1

2.Login into main website 
3.Login into website 1
4.Add a product in main website to cart
5.Go to website 1

Expected:
2.Main website displays customer name as main site
3.website 1 displays customer name as website 1
4.Product gets added to main site
5.Cart must be empty in website 1

Actual:
3.After log into website 1, main website displays website 1 as customer name
4.Product gets added in main site
5.Same notification displayed in website 1
Clicking on view cart in website 1 then displays empty cart message

6.Login into magento forntend and add item to cart
7.Go to checkout

Expected:
Flow must continue to checkout

Actual:
Page logs out immediately

NOTE: Lots of inconsistencies in session behavior so kindly do not close the issue as not reproducible

Screenshots attached for clarity
![customer_name_not_displayed_even_after_log_in](https://cloud.githubusercontent.com/assets/17591809/15768845/8775228a-2972-11e6-996e-6ec81a48070d.png)
![i_add_a_product_in_main_website_but_the_message_and_cart_icon_displayed_in_website_1](https://cloud.githubusercontent.com/assets/17591809/15768846/8bad17fe-2972-11e6-9c1e-07b61dede8c9.png)
![cart_displaying_the_item_added_in_main_website](https://cloud.githubusercontent.com/assets/17591809/15768848/8fe87da4-2972-11e6-94db-e66a97205da9.png)
![clicking_on_view_cart_displays_empty_cart_message](https://cloud.githubusercontent.com/assets/17591809/15768850/9889f686-2972-11e6-8f1a-a40aab600f9b.png)
![clicking_on_view_cart_displays_empty_cart_message](https://cloud.githubusercontent.com/assets/17591809/15768855/a14b8ff0-2972-11e6-962e-d5278cc9bd70.png)
![after_login_into_website_1 _main_website_showing_website_1_customer_name](https://cloud.githubusercontent.com/assets/17591809/15768856/a5413dd0-2972-11e6-81b1-198eb591bc4c.png)
![item_that__is_added_in_main_website](https://cloud.githubusercontent.com/assets/17591809/15768857/a7994262-2972-11e6-9c7d-d2746d3da6b1.png)

**Comment by sevos1984** [comment]
This should be fixed in latest 2.0 version, have you tried updating your code base?

**Comment by tommypyatt** [comment]
I have a similar problem in Enterprise 2.1, and am wondering if it's related. @Deepthi57 is this issue still present for you after update?

**Comment by deepthit57** [comment]
@tommypyatt 
Hi, Yes issue still persists in current version of 2.1.1 which is a fresh installation

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-59135. Thanks for reporting

**Comment by slavvka** [comment]
The issue has been fixed for 2.2. Soon it will be ported to previous releases

**Comment by korostii** [comment]
Hi @slavvka, 
Could you please keep the issue open until the fix appears in a released version?

**Comment by gsdsd** [comment]
/to @slavvka : 
Or propose a link to the commit of the v2.2 that corrects this problem.
 Cordially, GsdSd.
