### ISSUE TITLE
Gift wrap option for individual items not displayed for grouped items

### ISSUE THREAD

**Issue by Deepthi57** [magento/magento2#4852]
Magneto Enterprise Endition
Version: 2.0.7
Steps:
1. Go to Magento admin
2. Go to Stores-.Configuration->Sales->Sales
3. Set "yes" for all the options under Gift Options Section
4. Save the config
5. Go to stores->Other Settings->Gift Wraping
6. Add Gift Wrapping
7.Add a grouped product to cart
8.Add a simple and configurable product to cart

Expected result
Gift wrap option for individual item must be displayed below each item with gift wrap options

Actual result
Gift wrap option for individual item is displayed for configurable and simple product but not for grouped item. Gift wrap option is displayed but no options to choose under it

<img width="947" alt="gift option" src="https://cloud.githubusercontent.com/assets/17591809/15776358/a87dd698-29a4-11e6-8cc1-f59a7dfd5276.png">

**Comment by Deepthi57** [comment]
This is important to us. Requesting for a comment asap.
Thanks in advance

**Comment by sdzhepa** [comment]
@Deepthi57 Thank you for reporting this issue. We have created an internal ticket `MAGETWO-53986` to fix the problem.

**Comment by elenleonova** [comment]
The issue has been fixed in 2.2, and will be available with the next release.

**Comment by elenleonova** [comment]
The issue has been released as a part of 2.0.9.

**Comment by deepthit57** [comment]
Hi Elen,
Is this available in 2.1.2 EE? As far as i can see, its still not working for grouped items. Could you please confirm
