### ISSUE TITLE
Product URL Key not automatically generating during import

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#5128]
## Steps to reproduce
1. Install Magento 2.0.7
2. System > Import - Import this CSV file http://www.sharecsv.com/s/03019e6bb511194c0f148764b81708db/m2_import_test_demo.csv
3. Products > Catalog - open the imported product and click "Search Engine Optimisation" tab
## Expected result
1. URL key is filled
2. Product is showing on frontend
## Actual result
1. URL Key is empty
2. Product is not showing on frontend

<img width="974" alt="screen shot 2016-06-21 at 9 43 57 pm" src="https://cloud.githubusercontent.com/assets/19744729/16228339/c9977d1c-37f9-11e6-9244-ea45f2d87c9b.png">

**Comment by BaDos** [comment]
Hi @atIOCrON 

Thank you for reporting.
We've created an internal ticket MAGETWO-58289 to resolve this issue.

**Comment by dmatthew** [comment]
Any updates on this one? Is there an expected release version for this?

**Comment by dcabrejas** [comment]
Hey any updates on this one ?

**Comment by ThisIsRuddy** [comment]
ETA❓😄

**Comment by veloraven** [comment]
I'm closing this issue as it was fixed in develop branch and no backports to ver. 2.1 or 2.0 are planned now.

**Comment by J-Fricke** [comment]
@veloraven which version of Magento 2 will this resolve in? We are still seeing it in v2.1.9 and will soon be upgrading to one of the v2.2.x versions. I see the TODO for v2.3, though I'm not seeing it happen on a clean 2.2.1 install, so that is hopeful.
