### ISSUE TITLE
Product details page zoom issue when dropdown menu have overlap area with it.

### ISSUE THREAD

**Issue by gizmocn** [magento/magento2#5129]
## Steps to reproduce
1. Install Magento RC2.1
2. modify app/design/Magento/luma/etc/view.xml  to enable product gallery zoom, 
## Actual result
1. Zoom works fine, but when hover on category dropdown menu to the overlap area of product image and dropdown menu, the zoom is active abnormally, even the mouse is still on the dropdown menu.

The issue is also existed in 2.0.7.

please check the capture picture:
![screenshot from 2016-06-21 19 50 41](https://cloud.githubusercontent.com/assets/8723299/16228791/b1cdc28a-37eb-11e6-9610-94f657b46f72.png)

**Comment by vil11** [comment]
@gizmocn 

Hi! Thanks for reporting the issue. Internal ticket: **MAGETWO-54719**.

## 

:sunny: dima vilchynskyi, M2 QA

**Comment by phumlaninyati** [comment]
Hi Guys 

Has this issue been resolved by anyone, having the same issue?

Thanks

**Comment by JuteSenthil** [comment]
Hi Team,

Is this issue has resolved ? Can any one provide solution or suggestion for this issue ? It will be more 

helpful for me.

**Note:** Am using Magento-2.0.8 CE version.


Thanks.

**Comment by magento-engcom-team** [comment]
@gizmocn, thank you for your report.
We've created internal ticket(s) MAGETWO-54719 to track progress on the issue.

**Comment by nimitaemipro** [comment]
#mm18in I would like to work on this issues.

**Comment by magento-engcom-team** [comment]
@nimitaemipro thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-team** [comment]
Hi @gizmocn. Thank you for your report. 
The issue has been fixed in magento/magento2#13084 by @mayankzalavadia in 2.2-develop branch
Related commit(s):
 - f36d2ce4ba1d0d7f2a2634c2794b956cc6f57877

The fix will be available with the upcoming patch release.

**Comment by minhluan259** [comment]
@magento-team 
#13084 this patch has an issue
when moving the mouse out of the box, the magnifier-zoom does not hidden
https://prnt.sc/hz6ax8

**Comment by minhluan259** [comment]
#mageconf  I can fix this issue

**Comment by magento-engcom-team** [comment]
Hi @gizmocn. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1351 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 70dd5a3fa17e1ee1cdfaf7f0defd9276989ebbd0
 - 54bc3a1dca861e11e46e12f5a15578e0cb7ceb6d
 - 3debd3f87e27e23949b81cb2d7e881b5a269608c
 - 72c496566bf0d2ff1ced0401514faa5cbaccc0f8
 - e60ecdfeabe8b8839cf52fd5ba7fefcbb0b9bdc3
 - 8703b3da3dbe28f71c1daeaba08bbe44887f0733
 - bd88ed8cc4e1f98b791bd7ca8bed45c29b276ee1
 - 1c70b18a339fddf8a51a476a5a251aabef951350
 - 5fd7481d2cf8b298369837508a16a23ab4f49850
 - 7c615065b36cdafa95d752a891c09dd4ab1a4dfa
 - 2653b8ae55625637a6836d305451e292f881bd6a
 - 917a03f89f98454cb2ecde524dc8557d7fdcc135
 - eca73d0abd1ca6e110c364ef380adab86ab3cc1a
 - 26f3109842ce89096a49b9c122af0bae6b672ba2
 - c223484a75e38fdcece09d4586342528f06c6383
 - 3b90ad71d791ba9cf8e81cc204fd306f41473a18
 - ad317c25039de70c1a976e1139c57730899eb114
 - 53e721ccc06f1ade05132690715575bd7d47d6b7
 - 6114120c0a921b342871448dfb6c47bf34a65cdc
 - 63b483925c18304a32441f66b0db8a9c70995c73

The fix will be available with the upcoming 2.3.0 release.

**Comment by denistrator** [comment]
@magento-engcom-team the issue is not fixed. Please have attention to what @minhluan259 [says](https://github.com/magento/magento2/issues/5129#issuecomment-357060156)

**Comment by denistrator** [comment]
@minhluan259 

> I can fix this issue

what is your fix?

**Comment by minhluan259** [comment]
@denistrator 
You can add the code after line  `$box.on('mousemove', onMousemove);`
```
        $box.on('mouseout', function () {
            onThumbLeave();
            isOverThumb = false;
            $largeWrapper.addClass(MagnifyCls.magnifyHidden);
        });
```

**Comment by vivektrootech** [comment]
Confirm this on (Mage CE 2.2.5) PR #13084 messed up with Magnifier. You've to revert this PR to enable bug free image zoom.

**Comment by boostify-pro** [comment]
I am using 2.2.6 and still having this issue

**Comment by txbada** [comment]
Two new installs of 2.3.0. And the issue is still there on both sites.
