### ISSUE TITLE
Can not access Web Setup Wizard with 2.1 clean install

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#5247]
## Preconditions
Magento 2.1.0
## Steps to reproduce
1. Clean install 2.1.0
2. Try to access Web Setup Wizard
## Expected result

Access to Web Setup Wizard
## Actual result
1. `?app=setup`  Response 302
2. `setup`            Response 301
3. `setup/`           Response 302
4. `setup/index.php/session/unlogin`     Response 401

`Welcome to Magento Admin, your online store headquarters. 
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard`

**Comment by chrone81** [comment]
Same result after upgrading from 2.0.4 to 2.1.0, Web Setup Wizard is missing.

**Comment by EugeneVdovenko** [comment]
Same result after upgrading from 2.0.7 to 2.1.0

**Comment by nobodypb** [comment]
Try entering "setup/" into the addressbar manually. In my case the admin cookie is lost between step 2 and 3

**Comment by ghost** [comment]
Same issue here with a clean install of 2.1. The setup wizard is not there in the system menu.

**Comment by ghost** [comment]
This is an expected result if you use `pub` as your Magento docroot; it's designed this way so you cannot run the Web Setup Wizard in a production environment. Try setting the docroot to the Magento install directory and you should see the wizard again.

**Comment by ghost** [comment]
Web Setup wizard does not work if using the install directory as docroot or pub in 2.1.

It was also in the [2.1 release notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.0CE.html) that the Web Setup wizard is now accessible when using pub as the docroot.
- The Web Setup Wizard now works when Magento is installed in /pub. ([GITHUB-4159](https://github.com/magento/magento2/issues/4159))

**Comment by cizgidekiadam** [comment]
Docroot is not /pub folder. Same problem exist in 2.0.7 and 2.1

**Comment by ghost** [comment]
Are there any updates on this issue? Is it a confirmed known issue?

**Comment by ghost** [comment]
I don't think so. I have installed CE and EE 2.1 recently and am able to use the Setup Wizard. Hopefully someone from engineering will respond. Sorry for the trouble.

**Comment by piotrekkaminski** [comment]
The release notes are incorrect here @tanberry. The issue was not fixed due to unexpected challenges and is scheduled for next version, tracked internally as MAGETWO-52799. You can find more information https://github.com/magento/magento2/issues/4159.

**Comment by tanberry** [comment]
@rbostan and @crtsl  apologies that this issue is listed is Fixed in Rel Notes. As @piotrekkaminski explains above it was a last minute realization, and we failed to reflect final decision.

**Comment by cizgidekiadam** [comment]
@tanberry @piotrekkaminski  Thanks a lot for information. That mistake is not deadly bloody important for us as developers but end users may be 😄

**Comment by tanberry** [comment]
Sure, @rbostan, we really don't want any deadly nor bloody issues. ;-) Thanks for helping us stay safe;  please keep up the communications, we appreciate it!

**Comment by 12impress** [comment]
Is there any solution available?

**Comment by alexgran** [comment]
Is there a workaround to access the wizzard? I'd like to install a couple of modules...?
Got a clean and fresh isntallation, docroot is installation folder

**Comment by wert2all** [comment]
This is a copy of #4159 what was reopened. Thanks for reporting, closed as copy

**Comment by michaelmcgregor** [comment]
how can I setting the docroot to the Magento install directory ..

**Comment by michaelmcgregor** [comment]
installing  magento 2.1.2 to puplic.html as main domain. Then configure the second domain as multistore by parked domain direction. Websetup wizard dont working (setup/index.php/session/unlogin Response 401).
who can explain how can ı fix

**Comment by shuidaan** [comment]
@michaelmcgregor i have the problem same as you, Do You solve this problem ? could you give a email .      shuidaan@gmail.com
installing magento 2.1.2 to puplic.html as main domain. Then configure the second domain as multistore by parked domain direction. Websetup wizard dont working (setup/index.php/session/unlogin Response 401).
who can explain how can ı fix

**Comment by jmsalomr** [comment]
Same problem for me in a fresh install of magento CE 2.1.3. I'm using nginx.
I'm using sample nginx config that comes with the installation.

Anybody knows how to fix that?

**Comment by simonfunk** [comment]
Same here. would be happy for any advice. using CE 2.1.2

**Comment by Ylmzef** [comment]
Same here too CE 2.1.3

**Comment by jeversen** [comment]
Same problem here, just upgraded to 2.1.4 but no web-setup-wizard

**Comment by tanberry** [comment]
@jeversen , lemme look into this. @xcomSteveJohnson ?

**Comment by che2on** [comment]
Hello, I am running the latest 2.1.4, there is a label in right corner showing correct version number. However, when I enter system upgrade through web setup wizard, I see a message "error in update" with rollback button. In reality, the system is running on 2.1.4. Just want to get rid of error message as it is misleading, can u tell me how to clean that message. I might want to update 2.1.5 when it's available so need web set up wizard for future.

**Comment by ghost** [comment]
@che2on This is based on memory but look for hidden files in the `var` directory. If there was a real or imaginary error during upgrade, I think there might be a file named `.upgrade_err` or something. Try renaming it or deleting it.

**Comment by che2on** [comment]
@xcomSteveJohnson Awesome. Removing **.update_error.flag** in var directory solved the problem. Now I can access the web set up wizard and it says I am running the latest magento!  Thank you.

**Comment by jeversen** [comment]
@tanberry @xcomSteveJohnson Searched in the /var directory but no dot-error-alike files there. I must add that I installed 2.1.3; with no web-setup-wizard. But after upgrading (through composer...) to 2.1.4 there is still no web-setup-wizard.

Also tried to move the nginx -docroot to $MAGE_ROOT instead of $MAGE_ROOT/pub but it opened another can of worms. And because this means a considerable security-risk I wont even consider that solution-path an option.

Any other idea's ?

**Comment by vzabaznov** [comment]
Issue is still present and was fixed partially, internal ticket MAGETWO-52799

**Comment by asadyar** [comment]
I tested it with Magento 2.1.3 (with and without sample data) on Apache and NGINX (NGINX with sample configuration)

Results: 
Apache:
Web Setup Wizard link is available under tools - but always gives errors. so cannot install extensions or upgrade

NGINX:
Web Setup Wizard link is missing. If I manually type setup link in address bar 
e.g. www.example.com/setup/#/home
 it redirects to www.example.com/setup/index.php/session/unlogin#/home with below message
"Welcome to Magento Admin, your online store headquarters. 
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard" (but this link in missing)

**Comment by kgeiger310** [comment]
Clean install of Magento 2.1.3 - Web Setup Wizard  redirects to  www.example.com/setup/index.php/session/unlogin#/home on Chrome, but I was able to access setup wizard on Firefox.

**Comment by giabbatino** [comment]
Clean Install 2.1.5. Same Problem on Nginx. php7.0-fpm, MariaDB ubuntu 16.06. 
Web Setup Wizard link is missing. If I manually type setup link in address bar
e.g. www.example.com/setup/#/home
it redirects to www.example.com/setup/index.php/session/unlogin#/home with below message
"Welcome to Magento Admin, your online store headquarters.
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard" (but this link in missing)

Nginx config 
upstream fastcgi_backend {
        server  unix:/run/php/php7.0-fpm.sock;
}

server {

        listen 80;
        server_name www.xxx.com;
        set $MAGE_ROOT /var/www/html/xxx;
        set $MAGE_MODE developer;
         include /var/www/html/xxx/nginx.conf.sample;

Any Idear? Is there an alternativ way to Install extensions?

Kind Regard
Alex

**Comment by Ylmzef** [comment]
Upgraded to 2.1.5 but still same..

**Comment by ghost** [comment]
2.1.5 does not include any functional changes. The 2.1.5 update is to update the copyright date in every file as mentioned in the [release notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.5CE.html).

> This release updates the copyright date in every file. It does not contain any functional changes or security improvements. Isolating these changes in a single release is intended to simplify future updates and developer workflow.

**Comment by Userr017** [comment]
Any solution to this problem?

**Comment by rgjoyce** [comment]
Thought I'd give magento a look today.
What rubbish.
to write my own payment gateway is a nightmare. 
In joomla, I use 1 or 2 files and the payment plugin is working, for any of the cart systems.
Here, I can't even get into the setup wizard to install them because it's broken and the developers don't seem to care that nobody can use the system.

**Comment by Radiergummi** [comment]
I am utterly confused by this problem. Magento has its reputation as being one of the top shop solutions on the market, yet here we have an issue first reported months ago, not solved, no clear answer by the developers, and with no proper solution.  
I'm just trying to set up a shop for my client, adhered strictly to the installation manual, even using the default nginx configuration file, but installing extensions doesn't seem to be possible.  

What on earth is going on? Is there a fix planned? Is this a bug at all, or do I just have something missing from my configuration?
In my whole career as a sysadmin and PHP developer, I've never seen something like this - the key functionality of an application is not given yet there exists no documentation, workaround or clear communication.

**Comment by rgjoyce** [comment]
I figured out how to get around this.

After you install.

Make sure you are logged out of admin

Delete the contents of the /var directory.

Then login to admin and it should work

**Comment by rgjoyce** [comment]
The current verison 1.x of magento seems to be COMPLETELY unuseable

you can install it, but then you can't configure.

once you get into the setup area, it runs a diagnostics test EVERY time you try to do something which is just STUPID because it ran that test when you installed the system.

And now, the test fails on EVERYTHING.

**Comment by Radiergummi** [comment]
@rgjoyce nope, deleting the `var` folder doesn't do anything for me...

**Comment by kgeiger310** [comment]
Try using firefox (on pc) - i typically only use chrome, but I was able to to access with firefox after trying a bunch of other potential solutions.

**Comment by rgjoyce** [comment]
you need to make sure 

install

login

delete /var contents

logout

delete browser cache

RELOAD the admin login page and login

then load the wizard

 

This worked for me just now.

If I miss  step, it fails.

However, it's pointless since the next step is to install something and they retest php and all tests then fail

**Comment by fwolfst** [comment]
@rgjoyce didnt work for me.
And hopefully nobody really deleted `/var`, but `<installdir>var/` ... :)

**Comment by Radiergummi** [comment]
@fwolfst @rgjoyce Nope, for me neither.

@vzabaznov any news about this? If you guys refer to internal tickets, do we have any chance on viewing their status somewhere? Couldn't find anything yet

**Comment by vzabaznov** [comment]
@Radiergummi we have internal ticket MAGETWO-52799 in open status, right now i cannot help you with any estimation, Magento team will update ticket when we will get estimation or ticket status change

**Comment by korostii** [comment]
@vzabaznov, if no estimations are available, would it at least be possible for the Milestone to be set for the issue? meaning the version in which the feature is planned to be delivered: 2.1.10 or 2.2 or whatever.

**Comment by vzabaznov** [comment]
@korostii I hope @tanya-soroka can help you with this question

**Comment by rgjoyce** [comment]
ok I deleted Magento 2.

Gone back to 1.9.3.  At least it works.

**Comment by buskamuza** [comment]
As a workaround, did you try installing extensions via command line?
Let me know if you need more details about it.

**Comment by yassine-y** [comment]
Probably guys, you need contributors. Issues are open for years and for long releases and never solved. I wish I could help. I came across this issue too, and Installed over 3-4 versions (with data, without data) and each version installed using multiple ways, (wizard/command line), Compositor/Server...etc really gives same issues, hard to install crashes all the time... if Magento expects specific configuration why the need to do it manually everytime! ....etc sooo many questions.

**Comment by rgjoyce** [comment]
No. I’ve never found any instructions on how to do so.

**Comment by buskamuza** [comment]
If you have access to the command line,

1. run `composer require <new-package>` or `composer require <new-package>:<version>`
2. run `bin/magento setup:upgrade`

In most cases, it should be enough. Additional actions that you may need in more specific situations:
1. if you test `production` mode, additionally run `bin/magento setup:di:compile && bin/magento setup:static-content:deploy`
2. if you have any troubles with classes, you can try also cleaning `generation` folder and/or cleaning cache (this should be done by `setup:upgrade` command usually, but you can try it just in case something too low-level has changed)

Please let me know if it helps or if something doesn't work for you. It's just a workaround until Setup Wizard is fixed.

**Comment by rgjoyce** [comment]
Thjats over my head. We don’t use composer on our server.

**Comment by Radiergummi** [comment]
@rgjoyce Composer should be available for Magento to work - if it isn't installed yet, just follow the instructions [here](https://getcomposer.org/download/). Olga is right, installing extensions using the Magento CLI application seems to work properly.  

@buskamuza is there a command to update to the latest version automatically? The docs only contain instructions to use `composer require ...`, but having something like `bin/magento setup:upgrade [--version:<version>]` would be great.

**Comment by rgjoyce** [comment]
absolute rubbish.

Composer is NOT required for magento to work and any developer that would make it a requirement needs to be taken out and shot :)

Any person who wants to have their own estore for a small shop, will not have the budget to pay for a dedicated server where they can have comoser setup.  Most of them use shared hosting.

**Comment by Radiergummi** [comment]
@rgjoyce That's why I wrote *should*. Composer is a PHAR file, meaning you are able to run it in most shared hosting environments without any fuss.

I'm not going to follow this discussion further, considering the rude tone of your responses. Have a nice day.

**Comment by MohamedQabbani** [comment]
bad bug

**Comment by magekey** [comment]
Maybe it helps someone... 
Here is what I found on my hosting .. 
My backend panel works on apache server, but "/setup" folder and all "/setup" requests handles by nginx. As result we got Auth error message.
Just want to say most of times it's not an error of Magento code. Please make sure you choose a good provider :)

**Comment by rparsi-commer** [comment]
@tanya-soroka @rbostan @chrone81 @EugeneVdovenko @crtsl @tanberry @carfantasy @alexgran 
@MohamedQabbani @Radiergummi @rgjoyce @buskamuza @you-yas55 @vzabaznov
@korostii @fwolfst @kgeiger310 @Userr017 @Ylmzef @giabbatino @asadyar
@jeversen @simonfunk @jmsalomr @shuidaan @wert2all

Possible workaround and things I discovered -- Please read.

FYI stuff:

Dev environment
* installed latest magento2 (2.1.6) by cloning repo, running composer
* ran `php bin/magento setup:install`
* using default theme

While logged in as the admin, I do NOT see link to Web Setup Wizard.
Attempting to load the `/setup` uri generates the 401 error reported by @rbostan 

Internal staging environment
* not installed by me, but same magento2 version
* also uses default theme

While logged in as the admin I do see the link, but get exact same 401 error.

What I found:
* Using Chrome I traced all the http calls when `/setup` is invoked while logged in as the admin.
After hitting `/setup` my original `admin` cookie is deleted, replaced with new cookie.
This intentional?
* The new `admin` cookie value does not match what's shown in the database (table `admin_user_session`)

Very Yolo workaround:
After `/setup` uri loads and you get the 401 error, edit your cookies, add key `admin` with the value as whatever is in your `admin_user_session` table for the correct `user_id`.  Reload.
This seems to work.

I think there may be a bug with how the Web Setup Wizard determines where to look for the authentication/cookie data, mistakenly generating a new `admin` cookie value, which in turn causes authentication to fail.  Possibly something in Cache management/configuration/settings, though I have no idea what.

Magento2 maintainers please clarify this, is the above expected behavior?

To the other devs, please let me know if my hack at least helps you make progress.
I'm still troubleshooting this, as I can't ask my employers' clients to manually edit their cookies, unfortunately.

**Comment by rparsi-commer** [comment]
@tanya-soroka @veloraven @tanberry ping
I know the magento2 team is very busy, and we all appreciate your efforts
in general, especially dealing with all the posted issues in github.

This is a major feature that's still broken for many people.
Can we get an update on this?
Even if there's no fix, please tell us about any progress, no matter how small.

Thank you.

**Comment by SimbaMCO** [comment]
I've been wrestling with this issue for a few days and found a bit of a workaround.  I noticed that if I was visiting the admin backend via https, and clicked on the Web Setup Wizard link, the errant "unlogin" page would be presented via http (not https).  Watching the sequence of events in my browser's Developer tools (CTRL+SHIFT+I in Chrome and Firefox), I saw that the browser requests /setup via https, but gets redirected by Magento to /setup/ via http (not https).  I'm guessing that the session cookie isn't valid for the different URL base, so Magento treats the request as if it's coming from a session with no valid login.  That doesn't explain **why** it redirects to an http URL instead of https, but at least it gave me a clue toward a work-around.

I configured the Apache virtualhost serving this Magento installation to redirect all http requests to https, and that made the Web Setup Wizard display properly when clicked on - with the added benefit that more things are transported via SSL.

**Comment by rparsi-commer** [comment]
@SimbaMCO I see the same thing happening.  Is it a bug in magento2 code causing the redirect to http from https, or this behavior caused by something in configuration files (ie `app/etc/env.php`)?

**Comment by dklan** [comment]
I had the same problem here, please someone help!

**Comment by rparsi-commer** [comment]
@dklan Did you try configuring apache/nginx to force `https` on `/setup` uri?

**Comment by dklan** [comment]
What does it mean and is that the root cause of the problem? Can you show me how to resolve it pkease.

**Comment by rparsi-commer** [comment]
@dklan I don't know if it's the root cause, but in my case the problem is prevented by configuring apache to redirect `/setup` when it's accessed as `http`, to `https`.  I don't know what the exact config change is, as another person in my team manages the servers, but you can try searching stackoverflow.

**Comment by buskamuza** [comment]
@Radiergummi, no, there is no such Magento CLI command. One of the reasons is that Magento CLI relies on the code and updating the version means removing the code and downloading new code. So it's safer to run different tools for this process.

@rgjoyce , @Radiergummi, Magento application does not require Composer tool to be installed to work. Thought the Setup Wizard uses Composer, it uses it as a library (downloaded as Magento dependency), not as a tool installed on the server.

@rgjoyce, as I mentioned, I proposed a workaround, not a final solution. If you don't have Composer on the production server and don't want to install it there, I would recommend doing code update on staging or development machine. Then use Git to commit the new code (including `vendor` folder) and pull it on production. Then run `magento setup:upgrade` on production. In general, it's always better to have a separate server where you perform upgrade and test it.

**Comment by buskamuza** [comment]
@SimbaMCO, regarding redirect to `http` `setup/` - do you use `https` only as `Base Secure URL` or as both `Base URL` and `Base Secure URL`?

**Comment by SimbaMCO** [comment]
@buskamuza :  https is set in "Base URLs (Secure)".  http is set in "Base URLs".

**Comment by webspeaks** [comment]
Any update on this? Magento2 guys are really ignorant :(

**Comment by dklan** [comment]
I am still facing the same problem and still waiting for advices.

**Comment by svlauer** [comment]
Ran into this issue, tried various versions up to 2.1.7 (with various methods: Composer metapackage vs. download, etc.). The behavior is always the same: Everything works, except when I click on the Composer > Tools > Setup Wizard link, I get forwarded to setup/index.php/session/unlogin .

Except, on the same server (Apache/2.4.25 on a Linux server, tested with both PHP 5.6.28 and 7.0.20 ), I have one (old) 2.0.0 install where the Setup Wizard is reachable (that one does not sync, but I assume that may be because of old bugs).

Maybe this helps to debug:

On the (old) install where the setup wizard is **accessible**:
- When I login the admin, a session cookie "admin" is set with the "cookie path" being the admin path. 
- When the redirect happens, a NEW additional session cookie is set, again named "admin", with the "cookie path" being "/setup".

On the installs where the setup wizard is **inaccessible**:
- When I login the admin, a session cookie "admin" is set with the "cookie path" being the admin path. 
- No additional cookie is set when the redirect happens.

So, it is not so surprising that the setup thinks I am not logged in, as it cannot see the session cookie? The question is why the additional cookie is not set, and/or why the cookie path is not "/" (for an installation in docroot).

**Comment by ghost** [comment]
**# Try using different browser. Somehow it doesn't work in Chrome.**

**Comment by magento-engcom-team** [comment]
@rbostan, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Comment by meichenblatt** [comment]
Its great that you fixed it but if I can't upgrade the fix doesn't do me any good...

**Comment by webmarketiere** [comment]
I installed Magento 2.1.9 today and the problem is still there.

**Comment by paginasweb** [comment]
i just installes magento 2.2.0, same problem on a clean istallation

**Comment by korostii** [comment]
Hi @magento-engcom-team,

Are you sure that the issue is resolved? (see comments above)
Could you please link the corresponding commits which supposedly fix this bug?

Thanks in advance.

**Comment by jalot** [comment]
same problem here on clean install. 
no difference on install by ftp (web setup) or by composer.
issue remains

**Comment by Carcinie** [comment]
Clean install of 2.2. Same problem.

**Comment by jalot** [comment]
I solved it by manually installation of extensions thru composer commands with putty.
Works fine. Although i would love to have a working web setup wizard

Verstuurd vanaf mijn iPhone

Op 29 okt. 2017 om 10:30 heeft Raiden9000 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Clean install of 2.2. Same problem.

**Comment by Carcinie** [comment]
I got it to show up. I was following this tutorial for installing magento: https://www.howtoforge.com/tutorial/how-to-setup-magento-2-with-varnish-and-apache-on-ubuntu-1604/

What I changed was the port from 8080 (as indicated in the tut) to 80 default.
The reason it's changed to 8080 is to run Varnish on 80.

**Comment by pier28inc** [comment]
Fresh install on Debian with PHP7.1 and Magento CE 2.2.1.  Same result.  Cache Management, Backups, and Index Management are the only options under the Tools menu.  We've delayed over a year upgrading out of Magento 1.9.X because of this issue and the product is still not usable.  There's no way that we'll ever spend the money to upgrade to be a paid customer when the codebase is this bad for this long.

**Comment by tony-sar** [comment]
I had the same issue when i moved my magento from shared hosting to vps .. i had no access to wizard with 401 error. decided to use composer to upgrade and that failed because my PHP version was not compatible with 2.2.1 so decided to switch PHP to 7.0.24 , after rebooting apache , decided to take a look at wizard one more time , and to my surprise , IT WORKD .. 

as per magento doc .. php 7.1 is not compatible with magento 2 so maybe switching to something compatible like 7.0.x would help. this was just my experience with this issue , hope will help others.

**Comment by DyrectaLab** [comment]
I had the same issue: 
Magento : 2.1.8 CE
Nginx : 1.13.5
PHP-fpm : 7.0.22-0
OS ubuntu : 16.04
MariaDB  : Ver 15.1 Distrib 10.0.31-MariaDB
Redis-server : Redis server v=3.0.6

I've temporary solved with:
- Log in backend
- Open url : https://www.shop.it/admin_xxxx/admin/backendapp/redirect/app/setup/
And then the setup wizzard open correctly.

Any stable fix for this issue?

**Comment by lbetineli** [comment]
Fresh install of 2.2.2 CE and same problem. Nginx 1.10.3 (Ubuntu 16.04).
MYSql 14.14, PHP 7.0.22-0

**Comment by rparsi-commer** [comment]
@lbetineli How about 2.3 CE?

**Comment by korostii** [comment]
@rparsi-commer Last time I checked, 2.3 wasn't released yet :)

**Comment by rparsi-commer** [comment]
@korostii Well I see the "Fixed in 2.3.x" label...so I thought one could checkout that version and try again

**Comment by korostii** [comment]
Well, it also says `Fixed in 2.1.x`, `Fixed in 2.2.x`, but that doesn't seem to be true neither.

Besides, in case of 2.3 it's of little use because it's basically a develop version, nowhere near stable and not suitable for use in production. Feel free to check it out all you want, but IMHO it would be a total waste of time in this case.

**Comment by rparsi-commer** [comment]
@korostii I don't think this is in magento team's list of priorities, and even if eventually fixed by the time that happens do we even need a setup wizard?
I find it easier to just use the cli for such things.

**Comment by tlc033** [comment]
Solution for me was:
Base URLs (Secure)
-> Use Secure URLs on Storefront -> Yes
-> Use Secure URLs in Admin -> Yes
-> Enable HTTP Strict Transport Security (HSTS) -> Yes
-> Upgrade Insecure Requests -> Yes
php bin/magento cache:clean
https://yadi.sk/i/iPJi4k7X3S86Za
I SOLVE THIS.

**Comment by ncompass** [comment]
@tlc033 
THE MAN IS NOT LYING. BEST QUICK FIX

**Comment by fwolfst** [comment]
I could not udate these values via the admin backend (error regarding placeholer/template). I guess in `core_config_values` table its these values: `web/secure/enable_upgrade_insecure` and `web/secure/enable_hsts`. However, setting these to "1" (where "0" before **did not solve** the issue for me. Btw, after I changed the values in the db I can now change them in the backend without error.

**Comment by michelve** [comment]
Still having this issue any permanent solution

**Comment by epileftro85** [comment]
i have the same issue, any update in this? version 2.2.3, mac os and nginx, fresh install.

**Comment by DonMooi** [comment]
This is getting lame, 2.2.3 same problem ---> websetup wizard goes to /unlogin and gives a 401 authorization error.

PHP71
Appache/Nginx
Root not in PUB

Tried sollution:

Solution for me was:
Base URLs (Secure)
-> Use Secure URLs on Storefront -> Yes
-> Use Secure URLs in Admin -> Yes
-> Enable HTTP Strict Transport Security (HSTS) -> Yes
-> Upgrade Insecure Requests -> Yes
php bin/magento cache:clean

Did not work for me!

**Comment by epileftro85** [comment]
I’ve notice or I think it is cache problem, because I opened on incognito with no problems, and after try it again, and it works

**Comment by DonMooi** [comment]
> This is getting lame, 2.2.3 same problem ---> websetup wizard goes to /unlogin and gives a 401 authorization  error.

> PHP71 / Appache/Nginx / Root not in PUB

> Tried sollution:
> 
> Solution for me was:
> Base URLs (Secure)
> -> Use Secure URLs on Storefront -> Yes
> -> Use Secure URLs in Admin -> Yes
> -> Enable HTTP Strict Transport Security (HSTS) -> Yes
> -> Upgrade Insecure Requests -> Yes
> php bin/magento cache:clean
> 
> Did not work for me!

More testing:

1) I have noticed that in the configuration file app/etc/env.php the session save is set to db:

Code:
`'save' => 'db',`

so I have changed to files:

Code:
`'save' => 'files',`

And flushed the Magento cache.   

This did not fix the problem.... 

2) Then I made sure all the correct permissions are set for all directories and files.... 

This did not fix the problem either....

3) I have noticed that the ownership of the magento directory is "nobody"

Change this to the main admin user

This did not fix the problem either.....

4) I have tested the case with PHP70 and PHP71 

but sadly again to no avail....

5) I have also checked if the local php.ini file is not causing the issue 

But again this was not the cause....

6) My magento installation was installed in a directory, I moved the installation to the root. 

NO success either.

As I have written in my previous post, this is getting LAME!  How is it possible that an eCommerce application like Magento has these major bugs. 

YES we can install extensions manually through SSH or Putty, but not all extension developers offer instructions on how to do that.  

I would urge everybody to write down the tests that they have done towards a fix and post it here... so we don't have to invent the wheel again.

**Comment by TechnoBuddhist** [comment]
What worked for me...

`ln -s [magento-install-dir]/setup  [magento-install-dir]/pub/setup `

After installing mods/updates, remove the link

`rm [magento-install-dir]/pub/setup`

If the symbolic link doesn't work for you, check permissions and ownership(mine was set to nobody - the apache.http user)

`chown [magento-user]:[magento-user]   [magento-install-dir]/setup/* `

Hope this helps!

**Comment by PieroBonforte** [comment]
I found this solution for magento 2.2.4

http://phpcodez.com/configure-memcached-magento-2/

for me worked.

**Comment by PieroBonforte** [comment]
I found this solution for magento 2.2.4

http://phpcodez.com/configure-memcached-magento-2/

for me worked.

**Comment by ghost** [comment]
I will be out of the office from May 4 and returning May 14.

Please send your inquiries to sales@roselandtech.ca during this period

**Comment by chriskim-kissusa** [comment]
In my case, When I downgrade php version 7.1 to 7.0, It works for me. 
hope this help.

**Comment by 3615helloworld** [comment]
I am on Magento 2.3. I have the same issue. @tlc033 fix does not work for me. Did a genius managed to fix that? A step by step would be much appreciated! 

> Solution for me was:
> Base URLs (Secure)
> -> Use Secure URLs on Storefront -> Yes
> -> Use Secure URLs in Admin -> Yes
> -> Enable HTTP Strict Transport Security (HSTS) -> Yes
> -> Upgrade Insecure Requests -> Yes
> php bin/magento cache:clean
> https://yadi.sk/i/iPJi4k7X3S86Za
> I SOLVE THIS.

Also, there is no /setup folder in my /pub directory. Does the Symlink solution would still work? @TechnoBuddhist

> What worked for me...

> ln -s [magento-install-dir]/setup [magento-install-dir]/pub/setup

> After installing mods/updates, remove the link

> rm [magento-install-dir]/setup

> If the symbolic link doesn't work for you, check permissions and ownership(mine was set to nobody - the apache.http user)

> chown [magento-user]:[magento-user] [magento-install-dir]/setup/*

> Hope this helps!

**Comment by urfusion** [comment]
I am still facing the issue with my magento v 2.2.6 which I have upgraded by command line from V2.1. I have tried all the solution mention above such as "Symbolic link", "session is already is in the file", "Permission and ownership" but nothing working. Anyone find out the solution.

**Comment by PrakashElsner** [comment]
If u are installing  magento2 in nginx+varnish  webserver then varnish must on port 80 and backend port 8080 and nginx port must be 8080.
Then create virtual hosts like this in directory **/etc/nginx/conf.d/**
Magento installation path must match according to magento virtual host
1.magento.test.conf

server {
listen 8080;
    server_name magento.test;

     access_log /var/log/nginx/magento.test.access.log;
    error_log /var/log/nginx/magento.test.error.log;


    root /usr/share/nginx/html/magento;

    index index.html index.htm index.php;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
     #   include /etc/nginx/conf.d/magento.phpmyadmin.conf;
        location / {
        try_files /maintenance.html $uri $uri/ @handler; ## If missing pass the URI to Magento's front handler
        expires 30d; ## Assume all files are cachable
    }
    location @handler { ## Magento uses a common front handler
        rewrite / /index.php;
    }
    location ~ .php/ { ## Forward paths like /js/index.php/x.js to relevant handler
        rewrite ^(.*.php)/ $1 last;
}
   location ~ \.php$ {
                include /etc/nginx/fastcgi_params;        
include /etc/nginx/fastcgi.conf;
 fastcgi_pass 127.0.0.1:9001;
                fastcgi_index  index.php;
                fastcgi_param  SERVER_PORT 8080;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                fastcgi_param  MAGE_RUN_CODE default; ## Store code is defined in administration > Configuration > Manage Stores
                fastcgi_param MAGE_RUN_TYPE store;
        }


}
#End


 >And then do hosts entry in /etc/hosts  > localhost   magento.test
Then open http://magento.test in browser.
Make sure your php-fpm www.conf, and php session  file has correct ownership of nginx.
Then u can start installing.
