### ISSUE TITLE
2.1 Can't remove added product to cart message

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#5301]
After placing an order I was unable to remove the "You added Test Product to your shopping cart." message. The message also appeared on the order success page and even reappears when I close the browser and open the site again - see screenshot
![magento 2](https://cloud.githubusercontent.com/assets/10808588/16406411/6cda9246-3d51-11e6-8adb-a0b584af574d.png)

**Comment by plentyhappy** [comment]
I have a similar problem.  Current version is 2.0.7.  Whenever I add a product to cart the success message comes up and keeps showing anywhere I go in cart until going to one step checkout.  Also, if I add or remove to compare same thing happens...success message will not go away.

You added xxxx to your shopping cart.

You removed product xxxxx from the comparison list.

**Comment by bondimedical3** [comment]
This appeared to be some kind of glitch as I have tried more orders and the issue has disappeared.

**Comment by bondimedical3** [comment]
![magento2 1](https://cloud.githubusercontent.com/assets/10808588/16474440/3f487ae0-3eba-11e6-9dde-7843f48718a6.png)
The issue appears to be intermitrent. I have added an item to the cart today and the message appeared again on every page.

**Comment by wert2all** [comment]
To allow us research the issue, please, provide description according to the template and 
very accurate steps for reproduce.

**Comment by plentyhappy** [comment]
Version: 2.0.7

1) Click add to cart on home page for any product that shows 
2) click on category OR click on another product nothing shows
3) click a home page link and the success message occurs again
4) then I click on category page or product page again and now the success message keeps following me everywhere and won't go away.

I cleared chrome browser cache and tried again click add to cart directly from a category page and could not make the problem appear however when I go to home page and click add to cart it appears.  The same problem appears in Firefox but does not follow me around in category or product pages...only keeps showing on home page.  

Also in both Firefox and Chrome if I leave the session alone for a few minutes it seems to disappear until I start adding to cart again.

**Comment by oserediuk** [comment]
Do you use some widget on the home page which contains a product?

**Comment by bondimedical3** [comment]
Nothing. You can see a screenshot of the homepage above.

**Comment by oserediuk** [comment]
@bondimedical3 I don't see any product on your home page)

**Comment by plentyhappy** [comment]
I use productlist widget on home page

**Comment by plentyhappy** [comment]
Here's a similar thread:

https://github.com/magento/magento2/issues/5530

someone said that saying yes to cookie restriction mode fixed the problem but it did not work for me

**Comment by andimov** [comment]
@bondimedical3 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by bondimedical3** [comment]
This issue has not been resolved. Have just done a new installation of 2.1.1 and everything is working except for this - see screenshot.
![magento2](https://cloud.githubusercontent.com/assets/10808588/18622775/5104ccbe-7e77-11e6-827a-174e070c88c8.jpg)

**Comment by lucscu** [comment]
Could someone reply to this bug?

**Comment by mtb2112** [comment]
I'm working on a custom theme inheriting from blank, and I'm also getting this bug on the frontend.  I'm on version 2.1.2.

**Comment by lucscu** [comment]
@mtb2112 it is fixed in commit https://github.com/magento/magento2/commit/9515999f75fc728084079b8aae7ccc784cd8c1f3, just see other closed ticket https://github.com/magento/magento2/issues/5530.
I tried the fix and it seems work correctly.

**Comment by mtb2112** [comment]
Thanks @LucScu.  That resolved the issue for me.

**Comment by bondimedical3** [comment]
This has STILL not been fixed. Upgraded to 2.1.3 today and the bug is still showing intermittently. I have looked at the fixes:
Internal ticket for develop branch - MAGETWO-54866, fix is in commit 9515999
Internal ticker for branch 2.1 - MAGETWO-56956, fix is in commit 39b35ec
Internal ticket for branch 2.0 - MAGETWO-56955, fix is in commit 592ded2
but none of these work.
![magento](https://cloud.githubusercontent.com/assets/10808588/21415665/89f601e0-c860-11e6-9fb8-845af43c13ae.png)

**Comment by henryonsoftware** [comment]
Try this http://magento.stackexchange.com/questions/154119/remove-success-message-after-show

**Comment by ludwig-gramberg** [comment]
Hi all,

I made some tests and I tracked the bug down to a single method call in js.
Mage: 2.0.7
Symptoms:
 - Google Chrome: usually no symptoms, only rarely happens
 - Firefox: always happens

How to reproduce the bug (in devmode):
1. clear all caches, cookies, local storage from your browser
2. open customer-data.js from customer module
3. comment out the line  59 ``storage.remove(sectionName);``
4. trigger any system message
5. see how the message never disappears

Problematic code:
File: ``mage/vendor/magento/module-customer/view/frontend/web/js/customer-data.js``
Code: 
```
ko.extenders.disposableCustomerData = function(target, sectionName) {
        var sectionDataIds, newSectionDataIds = {};
        target.subscribe(function(newValue) {
            setTimeout(function(){
                storage.remove(sectionName); // <-- comment out this line
                sectionDataIds = $.cookieStorage.get('section_data_ids') || {};
                _.each(sectionDataIds, function (data, name) {
                    if (name != sectionName) {
                        newSectionDataIds[name] = data;
                    }
                });
                $.cookieStorage.set('section_data_ids', newSectionDataIds);
            }, 3000); // <-- comment out this line
        });
        return target;
    };
```

whenever the call to ``storage.remove(sectionName)`` fails, the browser is stuck in the state of showing the messages (I guess they're persisted in local storage). Prevent this call once and the message will stick around.
What I did was remove the timeout so the code is called immediately to reduce the chance of a messages sticking around (the 3s timeout is like asking for it).... 

I'm not 100% sure what goes wrong but 1) i could reproduce the bug, 2) removing the timeout cured the problem for me in firefox.

Maybe a magento frontend dev can shed some light as to what this is supposed to do exactly.

**Comment by sboutet06** [comment]
Hi I managed to make it work by adding some more condition introduced in the commit [iivashchenko committed on 17 Aug 2016](https://github.com/magento/magento2/commit/9515999f75fc728084079b8aae7ccc784cd8c1f3).

You need to modify the file located in `pub/static/frontend/Magento/luma/fr_FR/Magento_Theme/js/view/messages.js` as follow:

```
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
define([
    'jquery',
    'uiComponent',
    'Magento_Customer/js/customer-data',
    'jquery/jquery-storageapi'
], function ($, Component, customerData) {
    'use strict';

    return Component.extend({
        defaults: {
            cookieMessages: [],
            messages: []
        },
        initialize: function () {
            this._super();

            this.cookieMessages = $.cookieStorage.get('mage-messages');

            this.messages = customerData.get('messages').extend({
                    disposableCustomerData: 'messages'
                });

            var mess = this.messages();

            // Force to clean obsolete messages
            if (!_.isEmpty(mess.messages) || !mess.hasOwnProperty('messages')) {  // <-- force clean if messages property does not exist
                    customerData.set('messages', {});
            }

            $.cookieStorage.setConf({path: '/', expires: -1}).set('mage-messages', null);
        }
    });
});
```

Hope this helps.

**Comment by rotanev** [comment]
Temporary solution (saves his time and nerves):

1. Make copy of `vendor/magento/module-theme/view/frontend/web/js/view/messages.js` file:
<pre>
[magento@server webhome]# cp vendor/magento/module-theme/view/frontend/web/js/view/messages.js \
app/design/frontend/&lt;VendorName&gt;/&lt;theme&gt;/Magento_Theme/web/js/view/messages.js
</pre>

2. Find next line:
<pre>
$.cookieStorage.set('mage-messages', '');
</pre>
3. Replace with next:
<pre>
$(document).ready(function() {
      $.cookieStorage.set('mage-messages', '');
});
</pre>

**Comment by Triloworld** [comment]
My proposal before good fix of task quene after AJAX request:
Add ` "domReady!"` to list of defined method. I add setTimeout to be sure that messages are cleared from cookie. 

Main problem: Messages from AJAX are delivered after messages.js initialize method so they stay random time on screen.

**Comment by ashvinim0003** [comment]
same issue in magento 2.1.8 :(
any solution ?

**Comment by schizek** [comment]
Is there any update on this?

**Comment by talalus** [comment]
from https://github.com/magento/magento2/issues/10107#issue-239735117
copy vendor/magento/module-theme/view/frontend/web/js/view/messages.js to your theme file, and at the end of initialize function add:`
$(window).on('beforeunload', function () {
    $.cookieStorage.set('mage-messages', '');
});
`

**Comment by NguyenXuanNam** [comment]
> from [#10107 (comment)](https://github.com/magento/magento2/issues/10107#issue-239735117) copy vendor/magento/module-theme/view/frontend/web/js/view/messages.js to your theme file, and at the end of initialize function add:`$(window).on('beforeunload', function () { $.cookieStorage.set('mage-messages', ''); });`

- Not working on browser mobile.

**Comment by Triloworld** [comment]
> > from [#10107 (comment)](https://github.com/magento/magento2/issues/10107#issue-239735117) copy vendor/magento/module-theme/view/frontend/web/js/view/messages.js to your theme file, and at the end of initialize function add:`$(window).on('beforeunload', function () { $.cookieStorage.set('mage-messages', ''); });`
> 
> @talalus i'm already added this line before that's why it works fine in desktop, but I don't know why it didn't work on mobile devices(not emulator)

First, try other methods that are provided and update Magento, it should fix error even on mobile.
Pleas create new issue regarding your problem, add this as reference and add all required details as this is required by core team to fix that issue (check reply and reopen there issue - https://github.com/magento/magento2/issues/10107#issuecomment-330776636). Your response is on 2016 topic where last response was 2019 and main topic require data to be provided. Consider this topic as close

**Comment by ychadwick** [comment]
This issue still exists in Magento 2.4.3. The cookie gets removed, but then added again, as incoming ajax responses still contain the cookie, and, in Dev mode the assets are loaded much slower, which I think could cause the javascript to clear the cookie occurring earlier, and thus the cookie is repopulated.

In order to easily remove the unwanted cookies, just wrap the call to clear the cookie in a setTimeout, that should work on all platforms.

Copy the file vendor/magento/module-theme/view/frontend/web/js/view/messages.js and add create a file in your design directory called Magento_Theme/web/js/view/messages.js

This is how I delay the clearing of, adjust the timeout to suit your needs, I have it pretty slow in my dev environment.

`initialize: function () {
            this._super();

            this.cookieMessages = _.unique($.cookieStorage.get('mage-messages'), 'text');
            this.messages = customerData.get('messages').extend({
                disposableCustomerData: 'messages'
            });


            // Force to clean obsolete messages
            if (!_.isEmpty(this.messages().messages)) {
                customerData.set('messages', {});
            }

            setTimeout(() => {
                $.mage.cookies.set('mage-messages', '', {
                    samesite: 'strict',
                    domain: ''
                });
            }, 5000 )
        `
