### ISSUE TITLE
Minimal price "As low as $x.xx" being added to product page when cache is enabled on 2.1CE

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#5364]
## Steps to reproduce
1. Install Magento 2.1.0.
2. Enable cache (FPC or Varnish).
3. Add tier price to Simple, Virtual or Downloadable product.
4. View product page and see that "As low as $x.xx" is being added below product price.
5. Flush cache once or twice.
6. "As low as $x.xx" goes away from product page but ALSO is removed from below price on category page.
7. Repeat flushing of cache and it returns to product page again.

NOTE: This does not happen when cache is disabled, only when FPC or Varnish is enabled.
## Expected result
1. "As low as $x.xx" is NOT added below price on PRODUCT page.
2. Flushing of cache does NOT remove "As low as $x.xx" from CATEGORY page.
## Actual result
1. See screenshots...

![tier_cache_bug](https://cloud.githubusercontent.com/assets/18691038/16462844/1c8f4eb6-3e01-11e6-8b95-8e99b991b6ff.jpg)
![tier_cache_bug2](https://cloud.githubusercontent.com/assets/18691038/16462845/1c8fa776-3e01-11e6-980e-1361915d7bf1.jpg)

**Comment by thewhisperinyourears** [comment]
It doesnt loom a bug to me. Is more lime a offer rule. If you buy 5 you get it for 20

**Comment by stevekem** [comment]
It is a bug, the minimal price link should not be displaying on product page like it's shown in screenshot. Also the flushing of cache is removing it from category page.  This only happens when cache is enabled.

**Comment by pboisvert** [comment]
Not able to reproduce this on 2.1. I added tier pricing (2 levels) and the site has FPC enabled and then flushed the cache repeatedly and the tier pricing message remains on the product detail page and the product listing (category) page. Is there more detail to provide in terms of browser or other configuration info?

**Comment by stevekem** [comment]
The minimal price link is not supposed to appear on product detail page in 2.1 correct?

**Comment by stevekem** [comment]
Not sure if it matters but cache was flushed through SSH. It appears in all browsers (latest versions)

**Comment by stevekem** [comment]
Server is Debian GNU/Linux 8 and it happens on fresh install of 2.1.0 for us and for our developer on their server too.

**Comment by stevekem** [comment]
@pboisvert Installed a fresh copy of 2.1.0 on a new server at nexcess and same issue is happening with cache enabled.  This server is:

CentOS 6.7
PHP 5.6.20

Are you able to reproduce it yet?

**Comment by pboisvert** [comment]
@stevekem i was not able to reproduce in 2.1 with my account yet. Will pass along

**Comment by stevekem** [comment]
Can anyone instruct me how to make just the price block on category and product details page non-cacheable until a fix for this bug is done?  This is really preventing us from using this version since the minimal price keeps disappearing on category page when cache is enabled.  I would pay for this fix if anyone can help.  Thanks!

**Comment by tkacheva** [comment]
@stevekem you are right. Product page should contain _Buy 2 for $__._ each and save _%_
Bug is reported MAGETWO-55055
@antboiko could you confirm?

**Comment by stevekem** [comment]
The "Buy 2 for $_._ each and save %" is working normally actually.  The issue I am having is when cache is enabled, "As low as $_.__" is appearing below the price on product pages (this text previously only appeared on category pages).  Once you flush the cache a few times through SSH, this goes away on product pages BUT ALSO goes away on category pages (which is not normal).

We have installed on a variety of hosts with and without varnish and it always happens. If this was a feature that Magento added to product page, that is fine but why would it only appear when cache is enabled + go away when cache is flushed + also remove it from the category pages when cache is flushed.

**Comment by tkacheva** [comment]
@stevekem thanks, we are working on this issue already.

**Comment by cpartica** [comment]
This issue is related to #5364
This issue has been resolved and merged to develop (via MAGETWO-54320 and MAGETWO-55055) and it will available in the next release. Feel free to let us know if you encounter any other issues.

**Comment by elenleonova** [comment]
The issue has been released in 2.1.1.

**Comment by yosefkurniawan** [comment]
I'm still facing this issue in 2.1.3.
I have product with tier price to set special price for any customer group.
The problem is, price got cached on certain customer group. So user with different customer group would see the price of other customer group.
is anyone also still facing the same issue?

**Comment by MagentoSeba** [comment]
@cpartica @pboisvert this is not fixed in 2.1.3

**Comment by Hawkmoon72** [comment]
This has just started happening to me after upgrading from Magento 2.2.3 to 2.2.5.    Have never had this happen before - and no tier prices in on our in development site.  Also happened when upgrading on a copy of the site too.  Have tried many of the workarounds published here and elsewhere - nothing seems to work.
