### ISSUE TITLE
Flash message appears everywhere with Varnish

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5376]
## Steps to reproduce
1. Install Magento 2.0.7
2. Setup Varnish4
3. Add product to the cart or perform any other action that triggers flash message
## Expected result
1. Each flash message is shown only once
## Actual result
1. The same flash message is shown in all pages when I continue to navigate through site

This issue is present only when Varnish is enabled. This bug was mentioned 2 month ago already on [http://magento.stackexchange.com/](http://magento.stackexchange.com/questions/110561/magento2-and-varnish-always-delivers-flash-messages)

**Comment by lukeconvertdigital** [comment]
Where are you terminating SSL?

**Comment by jsakars** [comment]
@helloitsluke nowhere - we don't have SSL currently

**Comment by LiamFielding** [comment]
My messages are showing everywhere and multiple times without SSL. I haven't done anything to setup Varnish either - simply installed from dev branch.

**Comment by sevos1984** [comment]
This was fixed in 2.0.8, try updating your code base

**Comment by jsakars** [comment]
@sevos1984 we are using 2.0.8 - issue is still present. For example, I can see flash message for `product added to the cart` in CMS page

**Comment by sevos1984** [comment]
Have you tried 2.0.9. This looks like https://github.com/magento/magento2/issues/4336 https://github.com/magento/magento2/issues/4186 https://github.com/magento/magento2/issues/3503 that are fixed already. Check that you have respective commits.

**Comment by sevos1984** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.
