### ISSUE TITLE
Poor error message placement for Configurable products required swatch selection on Product page

### ISSUE THREAD

**Issue by lucasng13** [magento/magento2#5428]
## Steps to reproduce
1. Install Magento 2.1.
2. Go to a Configurable Product page.
3. Don't select any options and click "Add to cart"
## Expected result

 Message "This is a required field." should display below options.
## Actual result

 Message "This is a required field." displays at the bottom of form.

![required_field](https://cloud.githubusercontent.com/assets/19704072/16550473/22cfb0a4-41d5-11e6-99ce-3a75e7ba8702.png)

**Comment by wert2all** [comment]
Thanks for reporting. Internal ticket MAGETWO-55042 was created.

**Comment by kfaer** [comment]
that is good, but when will get it resolved? so I need to stop using M2.1 in production because of this issue.

**Comment by parthviroja** [comment]
I have resolve this issue.

### open below file

> ...pub\static\frontend\Magento\...\en_US\Magento_Swatches\js\swatch-renderer.js

### find below line around 273 line number

`if ($widget.productForm) {
                $widget.productForm.append(input);
                 input = '';
         }
`

### modify

`$widget.productForm.append(input);  ->  container.append(input);`

### after modification code look like this

`if ($widget.productForm) {
                    container.append(input);
                    input = '';
                }
`

now validation message will be display below options

**Comment by ksz2013** [comment]
Will this be resolved in the next release?

Thanks,

**Comment by mombrea** [comment]
@parthviroja was on the right track however you don't want to modify a pub/static file since it will be overwritten with each deploy.

In order to fix this you have to override the JavaScript for a Magento Core module. /vendor/magento/module-swatches/view/frontend/web/js/swatch-renderer.js
1. Create `<theme_dir>/Magento_Swatches/web/js/swatch-renderer.js`
2. Copy contents of `vendor/magento/module-swatches/view/frontend/web/js/swatch-renderer.js` into the newly created file
3. At around line 283, change

`if ($widget.productForm) {
       $widget.productForm.append(input);
       input = '';
  }`

to

`if ($widget.productForm) {
       container.append(input);
       input = '';
  }`
1. Move the snippet under the following snippet, which should be at around 288.

`// Create new control
container.append(
    '<div class="' + classes.attributeClass + ' ' + item.code +
        '" attribute-code="' + item.code +
        '" attribute-id="' + item.id + '">' +
            label +
        '<div class="' + classes.attributeOptionsWrapper + ' clearfix">' +
            options + select +
        '</div>' + input +
    '</div>'
);`
1. Flush Magento Cache
2. Flush JavaScript/CSS Cache

**Comment by tkacheva** [comment]
Issue is fixed and delivered into mainline 
https://github.com/magento/magento2/commit/51bc865
 If you still have it after upgrade, please reopen

**Comment by TClilMouse** [comment]
@tkacheva I upgraded to Magento 2.1.2 still having this issue.

**Comment by Dublerq** [comment]
same

**Comment by paales** [comment]
@seavenger @Dublerq The fix isn't in 2.1.2 yet, will be in 2.2 (or in 2.1.3 but don't get your hopes up).

**Comment by ghost** [comment]
Still in 2.1.2.

**Comment by erik-augustin** [comment]
Same problem 2.1.3.;-(

**Comment by tkacheva** [comment]
Delivering fix into mainline means that fix is in develop brunch (2.2 currently)
It will be included in upcoming patch release

**Comment by lingwooc** [comment]
I turned the relevant parts of the fix into a module (I ignored the aria stuff). [requiredFields-magento2](https://github.com/lingwooc/requiredFields-magento2). It appears to work just fine in isolation.  I only tested in 2.1.3 YMMV.

When we get the integrated fix just remove the module.

**Comment by ksz2013** [comment]
Hi,

Those who still have this problem i created a custom snippet that resolves this issue:

Just include it in one of your templates:


`
<pre>
<script>
    require([
        "jquery"
    ], function($){
        $(document).ready(function () {
            'use strict';
            var validationErrorMoved = false;
            $('#product-addtocart-button').click(function() {
                if (!validationErrorMoved) {
                    $('.swatch-attribute').each(function() {
                        var attrId = $(this).attr('attribute-id');
                        var validationElement = $('input[name="super_attribute['+attrId+']"]').get(0);
                        $(validationElement).appendTo(this);
                    });
                    validationErrorMoved = true;
                }
            });
        });
    });
</script>
</pre>`

No core functionality is rewritten, when they relese the fix, just remove this snippet.
Regards

**Comment by kfriend** [comment]
@ksz2013's workaround appears to be working for me. Might be a good band aid for others affected. 

Thanks!

**Comment by Ctucker9233** [comment]
@tkacheva Which version of Magento will this fix be included in?

**Comment by giusecapo** [comment]
Thanks @ksz2013 your wa worked like a charm!

**Comment by kfriend** [comment]
This is still an issue in 2.1.5.

**Comment by phanngochanh** [comment]
Thanks @ksz2013. It work for me
