### ISSUE TITLE
Transactional Email error

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#5484]
Can´t send transactional email error during operation:
Error filtering template: Warning: Missing argument 1 for Magento\Framework\View\Element\Template::setTemplate() in /home/39552-42818.cloudwaysapps.com/jwzsyzgrdt/public_html/vendor/magento/framework/View/Element/Template.php on line 187

**Comment by Crossmotion** [comment]
@salelsol I had the same problem. In my case it was a bug in a module that was not compatible with Magento 2.1. yet. Dit you try disabling all modules yet?

**Comment by veloraven** [comment]
@salelsol thank you for your report.
Please provide description according to the template: with steps, actual result and expected result.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by abi2** [comment]
Having the same issue,
I'm on Magento 2.1.1
Experiencing this issue when sending order emails, or previewing order templates,
Already tried using default templates, same issue.

`[2016-09-19 17:02:19] main.CRITICAL: Exception: Warning: Missing argument 1 for Magento\Framework\View\Element\Template::setTemplate() in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php on line 187 in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php(187): Magento\Framework\App\ErrorHandler->handler(2, 'Missing argumen...', '/opt/bitnami/ap...', 187, Array)
#1 [internal function]: Magento\Framework\View\Element\Template->setTemplate()
#2 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Generator/Block.php(284): call_user_func_array(Array, Array)
#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Generator/Block.php(159): Magento\Framework\View\Layout\Generator\Block->generateAction(Object(Magento\Sales\Block\Order\Email\Items), 'setTemplate', Array)
#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#5 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#6 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/Template/Filter.php(405): Magento\Framework\View\Layout->generateElements()
#7 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/Template/Filter.php(387): Magento\Email\Model\Template\Filter->emulateAreaCallback()
#8 [internal function]: Magento\Email\Model\Template\Filter->layoutDirective(Array)
#9 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Filter/Template.php(141): call_user_func(Array, Array)
#10 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/Template/Filter.php(965): Magento\Framework\Filter\Template->filter('<!DOCTYPE html ...')
#11 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/AbstractTemplate.php(352): Magento\Email\Model\Template\Filter->filter('{{template conf...')
#12 [internal function]: Magento\Email\Model\AbstractTemplate->getProcessedTemplate()
#13 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/State.php(171): call_user_func_array(Array, Array)
#14 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Block/Adminhtml/Template/Preview.php(74): Magento\Framework\App\State->emulateAreaCode('frontend', Array)
#15 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Email\Block\Adminhtml\Template\Preview->_toHtml()
#16 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#17 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('content')
#18 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('content')
#19 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout->renderElement('content', true)
#20 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/view/adminhtml/templates/template/preview.phtml(16): Magento\Framework\View\Element\AbstractBlock->getChildHtml('content')
#21 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/bitnami/ap...')
#22 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/opt/bitnami/ap...', Array)
#23 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/opt/bitnami/ap...')
#24 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#25 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#26 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('preview.page.co...')
#27 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('preview.page.co...')
#28 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('preview.page.co...')
#29 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#30 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#31 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.content')
#32 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#33 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#34 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper')
#35 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#36 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#37 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('backend.page')
#38 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#39 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('root')
#40 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout->renderElement('root')
#41 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(37): Magento\Framework\View\Layout->getOutput()
#42 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#43 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#44 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#45 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#46 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Controller/Adminhtml/Email/Template/Preview.php(21): Magento\Framework\App\View->renderLayout()
#47 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Action/Action.php(102): Magento\Email\Controller\Adminhtml\Email\Template\Preview->execute()
#48 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#49 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#50 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->___callParent('dispatch', Array)
#51 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Email\\C...', 'dispatch', Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Array, 'adminAuthentica...')
#52 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#53 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#54 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Email\\C...', 'dispatch', Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Array, 'adminMassaction...')
#55 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#56 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#57 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Email/Controller/Adminhtml/Email/Template/Preview/Interceptor.php(26): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->___callPlugins('dispatch', Array, Array)
#58 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/FrontController.php(55): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#59 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#60 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#61 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#62 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#63 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#64 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#65 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#66 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#67 /opt/bitnami/apps/magento/htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#68 {main} [] []
[2016-09-19 17:58:15] main.CRITICAL: Magento\Framework\Exception\LocalizedException: Block items throws exception and cannot be rendered. in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/ExceptionHandlerBlock.php:45
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/Template/Filter.php(410): Magento\Framework\View\Element\ExceptionHandlerBlock->__call('getParentBlock', Array)
#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/Template/Filter.php(387): Magento\Email\Model\Template\Filter->emulateAreaCallback()
#2 [internal function]: Magento\Email\Model\Template\Filter->layoutDirective(Array)
#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Filter/Template.php(141): call_user_func(Array, Array)
#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/Template/Filter.php(965): Magento\Framework\Filter\Template->filter('<!DOCTYPE html ...')
#5 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Model/AbstractTemplate.php(352): Magento\Email\Model\Template\Filter->filter('{{template conf...')
#6 [internal function]: Magento\Email\Model\AbstractTemplate->getProcessedTemplate()
#7 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/State.php(171): call_user_func_array(Array, Array)
#8 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Block/Adminhtml/Template/Preview.php(74): Magento\Framework\App\State->emulateAreaCode('frontend', Array)
#9 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Email\Block\Adminhtml\Template\Preview->_toHtml()
#10 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('content')
#12 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('content')
#13 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout->renderElement('content', true)
#14 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/view/adminhtml/templates/template/preview.phtml(16): Magento\Framework\View\Element\AbstractBlock->getChildHtml('content')
#15 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/bitnami/ap...')
#16 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/opt/bitnami/ap...', Array)
#17 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/opt/bitnami/ap...')
#18 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#19 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('preview.page.co...')
#21 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('preview.page.co...')
#22 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('preview.page.co...')
#23 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#24 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#25 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.content')
#26 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#27 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#28 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper')
#29 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#30 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#31 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('backend.page')
#32 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#33 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('root')
#34 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout->renderElement('root')
#35 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(37): Magento\Framework\View\Layout->getOutput()
#36 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#37 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#38 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#39 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#40 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-email/Controller/Adminhtml/Email/Template/Preview.php(21): Magento\Framework\App\View->renderLayout()
#41 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Action/Action.php(102): Magento\Email\Controller\Adminhtml\Email\Template\Preview->execute()
#42 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->___callParent('dispatch', Array)
#45 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Email\\C...', 'dispatch', Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Array, 'adminAuthentica...')
#46 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#47 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#48 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Email\\C...', 'dispatch', Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Array, 'adminMassaction...')
#49 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#50 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#51 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Email/Controller/Adminhtml/Email/Template/Preview/Interceptor.php(26): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->___callPlugins('dispatch', Array, Array)
#52 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/FrontController.php(55): Magento\Email\Controller\Adminhtml\Email\Template\Preview\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#53 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#54 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#55 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#56 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#57 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 /opt/bitnami/apps/magento/htdocs/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#59 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#60 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#61 /opt/bitnami/apps/magento/htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#62 {main} [] []
`

**Comment by salelsol** [comment]
For me fixed with: https://github.com/magento/magento2/issues/5101
Discoveries

After searching a bit around, it looks like the json in the  isn't valid in the file vendor/magento/module-sales/view/frontend/email/order_new.html:



There is a trailing comma missing after "Shipping Description"
If I add a comma, the issue is fixed.

This issue also exists in the order_new_guest.html file, I haven't took the time to check all other email templates, but maybe some other ones might have the same problem?

Best Regards
Toni

**Comment by abi2** [comment]
Hi @salelsol,

I already added a comma, but still have this issue,
Any other troubleshooting tips?

Thank You

**Comment by abi2** [comment]
@Crossmotion thanks for your advise,
After disabling all modules it worked!

**Comment by salelsol** [comment]
- Just enable one by one and check if still works.

Best Regards
Toni

**Comment by Yogesh-Makwana** [comment]
Hello @salelsol 
There is problem with xml files, i've same problem on admin panel and i've copied all xml files from madule-sales to my custom theme and everything working fine,
Hope this help someone,
