### ISSUE TITLE
Catalog Category Link Widget issue

### ISSUE THREAD

**Issue by LittleCamel** [magento/magento2#5536]
When adding "Catalog Category Link" widget if you leave empty "Anchor Custom Text" it should use category name but it don't. It just display empty span inside anchor on fronted ( link to category is there but category name is not).

**Comment by tkacheva** [comment]
@LittleCamel Please add more details about magento version and environment you are using. Works correct on 2.1

![cat_link2](https://cloud.githubusercontent.com/assets/5603216/16685712/933e7968-4515-11e6-83e2-a6c7dd434d98.png)
![cat_link1](https://cloud.githubusercontent.com/assets/5603216/16685713/933e6b94-4515-11e6-985c-0e7fe45cb44e.png)

**Comment by LittleCamel** [comment]
Hi @tkacheva ,

I am actually having this problem with widget added through wysiswyg.

![magento-admin](https://cloud.githubusercontent.com/assets/10742480/16687260/c38b6c14-4517-11e6-9a27-d80a1b898880.png)

Sorry for confusion.

**Comment by tkacheva** [comment]
@LittleCamel Still works for me:
![cat_link3](https://cloud.githubusercontent.com/assets/5603216/16693718/30ec28bc-453f-11e6-9643-9e80241c1d53.png)
![cat_link4](https://cloud.githubusercontent.com/assets/5603216/16693720/30ed0b92-453f-11e6-9d89-8cdcface5ef6.png)

**Comment by LittleCamel** [comment]
Hi @tkacheva ,

I have just downloaded new instance of magento2 to check this one more time. 
Magento version is 2.1.0 and I download it via composer.

I still have this problem even on this clean instance.
My php version is PHP 5.6.11-1ubuntu3.4, maybe this will help.

Do you need some more info?

**Comment by tkacheva** [comment]
@LittleCamel could you add a screen of how the link looks on storefront please?

**Comment by tkacheva** [comment]
Internal issue MAGETWO-55384

**Comment by LittleCamel** [comment]
Hi @tkacheva ,

here are screenshots.
![admin-category-link](https://cloud.githubusercontent.com/assets/10742480/16843449/93a86a46-49e1-11e6-81e9-9595a211d97d.png)
![frontend-category-link-inspect](https://cloud.githubusercontent.com/assets/10742480/16843467/a17c6ce4-49e1-11e6-9c7f-11e7f3cfc866.png)

**Comment by jknipper** [comment]
This issue seems to be fixed in develop: https://github.com/magento/magento2/commit/c5a09d4c7056176a282ced37c3a186a284ae2de0

**Comment by Ctucker9233** [comment]
Fixed in develop but wasn't in latest 2.1.2 release.

**Comment by KingKarrow** [comment]
Is this commit in 2.1.3? My admin says 2.1.3 but I'm still getting the exact issue as @LittleCamel.

**Comment by eInyzant** [comment]
still not fixed in 2.1.4 release 👎

**Comment by johnny-longneck** [comment]
Still not fixed in 2.1.6 but commit mentioned above is working. When is this being released?

**Comment by nicolallias** [comment]
Not fixed in 2.1.7

**Comment by magento-engcom-team** [comment]
@LittleCamel, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by ntuong95** [comment]
Not fixed on 2.2.3 . Frontend is still empty where Catalog Category Link Widget presents.

**Comment by Ctucker9233** [comment]
@magento-engcom-team what are the commits for this issue?

**Comment by nicolallias** [comment]
For the 2.2-develop, maybe [11049](https://github.com/magento/magento2/commit/dc7ce8acf60961c1fbcd6628fbe42118ade2b7b4) ? (I do not know how to filter commits by description)
