### ISSUE TITLE
After upgrade to 2.1, unable to save edited configurable products

### ISSUE THREAD

**Issue by Modoperator** [magento/magento2#5555]
## Steps to reproduce
1. Upgrade from 2.07 to 2.10 using composer (edit - this happens with fresh install as well, see update below)
2. Create or view a configurable product
3. Edit the product.
## Expected result
1. Product would update as expected
## Actual result
1. Error in browser console appears - URL posted to via AJAX (ex.  `/admin/catalog/product/validate/id/269/type/configurable/store/0/set/4/?isAjax=true`) returns a 404.   No further files are called in the developer console.
2. Page processing appears to complete very very quickly, but in fact no update is made.
3. If the URL is re-posted (via Firefox developer console, or cut & paste in browser as GET request), it does return a 200 status at this point, but the form key is obviously not correct here.  
4. I noticed that this URL being posted to is different than it in v2.07, where the format is `admin/catalog/product/validate/id/8/set/9/active_tab/product-details/back/edit/?isAjax=true`. It seems like the new URL or routing is somehow not working correctly.

Also tried re-compiling, re-indexing, and cache cleaning with Magento CLI and in multiple browsers. 
## Updated Info
- Magento is installed on CentOS 6.7.
- Also tried a fresh install of 2.1 in a clean directory.  Created one product attribute - Size.  Created one product with size attribute.  Saved product, attempted to edit, exact same failure. 
- Is this a POST routing match failure issue with the new destination URL?  How would I check ?

**Comment by Modoperator** [comment]
Resolved this issue by alerting hosting company to issue. They did some research and made some updates to the mod_security settings, which resolved this.  The POST action to the URL was being blocked in the mod_security.   Hosting company is Nexcess.   This may affect others, leaving this here as solution for anyone else who runs into this.

**Comment by expandlab** [comment]
For anyone still having this issue, I had to contact my host to get them to remove a mod_security rule that was blocking the URL:

https://www.xyz.com/admin_ck/catalog/product/validate/id/293/type/virtual/store/0/set/11/key/e8d386c967c40e7879fc7497dc023cc92f1786asdf67541c08dc946bff231f/?isAjax=true

This was me attempting to convert a simple in to a configurable and the ajax request was 404ing.  This is indicative of the server preventing the save.
