### ISSUE TITLE
Setting SKU mask as empty crashes product Javascript in backend

### ISSUE THREAD

**Issue by JangriX** [magento/magento2#5618]
## Steps to reproduce

In magneto backend( Version 2.1), go to Catalog -> Catalog -> Product Fields Auto-Generation 
Set 'Mask for SKU' to empty.
Try adding new product
## Expected result

Page to add new product appears
## Actual result

Product add page gets stuck in loading.
Javascript crashes in import-handler.js due to mask being NULL, see screenshot attached.
![screenshot from 2016-07-13 15-52-09](https://cloud.githubusercontent.com/assets/9083334/16803932/e21e6516-4911-11e6-84e2-75625dfc34eb.png)

**Comment by antboiko** [comment]
Hello @Jangri , thanks for reporting. We've created internal ticket MAGETWO-55346 to track this issue.

Best,
Anton.

**Comment by zengoma** [comment]
+1
The issue occurred after I rolled back my database and media.

**Comment by sma09sjb** [comment]
Has this been fixed? We're experiencing a similar issue with the setting Mask for Meta Keywords when this is empty, i.e. we're not using the system value. 

I suspect all the fields in this config section are causing the same error but i don't know for sure.

This is not ideal as for SEO purposes we're we're hoping to have no meta keywords.

Any update would be greatly appreciated.

Thanks,

Sophie

**Comment by hyesungs** [comment]
Yes we had the exact same issue!!!

It was the SKU mask and it took days to figure out the reason. Please fix!

**Comment by veloraven** [comment]
This issue has already be fixed for develop branch.
It also has been fixed for version 2.1 in scope of internal ticket MAGETWO-56937. The fix will be available in one of the nearest releases

**Comment by piavgh** [comment]
Hi everyone, 

This bug is still existed in version 2.1.7 when Mask for SKU is empty
