### ISSUE TITLE
Magento 2.1 new product, without selecting configurable product, add child products as virtual instead than simple products

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5648]
Steps to reproduce
1. Admin->Products->Catalog
2. Press new product
3. Create the product adding configuration (e.g. for size and colors)
4. save

Expected result
1. A configurable product is created with simple products for size and colors

Actual result
1. The configurable product is added
2. All products for attributes are created as virtual products

There is no way to edit and change, also for more than one product, the product Type, in this case from virtual to simple.

The only way to do it is via script on the db.

**Comment by ifekaj** [comment]
Adding weight to the product should fix this

**Comment by andimov** [comment]
@PierAlex
Thank you for reporting!
Please, approve, that adding weight to the product fix this.

**Comment by PierAlex** [comment]
Hi @andimov,
i check it and it fixes but we are not managing weight. Is this a workaround?
Ale

**Comment by andimov** [comment]
@PierAlex 
It is ok if weight is required field. Please check your  product field settings.

**Comment by PierAlex** [comment]
@andimov 
Weight is not required. I can leave it blank.

**Comment by AVoskoboinikov** [comment]
Hi, @PierAlex 

Thanks for reporting this issue, I have created ticket for it in our internal JIRA (MAGETWO-57747). This issue will be closed after fix.

**Comment by pynej** [comment]
Same, we use this workaround for now:

```
update catalog_product_entity 
set type_id = 'simple'
where type_id = 'virtual'
and sku like '%-%'

select * from catalog_product_entity
where type_id = 'virtual'
and sku like '%-%'
```

**Comment by valibus** [comment]
When will you fix this problem ?
it has been created 3 month ago, if not already fixed it should have an highest priority.

**Comment by claridgicus** [comment]
@magento-team whats happening with this?

**Comment by claridgicus** [comment]
@magento-team is this resolved in your other tickets or?

**Comment by sammarcus** [comment]
Is the issue here that if a weight is not provided it falls back to creating the variation as a Virtual product?

**Comment by pynej** [comment]
I believe so @sammarcus.  I haven't checked to see if its been fixed in current version.

**Comment by PascalBrouwers** [comment]
Checked in latest develop version. Problem still exists.
Maybe you should make it more clear that having no weight creates virtual products.

**Comment by magento-engcom-team** [comment]
@PierAlex @PascalBrouwers 
Indeed, products without weight are automatically considered to be virtual. It is default behavior of Magento.
We will consider updating UX to highlight this.
Closing this ticket, as it is not a bug.

**Comment by sammarcus** [comment]
Since there are many ways to add products outside of the standard conventional web UI, it is quite easy to not take this for granted. I think it would be nice if the docs could also highlight this important distinction as right now language is just "aside from the absence of a weight field". Happy to propose more specific edits if you suggest you would like to approve them.

http://docs.magento.com/m2/ce/user_guide/catalog/product-create-virtual.html

**Comment by paengski13** [comment]
@magento-engcom-team How come this is not considered a bug? It automatically set the product type to virtual since there is no way to set the weight in the first place?

**Comment by sammarcus** [comment]
Just following up that I think the current language in the docs is unclear enough that this should be given some attention. Other users find it confusing enough that they believe current behavior is a bug.

**Comment by paengski13** [comment]
The mere fact that I set the product attribute weight default value to 1, I was assuming that it is supposed to populate that with a correct default weight.

This works as normal when manually creating a product.
