### ISSUE TITLE
cannot refresh lifetime statistics on best sellers on 2.0.7

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5736]
Hi,

On magento 2.0.7 install, it gives me an error refreshing lifetime stats for bestsellers and does not generate best sellers report. It will only show the report on the day i refreshed last day statistics. rest all days it will be empty.
![refresh_statistics](https://cloud.githubusercontent.com/assets/19605497/17025832/99dec79c-4f55-11e6-9644-7bbfb1827f95.png)
![best seller reports](https://cloud.githubusercontent.com/assets/19605497/17025839/a1cfed96-4f55-11e6-97a0-9e964ed6b3b9.png)

**Comment by andimov** [comment]
@nmallepally
Thank you for reporting!
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by nmallepally** [comment]
Hi @andimov , The issue is fixed, after i updated to 2.1 v . Thank you.

**Comment by andimov** [comment]
@nmallepally 
Thank you!
So I'm closing this issue as fixed.
Please feel free to reopen if you need.

**Comment by dexterityzx** [comment]
Hello,

I still have this issue on magento 2.0.7. Do I need to opened a new thread?

Best,
Tim

**Comment by NSanthoshpriya** [comment]
Hi,
I'm using 2.0.10 i'm getting this issue. Any way to fix this without updating to 2.1?

**Comment by caiyundong** [comment]
check the var/log/exception.log

My sales_order_item table contains product_id that I have deleted before, which causes the exception to insert into sales_bestseller_daily.

After removing those items, then it would be fine.
