### ISSUE TITLE
REST API PayPal does not call setExpressCheckout method

### ISSUE THREAD

**Issue by torayeff** [magento/magento2#5788]
When making orders through REST API and selecting payment method **paypal_express** there is issue with invalid token.
### Preconditions

1. Magento 2.0.7 
2. PHP 5.6.24
### Steps to reproduce

1) Create guest cart through REST API:
`Send POST request to http://example.com/index.php/rest/V1/guest-carts`

2) Add some product to cart:

```
Send POST request to 
http://example.com/index.php/rest/V1/guest-carts/GUEST_CART_ID/items with data:
{
      "cartItem": {
        "quote_id": "GUEST_CART_ID",
        "sku": "PRODUCT_SKU",
        "qty": 1
      }
}
```

3) Set shipping information:

```
Send POST request to
http://example.com/index.php/rest/V1/guest-carts/GUEST_CART_ID/shipping-information with data:
{
    "addressInformation": {
            "shipping_address": {
                "firstname": "FirstName",
                "lastname": "LastName",
                "street": [
                    "My Address"
                ],
                "city": "MyCity",
                "telephone": "+99312xxxxxxx",
                "country_id": "TM"
            },
            "shipping_method_code": "freeshipping",
            "shipping_carrier_code": "freeshipping"
        }
}
```

4) Make payment:

```
Send POST request to http://example.com/index.php/rest/V1/guest-carts/GUEST_CART_ID/payment-information with data:
{
    "email": "myemail@example.com",
    "paymentMethod": {
        "method": "paypal_express"
    },
    "billingAddress": {
        "firstname": "BillingFirstName",
        "lastname": "BillingLastName",
        "street": [
            "Billing Address"
        ],
        "city": "Billing City",
        "country_id": "TM",
        "telephone": "+99365xxxxxx"
    }
}

```
### Expected result

setExpressCheckout method must be called first. This is log when PayPal payment made through web site:

```
'url' => 'https://api-3t.paypal.com/nvp',
  'SetExpressCheckout' =>
  array (
    'PAYMENTACTION' => 'Sale',
    'AMT' => '10',
    'CURRENCYCODE' => 'USD',
    'RETURNURL' => 'http://example.com/paypal/express/return/',
    'CANCELURL' => 'http://example.com/paypal/express/cancel/',
    'INVNUM' => '2000000057',
    'SOLUTIONTYPE' => 'Sole',
    'GIROPAYCANCELURL' => 'http://example.com/paypal/express/cancel/',
    'GIROPAYSUCCESSURL' => 'http://example.com/checkout/onepage/success/',
    ...
    ...
    ...
    'ADDROVERRIDE' => 1,
    'METHOD' => 'SetExpressCheckout',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
  ),
  'response' =>
  array (
    'TOKEN' => 'EC-XXXXXXXXXXX',
    'TIMESTAMP' => '2016-07-24T21:09:52Z',
    'CORRELATIONID' => 'xxxxxxxxxxxxxx',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '23642192',
  ),
) {"is_exception":false} []

```
### Actual result

Instead I receive this error in response to request in 4th step:
`PayPal gateway has rejected request. Invalid token (#10410: Invalid token)`
And in log file this:

```
main.DEBUG: array (
  'url' => 'https://api-3t.paypal.com/nvp',
  'DoExpressCheckoutPayment' =>
  array (
    'TOKEN' => NULL,
    'PAYERID' => NULL,
    'PAYMENTACTION' => 'Sale',
    'AMT' => '10',
    'CURRENCYCODE' => 'USD',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
    'NOTIFYURL' => 'http://example.com/paypal/ipn/',
    'RETURNFMFDETAILS' => 1,
    'SHIPPINGAMT' => '0.00',
    'ITEMAMT' => '0.10',
    ...
    ...
    ...
    'SHIPTONAME' => 'Mynam',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'DoExpressCheckoutPayment',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
  ),
  'response' =>
  array (
    'TIMESTAMP' => '2016-07-24T21:59:26Z',
    'CORRELATIONID' => 'xxxxxxxxxxxxxxxx',
    'ACK' => 'Failure',
    'VERSION' => '72.0',
    'BUILD' => '23642192',
    'L_ERRORCODE0' => '10410',
    'L_SHORTMESSAGE0' => 'Invalid token',
    'L_LONGMESSAGE0' => 'Invalid token.',
    'L_SEVERITYCODE0' => 'Error',
  ),
) {"is_exception":false} []
```

Note:
I think the problem is with directly calling **DoExpressCheckoutPayment** instead of **SetExpressCheckout**.

**Comment by YevSent** [comment]
Hi, @torayeff, thanks for reporting.
Created internal ticket MAGETWO-56347 to investigate this issue.

**Comment by alena-marchenko** [comment]
Hi @torayeff 

Fix for MAGETWO-56347 ticket is already merged to develop branch.
Closing the issue, please feel free to create new one if the issue still reproducible for you.

**Comment by ccyfly** [comment]
followed MAGETWO-56347, but issue still exists. Any ideas?

**Comment by YevSent** [comment]
@ccyfly, this issue was fixed and merged to develop branch. On what branch do you have this issue?

**Comment by pranavrajs** [comment]
@joni-jones I'm on latest commit in `develop` branch. I'm getting an error as follows

```
paypal gateway has rejected request. invalid token (#10410: invalid token).
```

and exception is as follows

```
[2016-12-15 15:11:01] main.CRITICAL: exception 'Exception' with message 'Wrong order ID: "".' in /var/www/html/magento2/app/code/Magento/Paypal/Model/Ipn.php:140
Stack trace:
#0 /var/www/html/magento2/app/code/Magento/Paypal/Model/Ipn.php(106): Magento\Paypal\Model\Ipn->_getOrder()
#1 /var/www/html/magento2/app/code/Magento/Paypal/Model/Ipn.php(87): Magento\Paypal\Model\Ipn->_getConfig()
#2 /var/www/html/magento2/app/code/Magento/Paypal/Controller/Ipn/Index.php(56): Magento\Paypal\Model\Ipn->processIpnRequest()
#3 /var/www/html/magento2/var/generation/Magento/Paypal/Controller/Ipn/Index/Interceptor.php(24): Magento\Paypal\Controller\Ipn\Index->execute()
#4 /var/www/html/magento2/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Paypal\Controller\Ipn\Index\Interceptor->execute()
#5 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callParent('dispatch', Array)
#7 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Paypal\Controller\Ipn\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /var/www/html/magento2/var/generation/Magento/Paypal/Controller/Ipn/Index/Interceptor.php(39): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#9 /var/www/html/magento2/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Paypal\Controller\Ipn\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /var/www/html/magento2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#18 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#20 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#21 {main} [] []
```

**Comment by darkredz** [comment]
As of version 2.1.8 as well as 2.2 GA I am still getting the exact same error. Step to reproduce are the same as above mentioned

**Comment by htswordpress** [comment]
As of Magento ver. 2.1.7 I am still getting the exact same error. Step to reproduce are the same as mentioned by @torayeff

**Comment by vincentwinkel** [comment]
I'm facing this same issue with the exact same steps (v2.0.14).
Did someones found a solution? The docs is absolutely not clear.

**Comment by ketan3193** [comment]
We are still facing an issue with Payflow express with API (v2.2.*)
getting an error like "Field format error: Invalid Token"

**Comment by csooraj** [comment]
@ketan3193 @vincentwinkel 

We also had the same issue when we tried the below payload it worked

Endpoint: http://localhost:8888/Magento/index.php/rest/V1/carts/mine/payment-information

{
    "paymentMethod": {
        "method": "paypal_express",
        "additional_data": {
            "paypal_express_checkout_token" : "EC-xxxxxxxxxxxx",
            "paypal_express_checkout_redirect_required" : false,
            "paypal_express_checkout_payer_id" : "XXXXXXXXXX"
        }
    }
}


In order to get the payment token we used the paypal set express checkout api directly

Here is more details 

https://developer.paypal.com/docs/classic/express-checkout/ht_ec-singleItemPayment-curl-etc/?mark=Do%20Express%20Checkout%20Call#

When the customer approves the payment we will get the payer id in the returned url.

Hope this helps!
