### ISSUE TITLE
js validation messages translation not working in customer account

### ISSUE THREAD

**Issue by bjoern-quast** [magento/magento2#5820]
### Preconditions
1. Magento CE 2.1.0 without sample data is installed.
2. Splendit Internet's mage2-locale-de-de is installed
3. A custom language pack is installed for de_DE
### Steps to reproduce
1. Add translation to custom language pack:

> Minimum length of this field must be equal or greater than %1 symbols. Leading and trailing spaces will be ignored.,Mindestlänge dieses Feldes muss größer oder gleich %1 Zeichen sein. Führende oder nachfolgende Leerzeichen werden ignoriert.
1. Log in as customer in the German store
2. Under "change password", enter fewer than the required symbols
### Expected result
1. Message that appears:

> Mindestlänge dieses Feldes muss größer oder gleich 8 Zeichen sein. Führende oder nachfolgende Leerzeichen werden ignoriert.
### Actual result
1. Message that appears:

> Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.

Also true for many other validation messages in the customer account, as well as the register new customer page.

**Comment by jernejh** [comment]
Having the same problem in 2.1.1.

**Comment by mv-developer** [comment]
Having the same problem in 2.1.1.

**Comment by cuiyang000** [comment]
Having the same problem in 2.1.1.
It's also in registration page.

**Comment by gabs77** [comment]
Having the same problem in 2.1.2.

**Comment by OktarinTentakel** [comment]
Also see https://github.com/magento/magento2/issues/7363

Seems to be a timing problem with the init code in translation.phtml.

**Comment by tlygnersjo** [comment]
I'm having the same problem on 2.1.2

**Comment by ulftietze** [comment]
Issue still persist.

**Comment by davidverholen** [comment]
The problem seems to be that the original string in lib/web/mage/validation.js and vendor/magento/module-ui/view/base/web/js/lib/validation/rules.js is divided into two parts.

https://github.com/magento/magento2/blob/2.1/lib/web/mage/validation.js#L549

This way, the translation cannot be found during the static content deploy and the translation is not added to the js-translation.json file

The Problem is already solved in the develop branch: https://github.com/magento/magento2/blob/develop/lib/web/mage/validation.js#L549

**Comment by tsauerwein** [comment]
See #5509

> Fix will be delivered in 2.1.7, 2.0.15 and 2.2.0

https://github.com/magento/magento2/issues/5509#issuecomment-279491041

**Comment by marcosdsdba** [comment]
I have this problem in Magento 2.1.5. Problem persists !!!!

**Comment by kanduvisla** [comment]
Still persists in 2.1.7

**Comment by dmitriyprime** [comment]
Hi, @bjoern-quast . Thanks for reporting this issue. An internal ticked MAGETWO-55900 was created based on Your issue. You'll be informed as the issue is fixed.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71380

**Comment by simomBlack** [comment]
1. remove `js-translation.json` file  (`{Project}/pub/static/frontend/{theme}/default/{store_language}/js-translation.json`)

2. in your browser go to Local Storage and delete `mage-translation-file-version`

3. go to `{Project}/lib/web/mage/validation.js`, copy file and create new directory in `{Project}/app/design/frontend/{theme}/default` as `web/mage/` and paste the file
( your new file would be `{Project}/app/design/frontend/{theme}/default/web/mage/validation.js` )

4. do not use the `+` to concatenate strings in `$.mage.__(` ... `)`, if found one => delete and don't concatenate

5. add your translations in your `.csv` files

6. try and feed me results

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-72250

**Comment by magento-engcom-team** [comment]
@bjoern-quast, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
Hi @bjoern-quast the issue already fixed in 2.1.10 and will be available soon.

**Comment by exdiogene** [comment]
Now it is May 2020 and version 2.3.4 still have the same exact issue!

"Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored." cannot be translated. Neither other similar messages...

Is it normal to have issues like this dating from 4 years ago and still not resolved?

**Comment by koushikch7** [comment]
Issue persistent with Magento 2.3.0 as well
The registration page and customer login page validation messages are not translating.
