### ISSUE TITLE
"update" in category custom layout xml is ignored

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#5901]
I'm trying to add a custom handle through `<update handle="my_shiny_handle" />` inside the custom layout xml of a category.
### Preconditions
1. magento 2.1.0
### Steps to reproduce
1. add a custom handle in app/code/Myname/Myext/view/frontend/layout/my_shiny_handle.xml:

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
       <referenceBlock name="catalog.leftnav" remove="true" />
    </body>
</page>
```
1. edit a category and set the following layout update xml:
   `<update handle="my_shiny_handle" />`
2. cache clean
3. load the category in the frontend
### Expected result
1. the catalog.leftnav should be removed and thus the update handle used
### Actual result
1. the catalog.leftnav is not removed and thus the update handle not used

the layout xml update for categories itself seems to work - when the action is added directly to the category layout update xml, it works just fine:

```
<container name="body">
  <referenceBlock name="catalog.leftnav" remove="true" />
</container>
```

**Comment by heldchen** [comment]
if this is per design (as the category page's layout update is added quite late into the rendering stage), maybe the xml validator for categories (and cms pages) should disallow the `<update>` tag.

**Comment by AVoskoboinikov** [comment]
Hi, 
Thanks for reporting. I have created internal ticket MAGETWO-57937 to fix this bug. This issue will be closed after fix.

Thanks again

**Comment by koenner01** [comment]
probably related with https://github.com/magento/magento2/issues/7510

**Comment by scottsb** [comment]
@AzVo This same issue was reported on StackExchange, and I traced the root of the issue. You may want to note this in your internal ticket if it helps: http://magento.stackexchange.com/a/157773/567

**Comment by scottsb** [comment]
Unfortunately, this issue with `<update>`s applies to product pages as well, due to the bug being in the general `Merge` class. I have not tested, but I would expect it applies to CMS pages as well.

**Comment by eInyzant** [comment]
still in magento CE 2.18

**Comment by jaykobi** [comment]
It applies to CMS pages as well.

If you needs a quickfix you can use something like

```xml
<event name="layout_load_before">
        <observer name="add_layout_handles" instance="My\Module\Observer\AddHandles" />
</event>
```

```php
/** @var \Magento\Framework\View\Layout $layout */
 $layout = $observer->getEvent()->getLayout();

foreach ($layout->getUpdate()->asArray() as $updateStr) {
  if (preg_match('~<update handle="([a-z_-]+)"/>~', $updateStr, $matches)) {
    $layout->getUpdate()->addHandle($matches[1]);
    }
  }
```

**Comment by magento-engcom-team** [comment]
@heldchen, thank you for your report.
We've created internal ticket(s) MAGETWO-57937 to track progress on the issue.

**Comment by php4umagento** [comment]
Will that ever be fixed?

**Comment by ryan-copeland** [comment]
Any update on resolving this issue @magento-engcom-team?

**Comment by sergey-solo** [comment]
I wasn't able to reproduce it on 2.3-develop.

**Comment by heldchen** [comment]
@sergey-solo I have reproduced this issue on a vanilla 2.3.2 installation with sample data right now. I'm not seeing any commits to 2.3-develop that might suggest that this is fixed for a future version.

**Comment by sergey-solo** [comment]
@heldchen Can't reproduce on 2.3.2 sample data either.

default.xml (or catalog_category_view.xml)
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <update handle="my_shiny_handle" />
</page>
```
my_shiny_handle.xml
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="catalog.leftnav" remove="true" />
    </body>
</page>
```

The above works correctly. Would you please describe your steps in more detail?

**Comment by heldchen** [comment]
@sergey-solo please re-read the issue description carefully: this issue is about layout update defined in the categories via the database... this issue is *not* about layout updates that are defined within layout xml files, those always worked.

![image](https://user-images.githubusercontent.com/299636/61950129-43033f00-afad-11e9-971a-240e7bf6dcfd.png)

**Comment by magento-engcom-team** [comment]
Hi @heldchen. Thank you for your report. 
The issue has been fixed in magento/magento2#23918 by @sergey-solo in 2.3-develop branch
Related commit(s):
 - [4810c1de8d0770765c96648caf500d86769b7062](https://github.com/magento/magento2/commit/4810c1de8d0770765c96648caf500d86769b7062)
 - [a681509c5d4aae5986dc2fb906aab4a10a109928](https://github.com/magento/magento2/commit/a681509c5d4aae5986dc2fb906aab4a10a109928)

The fix will be available with the upcoming 2.3.4 release.

**Comment by heldchen** [comment]
thanks @sergey-solo!

**Comment by SomeGeek** [comment]
@sergey-solo Still having issues with this one. Just tried it.

I have a custom layout (Vendor/Theme/Magento_Cms/page_layout/some_custom_layout.xml). Inside it, I do various things (pull in 1column using update handle) and change the layout. In the admin section, I select this layout I just created. This is a specific layout for some CMS pages.

In the design pane, I add a block inside the container I created using the custom layout. However, this doesn't get processed at all. I'm stuck with a default CMS layout page. Selecting '1column' as layout style and defining 'update handle' in the content pane doesn't help.

The log:

`report.INFO: Broken reference: the 'this.custom.element' element cannot be added as child to 'cms.custom.container', because the latter doesn't exist [] []`

'cms.custom.container' is (not) added using the xml page layout, where it should be.

Update: So, after fiddling around some more, I notice the following:
- Using a predefined cms xml layout doesn't work: changes you make will not get applied. `<update handle="x" />` inside that file doesn't work. So if you want, for example, to remove a element, it won't. Fun fact: if you use update handle empty everything will be gone (as that's "empty"), apart from the page.main.title I tried to remove. Strange behavior.
- Selecting a predefined parent layout (such as 1column) in the CMS page settings and using "update handle" in the admin section with the above described file doesn't work.
- Selecting a predefined parent layout in the CMS page settings and using "update handle" in the admin section with the above described file _works_ if you _remove_ the "update handle" from that file. (Strange, the whole point is that you can select the template you want to have the content on the right place...)
- Everything after "update handle" in the admin seems to be ignored. Try, for example, to insert a block inside a referenceContainer you created with the custom xml layout.
