### ISSUE TITLE
Braintree javascript error on Chrome: Uncaught TypeError: FormNapper requires an HTMLFormElement element or the id string of one

### ISSUE THREAD

**Issue by flecxie** [magento/magento2#5903]
On a regular basis I am not able to enter Braintree (sandbox) credit card details in the checkout form when using Chrome, it also shows the following javascript error:

`js.braintreegateway.com/js/braintree-2.17.6.min.js:4 Uncaught TypeError: FormNapper requires an HTMLFormElement element or the id string of one.`

Just confirmed that I also get this error in a fresh vanilla installation of Magento CE 2.1.0.
### Steps to reproduce
1. Install Magento-CE-2.1.0_sample_data-2016-06-23-02-34-56 
2. Create a Braintree Sandbox account & enable Braintree in Magento backend (make sure you set merchant country)
3. Add product to cart, enter shipping details and on Review & Payments page select "Credit Card (Braintree)"
### Expected result
1. Being able to enter credit card details
### Actual result
1. Can't enter data in any of the credit card form fields
2. Console shows the following error: 

`js.braintreegateway.com/js/braintree-2.17.6.min.js:4 Uncaught TypeError: FormNapper requires an HTMLFormElement element or the id string of one.`

Note that I am not able to reproduce this all the time, I seem to get it sometimes & sometimes I don't see the error. I can usually make it re-appear by deleting browser history. I am using Chromium Version 51.0.2704.79 Ubuntu 15.10 (64-bit) but have seen the problem on Windows Chrome as well.

**Comment by YevSent** [comment]
Hi, @flecxie, could you reproduce it on the latest develop?

**Comment by flecxie** [comment]
@joni-jones: ack, i'll try on develop

I've also checked with Braintree, they suggested the following:

> That said, I was able to reproduce the issue by deleting the browser history, as you mentioned in the issue you posted on Magento’s Github. It seems like what is happening is that braintree.setup is running before the form is loaded. I’m not sure why this is only happening in Chrome, but it might have something to do with the way the DOM elements are being created on the page.

**Comment by flecxie** [comment]
@joni-jones: not able to replicate this on develop so far...
Any idea which change I should try to copy to my CE 2.1.0 installation to get it working there?

**Comment by YevSent** [comment]
This fixed in MAGETWO-54721 and fix should be available in Magento 2.1.1.

**Comment by flecxie** [comment]
Thanks @joni-jones !
Is there already an estimate release date for Magento 2.1.1?

**Comment by stripcurtains** [comment]
I'm having the exactly same issue. I was getting crazy already.

@joni-jones Is there any work around until the next version is released?

**Comment by flecxie** [comment]
FWIW: also seeing this issue occasionally in Firefox 47.0 with Magento CE 2.1.0

**Comment by broakenmedia** [comment]
Is this definitely a magento issue? As this is also a problem for me without it.

**Comment by stripcurtains** [comment]
@xbroak Thats definetely an issue in Magento 2.1. Maybe you are having it because you are using the same way it was implemented in Magento as well as the Braintree JS version.

**Comment by YevSent** [comment]
We are planning Magento 2.1.1 in the next few weeks.

**Comment by ghost** [comment]
I'm getting this too see [my stackoverflow question](http://stackoverflow.com/questions/38807955/uncaught-typeerror-formnapper-requires-an-htmlformelement-element-or-the-id-str) - but I'm not using magento. @flecxie have you been able to fix this?

**Comment by flecxie** [comment]
@silentsnooc: sorry, haven't fixed this yet in our 2.1.0 environment, but can see that it is fixed on the develop branch of magento2.

@joni-jones referred to MAGETWO-54721, the following commit looks most relevant: https://github.com/magento/magento2/commit/133dd81e9e5711c87c138c142959fd7acfea02af#diff-a17c2301affbcbcf17653bf0cc6a00c5

**Comment by flecxie** [comment]
After applying the following changes (partly copied from https://github.com/magento/magento2/commit/133dd81e9e5711c87c138c142959fd7acfea02af#diff-a17c2301affbcbcf17653bf0cc6a00c5) in my Magento CE 2.1.0 vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js the issue seems to have gone away:

```
 .../web/js/view/payment/method-renderer/cc-form.js | 47 ++++++++++++----------
 1 file changed, 25 insertions(+), 22 deletions(-)

diff --git a/vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js b/vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js
index 6990c1e..b311ea8 100644
--- a/vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js
+++ b/vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js
@@ -62,10 +62,22 @@ define(
                     },

                     /**
+                     * Device data initialization
+                     *
+                     * @param {Object} checkout
+                     */
+                    onReady: function (checkout) {
+                        braintree.checkout = checkout;
+                        braintree.onReady();
+                    },
+
+                    /**
                      * Triggers on any Braintree error
+                     * @param {Object} response
                      */
-                    onError: function () {
-                        this.paymentMethodNonce = null;
+                    onError: function (response) {
+                        braintree.showError($t('Payment ' + this.getTitle() + ' can\'t be initialized'));
+                        throw response.message;
                     },

                     /**
@@ -90,7 +102,7 @@ define(
                 this._super()
                     .observe(['active']);
                 this.validatorManager.initialize();
-                this.initBraintree();
+                this.initClientConfig();

                 return this;
             },
@@ -122,11 +134,11 @@ define(
              * @param {Boolean} isActive
              */
             onActiveChange: function (isActive) {
-                if (!isActive || this.isSingleUse()) {
+                if (!isActive) {
                     return;
                 }

-                this.reInitBraintree();
+                this.initBraintree();
             },

             /**
@@ -146,17 +158,9 @@ define(
             },

             /**
-             * Create Braintree configuration
+             * Init Braintree configuration
              */
             initBraintree: function () {
-                this.initClientConfig();
-                braintree.config = _.extend(braintree.config, this.clientConfig);
-            },
-
-            /**
-             * Re-init Braintree configuration
-             */
-            reInitBraintree: function () {
                 var intervalId = setInterval(function () {
                     // stop loader when frame will be loaded
                     if ($('#braintree-hosted-field-number').length) {
@@ -165,6 +169,12 @@ define(
                     }
                 }, 500);

+                if (braintree.checkout) {
+                    braintree.checkout.teardown(function () {
+                        braintree.checkout = null;
+                    });
+                }
+
                 fullScreenLoader.startLoader();
                 braintree.setConfig(this.clientConfig);
                 braintree.setup();
@@ -189,6 +199,7 @@ define(
                     onReady: function (checkout) {
                         braintree.checkout = checkout;
                         this.additionalData['device_data'] = checkout.deviceData;
+                        braintree.onReady();
                     }
                 };

@@ -309,14 +320,6 @@ define(
                 });

                 return false;
-            },
-
-            /**
-             * Check if Braintree configured without PayPal
-             * @returns {Boolean}
-             */
-            isSingleUse: function () {
-                return window.checkoutConfig.payment[this.getCode()].isSingleUse;
             }
         });
     }
-- 
2.7.4.1.g5468f9e
```

Attached the complete file here as well for convienience: [cc-form.js.txt](https://github.com/magento/magento2/files/408755/cc-form.js.txt)

**Comment by stripcurtains** [comment]
@flecxie worked for me. Thanks a lot man!

**Comment by alena-marchenko** [comment]
Hi @flecxie 

Closing the issue, since it is resolved already. Please feel free to create new one if you experience further issues.

**Comment by janepoltoratskaya** [comment]
the issue is still present even with provided fix. Now the input fields are empty and not available for entering the information.

**Comment by lucscu** [comment]
@flecxie Your attached files is wrong, is different from [file fixed](https://github.com/magento/magento2/blob/133dd81e9e5711c87c138c142959fd7acfea02af/app/code/Magento/Braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js).
Please remove it from your post and let the user download github original.

**Comment by janepoltoratskaya** [comment]
@LucScu the original file has an issue as well. If your Braintree configuration doesn't include PayPal and the Braintree is only payment method, the CC fields are not initialized.

**Comment by lucscu** [comment]
@janepoltoratskaya i just see it now. So how we have to fix it? with flecxie file it works correctly?

**Comment by janepoltoratskaya** [comment]
@LucScu I've created a ticket #6827 about that case with my solution. It works on our installation. Feel free to review it.
