### ISSUE TITLE
Checkout address data vanishes despite stored in database quote_address

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#5959]
### Preconditions

1. Install M2 2.X (I'm using 2.1.0) 
2. Install any sample data to have products
3. Go to the frontend and add a product to the cart
4. Go to checkout and use the guest checkout
5. Fill out the address form and click next to proceed to the payment method, but do not submit the order.
6. Open developer console of Chrome Browser, then click "Hard reload and empty cache"
7. Checkout reloads with blank address fields.

Steps 6. and 7. can be skipped if you use a 3rd party payment module which redirects you after the checkout to the payment provider. If then your payment fails and you get redirected to the checkout/cart page, the address fields in the checkout are also empty.
### Expected result

- Despite a hard reload with empty cache (not empty cookies) the checkout address form must be pre-filled with the already entered data from a previous try.
- Same after a failed payment which redirects you back into the checkout.
### Actual result

1. Empty address fields
### Hints

All address data has been successfully stored in the `quote_address` table but Magento fails to load the data and refill the browsers localStorage with the key `mage-cache-storage`.

**Comment by SchumacherFM** [comment]
Still relevant in M2.1.1

**Comment by matthewscalf** [comment]
Any update on this? I am seeing this also in a site that is supposed to launch asap.

**Comment by SchumacherFM** [comment]
It usually takes 3-5 months until you can see here a fix.

**Comment by TommyKolkman** [comment]
Can confirm that this is happening in 2.1.1 as well.

**Comment by PieterCappelle** [comment]
Still relevant in 2.1.2. This is the checkout page guys...

**Comment by MagePsycho** [comment]
In my case mini cart is empty (though items are available in the cart page) when switching the store. Seems it has to do something with localStorage / mage-cache-store.

**Comment by twistedindustries** [comment]
Same thing if you get a declined transaction using something with authorize.net when the page reloads the address is missing.

**Comment by SchumacherFM** [comment]
Not fixed in 2.1.3

**Comment by twistedindustries** [comment]
@SchumacherFM Yeah I've been working on a fix.  It seems like its a session or cache thing.  I'll share my fix as soon as I find it.

**Comment by surfer190** [comment]
@twistedindustries Do you have an update on this?

Is seems that `/vendor/magento/module-checkout/Model/CompositeConfigProvider.php` is returning returning all the checkout info except `customer` from:

```
    public function getCheckoutConfig()
    {
        return $this->configProvider->getConfig();
    }
```

from `OnePage.php`

**Comment by 7sbg** [comment]
Still not fixed in 2.1.5 :(

**Comment by AlexWorking** [comment]
Hello, @SchumacherFM. We could not reproduce Your issue on the develop version, which for case is 2.1.7. If You are still able to reproduce it on that version, please tell us about it. Thanks for Your reporting.

**Comment by SchumacherFM** [comment]
Thanks for looking into it!

I won't have the time in the next couple of weeks to reproduce this issue ...

**Comment by wintermute-84** [comment]
Can anyone using 2.2 rc confirm that this is fixed?
The bug is still present on 2.1.9 
![screen shot 2017-09-20 at 13 28 51](https://user-images.githubusercontent.com/3521295/30636861-b11712c8-9e07-11e7-9e00-2db17fa93397.png)

**Comment by kapil019** [comment]
In Magento 2.1 I am facing same issue.
Can anyone help in this?

**Comment by wintermute-84** [comment]
@kapil019 check the referenced issue:
https://github.com/magento/magento2/issues/11247

Fixed only in 2.2.4

**Comment by kapil019** [comment]
OK Thanks @wintermute-84

**Comment by richardechidna** [comment]
Does anybody know where can I find the code for this fix please?

**Comment by kapil019** [comment]
@richardechidna I have fixed this in https://github.com/magento/magento2/issues/11197#issuecomment-359785930
Please check my commit
https://github.com/kapil019/magento2/commit/108c3fac3d5bde3353433199359582e7bf7cea0f

**Comment by peterjaap** [comment]
@kapil019 @wintermute-84 unfortunately that only fixes the issue when using the step navigator. Doing a (hard) refresh like @SchumacherFM explains in the first post is still not fixed.

**Comment by ron-sooryen** [comment]
Related tickets:
https://github.com/magento/magento2/pull/11958
https://github.com/magento/magento2/issues/6817
https://github.com/magento/magento2/issues/16149
https://github.com/magento/magento2/issues/5959
https://github.com/magento/magento2/issues/13690
