### ISSUE TITLE
Product::getExtensionAttributes() returns orphaned empty instance if not initialized

### ISSUE THREAD

**Issue by schmengler** [magento/magento2#5979]
### Preconditions
1.  Magento CE 2.1.0
### Steps to reproduce

1.  Load a product list from the product repository
2.  Load stock item from stock registry and attach it to the extension attributes

```
$product->getExtensionAttributes()->setStockItem($stockItem);
```
1. Inspect stock item

```
var_dump($product->getExtensionAttributes()->getStockItem());
```
### Expected result

1. I see a dump of `$stockItem`
### Actual result

```
NULL
```
#### Explanation

if the extension attributes were not loaded before, `getExtensionAttributes()` **always** returns an empty instance:

```
public function getExtensionAttributes()
{
    $extensionAttributes = $this->_getExtensionAttributes();
    if (!$extensionAttributes) {
        return $this->extensionAttributesFactory->create('Magento\Catalog\Api\Data\ProductInterface');
    }
    return $extensionAttributes;
}
```
#### Possible Solution

```
public function getExtensionAttributes()
{
    $extensionAttributes = $this->_getExtensionAttributes();
    if (!$extensionAttributes) {
        $extensionAttributes = $this->extensionAttributesFactory->create('Magento\Catalog\Api\Data\ProductInterface');
        $this->_setExtensionAttributes($extensionAttributes);
    }
    return $extensionAttributes;
}
```

**Comment by staniag** [comment]
Any news on this?

**Comment by magento-engcom-team** [comment]
@schmengler, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by Ttzombor** [comment]
Still facing that issue
https://github.com/magento/magento2/commit/375132a81b95fafa4a03a17b72dbacdc90afa745#diff-56d044692f579051647a8284ff39cc0eR165
