### ISSUE TITLE
Schema for language package does not allow vendor name to contain numbers

### ISSUE THREAD

**Issue by pascaladriaansen** [magento/magento2#6016]
### Preconditions

I am using Magento 2.1.0 in developer mode on a hypernode-vagrant local development environment. I have already developed some modules with the vendor name 'lab51', and am now trying to make a language package that uses the same vendor name. Unfortunately this results in the following error on my storefront:

```
Invalid XML in file /data/web/magento2/app/i18n/lab51/nl_nl/language.xml: Element 'vendor': [facet 'pattern'] The value 'lab51' is not accepted by the pattern '[a-zA-Z\-_]+'. Line: 4 Element 'vendor': 'lab51' is not a valid value of the atomic type 'vendorType'. Line: 4
```

For some reason the xsd schema doesn't allow it.
### Steps to reproduce

1. Create a language package with the necessary files (`language.xml, registration.php, nl_NL.csv, composer.json`)
2. Enter a name containing numbers in the `<vendor>` node in `language.xml`, e.g. `<vendor>lab51</vendor>`
3. Upload language package files to `app/i18n/<vendor>/nl_nl/`
4. Reload storefront and receive error mentioned above.
### Expected result

1. Language pack should load just fine without showing any errors.
### Actual result

1. Invalid XML error appears, language package is not loaded.

Why does the xsd schema not allow numbers in vendor names for language packages?

**Comment by NathanDayMF** [comment]
On Magento V2.1.7 and have this same error Message, any planned amendments to the Vendor pattern

**Comment by magento-engcom-team** [comment]
@pascaladriaansen, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by u12206050** [comment]
I still have this issue from the norwegian language pack the vendor is `<vendor>day4code</vendor>` Running Magento 2.2.2
