### ISSUE TITLE
Error while enabling module via Component Manager (CE 2.1)

### ISSUE THREAD

**Issue by hrle991** [magento/magento2#6078]
I have downloaded and installed a fresh copy of Magento 2.1 from Magento official website. Then I tried to enable several different modules in admin via 'Web Setup Wizard' --> 'Component manager' but got the same error every time. I tried on several machines with Magento 2.1 installation and the same error always occurs. 
### Preconditions
1. Magento CE 2.1,0 
2. PHP 5.6.24, MySQL 5.6.31
### Steps to reproduce
1. Put module files in [magento_installation]/app/code/[vendor]/[module_name] or do the step no. 3
2. Log into Magento 2.1 admin and go to System -> Web Setup Wizard -> Component Manager
3. Optionally you can sign in with a Magento Marketplace account to sync your bought modules
4. Find your newly added\bought module in modules grid and choose 'Enable' Action 
### Expected result
1. Magento should offer you to do a backup and go to a maintenance mode 
2. Disable all cache types 
3. Enable module 
4. Do a setup:upgrade 
5. Enable previously disabled cache types
6. Recompile static files
### Actual result

1. Magento fails to enable previously disabled cache types and module installation fails: 

_An error occurred while executing job "setup:cache:enable ["config layout block_html collections reflection db_ddl eav customer_notification full_page config_integration config_integration_api translate config_webservice"]": Could not complete setup:cache:enable ["config layout block_html collections reflection db_ddl eav customer_notification full_page config_integration config_integration_api translate config_webservice"] successfully: The "command" argument does not exist._

![error](https://cloud.githubusercontent.com/assets/17128368/17523451/e93efdde-5e5a-11e6-9fe1-58f1683599c9.jpg)

[error_log.txt](https://github.com/magento/magento2/files/409358/error_log.txt)

I have done some error tracing and I believe the problem is in execute() method located in setup\src\Magento\Setup\Model\Cron\JobSetCache.php. If I leave(comment) out IF conditions on line 67 and 70 then Magento manages to do cache:enable and module installation is successful.

**Comment by dthampy** [comment]
An internal Jira ticket has been created ->MAGETWO-56816.
Thanks for your detailed bug report

**Comment by gabriel-sf** [comment]
Does anyone have any update on this? or should we try the hack by @hrle991 ?

**Comment by dthampy** [comment]
This issue has been resolved internally and will be available in a future release.

Thanks.

**Comment by mom4751** [comment]
Hi,
i have just tried with Magento CE 2.1.1 and the issue is still here.
So the fix has not been implemented yet :-(

**Comment by f00stx** [comment]
I'm also having this issue, and have recently done an upgrade to CE 2.1.2. Is there a fix for this somewhere? This was a clean install from a version downloaded last week, which I upgraded to 2.1.2 today, and then tried to install an extension via the web setup wizard.

I didn't think to capture the output before closing the tab but it closely matches the output @hrle991 pasted in the ticket.

**Comment by bad-for-zathras** [comment]
Still present in 2.1.5. It was reported on 3. Jun 2016 (#4853) and again on 9. Aug 2016. No patch landed in the code after 9 months?

**Comment by mom4751** [comment]
@bad-for-zathras
Since this problem occured, i started to manage Magento 2 with Composer (and i think almost everyone does the same).
I never tried before because i thought it could not work on a shared/managed hosting without root privileges.
I was wrong: you just need an SSH connection.
Now i heavily use Composer to add and remove plugins and upgrade the Magento core too.
I got to the point where i have forgot the web setup wizard existence.

**Comment by justanewbie00** [comment]
I am using CE 2.1.6 and the problem still exist. I tried to enable the module I created and this error occured. Is there any solution for this?

**Comment by drpit** [comment]
Hello,
I use CE 2.1.7 and this issue still exist

**Comment by magento-engcom-team** [comment]
@hrle991, thank you for your report.
The issue is already fixed in 2.1.0, 2.2.0
