### ISSUE TITLE
Magento 2 reorder function not working properly

### ISSUE THREAD

**Issue by simonxy** [magento/magento2#6121]
### Preconditions

1. Magento 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, PHP 7.0.x, MySQL 5.6.x
2. Any browser
### Steps to reproduce

1. login as customer, navigate to Account Dashboard, or Order List;
2. On any existing order item, click "Reorder" button;
3. The result shopping cart page shows item from previous order is added. however the bag icon is not updated, and popup minicart doesn't have the reorder item;
### Expected result

1. The bag icon and minicart should be updated accordingly.
### Screenshots

1. [Resulting shopping cart](http://pasteboard.co/7u8cHvgdK.png)
2. [Customer Dashboard, Order List](http://pasteboard.co/7uawoJsVD.png)
   3, [Link to demo store](http://magento2.demo.ubertheme.com/customer/account/)

**Comment by apurv-anand** [comment]
+1. Our platform: M2.1
Please fix on priority or provide a workaround.

![blank](https://cloud.githubusercontent.com/assets/17824537/17618560/0edb1114-609e-11e6-9a07-c0645e4613a9.PNG)

**Comment by apurv-anand** [comment]
Please assign and act on this on priority. This looks like a major functional issue.

**Comment by katmoon** [comment]
Hi @simonxy @apurv-anand 

Thank you for reporting the issue. It is reported as `MAGETWO-54964` internally.

Thanks,
Kateryna.

**Comment by sshymko** [comment]
Experiencing the same issue here on Magento 2.1.
The mini cart does not get updated in result of the reorder.
Browser's local storage where the mini cart is cached only gets refreshed upon POST/PUT requests.
However, the reorder action is a regular link that results in an ordinary GET request.

**Comment by katmoon** [comment]
The issue is resolved and will be available in 2.1.2 patch version.

**Comment by brideo** [comment]
Hey @katmoon,

Is there a commit or work around we can use until the next release?

**Comment by katmoon** [comment]
Hi @brideo 

The fix will be available with the next non-security patch release.

**Comment by sshymko** [comment]
@brideo,

I don't have access to the official patch, but I can share the workaround we use.
The idea is to listen to the reorder link clicks and invalidate the customer data in the local storage.

**The Workaround**
Add the following JavaScript to pages with the reorder links (via layout handle `customer_account`):

``` js
require([
    'jquery',
    'Magento_Customer/js/section-config',
    'Magento_Customer/js/customer-data',
    'domReady!'
], function ($, sectionConfig, customerData) {
    'use strict';

    /**
     * Elements - Reorder links
     */
    var s = [
        '.sales-order-view .order-actions-toolbar .actions .reorder',       // sales-order-view
        '.sales-order-history .table-order-items .actions .order',          // sales-order-history
        '.customer-account-index .table-order-items .actions .order',       // customer-account-index
    ];

    /**
     * Events listener
     */
    $(s.join(', ')).on('click', function(event) {
        var sections;

        // anchor contains span, target may be span instead of anchor
        var el = event.target.href ? event.target : event.target.parentElement;

        // check if this is really a redirect link
        if (el.href.match(/reorder/i)) {
            sections = sectionConfig.getAffectedSections(el.href);

            if (sections) {
                customerData.invalidate(sections);
            }
        }
    });

});
```

Please note that the official unreleased fix is likely very different from the workaround above. It probably changes the request method from `GET` to `POST` to match semantics of the operation: entity creation rather than retrieval.

**Comment by brideo** [comment]
Brilliant thanks @sshymko!

I will make a note to remove it when the next version of Magento is released.

**Comment by veloraven** [comment]
This issue was fixed in 2.1.2. 2.0.10 and develop branch.
Closed.

**Comment by Bartlomiejsz** [comment]
@veloraven can you please bring us a link to the commit where this issue was fixed in 2.1 branch?

**Comment by AndreKlang** [comment]
@veloraven @katmoon 
Can you please do as @Bartlomiejsz asked and supply a reference to where/how this was fixed? Also in what release was this fixed in?

I'm still experiencing this on 2.1.5. I'm guessing that the previous (bad) vendor who made this site overwrote something, so the problem still exists..

**Comment by JMLucas96** [comment]
Issue still exists on magento 2.1.8, old prices not updating when reordering...
Any solution?

**Comment by JMLucas96** [comment]
Similar issue here #30663
