### ISSUE TITLE
Simple product videos display the thumbnail image rather than the embedded video player.

### ISSUE THREAD

**Issue by ntoombs19** [magento/magento2#6360]
### Preconditions

1. Magento Version 2.1
### Steps to reproduce

1. Add a video to a configurable product and one of the simple products for that configurable product
2. View that product on the frontend.
3. Select the product configuration to display the simple product for which the video was added.
4. Select the video slide in the gallery and try to play the video
5. The slide will open up in full screen rather than playing the video.
### Expected result
1. The video should play normally on the simple product like it does on the configurable product.
### Actual result

1. http://take.ms/YrP7q

**Comment by picamator** [comment]
@ntoombs19 Thanks for reporting.
We've created internal ticket MAGETWO-57995 to fix it.

**Comment by PetraSwed** [comment]
Still not working in 2.1.2. Any plans to fix this?

**Comment by AgenturSchroeder** [comment]
It is still broken. I can't use youtube or vimeo. Is there a workaround untill we wait?

**Comment by gavin9517** [comment]
Still not working in 2.1.3.

**Comment by erikhansen** [comment]
@Magento - I have a couple of merchants experiencing this issue. Please provide an ETA on a fix.

**Comment by Danielc3** [comment]
This is still an issue for me in 2.1.6. Has anyone made any progress with this?

**Comment by magento-engcom-team** [comment]
The issue has been fixed in MAGETWO-57995. Release 2.2.0
@ntoombs19 thank you for report

**Comment by nmallepally** [comment]
Hi,

I have updated to 2.2.2 version from 2.1.8 but the bug still appears.
it still shows as an image instead of a youtube embedded video.

on the load it shows up as video loading with video symbol and then it jumps and comes up as an image.
![after loading](https://user-images.githubusercontent.com/19605497/34989180-73e0681e-fab9-11e7-8fcb-5411e4392e72.PNG)


Is there any workaround or quick fix for this issue?.
it does not even work on updating to 2.2.2 v of Magento.

Environment:
php 7.0.24
Debian Jessie
Mysql 5.7
Apache 2.4


**Steps to reproduce:**
Upgrade from Magento 2.1.8v to Magento 2.2.2v
The video does not display on front-end for the configurable product.


Regards,
Navya

**Comment by pradeepkanaka** [comment]
Im also facing the same issue, configured product's child product video is not playing. It displays as image
