### ISSUE TITLE
Cart Price Rules Not Saving after 'Apply the rule only to cart items'

### ISSUE THREAD

**Issue by neildavey** [magento/magento2#6555]
1.  Magento 2.1.0
2. Production Site

Saving a New Cart Rules works OK but when I complete the next steps:
Apply the rule only to cart items matching the following conditions
1. If ALL of these conditions are TRUE:
2. Select any of the options in the dropdown
Result:
Spinning Wheel Rotates and the screen returns to the dashboard without saving the condition

If I start a new rule from scratch and include the condiiton - the whole rule doesnt save.

The expected result should be that the new condition is applied.

**Comment by miakusha** [comment]
Hi @neildavey, thank for report, issue was fixed in #5526

**Comment by darkredz** [comment]
This problem actually still exist in magento 2.1.9
the spinner comes in and screen still redirects to dashboard without saving the Condition added.

https://magento.stackexchange.com/questions/156872/i-am-unable-to-apply-condition-on-cart-price-rule

**Comment by darkredz** [comment]
It seems that when selected a condition from the dropdown box. the URL where the page is posting to (ajax) is Not Found 
<shopurl>/sales_rule/promo_quote/newConditionHtml/form/sales_rule_formrule_conditions_fieldset_2/form_namespace/sales_rule_form/key/70b5eb59b93515c52dcb77533557d2486b968ad9f0ab79c0ba8af37242ac3bf5/?isAjax=true
