### ISSUE TITLE
Configurable product old price with taxes displayed wrong

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#6729]
I have a store for EU, by law we need to show all prices with VAT included. In the admin we enter prices without tax, we have tax rule to add 20% VAT, in configuration everything es set up properly, so all prices include tax.

When we apply catalogue rule for category to have 20% discount all prices are shown correctly except configurable product old price- it is old price without tax.
### Steps to reproduce
1. create configurable product without tax, price is defined for each sku
2. create tax rule 20%
3. apply this tax rule to product
4. in tax settings set all values to display prices with tax
### Expected result
1. Configurable product old price should be child price without discount and with tax
### Actual result
1. for simple product old price is correct, if it is 100£ in admin and tax is 20%, on front end it is displayed as 96$ (regular price 120£) - 20% catalog rule discount applied
2. for configurable product that has prices for child products final price is correct, but old price is old price without VAT applied.

here is simple product and configurable, both has price 100$, 20% tax and 20% catalog rule discount. final price is correct for both, old price is not: 
http://i.imgur.com/qP8etV6.png

**Comment by yangsystem** [comment]
I have the same problem but I figured a workaround.
If you set the product as a virtual product you have this problem: price with tax is the same as price without tax. The code does not apply tax on it.
BUT:
if you make the same product as a simple product (just check this item has weight and fill 0 as weight) all work's out. And weight 0 is the same as virtual product for us human's. 

 I think the problem is somewhere in virtual product's logic.

**Comment by veloraven** [comment]
@kandrejevs thank you for your report.
Please identify which version of Magento you are running.

**Comment by kandrejevs** [comment]
@veloraven this bug is present on 2.1.1 CE and EE editions.

here is my tax configuration, tax rule is 20%

```
INSERT INTO `core_config_data` (`scope`, `scope_id`, `path`, `value`)
VALUES
    ('default', 0, 'tax/classes/wrapping_tax_class', '0'),
    ('default', 0, 'tax/calculation/apply_after_discount', '0'),
    ('default', 0, 'tax/notification/ignore_discount', '1'),
    ('default', 0, 'tax/notification/ignore_price_display', '0'),
    ('default', 0, 'tax/calculation/discount_tax', '1'),
    ('default', 0, 'tax/calculation/cross_border_trade_enabled', '0'),
    ('default', 0, 'tax/defaults/country', 'GB'),
    ('default', 0, 'tax/defaults/postcode', NULL),
    ('default', 0, 'tax/display/type', '2'),
    ('default', 0, 'tax/display/shipping', '2'),
    ('default', 0, 'tax/cart_display/price', '2'),
    ('default', 0, 'tax/cart_display/subtotal', '2'),
    ('default', 0, 'tax/cart_display/gift_wrapping', '1'),
    ('default', 0, 'tax/cart_display/printed_card', '1'),
    ('default', 0, 'tax/cart_display/grandtotal', '1'),
    ('default', 0, 'tax/sales_display/gift_wrapping', '1'),
    ('default', 0, 'tax/sales_display/printed_card', '1');
```

**Comment by bordeo** [comment]
@veloraven we find this bug on last magento version 2.1.3 CE. 
Like @kandrejevs I used catalog promo with 20% discount and old-price show price without tax.

**Comment by firstred** [comment]
I managed to show the correct prices by editing the file `/vendor/magento/module-configurable-product/Pricing/Price/ConfigurableRegularPrice.php`.
Replace (line ~89):
```php
    public function getAmount()
    {
        return $this->getMinRegularAmount();
    }
```
with
```php
    public function getAmount()
    {
        return $this->getMaxRegularAmount();
    }
```
At this moment I have no idea why it works for me and whether it will help in your case, but...
<img src="http://i.imgur.com/DGzSZ8h.png" height="200">

**Comment by 6ui11em** [comment]
Following the suggestion of @firstred I fixed it changing the loop of doGetMinRegularAmount function from:

foreach ($this->lowestPriceOptionsProvider->getProducts($this->product) as $product) {

to

foreach ($this->getUsedProducts() as $product) {

Hope this quick fix helps someone else.

**Comment by PierAlex** [comment]
Same problem for me on Magento 2.1.2 CE, the workarounds above do not take effects.

**Comment by jghaanstra** [comment]
Any news concerning this issue, it's still present in Magento 2.1.5. For me this is a pretty nasty bug. By law I'm obligated to show prices including tax in my country. Due to this bug I'm not able to and I'm violating the law.

**Comment by Turv** [comment]
@jghaanstra I'm in the same boat, and this is a pretty serious bug to have been in the core for 7 months with no workarounds (The above don't work for me). I believe this worked in 2.0.6 so something has changed..

**Comment by Turv** [comment]
@kandrejevs A fix has been put together by @jghaanstra and @maderlock here that resolves this issue until a permanent fix is available in the core on a future release.

https://github.com/jghaanstra/magento-grouped-product-tax-fix

**Comment by zamocom** [comment]
Sorry, I have insert the fix on my site and all commands works correctly but I have the same problem again. Is there another step? Thanks

**Comment by zamocom** [comment]
Works properly, but now I enter the price of the product and this takes into account the fees, if I insert 100 eur and the 20% fee the product result is not 120 eur but 100, practically the price I insert I already takes into account the fee And is not added after based on the percentage of the tax itself, is it correct?

**Comment by oleg-onufer** [comment]
Hi @kandrejevs.
Program logic for the regular price of the configurable  product was changed:
"Regular price for Configurable product should be shown for product page, but not be for list of products"

**Comment by korostii** [comment]
> Program logic for the regular price of the configurable product was changed:
> "Regular price for Configurable product should be shown for product page, but not be for list of products"

Hi @oleg-onufer, 
I wasn't able find any info about such a change in the devdocs.  Is it on the release notes somewhere?

To be perfectly clear, I'm interested to know when was this change introduced and whether this new behavior can be reverted via settings, so a link to a certain commit would also do. 

It seems to be a breaking change, is it not?

**Comment by korostii** [comment]
Hi @veloraven, I can see that you've added a "needs update" label.
Could you please clarify what kind of additional information do you require?

**Comment by rishabhrkrai** [comment]
I still facing this issue in 2.1.7

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70491

**Comment by magento-engcom-team** [comment]
@kandrejevs, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
@kandrejevs, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
Hi @yangsystem the issue has been fixed in 2.2-develop branch and will be available with release 2.2.1 soon

**Comment by magento-engcom-team** [comment]
Hi @kandrejevs. Thank you for your report. 
The issue has been fixed in magento/magento2#13490 by @simpleadm in 2.1-develop branch
Related commit(s):
 - [40ddfc0963e8afd7329f76ebf2e0b2cdb57ec77d](https://github.com/magento/magento2/commit/40ddfc0963e8afd7329f76ebf2e0b2cdb57ec77d)

The fix will be available with the upcoming 2.1.13 release.
