### ISSUE TITLE
Configurable Products with lots of configurations (about 3500) not creatable

### ISSUE THREAD

**Issue by avonheimburg** [magento/magento2#6763]
When creating a configurable product that results in a large number of configurations (easily done by having 3 different variables with 10-20 options), magento2 generates all of them in the frontend and tries to save them all at once. 

After having raised the number of input_vars into the million, magento errors out with 

> Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : internal error: Huge input lookup in /var/www/guebelin.im-dock.de/public/releases/20160921112445/web/vendor/magento/framework/View/TemplateEngine/Xhtml/Template.php on line 60

**Comment by choukalos** [comment]
Tracking internally as MAGETWO-55299

**Comment by choukalos** [comment]
Hi @avonheimburg what version of Magento are you on?

**Comment by avonheimburg** [comment]
Magento 2.1.0

**Comment by choukalos** [comment]
Hello @avonheimburg this is addressed in Magento 2.1.3, please upgrade.  closing

**Comment by mz-86** [comment]
running 2.1.6 and I'm still seeing it, 
Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : internal error: Huge input lookup

Can you please reopen

**Comment by jaiswal-grv** [comment]
I am also getting the same issue, please reopen..
Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : internal error: Huge input lookup in /home/lenssaverco/public_html/vendor/magento/framework/View/TemplateEngine/Xhtml/Template.php on line 60
