### ISSUE TITLE
Opengraphs og:description contains html tags

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#6776]
### Preconditions
1. CE 2.1.1
### Steps to reproduce
1. set short_description for product x to 
   `<ul><li>foo</li><li>bar</li></ul>`
2. view html source of product page and look out for `og:description`
### Expected result
1. `<meta property="og:description" content="foobar">`
### Actual result
1. `<meta property="og:description" content="&lt;ul&gt;&lt;li&gt;foo&lt;/li&gt;&lt;li&gt;bar&lt;/li&gt;&lt;/ul&gt;">`

`$block->stripTags()` is missing in `vendor\magento\module-catalog\view\frontend\templates\product\view\opengraph\general.phtml`

**Comment by tkacheva** [comment]
@heldchen Thanks for reporting. Issue MAGETWO-59826

**Comment by thomasdom** [comment]
I confirm that this issue is still happening in Magento CE 2.1.5

**Comment by corliving-web** [comment]
As a workaround, would the new code be?:
`<meta property="og:description" content="<?php echo $block->escapeHtml($block->stripTags($block->getProduct()->getShortDescription())); ?>" />`

Would we need to leave escapeHtml in?

Thanks.

**Comment by heldchen** [comment]
yes, to have `"` within your description text encoded properly

**Comment by veloraven** [comment]
This issue was fixed for develop branch.
Closed.

**Comment by korostii** [comment]
Hi @veloraven,
Are there any plans to backport this fix?

**Comment by gcampedelli** [comment]
I've applied the fix described here but I'm still getting html tags when I share products on Facebook. I'm using 2.1.6

**Comment by gcampedelli** [comment]
Sorry for my post. Changing file as it is described here: https://github.com/magento/magento2/issues/6776 
fixed my issue. 
Thanks, 
Gabriela

**Comment by gcampedelli** [comment]
Hello, I've applied the fix in general.phtml but after a while, when I added a new product I was getting an exception on product pages. I had to delete the file to have products displaying again. So, I think you should have to keep this issue opened.
