### ISSUE TITLE
Updates attributes for multiple products fails (Magento 2)

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#6867]
### Preconditions

1. Magento 2.1.1
2. Newest Google Chrome on Mac
### Steps to reproduce

1. product > catalog
2. select 2 products and "update attributes"
3. Can't edit price field and special price field, text seems to be behind inc.Tax. Can't save as no value in the field.
### Expected result

1. should be possible to edit values of price and special price
### Actual result

1. ![attribute](https://cloud.githubusercontent.com/assets/6672673/19068416/d8bb0f22-8a22-11e6-99aa-20f81bc2ee73.png)

**Comment by tkacheva** [comment]
Internal issue MAGETWO-59782

**Comment by Ambertvu** [comment]
In 2.1.6 this issue still persists, you can enter a value, but the value appears BEHIND the 'incl tax' label, so it seems you fill in nothing.

**Comment by zakgrindle** [comment]
This issue also persists in 2.1.7 CE

**Comment by magento-engcom-team** [comment]
@flipflap, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by Ambertvu** [comment]
This issue still exists in 2.1.10, unfortunatly we cannot update to 2.2 :-(
