### ISSUE TITLE
Minicart empty if FPC disabled in Magneto 2.1.1

### ISSUE THREAD

**Issue by ivanweiler** [magento/magento2#6882]
### Preconditions

1. Magento 2.1.1 with sample data
2. Page Cache (FPC) disabled in admin
### Steps to reproduce

1. add product to cart
2. switch currency, or switch language, or navigate to login and try to login with invalid user/pass
### Expected result

1. product should be in minicart
### Actual result

1. mini cart is empty
2. customer can't proceed to checkout

### Additional comment

Something is wrong with invalidation of local storage data. Local storage becomes empty and won't refresh when FPC is disabled (possible reason is that private_content_version cookie is missing and js reacts to it).

Funny thing is ..
**FPC disabled - customer can't buy, but currency switcher works
FPC enabled - customer can buy, but you can't switch currencies on frontend as reported in https://github.com/magento/magento2/issues/6746**

Customers are unable to proceed to checkout and purchase if we need to temporary disable FPC on live site for some reason.

Thx

**Comment by Tjitse-E** [comment]
I've noticed the same issue, but this was on a Magento 2.1 site.

**Comment by ihor-sviziev** [comment]
Looks like it's the same issue as #6473.
@ivanweiler could you check if this issue still reproduce after applying my patch from that Pull request?

**Comment by sevos1984** [comment]
Thanks for reporting, internal ticket created MAGETWO-59955

**Comment by erikhansen** [comment]
@ihor-sviziev I just tested the patch from your PR and I can verify that it fixed the described issue.

**Comment by SantoDE** [comment]
Is that possible linked to #4170 @sevos1984 ?

**Comment by sidolov** [comment]
Hi guys, this issue already fixed in develop branch, commit: 861f596371825d9e24672cd613229ae9486c635f

**Comment by ihor-sviziev** [comment]
@sidolov I think this issue can't be fixed in this way, because there also issue on client side (JS)

**Comment by Dublerq** [comment]
Bug still present in 2.1.2. Let's make magento work with cashes! Natively! And tell them to use caches all they long. Who cares about devs

**Comment by sevos1984** [comment]
Internal ticket id MAGETWO-60241

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70218

**Comment by magento-engcom-team** [comment]
Fixed in MAGETWO-53766. Release 2.2.0
@ivanweiler thank you for report
