### ISSUE TITLE
Loader issue with Payflow Pro Payment Method. 

### ISSUE THREAD

**Issue by vishveskrish** [magento/magento2#7159]
Preconditions
1. Magento CE 2.1.2(upgraded from 2.0.2 to 2.1.2) without sample data installed.
2. Configured PayPal Payflow Pro Payment Method.

Steps to reproduce
1. Navigate to storefront.
2. Click "Add to Cart" and go to the cart checkout page.
3. Enter all the details which require to place an order and click on Place order button.

Actual and Expected result:

Expected result:
The loader image should be invisible after redirecting to the payment page/success page or error page.

Actual result:
Order is placed but loader image is getting hidden before page redirection is started(Redirection starts approx after 1 seconds).Due to that reason customer will not able to know that the payment process is still running.

Our debugging outcome :

Here is the payment request process flow .
1. set-payment-information: This is the first request executing by clicking on place order button.  (www.xyz.com/storename/rest/repairparts/V1/carts/mine/set-payment-information)  - Loader status is visible.
2. requestSecureToken: This request execute after the set-payment-information process is completd (www.xyz.com/storename/rest/repairparts/paypal/transparent/requestSecureToken)  - Loader status is invisible and no process is going in customer point of view.
3. customer/section/load/?sections=messages&update_section_id=true&_=1477312905797
   : Loader is alread invisible and no process is going in customer point of view.
4. https://payflowlink.paypal.com/
   : Loader status is invisible and redirection process starts.

So overall finding says that issue with step 2,3,4.

**Comment by LiamFielding** [comment]
Funnily enough this may relate to my problem. Are you trying to update another section than messages? The messages request is made every time I call certain urls. If it's the section that needs updating this may be the problem.

**Comment by viktym** [comment]
Hi @vishveskrish 
We've created internal ticket MAGETWO-60589 to address this issue.
Thanks for reporting

**Comment by vishveskrish** [comment]
Hi @viktym , Thank you for the response!
Could you please provide the ETA for the resolution of this issue ?

Thanks,

**Comment by fxdegroot** [comment]
We're having the same problem on CE 2.1.2, CE 2.1.3 and EE 2.1.2. At the moment it's not possible for our customer to use the Payflow Pro payment method because of this issue. It's a critical issue in my opinion.

Can we get an ETA on this ?

**Comment by vishveskrish** [comment]
Hey @fxdegroot , 
We have fixed this issue by applying timeout temporary.

**Comment by Tristan-N** [comment]
Does your issue occur when you try to select payment/shipment method before you filled in an address? Because this looks a loot like an issues I an battling with atm. When I fill in address and then Cash on Delivery (for example) it works fine. When I do it the other way around it starts loading and loading etc. (CE 2.1.3)

**Comment by ladle3000** [comment]
Very disappointing to see this critical checkout issue is still present after 6 months. Do any of you have a workaround solution?  We have a contract with PayPal that we can't break and must process this way.  Going back to m1 is not an option.

**Comment by vishveskrish** [comment]
@snoroozi  : We have applied the workaround patch.

Copy this js in your theme: /Magento_Checkout/web/js/action/set-payment-information.js

Find this code : 

`return storage.post(
                serviceUrl, JSON.stringify(payload)
            ).fail(
                function (response) {
                    errorProcessor.process(response, messageContainer);
                }
            ).always(
                function () {
                    fullScreenLoader.stopLoader();
                }
            );`

and replace with below

`       return storage.post(
                serviceUrl, JSON.stringify(payload)
            ).fail(
                function (response) {
                    errorProcessor.process(response, messageContainer);
                }
            ).always(
                function () {
                     setTimeout(function(){                           
                            fullScreenLoader.stopLoader();
                        }, 6000);
                   
                }
            );`

Hope this works for you.

**Comment by vishveskrish** [comment]
@viktym : Sir do we get any resolution ? Is there any ETA on this issue ?

**Comment by alena-marchenko** [comment]
Hi @vishveskrish 

Fix for MAGETWO-60589 is merged to develop branch, closing the issue.
Thank you!

**Comment by korostii** [comment]
Hi @alena-marchenko,

Could you please provide an answer to the following questions:
1. Is there any official timeline for the 2.2 release which you could announce publicly?
2. Could you please briefly explain, what's the recommended way of using the fixes provided for the develop branch if you're a merchant or an integrator currently running 2.1.x CE in production? A link to documentation would be perfect (if available).

**Background for my questions:** 
I've seen numerous issues closed with the reason "merged to develop branch" and as I understand, develop branch corresponds to the future 2.2 version and there seems to be no publicly available date for its release. Many of those bugfixes don't reach 2.1.x releases for months straight.

To be honest, I don't see how is "merged to develop branch" an acceptable resolution to an acknowledged bug. Until the fix is officially released, a lot of the users are still struggling with it.
In my opinion, having these patches added into the nearest 2.1.x (or 2.1.x.x) releases right away would be perfect, but that doesn't seem to be happening for quite a lot of similar issues out here in on Magento2's GitHub. 

Considering that the switch to 2.2 will probably be somewhat resource-heavy and very delayed, it would make sense to have an alternative suggested officially to users of 2.1.x which would help use these numerous fixes in a safe and robust way (of which there seems to be none, to the best of my knowledge).

**Comment by mariamghalleb** [comment]
this has been fixed ? where i can find the solution if it did, thanks

**Comment by amanuni** [comment]
Hi,

This issue still not fixed and getting stuck in 4th step mentioned in the problem we have many time observed it using Magento 2.2 recently migrated and using it on live many customer complained that they get stuck while payment.

We have tested it on our test environment and some time its get stuck on test to.

**Comment by vinaysikarwar** [comment]
Any solution yet on this?
