### ISSUE TITLE
Unable to place order with coupon code and grandtotal zero 

### ISSUE THREAD

**Issue by vlauria** [magento/magento2#7536]
Hello,
I created a promotional code that apply € 50 discount on order, this promo is applied also on the shipping price.
After we have a product in the cart with the price € 10 price of shipping is 5 €.
In the cart and checkout I see grandtotal 0 but the tax is 0.9 € (this is a shipping tax).
When I click "place order" in the billing step, I have error: "the payment method requested is not available."
In by debug i see that in function isAvailable of module Payment Model Free.php the grandTotal is 0.9€

**Comment by veloraven** [comment]
@vlauria thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please also specify Magento version you are running,

**Comment by vlauria** [comment]
Precondition:
1. Magento CE 2.1 without sample data is installed.
2. Payment method Zero Subtotal Checkout is set up
3. Coupon code is set up
4. Tax configuration is set up
5. Shipping method have a tax calss associated

Steps to reproduce:
1. Create a cart price rule, whit specific coupon. Coupon setting is Apply: Fixed amount discount for whole cart. Discount amount: 50€. Apply to Shipping Amount: Yes. Discard subsequent rules: Yes.
2. Add product to cart and apply coupon. Now the grandtotal is 0.
3. In billing step, see a Free payment method.
4. Click place order and have a error: "the payment method requested is not available."

Expected result:
Order is placed successfully, customer is redirected to the success page.
Actual result:
After "Place order", order cannot be placed.

**Comment by SerhiyShkolyarenko** [comment]
@vlauria thank you! Reproduced on 2.1.2 and develop branch. Created internal issue MAGETWO-61522.

**Comment by dyushkin** [comment]
Hi @vlauria! This issue was fixed with another internal ticket, you can see commit eb4937a.

**Comment by andidhouse** [comment]
@dyushkin @veloraven - this issue still exists in 2.1.7!

If you have a voucher which is bigger then the payment amount the payment method Zero subtotal is shown - BUT THE ORDER CAN NOT BE PROGRESSED!

"Requested Payment Method is not available."

I am not shure what to hold of your bugfixes - @magento-team - And now? Vouchers are not usable at all?

**Comment by andidhouse** [comment]
@dyushkin The fix you mentioned does not work on a 2.1.7 (recent magento2 version). And now again... live with it and wait until 2.2 comes out? This does not sound like a solution in my opinion.

**Comment by hoektoe** [comment]
@andidhouse did you find a fix? I see it is move to Done in develop branch. Where can I see what was done for this particular fix

**Comment by czettnersandor** [comment]
Similar issue here, but I'm getting an error message in the checkout, where normally the payment methods are shown: "No payment methods available" and the Place Order button is hidden.

The issue goes away when I refresh the page and the Zero Subtotal payment method is showing with a text that reads "No Payment Information Required". I can progress the checkout after this.
