### ISSUE TITLE
Category Top Navigation / Maximal Depth configuration not working

### ISSUE THREAD

**Issue by ovsokolov** [magento/magento2#7543]
Category Top Navigation / Maximal Depth configuration not working

### Preconditions

1. Magento version 2.1.2

### Steps to reproduce
1.  Magento 2.1.2 installed
2. Register custom theme as a copy of standard theme without any modifications
3. Crated 3 levels of categories. (Category 1 child of Default Root/ Category 2 child of Category 1/ Category 3 child of Category 2
Category 1
--Category 2
---- Category 3
4) Configure Category Top Navigation / Maximal Depth =  1

### Expected result

1.  Expect only to see Category 1 in top navigation. When hoover over Category 1 do not expect to see child categories and children of children

### Actual result

1. Can see all categories from top menu

**Comment by palamar** [comment]
Thanks for reporting this issue. 

Internal task MAGETWO-61422 has been created for this issue.

**Comment by PascalBrouwers** [comment]
I also have some screenshots

Setting:
![category_depth_setting](https://cloud.githubusercontent.com/assets/17834386/21222345/a4ece486-c2c1-11e6-8647-afabf94519ed.png)

Actual Menu:
![category_depth_menu](https://cloud.githubusercontent.com/assets/17834386/21222344/a4d4664a-c2c1-11e6-8d93-b33b5fbf3800.png)

**Comment by PascalBrouwers** [comment]
It looks like this is the issue:
vendor/magento/module-theme/view/frontend/templates/html/topmenu.phtml
`<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>`

I fixed it manually by setting this block argument:
`
            <arguments>
                <argument name="columns_limit" xsi:type="string">1</argument>
            </arguments>
`

Don't know how to fix it because this function never get's called:
Magento\Catalog\Helper\Category->getStoreCategories() which has the check for the 'catalog/navigation/max_depth' setting.

**Comment by amansilla** [comment]
Same error here using Magento EE 2.1.3. @PascalBrouwers solutions doesn't seems to work for me.

**Comment by philipvandebriel** [comment]
Same in 2.1.4

**Comment by ventouris** [comment]
Do we have any news on this? I am on 2.1.6 and I still have the problem.

**Comment by magento-engcom-team** [comment]
@ovsokolov, thank you for your report.
We've created internal ticket(s) MAGETWO-61422 to track progress on the issue.

**Comment by linden2015** [comment]
@magento-engcom-team , can you tell me what will be done with this issue?

* Will it be fixed in 2.1.? What is the timeline?
* Will it be fixed in 2.2.? What is the timeline?

**Comment by arnoudhgz** [comment]
I just created a PR to solve this issue on 2.2, the solution is suitable for 2.1, so maybe it will be merged also in 2.1

**Comment by MarkSyred** [comment]
Issue remains in Magento 2.2.
@PascalBrouwers Where do you set the block argument you mention as a fix for this problem?

**Comment by magento-team** [comment]
Hi @ovsokolov. Thank you for your report. 
The issue has been fixed in magento/magento2#12640 by @arnoudhgz in 2.3-develop branch
Related commit(s):
 - 07233f2d04b92f308e99fe7fc0e5c24dd21ac4e5
 - 0a6ac4c0e8890de054be722718389aabf7e3e96e
 - b6215b64d45be94ece709abbcd39021529a885b4
 - 15523e82c43708eb3105e00405486495d7a068b8

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @ovsokolov The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by Floddy** [comment]
While this has been fixed in 2.3, the fix doesn't seem correct. The level setting is applied as-is, so if you enter '1' as maximal depth, it filters on level 1, which is the root category, which is never shown, so to get the 'top categories' or any categories at all really, you have to enter 2 in the setting.

In M1 the level filter was applied as 'settingvalue + 1'.

**Comment by arnoudhgz** [comment]
@Floddy it is according to the documentation. So people who use the documentation are not being confused with what programmers think: https://docs.magento.com/m2/ce/user_guide/catalog/navigation-top.html

**Comment by Floddy** [comment]
@arnoudhgz The documentation doesn't explicitly state the correlation between level and depth, and the setting says 'Maximal Depth', not 'Maximum level'. In my opinion they're two different things. Depth for me is 'how deep the main menu should render' - and setting it to 1 to me means 'render one level', just like in M1.

It also states that 'To limit the number of subcategories that appear in the top navigation, enter the number in the Maximal Depth field.' which could suggest entering 1 would show 1 set of subcategories.
