### ISSUE TITLE
Product relations get lost on product save

### ISSUE THREAD

**Issue by andreaskoch** [magento/magento2#7588]
Saving a configurable product while the product editor is not fully initialized destroys the connection to its child products and turns the configurable product into a simple product.

**Before**

![Screenshot of Magento 2 Sample Product "Hero Hoodie product detail page" BEFORE it was destroyed](https://cloud.githubusercontent.com/assets/247364/20669020/1a4871ee-b572-11e6-86d5-d6a893fc2ac7.png)

**After**

![Screenshot of Magento 2 Sample Product "Hero Hoodie product detail page" AFTER it was destroyed](https://cloud.githubusercontent.com/assets/247364/20669036/2988f99e-b572-11e6-8bed-4c82f1b47eb9.png)

### Preconditions

We could reproduce the bug under the following conditions:

- Magento 2.1 Community Edition with the standard sample data)
- Magento 2.1 Enterprise Edition
- Nginx + PHP 7
- Browsers
  - Firefox 48, 50 (Windows + Ubuntu)
  - Chrome (Windows + Ubuntu)

### Steps to reproduce

1. Open a configurable product in the Magento backend
   `Magento 2 Backend > Products > Catalog > Filter [Type = Configurable] > Edit` (e.g. Hero Hoodie (MH07))
2. Review the configurations section. All child products of the configurable should be displayed.
3. Click the save button
4. Wait 2-3 seconds.
5. Click the save button a second time.
6. Wait for the product editor to load.
7. Review the configurations sections. This time the configurations section will be empty.
8. Click the save button again. Magento will save the incomplete product state to the database and the relationship between the configurable product and it's child products will be lost, and the configurable product now is a simple product.

Here is a short video of the steps above: https://youtu.be/ShBcU_-LQHA

![Screencast on how to destroy a configurable product from the Magento backend](https://cloud.githubusercontent.com/assets/247364/20670021/49c84e8a-b577-11e6-8256-3d5903e8fdc1.gif)

The example might seem a bit contrived but **we experienced this issue many times in our production environment**.

### Expected result

Magento should not take the data sent by the client as the single source of truth. If the product relations have not been updated, Magento should not remove them if they are missing in the request sent by the client. Or the JavaScript should prevent save requests if the product model is not fully initialized.

As a quick fix we have added a check to the method that prevents the save if the product does not have any configurable products. For the Community Edition could look something like this (see: `Magento\Catalog\Controller\Adminhtml\Product\Save::execute`):

```php
class Save extends \Magento\Catalog\Controller\Adminhtml\Product
{
  public function execute()
  {
      ...

      $product = $this->initializationHelper->initialize(
          $this->productBuilder->build($this->getRequest())
      );

      if ($this->isConfigurableWithoutProductLinks($product)) {
          throw new \Exception("A second save request with missing product relations was detected");
      }

      ...
  }

  private function isConfigurableWithoutProductLinks(\Magento\Catalog\Model\Product $product): bool
  {
      if ($product->getTypeId() !== 'configurable') {
          return false;
      }

      /** @var \Magento\Catalog\Api\Data\ProductExtension $extensionAttributes */
      $extensionAttributes = $product->getExtensionAttributes();
      if (empty($extensionAttributes)) {
          return false;
      }

      $configurableProductLinks = $extensionAttributes->getConfigurableProductLinks();
      if (!empty($configurableProductLinks)) {
          return false;
      }

      return true;
  }

}
```

But it would be nice if you could find a more elegant way to prevent this whole class of errors.

### Actual result

If you watch the `catalog/product/save/id/` requests sent by Magento with your browser's network console or with Fiddler you can see the impartial save request body that destroys the configurable product:

[save-request-1.txt](https://github.com/magento/magento2/files/616335/save-request-1.txt) compared to [save-request-2.txt](https://github.com/magento/magento2/files/616337/save-request-2.txt)

![Comparing the first save request with the impartial second request](https://cloud.githubusercontent.com/assets/247364/20669536/0e1a7d56-b575-11e6-8be5-f6613faac523.png)

Magento saves the data sent by the client without checking the integrity of the data and clears all attributes that are missing the request body.

**Comment by roseofgold** [comment]
New to Magento and having this issue. Does the code you have posted under expected result give you the expected outcome? If so, where would I put it in CE 2.1.2 so that it doesn't get written over?

**Comment by VirginiaMoon** [comment]
Have you had any more insight into this issue? Currently experiencing it on servers running Apache and PHP5.6.

**Comment by Istel83** [comment]
Same behavior in 2.1.3 CE , Apache + PHP7, but it seems to affect only some backoffice users ( the role is the same ). Tested with the same "affected-user" using different devices/browsers.

**Comment by jzahedieh** [comment]
I have encountered this issue when dealing with custom and standard product attributes, if an error is thrown then the product association can get lost.

I have raised this with EE support team and provided replication steps but for openness I am going to post the issue here as well as it is a really bad bug.

----

# Configurable product variants lost after save preceding error.

## Description:	
In order to work around the datetime issue we are creating separate date and time attributes in order to be able to set the the time on a datetime product attribute.

The  new time attribute (static, custom backend model) has to do some validation to make sure the content team use the correct time format, "HH:MM". The class extends `\Magento\Eav\Model\Entity\Attribute\Backend\AbstractBackend` like many other core backend product models.

This throws a `\Magento\Framework\Exception\LocalizedException` if there are any issues.

All good so far the functionality is working as intended, an error message is presented if incorrectly used.

The issue happens after an error message is presented, which is then fixed allowing the product to be successfully saved. All product variants of the configurable product are lost and now the product is a simple product.

## Steps to Reproduce:	
I used a fresh install of Magento to replicate this issue using the Docker DevBox (Beta) installing a fresh copy of EE 2.1.3 with sample data using Redis and Varnish. 

It is possible to replicate this issue by following these steps:

1. Login to admin 
2. Create a new attribute called "Unique Attribute" 
2.1 Attribute Code: unique_attribute 
2.2 Scope: Global 
2.3 Unique Value: Yes 
2.4 Add to Column Options: No 
2.5 Use in Filter Options: No 
3. Assign new attribute to following attribute sets under the Product Details Group: Default, Bottom 
4. Navigate to Products > Catalog and apply following filters: 
4.1 Type: Configurable Product Attribute 
4.2 Set: Bottom 
4.3 Visibility: Catalog, Search 
5. Edit Product MP01 
5.1 Set Unique Attribute value to: unique 
5.2 Save 
6. Edit Product MP02 
6.1 Set Unique Attribute value to: unique 
6.2 Save 
6.3 Error validation displays following message: 
6.3.1 The value of attribute "Unique Attribute" must be unique 
6.4 Set Unique Attribute value to: unique2 
6.5 Save 
7. Assert following issues:
7.1 Product MP02 has no variants 
7.1 Product MP02 is type simple

## Magento Support Response

I have tested and confirmed this issue in our native Magento EE version 2.1.3. This issue has not been reported by an EE merchant and there is currently no available fix or workaround other than generating a product CSV prior to making changes for a product to ensure that if the error occurs, you can reassign the lost products via a CSV import.

**Comment by luukschakenraad** [comment]
This seems to be caused by `/vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/variations.js` line 306 and 309:

`delete this.source.data["configurable-matrix"];`

`delete this.source.data["associated_product_ids"];`

Removing/commenting these lines solves this issue. The next question: What does this solution break?

**Comment by T0mGreg0ry** [comment]
We are an EE merchant and we are putting in a ticket with EE support as we are having this exact issue. 

I will update once I've heard back from Magento support.

**Comment by jzahedieh** [comment]
@ImFastTom I've had 9 updates of the following, hopefully you get more out of them than me:

> I am again reaching out to provide you with a weekly update on the status of this issue and the escalation ticket. Our developers are still working to resolve this issue and have not yet provided any new information. Due to the complex nature of the Magento software, we are unable to provide you with an ETA or an expected release version that will correct this issue. I am constantly monitoring the escalation ticket and will keep you updated as this issue progresses through the investigation and development processes.
>
> I thank you for your patience and understanding.

**Comment by T0mGreg0ry** [comment]
Thanks for letting me know @jzahedieh I'll let you know if i get any more info.

**Comment by HashmiRSA-zz** [comment]
Running into the same issue after configuring UPC attribute having a unique value configuration. Our setup consists of:
- Magento 2.1.7 CE
- PHP 7.0.19
- Litespeed web server
- chrome browser.

**Comment by haneef-faisal** [comment]
Facing the same on

Magento CE 2.1.3
PHP 7.0.17
Zend Engine v3.0.0
Nexces Hosting Server
Chrome, FireFox, Safar & IE

**Comment by IlnitskiyArtem** [comment]
@andreaskoch, , Thanks for reporting this issue.
We've created internal ticket MAGETWO-69704 to address this issue.

**Comment by altafhussain10** [comment]
I am facing the same issue in 2.1.6. It is very frustrating and costing us a lot of time :( . I am already regreting to update to M2.

**Comment by luukschakenraad** [comment]
We have created a composer patch which comments line 306 and 309 in `/vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/variations.js` after deployment.

This solves the issue for us and we have not found any downsides of this solution the last month.

**Comment by altafhussain10** [comment]
@schakenraadjuh  Can you please share the file with me, as I can't update my installation with composer.

**Comment by luukschakenraad** [comment]
@altafhussain10 Attached the patch I use. If you do not use deployment / composer you can always comment the mentioned lines manually, but keep in mind they wil be overwritten when updating.

[Patch-Magento_Configurable-loosing-simples-after-double-save.txt](https://github.com/magento/magento2/files/1119588/Patch-Magento_Configurable-loosing-simples-after-double-save.txt)

**Comment by k4emic** [comment]
Reproduced on 2.1.7 running apache with PHP 7. Mentioned patch fixes the problem.

**Comment by devqualwebs** [comment]
Facing the same issue after save configurable products. Our setup consists of:

    Magento 2.1.7 CE
    PHP 7.0.19
    chrome and firefox browser.

**Comment by roseofgold** [comment]
Reproduced on 2.1.8. Mentioned patch doesn't seem to fix the issue.

**Comment by magento-engcom-team** [comment]
@andreaskoch, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by edwinchandra** [comment]
Hi,
Is there any fix for issue? I am also facing similar issue if there is any validation error for required field thrown for configuration product and then save the product all the associated child product get lost.

Magento 2.1.9 CE
PHP 7.0.19
chrome browser.

**Comment by dtfdigital** [comment]
Note we have a Magento CE 2.3.2 customer and they still get this issue. Whether it makes any difference, but they were a M1.9 migration.
