### ISSUE TITLE
Multi Select attribute not updating

### ISSUE THREAD

**Issue by Zarina2222** [magento/magento2#7646]
### Preconditions

1. Magento CE 2.1.2
2. Apache/2.4.18 (Ubuntu) PHP/7.0.8-0ubuntu0.16.04.3 MySQL/5.7.13-0ubuntu0.16.04.2

### Steps to reproduce

1. I have multiselect attribute `display_connectors`
![image](https://cloud.githubusercontent.com/assets/11063464/20790638/e2ab7428-b7c1-11e6-9853-a68b4a2762eb.png)
2. I have product TF-AEC-6635-A2M-1210 with this attribute and DP selected 
![image](https://cloud.githubusercontent.com/assets/11063464/20790705/3ea76fe8-b7c2-11e6-97c4-59ca06ba3438.png)
3. Then I try to add VGA and HDMI options using Catalog product edit page
![image](https://cloud.githubusercontent.com/assets/11063464/20790947/5c3458fe-b7c3-11e6-98bb-b2961a1544a4.png)
or import csv-file
`sku,additional_attributes`
`TF-AEC-6635-A2M-1210,"display_connectors=DP,DVI,VGA"`

### Expected result

1. Product's display_connectors attributes should have DP, VGA and HDMI options selected

### Actual result

1. Nothing happens, DP stays selected and also if I try remove DP it still stays there. This happens with all multiselect attributes. First time when product not yet have that attribute, I can normally select or import options I want, but if I try remove or add options later nothing happens.

**Comment by daniel-ifrim** [comment]
@Juigeli I have same problem in Magento CE 2.1.6.
This happens to me if I have 1 configurable product from other attribute set that does not have this attribute in it. It happens only for multiselect. I've tested it on CE 2.1.6 with sample data too.
@Juigeli  Do you have a configurable product  in related, cross or up-sell products like my case ?

**Comment by RomanKrut** [comment]
@Juigeli  Unfortunately, I could not reproduce the issue as you described it. Maybe your issue was fixed, can you please recheck it on the latest version of Magento 2 ?

**Comment by Zarina2222** [comment]
I'm updating to Magento 2.1.7 on this week, maybe tomorrow. I can check the issue after that, hopefully updating fixes the issue.

**Comment by Juigeli** [comment]
After update still not working. 

But I found a solution: https://github.com/nagno/magento2/commit/b380502570b92449326ab6ed50e6ce0359287240

After that
```
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy en_US fi_FI
php bin/magento cache:flush
php bin/magento cache:clean
sudo chown -R user:www-data ./
```

And clear browser cache

: )

**Comment by RomanKrut** [comment]
@Juigeli Tell us if this issue is still actual, or we can close it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
