### ISSUE TITLE
Custom theme doesn't apply XML layout updates when applied to a product

### ISSUE THREAD

**Issue by chickenland** [magento/magento2#7710]
I was looking to open this issue, but thought I'd try and find one before I did.  I think this issue is linked to #7503, but is manifesting is achieved in a different way

We have a theme that does not inherit, and it's XML updates appear to be ignored.

### Preconditions

    Magento 2.1.2, PHP 5.6.24
    Environment: Windows XAMPP / Windows WSL
    Developer Mode

### Steps to reproduce

Set the theme for a specific storeview to Purenet/Theme (our default theme for the store) via Content > Design > Configuration > Edit.

Create and install a theme that has no inheritence. Add layout changes. For this example, I created a theme with a `catalog_product_view.xml` file that removes the main title for the product as Purenet/Client.

    <?xml version="1.0"?>
    <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="page.main.title" remove="true"/>
    </body>
    </page>

1. Deploy static content for the 'Purenet Client' theme:
2. bin/magento setup:static:deploy --theme="Purenet/Client" en_GB
3. Apply the 'Purenet Client' theme to a category via Products > Catalog > Actual Product > Schedule Design Update > Set Dates & New theme to be Purenet/Client. Save Product.

### Expected result

When checking the the product page, you should not see the main product title.

### Actual result

On the Product Page, the main product title is displayed.

Setting a similar XML layout file on a category in the same manner appears to work.

### Investigation

So far, it looks like `_fetchPackageLayoutUpdates` within `lib/internal/Magento/Framework/View/Model/Layout/Merge.php` doesn't capture the XML that contains the handle updates.  I found moving the XML into `catalog_product_prices` made it added as an update, however, it was still not removed.

**Comment by shavounet** [comment]
I can confirm this bug : the new Theme is correctly set by \Magento\Catalog\Helper\Product\View::initProductLayout ; yet, only templates are changed and layout XML updates are ignored...

**Comment by shavounet** [comment]
Also, I didn't manage to use my theme in the "Schedule a design update" in product form (outside of any category configuration...)

**Comment by shavounet** [comment]
I saw the line "Custom themes now inherit parent XML configuration information as expected." in [Magento's 2.1.3 release notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html#general-fixes), but after upgrading to 2.1.3 and cleaning every cache, it's still not working.

**Comment by shavounet** [comment]
I may have fixed it in my codebase... I used a before plugin on the execute method of catalog/product/view controller. The idea is to set the code bellow as soon as possible (from \Magento\Catalog\Helper\Product\View::initProductLayout). 
```php
            $settings = $this->_catalogDesign->getDesignSettings($product);

            if ($settings->getCustomDesign()) {
                $this->_catalogDesign->applyCustomDesign($settings->getCustomDesign());
            }
```

The bug is due to the layout being loaded before the custom design is set. It happens twice : 
- vendor/magento/module-catalog/Controller/Product/View.php:108 (with the 'addDefaultHandle')
- vendor/magento/module-catalog/Helper/Product/View.php:195 (with the 'getUpdate')

**Comment by bunsworth94** [comment]
@shavounet I've tried your solution however it doesn't seem to work? Could you expand on this more please?

**Comment by shavounet** [comment]
Here is the main code of the plugin I use, on `Magento\Catalog\Controller\Product\View` : 
```php
    /**
     * Custom fix for https://github.com/magento/magento2/issues/7710
     * It allows to use a custom them for product page
     * @see \Magento\Catalog\Controller\Product\View::execute
     * @param View $subject
     */
    public function beforeExecute(View $subject)
    {
        $productId = (int) $subject->getRequest()->getParam('id');
        $categoryId = (int) $subject->getRequest()->getParam('category', false);

        $product = $this->initProduct($productId, $categoryId);
        if($product) {
            $settings = $this->_catalogDesign->getDesignSettings($product);

            if ($settings->getCustomDesign()) {
                $this->_catalogDesign->applyCustomDesign($settings->getCustomDesign());
            }
        }
    }

    /**
     * Get the product with the given ID, and optionally set the category, if given
     * @param $productId
     * @param $categoryId
     * @return \Magento\Catalog\Model\Product|ProductInterface|bool
     */
    protected function initProduct($productId, $categoryId)
    {

        try {
            $product = $this->productRepository->getById($productId, false, $this->storeManager->getStore()->getId());
        } catch (NoSuchEntityException $e) {
            return false;
        }

        try {
            $category = $this->categoryRepository->get($categoryId);
            $product->setCategory($category);
        } catch (NoSuchEntityException $e) {
            // Do nothing
        }

        return $product;
    }
```

**Comment by demetrius143** [comment]
I have this problem to. I've been stuck on it for 4 days! Thank so much for the solution. Initially I thought I had made a mistake in the theme layout but no matter what I did to the xml file, it would not render. 
Magento 2 seems like its still buggy even after 2.1 has been released.

**Comment by eoss-th** [comment]
So i would like to know that this bug will close in 2.1.7 or not?

**Comment by surendragamage** [comment]
Go to your database. select **theme** table. Check custom theme record. If the value of the **type** field is **1** change it to **0**. This fixed my issue.

**Comment by veloraven** [comment]
Internal ticket was created for this issue: MAGETWO-69709

**Comment by jakgyamfi** [comment]
hi shavounet, i have been struggling with this. i cannot figure out how to implement your fix to try it out. i have a child theme (myfirsttheme) with Magento/blank as parent. 
I have another child theme (mysecondtheme) with (myfirsttheme) as parent. 
The problem is template files amended get parsed in frontend but the xml files do not. i am only seeking to amend the catalog_product_view.xml and it does not parse at all, overriden by settings in the (myfirsttheme)
i think your fix will be a solution for me but i do not know how to implement them. copied and pasted in code at Magento\Module_Catalog\Controller\Product\View.php it didnt work. and tried it in Magento\Module_Catalog\Helper\Product\View.php that also didnt work either. Please can you tell me if that solution fixes my detailed problem and how i should implement it.
Thank you

**Comment by demetrius143** [comment]
@elghana I have a module that you can add to your site that solves this problem using the solution above.
email me for details: info@dknzdesign.com

**Comment by DenisNatalevich** [comment]
My solution:

Override\Override\etc\di.xml
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Catalog\Helper\Product\View" type="Override\Override\Model\View"/>
</config>
```

Override\Override\Model\View.php
```php
<?php
namespace Override\Override\Model;

use Magento\Framework\View\Result\Page as ResultPage;

class View extends \Magento\Catalog\Helper\Product\View
{

    public function __construct(
        \Magento\Framework\App\Helper\Context $context,
        \Magento\Catalog\Model\Session $catalogSession,
        \Magento\Catalog\Model\Design $catalogDesign,
        \Magento\Catalog\Helper\Product $catalogProduct,
        \Magento\Framework\Registry $coreRegistry,
        \Magento\Framework\Message\ManagerInterface $messageManager,
        \Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator $categoryUrlPathGenerator,
        array $messageGroups = []
    ) {
        parent::__construct(
            $context,
            $catalogSession,
            $catalogDesign,
            $catalogProduct,
            $coreRegistry,
            $messageManager,
            $categoryUrlPathGenerator
        );
    }

    public function initProductLayout(ResultPage $resultPage, $product, $params = null)
    {
        $settings = $this->_catalogDesign->getDesignSettings($product);
        $pageConfig = $resultPage->getConfig();

        if ($settings->getCustomDesign()) {
            $this->_catalogDesign->applyCustomDesign($settings->getCustomDesign());
        }

        // Apply custom page layout
        if ($settings->getPageLayout()) {
            $pageConfig->setPageLayout($settings->getPageLayout());
        }

        $urlSafeSku = rawurlencode($product->getSku());

        // Load default page handles and page configurations
        if ($params && $params->getBeforeHandles()) {
            foreach ($params->getBeforeHandles() as $handle) {
                $resultPage->addPageLayoutHandles(
                    ['id' => $product->getId(), 'sku' => $urlSafeSku, 'type' => $product->getTypeId()],
                    $handle
                );
            }
        }

        $resultPage->addPageLayoutHandles(
            ['id' => $product->getId(), 'sku' => $urlSafeSku, 'type' => $product->getTypeId()]
        );

        if ($params && $params->getAfterHandles()) {
            foreach ($params->getAfterHandles() as $handle) {
                $resultPage->addPageLayoutHandles(
                    ['id' => $product->getId(), 'sku' => $urlSafeSku, 'type' => $product->getTypeId()],
                    $handle
                );
            }
        }

        // Apply custom layout update once layout is loaded
        $update = $resultPage->getLayout()->getUpdate();
        $layoutUpdates = $settings->getLayoutUpdates();

        // NEW CODE
        $category_ids = $product->getData('category_ids');
        if (is_array($category_ids) && count($category_ids)) {
            foreach($category_ids as $category_id) {
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $model = $objectManager->create('Magento\Catalog\Api\CategoryRepositoryInterface');
                $category = $model->get($category_id);
                if($category->getData('custom_apply_to_products')) {
                    $layoutUpdates[] = $category->getData('custom_layout_update');
                }
            }
        }

        if ($layoutUpdates) {
            if (is_array($layoutUpdates)) {
                foreach ($layoutUpdates as $layoutUpdate) {
                    $update->addUpdate($layoutUpdate);
                }
            }
        }

        $currentCategory = $this->_coreRegistry->registry('current_category');
        $controllerClass = $this->_request->getFullActionName();
        if ($controllerClass != 'catalog-product-view') {
            $pageConfig->addBodyClass('catalog-product-view');
        }
        $pageConfig->addBodyClass('product-' . $product->getUrlKey());
        if ($currentCategory instanceof \Magento\Catalog\Model\Category) {
            $pageConfig->addBodyClass('categorypath-' . $this->categoryUrlPathGenerator->getUrlPath($currentCategory))
                ->addBodyClass('category-' . $currentCategory->getUrlKey());
        }

        return $this;
    }
}
```

**Comment by magento-engcom-team** [comment]
@chickenland, thank you for your report.
We've created internal ticket(s) MAGETWO-69709 to track progress on the issue.

**Comment by kirmorozov** [comment]
Same as https://github.com/magento/magento2/issues/8333

**Comment by kirmorozov** [comment]
I provided reference fast patch within https://github.com/magento/magento2/issues/8333

**Comment by magento-engcom-team** [comment]
Hi @chickenland. Thank you for your report. 
The issue has been fixed in magento/magento2#19124 by @drew7721 in 2.3-develop branch
Related commit(s):
 - [1becee9bb4114318c89f54b45c10b6b60cdc9cee](https://github.com/magento/magento2/commit/1becee9bb4114318c89f54b45c10b6b60cdc9cee)
 - [b8940db9514c672c9e191bbb33172884a524a993](https://github.com/magento/magento2/commit/b8940db9514c672c9e191bbb33172884a524a993)
 - [fd26b94dc1950845a135879937ce7ce0d8f8b8b4](https://github.com/magento/magento2/commit/fd26b94dc1950845a135879937ce7ce0d8f8b8b4)
 - [47e42a969d443715bf483f9e90eabfd2a141c930](https://github.com/magento/magento2/commit/47e42a969d443715bf483f9e90eabfd2a141c930)
 - [4b6100d1e991fc56f7ff9f8e0f0be0db7192328e](https://github.com/magento/magento2/commit/4b6100d1e991fc56f7ff9f8e0f0be0db7192328e)
 - [b8442a15bb1fed7843166bdd4437c009ef03a82f](https://github.com/magento/magento2/commit/b8442a15bb1fed7843166bdd4437c009ef03a82f)

The fix will be available with the upcoming 2.3.1 release.

**Comment by uabassguy** [comment]
@magento-engcom-team The issue still exists in 2.3.2, updating the type field in the theme table to 0 fixed it in my case, need a more substantial fix. Half of those commits referenced are just comments

https://github.com/magento/magento2/issues/7710#issuecomment-306389802

**Comment by BtotheT** [comment]
@shavounet thank you for providing the plugin code you used - that was the ONLY one that worked for a Cloud 2.3.3 instance!
