### ISSUE TITLE
Bundle Product Show Incorrect Price if Bundle option has quantity more than 1 by default

### ISSUE THREAD

**Issue by frostshoxx** [magento/magento2#7718]
### Preconditions

1. Magento version 2.1.2
2. PHP 7.0.11
3. MySQL 5.6

### Steps to reproduce

1. Create a bundle product.
2. Set base price 0.
3. Add some bundle option. For example, 1 drop down option with $10 product A, 2nd drop down option with $5 product B with default quantity of 4.

### Expected result

1. In theory, the default price should be $0 + $10 + (4x $5 = $20) = $30 and that show be consistently shown on category page, product page, and shopping cart (if added).

### Actual result

1. On the product page the top price that show under the product name is for some reason show as $0 + $10 + (4 x 4 x $5 = 80) = $90.
![issue1](https://cloud.githubusercontent.com/assets/567851/20975460/914f347e-bc6d-11e6-8a7f-9ef49123402c.PNG)

2. The bottom price toward the end where we specify quantity is show the correct $30.
![issue2](https://cloud.githubusercontent.com/assets/567851/20975499/b07be3f6-bc6d-11e6-8b91-c882f4c52c23.PNG)

![issue3](https://cloud.githubusercontent.com/assets/567851/20975950/00ef8cba-bc6f-11e6-92fd-6a760e2fc540.PNG)

So in the other words, the first price, which is also the same price that shows on the category page incorrectly combine the 4 x qty price on top of the pre-computed (4 x $5) again.

The bottom part and the final amount show on the shopping cart is shown correctly.

**Comment by IlnitskiyArtem** [comment]
Thank you, Internal ticket was created for this issue - MAGETWO-69896

**Comment by magento-engcom-team** [comment]
@frostshoxx, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by sarfarazbheda** [comment]
Hello,
Still facing the issue on 2.2 branch. 
@magento-engcom-team give me 2.3.0 instance
Want to test in detail or provide me any git commit reference.

Thanks.

**Comment by magento-engcom-team** [comment]
Hi @sarfarazbheda. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sarfarazbheda, here is your [Magento instance](https://i-7718-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-7718-2-3-0.instances.magento-community.engineering/admin](https://i-7718-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
