### ISSUE TITLE
TinyMCE editor does not allow "%" character

### ISSUE THREAD

**Issue by jasonheecs** [magento/magento2#7733]
### Preconditions

Using custom Ubuntu xenial vagrant-box, php7, apache

Have develop branch of Magento 2 installed.
Install sample data (sampledata:deploy).

### Steps to reproduce

Log into admin
Navigate to PRODUCTS >> Inventory >> Catalog
Filter the list by name: "Breathe-Easy Tank"
Select the product that has that exact name (should be last in the list)
In the editor form open up: Content >> Description
Enable WYSIWYG editor
Insert some dummy text in the product description with the "%" character. For example: "This is a dummy product % description"

### Expected result

Product description text is inserted into the WYSIWYG editor

### Actual result

An error message is shown:
![image](https://cloud.githubusercontent.com/assets/9844923/21041416/d9824786-be25-11e6-93e4-e103247d8f04.png)

### Notes
Is this caused by [this commit](https://github.com/magento/magento2/commit/9030e0860abaa93650dd82aaaac42aff081b2378) that was to address [this issue](https://github.com/magento/magento2/issues/6138)?

**Comment by vityakopin** [comment]
Unfortunately, I could not reproduce the issue as you described it. Can you reproduce this issue on latest version of Magento?

**Comment by hostep** [comment]
@vityakopin: the issue only existed for a couple of months on the `develop` branch, but was never released in an actual release. It seems like it was recently fixed, see https://github.com/magento/magento2/issues/9452 for more info.
It looks like @jasonheecs came to the same conclusion as I did. Sorry for creating a duplicate ticket. Which one should we close?

**Comment by veloraven** [comment]
I'm closing this issue as it was already fixed in develop branch and there is separate ticket for ver. 2.1  - #8369 (Internal ticket MAGETWO-68810)

**Comment by hostep** [comment]
@veloraven: as far as I'm aware, this issue doesn't exist in version 2.1, so why do you have an internal ticket for this?

**Comment by mmred** [comment]
Hello @hostep ,
The error is still recurring after applying the fix by removing the line content = decodeURIComponent(content);.

I am using magento 2.1.6 version.
Please advise,

Thank you

**Comment by hostep** [comment]
@mmred: I can't seem to reproduce this on clean Magento 2.1.6

And reading through the comments in this ticket and others, the issue should never have appeared in a officially released version, but if it did, it should at least be finally fixed in 2.1.8 (according to the discussion in https://github.com/magento/magento2/pull/10131)

But I would highly advise you to upgrade to the latest version (2.1.13 at the moment of writing) since you are missing out a lot of security fixes:
- https://magento.com/security/patches/magento-2014-and-217-security-update
- https://magento.com/security/patches/magento-2016-and-219-security-update
- https://magento.com/security/patches/magento-221-2110-and-2017-security-update
- https://magento.com/security/patches/magento-2.2.3-2.1.12-and-2.0.18-security-update

I understand that upgrades aren't that easy sometimes and can screw up customised features and/or introduce new bugs, but you should still try to prioritise upgrading a bit and then work around new issues when you run into them.
