### ISSUE TITLE
Unexpexted display of the tax row in the cart summary block

### ISSUE THREAD

**Issue by edelepine** [magento/magento2#7990]
### Preconditions
1. Magento CE 2.1.2

### Steps to reproduce
1. Add product in order to access checkout/cart page.
2. View and edit cart.
3. Ensure that tax segment is equal to zero.
4. Ensure that `window.checkoutConfig.isZeroTaxDisplayed` is equal to `false`.

### Expected result
1. In summary block, tax row should'nt be displayed

### Actual result
1. Despite of expected configuration, tax row is displayed in the summary block

![image](https://cloud.githubusercontent.com/assets/1932248/21540489/b131eeaa-cdaf-11e6-8567-4dfc029b166b.png)

The problem seems to come from the js function `ifShowValue` in [`totals/tax.js`](https://github.com/magento/magento2/blob/develop/app/code/Magento/Tax/view/frontend/web/js/view/checkout/cart/totals/tax.js#L21) where condition use a `===` comparison operator.
So when comparing a float value and an integer value, the function will always return true.

**Comment by IlnitskiyArtem** [comment]
HI, @edelepine.
Internal ticket MAGETWO-70597, which tracks this GitHub issue, is in our issue backlog.

**Comment by magento-engcom-team** [comment]
@edelepine, thank you for your report.
We've created internal ticket(s) MAGETWO-70597 to track progress on the issue.

**Comment by RomaKis** [comment]
Working on this.

**Comment by magento-engcom-team** [comment]
Hi @edelepine. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1135 by @RomaKis in 2.2-develop branch
Related commit(s):
 - [2b92f79e81b32810de5fff8d0001c9a42c685ae7](https://github.com/magento/magento2/commit/2b92f79e81b32810de5fff8d0001c9a42c685ae7)

The fix will be available with the upcoming 2.2.5 release.

**Comment by pooshok** [comment]
As usual the fix was overwrited in future releas :roll_eyes: 
Issue still the case in 2.4.1
