### ISSUE TITLE
Using System Value for Base Currency Results in Config Error

### ISSUE THREAD

**Issue by tsmith1985** [magento/magento2#8003]
Checking `Use system value` for the base currency in the currency options results in a configuration error when importing currency rates.

### Preconditions

- Magento CE v2.1.3
- PHP v7.0.14
- MySQL v14.14 Distrib 5.7.16, for osx 10.12

### Steps to reproduce

1. Log into Admin 
2. Navigate to `Stores > Settings > Configuration > General > Currency Setup`
3. Select `Use system value` for `Base Currency`
4. Select `Yes` for `Enabled` in the `Scheduled Import Settings` section 
5. Click `Save Config` if necessary and flush the cache
6. Navigate to `Stores > Currency > Currency Rates`
7. Try Importing Currency Rates via any of the three services

### Expected result
1. Currency rates are imported for `Allowed Currencies`

### Actual result
1. `You must first configure currency options before being able to see currency rates.` is displayed on `Currency Rates` page and user is unable to import rates via any of the services.

![currency_options](https://cloud.githubusercontent.com/assets/582928/21569678/f5a35dac-ce73-11e6-8262-c68e5736a3b7.png)

![currency_rates](https://cloud.githubusercontent.com/assets/582928/21569680/fa7f958e-ce73-11e6-986f-8dda9497e572.png)

### Additional Notes
I was able to work around this issue by unselecting `Use system value` and explicitly selecting a Base Currency.

This issue seems to be a result of the base currency not being written to the database when `Use system value` is selected

```
mysql> mysql> select * from core_config_data where path='currency/options/base';
Empty set (0.00 sec) 
```

This results in this method failing to fetch the rates as `$defaultCurrencies` (actually base currencies) is empty:

```
<magento install dir>/vendor/magento/module-directory/Model/Currency/Import/AbstractImport.php#L92-L117

/**
  * @return array
  */
public function fetchRates()
{
    $data = [];
    $currencies = $this->_getCurrencyCodes();
    $defaultCurrencies = $this->_getDefaultCurrencyCodes();
    set_time_limit(0);
    foreach ($defaultCurrencies as $currencyFrom) {
        if (!isset($data[$currencyFrom])) {
            $data[$currencyFrom] = [];
        }
        foreach ($currencies as $currencyTo) {
            if ($currencyFrom == $currencyTo) {
                $data[$currencyFrom][$currencyTo] = $this->_numberFormat(1);
            } else {
                $data[$currencyFrom][$currencyTo] = $this->_numberFormat(
                    $this->_convert($currencyFrom, $currencyTo)
                );
            }
        }
        ksort($data[$currencyFrom]);
    }
    ini_restore('max_execution_time');
    return $data;
}
```

Also, the `_getDefaultCurrencyCodes()` method is getting the base currencies rather than the default currencies, which may be a bug or just a poor naming choice:

```
<magento install dir>/vendor/magento/module-directory/Model/Currency/Import/AbstractImport.php#L49-L52
protected function _getDefaultCurrencyCodes()
{
    return $this->_currencyFactory->create()->getConfigBaseCurrencies();
}

```

**Comment by veloraven** [comment]
@tsmith1985 thank you for your report.
We have created internal ticket MAGETWO-62921

**Comment by michael-tourneur** [comment]
@veloraven this issue has been fixed and merged?

**Comment by magento-engcom-team** [comment]
@tsmith1985, thank you for your report.
We've created internal ticket(s) MAGETWO-62921 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has neeb fixed and delivered to 2.2-develop branch

**Comment by magento-engcom-team** [comment]
Hi @tsmith1985. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1358 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 2e90684d1f906a63c37e2dea4710aee59c0c0a58
 - f99b75906ab0d370005692499faebba810aa3984
 - 49a3076876a44798397495c6f376699eb3214528
 - b754973b0c24a5d4482ba6b027f8d673a64dae80
 - ed833c492e51f78ee2523c0b2eb5fee37c91166d
 - d8b73d3bb4b8ff66faa308e761b9ade25d0bf9f7
 - 60e83eac5925e1ec01cbc11b8eb1acc5305a7a23
 - dc69e175dc95befc3e1c0eb1b9d51c23a0e1e0e9
 - 6b9c188627aa4d9614c5ffe1a0436d75e17bb796
 - 3b58efc8e8cf3f856f7f0edbe84bd2ceb5f167b2
 - 8b40859ed856295dfd4240638c26d7b17807402a
 - 11922a14040b4869da87445fa627533256164595
 - 0bd39d42c785cac7ee0b49434cb957baa04f6c7f
 - 8bbb8bbb675f10f9632e76ff27a8199a7a3aa4ee
 - f8307d9d169debab91b1440d131dc166eb2e2640
 - 768c769b2772743e8599840aa8dc523597d0b6e5
 - 16a10291b25f826d066f155257a3922ee3f01682
 - 17a26cbcf93a3d95815a21b92dc9bc04ec116e58
 - 8f1d8e78df9cd8f648ea30d399f81816ad1d6d01
 - 5d084ce7979f07e7b1d6ac9980be13fdd2a378cd
 - d248f4e39a1fca56c5ea429dca5af190e28c56cb

The fix will be available with the upcoming 2.3.0 release.

**Comment by harshvardhanmalpani** [comment]
This issue is still present in 2.2.4. None of exchange rate providers work
