### ISSUE TITLE
Stock item save after event not firing

### ISSUE THREAD

**Issue by Danielc3** [magento/magento2#8073]
### Preconditions
Magento v.2.1.2

### Steps to reproduce
1. Create an observer for the event cataloginventory_stock_item_save_after.
2. Place breakpoint within observer and trigger saving of a stock item.

### Expected result
1. Xdebug gets into observer.

### Actual result
1. It does not. This is due to an incorrectly named $eventPrefix variable in \Magento\CatalogInventory\Model\Stock\Item. In the abstract model class         
$this->_eventManager->dispatch($this->_eventPrefix . '_save_after', $this->_getEventData()); is used to trigger the event, notice the underscore in the variable name.

**Comment by fooman** [comment]
It's already fixed in develop with https://github.com/magento/magento2/commit/bffd1c01d5f0ba22719e09af6323a12c186c3803

**Comment by Ctucker9233** [comment]
@fooman @veloraven What version of Magento will have this fix?

**Comment by ShirishRam** [comment]
@veloraven Do we have any workaround for this? Not sure why the fix is not included yet in the latest release (2.1.8)

**Comment by czettnersandor** [comment]
It looks like the afterSave() method is not being called anywhere in the code in vendor/magento/framework/Model/AbstractModel.php

Very strange indeed as it supposed to run when you call save() on the model.

**Comment by orlangur** [comment]
@ShirishRam because not every fix in `develop` was backported to `2.1.x`. Please check https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 out. So, having knowledge where a bugfix resides in `develop` branch the best approach is to create a backport PR to `2.1-develop` branch (it will be included in next 2.1.x release, until then you can apply a well-tested fix manually to your codebase).

@czettnersandor model is not responsible for saving itself anymore (`save` is deprecated), `afterSave` is called in `\Magento\Framework\Model\ResourceModel\Db\AbstractDb::processAfterSaves`.

**Comment by magento-engcom-team** [comment]
@Danielc3, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by Ctucker9233** [comment]
@magento-engcom-team Give that this issue was reported against 2.1 and is still not fixed in 2.1, can we expect a backport sometime soon?

**Comment by orlangur** [comment]
@Ctucker9233 I doubt this issue is severe enough to be backported but as I said earlier, backports are always welcomed from Community members.
