### ISSUE TITLE
Free Shipping Method not showing in backend

### ISSUE THREAD

**Issue by umang-ranium** [magento/magento2#8100]
### Preconditions

1. I am using Magento ver. 2.1.2 facing the same issue, free shipping is not showing up for backend orders i have multiple stores.

### Steps to reproduce

1. Go to sales order
2. Create Order
3. New customer fill up the details click on get shipping method flat rate is shown, free shipping is not showing up

### Expected result

1. See Free shipping in backend order

### Actual result

1. Free shipping not showing up

**Comment by veloraven** [comment]
@umang-ranium thank you for your report.
This issue is already fixed in develop branch and the fix was ported to 2.1 and 2.0.
The fix will be available in one of following patch-releases.

**Comment by deepak-netwin** [comment]
@veloraven I'm facing this issue in Magento 2.1.5. It seems that issue is still there.
Can you please tell me the files to be changed for this fix?

**Comment by deepak-netwin** [comment]
@veloraven Even flat rate and table rates are not showing at backend on magento version 2.1.4. Do you know the fix for this?
