### ISSUE TITLE
A products' category assignment gets lost when saving product in store scope

### ISSUE THREAD

**Issue by andreaskoch** [magento/magento2#8118]
# A products' category assignment gets lost when saving product in store scope

When saving a product in store scope instead of the default scope the category assignment gets lost.

## Preconditions

- Magento CE 2.1.3 or Magento EE 2.1.2
- PHP 7.0.14
- Nginx 1.11.8

## Steps to reproduce

1. Fresh installation of the Magento 2.1.3 CE with sample data

  ```bash
  composer clearcache
  composer create-project --ignore-platform-reqs --repository-url=https://repo.magento.com/ magento/project-community-edition magento2ce
  cd magento2ce

  composer require --ignore-platform-reqs arvatoscm/dockerize-magento2
  chmod +x bin/*
  bin/console exec sampledata:deploy
  bin/console install magento2ce.local
  ```

2. Goto the backend and create a second store and store view: `Backend > Stores > Settings > All Stores`

  ![Screenshot: Create a new store and store view](https://cloud.githubusercontent.com/assets/247364/21897298/7bda4f78-d8e9-11e6-9276-dbc9c7c1d2ab.gif)

3. Enable "Add Store Code to Urls" in the system configuration (`Backend > Stores > Settings > Configuration > General > Web > Url Options`)

  ![Screenshot: Enable "Add Store Code to Urls"](https://cloud.githubusercontent.com/assets/247364/21897315/85ccbc46-d8e9-11e6-8b15-d847fbd36262.png)

4. Change the scope of the `category_ids` product attribute from `Global` to `Web Site`

  ![Screenshot: Scope of the category_ids attribute changed to "Web Site"](https://cloud.githubusercontent.com/assets/247364/21897322/8d8ee436-d8e9-11e6-95dd-0d835745b335.png)

5. Clear the caches and reindex
6. Goto the frontend to the `Gear > Bags` category of the new store

  ![Screenshot of the Gears/Bags category on the newly created second store view](https://cloud.githubusercontent.com/assets/247364/21897340/99d182a8-d8e9-11e6-8e3b-b98c41b4fade.png)

7. Goto the backend and open the `Joust Duffle Bag` sample product (id: 1) and switch the scope to the newly created "second store"

  ![Switch the store scope to "second store" for the Joust Duffle Bag in the backend](https://cloud.githubusercontent.com/assets/247364/21897354/a4856156-d8e9-11e6-9bb9-de9a233d0b25.png)

8. Change something (e.g. the product description)
9. Click "Save"
10. The "Categories" field that previously contained "Gear" and "Bags" is now empty.

  ![The categories attribute is empty after the save](https://cloud.githubusercontent.com/assets/247364/21897372/aec0e96a-d8e9-11e6-94ee-8a7f324b8571.png)

11. Goto the `Gear > Bags` in the frontend. The `Joust Duffle Bag` product disappeared from the category.

  ![Joust Duffle Bag is no longer assigned to the category Gear/ Bags`](https://cloud.githubusercontent.com/assets/247364/21897392/b9509ac4-d8e9-11e6-9148-0f06e77233b7.png)

## Expected result

The category assignment should not get lost when saving a product in a different store scope.

## Actual result

The category assignment gets lost when saving a product in a different store scope (ꜛsee "Steps to reproduce").

**Comment by LSERRE** [comment]
Got the same issue on 2.1.7

**Comment by dnunez24** [comment]
Same here on 2.1.7

**Comment by magento-engcom-team** [comment]
@andreaskoch, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by gabriel3iri** [comment]
@magento-engcom-team the issue wasn't fixed on 2.2.0, also it's happening in 2.2.2, any news on this?
