### ISSUE TITLE
Unknown column quantity_and_stock_status

### ISSUE THREAD

**Issue by gputignano** [magento/magento2#8174]
### Preconditions

1. PHP 7.0.14
2. MySQL 5.6.28-76.1-log
3. Magento 2.1.3 with imported database from a magento 1.9.3.1

### Steps to reproduce
1. Insert in CMS Home Page a Catalog Product List Widget with condition Quantity is In Stock

### Expected result
1. I expect in Home Page a list of in stock products

### Actual result
1. I get There has been an error processing your request
Exception printing is disabled by default for security reasons.
Error log record number: 803239251202

2. In report file I get:
a:4:{i:0;s:604:"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.quantity_and_stock_status' in 'where clause', query was: SELECT COUNT(DISTINCT e.entity_id) FROM `catalog_product_flat_1` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(`e`.`quantity_and_stock_status`, 0) = '1') ))";i:1;s:8891:"#0 /home/account/domains/example.com/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)

**Comment by naydav** [comment]
Thanks
We've created internal ticket MAGETWO-63422 to address this issue.

**Comment by Frits1980** [comment]
Is that attribute a boolean? Because I'm missing all boolean attributes in my flat data tables.

**Comment by magento-engcom-team** [comment]
@gputignano, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by BarnyShergold** [comment]
@okobchenko @magento-engcom-team - We've got this problem in a 2.1.10 site, please can you tell me how you fixed this as I cannot find the PR or commit relating to this Issue

We are getting this as a different error -
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_quantity_and_stock_status.value' in 'where clause', query was: SELECT COUNT(DISTINCT e.entity_id) FROM `catalog_product_flat_1` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_product_entity` AS `product_entity` ON product_entity.entity_id = e.entity_id AND (product_entity.created_in <= 1 AND product_entity.updated_in > 1) WHERE (((IFNULL(`e`.`entity_id`, 0) IN (SELECT `catalog_category_product`.`product_id` FROM `catalog_category_product` WHERE (category_id IN ('243')))) AND(IFNULL(`at_quantity_and_stock_status`.`value`, 0) = '1') )
```

**Comment by genyuk** [comment]
Hi
When we switch to "Flat Products" we still see the same error on Magento 2.2.2 CE (See the error below).
How it was "fixed"?

Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.quantity_and_stock_status' in 'where clause', query was: SELECT COUNT(DISTINCT e.entity_id) FROM `catalog_product_flat_1` AS `e`
INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2'
INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1 WHERE (((IFNULL(`e`.`quantity_and_stock_status`, 0) = '1') AND(IFNULL(`e`.`entity_id`, 0) IN (SELECT `catalog_category_product`.`product_id` FROM `catalog_category_product` WHERE (category_id IN ('407')))) AND(IFNULL(`e`.`status`, 0) = '1') )) AND (stock_status_index.stock_status = 1) at /var/www/svm/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.quantity_and_stock_status' in 'where clause' at /var/www/xxxx/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"}

**Comment by BarnyShergold** [comment]
The problem is more wide ranging. If you have Flat Products on and the you use a widget on a page where a condition is based on an attribute that is NOT on the Flat Product table (Product Listing = Off) then the error will occur as Magento is not building the query correctly.

**Comment by genyuk** [comment]
Thanks for the tip. We do have a widget which filter out products by availability (instock=1) and it cause this MySQL error.
Could you please clarify what "(Product Listing = Off)" mean? Is it a setting in Magento?

**Comment by BarnyShergold** [comment]
@genyuk 
Edit the appropriate attribute
Click on the "Storefront Properties" tab
Second option from the bottom - "Used in Product Listing"
Switch to yes, save and then CLI reindex.
Your widget should then work - but you can't do this with the quantity_and_stock_status attribute (it's a special compound one)
