### ISSUE TITLE
"Save to Address Book" in Admin checkout causes duplicate address book entries

### ISSUE THREAD

**Issue by lisamych** [magento/magento2#8181]
Customer address is being duplicated in the address book when "Save to Address Book" is chosen during checkout in the Admin screen. 

### Preconditions
1. Magento 2.1

### Steps to reproduce
1.  Create an order for a customer in Admin.  Menupath:  Sales -> Orders -> Create New Order OR Customers -> All Customers - > (select a customer) -> Create Order 
2.  In the Billing or Shipping address area, choose an existing address.  
3.  Optional - Change address information. 
3.  Click "Save to Address Book". 

Image indicates current entries in address book and selected address, plus the updated address information.
![address checkout](https://cloud.githubusercontent.com/assets/25203011/22070758/1ae8d186-dd6b-11e6-8833-210c77ff5af7.jpg)

### Expected result
1.  The existing address entry would be updated within the address book.  

### Actual result
1.  The changes are saved into the existing address book entry, and a new address book entry is created.  So, two entries exist.  (The duplicate entry is created regardless of the address being changed. )

Image indicates duplicate address book entries for the customer after order has been submitted.
![address after](https://cloud.githubusercontent.com/assets/25203011/22070925/95a26356-dd6b-11e6-95a8-5ebaf6d041f1.JPG)

**Comment by 1408sheva** [comment]
Internal ticket MAGETWO-69934 was created;

**Comment by php-cuong** [comment]
@lisamych I got same this errors as you.

There are any updates for this issue?

Thanks!

**Comment by lisamych** [comment]
@php-cuong  No, we haven't heard anything back from Magento, though it appears that the issue has been acknowledged by them.  We ended up doing custom coding to fix this.

**Comment by php-cuong** [comment]
@lisamych You can put your codes here? :) thanks

**Comment by magento-engcom-team** [comment]
@lisamych, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by JeremyPlease** [comment]
I'm experiencing the described issue in v2.2.5. 
@magento-engcom-team Was this issue fixed in 2.2 or 2.3 branch?

**Comment by tuyennn** [comment]
@magento-engcom-team Please specific which commit related to the fixes

**Comment by wjpbill** [comment]
I'm getting this in Magento 2.3.3

Every time I create an order in the admin, it duplicates the customers address in their address book

Did this get fixed?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29856` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tuyennn** [comment]
The last fix related to this issue was 2d007bed2fc42324b9c71f858e3e833c94f58bb4
MAGETWO-59997: Shipping address duplicates if entered credit card was incorrect during checkout via Braintree

**Comment by erikhansen** [comment]
For anyone else who is running into this issue: The commit above is pretty large and doesn't look specifically related to this issue. I worked around this issue by applying a one-line patch. Details [here](https://github.com/magento/magento2/issues/22596#issuecomment-571687836).

**Comment by krnshah** [comment]
Thank you @tuyennn and @erikhansen for the comments, but your suggested changes are already merged in 2.3.3 and still we are facing this issue.

Do we have any other suggestion?

**Comment by erikhansen** [comment]
@krnshah The change I mentioned has _not_ been merged into 2.3.3, as it's my own custom workaround. I'd recommend taking another look at [the comment](https://github.com/magento/magento2/issues/22596#issuecomment-571687836) I linked to.

**Comment by krnshah** [comment]
@erikhansen yes, your changes will not save the new address every time. but if we change something in existing address and checked the checkbox it will "add the new address".

Instead of that it should be update the current address.

Please share your thoughts. if i am wrong.

**Comment by atIOCrON** [comment]
Any update on this, Magento?

How is it possible a bug like this gets reported in Jan 2017 and in Jan 2020 it still isn't fixed?

We have staff on the phone all day every day placing orders and inadvertently filling customers accounts with duplicate addresses.

This lack of action on the part of Magento is seriously making me wish we'd chosen another platform.

If @erikhansen can come up with a workaround in a one-line patch how is it possible that Magento haven't done anything?

**Comment by shilpsauce** [comment]
We are also running into this issue. Any updates?

**Comment by sdzhepa** [comment]
@lisamych @jiten-patel 

Just checked this issue on the lates `2.4-develop` branch
It seems the issue has been already fixed and case works as expected.

Please confirm that we can close it or share additional details.

My test flow:
1. Test Customer with address in book
![issue_8181](https://user-images.githubusercontent.com/3409584/83548515-82ea5b00-a4c9-11ea-9a49-f7309e5d0406.png)

2. Create new order; select address and edit it during order creation
![issue_8184_2](https://user-images.githubusercontent.com/3409584/83548652-b62cea00-a4c9-11ea-9aa7-2d57815a69a1.png)

3. Place order and check test Customer address book

- OK: Old address is not updated
- OK: new address(based on edited fields) are created


![issue_8181_result](https://user-images.githubusercontent.com/3409584/83550501-8df2ba80-a4cc-11ea-835a-753e81ff32af.png)

**Comment by lenaorobei** [comment]
Closing this issue with "Cannot reproduce" resolution. P{lease feel free to reopen if you are still experiencing it using `2.4-develop` branch. Thank you.

**Comment by killoff** [comment]
The issue is still being reproduced on 2.4.1 (we upgraded on 16 Oct 2020)

**Comment by ni-bschmitt** [comment]
Same, still an issue - when creating an order via the Magento backend, addresses are always duplicated in case you don't uncheck 'save in address book'.  I guess That's not expected and a bug, so @lenaorobei re-open.

Steps to reproduce:
* Create an order via the backend for an existing customer already having a single address available 
* Select the existing address during checkout 
* Create order

Expected:
* Address is not duplicated

Result:
* Two customer addresses are now assigned to the account containing the same values

Reproduced on Magento ver. 2.4.1-p1

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@ni-bschmitt Just checked on https://2ed8af33024e5452bc294f18ecc55f32-2-4-develop.instances.magento-community.engineering/admin_52b6
Issue is not reproduced.
Could you check on instance provided by Magento?

**Comment by ni-bschmitt** [comment]
@Den4ik thank you for the support. Maybe the links are expired already, getting a 403 when clicking in them.

**Comment by Den4ik** [comment]
> @magento give me 2.4-develop instance

**Comment by ni-bschmitt** [comment]
@Den4ik the key difference is that **Add to address book** is by default unchecked, whereas it's **not** at the version I have (is there a configuration I can adjust?).

When I check *Add to address book* even if I selected *Select from an existing customer address* the address is duplicated.

# Select existing address
![image](https://user-images.githubusercontent.com/58559970/117039957-a46f4a80-ad09-11eb-84d0-03446a3ed76f.png)
# Add the address book
![image](https://user-images.githubusercontent.com/58559970/117039975-a6d1a480-ad09-11eb-8c15-79b62c4049a7.png)
# Duplicated
![image](https://user-images.githubusercontent.com/58559970/117039917-9a4d4c00-ad09-11eb-93b3-636c0f1fdb4b.png)

It might be a question of UX but those two things are misleading. It's good it's not checked by default in the latest development branch.

**Comment by Den4ik** [comment]
@ni-bschmitt  Thanks for details. Let me recheck it again

**Comment by jaykobi** [comment]
Hi @ni-bschmitt 

in the screenrecord you do something that is not related to the question. What you do is:  Create another address with different information. That address is saved correctly.

But the problem is something different. When you select the address form the dropdown and do not change anything, the address also gets saved and then there are **two identical entries** in the address grid. 

Since the checkbox is, in many versions of Magento2 (also in mine, 2.3.6-p1), checked by default, addresses get duplicated with every admin order. (At least if the problem is no known and the checkbox is not unchecked manually.)

**Comment by chinhnm** [comment]
I still got this duplicate billing address in checkout when override billing-address.html in M2.4.5-p1. Do anyone have solution for this? Thanks.

**Comment by hewgim** [comment]
It looks like the latest versions of Magento have the Add to Address Book checkboxes as unchecked which prevents duplicate addresses entries from being created. However, this leads to a new problem. When an order is created in admin for a NEW customer, the admin user has to remember to check the Add to Address Book checkboxes to save the new customer's addresses. If they forget (which they do all the time) the customer record is saved without any address records which is not that helpful when the customer orders again in the future. Doesn't look like this functionality has been properly thought through. I would have thought than in most cases where you are explicitly creating a new address e.g. because it's a new customer or because you explicitly want a new address, that the Add to Address checkboxes should be checked by default, but where you are dealing with an existing address, the Add to Address checkboxes should be unchecked to avoid duplicates.
