### ISSUE TITLE
Rest API attribute set updating not working as expected

### ISSUE THREAD

**Issue by NotAndD** [magento/magento2#8194]
### Preconditions

1.  Install Magento 2.1.3 with sample data.
2. Set up Rest integration.

### Steps to reproduce

1. Try to update an attribute set from /V1/products/attribute-sets/{attributeSetId} with a PUT request, inserting in the body ONLY the not-optional parameters (as explained in the documentation).
```
{
"attribute_set": {
"attribute_set_name":"Updated Name",
"sort_order":0 }
}
```
and with an existing attribute set id as url parameter

### Expected result

1. The attribute set with given attribute set id gets updated with the new name

### Actual result

1. It doesn't get updated and magento answer with 
`{"message":"Provided Attribute set non product Attribute set."}`

### Why
1. Field entity_type_id is NOT optional in the PUT request, differently from what the documentation says.
2. If field attribute_set_id is only in the url parameter and NOT in the body, instead of updating the attribute set, a new attribute set with the given fields is created.
3. Only if both fields attribute_set_id and entity_type_id are given in the body, the request is succesful and the attribute set with the given id in the url parameter is updated.

**Comment by magento-engcom-team** [comment]
@ziliquas, thank you for your report.
We've created internal ticket(s) MAGETWO-81147 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @ziliquas. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1233 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - [0eb2e9494b3e2879d6df5c2eb2f5dbb88a963e27](https://github.com/magento/magento2/commit/0eb2e9494b3e2879d6df5c2eb2f5dbb88a963e27)

The fix will be available with the upcoming 2.2.5 release.

**Comment by jannath-hussain** [comment]
use this api
/V1/eav/attribute-sets/:attributeSetId
with payload of
{
"attribute_set": {
"attribute_id" : 10,    // whatever attributesetid u have..
"attribute_set_name":"Updated Name",
"sort_order":0 }
}

**Comment by anowave** [comment]
I believe there is still an issue. 

$result = $attributeSet->getEntityTypeId() === $productEntityId; is returning false because:

$productEntityId = $this->eavConfig->getEntityType(\Magento\Catalog\Model\Product::ENTITY)->getId(); returns a string while 

$attributeSet->getEntityTypeId() is an integer and the type comparison fails.
