### ISSUE TITLE
Translation issues with the customizable options

### ISSUE THREAD

**Issue by Buy-bg** [magento/magento2#8251]
### Preconditions

1. Magento ver. 2.1.2
2. 

### Steps to reproduce

1. Set different stores - English, Deutch
2. Create a product - downloadable in this case
3. Create customizable options 
4. Set options'content for one of the versions or for the default store in English and press Save
5. Translate the options'content for the other store, for example the Deutch view store and press Save
![language issues 1](https://cloud.githubusercontent.com/assets/25318720/22243251/317fb162-e22f-11e6-955c-1ac96ddcecfb.png)
![language issues 2](https://cloud.githubusercontent.com/assets/25318720/22243252/31822ff0-e22f-11e6-8bdb-00c04c963a5a.png)
![language issues 1](https://cloud.githubusercontent.com/assets/25318720/22243289/5f8d05fa-e22f-11e6-96b3-f0cc13c5e591.png)
![language issues 2](https://cloud.githubusercontent.com/assets/25318720/22243303/6cc4f3fe-e22f-11e6-98d3-32a08119bd62.png)

6. Check the Default store view or the English store view - the options' content will be in German, not in English 

### Expected result

1.  The content should be in the right language according to its store view - In the Default and English store view should be in English, in the German store view should be in German

### Actual result

1. The content set last in whatever view store ( english, german or default) is visualized everywhere ( in the three stores) 
[Screenshot, logs]

**Comment by Buy-bg** [comment]
Hellooo, 
Is there anybody out there???

**Comment by Buy-bg** [comment]
Hi there, 
As there has been no sign of support or any information, we would like to receive the money we have paid back. Without this fixture fixed the whole online store may become useless.

**Comment by Ctucker9233** [comment]
@Buy-bg What money did you pay? If you bought the Enterprise Edition I would suggest you post a ticket in their system. I don't work for Magento, but it sounds like either a problem with cookies or perhaps there is something misconfigured in the store view. If you could post a screen shot of how you have your store views set up, I'll try to help you.

**Comment by audexpro** [comment]
@Buy-bg You've solved the problem? I have the same problem!

**Comment by veloraven** [comment]
Internal ticket was created for this issue: MAGETWO-69905

**Comment by Buy-bg** [comment]
Hello, does the creation of the internal ticket mean that the issue will now be reviewed and we can expect some actions :) ?

**Comment by audexpro** [comment]
I solved by replacing these files  https://github.com/magento/magento2/commit/0942a9a85193b8cac9b61af5ef0f44a6be3e843f

**Comment by Buy-bg** [comment]
Thanks a lot, man :) :) :) We will try that for sure :+1:

**Comment by audexpro** [comment]
File https://www.dropbox.com/s/avq2kub7f6qs2ob/Fix%20Customizable%20Options.zip?dl=0

1. Backup your store database and web directory.
2. Log into your hosting space via a FTP software. ie, FileZilla
3. Unzip Files and upload all to Magento 2 root directory
4. Upgrade: php bin/magento setup:upgrade
5. Flush cache: php bin/magento cache:flush
6. Cleancache: php bin/magento cache:clean

**Comment by Userr017** [comment]
> audexpro - I solved by replacing these files 0942a9a

I tried upload these files but now i cannot add Customizable Options. How fix problems? Magento 2.1.7

Errors: 
1. no such entity
2. Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`DATABASE-NAME`.`catalog_product_option_title`, CONSTRAINT `CAT_PRD_OPT_TTL_OPT_ID_CAT_PRD_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `catalog_product_option` (`optio), query was: INSERT INTO `catalog_product_option_title` (`option_id`, `store_id`, `title`) VALUES (?, ?, ?)

**Comment by HedonieBrazil** [comment]
Look like there is 18 files changes (on github). in yours zip package i found 6 files changed...

I replaced your files (6 files) on vendor folder directly and it work fine for me. Thanks !! (magento version 2.1.7)

Do you know how to generate the vendor patch diff files from github changes ?

**Comment by Userr017** [comment]
@HedonieBrazil 

Yes, it works with magento 2.1.8 just edit 6 files! Thanks!

**Comment by HedonieBrazil** [comment]
I just realized i had same problem as you !!

Errors:

no such entity
Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (DATABASE-NAME.catalog_product_option_title, CONSTRAINT CAT_PRD_OPT_TTL_OPT_ID_CAT_PRD_OPT_OPT_ID FOREIGN KEY (option_id) REFERENCES catalog_product_option (optio), query was: INSERT INTOcatalog_product_option_title(option_id,store_id,title`) VALUES (?, ?, ?)

I am going to update magento then. Thanks !

**Comment by piavgh** [comment]
Hi @Userr017 , @HedonieBrazil : do you mean that those 6 files fix are only work with 2.1.8 version?
I tested with 2.1.7 version and it works great, when just save the product or when I add a new Customizable Options.
Thank you.

**Comment by HedonieBrazil** [comment]
it don't work for the version 2.1.7 for me

**Comment by piavgh** [comment]
@HedonieBrazil : in which case it doesn't work for you?

**Comment by HedonieBrazil** [comment]
i got the same error as @Userr017 went i tried to add new option and save the product i got this error : 

Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (DATABASE-NAME.catalog_product_option_title, CONSTRAINT CAT_PRD_OPT_TTL_OPT_ID_CAT_PRD_OPT_OPT_ID FOREIGN KEY (option_id) REFERENCES catalog_product_option (optio), query was: INSERT INTOcatalog_product_option_title(option_id,store_id,title`) VALUES (?, ?, ?)

when i try to import an option from an other products and save. i got this one

no such entity

**Comment by magento-engcom-team** [comment]
@Buy-bg, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by qaniel** [comment]
This issue came back with vengeance on version 2.4...
I have the same issue now, I'm importing product customizable options into different products but it only takes the default one and ignore the options created per store view :(

**Comment by ValeSauer** [comment]
Still not working in Magento ver. 2.4.2-p1

**Comment by thijs-kuipers** [comment]
Still broken
