### ISSUE TITLE
Tier price not applied in cart/checkout

### ISSUE THREAD

**Issue by FerihumF** [magento/magento2#8267]
### Preconditions

1. Magento 2.1.2
2. PHP 5.6.28

### Steps to reproduce

1. Add product with global price e.g. 169€ and tier price for "Retailer" with quantity 1 and price e.g. 135.2€
2. Login with customer having group "Retailer"
3. Go to product created in 1)
4. Verify that price is reduced (see screenshot in actual result)
5. Add to cart

### Expected result

1. The price of item in cart and checkout being the reduced price of 135.2€

### Actual result

1. Tier price is not applied (neither in cart nor checkout), standard price of 169€ is used
<img width="198" alt="bildschirmfoto 2017-01-25 um 08 43 35" src="https://cloud.githubusercontent.com/assets/4960238/22282245/770d34a0-e2db-11e6-8250-f7a7cebc5b97.png">
<img width="190" alt="bildschirmfoto 2017-01-25 um 08 43 44" src="https://cloud.githubusercontent.com/assets/4960238/22282296/c62d248c-e2db-11e6-9c50-eacad7720765.png">

**Comment by veloraven** [comment]
@FerihumF thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
I see that all necessary information is already present but it is much easier to read and understand the issue when it is well-formatted.

**Comment by FerihumF** [comment]
@veloraven 
thank you, updated the issue.

**Comment by miakusha** [comment]
Hi @FerihumF, thanks for report but I cannot reproduce issue.
Can you reproduce it on clean Magento without any custom modules or theme?

**Comment by sdgobinda** [comment]
Hi @FerihumF 

I am getting the same kind of issue. If your issue resolved could you please help me.

**Comment by renatolovato** [comment]
Hi, guys!

The problem is, Magento for some reason hasn't set up the customer group id for the simple product correctly.

This is a quick fix that you can apply, until Magento devs solve this:

You need to change the file **vendor/magento/module-catalog/Model/Product/Type/Price.php**

**From:**

```
/**
     * @param Product $product
     * @return int
     */
    protected function _getCustomerGroupId($product)
    {
     
        if ($product->getCustomerGroupId() !== null) {
            return $product->getCustomerGroupId();
        }

        return $this->_customerSession->getCustomerGroupId();
    }
```

**To:**

   ```
 /**
     * @param Product $product
     * @return int
     */
    protected function _getCustomerGroupId($product)
    {
        if($this->_customerSession->isLoggedIn() && $this->_customerSession->getCustomerGroupId() != $product->getCustomerGroupId())
                $product->setCustomerGroupId($this->_customerSession->getCustomerGroupId());

        if ($product->getCustomerGroupId() !== null) {
            return $product->getCustomerGroupId();
        }

        return $this->_customerSession->getCustomerGroupId();
    }
```

**Comment by magento-engcom-team** [comment]
@FerihumF, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by damien-lechopier** [comment]
Hi,

I allow myself to reopen this issue.
I encounter the same problem on Magento v2.2.2 and PHP 7.0

Tier price display good on product page but when I put article in cart, the price is base price.
I note that the customer group id in session is lose when I put my product in cart. 
When I display session data for the session after cart, it take the default group id for my customer.

Is anyone enconter same issue?
I tried the @renatolovato renatolovato quick fix but it dosen't fix the problem for me.

Please help
Thanks

**Comment by webspeaks** [comment]
Having this issue on Magento 2.2.2 and PHP 7.0
Seems to be a bug :(

**Comment by masterkinou** [comment]
Had the same issue with Magento 2.1.12 and PHP 7.0

The fix renatolovato proposed fixed this issue.

**Comment by webspeaks** [comment]
For me it was due to a third party extension. I removed that extension and now it is fixed.

**Comment by RedDevilEvo** [comment]
I had the same issue with Magento 2.1.7.

No third party extension.

Also i confirm that the fix from @renatolovato  is working great.  THANK YOU.

**Comment by jvhost** [comment]
@damien-lechopier I'm still having this bug too .. Magento 2.2.4 .. the "fix" partially works if I force it to return the wholesaler group, and as long as I don't change anything in the estimator, it "looks" fine, but as soon as it recalculates, it does the exact same thing as yours - it loses the logged in customer's group.  Does anyone know what route the recalculation of the totals uses?

**Comment by jvhost** [comment]
@webspeaks Hi webspeaks, which 3rd party extension did you remove by chance?

**Comment by jvhost** [comment]
Hi guys .. FYI, I'm a lot closer now.  The problem is in another getCustomerGroupId .. in /vendor/magento/module-quote/Model/Quote.php .. this is where it goes every time there's an update to the quote.

Just to test it, I commented out the following:

/*        if ($this->hasData('customer_group_id')) {
            return $this->getData('customer_group_id');
        } elseif ($this->getCustomerId()) {
            return $this->getCustomer()->getGroupId();
        } else {
            return GroupInterface::NOT_LOGGED_IN_ID;
        }
*/

and returned 3 which is my customer group that I want, and it worked.  Now .. why is it failing the first 2 if statements and why is it setting the session customer group to the default?  Thoughts?

**Comment by jvhost** [comment]
Sorry .. one more thing I noticed, it is setting the customer group immediately after adding it to the cart, so it's not even the quote that's setting customer group id.

**Comment by jvhost** [comment]
Hi .. I did some more debugging on /vendor/magento/module-quote/Model/Quote.php ... getCustomerGroupId

This function gets called numerous times. Here is some detail about what methods are calling it.  I had 3 items in my cart at the time:

main.INFO: Group id: 3 called by addTierPriceData - from /vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php [] []

main.INFO: Group id: 3 called by setProduct - from /vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php [] []

main.INFO: Group id: 3 called by setProduct - from /vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php [] []

main.INFO: Group id: 3 called by setProduct - from /vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php [] []

main.INFO: Group id: 3 called by execute - from /vendor/magento/framework/Event/Invoker/InvokerDefault.php [] []

_**And the next return is different:**_
main.INFO: Group id: 2 called by _initItem - from /vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php [] []

main.INFO: Group id: 2 called by _initItem - from /vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php [] []

main.INFO: Group id: 2 called by _initItem - from /vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php [] []

I haven't looked further yet but what I did is replace the existing function with the following (pulling the session in first and then getting the customer id:

$this->_customerSession=\Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Customer\Model\Session');

return $this->_customerSession->getCustomer()->getGroupId();

That's when it finally started working!!!  Hope that helps someone and if you can figure out why execute method seems to be changing the customer group id, please share (I verified, it's the same customer id throughout all the calls, just the group id changes).

**Comment by earlelnar** [comment]
> getCustomerGroupId

Hello @jvhost,

In order to fix the issue, try this method, you need to configure "Disable Automatic Group Change Based on VAT ID" to Yes for the customer.

But normally this should not be the case. I tried a fresh install of Magento 2.3.1 and it works fine without doing this method. So I think something like a third party extension or any. 

![image](https://user-images.githubusercontent.com/14094984/66488086-f6290200-eadf-11e9-9bcd-318d37bffaf0.png)

There's also a configuration for this one that upon user registration it will automatically disable that setting

![image](https://user-images.githubusercontent.com/14094984/66533968-64ed7600-eb47-11e9-9da7-a0fb9312894b.png)


Thanks!
MazeStricks
.

**Comment by foreverhydrox** [comment]
Disabling Automatic Group Changes fixed it for me.

**Comment by pedro0506** [comment]
for me none of the alternatives worked. Magento 2.3.5-p1
