### ISSUE TITLE
Sales rule scope changing when multiple rules are applied (with multiple websites)

### ISSUE THREAD

**Issue by OLTC-fperrin** [magento/magento2#8490]
### Preconditions
1. Magento 2.0.11
2. MariaDB 10.0.27 & PHP 5.6.20
3. 3 or more websites configured in Magento
4. 2 or more sales rules applicable simultaneously

### Steps to reproduce
We'll need at least three different websites setup on our Magento; to desmonstrate the behavior we'll need two sales rule applied on two websites with only one in common. Here are some screenshot two illustrate if it's not clear:

The website setup:
![image](https://cloud.githubusercontent.com/assets/16817276/22785492/d3367bb0-eed4-11e6-893f-85488c0b8d59.png)

Two sales rules:
![image](https://cloud.githubusercontent.com/assets/16817276/22785592/2eab8198-eed5-11e6-9141-941dca80f0db.png)

Here we can see I have two rules with only the Main website in common.

20$ off cart | -10% cart over 200$
------------ | -------------
![image](https://cloud.githubusercontent.com/assets/16817276/22785640/7300fa3a-eed5-11e6-9cd0-b05523c3b359.png) | ![image](https://cloud.githubusercontent.com/assets/16817276/22785662/879a2c1e-eed5-11e6-8ffc-b5eaae282d08.png)

Now, if I create an order with both rules applied:
![image](https://cloud.githubusercontent.com/assets/16817276/22785743/dcbca00a-eed5-11e6-9429-1467afea959c.png)

Here is where the mix up happens, if I complete the order Magento will update the rule to update the `times used` field. At this point the `website_ids` are loaded in the Rule's ResourceModel which is done as follows:
vendor/magento/module-sales-rule/Model/ResourceModel/Rule.php:113
```
public function loadWebsiteIds(AbstractModel $object)
{
    if (!$this->websiteIds) {
        $this->websiteIds = (array)$this->getWebsiteIds($object->getId());
    }

    $object->setData('website_ids', $this->websiteIds);
}
```

Since the same resource model is used to load both rules (the resource model is instantiated using the ObjectManager get function):
vendor/magento/framework/Model/AbstractModel.php:475
```
 return $this->_resource ?: \Magento\Framework\App\ObjectManager::getInstance()->get($this->_resourceName);
```

It results in saving both rules with the same array of website_ids therefore the rules are changing scope:

20$ off cart | -10% cart over 200$
------------ | -------------
![image](https://cloud.githubusercontent.com/assets/16817276/22786040/3734f13a-eed7-11e6-9ebe-c53dcd6a5440.png) | ![image](https://cloud.githubusercontent.com/assets/16817276/22786027/23a6e9b6-eed7-11e6-986c-5c903633d1ad.png)

### Expected result
1. Both rules keep their respective scope

### Actual result
1. The rules change scope to whichever one is loaded first

**Comment by rugirl** [comment]
Hi @LTC-fperrin ,
Has this been fixed in Magento 2.0.12?

**Comment by OLTC-fperrin** [comment]
No, as far as I can see, the bug persists in every version including the develop branches

**Comment by rugirl** [comment]
So you mean it's **NOT** fixed in 2.0.12?

**Comment by OLTC-fperrin** [comment]
Sorry I meant "no", fixed the original post

**Comment by rugirl** [comment]
Thanks :)

**Comment by magento-engcom-team** [comment]
@LTC-fperrin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
