### ISSUE TITLE
Unable to save shipping information. Please check input data.

### ISSUE THREAD

**Issue by malikt** [magento/magento2#8544]
### Preconditions

1. Magento version 2.1.2
2. PHP 7.0.13
3. MySQL 5.6.34
4. nginx

### Steps to reproduce

1. Login to account
2. add product to cart
3. Move to checkout page
4. enter address and select shipping method
5. click Next button

### Expected result

1. it should save the info and move to payment page.

### Actual result

1. I get an error `Unable to save shipping information. Please check input data.`
2. and following exception:
`#0/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\ShippingInformationManagement->saveAddressInformation(128, Object(Magento\Checkout\Model\ShippingInformation))
#1/public_html/var/generation/Magento/Checkout/Model/ShippingInformationManagement/Interceptor.php(26): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callPlugins('saveAddressInfo...', Array, Array)
#2 [internal function]: Magento\Checkout\Model\ShippingInformationManagement\Interceptor->saveAddressInformation(128, Object(Magento\Checkout\Model\ShippingInformation))
#3 /public_html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#4 /public_html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#5/public_html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /public_html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#8 /public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}"`

**Comment by korostii** [comment]
That's rather unexpected. Are you sure there aren't any unusual steps missing & I doubt this would get reproduced on a clean installation.
Do you have any 3rd-[arty modules or themes installed? Shipping-related, if I were to guess.
It might also be a case of "address validation went wrong". Could you please provide the test address you've been using and\or try to reproduce this error while using a different address during checkout?

**Comment by malikt** [comment]
yes its unexpected,
Yes third party modules and themes are installed.
 How can i find which fields the error message is referring to?

**Comment by malikt** [comment]
thanks, issue was resolved.

**Comment by puples** [comment]
hello, what is the solution to resolve it ?

**Comment by malikt** [comment]
in my case the date format was conflicting, the date format of calendar was not supported by the date format of database, so i have to match them.

**Comment by paalsoberg** [comment]
I've got this issue as well. But in my case it is due to the email validation. If you have a domain with a .cloud extension, and use this for email - e.g. test@test.cloud - you will get the same issue. Changing to a test@test.com and the order proceeds as normal.

**Comment by congaframe** [comment]
hm.. I got the same error with .shop email  on the CE 2.1.6 
I think this should be classified as a bug.

**Comment by korostii** [comment]
@paalsoberg, @congaframe, Hi. The issue you're referring to is a slightly different one and it's been reported numerous times already, see #4547 and #7697 for example. 
Additionally, it is possible that it might get fixed in 2.2 by changing the validator to only check for the presence of `@` symbol, as suggested in [pull request #9087](https://github.com/magento/magento2/pull/9087)

**Comment by conflicker** [comment]
MAGETWO-64901: Bypassing outdated TLD validation does not solve the issue. I got the same error in CE 2.1.7. Is there a way to validate the email before the user can hit the 2nd step of checkout process?

**Comment by orlangur** [comment]
@conflicker it wasn't backported to `2.1.x`: https://github.com/magento/magento2/search?q=MAGETWO-64901&type=Commits&utf8=✓

**Comment by joe-vortex** [comment]
I got this error while inputting an email address with an invalid domain extension. Might be worth checking that.

**Comment by winterk80** [comment]
paalsoberg you're on to something!
99% sure it's a bug with the email extension not validating in magento correctly. .cloud  .ent  both create the error in 2.1.8.

**Comment by Alok-Finch** [comment]
how you were able to rectify this issue , even i have same issue @malikt

**Comment by winterk80** [comment]
magento has a fix for this, you'll have to contact them for the patch. I'm not sure if the free version has a fix though, we're on enterprise

**Comment by OleksiyOleksiyovych** [comment]
Could someone add this patch (or link to this patch) in this ticket? Thank you!
