### ISSUE TITLE
Bundle option Input Type is Checkbox, User Defined does not work

### ISSUE THREAD

**Issue by dmatthew** [magento/magento2#8674]
### Preconditions

1. Magento CE 2.1.3

### Steps to reproduce

1. Create a bundle product.
2. Add an option with an "Input Type" of "Checkbox", with "User Defined" checked, a "Default Quantity" of 0, and "Is Default" unchecked.

### Expected result

1. On the catalog product view page, the bundle option should have an input box for "Quantity", with the default value of 0.

### Actual result

1. There is no "Quantity" input box.

The Quantity box does appear when you use an Input Type of Drop-down or Radio Buttons, but does not appear for Checkboxes. On the bottom image below, I would expect there to be an input box for the user to select how much quantity they wanted of either product.

<img width="1297" alt="shirts bundle option admin" src="https://cloud.githubusercontent.com/assets/8683207/23479538/a15c284c-fe79-11e6-8b10-da079cfa7a8a.png">
<img width="319" alt="shirts bundle option frontend" src="https://cloud.githubusercontent.com/assets/8683207/23479537/9fac0a08-fe79-11e6-87c6-34d18a639de5.png">

**Comment by vrann** [comment]
@dmatthew what do you mean by "User Defined", just tried to create bundle option on the latest mainline and it does not provide such option. Can you attach screenshot?

**Comment by dmatthew** [comment]
@vrann screenshots attached.

**Comment by okorshenko** [comment]
@dmatthew thank you for reporting the issue. According to User Guide 

> To allow customers to change the quantity of any bundle item, mark the User Defined checkbox of any item that you want changed.

http://docs.magento.com/m2/ce/user_guide/catalog/product-create-bundle.html

**Comment by Lee-Indez** [comment]
I think this is the same issue as : https://github.com/magento/magento2/issues/6873

**Comment by dmatthew** [comment]
From https://github.com/magento/magento2/issues/6873#issuecomment-286454358

> after discussing with Product Owner, it was confirmed that "User Defined" quantity is not allowed for checkbox and multiple-select input types by design.

If this is the case, then it is a bug if the checkbox for User Defined is being shown when it is not allowed.

**Comment by Lee-Indez** [comment]
@dmatthew - I'm with you on this one.  I've put off rewriting the module and messing with the javascript for about a week - looks like I'll have to bite the bullet...

**Comment by lavanyadckap** [comment]
I'm going to start this issue

**Comment by CNSam** [comment]
Is there any progress on this as have come across the same issue in 2.1.7

**Comment by magento-engcom-team** [comment]
@dmatthew, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by welllin** [comment]
@magento-engcom-team 

Hi I've tried to upgrade to 2.2.0 and 2.2.1, and yet I still can't see it working.

What I did see is that the User Defined is only showing when you select dropdowns or radio buttons input types.

Could you please confirm this? :)

**Comment by Richi2293** [comment]
I'm on Magento ver. 2.1.8 and you are right welllin

**Comment by syedsaleem086** [comment]
@magento-engcom-team 

Hi, I've installed fresh Magento2.2.2 still not working. 
Only showing user-defined field for Drop down and Radios

Tested in latest version Magento 2.2.5-develop still not working.
![user_defined](https://user-images.githubusercontent.com/15724424/38598024-5ca12664-3d78-11e8-8e70-bd95d13ea312.png)

**Comment by FredFlitsPaal** [comment]
I encountered the same problem as @syedsaleem086 Is there any news about this problem?

**Comment by jvkranenburg** [comment]
Same problem here on v 2.2.5. Has someone created a quickfix for them self already?
I'm interested ;-)

**Comment by RaphaelBronsveld** [comment]
Since the "user defined" option for checkbox is not visible, by design, we still needed an option for our customers to let the quantity be up to the user.

I made a module where it's possible to change the quantity (for checkbox options).
https://github.com/Itonomy/magento2-bundle-products-change-qty

**Comment by dsomnionline** [comment]
> Since the "user defined" option for checkbox is not visible, by design, we still needed an option for our customers to let the quantity be up to the user.
> 
> I made a module where it's possible to change the quantity (for checkbox options).
> https://github.com/Itonomy/magento2-bundle-products-change-qty

Hi @RaphaelBronsveld 

This solution is not working when you edit the product from a mini cart OR Cart page. It gives the error can you please check and provide the solution for this.

**Comment by hatemdeeb** [comment]
This issue is still exist in Magento v 2.4.6
Can't get bundle qty option set to user defined for checkbox bundle option items.
