### ISSUE TITLE
IO SFTP - wrong constants in write method

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9016]
### Preconditions
Magento 2.1.5

### Steps to reproduce
File upload via SFTP to remote Server

### Expected result
File upload works

### Actual result
Exception thrown:         
Notice: Use of undefined constant NET_SFTP_LOCAL_FILE - assumed 'NET_SFTP_LOCAL_FILE' in
.../magento/vendor/magento/framework/Filesystem/Io/Sftp.php on line 187

Wrong code: $mode = is_readable($source) ? NET_SFTP_LOCAL_FILE : NET_SFTP_STRING;
Should be: $mode = is_readable($source) ? \phpseclib\Net\SFTP::SOURCE_LOCAL_FILE : \phpseclib\Net\SFTP::SOURCE_STRING;

**Comment by veloraven** [comment]
@mb-tec thank you for your report.
This issue has already been fixed in develop #6894 
And we have internal ticket for fixing it in ver. 2.1 - MAGETWO-67470

**Comment by diazwatson** [comment]
It is happening in 2.1.7

**Comment by rikwillems** [comment]
This issue is still present in 2.1.8. I solved it with a preference that overrides the write method according to https://github.com/magento/magento2/commit/db17419f81089df739b6a3a69e9e87ca215c7ecf
provided in #6894.

**Comment by magento-engcom-team** [comment]
@mb-tec, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
