### ISSUE TITLE
Default Store is always used when retrieving sequence value's for sales entity's.

### ISSUE THREAD

**Issue by reztierk** [magento/magento2#9055]
The getReservedOrderId function in `/vendor/magento/module-quote/Model/ResourceModel/Quote.php` and the _beforeSave function in `\Magento\Sales\Model\ResourceModel\EntityAbstract` are using `getStore()->getGroup()->getDefaultStoreId()`, when they should be using `getStore()->getStoreId()`. Causing orders placed on other storeviews to use the prefix/suffix/increment id and sequence tables of the default store.

### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Setup a clean install of Magento 2.1.5 with sample data
2. Add a second store view to the default website
3. Place an order on the second store view

### Expected result

1. An increment id using the prefix from the new store view, and an entry in the sequence_order_2 table

### Actual result

1. An increment id using the prefix from the default store view, and an entry in the sequence_order_1 table

**Comment by jaykobi** [comment]
Those line were introduced two years ago:
https://github.com/magento/magento2/commit/f9559c2d253aa2fed7465aa28a64f10f6e4da5a0
MAGETWO-36935: Orders placed in different store views should not have duplicated IDs

But I don't see why, either. With sequences and the meta table I can precisely crontrol when which increment id is used. But getStore()->getGroup()->getDefaultStoreId() completely breaks this for multiple store views in one group.

One more in the long list of bugs that REALLY need to be fixed asap. 
Thanks for reporting @reztierk.

**Comment by magento-engcom-team** [comment]
@reztierk, thank you for your report.
We've created internal ticket(s) MAGETWO-80977 to track progress on the issue.

**Comment by tdgroot** [comment]
I'm picking up this issue!

**Comment by tdgroot** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
Hi @reztierk 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by domeglic** [comment]
Was this fixed completely? Because one of the classes mentioned by @reztierk is still the same:
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Sales/Model/ResourceModel/EntityAbstract.php#L129

I can only reproduce the bug when creating an order without going through checkout though (integration test).

**Comment by magento-engcom-team** [comment]
Hi @reztierk. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1362 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 4705e23479eae053947c52ee5be6969a79a82079
 - 6d355e033e513cefc390f26417eb2321756b1dce
 - 77f34cf7e3e12f567aa8fdd6918bcf9cd1ffda2f
 - 748ab4db199379ce2154ffb63b9801a8c0d13bb4
 - 90f9d95056b1cd7fe0be036ec72c236bc03738fc
 - 44ca24fdc0d3367515893cf9a8fc1bffcc070140
 - f0b7f2b1708218a8d894178fc9a4f045dfdbdedd
 - c3e1d93db404b63dc38050f9089d2b6a72094085
 - 4810755a4751e3a389e2a39dcbaf55ab72c2149c
 - 4709a222e58918876e2f5b9d28b8f0e5e120d52f
 - a2b9fab4b10421c327b1f323bf222750ac371fb9
 - ac7df33cecf744cf9899067dc62453bc7a15ca50
 - 245238dcbb72b10fad84596399b12b9814295641
 - 2c153c3c428308c1cbc1969bd2eb271913d6551d
 - 48a72fa0d214418a79a5d77d25ead1eb75cbc1c1
 - 625f685c183e0c0a7993ca38c025a079e0e29b47
 - afa4516615808a427be8a160e9cd6ae80c321b27

The fix will be available with the upcoming 2.3.0 release.
