### ISSUE TITLE
escapeHtml not working for tags with attributes

### ISSUE THREAD

**Issue by magentomaniac** [magento/magento2#9223]
### Preconditions

1. Magento Enterprise 2.1.4
2. PHP 7.0.13

### Steps to reproduce
1. Add the following to any template file. Works e.g. in logo.phtml.
`<?php echo $block->escapeHtml('<a href="#">standard link</a>', ['a']); ?>`
compare output with 
`<?php echo $block->escapeHtml('<a>standard link</a>', ['a']); ?>`
2. Replicates with other tags e.g. `<p>` vs `<p class=''>`

### Expected result
1. Tag escaping works regardless of tag attributes and not only for very simple tags such as `<br/>`
HTML: `<a href="#">standard link</a>
    <a>standard link</a>`
### Actual result
![wth](https://cloud.githubusercontent.com/assets/27358520/24963178/c23c4c76-1f95-11e7-951d-209ea61257c7.png)
HTML: `&lt;a href="#"&gt;standard link 
    <a>standard link</a>`

**Comment by digitalredefined** [comment]
Experiencing same issue with CE 2.1.4.  For my issue, I had to change the code 
FROM:  <span data-bind="text: customer().fullname ? $t('Welcome, %1!').replace('%1', customer().fullname) : '<?= $block->escapeUrl($welcomeMessage) ?>'"></span>
TO:  <span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>

Note the data-bind type.

**Comment by drsndodiya** [comment]
This issue is resolved in updated version of magento 2.2 CE not sure in Enterprise version.

**Comment by magento-engcom-team** [comment]
@magentomaniac, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by slackerzz** [comment]
The problem is still present in Magento Commerce 2.4.3:

```php
$html = "<a target='_blank' style='color:red' href='#'>Link text</a>";
<?= $escaper->escapeHtml($html, ['a']) ?>
```

outputs

```html
<a href="#">Link text</a>
```

**Comment by ProxiBlue** [comment]
having issues building magnto for deploy

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yireo/magento2-replace-inventory[4.2.0, ..., 4.2.7] cannot be installed as that would require removing magento/project-community-edition[2.4.3-p2]. They all replace magento/module-inventory-bundle-import-export and thus cannot coexist.
    - yireo/magento2-replace-inventory[4.2.0, ..., 4.2.3] require magento/product-community-edition >=2.4.0 <2.4.3 -> found magento/product-community-edition[2.4.0, ..., 2.4.2-p2] but it conflicts with your root composer.json require (2.4.3-p2).
    - magento/project-community-edition is present at version 2.4.3-p2 and cannot be modified by Composer
    - Root composer.json requires yireo/magento2-replace-inventory ~4.2 -> satisfiable by yireo/magento2-replace-inventory[4.2.0, ..., 4.2.7].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by odrais-amsicorp** [comment]
> 

The Escaper only allows certain attributes: `id`,`class`,`href`,`title` and `style`. Plus for `a` tags, `style` isn't allowed.

The only way I can think of for you to get what you need is to extend your own Escaper.
