### ISSUE TITLE
Color attribute taking swatch instead of Drop down option for configurable options,

### ISSUE THREAD

**Issue by vishveskrish** [magento/magento2#9307]
### Preconditions
1. Magento: 2.1.6

### Steps to reproduce
1. Login to admin-panel and go to the Product >> Attributes. 
2. Created color attribute with Catalog Input Type for Store Owner to "Drop down"
3. Go to the front-end and open any configurable product with COLOR options.
### Expected result
1. It should display Dropdown select box.

### Actual result

1. It is showing swatch. 

Kindly see screenshots.
![screenshot-10 16 16 212 2017-04-19 14-37-19](https://cloud.githubusercontent.com/assets/6836510/25172227/f4c41d86-250d-11e7-8274-b34e196eb34c.jpg)
![screenshot-10 16 16 212 2017-04-19 14-30-41](https://cloud.githubusercontent.com/assets/6836510/25172228/f4c6bd5c-250d-11e7-8a07-7e193cbd9576.jpg)

**Comment by elisabethesbjornsson-vaimo** [comment]
I am also experiencing this issue, after upgrade from 2.1.4 to 2.1.6.

**Comment by lingwooc** [comment]
+1 I had it working originally as a dropdown. Then changed it to a swatch, now I can't go back to a dropdown. The setting saves but the front end ignores it. I assume is is because the extra attributes are created for the options when it is turned into a swatch, then not removed. No amount of cache clearing fixes it.

**Comment by gclift** [comment]
+1 Also had this issue after switching to swatch then back to dropdown. When the product detail page is showing, we're seeing markup with 'swatch-input'. Note, we upgraded from Magento 1.9 to Magento 2.1.6 and imported the data using the magento import tool. It was appearing fine as a drop down until we changed the "Catalog Input Type for Store Owner" from dropdown to Text Swatch.

Markup that appeared after switching to text swatch, and remained after switching back to dropdown:
input class="swatch-input super-attribute-select" name="super_attribute[133]" type="text" value="" data-selector="super_attribute[133]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px"

**Comment by vishveskrish** [comment]
Any one get resolution ?

**Comment by gclift** [comment]
I traced the code back to the isProductHasSwatchAttribute in the Magento\Swatches\Block\Product\Renderer\Configurable class. It's using the SwatchAttributesProvider class to check for swatch data. 

It looks like there is some leftover data in the eav_attribute_option_swatch table after switching back to the dropdown. Once I cleaned out the swatch values that were created when we switched to the text swatch, it worked as expected again. 

To see if there is data, and get the swatch_ids, use this sql query:
Note: Change _YOUR_ATTRIBUTE_ID_ to the id of your attribute.
**SQL** 
```
SELECT o.option_id, o.attribute_id, s.swatch_id
FROM eav_attribute_option AS o
JOIN eav_attribute_option_swatch AS s ON(o.option_id = s.option_id)
WHERE o.attribute_id = YOUR_ATTRIBUTE_ID
ORDER BY s.swatch_id ASC;
```

**Comment by ghost** [comment]
Having this issue also on 2.1.7.

**Comment by imsergiobernal** [comment]
Me too, same issue in 2.1.7

**Comment by mayankzalavadia** [comment]
We are also facing the same issues on Magento 2.1.7. If anyone finds a solution for this issue then please share it with all.

**Comment by lingwooc** [comment]
@gclift gave a manual solution above. It will need some db editing.

**Comment by oleg-onufer** [comment]
Hi @vishveskrish.
Thanks for reporting this issue.
Internal ticket MAGETWO-70321 was created.

**Comment by sdotsuk** [comment]
Using your preferred database editor, navigate and find the table **eav_attribute_option_swatch**

Magento will store a row for each of the swatches you have configured in the Magento Admin.
Pay attention to the **option_id** select each row you want to remove as a swatch not forgetting to remove any other associated rows which contain the same option_id.

Once deleted. Head over to your Magento admin panel, clear the magento cache and static file cache.

I was able to solve my issue in 5 minutes. I hope this helps somebody else

**Comment by gboz17** [comment]
Thanks @sanjeshsodha !!

I can confirm this works.

**Comment by mattdillon100** [comment]
Thanks @sanjeshsodha your solution worked for us.
@magento-team is there any update as to why this happens and when it will be fixed?

**Comment by korostii** [comment]
@wildcard27, well, I could tell you why it happens is this scenario: https://github.com/magento/magento2/issues/9923#issuecomment-310601303

But an official fix might take a couple more months to get implemented and released, speaking optimistically.

**Comment by mattdillon100** [comment]
@korostii So not as simple as programmatically deleting all of the entries in the eav_attribute_option_swatch table relating to the attribute being saved if the frontend type is changed? If so, this could be implemented in a plugin as a 'quick' fix for now.

**Comment by korostii** [comment]
@wildcard27, That might break the actual swatch attributes that should _not_ look like dropdown, so be careful down that road. But yeah, that _might_ work.

Personally, I don't think there's a "quick" solutions here. I mean, there were [whole](https://github.com/magento/magento2/commits/436d046f75309df7005d6bea05d8274a252388c6/app/code/Magento/Swatches/Model/SwatchAttributeCodes.php) [classes](https://github.com/magento/magento2/commits/2.1/app/code/Magento/Swatches/Model/SwatchAttributesProvider.php) written around implementing some parts of the swatches' rendering, it seems to be an interdependent a fragile thing.

I wish the guys at Magento would test this better though. I mean, they have the resources for it and ytet they release this piece of buggy functionality in a *patch* version while ignoring hundreds of safe one-liners that await months for a backport. Frankly, that whole routine makes me somewhat angry every time I stumble upon its results, again and again.

**Comment by saeohioalpha** [comment]
I was able to fix this by:

Step 1: Finding my attribute id by:
SELECT * FROM magento_store.eav_attribute where attribute_code = 'you_attribute_code'

Step 2: Running the SQL Query referenced above to confirm the swatch entries:
SELECT o.option_id, o.attribute_id, s.swatch_id FROM eav_attribute_option AS o JOIN eav_attribute_option_swatch AS s ON(o.option_id = s.option_id) WHERE o.attribute_id = 'you_attribute_id' ORDER BY o.option_id ASC; 

Step 3: Delete the swatch entries. 
For me I didn't have any attributes that should be swatches, so I truncated the eav_attribute_option_swatch table and then cleared all the caches, and my swatches turned into dropdowns. 

If you have more complicated setup with legit swatches, you may want to only delete the results from the query in step 2.

**Comment by magento-engcom-team** [comment]
@vishveskrish, thank you for your report.
We've created internal ticket(s) MAGETWO-70321 to track progress on the issue.

**Comment by vishveskrish** [comment]
Hello @magento-engcom-team,

Do we get the resolution?

**Comment by RakeshJesadiya** [comment]
I am also experiencing this issue, after upgrade from 2.1.3 to 2.2.0
Any update for this issue?

**Comment by s00071609** [comment]
![website](https://user-images.githubusercontent.com/19631643/33376326-5895de0e-d561-11e7-8d92-afba22e933a5.PNG)

What are these blank fields (super attribute) - unwanted fields showing not sure what is wrong with M2.2.1

**Comment by jmtakahashi** [comment]
@s00071609 see this issue [https://github.com/magento/magento2/issues/11387](url)

**Comment by vishveskrish** [comment]
@RakeshJesadiya , Yes I got the resolution

**Comment by eugene-shab** [comment]
#mageconf

**Comment by eugene-shab** [comment]
Closed because duplicate #12695

**Comment by gouravsyscraft** [comment]
Thank you very much @saeohioalpha . You save my day. your solution is working fine but i am confused like each time when i will create configurable product then i need to do this step?

Still magento not resolved this issue?

**Comment by sidolov** [comment]
Hi @vishveskrish. Thank you for your report. 
The issue has been fixed in magento/magento2#12771 by @eugene-shab in 2.2-develop branch
Related commit(s):
 - [39b1ef3a5b5a4741a0c664135b13944c4e7c7b61](https://github.com/magento/magento2/commit/39b1ef3a5b5a4741a0c664135b13944c4e7c7b61)
 - [94539b755992f120927a4760c06c624a0ced07c7](https://github.com/magento/magento2/commit/94539b755992f120927a4760c06c624a0ced07c7)
 - [3d76096a752ff234843890d7a072cd1d64e8c1c2](https://github.com/magento/magento2/commit/3d76096a752ff234843890d7a072cd1d64e8c1c2)
 - [0b079e05ab2e12c004fb1e81bda57817e5f0f14f](https://github.com/magento/magento2/commit/0b079e05ab2e12c004fb1e81bda57817e5f0f14f)
 - [71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79](https://github.com/magento/magento2/commit/71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79)
 - [47b2f4841ae27fa7bde0124e8860493e79c62a92](https://github.com/magento/magento2/commit/47b2f4841ae27fa7bde0124e8860493e79c62a92)
 - [707f1cd34f0f4c905b07658849984d0eb825d6d7](https://github.com/magento/magento2/commit/707f1cd34f0f4c905b07658849984d0eb825d6d7)
 - [9153fe221d7ce9e65a3b082ab9d79c26245f1e0b](https://github.com/magento/magento2/commit/9153fe221d7ce9e65a3b082ab9d79c26245f1e0b)
 - [1bd4acfee8a58b035eef561aaebe94f97990a4a2](https://github.com/magento/magento2/commit/1bd4acfee8a58b035eef561aaebe94f97990a4a2)
 - [f4990277bf9f20227402f4b76e57499873b170ad](https://github.com/magento/magento2/commit/f4990277bf9f20227402f4b76e57499873b170ad)
 - [3fa9ed2485a97972133ddb1f7d7e775f784fe6e4](https://github.com/magento/magento2/commit/3fa9ed2485a97972133ddb1f7d7e775f784fe6e4)
 - [8fa792a1444670e60fe6052c77e7b35684549906](https://github.com/magento/magento2/commit/8fa792a1444670e60fe6052c77e7b35684549906)
 - [7cd7adecf598dd6f9fe6ecd4369208869442387d](https://github.com/magento/magento2/commit/7cd7adecf598dd6f9fe6ecd4369208869442387d)
 - [54ad76c1f48eafbfe16a4e8e3c7669145a190627](https://github.com/magento/magento2/commit/54ad76c1f48eafbfe16a4e8e3c7669145a190627)
 - [bd126512cfe4f139a10ada9136495c1a617df158](https://github.com/magento/magento2/commit/bd126512cfe4f139a10ada9136495c1a617df158)
 - [cb6975c3f57739946cb65acebaf62300def1fa99](https://github.com/magento/magento2/commit/cb6975c3f57739946cb65acebaf62300def1fa99)

The fix will be available with the upcoming 2.2.6 release.

**Comment by prashantvalanda** [comment]
Temporary work around:

Change your attribute to dropdown from swatch from admin

go to database >> table `eav_attribute_option_swatch`

delete all related swatch attribute row from this table

deploy static content and flush cache.

**Comment by ishakhsuvarov** [comment]
Hi @vishveskrish. Thank you for your report. 
The issue has been fixed in magento/magento2#17750 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [0f28b61565c3108281ef24c5f846ba2034e9ba9c](https://github.com/magento/magento2/commit/0f28b61565c3108281ef24c5f846ba2034e9ba9c)
 - [d159921f79c68e9aec489192c223ce5535ff47d9](https://github.com/magento/magento2/commit/d159921f79c68e9aec489192c223ce5535ff47d9)

The fix will be available with the upcoming 2.3.0 release.

**Comment by diamondavocado** [comment]
@ishakhsuvarov I'm still having this issue on 2.3.0. I'm unable to change my attribute type from Text  Swatch to Dropdown, even if I truncate the swatch options table.

**Comment by aliomattux** [comment]
I also had a similar issue but believe the attribute was changed from a dropdown to a text swatch. On the front end, it looks like below. I only found out about this issue by looking through bug reports. After I saw this report, I changed it back to a dropdown and it works again.
Magento 2.3.3
![2020-03-10_23-55-37](https://user-images.githubusercontent.com/1051273/76383729-bc785380-632a-11ea-93f5-e88ab5d12b57.png)
