### ISSUE TITLE
"Use Default Value" gets unchecked, when product data is saved

### ISSUE THREAD

**Issue by justinsamuel92** [magento/magento2#9486]
### Preconditions
1. CE 2.1.4

### Steps to reproduce

1. Open a product in Admin, select a store view, say Default Store View
2. Check any of the 'Use Default Value' checkboxes in 'Search Engine Optimisation'(or any) tab and save product.
3. Click on the Save button to save the product again, without opening/loading the 'Search Engine Optimisation' accordion tab

### Expected result

1. The check boxes must be checked and unchecked as specified.

### Actual result

1. All the checkboxes inside accordions which are not opened/loaded will be reverted to unchecked state.

**Comment by VasylShvorak** [comment]
@justinsyatnam Thanks for reporting this issue. Created internal issue MAGETWO-70217 to investigate and track this issue.

**Comment by hezide** [comment]
same here 2.1.8

**Comment by magento-engcom-team** [comment]
@justinsyatnam, thank you for your report.
We've created internal ticket(s) MAGETWO-70217 to track progress on the issue.

**Comment by BenGlassAtlas** [comment]
Can also replicate, here is a gif for clarity:

![price](https://user-images.githubusercontent.com/8895777/31808948-66ab880e-b56d-11e7-9990-09153b08aab0.gif)

**Comment by LucaGallinari** [comment]
Any update on this? It's really important, our customers are getting mad while doing data entry

**Comment by ansukhorukova** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@ansukhorukova thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Deep256** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@Deep256 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by cadencelabs-master** [comment]
See here for a patch: https://www.cadence-labs.com/2018/03/magento-2-use-default-value-store-view-scope-fix/

The associated module should fix the issue which comes from the url_key autogenerator (for url_key attribute) and then the general issue of attributes in non-opened tabs not having their "use_default_value" flag sent to the server

**Comment by Koc** [comment]
This bug occurs even if we have enabled simple store mode. Even in this case product attribute values copies on some actions (maybe save or duplicate, not detected yet) with `store_id=1`.

**Comment by LouNik1984** [comment]
Hi, the issue is still here on magento 2.2.5

**Comment by warrior7789** [comment]
nobody is able to solve this issue ?

**Comment by hostep** [comment]
Can somebody re-test this on Magento 2.2.6 or 2.2.7? I believe it was fixed in 2.2.6 based on some commits I saw passing by, but I never verified this myself.

**Comment by knelus** [comment]
It's not fixed in 2.2.6 still dealing with this issue

**Comment by warrior7789** [comment]
yes i check in 2.2.6  i also get same issue .. i cant find solution of it

**Comment by hostep** [comment]
Ok, sorry to disappoint (?) the people above, but this really **is** fixed in 2.2.6 and 2.2.7, and also in 2.3.0.

So I just put some time in this, setup clean Magento 2.2.5, 2.2.6, 2.2.7 and 2.3.0 installations and followed the exact steps as outlined by @justinsyatnam on each one of them.
In Magento 2.2.5 I can fully reproduce the problem, but in 2.2.6, 2.2.7 and 2.3.0 the issue is definitely fixed.

My guess is that for the people saying it's not fixed, is that they only test it on products which already have the problem. Upgrading to 2.2.6 will not fix the issue for products which already have the problem, since incorrect data is already stored in the database. The fix will only work for new products created in 2.2.6 or for older products which didn't already have the problem.

Closing the issue.

If someone can prove me wrong by outlining exact steps to reproduce the problem on a clean Magento installation, please go ahead and we can then re-open the issue.

**Comment by warrior7789** [comment]
> Ok, sorry to disappoint (?) the people above, but this really **is** fixed in 2.2.6 and 2.2.7, and also in 2.3.0.
> 
> So I just put some time in this, setup clean Magento 2.2.5, 2.2.6, 2.2.7 and 2.3.0 installations and followed the exact steps as outlined by @justinsyatnam on each one of them.
> In Magento 2.2.5 I can fully reproduce the problem, but in 2.2.6, 2.2.7 and 2.3.0 the issue is definitely fixed.
> 
> My guess is that for the people saying it's not fixed, is that they only test it on products which already have the problem. Upgrading to 2.2.6 will not fix the issue for products which already have the problem, since incorrect data is already stored in the database. The fix will only work for new products created in 2.2.6 or for older products which didn't already have the problem.
> 
> Closing the issue.
> 
> If someone can prove me wrong by outlining exact steps to reproduce the problem on a clean Magento installation, please go ahead and we can then re-open the issue.


check this link i have upload video of my issue you will check i have magento 2.2.7 still got the issue and i create new product as you se in video 
https://streamable.com/i4xa2

**Comment by hostep** [comment]
Thanks for the video @warrior7789! This is not what I saw when I tested 2.2.7, but I'll try to redo the test later today and see if it behaves the same as with you or not.

**Comment by warrior7789** [comment]
but if you install fresh magento 2.2.6  .  its work perfectly but i have upgrade magento 2.1.8 to 2.2.7 

The error i found is while you save i print the data which i get is 

this is Default magento 2.2.6 here we get [use_default] => Array
![default2 2 6](https://user-images.githubusercontent.com/21073575/49719460-38e13a00-fc83-11e8-8cd5-4752c21e125b.png)

this isupgrade from  2.18 to 2.2.6  here i dont  get [use_default] => Array
![myupdate](https://user-images.githubusercontent.com/21073575/49719473-41397500-fc83-11e8-9586-e4cdc93614c5.png)

**Comment by LouNik1984** [comment]
I don't think it's right to mark the issue as closed if upgrading the magento version is not enough to fix it. We cannot install a fresh version any time a new bug is fixed, we can only upgrade the version we have, so if the fix does not work by upgrading then the issue is not fixed therefore it should not be closed in my opinion

**Comment by BenGlassAtlas** [comment]
@hostep I agree with @LouNik1984 - If Magento's stance on this is "You installed Magento 2 before 2.2.6 so just live with it" that is pretty poor.

The issue is not fixed for the huge majority of Magento 2 customers therefore the issue should not be closed.

**Comment by hostep** [comment]
Sure, re-opening, but would anyone be so kind to add exact steps to reproduce, like: setup a clean Magento 2.1.x store, do A, B and C, then upgrade to 2.2.7, and perform D, E and F to demonstrate the problem. That would be very helpful!

I can't be sure about how people's stores are setup, with all kinds of custom code (patches, modules, ...) which might influence this behaviour, therefore finding exact steps to reproduce on a vanilla installation is preferred.

**Comment by warrior7789** [comment]
> @hostep I agree with @LouNik1984 - If Magento's stance on this is "You installed Magento 2 before 2.2.6 so just live with it" that is pretty poor.
> 
> The issue is not fixed for the huge majority of Magento 2 customers therefore the issue should not be closed.

hi @BenSpace48  did you get any solution ? i found issue that is will not send use_default value while you submit the form

**Comment by warrior7789** [comment]
finally i got the solution by adding new code in form.js  this is temporary solution for right now.    
1) /vendor/magento/module-ui/view/base/web/js/form/form.js
    code we add

find this submit function add my code 

  submit: function (redirect) {
            var additional = collectData(this.additionalFields),
                source = this.source;

            _.each(additional, function (value, name) {
                source.set('data.' + name, value);
            });

            **// HACK for product - use default value...
                if($('input[name="product[name]"]').length){
                    // source.set('data.use_default[name]', 1);
                    $(".admin__field-service").each(function(i, v){
                        if($(this).find("input").attr("type") == "checkbox"){
                            var name = $(this).find("input").attr("name");
                            var checked = $(this).find("input").prop("checked");
                            var value = 0;
                            if(checked){
                                value = 1;
                            }
                            source.set('data.'+name, value);
                        }
                    });
                }
            // HACK for product - use default value...**

            source.save({
                redirect: redirect,
                ajaxSave: this.ajaxSave,
                ajaxSaveType: this.ajaxSaveType,
                response: {
                    data: this.responseData,
                    status: this.responseStatus
                },
                attributes: {
                    id: this.namespace
                }
            });
        },

**Comment by BenGlassAtlas** [comment]
I'm not currently working on Magento so I'm unable to test or debug sorry, as far as I'm aware we still have the issue with no workaround.

I would advise overwriting or extending that file rather than editing the core.

**Comment by dwaynebartels** [comment]
What is the status of this issue?

Updateing products on storeview level using REST API also unchecks al the boxes. 
Even those who we didnt touch.

**Comment by padmapriya-thattaivaradhan** [comment]
Any update on this issue? It happens when I check "Use Default Value" on store view and click save. The checkbox remains unchecked.

**Comment by hostep** [comment]
@dwaynebartels: as far as I'm aware this got fixed in 2.2.6 for the adminhtml "use default value" checkboxes. But some people in here commented this isn't true but then fail to provide exact steps to reproduce on 2.2.6 or 2.2.7, so the status is a bit unknown at the moment I'm afraid.

As for REST API calls, that's a different bug, you can follow these issues:
- for products: https://github.com/magento/magento2/issues/9186
- for categories: https://github.com/magento/magento2/issues/17186

**Comment by cadencelabs-master** [comment]
Based on the code, this issue appears to have been fixed - you can see the history here: https://github.com/magento/magento2/commits/2.2/app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/AttributeFilter.php

The addition of the isAttributeShouldNotBeUpdated method is meant to address this issue (I believe).

**Comment by mohith-ecommerce** [comment]
@magento-engcom-team give me 2.2-develop instance to deploy test instance on Magento infrastructure.

**Comment by magento-engcom-team** [comment]
Hi @mohith227. Thank you for your request. I'm working on Magento 2.2-develop instance to deploy test instance for you

**Comment by mohith-ecommerce** [comment]
@magento-engcom-team  this issue is already fixed in 2.3-develop

**Comment by magento-engcom-team** [comment]
Hi @justinsamuel92, @ansukhorukova, @Deep256. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-70217` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by jeroenschipper** [comment]
Can confirm that this is still an issue in Magento 2.3.1. 

Steps to reproduce;
Assign an existing product to a new website.
Try changing product attributes (for example 'name') to 'use default value'. 
Save the product

Expected result: Product attribute is saved with the use default value checkbox.

Actual result: Product attribute is not saved with the use default value checkbox.

Also, the js change submitted by @warrior7789 works for this issue.

**Comment by magento-engcom-team** [comment]
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17995` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nmalecki** [comment]
nmalecki #mm19pl

**Comment by magento-engcom-team** [comment]
@nmalecki thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by nmalecki** [comment]
looks like this issue is already fixed in 2.3-develop

**Comment by hostep** [comment]
Yeah, this was fixed in 2.2.6 I believe, let's close this since nobody is able to provide steps to reproduce the problem.

**Comment by LukSky24** [comment]
I have multistore on Magento 2.2.9 and after installing Cadence module (and also without it) the problem still exist. When i checked "Use deafult value" on one of the stores, and click "Save", page is refreshed and checkbox is still nonchecked. I test it on Magento 2.3.2 and there is no problem, but can someone help me and tell what change in code of M 2.2.9 (without upgrading to 2.3.2) to get this fix?

**Comment by tushhan** [comment]
The issue persist on Magento 2.3.3
![Screenshot 2019-12-18 at 21 28 33](https://user-images.githubusercontent.com/746774/71124720-5f627b00-21dd-11ea-8c23-1ec844737392.png)

**Comment by tushhan** [comment]
The issue persist on Magento 2.3.3 
![Screenshot 2019-12-18 at 21 28 33](https://user-images.githubusercontent.com/746774/71124893-bbc59a80-21dd-11ea-9a40-77793310ed6a.png)

**Comment by BenGlassAtlas** [comment]
@tushhan Can you add steps to replicate on a vanilla instance of Magento 2.3.3 please? If you do this ticket can hopefully be re-opened.

**Comment by webspeaks** [comment]
I am also having this in Magento 2.3.3

**Comment by hostep** [comment]
@webspeaks or @tushhan: please open a new issue with exact steps about how to reproduce, because the bug as reported by @justinsamuel92 should no longer occur in Magento 2.3.3:
> All the checkboxes inside accordions which are not opened/loaded will be reverted to unchecked state.

If you've found a way to trigger it again, more information would be appreciated, thanks!

**Comment by justinsamuel92** [comment]
@hostep @tushhan @BenSpace48  Can you please check for the issue in both a vanilla instance and an upgraded instance? I think this only works in vanilla

**Comment by hostep** [comment]
@justinsamuel92: please give exact steps to reproduce, we can't just at random try something out and hope the bug will trigger (if it still exists), thanks!

**Comment by webspeaks** [comment]
@hostep All I can tell right now is that we migrated from Magento 1.9 to Magento 2.2. The site was running fine till we upgraded to 2.3.3 recently.
Please note that we did all upgrades on time and did necessary upgrades from 2.2 -> -2.3.1 -> 2.3.2 -> 2.3.3
Also the issue occurs even for the opened tabs, like General tab which is always open. Not sure what else I can provide.

**Comment by hostep** [comment]
@webspeaks: it sounds like a different bug then, the initial bugreport was that the "use default value" checkboxes got incorrectly unchecked when the accordion/tab was closed and you saved the entity without opening one of the accordions/tabs.

What I understand from your issue is that you have the "use default value" checkbox unchecked and by checking it and saving, it remains unchecked, is that correct?

It would be super awesome if you could figure out why that happens and try to reproduce this on a vanilla 2.3.3 installation. Take a look at the values stored in the database, maybe you'll notice something strange there.

I would strongly recommend you to open a new issue if you've figured out the steps to reproduce this problem, as it's not the exact same bug as reported in this issue.

**Comment by ioweb-gr** [comment]
I recently upgraded from 

1.9.4.5 to 2.4.1 to 2.4.6-p4 and facing the same issue. Values disappear in the products as soon as I save them in a different store view.

Moreover when checking the Use Default, and save on the next page load the Use Default button is left unchecked.

Very weird behavior 

The same product on 2.4.1 cannot update it's price in website scope and always stays with use default button  checked
