### ISSUE TITLE
Notice: iconv_strpos(): Detected an illegal character in input string in /public_html/lib/Zend/Currency.php on line 199

### ISSUE THREAD

**Issue by farbulous** [magento/magento2#984]
Hello All.

I'm working on a project for the past 2 months.  Everything has been smooth until today.  I'm getting an error in system.log Notice: iconv_strpos(): Detected an illegal character in input string in /home/sitename/public_html/lib/Zend/Currency.php on line 199.

It seems that this error is causing the front end and backend to timeout causing major server load.

Any help will be much appreciated.

**Comment by farbulous** [comment]
Issue found and fixed.  Changed the permission of index.php to 400.  Worked like a charm.

**Comment by vpelipenko** [comment]
Issue is fixed. Closed.

**Comment by onahkenneth** [comment]
@farbulous , Your solution did not fix it for me. Does anyone have an alternative solution
